### ISSUE TITLE
v2rayN导出的配置文件不能用

### ISSUE THREAD

**Issue by qinyuling** [yanue/V2rayU#1]
软件：V2RayN 2.18
core版本: 4.6

配置： websocket + tls

纯tcp的配置没问题。

**Comment by yanue** [comment]
有提醒什么吗?  错误的话 通知栏有提醒

**Comment by qinyuling** [comment]
没有错误提示 后来勾上服务器端版本>4.0的选项之后就ok了
感谢！ issue关掉吧
另外 能否自己手动升级v2ray-core版本？

**Comment by yanue** [comment]
每次启动会自动检测v2ray版本的
