### ISSUE TITLE
实现负载均衡

### ISSUE THREAD

**Issue by JackHansn** [yanue/V2rayU#100]
两个服务器，能不能加个负载均衡功能

**Comment by yanue** [comment]
软件本身实现很麻烦,不考虑,你可以试下将2个服务合并到一个config里面

**Comment by n0thing2speak** [comment]
> 软件本身实现很麻烦,不考虑,你可以试下将2个服务合并到一个config里面

但是软件会强制改成只有一个服务器的配置
