### ISSUE TITLE
M1 PRO macbook无法使用

### ISSUE THREAD

**Issue by raulpeter** [yanue/V2rayU#1001]
1.你正在使用的 V2RayU 和 Mac 版本 ？
Mac 12.0.1
V2RayU 3.2.0

2.你遇到的问题是什么？
安装并授权之后，打击没反应，状态栏没有图标。

**Comment by ellisonchan** [comment]
我也是 M1 pro，安装后无法打开。显示无法验证的来源。![image](https://user-images.githubusercontent.com/20257755/140437628-a48b0746-888d-43fa-a881-e34151bb9f16.jpeg)

**Comment by ellisonchan** [comment]
在设置里选择信任就好了，可以正常使用了。但我的版本是3.0

**Comment by raulpeter** [comment]
3.0正式版可以使用，感谢楼上提示

**Comment by Gold741** [comment]
安装rosetta就行，不要用3.0
Install rosetta and it will be working, do not need install 3.o version

**Comment by zyuchuan** [comment]
可能是刘海屏的原因，我的也是这样，外接一个显示器后就看见了

**Comment by zixiaoyao369** [comment]
请问你们为什么不用小火箭，还有比小火箭好用的吗

**Comment by zixiaoyao369** [comment]
> 请问你们为什么不用小火箭，还有比小火箭好用的吗

**Comment by Gold741** [comment]
> > 请问你们为什么不用小火箭，还有比小火箭好用的吗

喂，你好！ https://github.com/yanue/V2rayU/issues/992

**Comment by zixiaoyao369** [comment]
> > > 请问你们为什么不用小火箭，还有比小火箭好用的吗
> 
> 喂，你好！ #992

？？

**Comment by zixiaoyao369** [comment]
> 我也是 M1 pro，安装后无法打开。显示无法验证的来源。![image](https://user-images.githubusercontent.com/20257755/140437628-a48b0746-888d-43fa-a881-e34151bb9f16.jpeg)

请问你们为什么不用小火箭，还有比小火箭好用的吗

**Comment by zixiaoyao369** [comment]
> 可能是刘海屏的原因，我的也是这样，外接一个显示器后就看见了

请问你们为什么不用小火箭，还有比小火箭好用的吗

**Comment by Gold741** [comment]
看一下https://github.com/yanue/V2rayU/issues/992

**Comment by Vhibli** [comment]
今天刚到的m1p一开始用不了，后来弄着弄着就可以了
