### ISSUE TITLE
macos上无法翻墙，相同配置手机可以

### ISSUE THREAD

**Issue by FutureHere** [yanue/V2rayU#1006]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2rayu3.2
macos 11.6
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
手机软件可以翻墙   相同配置下v2rayu不可以 

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

{
    "log": {
        "error": "",
        "loglevel": "info",
        "access": ""
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": false,
                "auth": "noauth"
            },
            "port": "1080"
        },
        {
            "listen": "127.0.0.1",
            "protocol": "http",
            "settings": {
                "timeout": 360
            },
            "port": "1087"
        }
    ],
    "outbounds": [
        {
            "mux": {
                "enabled": false,
                "concurrency": 8
            },
            "protocol": "vmess",
            "streamSettings": {
                "network": "quic",
                "quicSettings": {
                    "key": "",
                    "header": {
                        "type": "wechat-video"
                    },
                    "security": "aes-128-gcm"
                },
                "security": "none"
            },
            "tag": "proxy",
            "settings": {
                "vnext": [
                    {
                        "address": "",
                        "users": [
                            {
                                "id": "8aada59e-a7d7-47ea-b83a-3c86217676f1",
                                "alterId": 233,
                                "level": 0,
                                "security": "auto"
                            }
                        ],
                        "port": 48848
                    }
                ]
            }
        },
        {
            "tag": "proxy",
            "protocol": "dns",
            "settings": null
        },
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP",
                "userLevel": 0
            }
        },
        {
            "tag": "block",
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "none"
                }
            }
        }
    ],
    "dns": {},
    "routing": {
        "settings": {
            "domainStrategy": "AsIs",
            "rules": []
        }
    },
    "transport": {}
}
4)  请附上出错时软件输出的错误日志。
2021/11/11 17:39:29 [Info] infra/conf/serial: Reading config: config.json
2021/11/11 17:39:29 [Info] app/dns: DNS: created localhost client
Failed to start: main: failed to create server > app/proxyman/outbound: existing tag found: proxy

**Comment by he-erduo** [comment]
我也遇到了这种情况，同样的配置手机端是可以的

**Comment by PrimeMHD** [comment]
同样的情况，v2rayU 3.2, MacOS 12.0.1

**Comment by Jtome46** [comment]
彻底卸载v2rayU 然后重装就可以了 我也碰到了类似问题 现在解决了

**Comment by h0lden96** [comment]
> 彻底卸载v2rayU 然后重装就可以了 我也碰到了类似问题 现在解决了

请问怎么彻底卸载啊，教程里的那串代码看不懂，是要在哪里输入呢？谢谢

**Comment by liranpku** [comment]
下载一个AppCleaner

**Comment by zyuchuan** [comment]
我打开“自动发现代理”就可以了

![截屏2021-11-28 13 18 50](https://user-images.githubusercontent.com/5938776/143730678-302517d5-f1f9-41d8-bcb0-03afe916d6e4.png)

**Comment by stefanielyq** [comment]
同样的问题
pc、ios上都可以正常翻墙 只有mac上不行
上面说的卸载、自动发现代理都试过 解决不了

**Comment by guochunyang** [comment]
> 同样的问题 pc、ios上都可以正常翻墙 只有mac上不行 上面说的卸载、自动发现代理都试过 解决不了

我是直接切换到 qv2ray 了 ...

**Comment by Kathyyyyyyyyy** [comment]
> > 同样的问题 pc、ios上都可以正常翻墙 只有mac上不行 上面说的卸载、自动发现代理都试过 解决不了
> 
> 我是直接切换到 qv2ray 了 ...

我也一样，iOS 可以，Mac 不行。也尝试了卸载，依旧不能用。v3.0.3，v3.2.0都不能用。你说的切换qv2ray是什么意思啊？

**Comment by guochunyang** [comment]
> > > 同样的问题 pc、ios上都可以正常翻墙 只有mac上不行 上面说的卸载、自动发现代理都试过 解决不了
> > 
> > 
> > 我是直接切换到 qv2ray 了 ...
> 
> 我也一样，iOS 可以，Mac 不行。也尝试了卸载，依旧不能用。v3.0.3，v3.2.0都不能用。你说的切换qv2ray是什么意思啊？

https://github.com/Qv2ray/Qv2ray 但这个项目已经废弃了

**Comment by biexingxing** [comment]
相同节点手机能够用，在电脑上用不了。 v2rayu版本是3.2.0

{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "",
          "headers": {
            "host": ""
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "",
            "users": [
              {
                "id": "",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 21101
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

**Comment by chrisdylan** [comment]
> 我打开“自动发现代理”就可以了
> 
> ![截屏2021-11-28 13 18 50](https://user-images.githubusercontent.com/5938776/143730678-302517d5-f1f9-41d8-bcb0-03afe916d6e4.png)

哇这个真的可以 我有个网页一直打不开 其他都可以 问了我们技术也不知道咋解决 试了你的这个办法真的就可以啦 太感谢了！！！
