### ISSUE TITLE
v2ray Mac上一直在崩溃

### ISSUE THREAD

**Issue by laozhangboop** [yanue/V2rayU#1007]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               V2rayU [1184]
Path:                  /Applications/V2rayU.app/Contents/MacOS/V2rayU
Identifier:            net.yanue.V2rayU
Version:               3.2.0 (3.2.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-11-08 19:24:57.4677 +0800
OS Version:            macOS 12.0 (21A344)
Report Version:        12
Anonymous UUID:        E111FF99-619D-5B16-3426-6AFC7A50135D

Sleep/Wake UUID:       715BE79C-2199-4837-9743-6D51574C5EAA

Time Awake Since Boot: 750 seconds
Time Since Wake:       496 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010454e690
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [1184]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   V2rayU                        	       0x10454e690 0x104544000 + 42640
1   V2rayU                        	       0x10454e31c 0x104544000 + 41756
2   V2rayU                        	       0x10454e6dc 0x104544000 + 42716
3   CoreFoundation                	       0x1c18b8580 0x1c1840000 + 492928
4   AppKit                        	       0x1c43e64ec 0x1c43c8000 + 124140
5   AppKit                        	       0x1c43da7ac 0x1c43c8000 + 75692
6   AppKit                        	       0x1c43d9d2c 0x1c43c8000 + 73004
7   AppKit                        	       0x1c43d995c 0x1c43c8000 + 72028
8   AppKit                        	       0x1c43d972c 0x1c43c8000 + 71468
9   AppKit                        	       0x1c43cb4d4 0x1c43c8000 + 13524
10  V2rayU                        	       0x104549e4c 0x104544000 + 24140
11  dyld                          	       0x1047890f4 0x104784000 + 20724

Thread 1:
0   libsystem_pthread.dylib       	       0x1c17f42bc 0x1c17f2000 + 8892

Thread 2:
0   libsystem_pthread.dylib       	       0x1c17f42bc 0x1c17f2000 + 8892

Thread 3::  Dispatch queue: com.apple.root.background-qos
0   libsystem_kernel.dylib        	       0x1c17c5b04 0x1c17bc000 + 39684
1   Swifter                       	       0x104928874 0x10490c000 + 116852
2   Swifter                       	       0x104928f14 0x10490c000 + 118548
3   libdispatch.dylib             	       0x1c1638f60 0x1c1637000 + 8032
4   libdispatch.dylib             	       0x1c163acac 0x1c1637000 + 15532
5   libdispatch.dylib             	       0x1c164c53c 0x1c1637000 + 87356
6   libdispatch.dylib             	       0x1c164cc58 0x1c1637000 + 89176
7   libsystem_pthread.dylib       	       0x1c17f5574 0x1c17f2000 + 13684
8   libsystem_pthread.dylib       	       0x1c17f42c4 0x1c17f2000 + 8900

Thread 4::  Dispatch queue: com.apple.NSURLSession-work
0   AppSSOCore                    	       0x1cccdbdf4 0x1cccda000 + 7668
1   CFNetwork                     	       0x1c665d008 0x1c6457000 + 2121736
2   CFNetwork                     	       0x1c665d008 0x1c6457000 + 2121736
3   CFNetwork                     	       0x1c656c67c 0x1c6457000 + 1136252
4   CFNetwork                     	       0x1c646e2f0 0x1c6457000 + 94960
5   CFNetwork                     	       0x1c651bd1c 0x1c6457000 + 806172
6   CFNetwork                     	       0x1c646e1f4 0x1c6457000 + 94708
7   CFNetwork                     	       0x1c646e058 0x1c6457000 + 94296
8   CFNetwork                     	       0x1c646d8b8 0x1c6457000 + 92344
9   CFNetwork                     	       0x1c650d670 0x1c6457000 + 747120
10  libdispatch.dylib             	       0x1c1638f60 0x1c1637000 + 8032
11  libdispatch.dylib             	       0x1c163acac 0x1c1637000 + 15532
12  libdispatch.dylib             	       0x1c1642430 0x1c1637000 + 46128
13  libdispatch.dylib             	       0x1c1642fd8 0x1c1637000 + 49112
14  libdispatch.dylib             	       0x1c164d808 0x1c1637000 + 92168
15  libsystem_pthread.dylib       	       0x1c17f55b0 0x1c17f2000 + 13744
16  libsystem_pthread.dylib       	       0x1c17f42c4 0x1c17f2000 + 8900

Thread 5:: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib        	       0x1c17c1120 0x1c17bc000 + 20768
1   libsystem_pthread.dylib       	       0x1c17f9ab4 0x1c17f2000 + 31412
2   libc++.1.dylib                	       0x1c1747e78 0x1c173e000 + 40568
3   JavaScriptCore                	       0x1da9b8ec0 0x1d981a000 + 18476736
4   JavaScriptCore                	       0x1da9b897c 0x1d981a000 + 18475388
5   JavaScriptCore                	       0x1da9b9db0 0x1d981a000 + 18480560
6   libsystem_pthread.dylib       	       0x1c17f94ec 0x1c17f2000 + 29932
7   libsystem_pthread.dylib       	       0x1c17f42d0 0x1c17f2000 + 8912

Thread 6:: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib        	       0x1c17c1120 0x1c17bc000 + 20768
1   libsystem_pthread.dylib       	       0x1c17f9ab4 0x1c17f2000 + 31412
2   JavaScriptCore                	       0x1da99d2b0 0x1d981a000 + 18363056
3   libsystem_pthread.dylib       	       0x1c17f94ec 0x1c17f2000 + 29932
4   libsystem_pthread.dylib       	       0x1c17f42d0 0x1c17f2000 + 8912

Thread 7:
0   libsystem_pthread.dylib       	       0x1c17f42bc 0x1c17f2000 + 8892

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000001   x1: 0x0000000000000001   x2: 0x000000021b0b8a68   x3: 0x0000000000000001
    x4: 0x00000001047e66c8   x5: 0x000000012904a590   x6: 0x0000000000000006   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x000000030000078c  x11: 0x000000000000007f
   x12: 0x0000000000000042  x13: 0x00000001288e6e00  x14: 0x000000016b8bab40  x15: 0x000000021a2ed450
   x16: 0x00000001d2b91178  x17: 0x7d4b0001c1862cc0  x18: 0x0000000130083940  x19: 0x40000001286bd410
   x20: 0x0000000129014810  x21: 0xc000000000000083  x22: 0x00000001286bd390  x23: 0x000000016b8bb010
   x24: 0x40000001286bd450  x25: 0x000000016b8bb020  x26: 0x00000001286b9750  x27: 0xc00000000000002e
   x28: 0x0000000000000001   fp: 0x000000016b8bb110   lr: 0x000000010454e31c
    sp: 0x000000016b8baff0   pc: 0x000000010454e690 cpsr: 0x60000000
   far: 0x0000000104ade924  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x104544000 -        0x10461ffff net.yanue.V2rayU (3.2.0) <6974e638-06e6-34c9-a067-804e4fad3234> /Applications/V2rayU.app/Contents/MacOS/V2rayU
       0x1c1840000 -        0x1c1d83fff com.apple.CoreFoundation (6.9) <d1b80ad3-9834-3729-b837-b8475ca00b58> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1c43c8000 -        0x1c5276fff com.apple.AppKit (6.9) <265eb782-1005-3e66-b44d-b9e8ccd9cce8> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x104784000 -        0x1047e3fff dyld (*) <c67eec77-8841-3ee4-921e-e3ac712475ad> /usr/lib/dyld
       0x1c17f2000 -        0x1c17fefff libsystem_pthread.dylib (*) <aa39ff66-b3f0-3777-99bc-f4a4c5cbd566> /usr/lib/system/libsystem_pthread.dylib
       0x1c17bc000 -        0x1c17f1fff libsystem_kernel.dylib (*) <17550b77-d255-389a-b779-906af75314b6> /usr/lib/system/libsystem_kernel.dylib
       0x10490c000 -        0x1049abfff org.cocoapods.Swifter (1.4.7) <72d57037-09cc-3cb9-ba23-e3dcea9fa0ac> /Applications/V2rayU.app/Contents/Frameworks/Swifter.framework/Versions/A/Swifter
       0x1c1637000 -        0x1c167dfff libdispatch.dylib (*) <9c4116f5-b8eb-3a00-b4b5-54af6a76f66b> /usr/lib/system/libdispatch.dylib
       0x1cccda000 -        0x1cccf6fff com.apple.AppSSOCore (1.0) <3fa1c1fd-d0ff-3e9f-ba8a-e1a2c6a80e05> /System/Library/PrivateFrameworks/AppSSOCore.framework/Versions/A/AppSSOCore
       0x1c6457000 -        0x1c690efff com.apple.CFNetwork (1323) <ed54fdbe-fd7c-3a83-b093-6f569a0229f0> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
       0x1c173e000 -        0x1c17a1fff libc++.1.dylib (*) <20fbe382-cc21-324e-8813-c84b94cc04ef> /usr/lib/libc++.1.dylib
       0x1d981a000 -        0x1daae1fff com.apple.JavaScriptCore (17612) <5039068d-4c27-3bcf-9c18-a17c6e159c6f> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=971.2M resident=0K(0%) swapped_out_or_unallocated=971.2M(100%)
Writable regions: Total=927.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=927.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          496K       23 
CoreAnimation                       16K        1 
CoreGraphics                        32K        2 
CoreUI image data                   32K        1 
Dispatch continuations            80.0M        1 
Foundation                          16K        1 
JS JIT generated code            512.0M        3 
Kernel Alloc Once                   32K        1 
MALLOC                            69.2M       33 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                        1.0G        4 
WebKit Malloc                    134.2M        9 
__AUTH                            2199K      226 
__AUTH_CONST                      16.7M      399 
__DATA                            10.7M      397 
__DATA_CONST                      14.7M      411 
__DATA_DIRTY                      1409K      158 
__FONT_DATA                          4K        1 
__LINKEDIT                       569.5M       11 
__OBJC_CONST                      2499K      191 
__OBJC_RO                         81.5M        1 
__OBJC_RW                         3008K        1 
__TEXT                           401.7M      428 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                      144.9M       18 
shared memory                      848K       14 
===========                     =======  ======= 
TOTAL                              3.2G     2365 
TOTAL, minus reserved VM space     3.1G     2365 

-----------
Full Report
-----------

{"app_name":"V2rayU","timestamp":"2021-11-08 19:24:57.00 +0800","app_version":"3.2.0","slice_uuid":"6974e638-06e6-34c9-a067-804e4fad3234","build_version":"3.2.0","platform":1,"bundleID":"net.yanue.V2rayU","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0 (21A344)","incident_id":"62D449DC-6F43-45C3-9634-4A38DF5D38CA","name":"V2rayU"}
{
  "uptime" : 750,
  "procLaunch" : "2021-11-08 19:24:57.2080 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 18222057899,
  "coalitionID" : 947,
  "osVersion" : {
    "train" : "macOS 12.0",
    "build" : "21A344",
    "releaseType" : "User"
  },
  "captureTime" : "2021-11-08 19:24:57.4677 +0800",
  "incident" : "62D449DC-6F43-45C3-9634-4A38DF5D38CA",
  "bug_type" : "309",
  "pid" : 1184,
  "procExitAbsTime" : 18228193671,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "V2rayU",
  "procPath" : "\/Applications\/V2rayU.app\/Contents\/MacOS\/V2rayU",
  "bundleInfo" : {"CFBundleShortVersionString":"3.2.0","CFBundleVersion":"3.2.0","CFBundleIdentifier":"net.yanue.V2rayU"},
  "storeInfo" : {"deviceIdentifierForVendor":"D30C0054-430A-5F41-A70B-E996D9600606","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "net.yanue.V2rayU",
  "crashReporterKey" : "E111FF99-619D-5B16-3426-6AFC7A50135D",
  "wakeTime" : 496,
  "sleepWakeUUID" : "715BE79C-2199-4837-9743-6D51574C5EAA",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x000000010454e690","rawCodes":[1,4367640208],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":1184},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":15439,"threadState":{"x":[{"value":1},{"value":1},{"value":9043675752},{"value":1},{"value":4370360008},{"value":4983137680},{"value":6},{"value":0},{"value":0},{"value":0},{"value":12884903820},{"value":127},{"value":66},{"value":4975390208},{"value":6099282752},{"value":9029211216},{"value":7830311288},{"value":9028309885536054464},{"value":5100812608},{"value":4611686023400510480},{"value":4982917136},{"value":13835058055282163843},{"value":4973122448},{"value":6099283984},{"value":4611686023400510544},{"value":6099284000},{"value":4973107024},{"value":13835058055282163758},{"value":1}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4367639324},"cpsr":{"value":1610612736},"fp":{"value":6099284240},"sp":{"value":6099283952},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4367640208,"matchesCrashFrame":1},"far":{"value":4373473572}},"queue":"com.apple.main-thread","frames":[{"imageOffset":42640,"imageIndex":0},{"imageOffset":41756,"imageIndex":0},{"imageOffset":42716,"imageIndex":0},{"imageOffset":492928,"imageIndex":1},{"imageOffset":124140,"imageIndex":2},{"imageOffset":75692,"imageIndex":2},{"imageOffset":73004,"imageIndex":2},{"imageOffset":72028,"imageIndex":2},{"imageOffset":71468,"imageIndex":2},{"imageOffset":13524,"imageIndex":2},{"imageOffset":24140,"imageIndex":0},{"imageOffset":20724,"imageIndex":3}]},{"id":15446,"frames":[{"imageOffset":8892,"imageIndex":4}]},{"id":15447,"frames":[{"imageOffset":8892,"imageIndex":4}]},{"id":15454,"queue":"com.apple.root.background-qos","frames":[{"imageOffset":39684,"imageIndex":5},{"imageOffset":116852,"imageIndex":6},{"imageOffset":118548,"imageIndex":6},{"imageOffset":8032,"imageIndex":7},{"imageOffset":15532,"imageIndex":7},{"imageOffset":87356,"imageIndex":7},{"imageOffset":89176,"imageIndex":7},{"imageOffset":13684,"imageIndex":4},{"imageOffset":8900,"imageIndex":4}]},{"id":15460,"queue":"com.apple.NSURLSession-work","frames":[{"imageOffset":7668,"imageIndex":8},{"imageOffset":2121736,"imageIndex":9},{"imageOffset":2121736,"imageIndex":9},{"imageOffset":1136252,"imageIndex":9},{"imageOffset":94960,"imageIndex":9},{"imageOffset":806172,"imageIndex":9},{"imageOffset":94708,"imageIndex":9},{"imageOffset":94296,"imageIndex":9},{"imageOffset":92344,"imageIndex":9},{"imageOffset":747120,"imageIndex":9},{"imageOffset":8032,"imageIndex":7},{"imageOffset":15532,"imageIndex":7},{"imageOffset":46128,"imageIndex":7},{"imageOffset":49112,"imageIndex":7},{"imageOffset":92168,"imageIndex":7},{"imageOffset":13744,"imageIndex":4},{"imageOffset":8900,"imageIndex":4}]},{"id":15464,"name":"JavaScriptCore bmalloc scavenger","frames":[{"imageOffset":20768,"imageIndex":5},{"imageOffset":31412,"imageIndex":4},{"imageOffset":40568,"imageIndex":10},{"imageOffset":18476736,"imageIndex":11},{"imageOffset":18475388,"imageIndex":11},{"imageOffset":18480560,"imageIndex":11},{"imageOffset":29932,"imageIndex":4},{"imageOffset":8912,"imageIndex":4}]},{"id":15465,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":20768,"imageIndex":5},{"imageOffset":31412,"imageIndex":4},{"imageOffset":18363056,"imageIndex":11},{"imageOffset":29932,"imageIndex":4},{"imageOffset":8912,"imageIndex":4}]},{"id":15467,"frames":[{"imageOffset":8892,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4367597568,
    "CFBundleShortVersionString" : "3.2.0",
    "CFBundleIdentifier" : "net.yanue.V2rayU",
    "size" : 901120,
    "uuid" : "6974e638-06e6-34c9-a067-804e4fad3234",
    "path" : "\/Applications\/V2rayU.app\/Contents\/MacOS\/V2rayU",
    "name" : "V2rayU",
    "CFBundleVersion" : "3.2.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7541620736,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "d1b80ad3-9834-3729-b837-b8475ca00b58",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1853"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7587266560,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15396864,
    "uuid" : "265eb782-1005-3e66-b44d-b9e8ccd9cce8",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2103.13.10"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4369956864,
    "size" : 393216,
    "uuid" : "c67eec77-8841-3ee4-921e-e3ac712475ad",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7541301248,
    "size" : 53248,
    "uuid" : "aa39ff66-b3f0-3777-99bc-f4a4c5cbd566",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7541080064,
    "size" : 221184,
    "uuid" : "17550b77-d255-389a-b779-906af75314b6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4371562496,
    "CFBundleShortVersionString" : "1.4.7",
    "CFBundleIdentifier" : "org.cocoapods.Swifter",
    "size" : 655360,
    "uuid" : "72d57037-09cc-3cb9-ba23-e3dcea9fa0ac",
    "path" : "\/Applications\/V2rayU.app\/Contents\/Frameworks\/Swifter.framework\/Versions\/A\/Swifter",
    "name" : "Swifter",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7539486720,
    "size" : 290816,
    "uuid" : "9c4116f5-b8eb-3a00-b4b5-54af6a76f66b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7730995200,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.AppSSOCore",
    "size" : 118784,
    "uuid" : "3fa1c1fd-d0ff-3e9f-ba8a-e1a2c6a80e05",
    "path" : "\/System\/Library\/PrivateFrameworks\/AppSSOCore.framework\/Versions\/A\/AppSSOCore",
    "name" : "AppSSOCore",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7621406720,
    "CFBundleShortVersionString" : "1323",
    "CFBundleIdentifier" : "com.apple.CFNetwork",
    "size" : 4947968,
    "uuid" : "ed54fdbe-fd7c-3a83-b093-6f569a0229f0",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/Versions\/A\/CFNetwork",
    "name" : "CFNetwork",
    "CFBundleVersion" : "1323"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7540563968,
    "size" : 409600,
    "uuid" : "20fbe382-cc21-324e-8813-c84b94cc04ef",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7944118272,
    "CFBundleShortVersionString" : "17612",
    "CFBundleIdentifier" : "com.apple.JavaScriptCore",
    "size" : 19693568,
    "uuid" : "5039068d-4c27-3bcf-9c18-a17c6e159c6f",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/Versions\/A\/JavaScriptCore",
    "name" : "JavaScriptCore",
    "CFBundleVersion" : "17612.1.29.5"
  }
],
  "sharedCache" : {
  "base" : 7538130944,
  "size" : 3046227968,
  "uuid" : "bf8bef8d-8074-3dd6-8c9b-cc48eb279f34"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=971.2M resident=0K(0%) swapped_out_or_unallocated=971.2M(100%)\nWritable regions: Total=927.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=927.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          496K       23 \nCoreAnimation                       16K        1 \nCoreGraphics                        32K        2 \nCoreUI image data                   32K        1 \nDispatch continuations            80.0M        1 \nFoundation                          16K        1 \nJS JIT generated code            512.0M        3 \nKernel Alloc Once                   32K        1 \nMALLOC                            69.2M       33 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                        1.0G        4 \nWebKit Malloc                    134.2M        9 \n__AUTH                            2199K      226 \n__AUTH_CONST                      16.7M      399 \n__DATA                            10.7M      397 \n__DATA_CONST                      14.7M      411 \n__DATA_DIRTY                      1409K      158 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       569.5M       11 \n__OBJC_CONST                      2499K      191 \n__OBJC_RO                         81.5M        1 \n__OBJC_RW                         3008K        1 \n__TEXT                           401.7M      428 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      144.9M       18 \nshared memory                      848K       14 \n===========                     =======  ======= \nTOTAL                              3.2G     2365 \nTOTAL, minus reserved VM space     3.1G     2365 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000153
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000068
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "618455f04b3765609b8b78c2"
      },
      "deploymentId" : 240000311
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6182cb1c4b3765609b8b76c7"
      },
      "deploymentId" : 240000254
    }
  ],
  "experiments" : [

  ]
}
}

请大佬们帮我解决一下这个问题，我是个小白。  谢谢

**Comment by yuanhuikai** [comment]
@laozhangboop 请问你是怎么解决的呢
