### ISSUE TITLE
关于M1 运行 无法运行/速度慢问题 解决方案

### ISSUE THREAD

**Issue by ltto** [yanue/V2rayU#1008]
问题发现
1.问题
 查看日志
```
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
```
得知现在的软件架构是amd的 并不是M1的arm

2.解决方案
替换 ~/.V2rauU/v2ray-core 文件夹的v2ray程序和xray程序 
查看readme.md得知 主程序源码地址 https://github.com/XTLS/Xray-core

替换后看看日志
```
Xray 1.5.0 (Xray, Penetrates Everything.) Custom (go1.17.2 darwin/arm64)
A unified platform for anti-censorship.
```
替换为arm64架构

**Comment by xihrni** [comment]
我好像不行，更换了还是显示 
`Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)`
每次只有开关的一瞬间可以访问，然后就不行了

**Comment by ltto** [comment]
> 我好像不行，更换了还是显示 `Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)` 每次只有开关的一瞬间可以访问，然后就不行了
你确定是用 golang arm64/darwin  版本 编译的源码吗

**Comment by zixiaoyao369** [comment]
请问你们为什么不用小火箭，还有比小火箭好用的吗

**Comment by eunrui** [comment]
> 

你替换的可能是Resource下面的 他说的这个是隐藏的文件夹 /Users/eunrui/.V2rauU/v2ray-core command+shift+. 就看到了

**Comment by wyd19981006** [comment]
> > 
> 
> 你替换的可能是Resource下面的 他说的这个是隐藏的文件夹 /Users/eunrui/.V2rauU/v2ray-core command+shift+. 就看到了

你好，能请问替换的具体步骤么，我在 https://github.com/XTLS/Xray-core 没找到需要替换的那两个文件，感谢

**Comment by eunrui** [comment]
> > > 
> > 
> > 
> > 你替换的可能是Resource下面的 他说的这个是隐藏的文件夹 /Users/eunrui/.V2rauU/v2ray-core command+shift+. 就看到了
> 
> 你好，能请问替换的具体步骤么，我在 https://github.com/XTLS/Xray-core 没找到需要替换的那两个文件，感谢

https://github.com/v2fly/v2ray-core/releases
https://github.com/XTLS/Xray-core/releases

**Comment by ltto** [comment]
需要go build

**Comment by wyd19981006** [comment]
> > > > 
> > > 
> > > 
> > > 你替换的可能是Resource下面的 他说的这个是隐藏的文件夹 /Users/eunrui/.V2rauU/v2ray-core command+shift+. 就看到了
> > 
> > 
> > 你好，能请问替换的具体步骤么，我在 https://github.com/XTLS/Xray-core 没找到需要替换的那两个文件，感谢
> 
> https://github.com/v2fly/v2ray-core/releases https://github.com/XTLS/Xray-core/releases
感谢，请问下最新的3.2版本不是已经换成了xray程序么，为什么日志输出的还是 amd版本

**Comment by xihrni** [comment]
> > 我好像不行，更换了还是显示 `Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)` 每次只有开关的一瞬间可以访问，然后就不行了
> > 你确定是用 golang arm64/darwin  版本 编译的源码吗

我已经解决了，原来下载的核心包只有一个xray程序，要复制一份改为v2ray文件一起替换进去就可以了，显示为 (go1.16.2 darwin/amd64)

**Comment by ltto** [comment]
烦死了 我要关了这个issues 谁爱解决谁解决
