### ISSUE TITLE
新版本找不到pac.js文件,我想更改pac文件,找不到文件在哪了

### ISSUE THREAD

**Issue by LastStranger** [yanue/V2rayU#1012]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
是的
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
我想更改pac文件,不单单想要添加用户自定义URL
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
不需要提供配置
```javascript
    // 在这里附上配置信息
不需要
```
4)  请附上出错时软件输出的错误日志。
无
```javascript
    // 在这里附上日志信息
无
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
文件路径 `~/.V2rayU/pac/proxy.js` 但是修改了没用,需要用pac设置界面进行设置
