### ISSUE TITLE
macos 订阅正常，但不能连到外网

### ISSUE THREAD

**Issue by Wyattwwwww** [yanue/V2rayU#1015]
1. 你正在使用的 V2RayU 和 Mac 版本 ？
v2rayu3.2
macos 11.2.1

2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
同样的订阅在别的macos上可以用，在这台mac上显示订阅成功，却不能访问外网

3. 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/",
          "headers": {
            "host": "hk01.fq.mk"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "hk01.fq.mk",
            "users": [
              {
                "id": "f8c11150-e69e-3b1d-b82b-d33bfa4ff76c",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 80
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

4. 请附上出错时软件输出的错误日志。
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2021/12/12 21:22:08 [Info] infra/conf/serial: Reading config: config.json
2021/12/12 21:22:08 [Info] app/dns: DNS: created localhost client
2021/12/12 21:22:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2021/12/12 21:30:40 [Info] infra/conf/serial: Reading config: config.json
2021/12/12 21:30:40 [Info] app/dns: DNS: created localhost client
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2021/12/12 21:30:50 [Info] infra/conf/serial: Reading config: config.json
2021/12/12 21:30:50 [Info] app/dns: DNS: created localhost client
2021/12/12 21:30:50 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by zhengjiawei001** [comment]
更新3.0之后，提示config not found,也找不到之前订阅的官网了

**Comment by Wyattwwwww** [comment]
是端口被占用的问题，已解决

**Comment by Henrfnfjfue** [comment]
想请教一下端口问题要怎么解决
