### ISSUE TITLE
如何直接更改config？

### ISSUE THREAD

**Issue by ghost** [yanue/V2rayU#1018]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.2.3 mbp2015 big sur

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
PAC模式打不开一些网站（比如alibabacloud和测速网站fast.com）。但是配置里proxy, direct,block三栏需要手动填入domain和ip，很麻烦，将fast.com加入proxy，依然无法打开。
manual mode如何配置？怎么改config文件？

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": " ",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": " "
    },
    {
      "listen": " ",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": " "
    }
  ],
  "outbounds": [
    {
      "protocol": "socks",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "servers": [
          {
            "address":  "",
            "users": [],
            "port":  
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "ip": [
            "geoip:cn"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {}
}
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by skyrockgz** [comment]
我也想知道如何直接修改配置文件，我遇到的问题是，allowInsecure选项无效
