### ISSUE TITLE
关于Pac设置的问题

### ISSUE THREAD

**Issue by xiebruce** [yanue/V2rayU#102]
解决了，原因我先说答案：
出现这个问题的原因，是因为我输入pac后没有点保存按钮，因为那个按钮在上边，我只是以为它是用来更新保存gfwlist的。。。

添加的规则就是用双竖杠就行，比如：
```
|| wireguard.com
|| github.io
|| quoracdn.net
```
个人添加的，会被保存在：
```
/Applications/V2rayU.app/Contents/Resources/pac/user-rule.txt
```
保存后就会添加到`pac.js`的最开头，不需要切换开关也不需要退出软件再打开。

---
**原问题：**

@yanue 大佬抽时间看看问题呀，谢谢了！

macOS: `10.14.4 (18E226)`
V2rayU: `1.3.2`

1、添加了自己的pac规则后，需要把V2rayU关闭再打开吗？(不是关软件，是软件上的那个开关)

2、规则到底是怎样添加的？我按这个规则添加，就是两个竖杠开头，怎么不行呢？
![image](https://user-images.githubusercontent.com/13575500/59142296-91a14d80-89ee-11e9-8012-7a38ca6ec475.png)

我看pac文件里大部分也是双竖杠开头呀：
![image](https://user-images.githubusercontent.com/13575500/59142355-b518c800-89ef-11e9-9c05-c9c44263cb45.png)

我添加的pac：
![image](https://user-images.githubusercontent.com/13575500/59142261-f27c5600-89ed-11e9-880e-a40ac04c13f4.png)

看，全加载不了：
![image](https://user-images.githubusercontent.com/13575500/59142258-dbd5ff00-89ed-11e9-83b9-f5ac31984f67.png)

我全局访问quora没有任何问题，但pac我这么添加就不行，大佬给个例子呗，其实也不用例子，就加`quoracdn.net`吧。

3、用户添加的pac，点View Pac File查看，是否能看到？我感觉看不到呀。

**Comment by albertjone** [comment]
hi, how u solved the problem

**Comment by HaiyiMei** [comment]
thx for your solution

**Comment by imxiaolong** [comment]
Thanks for the explanation.

**Comment by HS327** [comment]
Thanks
