### ISSUE TITLE
3.2版本VLESS配置中allowinsecure选项保存后不生效。

### ISSUE THREAD

**Issue by xxsscode** [yanue/V2rayU#1020]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.2 。M1 max 12.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
VLESS配置中allowinsecure选项保存后不生效。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by skyrockgz** [comment]
相同的情况我也遇到了，不管是手动模式还是导入模式，修改了allowinsecure为允许（选中）后，保存虽然提示成功了，但切换节点再切换回来看，还是不允许的状态

**Comment by skyrockgz** [comment]
另外请问服务器设置的节点信息保存在哪个目录下？想直接修改节点配置信息试试，
只找到了config.json文件，没找到节点

**Comment by altairbow** [comment]
同样的问题，3.3也有
