### ISSUE TITLE
启动和退出以及更改模式，更改配置都会有弹窗提示 修改网络配置的密码校验。

### ISSUE THREAD

**Issue by frankdqsc** [yanue/V2rayU#1021]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
    v3.2.0  MacOS12.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    启动和退出以及更改模式，更改配置都会有 修改网络配置的密码校验。但是不输入密码直接点取消也可通过校验。

**Comment by funchs** [comment]
同样的情况
same situation

**Comment by LiHang-CN** [comment]
v3.2.0 MacOS12.4，the same situation occurs
v3.2.0 MacOS12.4，出现了相同的情况
