### ISSUE TITLE
点击订阅设置，pac设置时，直接闪退了。毕现。

### ISSUE THREAD

**Issue by qingdi** [yanue/V2rayU#1023]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
最新版 3.2
mac 12.1 (21C52)

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
点击订阅设置，pac设置时，直接闪退了。毕现。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by kt7a** [comment]
+1
除了点击“订阅”、“Pac..."闪退外，点击“Preference"也会闪退；
操作系统： MacOS Mojave 10.14.6

**Comment by Rock981119** [comment]
相同的问题, 不知道如何解决

**Comment by Rock981119** [comment]
删了这两行重启软件就好了
```
rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist
```

**Comment by kt7a** [comment]
> 删了这两行重启软件就好了
> 
> ```
> rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist
> ```

试了下，不闪退了， 谢谢 🙏

**Comment by shizhi3620** [comment]
闪退的，试试以下步骤(亲测有效)：

退出V2rayU
rm ~/Library/Preferences/net.yanue.V2rayU.plist
重新启动V2rayU

**Comment by wentmac** [comment]
> 

好使了，感谢

**Comment by wentmac** [comment]
> 



> 删了这两行重启软件就好了
> 
> ```
> rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist
> ```

thanks，It's worked after delete plist file

**Comment by OCer** [comment]
一堆坑货。。。 删了后所有的配置、数据和服务器全没了。。 没一个人说  害我删了 东西全没了 草

**Comment by OCer** [comment]
一堆坑货。。。 删了后所有的配置、数据和服务器全没了。。 没一个人说  害我删了 东西全没了 草

**Comment by sanzyuan** [comment]
mark

**Comment by Silence566** [comment]
感谢楼上说明，试了下确实有用，不闪退了
