### ISSUE TITLE
When can v2ray adapt to mac m1

### ISSUE THREAD

**Issue by westines** [yanue/V2rayU#1024]

**Comment by westines** [comment]
![CleanShot 2022-01-13 at 19 14 01](https://user-images.githubusercontent.com/24730865/149320194-df472241-43fe-4617-a4c3-fd9c2a4af3ee.jpg)
I have waited too long, and now it has always been the intel version.

**Comment by chinayin** [comment]
也遇到同样问题，设置里配置安全允许可用就好了

**Comment by qdpoboy** [comment]
> 也遇到同样问题，设置里配置安全允许可用就好了

什么意思，新手麻烦大佬详细指导下

**Comment by wujingke** [comment]
![image](https://user-images.githubusercontent.com/565778/149616192-8323dd63-6041-4acd-a2b4-1d040ebfe6bf.png)

**Comment by Doormaster** [comment]
我也是同样问题，有解决方法了吗？

**Comment by chinayin** [comment]
- macos新版本无法打开程序问题
关机后按住指纹识别按键，进入安全引导，设置系统打开app安全

@Doormaster @qdpoboy

**Comment by youkaichao** [comment]
@chinayin 我已经把启动安全性实用工具 https://support.apple.com/zh-cn/HT208198 关掉了，依然打不开程序（点了之后没有图标出现）

**Comment by youkaichao** [comment]
我根据 https://www.v2fly.org/developer/intro/compile.html 这里的脚本构建部分，用 ``./user-package.sh darwin arm64 nosource nodat noconf``构建成功了，有需要的朋友可以自取：https://cloud.tsinghua.edu.cn/f/3caf8e05c7e946d4949a/

**Comment by n0thing2speak** [comment]
> 

#1085 自己改改就行了

**Comment by n0thing2speak** [comment]
> 我根据 https://www.v2fly.org/developer/intro/compile.html 这里的脚本构建部分，用 `./user-package.sh darwin arm64 nosource nodat noconf`构建成功了，有需要的朋友可以自取：https://cloud.tsinghua.edu.cn/f/3caf8e05c7e946d4949a/

v2不行，要用xray
