### ISSUE TITLE
新款pro 芯片M1 pro使用最新v2rayu打不开

### ISSUE THREAD

**Issue by matthewhan-95** [yanue/V2rayU#1025]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU版本：3.2.0
Mac版本：2021 款pro 芯片M1 pro
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
安装最新v2rayu 软件打不开 卸载重装 重启都不行
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by flashing** [comment]
同款使用没问题。

**Comment by matthewhan-95** [comment]
> 同款使用没问题。

系统版本是多少的

**Comment by Doormaster** [comment]
我也一样问题，等个解决方案啊

**Comment by qdpoboy** [comment]
同，怎么回事，点击没任何反应

**Comment by deng00** [comment]
要安装 rosetta
`softwareupdate --install-rosetta`

**Comment by matthewhan-95** [comment]
突然就好了 感觉是因为软件刘海适配的问题导致很多软件图标隐藏了 可以尝试 关闭菜单栏显示的一些应用图标，看看v2ray的图标是否会显现出来

**Comment by javaxxl** [comment]
同样的问题，系统mac os monterey 12.2， V2rayU 3.2 。将dmg 拖入到application后，没有反应（没有启动安装）。
尝试一下方法，没有解决：
“要安装 rosetta
softwareupdate --install-rosetta”。

请大佬帮忙指点一下，谢谢。

**Comment by javaxxl** [comment]
> > 同款使用没问题。
> 
> 系统版本是多少的

系统12.2

**Comment by javaxxl** [comment]
> 同，怎么回事，点击没任何反应

同样，投入到application后，没有反应（没有启动安装）

**Comment by shelltea** [comment]
同样的问题，用下面的命令解决了。
```
# permission
sudo chown -R $USER  ~/.V2rayU/
sudo chmod -R 777 ~/.V2rayU/

# root permission
cd  ~/.V2rayU/
cmd="./unzip.sh"
sudo chown root:admin ${cmd}
sudo chmod a+rx ${cmd}
sudo chmod +s ${cmd}

cmd="./V2rayUTool"
sudo chown root:admin ${cmd}
sudo chmod a+rx ${cmd}
sudo chmod +s ${cmd}

cmd="./V2rayUHelper"
sudo chown root:admin ${cmd}
sudo chmod a+rx ${cmd}
sudo chmod +s ${cmd}

echo 'done'
```

**Comment by kfcceo** [comment]
怎么打不开，一直用的好好的

**Comment by matthewhan-95** [comment]
> 怎么打不开，一直用的好好的
都是新版mac刘海问题导致的 这个app没有软件启动界面 只有菜单栏显示图标才能进行设置  新版mac因为刘海屏幕问题 菜单栏图标过多 导致只显示前几个 剩余的都会隐藏 所以好多都是没有看到软件启动界面 以及图标没有显示 就会误以为没有启动

**Comment by matthewhan-95** [comment]
> 怎么打不开，一直用的好好的

都是新版mac刘海问题导致的 这个app没有软件启动界面 只有菜单栏显示图标才能进行设置 新版mac因为刘海屏幕问题 菜单栏图标过多 导致只显示前几个 剩余的都会隐藏 所以好多都是没有看到软件启动界面 以及图标没有显示 就会误以为没有启动

**Comment by supermisscat** [comment]
我今天也折腾了很久，方法都试过了 最后通过彻底卸载，就好了

https://github.com/yanue/V2rayU/blob/master/README.md#%E5%BD%BB%E5%BA%95%E5%8D%B8%E8%BD%BD

**Comment by n0thing2speak** [comment]
#1085
