### ISSUE TITLE
PAC模式无效

### ISSUE THREAD

**Issue by Johnson1602** [yanue/V2rayU#103]
系统版本：MacOS 10.14.5
V2RayU版本：1.3.2

设置为PAC模式之后无法翻墙
但是设置为Global模式可以翻墙
请问是为什么呀

**Comment by xiebruce** [comment]
你确定你pac的时候，google也上不了？还是你自己添加到pac的域名上不了？我pac的时候，默认在pac列表的都能上，但自己添加的pac不管用。

**Comment by Johnson1602** [comment]
下午的时候我PAC确实Google也上不去（但是只要换成Global就可以），后来反复重启电脑，重新安装，又重新更新了订阅之后晚上PAC又可以用了😂不知道是什么原因

**Comment by xiebruce** [comment]
哦，可以了就好

**Comment by Johnson1602** [comment]
OK👌

**Comment by Gui052** [comment]
1.4pac还是没用，怎么回事儿

**Comment by wk19921225** [comment]
自行添加的PAC规则并不会生效，望能修改下
macOS: 10.14.6 
V2rayU: 1.4.1

**Comment by phoenixg** [comment]
pac 模式没有用， 全局模式可以 +1

**Comment by best2wazi** [comment]
pac 模式没有用， 全局模式可以 +1
