### ISSUE TITLE
V2rayU正常下载及更新，连接速度正常但是无法使用，日志上说地址已经在使用中？

### ISSUE THREAD

**Issue by Henrfnfjfue** [yanue/V2rayU#1032]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V3.2.0 Mac 最新版
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
V2rayU正常连接，速度和服务器没有问题，但是无法连接外网

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

A unified platform for anti-censorship.
2022/01/26 11:59:53 [Info] infra/conf/serial: Reading config: config.json
2022/01/26 11:59:53 [Info] app/dns: DNS: created localhost client
2022/01/26 11:59:53 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

请预览一下你填的内容再提交。

**Comment by Henrfnfjfue** [comment]
应该是端口出问题，请问怎么解决

**Comment by Liesport758** [comment]
楼主解决了吗，遇到同样的问题了

**Comment by Liesport758** [comment]
卸载不干净导致的

**Comment by liuliangsir** [comment]
@Henrfnfjfue 把端口改成非 1087 以及 非 1080，比如 1088；如果还遇到这个问题，可以尝试把端口向上递增 +1
<img width="590" alt="image" src="https://user-images.githubusercontent.com/8049878/153760176-e030a9e7-a684-408d-b25f-affba0076482.png">

**Comment by cloudran5** [comment]
楼主解决了吗？按楼上的+1了七八个端口还是不行…

**Comment by Henrfnfjfue** [comment]
我还是不行，调了很久也上不了，最近只能用手机下了个新的是VPN上，笔记本电脑就是连接不上
