### ISSUE TITLE
部分节点无法正常使用

### ISSUE THREAD

**Issue by RomanticHW** [yanue/V2rayU#1033]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V3.2.0     12.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
部分节点无法使用，手机端，Windows端都是正常的，配置直接URL导入。日志显示
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1088"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": false
        },
        "security": "tls",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "********",
            "users": [
              {
                "id": "**************",
                "alterId": 0,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  }
}
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2022/01/26 16:29:56 [Info] infra/conf/serial: Reading config: config.json
2022/01/26 16:29:56 [Info] app/dns: DNS: created localhost client
2022/01/26 16:29:56 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
2022/01/26 16:29:56 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1088
2022/01/26 16:29:56 [Warning] core: Xray 1.4.2 started
2022/01/26 16:29:57 [Info] [885821672] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2022/01/26 16:29:57 [Info] [885821672] app/dispatcher: default route for tcp:alive.github.com:443
2022/01/26 16:29:57 tcp:127.0.0.1:57294 accepted tcp:alive.github.com:443 [proxy]
2022/01/26 16:29:57 [Info] [885821672] transport/internet/tcp: dialing TCP to tcp:************:443
2022/01/26 16:29:57 [Info] [885821672] proxy/vmess/outbound: tunneling request to tcp:alive.github.com:443 via tcp:**************:443
2022/01/26 16:29:57 [Info] [885821672] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
2022/01/26 16:29:57 [Info] [885821672] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by altairbow** [comment]
遇到同样的问题，每次启动 V2rayU 后都需要手工修改 config.json 文件，注意不是使用 V2RayU 的导入功能，V2RayU 每次启动后都会固执的把 allowInsecure 关掉，无论之前是 true 还是 false，很严重的 BUG
