### ISSUE TITLE
各项正常，但是不能翻墙上网

### ISSUE THREAD

**Issue by crybabylulu** [yanue/V2rayU#1035]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.2.0
Mac air 12.1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法翻墙上网

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by aloislee10** [comment]
我也是有同样的问题，安装完跟着步骤设置完，连接上了但是就是打不开外网

**Comment by YH2012** [comment]
我也有同样的问题。
V2RayU 3.2.0
Macbook air M1: macOS 12.3.1

**Comment by YH2012** [comment]
错误日志：
2022/05/21 21:58:25 [Info] v2ray.com/core/main/jsonem: Reading config: config.json
main: failed to read config files: [config.json] > v2ray.com/core/infra/conf: unknown cipher method: chacha20-ietf

**Comment by yanue** [comment]
不支持chacha20-ietf
