### ISSUE TITLE
个别网站添加pac不管用

### ISSUE THREAD

**Issue by xiebruce** [yanue/V2rayU#105]
我只能用神奇来形容，昨天不行，今天却又突然好了，我啥也没动，是哪里有隐藏的bug没发现吗？因为我全局是可以的，所以这排除了我服务器的问题，问题肯定出在客户端这边。

---

**原问题：**
@yanue 大佬看看这是什么原因呀？

macOS：`10.14.4`
V2rayU：`1.3.2`

被和谐网站：[https://233v2.com](https://233v2.com)

我的pac：
![image](https://user-images.githubusercontent.com/13575500/59149984-36ec0e00-8a4f-11e9-82e4-40ebb0576c7e.png)

可以看到我添加的pac已经在pac.js文件里了：
![image](https://user-images.githubusercontent.com/13575500/59149962-fbe9da80-8a4e-11e9-8696-95a4319c826f.png)

但还是无法访问：
![image](https://user-images.githubusercontent.com/13575500/59149972-1d4ac680-8a4f-11e9-892a-197e68bd4347.png)

请问这是什么原因呢？事实上，`pac.js`截图中前4个都是我自己添加的，前三个都管用，就233这个不管用！

**Comment by yanue** [comment]
这个我也没办法了
