### ISSUE TITLE
在开启V2ray U以后无法上网会提示Proxy伺服器错误

### ISSUE THREAD

**Issue by Bruce081** [yanue/V2rayU#1050]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.2.0 MacOS12.2.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
<img width="488" alt="image" src="https://user-images.githubusercontent.com/65952137/157890127-7729b525-c2e6-47b1-a19d-ab166864cfa7.png">

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by AaronWang666** [comment]
相同现象,补充一下配置:
请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    // 在这里附上配置信息
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "",
            "users": [
              {
                "id": "7bbb4ddd-6199-4979-8201-e56f990351cf",
                "alterId": 8,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port":
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
请附上出错时软件输出的错误日志。
    // 在这里附上日志信息
2022/05/17 19:36:39 [Info] [739146556] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2022/05/17 19:36:39 [Info] [739146556] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2022/05/17 19:36:42 [Info] [581439551] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2022/05/17 19:36:42 [Info] [581439551] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2022/05/17 19:37:22 [Info] [3727618008] proxy/http: request to Method [CONNECT] Host [kt-prod.ess.apple.com:443] with URL [//kt-prod.ess.apple.com:443]
2022/05/17 19:37:22 [Info] [3727618008] app/dispatcher: default route for tcp:kt-prod.ess.apple.com:443
2022/05/17 19:37:22 [Info] [3727618008] transport/internet/tcp: dialing TCP to tcp:
2022/05/17 19:37:22 127.0.0.1:50441 accepted //kt-prod.ess.apple.com:443 [proxy]
2022/05/17 19:37:22 [Info] [3727618008] proxy/vmess/outbound: tunneling request to tcp:kt-prod.ess.apple.com:443 via tcp:
2022/05/17 19:38:24 [Info] [1698569184] proxy/http: request to Method [CONNECT] Host [drive.wps.cn:443] with URL [//drive.wps.cn:443]
2022/05/17 19:38:24 [Info] [1698569184] app/dispatcher: default route for tcp:drive.wps.cn:443
2022/05/17 19:38:24 [Info] [1698569184] transport/internet/tcp: dialing TCP to tcp:
2022/05/17 19:38:24 127.0.0.1:50447 accepted //drive.wps.cn:443 [proxy]
2022/05/17 19:38:24 [Info] [1698569184] proxy/vmess/outbound: tunneling request to tcp:drive.wps.cn:443 via tcp:
2022/05/17 19:38:33 [Info] [1759430] proxy/http: request to Method [CONNECT] Host [presence.teams.microsoft.com:443] with URL [//presence.teams.microsoft.com:443]
2022/05/17 19:38:33 [Info] [1759430] app/dispatcher: default route for tcp:presence.teams.microsoft.com:443
2022/05/17 19:38:33 [Info] [1759430] transport/internet/tcp: dialing TCP to tcp:
2022/05/17 19:38:33 127.0.0.1:50449 accepted //presence.teams.microsoft.com:443 [proxy]
2022/05/17 19:38:33 [Info] [1759430] proxy/vmess/outbound: tunneling request to tcp:presence.teams.microsoft.com:443 via tcp:
2022/05/17 19:38:42 [Info] [1698569184] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2022/05/17 19:38:42 [Info] [1698569184] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled

**Comment by AaronWang666** [comment]
已经几天没办法访问google了,希望作者早日解决

**Comment by kJialing** [comment]
您好，我也出现了相同的问题，请问您的问题已经解决了吗？

**Comment by Bruce081** [comment]
我的问题并没有解决，我尝试了重新加载网路配置都没有解决，最后更换使用了ClashX。
