### ISSUE TITLE
在pac模式下如何单独设置一个域名走节点呢？

### ISSUE THREAD

**Issue by huiyuerandy** [yanue/V2rayU#1053]
我在设置的routing搞了半天不行，请问如果想把xx.com 在pac的模式走代理怎么设置 谢谢了

**Comment by cl53544007** [comment]
你是用什么版本?新版本哪还有PAC模式.老版本在设置-用户PAC设置中添加||xx.com

**Comment by kestrelbright** [comment]
||xx.com
