### ISSUE TITLE
路由设置无法生效,必须在pac里手动添加

### ISSUE THREAD

**Issue by egoistttt** [yanue/V2rayU#1060]
1) 你正在使用的 V2RayU 和 Mac 版本 ？

v2rayU: 3.2.0
mac:11.2.2

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

路由设置无法生效,必须在pac里手动添加

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

"routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "proxy",
          "domain": [
            "domain:sexbjcam.com",
            "domain:githubusercontent.com",
            "domain:google.com"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "domain:bilibili.com",
            "domain:qq.com",
            "localhost",
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by gdlcf88** [comment]
遇到了，请问是什么导致的？
