### ISSUE TITLE
v2ray-core有mac的arm版本了，可以发布一个包含v2ray-core arm的吗

### ISSUE THREAD

**Issue by acodercat** [yanue/V2rayU#1062]

**Comment by mikecjz** [comment]
可以手动更新core
core 位于 ~/.V2rayU/v2ray-core/

**Comment by GPPyeye** [comment]
> 可以手动更新core core 位于 ~/.V2rayU/v2ray-core/

请问是把下载的文件复制进这个目录吗？我在v2fly/v2ray-core的项目里面下载了.zip文件解压放进目录后，重新启动了，好像不起作用

**Comment by mikecjz** [comment]
> > 可以手动更新core core 位于 ~/.V2rayU/v2ray-core/
> 
> 请问是把下载的文件复制进这个目录吗？我在v2fly/v2ray-core的项目里面下载了.zip文件解压放进目录后，重新启动了，好像不起作用

应该只替换 ”v2ray“ 就可以。
还有就是你那里不起作用具体体现在哪里？

**Comment by n0thing2speak** [comment]
> > 可以手动更新core core 位于 ~/.V2rayU/v2ray-core/
> 
> 请问是把下载的文件复制进这个目录吗？我在v2fly/v2ray-core的项目里面下载了.zip文件解压放进目录后，重新启动了，好像不起作用

看#1085 ,不是v2ray，是xray

**Comment by kang000feng** [comment]
> > > 可以手动更新core core 位于 ~/.V2rayU/v2ray-core/
> 
> > 
> 
> > 请问是把下载的文件复制进这个目录吗？我在v2fly/v2ray-core的项目里面下载了.zip文件解压放进目录后，重新启动了，好像不起作用
> 
> 
> 
> 看#1085 ,不是v2ray，是xray

大佬 请问V2rayU 这个好像会自动更新xray core？  所以你这样手动替换了后 等后续他自动更新core 还是会变成 x86的那个啊 https://github.com/yanue/V2rayU/releases/tag/3.2.0

**Comment by kang000feng** [comment]
> > > 可以手动更新core core 位于 ~/.V2rayU/v2ray-core/
> 
> > 
> 
> > 请问是把下载的文件复制进这个目录吗？我在v2fly/v2ray-core的项目里面下载了.zip文件解压放进目录后，重新启动了，好像不起作用
> 
> 
> 
> 看#1085 ,不是v2ray，是xray


你看一下他的自动更新代码 mac-64

https://github.com/yanue/V2rayU/blob/master/V2rayU/V2rayCore.swift

**Comment by n0thing2speak** [comment]
> 

嗯嗯，所以要替换最新版的xray

**Comment by kang000feng** [comment]
> > 
> 
> 
> 
> 嗯嗯，所以要替换最新版的xray

大佬 你看他的自动更新代码 是mac-64，我手动替换之后后续它自动更新，还是还是会变成X86啊，这个还要怎么禁止它自动更新？

https://github.com/yanue/V2rayU/blob/master/V2rayU/V2rayCore.swift

**Comment by yanue** [comment]
已更新3.3,请下载试用
