### ISSUE TITLE
导入的服务器配置不生效

### ISSUE THREAD

**Issue by oakax** [yanue/V2rayU#1066]
V2RayU V3.2.0 Macos 12.3.1

导入了多个服务器配置，vless，vemss，ss协议的都有，但是没有一个服务器配置是生效的。
开启全局配置能够翻墙，但是使用的服务器配置不是我添加的服务器中的任何一个；切换到PAC模式也无法上网

我不清楚这个能够让我全局翻墙的配置是从哪来的，可能是之前配置然后删掉的一个。

**Comment by Joker-smile** [comment]
切换到v2.*版本的没问题，不要用最新的，他这个好像不维护了

**Comment by ZhongFuze** [comment]
我也想知道怎么才能生效

**Comment by Joker-smile** [comment]
这是来自QQ邮箱的自动回复邮件。
 你好，我已经收到你的邮件，但未查看，待查看后回复你~

**Comment by vvvvie** [comment]
你好，我也遇到服务器配置失败，没有服务器列表的问题，请问你解决了吗

**Comment by oakax** [comment]
> 你好，我也遇到服务器配置失败，没有服务器列表的问题，请问你解决了吗

没有解决，目前解决方案就是用清理软件彻底卸载掉。然后重新安装导入

**Comment by Joker-smile** [comment]
这是来自QQ邮箱的自动回复邮件。
 你好，我已经收到你的邮件，但未查看，待查看后回复你~
