### ISSUE TITLE
v2rayU代理终端流量异常

### ISSUE THREAD

**Issue by yintao-xu** [yanue/V2rayU#1071]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU3.2.0    macos 11.6
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端使用pac模式，在浏览器中可正常区分内网流量和外网流量。
然后有个功能是终端代理，export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;export ALL_PROXY=socks5://127.0.0.1:1080，我将这段命令复制到.bash_profile文件中，发现终端的流量似乎被全局代理了，无法访问内网服务(git代码拉取)，并不会像客户端pac模式那样区分内外网流量，请问有办法解决吗？
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
终端代理后用curl -v访问内网服务，就会报503错误
< HTTP/1.1 503 Service Unavailable
< Connection: close
* HTTP/1.1 proxy connection set close!
< Proxy-Connection: close
< Content-Length: 0
< 
* Closing connection 0
取消终端代理后可正常访问内网服务（git 拉取）
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
配置路由方式
