### ISSUE TITLE
至我们伟大的作者

### ISSUE THREAD

**Issue by lxtx528** [yanue/V2rayU#1075]
这是一款我常用且非常喜欢用的软件，希望作者能抽点时间在维护维护，好久没有更新了，很多新功能跟不太上了，希望大佬能新增协议的支持，如果能有clash分流就更好了，还有就是内核直接换xray，希望越来越好用！

**Comment by yamazakitouma** [comment]
好久没更新了，U 应该是 mac 系统上最好用的客户端了

**Comment by shuimulingyang** [comment]
可以自己更新内核吗

**Comment by yanue** [comment]
已更新3.3, 后续有时间的话,会有新版ui

**Comment by lxtx528** [comment]
👍👍👍👍顶一个。

yanue ***@***.***> 于 2022年8月19日周五 21:50写道：

**Comment by lxtx528** [comment]
还有近段时间发现，ping speed 测速一直在测试中，但是一直测不出来。

Aaro Cheung ***@***.***> 于 2022年8月21日周日 20:07写道：

**Comment by lxtx528** [comment]
还有近段时间发现，ping speed 测速一直在测试中，但是一直测不出来。

yanue ***@***.***> 于 2022年8月19日周五 21:50写道：

**Comment by lxtx528** [comment]
能不能直接上xray内核，我试着换过几次，没成功。太笨了。

Aaro Cheung ***@***.***> 于 2022年8月21日周日 19:57写道：
