### ISSUE TITLE
configure界面打开后停留在Dock栏上无法关闭

### ISSUE THREAD

**Issue by xiebruce** [yanue/V2rayU#108]
macOS: `10.14.4`
V2rayU：`1.3.2`

![image](https://user-images.githubusercontent.com/13575500/59173615-48810300-8b80-11e9-9246-5fdb2dd75761.png)

因为经常要配置，有时候可能点到其他窗口这个configure窗口就隐藏到背后了，所以最后忘了关，但是后来我想关的时候，点Dock栏上的VrayU图标已经点不开了，如果我右击→退出，将会退出整个V2rayU而不是只是这个图标，不过如果我重新点configure，又会正常出来一个配置窗口，而Dock栏那个就一直留在那，除非我右击→退出，否则这个图标无法关闭！

**Comment by lostwolf** [comment]
10.14.5一样的毛病

**Comment by Kevin-Winehouse** [comment]
我的也是。

**Comment by atlascollege** [comment]
10.13.6上面也是一样。

**Comment by ZevveZ** [comment]
+1

**Comment by pyericz** [comment]
看作者的代码提交，已经有一段时间没维护了。看来是不打算修复了

**Comment by yanue** [comment]
一是忙，二是怕，后面抽时间弄吧

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Eric Zhang <notifications@github.com>
发送时间: Wednesday, July 10, 2019 12:03:46 PM
收件人: yanue/V2rayU
抄送: Subscribed
主题: Re: [yanue/V2rayU] configure界面打开后停留在Dock栏上无法关闭 (#108)


看作者的代码提交，已经有一段时间没维护了。看来是不打算修复了

―

**Comment by Kevin-Winehouse** [comment]
暂时也可以先用回V2rayX

**Comment by yanue** [comment]
尝试修复:1.3.3
