### ISSUE TITLE
mac无法使用

### ISSUE THREAD

**Issue by qingliulin** [yanue/V2rayU#1080]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.2.0.  macOS12.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2022/07/08 12:06:30 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: rc4-md5
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
之前正常使用的配置，手机可以使用的订阅连接
```
4)  请附上出错时软件输出的错误日志。

```javascript
   Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2022/07/08 12:06:30 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: rc4-md5
```

请预览一下你填的内容再提交。

**Comment by Robert87666** [comment]
我就出现这样的问题了， V2RayU 和 Mac 版本 —— 3.2.0. macOS12.4  一直连不上，没有更新monterty系统之前是可以用的，更新之后就用不了了。具体的日志需要在哪里截取出来呢。目前手机跟window都正常使用。

**Comment by Lelouch-Lamperoge** [comment]
v2ray可以用 我也3.2.0 + monterty

**Comment by Burning-Shadow** [comment]
同robort，只不过我系统更新之前也没有翻成功，手机正常Windows未尝试

**Comment by solomsk** [comment]
我退回到2.3.1版本，还是不能用

**Comment by Robert87666** [comment]
1.先确定有没有卸载干净，最好用cleaner这样的工具卸载
2.看你的配置，服务是自己部署的，还是机场，机场应该不存在问题，自己部署的，看是用什么协议部署，设置的时候仔细看一下。各端客户端不同，配置会有点差别，多尝试修改几次。

**Comment by mingyuezixun** [comment]
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2022/07/24 16:14:09 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: rc4-md5

同遇到这个问题了，求助 mac catalina

**Comment by yanue** [comment]
v2ray不支持ss的c4-md5, 请改用shandowsockX
