### ISSUE TITLE
Preferences 界面改进

### ISSUE THREAD

**Issue by xpol** [yanue/V2rayU#1082]
现在的界面是这样的：
<img width="572" alt="Screen Shot 2022-07-25 at 23 38 22" src="https://user-images.githubusercontent.com/20248/180818681-a180a173-b6fa-4987-a67d-6adfa1ddbfe9.png">
由于窗口宽度问题，Pac，Routing等tab被折叠。

改进可能一：减小图标，并且在图标在独立的一行，这样避免折叠：
<img width="921" alt="Screen Shot 2022-07-25 at 23 32 42" src="https://user-images.githubusercontent.com/20248/180818996-acba4896-b50e-45de-ac7d-c321fe9b138c.png">

改进可能二：像新版Mac风格一样，把导航放到界面右边：
<img width="1049" alt="Screen Shot 2022-07-25 at 23 33 05" src="https://user-images.githubusercontent.com/20248/180819458-965c0885-1a58-49e6-ae9c-02ae7ca101f9.png">

**Comment by Oio0** [comment]
赞同👻
About应该剔掉作为单独的菜单项和窗口。剩下一共6个图标+左右两边的留白，窗口再横向拉大一点点，就够放了。
如果某个Tab的设置少可以让窗口变矮一点。不同Tab的高度可以变。
<img width="886" alt="image" src="https://user-images.githubusercontent.com/119158747/211087120-4cb00537-c583-4002-a8da-9095d4038fa4.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/119158747/211087512-88dfdb06-0be2-43c0-bb1a-1d29197bbaa5.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/119158747/211092595-3186c17b-787b-4a2b-9fca-f519bfe212f9.png">

此外，Subscribe貌似可以改成Subscriptions，Advance=>Advanced. Preferences被Apple改成Settings了。Advanced放最右。还有一些大小写，比如DNS，PAC。
Copyright还是2021，而且About那个界面不适配深色模式。
