### ISSUE TITLE
M1 M2 arm芯片的新选择（shadowsocket）

### ISSUE THREAD

**Issue by DevHaoZi** [yanue/V2rayU#1084]
经本人测试，ios上的小火箭shadowsocket在本人的M2 MacBook Pro工作良好，完全可以替代ClashX和V2RayU。
下载方法和手机一致，appstore登录外区appleid下载即可。
<img width="515" alt="image" src="https://user-images.githubusercontent.com/45513686/181616748-baf55f6d-2ac3-4538-a743-540e985d489f.png">

**Comment by DevHaoZi** [comment]
甚至可以做到自动更新规则，参考：[https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever#如何自动更新](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever#如何自动更新)

**Comment by xbol0** [comment]
试过一段时间，同一条线路，总感觉性能不如clashx (我用的是clashx pro)，不知道是不是我的错觉，你有这种情况吗？

**Comment by DevHaoZi** [comment]
> 试过一段时间，同一条线路，总感觉性能不如clashx (我用的是clashx pro)，不知道是不是我的错觉，你有这种情况吗？

我没啥感觉，可能我用的线路本来就不咋滴。目前感觉最不爽的地方就是没有通知栏图标和快捷键，开关起来麻烦。

**Comment by n0thing2speak** [comment]
速度还是v2rayU更好， 可以试试 #1085

**Comment by yosolin** [comment]
> 经本人测试，ios上的小火箭shadowsocket在本人的M2 MacBook Pro工作良好，完全可以替代ClashX和V2RayU。 下载方法和手机一致，appstore登录外区appleid下载即可。 <img alt="image" width="515" src="https://user-images.githubusercontent.com/45513686/181616748-baf55f6d-2ac3-4538-a743-540e985d489f.png">

感谢提醒！我也试了可以！

**Comment by nodeInLive** [comment]
购买这个需要2.99美金么

**Comment by yuxianwen** [comment]
> 购买这个需要2.99美金么
肯定需要啊，相比 Quantumult X、Surge、Loon 性价比最高了，算入门级代理软件了，如果没有美元信用卡，很多网站提供礼品卡只是价格贵点

**Comment by yanue** [comment]
ios版本跟本项目完全无关，别人盗用图标，千万别信

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maksimh3** [comment]
為什麼我打不開Shadowrocket？m1的MacbookPro
