### ISSUE TITLE
ARM芯片的mac使用纯arm架构的v2rayU的方法，免rosetta

### ISSUE THREAD

**Issue by n0thing2speak** [yanue/V2rayU#1085]
1:下载arm版的[xray](https://github.com/XTLS/Xray-core/releases/download/v1.5.9/Xray-macos-arm64-v8a.zip)并解压
2:复制一个xray并粘贴，并命名为v2ray，也就是现在有一个xray和v2ray的可执行程序，但是其实都是xray
<img width="798" alt="image" src="https://user-images.githubusercontent.com/19668794/181903078-aeb37d0b-1c68-4c3b-b15f-14e0190fbe19.png">

## 新装v2rayu未启动过的同学
直接替换掉 `/Applications/V2rayU.app/Contents/Resources/v2ray-core`中的v2ray和xray并启动就OK了

## 运行过的同学
替换掉 `/Users/$USER/.V2rayU/v2ray-core `和`/Applications/V2rayU.app/Contents/Resources/v2ray-core`中的v2ray和xray

然后启动v2rayU就是纯arm架构的了。enjoy🎉
<img width="953" alt="image" src="https://user-images.githubusercontent.com/19668794/181903128-9fa89bc0-26b8-4023-b31c-01b1757b33bb.png">

**Comment by snsnselaoyeye** [comment]
我是新安装 替换完 启动居然没反应

**Comment by snsnselaoyeye** [comment]
我试了半天启动不了 然后重新卸载安装一遍 安装了下罗塞塔 然后顺利启动了 什么也没动 进程里都是apple 看不懂了

**Comment by coolqingcheng** [comment]
你复制的是哪个版本，我用最新版不行。。。

**Comment by snsnselaoyeye** [comment]
我复制了1.5.5 1.5.9测试版 都不行 
 
看命令行 好像是读取不到什么config文件

小白不懂 最后还是用原版加罗塞塔运行了

**Comment by n0thing2speak** [comment]
> 你复制的是哪个版本，我用最新版不行。。。

1.5.9

**Comment by n0thing2speak** [comment]
> 我复制了1.5.5 1.5.9测试版 都不行
> 
> 看命令行 好像是读取不到什么config文件
> 
> 小白不懂 最后还是用原版加罗塞塔运行了

我是1.5.9可以的，你自己看看，是下载一个xray mac的arm64版本，然后解压再复制一份，粘贴重命名为v2ray，也是说现在一个叫v2ray，一个叫xray，其实都是你下载的xray

**Comment by snsnselaoyeye** [comment]
> > 我复制了1.5.5 1.5.9测试版 都不行
> > 看命令行 好像是读取不到什么config文件
> > 小白不懂 最后还是用原版加罗塞塔运行了
> 
> 我是1.5.9可以的，你自己看看，是下载一个xray mac的[arm64版本](https://github.com/XTLS/Xray-core/releases/download/v1.5.9/Xray-macos-arm64-v8a.zip)，然后解压再复制一份，粘贴重命名为v2ray，也是说现在一个叫v2ray，一个叫xray，其实都是你下载的xray

对啊就是这么操作的，把两个文件复制到核心文件夹替换掉原来的两个，然后点击运行，没有任何反应。
M1 air macos12.5

**Comment by 50kg** [comment]
谢谢 完美解决

**Comment by zhangxiaoqiang1998** [comment]
谢谢 ！完美解决！

**Comment by coolqingcheng** [comment]
我也解决了

**Comment by snsnselaoyeye** [comment]
> 我也解决了
说说怎么解决的 参考下 谢谢

**Comment by Nasamars** [comment]
我也解决了 重要是的安全设置那里要允许 v2ray运行

**Comment by yanue** [comment]
已经更新3.3,可下载试用
