### ISSUE TITLE
A unified platform for anti-censorship

### ISSUE THREAD

**Issue by evilvlso** [yanue/V2rayU#109]
```

V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
2019/06/10 15:36:01 [Warning] v2ray.com/core: V2Ray 4.19.1 started
```
这条日志是正常启动的日志么？同样的配置在手机上是可以的mac上不行了

**Comment by yanue** [comment]
这个是正常的,系统版本是多少,V2rayU版本是多少
选用什么模式呢? global还是pac?

**Comment by evilvlso** [comment]
你好，mac pro 10.13.6  V2rayU 1.3.2 ,pac模式。之前是可以上网的，然后重启了电脑报错 conf does not exist ，然后卸载重装最新版本的，就是这样了

**Comment by yanue** [comment]
设置log级别为info,切换到global模式,看看wifi设置里面的代理信息有没有写入,浏览器再打开看看,另外看见日志有没有反应

**Comment by evilvlso** [comment]
你好，很奇怪，在我清除所有配置，从新倒入，切换全局模式下可以上网了。但是我发四这样的操作我做过很多次，没效果才发起的issue。麻烦 你了！谢谢
