### ISSUE TITLE
mac 配置好后，无法上网，启动不了本地监听的sockt和http端口

### ISSUE THREAD

**Issue by fengxueguang** [yanue/V2rayU#1092]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v3.3.0
mac版本是：10.14.6 (18G87)
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
不报任何错误，错误日志也是空，手动改过两个端口，sock--1096 ，http--1097
 发现启动软件后，只有pac监听的端口可以在终端搜到

➜  ~ lsof -i tcp:11086                                                                                                                                                         [1]
COMMAND   PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
V2rayU  75327 xxxxx   3u  IPv6 0xxxb4fdd      0t0  TCP *:11086 (LISTEN)
➜  ~                                                                                                                                                                           [0]
➜  ~ lsof -i tcp:1097                                                                                                                                                          [0]
➜  ~ lsof -i tcp:1096                                                                                                                                                          [1]
➜  ~

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    {
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1096"
    },
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1097"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xxxxxxxx",
            "users": [
              {
                "id": "xxxxxxxxx",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": xxxx
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "ip": [
            "geoip:cn"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 没有任何错误信息，log中是空的
```

请预览一下你填的内容再提交。

**Comment by Aknksdo** [comment]
问题解决了吗？

**Comment by fengxueguang** [comment]
> 

没有

**Comment by AlbertMingXu** [comment]
m2 mac 同样的问题，启动后不监听1080和1087端口，11085端口正常。使用1.5.10和1.5.9版本的xray替换v2ray-core中的文件同样无效果。

日志为空，无任何记录。

**Comment by 54whui** [comment]
我是intel的cpu，下载的是V2rayU-64.dmg，配置了ssr和v2ray的连接，都无法使用，站点状态正常。恢复成3.2也无法访问了。

**Comment by minchenzz** [comment]
相同的问题，手动添加http和socks后可以正常使用，否则只能全局模式

m2 12.5.1，3.3版本

**Comment by martin-matj** [comment]
用命令行启动。进入到v2ray的目录中。。麻烦点。但是可以用
