### ISSUE TITLE
一直在测速中有什么方法解决么？

### ISSUE THREAD

**Issue by liu1169681** [yanue/V2rayU#1094]
![屏幕快照 2022-08-21 14 54 39](https://user-images.githubusercontent.com/23412521/185779463-dac498ae-87b5-4b2f-8b0f-fc28950ece7b.png)
![屏幕快照 2022-08-21 14 54 47](https://user-images.githubusercontent.com/23412521/185779465-aee70737-6015-4879-8f4d-33dc808b8f55.png)
一直在测速
却显示不出速度
不知道哪个节点能用哪个不能用
很不方便 有办法解决么？

**Comment by yanue** [comment]
关闭sip试下

**Comment by J-Liu** [comment]
> 关闭sip试下

问一下怎么关闭sip？设置里面没找到

**Comment by Jerry-kwong** [comment]
我也有同样的情况，关了SIP也还是没有解决问题。

**Comment by windyking** [comment]
我也遇到了同样的问题，一直测速中，显示不出速度。但是节点在手机上或者win电脑上测速都能显示出速度
