### ISSUE TITLE
M2 Mac 打不开 最新3.3.0 v2ray

### ISSUE THREAD

**Issue by ThuSNO3** [yanue/V2rayU#1096]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.3.0, MacBook Air (M2, 2022年)

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
在安全性与隐私允许打开v2ray后，就没有其他任何反应了，活动监视器也找不到相关的进程

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by ThuSNO3** [comment]
下载的 arm64版本

**Comment by GeckoWang** [comment]
出现了同样问题。电脑是m1 pro芯片的。一直显示config not found。求问如何配置？

**Comment by R-juzi** [comment]
我安装新版本后直接打不开
<img width="130" alt="image" src="https://user-images.githubusercontent.com/59160257/187326503-4737f65f-69a8-481b-9c23-57e99de0213c.png">

**Comment by GeckoWang** [comment]
> 

你这个 点“好”，然后再点开系统偏好设置的“安全性与隐私“的通用，会让你信任软件（大概就在这个界面上会出现）。你点类似确认信任，就好了。
<img width="670" alt="image" src="https://user-images.githubusercontent.com/103023369/187327438-677b1c9e-90f1-4986-af0c-ada03f938e3e.png">

**Comment by GeckoWang** [comment]
> 我安装新版本后直接打不开
> <img alt="image" width="130" src="https://user-images.githubusercontent.com/59160257/187326503-4737f65f-69a8-481b-9c23-57e99de0213c.png">
你这个 点“好”，然后再点开系统偏好设置的“安全性与隐私“的通用，会让你信任软件（大概就在这个界面上会出现）。你点类似确认信任，就好了。

<img width="663" alt="image" src="https://user-images.githubusercontent.com/103023369/187327739-e2a5842a-424e-4d27-b2f6-f30daa44be75.png">

**Comment by R-juzi** [comment]
弄好了，谢谢！

**Comment by GeckoWang** [comment]
> 弄好了，谢谢！

那太好了。那请问你的可以用吗？我总觉得我一定是安装上的哪个步骤出错了。是 点开dmg-拖到application-推出磁盘映像-在启动台打开v2ray。设置好安全性后，设置订阅 吧？

**Comment by R-juzi** [comment]
是的我可以用，我之前有安装老版本的。然后这次更新是下载arm64版本，然后双击dmg，拖动到application，弹出对话框替换还是安装两个，我点了替换。然后就是设置下允许打开这个软件就能正常使用了，比起你来少了一步设置订阅

**Comment by R-juzi** [comment]
而且我不是订阅源，是直接从粘贴板导入配置的方式

**Comment by GeckoWang** [comment]
> 而且我不是订阅源，是直接从粘贴板导入配置的方式

我是删干净之后重新下载的。但我记得上一个版本我按照一篇帖子在终端配置过什么东西（一开始也是不能用，也是config not found的情况）。但忘记是哪篇帖子了。请问您最开始有配置过什么吗？开始下载了就能直接用？

**Comment by R-juzi** [comment]
是啊 什么都没有配置 直接下载了就能用

**Comment by ThuSNO3** [comment]
@R-juzi 你的是m2吗？我的m2 下载之后也点击了“ 安全与隐私”里面允许打开的按钮，但是后面就没有任何反应了

**Comment by ChandlerVer5** [comment]
> > 而且我不是订阅源，是直接从粘贴板导入配置的方式
> 
> 我是删干净之后重新下载的。但我记得上一个版本我按照一篇帖子在终端配置过什么东西（一开始也是不能用，也是config not found的情况）。但忘记是哪篇帖子了。请问您最开始有配置过什么吗？开始下载了就能直接用？



> > 而且我不是订阅源，是直接从粘贴板导入配置的方式
> 
> 我是删干净之后重新下载的。但我记得上一个版本我按照一篇帖子在终端配置过什么东西（一开始也是不能用，也是config not found的情况）。但忘记是哪篇帖子了。请问您最开始有配置过什么吗？开始下载了就能直接用？

老哥和我一样的情况，感觉是bug，找到了解决办法，记得回来踢🦶我一下

**Comment by ChandlerVer5** [comment]
> @R-juzi 你的是m2吗？我的m2 下载之后也点击了“ 安全与隐私”里面允许打开的按钮，但是后面就没有任何反应了

把之前的清除干净试试？

**Comment by R-juzi** [comment]
@ThuSNO3 我是m1pro

**Comment by ThuSNO3** [comment]
> 

我这是刚刚开箱的新电脑，啥都没有呢，第一次装就不成功

**Comment by ThuSNO3** [comment]
> > @R-juzi 你的是m2吗？我的m2 下载之后也点击了“ 安全与隐私”里面允许打开的按钮，但是后面就没有任何反应了
> 
> 把之前的清除干净试试？
我是刚拆箱的船新m2，尴尬

**Comment by ThuSNO3** [comment]
> @ThuSNO3 我是m1pro

那可能和m2还不一样？我再试试

**Comment by QQ1597289624** [comment]
same problems here. M2 version MacBook Pro 13' , can't start after after the security & privacy check's OPEN ANYWAY, nothing happens.

**Comment by jujuxiaotian** [comment]
我的MacBook Air M1上也是 failed to load config files，有解决这个问题的吗？

**Comment by jujuxiaotian** [comment]
点击图标打开直接没反应

**Comment by ChandlerVer5** [comment]
有兄弟有解决办法了嘛？记得回来踢一下这里所有人

**Comment by snsnselaoyeye** [comment]
我是不装罗塞塔直接不能启动
M1 air 12.5.1 3.30版
装了罗塞塔就无问题了，进程里显示的也是apple方式运作

**Comment by jujuxiaotian** [comment]
> 我是不装罗塞塔直接不能启动 M1 air 12.5.1 3.30版 装了罗塞塔就无问题了，进程里显示的也是apple方式运作

安装的是arm64版本的吗？

**Comment by snsnselaoyeye** [comment]
> > 我是不装罗塞塔直接不能启动 M1 air 12.5.1 3.30版 装了罗塞塔就无问题了，进程里显示的也是apple方式运作
> 
> 安装的是arm64版本的吗？

是的

**Comment by jujuxiaotian** [comment]
使用罗塞塔确实可以打开了😀

**Comment by YCoffee** [comment]
m1 pro 安全隐私信任后也无法启动

**Comment by jujuxiaotian** [comment]
> m1 pro 安全隐私信任后也无法启动，装的arm 64 12.5版本
重启一下电脑，然后用罗塞塔打开就可以了

**Comment by kent4git** [comment]
新M2 pro, 最新的arm 64软件版本,安装正常,隐私安全也点击允许了,但是依然无法打开软件. 你们都是怎么解决的?还有其他软件推荐的吗?

**Comment by xmbear-stack** [comment]
安装Rosseta之后，M2就可以打开了，亲测使用命令：softwareupdate --install-rosetta 有效。安装参考地址：https://zhuanlan.zhihu.com/p/338961302

**Comment by ningg** [comment]
我已经解决了，最新的解决方案：

* [mbp2023 m2 pro 重新安装 V2rayU](https://ningg.top/tools-series-mbp2023-reinstall-v2ray/)
