### ISSUE TITLE
请问Turn v2ray-core Off甚至退出V2rayU后仍能fq是正常的吗？

### ISSUE THREAD

**Issue by KFE-Stefan** [yanue/V2rayU#1097]
V2rayU版本：v3.3.0 [V2rayU-arm64.dmg](https://github.com/yanue/V2rayU/releases/download/3.3.0/V2rayU-arm64.dmg)
<img width="276" alt="v2rayU" src="https://user-images.githubusercontent.com/20940503/186370202-4aa7775d-15de-473d-a75a-1b705b8c4c76.png">
系统版本：macOS 12.5.1
MacBook Pro (14-inch, 2021)
选择Turn v2ray-core Off并且退出V2rayU后，仍然能在活动监视器里看到v2ray进程：
<img width="822" alt="v2ray" src="https://user-images.githubusercontent.com/20940503/186371606-bf73cc77-2bcb-45f9-9a55-77e369dfae5c.png">
然后在Chrome里面配合SwitchyOmega仍然能够正常fq浏览网页，请问是正常的吗？有没有办法彻底退出呢？
（小白提问，恳求解答）

**Comment by jackliu145** [comment]
应该是开启与关闭的代码逻辑有bug吧，不过你可以手动试试以下命令：
`
/bin/launchctl remove yanue.v2rayu.v2ray-core
/bin/launchctl remove yanue.v2rayu.http
`

**Comment by yanue** [comment]
@jackliu145 这个方法可行
本次版本改了这里导致
[`https://github.com/yanue/V2rayU/blob/master/V2rayU/V2rayLaunch.swift#L97`](https://github.com/yanue/V2rayU/blob/master/V2rayU/V2rayLaunch.swift#L97)

**Comment by wendaleruan** [comment]
下个版本会解决这个问题吗？

**Comment by reducm** [comment]
同样问题，退出后，core进程依然是启动中，导致各种访问问题
