### ISSUE TITLE
最新版3.3.0 config not found问题

### ISSUE THREAD

**Issue by GeckoWang** [yanue/V2rayU#1101]
找了好多之前的issue，因为之前的3.2.0版本记得也是config not found，也是看了某篇帖子在终端配置后才能用的（但忘了是哪篇帖子了！啊喂！）。所以每个提到config的帖子都试了一下，但是都没啥子效果。兄弟姐妹们帮帮我！

1) 你正在使用的 V2RayU 和 Mac 版本 ？
使用的V2rayU版本为3.3.0，之前用的是3.2.0，是按照大大提供的方法彻底删除原文件后下载的，Mac是m1pro，系统是12.3

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
遇到的问题是无法turn v2ray-core on。（已经完成安全性和订阅设置之后）
点击后会出现这样的图标
<img width="467" alt="截屏2022-08-31 10 57 07" src="https://user-images.githubusercontent.com/103023369/187624950-b245d761-a900-4c6f-9996-e419427b2aeb.png">
点击查看config.json，会跳出一个网络空白页（不知道这算不算正常）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
不太明白配置应该上哪里找
```

4)  请附上出错时软件输出的错误日志。
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
Failed to start: main: failed to load config files: [config.json] > infra/conf/serial: failed to read config: config.json > open config.json: no such file or directory

**Comment by GeckoWang** [comment]
无人问津，dd自己

**Comment by jujuxiaotian** [comment]
同样的问题，题主解决了吗?

**Comment by GeckoWang** [comment]
> 同样的问题，题主解决了吗?

> 同样的问题，题主解决了吗?

还没有解决～

**Comment by jackliu145** [comment]
我比较好奇，你们m1的macbook，为啥不用shadowrocket客户端，那个客户端几乎支持所有的协议。。。我的intel是想用都用不了。。。

**Comment by GeckoWang** [comment]
> 我比较好奇，你们m1的macbook，为啥不用shadowrocket客户端，那个客户端几乎支持所有的协议。。。我的intel是想用都用不了。。。

之前sr下载了也没打开诶！奇怪的！我一会再下个试试

**Comment by jujuxiaotian** [comment]
sr在哪可以下载？

**Comment by jackliu145** [comment]
> > 我比较好奇，你们m1的macbook，为啥不用shadowrocket客户端，那个客户端几乎支持所有的协议。。。我的intel是想用都用不了。。。
> 
> 因为v2ray打不开所以有下sr。也打不开诶！奇怪的！我一会再下个试试

你可能误解我的意思了，我说的是小飞机，ios上的那个应用。不是ss和ssr客户端。m1和m2可以安装ios应用。

**Comment by jujuxiaotian** [comment]
我的sr也打不开

**Comment by jujuxiaotian** [comment]
使用罗塞塔可以打开😀😀

**Comment by jujuxiaotian** [comment]
使用罗塞塔打开了，但是无法上网

**Comment by zdante** [comment]
> > > 我比较好奇，你们m1的macbook，为啥不用shadowrocket客户端，那个客户端几乎支持所有的协议。。。我的intel是想用都用不了。。。
> > 
> > 
> > 因为v2ray打不开所以有下sr。也打不开诶！奇怪的！我一会再下个试试
> 
> 你可能误解我的意思了，我说的是小飞机，ios上的那个应用。不是ss和ssr客户端。m1和m2可以安装ios应用。

我也是无语了，本来v2rayu更新到3.3后打不开节点退回到3.2也不可用，下载了shadowrocket可以用，今天刚刚shadowrocket更新了下，电脑和手机上都不可以用了。不知道到底哪里出问题了，节点应该是没问题的，因为安卓上节点是可以用的😂真是醉了😂。v2ray ws套cf，怎么问题这么多。烦死了😂。。

**Comment by Finnliang** [comment]
MBP M2、v2rayU 3.3.0版本，安装后查看日志，提示找不到config.json，但点击【查看Config.json】却有可以，不知该如何解决

**Comment by pavenchen** [comment]
v2rayU 3.3.0, mac os 13.2.1，一样提示v2ray run fail: v2ray config not found, 点【查看config.json】打开了空白页面

**Comment by sdpong** [comment]
能不能增加多proxy 和多route

**Comment by PicaJIN** [comment]
同样在彻底卸载、重新安装之后还会出现config无法找到的提示，我一开始看没有这个文件，手动把以前备份的放进去了，还是识别不到，不知道是不是整个~/.V2rayU/文件的权限有问题
