### ISSUE TITLE
3.3.0 版本 不支持 ss 的 unknown cipher method: aes-256-cfb 

### ISSUE THREAD

**Issue by ChandlerVer5** [yanue/V2rayU#1109]
配置
```javascript
mac 12.6 (21G115)
MacBook Pro (14-inch, 2021)
```
4)  请附上出错时软件输出的错误日志。
![image](https://user-images.githubusercontent.com/10599509/191672876-f297c3f0-e83f-4f7a-8618-e81ca25ac9b6.png)

```javascript
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
2022/09/22 11:09:10 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: aes-256-cfb
```

v2rayU 3.3.0 (arm64/x64) 一直提示 如上错误

**Comment by ChandlerVer5** [comment]
卸载之后，安装 3.2 版本可以支持，所以这是个bug

**Comment by Char-CN** [comment]
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/amd64)
A unified platform for anti-censorship.
2023/03/30 15:17:49 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: aes-256-cfb

@ChandlerVer5 为什么我3.2都不行？

**Comment by ChandlerVer5** [comment]
> Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/amd64) A unified platform for anti-censorship. 2023/03/30 15:17:49 [Info] infra/conf/serial: Reading config: config.json Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: aes-256-cfb
> 
> @ChandlerVer5 为什么我3.2都不行？

卸载干净，再打开试试？

**Comment by Lkh017** [comment]
M1 mac遇到同样的问题, 回到3.2解决问题, 但是还是需要升级的呀, 会不会修复呢

**Comment by jeffery9** [comment]
回退到 3.0 依然不支持

2023/04/03 15:04:31 tcp:127.0.0.1:53874 accepted tcp:alive.github.com:443 [proxy]
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/amd64)
A unified platform for anti-censorship.
2023/04/03 15:16:42 [Info] infra/conf/serial: Reading config: config.json
2023/04/03 15:16:42 [Warning] core: Xray 1.5.5 started
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 darwin/amd64)
A unified platform for anti-censorship.
2023/04/03 15:17:30 [Info] v2ray.com/core/main/jsonem: Reading config: config.json
main: failed to read config files: [config.json] > v2ray.com/core/infra/conf: unknown cipher method: aes-256-cfb

貌似 v2ray core 版本太高， 不再支持。

**Comment by jeffery9** [comment]
ref.  https://github.com/v2fly/v2ray-core/issues/620

**Comment by jeffery9** [comment]
ref.  https://github.com/v2fly/v2ray-core/issues/620

**Comment by jeffery9** [comment]
https://github.com/v2fly/v2ray-core/pull/566

需要将 v2ray core 换回到 v.4.33 
从 v4.34 开始移除了 
```
AES-256-CFB
AES-128-CFB
ChaCha20
ChaCha20-IETF
```

**Comment by zachx121** [comment]
@jeffery9 请问哪个版本的v2rayU对应了 v4.33的v2ary-core？
