### ISSUE TITLE
在界面上手工添加的server找不到修改server name的地方，都是new server

### ISSUE THREAD

**Issue by anuxs** [yanue/V2rayU#111]
我手工添加了两个server，没找到填写server name的地方，现在Servers下面显示的是两个new server，我无法区分哪个是哪个了。看了文档，也没有说明如何修改server name。

**Comment by yanue** [comment]
双击修改

**Comment by anuxs** [comment]
> 双击修改

收到。搞定。最好在界面上增加一个输入框server name 或者memo，我一直用的ShadowsocksX-NG182，它就是有个备注名，可以填入名称区分，因为macos 10.15beta让它有点不能自动启动，才切换到V2rayU。
