### ISSUE TITLE
希望增加测试节点速度的功能

### ISSUE THREAD

**Issue by ghost** [yanue/V2rayU#1111]
感谢作者，很好的软件，希望加上测试节点网速的功能，还有pingspeed一直在测试中，应该也是一个bug

**Comment by zzz-one** [comment]
+1

**Comment by zzz-one** [comment]
> 感谢作者，很好的软件，希望加上测试节点网速的功能，还有pingspeed一直在测试中，应该也是一个bug

pingspeed在哪，是要新版吗，我3.3.0

**Comment by kun-list** [comment]
+1

**Comment by Dazhu10** [comment]
+1
