### ISSUE TITLE
切换节点后无效，需要off/on下才会更换

### ISSUE THREAD

**Issue by elonleebj** [yanue/V2rayU#1115]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v3.3.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
切换节点后，没有改变，还是上一个使用的节点，需要off/on 下才会更换。（通过【查看v2ray日志】和改为全局访问IP地址检测网站验证）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/xxxxxxxxxxxx/",
          "headers": {
            "host": "xxx.xxxxxxx.link"
          }
        },
        "tlsSettings": {
          "serverName": "xxx.xxxxxxx.link",
          "allowInsecure": false
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxxxxxx.link",
            "users": [
              {
                "id": "11111111-1111-1111-1111-4b9153cce3f7",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by sinict** [comment]
是的 我也碰到这个问题, 自从有一次切换节点原来的节点流量超了发现的

**Comment by keengrass** [comment]
相同的版本V3.3.0遇到相同的问题，很影响体验。
你正在使用的 V2RayU 和 Mac 版本 ？
Arm 64版 v3.3.0  （我的MAC版本是11.6.8，M1芯片）

你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
切换节点后，没有改变，还是上一个使用的节点，需要off/on 下才会更换。（通过【查看v2ray日志】和改为全局访问IP地址检测网站验证）

**Comment by elonleebj** [comment]
最近卸载（v3.3.0）了，重新安装后切换节点可以起作用了。未卸载前有过手动更新v2ray核心包，不知道之前的问题和这个有没有关系。
