### ISSUE TITLE
不是默认用xray了吗？为什么启动的还是v2ray？

### ISSUE THREAD

**Issue by iwoomi** [yanue/V2rayU#1118]
![image](https://user-images.githubusercontent.com/112089622/196422145-b15198ff-cd00-4272-9bd4-8a093950bc1a.png)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/112089622/196440572-2a2f4ed9-180f-4090-83ca-4176acff06bc.png">

**Comment by ipatpat** [comment]
实际是Xray 只是为了方便没有更改相关的路径与文件名
具体运行哪个版本可以查看软件日志

**Comment by iwoomi** [comment]
是的，我后来也发现了
