### ISSUE TITLE
10.14.5全局模式无法上网，PAC经常间接性的无法访问

### ISSUE THREAD

**Issue by hunao0221** [yanue/V2rayU#112]
最新版1.3.2全局模式无法上网，上一个版本也是一样，pac模式经常会出现无法连接的情况，重启一下就好了，不知道是不是个例

**Comment by hackershi** [comment]
一样，求修复

**Comment by Johnson1602** [comment]
也有同样的情况，但是全局可用，PAC经常出现无法连接，重启有时候也解决不了

**Comment by hackershi** [comment]
全局模式无法上网

**Comment by muwan** [comment]
我是pac无法使用，必须开启全局

**Comment by wanwanga** [comment]
我也是pac无法使用，必须开启全局，1.3.2版本

**Comment by tanningzhong** [comment]
我也是pac无法使用，必须开启全局，1.3.2版本

**Comment by Kevin-Winehouse** [comment]
pac模式用久了以后，突然就会无法访问。
重启一下又好了。求解决惹。

**Comment by hunao0221** [comment]
> pac模式用久了以后，突然就会无法访问。
> 重启一下又好了。求解决惹。

同样的情况，有时候要重启好几次

**Comment by Songkunda** [comment]
全局模式无法上网 PAC总断

**Comment by x6893** [comment]
> pac模式用久了以后，突然就会无法访问。
> 重启一下又好了。求解决惹。

同样的情况，让我总以为网络出了问题

**Comment by NeetMitotsu** [comment]
1.3.2版本, PAC模式不行,  全局模式可以

**Comment by yanue** [comment]
未找到具体原因

**Comment by Luxuslaerm** [comment]
我也是pac模式间歇性失效，chrome左下角显示正在下载代理脚本，切换全局模式正常，版本1.4.0
