### ISSUE TITLE
V2rayU不能科学

### ISSUE THREAD

**Issue by adamnb1** [yanue/V2rayU#1120]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
版本3.30 mac系统 12.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
能正常启动，也能更新订阅，全局，PAC均能正常。PAC模式能访问国内，不能访问国外。全局模式哪里都不能访问。日志是空的，改了等级仍然是空的。换内核或者不换内核都是这样。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
{
  "log": {
    "error": "",
    "loglevel": "warning",
    "access": ""
  },
  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "servers": [
          {
            "port": 443,
            "method": "chacha20-ietf",
            "password": "mblank1port",
            "address": "",
            "level": 0,
            "email": "",
            "ota": false
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
日志空的
```

请预览一下你填的内容再提交。

**Comment by adamnb1** [comment]
同一节点，使用shadowsocksX-NG-R8能正常科学。我使用V2rayU的目的是为了使用自建的vmess节点。

**Comment by chimiansw** [comment]
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "servers": [
          {
            "port": 64443,
            "method": "aes-256-cfb",
            "password": "",
            "address": "",
            "level": 0,
            "email": "",
            "ota": false
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "IPOnDemand",
      "rules": [
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "localhost",
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {}
}


遇到这个问题了，日志是空的，跟上面一样，同一节点NG-R8正常

**Comment by adamnb1** [comment]
> 提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。 除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。
> 
> 1. 你正在使用的 V2RayU 和 Mac 版本 ？
>    版本3.30 mac系统 12.6
> 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    能正常启动，也能更新订阅，全局，PAC均能正常。PAC模式能访问国内，不能访问国外。全局模式哪里都不能访问。日志是空的，改了等级仍然是空的。换内核或者不换内核都是这样。
> 3. 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
> 
> ```js
>     // 在这里附上配置信息
> {
>   "log": {
>     "error": "",
>     "loglevel": "warning",
>     "access": ""
>   },
>   "inbounds": [
>     {
>       "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "tls",
>           "http"
>         ]
>       },
>       "listen": "127.0.0.1",
>       "protocol": "socks",
>       "settings": {
>         "udp": false,
>         "auth": "noauth"
>       },
>       "port": "1080"
>     },
>     {
>       "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "tls",
>           "http"
>         ]
>       },
>       "listen": "127.0.0.1",
>       "protocol": "http",
>       "settings": {
>         "timeout": 360
>       },
>       "port": "1087"
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "shadowsocks",
>       "streamSettings": {
>         "network": "tcp",
>         "tcpSettings": {
>           "header": {
>             "type": "none"
>           }
>         },
>         "security": "none"
>       },
>       "tag": "proxy",
>       "settings": {
>         "servers": [
>           {
>             "port": 443,
>             "method": "chacha20-ietf",
>             "password": "mblank1port",
>             "address": "",
>             "level": 0,
>             "email": "",
>             "ota": false
>           }
>         ]
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {
>         "domainStrategy": "UseIP",
>         "userLevel": 0
>       }
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {
>         "response": {
>           "type": "none"
>         }
>       }
>     }
>   ],
>   "dns": {},
>   "routing": {
>     "settings": {
>       "domainStrategy": "AsIs",
>       "rules": []
>     }
>   },
>   "transport": {}
> }
> ```
> 
> 4. 请附上出错时软件输出的错误日志。
> 
> ```js
>     // 在这里附上日志信息
> 日志空的
> ```
> 
> 请预览一下你填的内容再提交。

特来向大家报告一下。3.30不成功，3.20一次性成功

**Comment by elloop** [comment]
我是m1 max芯片 monterey系统，也遇到日志空白、无法科学的问题。 
折腾了一会发现， 在wifi设置中，把‘限制ip跟踪’去掉就好了。
