### ISSUE TITLE
M2笔记本上无法运行

### ISSUE THREAD

**Issue by quarkhe** [yanue/V2rayU#1123]
【Mac版本】
MacBook Pro (2022款）
芯片：M2

【V2rayU版本】
3.3.0

【现象】
点击程序，无任何反应，下面两个包都试过了
V2rayU-arm64.dmg
V2rayU-64.dmg

**Comment by onlyling** [comment]
M1 Pro
12.6.1 (21G217)
状态栏图标无法显示，12.6 没有问题。

彻底删除重新安装后依旧无法在状态栏看到图标。

打开活动监视器，触发安装 `Rosetta`，重新打开软件图标出现，奇奇怪怪。

**Comment by wumouse** [comment]
@onlyling 我在今天安装 Ventura 系统后也遇到这个问题，按你的方法，在简介里勾选通过 Rosetta 打开，安装 Rosetta 之后就可以显示 UI 了

**Comment by tantanorange** [comment]
M2的芯片，UI正常，可以显示所有服务器，但是就是连不上，试了PAC和GLOBAL都不行，Google登不上去。

**Comment by elloop** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/1855317/199545561-13484bf8-8772-41ab-9ba1-1b54e68ed7ff.png">

我是m1 max芯片 monterey系统，也遇到无法科学的问题。 折腾了一会发现，  在wifi设置中，把‘限制ip跟踪’去掉就好了。

**Comment by tantanorange** [comment]
> 超级感谢！我去试试

**Comment by mebtte** [comment]
试了一下, 需要安装 Rosetta 才能启动, 包括 arm64 的版本

**Comment by airunza** [comment]
同样的问题，目前没有解决。
新款macbook pro m2，安装后不显示图标，安装了罗塞塔可以打开了，但是无法上网。日志显示空白，限制ip跟踪也去掉了

**Comment by airunza** [comment]
另一台非m芯片的mac是可以用的，配置直接导到m2上用不了

**Comment by okerivy** [comment]
一样的问题，m2 芯片 系统 13.2 ， 无法联网，日志空白。
另一台 inter ，系统11.5，同样配置 正常运行。
没有解决，求帮助。

**Comment by CooljunS** [comment]
一样的问题，m2 芯片 系统 13.3 ， 无法联网，日志空白。

**Comment by raintiankunyu** [comment]
我的也是M2，进程里能看到在运行，菜单栏没有图标。最后发现是刘海屏把图标隐藏了。方法是把所有APP先关闭掉（command+Q），菜单栏就会有图标了。然后app商店找到免费的“Hidden Bar”。一切解决
