### ISSUE TITLE
如果配置了错误的订阅地址，v2rayu 则无法启动。

### ISSUE THREAD

**Issue by liufee** [yanue/V2rayU#1125]

**Comment by chinaht** [comment]
rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist

**Comment by chinaht** [comment]
rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist

**Comment by liufee** [comment]
解决了，感谢～
