### ISSUE TITLE
V2RayU在M1 Ventura上完全打不开

### ISSUE THREAD

**Issue by KailinLi** [yanue/V2rayU#1127]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.3.0(https://github.com/yanue/V2rayU/tree/3.3.0)
MacBook m1 2020版本，最新Ventura系统

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
安装成功后完全打不开。
第一次点击出现安全提示，解决之后，完全打不开，点击图标没有反应。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
无配置，没有成功打开过

4)  请附上出错时软件输出的错误日志。

install /Applications/V2rayU.app/Contents/Resources
launchedBefore true false
not install
2022-10-28 16:09:08.836 V2rayU[11773:260659] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSConcreteTask terminationStatus]: task not launched'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180de4418 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000018092eea8 objc_exception_throw + 60
	2   Foundation                          0x0000000181cdd530 -[NSConcreteTask dealloc] + 0
	3   V2rayU                              0x0000000100dbec38 V2rayU + 76856
	4   V2rayU                              0x0000000100db5e94 V2rayU + 40596
	5   V2rayU                              0x0000000100db68ac V2rayU + 43180
	6   CoreFoundation                      0x0000000180d5d9d8 -[NSSet makeObjectsPerformSelector:] + 176
	7   AppKit                              0x0000000183fa2a68 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 828
	8   AppKit                              0x0000000183f985d8 loadNib + 340
	9   AppKit                              0x0000000183f97c08 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 560
	10  AppKit                              0x0000000183f9790c -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 180
	11  AppKit                              0x0000000183f97730 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 300
	12  AppKit                              0x0000000183f8aed0 NSApplicationMain + 488
	13  V2rayU                              0x0000000100db21e4 V2rayU + 25060
	14  dyld                                0x000000018095fe50 start + 2544
)
libc++abi: terminating with uncaught exception of type NSException
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
zsh: abort      /Applications/V2rayU.app/Contents/MacOS/V2rayU

**Comment by cn-zhixiang** [comment]
+1。本来 3.2 一直可以正常用，升级了 3.3 后就打不开了，点击应用完全没有反应。重新安装 3.2 也不行

**Comment by LrWangLei** [comment]
+1 m1 pro 和楼主情况完全一样

**Comment by retme7** [comment]
+1 same issue

**Comment by crayonXXin** [comment]
+1 m1 pro macos 12.0.1 和楼主情况完全一样

**Comment by h2ohorse** [comment]
遇到了同样的问题，bartender没有隐藏图标，通过monitor查看进程也没有发现。

**Comment by raintiankunyu** [comment]
我的也是M2，进程里能看到在运行，菜单栏没有图标。最后发现是刘海屏把图标隐藏了。方法是把所有APP先关闭掉，菜单栏就会有图标了。然后app商店找到免费的“Hidden Bar”。一切解决
