### ISSUE TITLE
无法彻底退出V2ray

### ISSUE THREAD

**Issue by popsc30** [yanue/V2rayU#1128]
**已参考ISSUE链接：**
https://github.com/yanue/V2rayU/issues/225
#256  
#474

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v3.3.0/Mac M1 Monterey
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法彻底退出V2ray;
过程如下：
1. 查看v2ray进程，得知v2ray PID 为43439；
2. 杀掉v2ray，结果得知v2rayU被杀掉，但是v2ray并没有，推断出v2ray以ROOT启动；
3. sudo 杀掉v2ray，并再次查看v2ray进程，发现PID变更为43624，推断出sudo成功杀掉，但是`launchctl`又自动启动v2ray；
4. 查看v2ray自启动信息列表，得知`yanue.v2rayu.v2ray-core`在其中;
5. 通过`launchctl remove yanue.v2rayu.v2ray-core` 成功删除，再次查看v2ray进程，发现成功关闭并不再自动启动；
如上倒还好，**但是一旦再次打开V2rayU应用，则v2ray又在launchctl列表中，上面问题再次循环**

测试过程截图如下：
![process](https://i.imgur.com/z3MPC2d.png)

**Comment by lunacory** [comment]
我也发现了这个问题

退出V2rayU后，v2ray进程并没有退出。
把v2ray进程强制退出后，过一会儿v2ray进程又自启动了……

**Comment by e788b1** [comment]
launchctl remove yanue.v2rayu.v2ray-core

**Comment by WoodSong** [comment]
> 我也发现了这个问题
> 
> 退出V2rayU后，v2ray进程并没有退出。 把v2ray进程强制退出后，过一会儿v2ray进程又自启动了……

+1 希望可以解决

**Comment by WoodSong** [comment]
> 我也发现了这个问题
> 
> 退出V2rayU后，v2ray进程并没有退出。 把v2ray进程强制退出后，过一会儿v2ray进程又自启动了……

+1 希望可以解决

**Comment by newfuture33** [comment]
It will help you
do {
    try safeShell("launchctl remove com.teon.v2ray.v2ray-core")
}
catch {
    print("\(error)") //handle or silence the error here
}


@discardableResult // Add to suppress warnings when you don't want/need a result
func safeShell(_ command: String) throws -> String {
    let task = Process()
    let pipe = Pipe()
    
    task.standardOutput = pipe
    task.standardError = pipe
    task.arguments = ["-c", command]
    task.executableURL = URL(fileURLWithPath: "/bin/zsh") //<--updated
    task.standardInput = nil

    try task.run() //<--updated
    
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    let output = String(data: data, encoding: .utf8)!
    
    return output
}
