### ISSUE TITLE
Mac Ventura 无法科学上网？大家有遇到同样的问题嘛

### ISSUE THREAD

**Issue by Mario-Kong** [yanue/V2rayU#1129]
升级完 Ventura之后就无法科学上网了，其它UU们有遇到这个问题吗？如何解决？

**Comment by BLkubin** [comment]
一样的情况

**Comment by Mario-Kong** [comment]
> 一样的情况

有找到解决方案不？

**Comment by BLkubin** [comment]
> > 一样的情况
> 
> 有找到解决方案不？

正在关注此问题，希望有高手来解决

**Comment by Piggy-Knight** [comment]
系统更新为Ventura 13.0 (22A380)后问题解决

**Comment by Mario-Kong** [comment]
问了官方，目前没有直接的解决方案。只能回退到Monterey。
今天回退之后一切正常。
建议在这方面有需求的朋友谨慎升级！

ps：部分Adobe软件也出现了兼容性问题。

**Comment by lingyurunxin** [comment]
昨天刚刚更新，没有什么问题

**Comment by Mario-Kong** [comment]
我已收到您的邮件，感谢！

**Comment by chenjunbiao** [comment]
求助！ 有解决办法不？

**Comment by wv1124** [comment]
本地1080端口都不会启动，应该作者代码还没写完吧

**Comment by Mario-Kong** [comment]
我已收到您的邮件，感谢！

**Comment by Mario-Kong** [comment]
我已收到您的邮件，感谢！
