### ISSUE TITLE
更新服务器，及内核后，无法翻墙

### ISSUE THREAD

**Issue by Ruixu05** [yanue/V2rayU#113]
之前梯子被墙，重新换了个梯子，更新了一下内核就无法使用了

**Comment by Ruixu05** [comment]
2019/06/12 11:43:04 [Info] [2638563591] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2019/06/12 11:43:04 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain  at server udp::53 > context deadline exceeded
2019/06/12 11:43:04 [Info] v2ray.com/core/app/router: failed to resolve IP for domain > v2ray.com/core/app/dns: returning nil for domain  > context deadline exceeded
2019/06/12 11:43:04 [Info] v2ray.com/core/app/dispatcher: default route for udp::53
2019/06/12 11:43:04 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:04 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain ios.rqd.qq.com at server udp::53 > context deadline exceeded
2019/06/12 11:43:04 [Info] [3162180794] v2ray.com/core/app/router: failed to resolve IP for domain > v2ray.com/core/app/dns: returning nil for domain ios.rqd.qq.com > context deadline exceeded
2019/06/12 11:43:04 [Info] [3162180794] v2ray.com/core/app/dispatcher: default route for tcp:ios.rqd.qq.com:443
2019/06/12 11:43:04 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:04 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:04 [Info] v2ray.com/core/transport/internet/kcp: #49703 creating connection to 95.179.251.25:37176
2019/06/12 11:43:04 [Info] [3162180794] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:ios.rqd.qq.com:443 via tcp:95.179.251.25:37176
2019/06/12 11:43:04 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:05 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:05 [Debug] v2ray.com/core/transport/internet/kcp: #49691 entering state 1 at 27110
2019/06/12 11:43:05 [Info] v2ray.com/core/transport/internet/kcp: #49691 closing connection to 95.179.251.25:37176
2019/06/12 11:43:05 [Info] [3654226661] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/06/12 11:43:05 [Info] [3654226661] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2019/06/12 11:43:05 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:06 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/kcp: failed to dial to dest: dial udp 95.179.251.25:37176: operation was canceled > dial udp 95.179.251.25:37176: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/12 11:43:06 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
2019/06/12 11:43:07 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain android.clients.google.com at server udp::53 > context deadline exceeded
2019/06/12 11:43:07 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain  at server udp::53 > context deadline exceeded
2019/06/12 11:43:07 [Info] v2ray.com/core/app/router: failed to resolve IP for domain > v2ray.com/core/app/dns: returning nil for domain  > context deadline exceeded
2019/06/12 11:43:07 [Info] [645120978] v2ray.com/core/app/router: failed to resolve IP for domain > v2ray.com/core/app/dns: returning nil for domain android.clients.google.com > context deadline exceeded
2019/06/12 11:43:07 [Info] v2ray.com/core/app/dispatcher: default route for udp::53
2019/06/12 11:43:07 [Info] [645120978] v2ray.com/core/app/dispatcher: default route for tcp:android.clients.google.com:443
2019/06/12 11:43:07 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:07 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:07 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:07 [Info] v2ray.com/core/transport/internet/kcp: #49704 creating connection to 95.179.251.25:37176
2019/06/12 11:43:07 [Info] [645120978] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:android.clients.google.com:443 via tcp:95.179.251.25:37176
2019/06/12 11:43:07 [Debug] v2ray.com/core/transport/internet/kcp: #49681 sending terminating cmd.
2019/06/12 11:43:07 [Info] [4111113834] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2019/06/12 11:43:07 [Debug] v2ray.com/core/transport/internet/kcp: #49692 entering state 1 at 26941
2019/06/12 11:43:07 [Info] v2ray.com/core/transport/internet/kcp: #49692 closing connection to 95.179.251.25:37176
2019/06/12 11:43:07 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:95.179.251.25:37176
2019/06/12 11:43:07 [Info] [4111113834] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/06/12 11:43:07 [Debug] v2ray.com/core/app/log: Logger closing

**Comment by yanue** [comment]
这个是v2ray问题,或配置问题
