### ISSUE TITLE
测试ping之后一直显示“ping speed测试中”，重启程序之后也是一样

### ISSUE THREAD

**Issue by CometYZ** [yanue/V2rayU#1131]
版本3.3.0，系统macos13.0。使用的是导入订阅，所以服务器列表比较多

**Comment by claire9** [comment]
出现同样的问题，覆盖重装也不能解决 3.3.0  系统 macOS 11.6.1

**Comment by Tipeman** [comment]
同，蒙特雷，无限卡在这里，导入的也显示invalid v2ray config,一直在ping不通状态。

**Comment by rachaellovecA** [comment]
同上，无法更新、无法连接订阅已经好几天了， 3.3.0 系统 macOS Monterey 12.6.1;此外在手机上官网也上不去了

**Comment by Tipeman** [comment]
解决了，appcleaner卸载v2rayu再重装重新导入解决的，bug依然存在。

**Comment by xartisan** [comment]
bug

**Comment by shaonhuang** [comment]
> 

看了一下，源码，编译打包了，我发现3.3.0的代码和版号都没问题，这个bug是fix的，我估计是作者上传错了软件到release中。我@一下作者

**Comment by Xu-Nan** [comment]
同样的问题，解决了吗？

**Comment by Xu-Nan** [comment]
> 

系统macos13.3，版本3.3.0

**Comment by CometYZ** [comment]
> 同样的问题，解决了吗？

最近没有这种情况了，可能是因为更新了xray内核，也可能是因为换了订阅链接

**Comment by shaonhuang** [comment]
我打算开个新项目了，有兴趣可以关注一下
➡️ [V2rayX](https://github.com/shaonhuang/V2rayX.git)

**Comment by CometYZ** [comment]
> 我打算开个新项目了，有兴趣可以关注一下,watch or star
> ➡️ [V2rayX](https://github.com/shaonhuang/V2rayX.git)

不错，期待一下
