### ISSUE TITLE
Global mode does not put MacOs terminals behind VPN (vmess)

### ISSUE THREAD

**Issue by hosseink33** [yanue/V2rayU#1139]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2Ray 3.2.0
MacOS BigSur 11.6.5 (MacbookPro 2.6 GHz 6-Core Intel Core i7)

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
After connecting, browsers (Chrome) go behind the server (vmess) but terminal (ITerm and Mac Terminal) are not behind VPN. I found WhatsApp and Slack to be behind VPN (so looks like it's an issue with having terminal apps behind proxy)

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
   {
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/",
          "headers": {
            "host": ""
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "----",
            "users": [
              {
                "id": "----",
                "alterId": 0,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": *****
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。

I can confirm in the terminal (via speedtest cli) that traffic is not behind VPN. I also got blocked when I tried to access a restricted website via terminal.

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by ipatpat** [comment]
It provides terminal command specific for terminal proxy. You can copy it form the V2rayU menu.

**Comment by StephTruong** [comment]
> It provides terminal command specific for terminal proxy. You can copy it form the V2rayU menu.

could you give more detail on how to copy from the menu?

**Comment by vanenshi** [comment]
> > It provides terminal command specific for terminal proxy. You can copy it form the V2rayU menu.
> 
> could you give more detail on how to copy from the menu?

<img width="296" alt="image" src="https://user-images.githubusercontent.com/61600246/210089275-4d4f2010-fe57-40eb-9b60-c64125d0833e.png">

**Comment by amerllica** [comment]
Is it possible to have `VPN mode` rather than global mode, like [`nekoray`](https://github.com/MatsuriDayo/nekoray)
