### ISSUE TITLE
10.14.5  应用程序“V2rayU.app”不能打开

### ISSUE THREAD

**Issue by ZimriGeek** [yanue/V2rayU#114]
把发布的版本基本都试了一遍。 提示 应用程序“V2rayU.app”不能打开。无法使用 没有错误日志

**Comment by ZimriGeek** [comment]
exec of /Applications/V2rayU.app/Contents/Resources/v2ray-core/v2ray denied since it was quarantined by Microsoft\x20Remote\x20Desktop and created without user consent, qtn-flags was 0x00000186

**Comment by yanue** [comment]
参考readme,全部卸载,或appcleaner卸载试一下

**Comment by ZimriGeek** [comment]
恢复重装了系统，登陆了Apple ID 进入系统 仍然提示 不能打开... 日志一样

第二次恢复了重装了系统 没有登陆Apple ID 进入系统 仍然 不能打开... 日志一样

尝试找到了另一台一样系统一样环境的电脑 打开 就能出现 “来自不明身份开发者xxxxx”提示 通过设置放行 能正常打开！
**重点**：把这个环境下之前安装过的同类软件卸载后... 在打开 就出现了一样的问题 无法打开！

可能：macOS 10.14.5 引起的，寻求解决方法 谢谢！

**Comment by yanue** [comment]
你的其他软件也有这个问题吧? 你去google看下了

**Comment by ZimriGeek** [comment]
仅仅是v2ray核心的所有macOS端app 均有问题，其他软件能正常安装使用

**Comment by yanue** [comment]
你去替换一下v2ray-core文件,目录:
```
/Applications/V2rayU.app/Contents/Resources/
```

**Comment by caicaiyining** [comment]
我的 v2rayx 也遇到相同问题，
解决方法是不用下载、解压、运行。
改为通过 Homebrew 方式安装：
brew cask install v2rayx
绝对好使。

**Comment by baofeidyz** [comment]
我今天重新抹盘安装了系统，也遇到了这个问题，我用了
https://github.com/yanue/V2rayU/issues/114#issuecomment-532558547
提供的思路成功解决问题。不知道具体的原因 但问题肯定是出在macOS上面。

**Comment by Andrew5** [comment]
我在MAC电脑上安装了V2rayU 软件，我点击服务器设置->订阅管理，添加了一个https://losadhwselfff2332dasd.xyz/link/E44QpUctNcW2193S?sub=2
这个地址  结果V2rayU软件 就崩了，然后就再也打不开了，重新安装也不行，大家有遇到过吗？

**Comment by BlessFruit** [comment]
> 我在MAC电脑上安装了V2rayU 软件，我点击服务器设置->订阅管理，添加了一个https://losadhwselfff2332dasd.xyz/link/E44QpUctNcW2193S?sub=2
> 这个地址 结果V2rayU软件 就崩了，然后就再也打不开了，重新安装也不行，大家有遇到过吗？

我也是，请问你解决了吗
