### ISSUE TITLE
安装3.0，3.1，3.2几个版本都无法翻墙

### ISSUE THREAD

**Issue by yumohuike** [yanue/V2rayU#1141]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.0，3.1，3.2；Mac版本：10.15.7
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
没有反应
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
2022/11/17 13:20:47 [Info] infra/conf/serial: Reading config: config.json
2022/11/17 13:20:47 [Info] app/dns: DNS: created localhost client
2022/11/17 13:20:47 [Info] transport/internet/tcp: listening TCP on xxxxx
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: xxxxx
> transport/internet/tcp: failed to listen TCP on xxxx > listen tcp xxxxx: bind: address already in use
```

请预览一下你填的内容再提交。

**Comment by yumohuike** [comment]
有人遇到过这个问题吗

**Comment by yanue** [comment]
换端口

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yumohuike ***@***.***>
发送时间: Thursday, November 17, 2022 1:30:59 PM
收件人: yanue/V2rayU ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [yanue/V2rayU] 安装3.0，3.1，3.2几个版本都无法翻墙 (Issue #1141)


有人遇到过这个问题吗

―

**Comment by rui-helloworld** [comment]
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: aes-256-cfb

**Comment by winslis2** [comment]
> Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: aes-256-cfb

我的日志里也是报这个错，因为我是同时使用shadowsocks和V2rayU ，不知道是哪里代理设置搞错了，我是把V2rayU卸载了，只使用https://github.com/qinyuhang/ShadowsocksX-NG-R/releases

**Comment by benjaminyin01** [comment]
bind: address already in use
unknown cipher method: aes-256-cfb
------------
你们两个眼瞎啊
