### ISSUE TITLE
V2RayU无法用自己已经连接成功的代理去更新自己?

### ISSUE THREAD

**Issue by macgg** [yanue/V2rayU#1150]
V2RayU: 3.3.0
Mac: Ventura 13.0.1

V2rayU可以成功连接代理, 也可以成功访问外网网页. 但是点击"Check for Updates"
却显示Update Error!

估计是没有给自己的update程序配置访问代理?

**Comment by williamlee1982** [comment]
我这里也有同样的问题

**Comment by yxo1oyx** [comment]
一样，同款问题
