### ISSUE TITLE
v2ray gets started on system startup and creates a permanent connection

### ISSUE THREAD

**Issue by amzaf** [yanue/V2rayU#1159]
If I exit v2rayU, I expect that the v2ray process also exit. When I restart the system, the v2ray process gets launched on startup, no matter what the launch on startup setting is. This is highly undesirable and needs immediate attention because the v2ray process connects to the last selected server and accepts inbound connections.

**Comment by sunner** [comment]
Yes, I meet the same problem on macOS 13.1. The v2ray process can be switched off through System Settings -> General -> Login items.

**Comment by sunner** [comment]
Yes, I meet the same problem on macOS 13.1. The v2ray process can be switched off through System Settings -> General -> Login items.
