### ISSUE TITLE
连接不上，用v2rayX却可以。

### ISSUE THREAD

**Issue by activeliang** [yanue/V2rayU#116]
v2rayU的Log提示：
`V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1080 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1080 > listen tcp 127.0.0.1:1080: bind: address already in use`
检查了，只开了这么一个代理。
用了指令`kill -9 $(lsof -i tcp:1080 -t)`重试也不行。

v2rayU有订阅功能，scan QR code功能，所以相比v2rayX我更想用v2rayU，特来求助。

**Comment by yanue** [comment]
端口占用了 改端口试下

**Comment by activeliang** [comment]
灰常感谢，换了端口，成功了！
