### ISSUE TITLE
希望大佬能加入clah自动测速及分流就好了

### ISSUE THREAD

**Issue by lxtx528** [yanue/V2rayU#1161]
希望大佬能加入clah自动测速及分流就好了，这样体验就更好了。或者加入延迟排名也行，这样能更好的选择和使用节点，提高使用效率，如果能优化一下握手延迟就更妙了，还有希望能够同步支持及更新最新的xray内核，永远支持。

**Comment by shaonhuang** [comment]
建议是动手改代码，pull一下，一块提升功能，众人拾柴火焰高，有兴趣一块做吗？
