### ISSUE TITLE
在pac设置中填入了不适用的地址导致程序崩溃且无法启动（稳定触发）

### ISSUE THREAD

**Issue by CometYZ** [yanue/V2rayU#1162]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2rayu 3.3.0，macos13.1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
导入ss机场链接并开启内核后，在pac设置中填入了https://r0uter.github.io/gfw_domain_whitelist/whitelist.pac ，点击更新gfwlist，程序会闪退且无法再次启动，重启电脑后依旧，完全卸载重装后恢复正常。相同的步骤尝试多次均可以触发该问题，具体见以下视频：https://drive.google.com/file/d/1Yr7aSBprHGecWQ8wssiq8gaw5RDCeng4/view?usp=sharing

**Comment by shaonhuang** [comment]
因为读取配置文件问题,删除以下文件重新配置即可
~/Library/Preferences/net.yanue.V2rayU.plist

源码上是遇到了无法解析都value, var lines = str!.components(separatedBy: CharacterSet.newlines)。str为空，解决问题的最简单都做法是执行一下命令。

`rm ~/Library/Preferences/net.yanue.V2rayU.plist`
