### ISSUE TITLE
Delete servers

### ISSUE THREAD

**Issue by 1mehdifaraji** [yanue/V2rayU#1163]
How can we delete already imported servers on mac m1 Ventura 13.1 ?

**Comment by shaonhuang** [comment]
Is there a button to do that?
<img width="597" alt="image" src="https://user-images.githubusercontent.com/68820540/213871196-4409ac0d-57c9-4989-bfc7-21672b21e95a.png">

**Comment by 1mehdifaraji** [comment]
@shaonhuang Thanks for the image I found the section to delete servers I don't need .

![Screenshot 1401-11-02 at 00 33 29](https://user-images.githubusercontent.com/63982703/213887113-717fb2b8-0ef6-4226-949d-f2091f63dfe2.png)
