### ISSUE TITLE
Connection fail 

### ISSUE THREAD

**Issue by 1mehdifaraji** [yanue/V2rayU#1164]
The v2ray app is not working recently on MacM1 Ventura 13.1

v2ray.log file : 

```
2023/01/25 09:28:59 [Warning] [892951696] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://isegaro.ddns.net:2083/omega):  > x509: “*.researchgate.net” certificate name does not match input] > common/retry: all retry attempts failed
2023/01/25 09:28:59 [Info] [892951696] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/01/25 09:28:59 [Warning] [1392239340] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://isegaro.ddns.net:2083/omega):  > x509: “*.researchgate.net” certificate name does not match input] > common/retry: all retry attempts failed
2023/01/25 09:28:59 [Info] [1392239340] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/01/25 09:28:59 [Warning] [1775662408] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://isegaro.ddns.net:2083/omega):  > x509: “*.researchgate.net” certificate name does not match input] > common/retry: all retry attempts failed
2023/01/25 09:28:59 [Info] [1775662408] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
```
Ruby version : 
```
ruby-3.0.0 [ arm64 ]
```

**Comment by guoqingXibei** [comment]
试试把 WiFi 设置里面的乱七八糟的 DNS 删掉

**Comment by Shaniplax** [comment]
> The v2ray app is not working recently on MacM1 Ventura 13.1
> 
> v2ray.log file :
> 
> ```
> 2023/01/25 09:28:59 [Warning] [892951696] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://isegaro.ddns.net:2083/omega):  > x509: “*.researchgate.net” certificate name does not match input] > common/retry: all retry attempts failed
> 2023/01/25 09:28:59 [Info] [892951696] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
> 2023/01/25 09:28:59 [Warning] [1392239340] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://isegaro.ddns.net:2083/omega):  > x509: “*.researchgate.net” certificate name does not match input] > common/retry: all retry attempts failed
> 2023/01/25 09:28:59 [Info] [1392239340] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
> 2023/01/25 09:28:59 [Warning] [1775662408] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://isegaro.ddns.net:2083/omega):  > x509: “*.researchgate.net” certificate name does not match input] > common/retry: all retry attempts failed
> 2023/01/25 09:28:59 [Info] [1775662408] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
> ```
> 
> Ruby version :
> 
> ```
> ruby-3.0.0 [ arm64 ]
> ```

سلام داداش
