### ISSUE TITLE
希望增加全局的 allowInsecure 选项

### ISSUE THREAD

**Issue by ghost** [yanue/V2rayU#1165]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

### 1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU: 3.3.0
macOS: 13.1

### 2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

我使用justmysocks机场，Transport Type选了TCP + TLS，但是justmysocks使用了dummy domain + 自签证书，所以要求app端开启allowInsecure，justmysocks的文档信息：

> IMPORTANT: If you are choosing TCP+TLS, we will generate a certificate for a dummy domain name example.com.
> This is done to avoid blocking based on certificate domain name.
> This, however, requires setting TLS option allowInsecure to True in your app

V2RayU 虽然可以针对单个 server 设置 allowInsecure = true，但是我更新订阅后，allowInsecure 又恢复到了默认的 false，于是又要逐个 server 去勾选一遍 allowInsecure，很麻烦。

希望能和 Android 上的 v2rayNG 一样，有个全局的 allowInsecure 开关（为了安全性，默认allowInsecure = false，但是提供开关给了用户全局设置allowInsecure的机会），v2rayNG的设置界面如下图：

![saa](https://user-images.githubusercontent.com/123873634/215327282-84f994a4-bb40-4635-98a9-fab388500e58.png)

另外，我理解 allowInsecure、TLS、中间人攻击的含义，但是有些机场的想法可能不太一样，比如justmysocks在使用 TCP + TLS时，vmess还是选择了aes-128-gcm加密，并没有使用none/zero，因此被中间人攻击后，并不会导致用户信息泄漏，只是增加了机场server被封的概率，也许这是justmysocks在权衡了维护复杂度、服务器负载、节点被封后切换的成本后的选择？我也不太清楚。

真心的感谢您开发和维护了 V2RayU 这么优秀的软件～

### 3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
{
  "log": {
    "error": "",
    "loglevel": "none",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxx.xxx.xxx",
            "users": [
              {
                "id": "xxxxxxxxxxxxxx",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": xxxxx
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```

### 4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by pkuliubin** [comment]
附议
