### ISSUE TITLE
服务器列表那里能否增加分组和按ping排序功能

### ISSUE THREAD

**Issue by OCer** [yanue/V2rayU#1167]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V3.3.0   M1  系统13.1 
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
 - 能否增加分组功能呢？？
我现在有2个订阅，一个是按月付费，一个是按流量付费（不限使用时间），一般来说，我都是优先使用按月付费的，而按流量付费只是备用，当目前我没办法判断哪个节点是哪个订阅的

 - 能否增加按ping排序功能？
每次ping了之后，需要在上百个节点里找到最好的，挺麻烦的

- 能否增加自动隐藏无效节点功能呢？
同理，在上百的节点里，有些在某个时候不可用，希望能隐藏掉，减少节点列表里的数据

**Comment by YasinZhou** [comment]
+1, 迫切需要分组和排序功能

**Comment by CometYZ** [comment]
同感，要是可以像clash一样可以自动切换节点就更好了

**Comment by CrassusX** [comment]
ping并不是最靠谱的，建议参考v2rayNG的测试全部配置真连接+按测试结果排序
