### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by winsonhet** [yanue/V2rayU#117]
每次订阅updte后产生大量的server，有什么方法可以批量删除以前的server？

**Comment by yanue** [comment]
从configure里面进去，先全部删除，然后再更新订阅
后面会优化

**Comment by winsonhet** [comment]
好的,谢谢
现在只能先从configure进去,一个个的删除后,再更新订阅了吧?
有没有快捷的方法?订阅产生的server是存在哪个文件中,直接对文件编辑,会方便一些

**Comment by yanue** [comment]
已修复:1.3.3
