### ISSUE TITLE
v2ray testing ping

### ISSUE THREAD

**Issue by keivanmj** [yanue/V2rayU#1170]
v2ray says its testing ping all the time
it never stops testing
and there are no results
it just says in testing and it never ends

**Comment by Snow-S0** [comment]
me too, v2ray can't be used

**Comment by Acer-Raosysu123** [comment]
+1, can anyone fix this bug? thanks a lot

**Comment by Acer-Raosysu123** [comment]
V2Ray is a proxy tool that can be used to bypass network restrictions and
improve network security. When you see the message "testing ping all the
time," it likely means that V2Ray is trying to establish a connection to a
server and is checking the network latency. If the connection cannot be
established or if the network latency is too high, the testing process may not
complete, and you may see the message "in testing" indefinitely.
There could be a few reasons for this issue:
1 Network connectivity: Make sure that your device has a stable
internet connection and that the firewall or antivirus software is not blocking
the connection.
2 Server configuration: The server you are trying to connect to
may be down or may not be configured correctly. Try connecting to a
different server or contact the server administrator for more information.
3 V2Ray configuration: The V2Ray configuration file may be
incorrect or outdated. Try updating the configuration file or creating a new
one. If you continue to experience issues with V2Ray, you may want to seek help
from the V2Ray community or consult the V2Ray documentation for more
information.

**Comment by faceback** [comment]
YES! ME TOO, is Mac M1 os issues?

**Comment by keivanmj** [comment]
> YES! ME TOO, is Mac M1 os issues?
I have an intel mac.
it still doesn't work

**Comment by ShuBo6** [comment]
an ye yi yang!

**Comment by ShuBo6** [comment]
> an ye yi yang!

m1max mac book pro

**Comment by lightsaid** [comment]
同样问题，脑壳疼～
