### ISSUE TITLE
V2rayU-arm64.dmg macos 12.6 无法打开“V2rayU”，因为Apple无法检查其是否包含恶意软件

### ISSUE THREAD

**Issue by Nevernamed** [yanue/V2rayU#1179]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // V2rayU-arm64.dmg  MacOS12.6 M2芯片
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 无法打开“V2rayU”，因为Apple无法检查其是否包含恶意软件。
    //此软件需要更新。请联系开发者了解更多信息。
```

请问怎么解决？

**Comment by BrainT** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app

**Comment by BrainT** [comment]
亲，收到您的邮件了！暂时潜水，回头给你回复~_~
