### ISSUE TITLE
SSR订阅的都用不了

### ISSUE THREAD

**Issue by iewgnaw** [yanue/V2rayU#118]
两个订阅的地址shadowsocksX-NG-R8里都是可以的，同样的订阅地址拿过来能更新到节点信息，但是上网都失败

第一个订阅的：
 > exit status 255
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
main: failed to read config file: config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: aes-128-ctr

第二个订阅的：

2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
2019/06/15 07:44:43 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/15 07:44:44 [Info] [2995540330] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [clients4.google.com:443] with URL [//clients4.google.com:443]
2019/06/15 07:44:44 127.0.0.1:50007 accepted //clients4.google.com:443  
2019/06/15 07:44:44 [Info] [2995540330] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
2019/06/15 07:44:44 [Info] [2995540330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:hkt01.susanoocloud.com:443
2019/06/15 07:44:44 [Info] [2995540330] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:clients4.google.com:443 via tcp:hkt01.susanoocloud.com:443
2019/06/15 07:44:44 [Info] [2995540330] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: connection ends > v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF
2019/06/15 07:44:44 [Info] [2995540330] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/06/15 07:44:44 127.0.0.1:50010 accepted //clients4.google.com:443  
2019/06/15 07:44:44 [Info] [880706429] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [clients4.google.com:443] with URL [//clients4.google.com:443]
2019/06/15 07:44:44 [Info] [880706429] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
2019/06/15 07:44:44 [Info] [880706429] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:hkt01.susanoocloud.com:443
2019/06/15 07:44:44 [Info] [880706429] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:clients4.google.com:443 via tcp:hkt01.susanoocloud.com:443
2019/06/15 07:44:44 [Info] [880706429] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: connection ends > v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF

版本是最新的

**Comment by Jasonx0716** [comment]
I have the same question

**Comment by Stark1937** [comment]
我现在订阅、设置一样，  shadowsocksX-NG-R8 和 V2rayU 都用不了，ShadowsocksX-NG可以用

**Comment by yanue** [comment]
官方只支持几种cipher method,这边补齐了  不一定能用,请下载1.3.3试下
