### ISSUE TITLE
mac下可以正常启动，但是无法翻墙(同样的配置在手机上使用小火箭可以)

### ISSUE THREAD

**Issue by fengyueran** [yanue/V2rayU#1180]
1.V2RayU 和 Mac 版本 
mac:11.2.3
<img width="257" alt="image" src="https://user-images.githubusercontent.com/17682887/221558626-f16efa35-caab-49cb-bb42-50289572319d.png">
v2rayu:3.3.0
<img width="195" alt="image" src="https://user-images.githubusercontent.com/17682887/221558773-2779bec8-4fde-46ac-8afc-42917c5a2229.png">

2.问题
可以正常启动，但是无法翻墙

3.配置
```
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xx",
            "users": [
              {
                "id": "db541f69-4a27-4dfd-9033-3d30337d1f4d",
                "alterId": 64,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": 30645
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```

4.日志
```
2023/02/27 19:24:37 127.0.0.1:57356 accepted //www.google.com:443 [proxy]
2023/02/27 19:24:38 [Info] [1491593779] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via xx:30645
2023/02/27 19:24:38 [Info] [1176443082] proxy/http: request to Method [CONNECT] Host [beacons.gvt2.com:443] with URL [//beacons.gvt2.com:443]
2023/02/27 19:24:38 127.0.0.1:57362 accepted //beacons.gvt2.com:443 [proxy]
2023/02/27 19:24:38 [Info] [1176443082] app/dispatcher: default route for tcp:beacons.gvt2.com:443
2023/02/27 19:24:38 [Info] [1176443082] transport/internet/tcp: dialing TCP to tcp:xx:30645
2023/02/27 19:24:38 [Info] [1176443082] proxy/vmess/outbound: tunneling request to tcp:beacons.gvt2.com:443 via xx:30645
2023/02/27 19:24:39 [Info] [1113089720] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2023/02/27 19:24:39 [Info] [1113089720] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/02/27 19:24:40 [Info] [1116444384] proxy/http: request to Method [CONNECT] Host [api.infinitynewtab.com:443] with URL [//api.infinitynewtab.com:443]
2023/02/27 19:24:40 [Info] [1116444384] app/dispatcher: default route for 
```

**Comment by wanghuiwan** [comment]
me too

**Comment by EeveeNye** [comment]
没新版本吗-。-？

**Comment by nbgwh1234** [comment]
我也是这种情况

**Comment by guoqingXibei** [comment]
试试把 WiFi 设置里面的乱七八糟的 DNS 删掉

**Comment by songzenghui** [comment]
我也是这样的问题。用windows电脑就可以

**Comment by HillKubeo** [comment]
我也有同样问题，但情况有不同，头1分钟能正常工作，之后就不行，手机上和WIN上都正常
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vless",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "xtlsSettings": {
          "serverName": “***********”,
          "allowInsecure": false
        },
        "security": "xtls",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "207.148.105.56",
            "users": [
              {
                "encryption": "none",
                "id": “*************************”，
                "level": 0,
                "flow": "xtls-rprx-direct"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}




Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2021/10/14 14:16:08 [Info] infra/conf/serial: Reading config: config.json
2021/10/14 14:16:08 [Info] app/dns: DNS: created localhost client
2021/10/14 14:16:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/10/14 14:16:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1087
2021/10/14 14:16:08 [Warning] core: Xray 1.4.2 started
2021/10/14 14:16:09 [Info] [2883643807] proxy/socks: TCP Connect request to tcp:clients2.google.com:443
2021/10/14 14:16:09 [Info] [2883643807] app/dispatcher: default route for tcp:clients2.google.com:443
2021/10/14 14:16:09 [Info] [2883643807] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:09 tcp:127.0.0.1:49932 accepted tcp:clients2.google.com:443 [proxy]
2021/10/14 14:16:09 [Info] [2883643807] proxy/vmess/outbound: tunneling request to tcp:clients2.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:16:10 [Info] [1504742165] proxy/socks: TCP Connect request to tcp:r4---sn-j5o76n7l.gvt1.com:80
2021/10/14 14:16:10 [Info] [1504742165] app/dispatcher: default route for tcp:r4---sn-j5o76n7l.gvt1.com:80
2021/10/14 14:16:10 [Info] [1504742165] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:10 tcp:127.0.0.1:49936 accepted tcp:r4---sn-j5o76n7l.gvt1.com:80 [proxy]
2021/10/14 14:16:11 [Info] [1504742165] proxy/vmess/outbound: tunneling request to tcp:r4---sn-j5o76n7l.gvt1.com:80 via tcp:167.179.64.170:8888
2021/10/14 14:16:12 [Info] [3370228247] proxy/socks: TCP Connect request to tcp:r2---sn-oguesn6s.gvt1.com:80
2021/10/14 14:16:12 [Info] [3370228247] app/dispatcher: default route for tcp:r2---sn-oguesn6s.gvt1.com:80
2021/10/14 14:16:12 [Info] [3370228247] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:12 tcp:127.0.0.1:49939 accepted tcp:r2---sn-oguesn6s.gvt1.com:80 [proxy]
2021/10/14 14:16:12 [Info] [3370228247] proxy/vmess/outbound: tunneling request to tcp:r2---sn-oguesn6s.gvt1.com:80 via tcp:167.179.64.170:8888
2021/10/14 14:16:15 [Info] [2662842349] proxy/socks: TCP Connect request to tcp:accounts.google.com:443
2021/10/14 14:16:15 [Info] [2662842349] app/dispatcher: default route for tcp:accounts.google.com:443
2021/10/14 14:16:15 [Info] [2662842349] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:15 tcp:127.0.0.1:49941 accepted tcp:accounts.google.com:443 [proxy]
2021/10/14 14:16:15 [Info] [2662842349] proxy/vmess/outbound: tunneling request to tcp:accounts.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:16:15 [Info] [122472299] proxy/socks: TCP Connect request to tcp:ocsp.pki.goog:80
2021/10/14 14:16:15 [Info] [122472299] app/dispatcher: default route for tcp:ocsp.pki.goog:80
2021/10/14 14:16:15 [Info] [122472299] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:15 tcp:127.0.0.1:49943 accepted tcp:ocsp.pki.goog:80 [proxy]
2021/10/14 14:16:16 [Info] [122472299] proxy/vmess/outbound: tunneling request to tcp:ocsp.pki.goog:80 via tcp:167.179.64.170:8888
2021/10/14 14:16:24 [Info] [3241965835] proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2021/10/14 14:16:24 [Info] [3241965835] app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2021/10/14 14:16:24 [Info] [3241965835] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:24 tcp:127.0.0.1:49946 accepted tcp:content-autofill.googleapis.com:443 [proxy]
2021/10/14 14:16:25 [Info] [3241965835] proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:16:43 [Info] [2795199372] proxy/socks: TCP Connect request to tcp:play.google.com:443
2021/10/14 14:16:43 [Info] [2795199372] app/dispatcher: default route for tcp:play.google.com:443
2021/10/14 14:16:43 [Info] [2795199372] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:43 tcp:127.0.0.1:49955 accepted tcp:play.google.com:443 [proxy]
2021/10/14 14:16:45 [Info] [2795199372] proxy/vmess/outbound: tunneling request to tcp:play.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:16:48 [Info] [930305091] proxy/socks: TCP Connect request to tcp:www.google.com:443
2021/10/14 14:16:48 [Info] [930305091] app/dispatcher: default route for tcp:www.google.com:443
2021/10/14 14:16:48 [Info] [930305091] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:16:48 tcp:127.0.0.1:49958 accepted tcp:www.google.com:443 [proxy]
2021/10/14 14:16:49 [Info] [930305091] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:46 [Info] [3123520983] proxy/socks: TCP Connect request to tcp:www.googleapis.com:443
2021/10/14 14:17:46 [Info] [3123520983] app/dispatcher: default route for tcp:www.googleapis.com:443
2021/10/14 14:17:46 [Info] [3123520983] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:46 tcp:127.0.0.1:49960 accepted tcp:www.googleapis.com:443 [proxy]
2021/10/14 14:17:46 [Info] [3123520983] proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:46 [Info] [122472299] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2021/10/14 14:17:46 [Info] [122472299] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:17:47 [Info] [3308715927] proxy/socks: TCP Connect request to tcp:android.clients.google.com:443
2021/10/14 14:17:47 [Info] [3308715927] app/dispatcher: default route for tcp:android.clients.google.com:443
2021/10/14 14:17:47 [Info] [3308715927] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:47 tcp:127.0.0.1:49962 accepted tcp:android.clients.google.com:443 [proxy]
2021/10/14 14:17:47 [Info] [3308715927] proxy/vmess/outbound: tunneling request to tcp:android.clients.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:47 [Info] [2295020537] proxy/socks: TCP Connect request to tcp:clients4.google.com:443
2021/10/14 14:17:47 [Info] [2295020537] app/dispatcher: default route for tcp:clients4.google.com:443
2021/10/14 14:17:47 [Info] [2295020537] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:47 tcp:127.0.0.1:49964 accepted tcp:clients4.google.com:443 [proxy]
2021/10/14 14:17:48 [Info] [2295020537] proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:48 [Info] [3748074169] proxy/socks: TCP Connect request to tcp:lh3.googleusercontent.com:443
2021/10/14 14:17:48 [Info] [3748074169] app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
2021/10/14 14:17:48 [Info] [3748074169] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:48 [Info] [2783773480] proxy/socks: TCP Connect request to tcp:lh3.googleusercontent.com:443
2021/10/14 14:17:48 [Info] [2783773480] app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
2021/10/14 14:17:48 [Info] [2783773480] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:48 tcp:127.0.0.1:49966 accepted tcp:lh3.googleusercontent.com:443 [proxy]
2021/10/14 14:17:48 tcp:127.0.0.1:49967 accepted tcp:lh3.googleusercontent.com:443 [proxy]
2021/10/14 14:17:48 [Info] [3748074169] proxy/vmess/outbound: tunneling request to tcp:lh3.googleusercontent.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:48 [Info] [2783773480] proxy/vmess/outbound: tunneling request to tcp:lh3.googleusercontent.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:48 [Info] [3420438642] proxy/socks: TCP Connect request to tcp:mtalk.google.com:5228
2021/10/14 14:17:48 [Info] [3420438642] app/dispatcher: default route for tcp:mtalk.google.com:5228
2021/10/14 14:17:48 [Info] [3420438642] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:48 tcp:127.0.0.1:49970 accepted tcp:mtalk.google.com:5228 [proxy]
2021/10/14 14:17:49 [Info] [3420438642] proxy/vmess/outbound: tunneling request to tcp:mtalk.google.com:5228 via tcp:167.179.64.170:8888
2021/10/14 14:17:49 [Info] [1134543167] proxy/socks: TCP Connect request to tcp:ocsp.pki.goog:80
2021/10/14 14:17:49 [Info] [1134543167] app/dispatcher: default route for tcp:ocsp.pki.goog:80
2021/10/14 14:17:49 [Info] [1134543167] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:49 tcp:127.0.0.1:49972 accepted tcp:ocsp.pki.goog:80 [proxy]
2021/10/14 14:17:49 [Info] [1163975034] proxy/socks: TCP Connect request to tcp:lh3.googleusercontent.com:443
2021/10/14 14:17:49 [Info] [1163975034] app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
2021/10/14 14:17:49 [Info] [1163975034] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:49 tcp:127.0.0.1:49974 accepted tcp:lh3.googleusercontent.com:443 [proxy]
2021/10/14 14:17:49 [Info] [3225128185] proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2021/10/14 14:17:49 [Info] [3225128185] app/dispatcher: default route for tcp:www.gstatic.com:443
2021/10/14 14:17:49 [Info] [3225128185] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:49 tcp:127.0.0.1:49976 accepted tcp:www.gstatic.com:443 [proxy]
2021/10/14 14:17:49 [Info] [505109298] proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2021/10/14 14:17:49 [Info] [505109298] app/dispatcher: default route for tcp:www.gstatic.com:443
2021/10/14 14:17:49 [Info] [505109298] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:49 [Info] [830610319] proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2021/10/14 14:17:49 [Info] [830610319] app/dispatcher: default route for tcp:www.gstatic.com:443
2021/10/14 14:17:49 [Info] [830610319] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:49 tcp:127.0.0.1:49978 accepted tcp:www.gstatic.com:443 [proxy]
2021/10/14 14:17:49 tcp:127.0.0.1:49979 accepted tcp:www.gstatic.com:443 [proxy]
2021/10/14 14:17:49 [Info] [1134543167] proxy/vmess/outbound: tunneling request to tcp:ocsp.pki.goog:80 via tcp:167.179.64.170:8888
2021/10/14 14:17:49 [Info] [830610319] proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:49 [Info] [505109298] proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:49 [Info] [1163975034] proxy/vmess/outbound: tunneling request to tcp:lh3.googleusercontent.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:49 [Info] [1163975034] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:1080->127.0.0.1:49974: writev: broken pipe
2021/10/14 14:17:49 [Info] [1163975034] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:17:50 [Info] [3225128185] proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:50 [Info] [3225128185] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:17:50 [Info] [3225128185] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2021/10/14 14:17:51 [Info] [806607177] proxy/socks: TCP Connect request to tcp:apis.google.com:443
2021/10/14 14:17:51 [Info] [806607177] app/dispatcher: default route for tcp:apis.google.com:443
2021/10/14 14:17:51 [Info] [806607177] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:51 tcp:127.0.0.1:49982 accepted tcp:apis.google.com:443 [proxy]
2021/10/14 14:17:51 [Info] [806607177] proxy/vmess/outbound: tunneling request to tcp:apis.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:17:52 [Info] [830610319] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:17:52 [Info] [830610319] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/10/14 14:17:55 [Info] [3295386344] proxy/socks: TCP Connect request to tcp:ogs.google.com:443
2021/10/14 14:17:55 [Info] [3295386344] app/dispatcher: default route for tcp:ogs.google.com:443
2021/10/14 14:17:55 [Info] [3295386344] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:17:55 tcp:127.0.0.1:49984 accepted tcp:ogs.google.com:443 [proxy]
2021/10/14 14:17:55 [Info] [3295386344] proxy/vmess/outbound: tunneling request to tcp:ogs.google.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [2176322331] proxy/socks: TCP Connect request to tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [2176322331] app/dispatcher: default route for tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [2176322331] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:18:00 tcp:127.0.0.1:49991 accepted tcp:firebaseperusertopics-pa.googleapis.com:443 [proxy]
2021/10/14 14:18:00 [Info] [2410078940] proxy/socks: TCP Connect request to tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [1549618419] proxy/socks: TCP Connect request to tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [1549618419] app/dispatcher: default route for tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [1549618419] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:18:00 tcp:127.0.0.1:49988 accepted tcp:firebaseperusertopics-pa.googleapis.com:443 [proxy]
2021/10/14 14:18:00 tcp:127.0.0.1:49987 accepted tcp:firebaseperusertopics-pa.googleapis.com:443 [proxy]
2021/10/14 14:18:00 tcp:127.0.0.1:49989 accepted tcp:firebaseperusertopics-pa.googleapis.com:443 [proxy]
2021/10/14 14:18:00 tcp:127.0.0.1:49986 accepted tcp:firebaseperusertopics-pa.googleapis.com:443 [proxy]
2021/10/14 14:18:00 [Info] [2410078940] app/dispatcher: default route for tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [2410078940] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:18:00 tcp:127.0.0.1:49990 accepted tcp:firebaseperusertopics-pa.googleapis.com:443 [proxy]
2021/10/14 14:18:00 [Info] [3608478181] proxy/socks: TCP Connect request to tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [3608478181] app/dispatcher: default route for tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [3608478181] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [1405774347] proxy/socks: TCP Connect request to tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [1405774347] app/dispatcher: default route for tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [1405774347] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [4199337264] proxy/socks: TCP Connect request to tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [4199337264] app/dispatcher: default route for tcp:firebaseperusertopics-pa.googleapis.com:443
2021/10/14 14:18:00 [Info] [4199337264] transport/internet/tcp: dialing TCP to tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [3608478181] proxy/vmess/outbound: tunneling request to tcp:firebaseperusertopics-pa.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [4199337264] proxy/vmess/outbound: tunneling request to tcp:firebaseperusertopics-pa.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [1549618419] proxy/vmess/outbound: tunneling request to tcp:firebaseperusertopics-pa.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [2176322331] proxy/vmess/outbound: tunneling request to tcp:firebaseperusertopics-pa.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [2410078940] proxy/vmess/outbound: tunneling request to tcp:firebaseperusertopics-pa.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [1405774347] proxy/vmess/outbound: tunneling request to tcp:firebaseperusertopics-pa.googleapis.com:443 via tcp:167.179.64.170:8888
2021/10/14 14:18:00 [Info] [882022521] app/proxyman/inbound: connection ends > proxy/socks: failed to read request > proxy/socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:49998: read: connection reset by peer
2021/10/14 14:18:00 tcp:127.0.0.1:49998 rejected  proxy/socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:49998: read: connection reset by peer
2021/10/14 14:18:01 [Info] [2176322331] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:1080->127.0.0.1:49991: writev: broken pipe
2021/10/14 14:18:01 [Info] [2176322331] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:18:01 [Info] [1549618419] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > write tcp 127.0.0.1:1080->127.0.0.1:49988: write: broken pipe
2021/10/14 14:18:01 [Info] [1549618419] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:18:02 [Info] [2410078940] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:18:02 [Info] [1405774347] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:18:02 [Info] [2410078940] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2021/10/14 14:18:02 [Info] [1405774347] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2021/10/14 14:18:03 [Info] [4199337264] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/10/14 14:18:03 [Info] [4199337264] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/10/14 14:18:04 [Info] [2295571926] proxy/socks: TCP Connect request to tcp:clients2.googleusercontent.com:443

**Comment by fengyueran** [comment]
> 试试把 WiFi 设置里面的乱七八糟的 DNS 删掉

么有用

**Comment by imxintian** [comment]
同样的问题，Intel macOS13.2.1 升级完版本3.3.0之后一直无法正常访问外网，可以ping通
日志部分报错：
>
2023/03/12 23:36:33 [Info] [636654934] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: drained connection > proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2023/03/12 23:36:33 [Info] [636654934] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/03/12 23:36:33 [Info] [229813841] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2023/03/12 23:36:33 [Info] [229813841] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/03/12 23:36:33 [Info] [161642141] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2023/03/12 23:36:33 [Info] [161642141] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by fengyueran** [comment]
> 

我降到3.2.0还是一样的问题

**Comment by imxintian** [comment]
> > 切换到master分支 看到作者有一个彻底卸载v2rayU的方法

cd ~/Library/LaunchAgents/
/bin/launchctl remove yanue.v2rayu.v2ray-core
/bin/launchctl remove yanue.v2rayu.http

rm -f ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -f ~/Library/Preferences/net.yanue.V2rayU.plist
rm -f ~/Library/Logs/V2rayU.log

删除完后 再降版本 试一试
> 
> 
> 
> 我降到3.2.0还是一样的问题

**Comment by ttototooo** [comment]
怎么降版本呢？

**Comment by ttototooo** [comment]
好的 谢谢～

在 2023年4月4日星期二，imxintian ***@***.***> 写道：

**Comment by Dazhu10** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by HillKubeo** [comment]
我的可以了，換一個xray内核就行

**Comment by Dazhu10** [comment]
> 我的可以了，換一個xray内核就行

是怎么换的，有操作方法吗

**Comment by sysonlai** [comment]
Replace /Applications/V2rayU.app/Contents/Resources/v2ray-core/xray with latest version https://github.com/chaitin/xray

**Comment by wb94** [comment]
> 我的可以了，换一个xray内核就可以了

您好，请问怎么换内核

**Comment by HillKubeo** [comment]
下載新內核，mac系統，前往所有程序，右击v2rayu，打開顯示包内容，contents,resources,v2ray-core替換新內核

**Comment by careubaby** [comment]
> 下載新內核，mac系統，前往所有程序，右击v2rayu，打開顯示包内容，contents,resources,v2ray-core替換新內核
您好，请问可以指导一下怎么改内核吗

**Comment by careubaby** [comment]
> 下載新內核，mac系統，前往所有程序，右击v2rayu，打開顯示包内容，contents,resources,v2ray-core替換新內核

您好，请问可以教一下怎么下载“内核”和替换“内核”吗 。这个代理没有客服对接真的已经两天上不了无法解决问题…………谢谢哦

**Comment by HillKubeo** [comment]
你代理之前能用的，現在不能用哪你要確定一下代理哪邊是否正常，

**Comment by fengyueran** [comment]
> 我的可以了，換一個xray内核就行

3.2/3.3换了俩macos的内核(Xray-macos-64，Xray-macos-arm64-v8a)仍然没用
