### ISSUE TITLE
mac mini m2 能打开软件，但是无法科学上网

### ISSUE THREAD

**Issue by ZKzhangkun** [yanue/V2rayU#1186]
V2rayU:2.3.0 , macos 13.2.1
启动日志：
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64)
A unified platform for anti-censorship.
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64)
A unified platform for anti-censorship.
2023/03/09 17:49:52 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
2023/03/09 17:49:52 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2023/03/09 17:49:52 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2023/03/09 17:49:52 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2023/03/09 17:49:52 [Warning] v2ray.com/core: V2Ray 4.23.1 started

<img width="775" alt="image" src="https://user-images.githubusercontent.com/31854020/223985258-4ec19b8e-a44a-4225-8c06-b817ecc1724e.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/31854020/223985581-a000c7cd-dadd-4cfa-a1b0-e463ca56e79d.png">

最新版本不行

请预览一下你填的内容再提交。

**Comment by ZZY1970** [comment]
刚换了M2Pro 芯片的机器，重新安装了客户端发现无法翻墙了。试了几个版本，似乎都不行。求指点！
