### ISSUE TITLE
请教：提示不支持"xtls-rprx-vision", 如何解决？

### ISSUE THREAD

**Issue by bylucky** [yanue/V2rayU#1188]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V3.3
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
提示不支持velss-vision,   我自己用Xray-core换名后替换掉目录里的【v2ray-core】，还是报错，
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
Failed to start: main: failed to load config files: [config.json] > infra/conf: 
VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
```

**Comment by luyang-yanglu** [comment]
我遇到了同样的问题：Failed to start: main: failed to load config files: [config.json] > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
但是我通过将flow设置为空，可以正常连接；但这不是个彻底的解决方式；
V2RayU似乎无法通过覆盖xray-core的方式实现xray核版本升级；
临时解决：
"settings": {
        "clients": [
          {
            "id": "d320dc97-76be-527e-9cd9-457fbfdf18fc",
            "flow": "xtls-rprx-vision,none",
            "level": 0,
            "email": "2446a573b8e8dc7@idleleo.com"
          }
        ]

**Comment by Ryan-Shang** [comment]
> 我遇到了同样的问题：Failed to start: main: failed to load config files: [config.json] > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64) 但是我通过将flow设置为空，可以正常连接；但这不是个彻底的解决方式； V2RayU似乎无法通过覆盖xray-core的方式实现xray核版本升级； 临时解决： "settings": { "clients": [ { "id": "d320dc_****5****f18fc", "flow": "xtls-rprx-vision,none", "level": 0, "email": "23****_com" } ]

```bash
cd ~

# mac Intel
wget https://github.com/XTLS/Xray-core/releases/download/v1.7.5/Xray-macos-64.zip
unzip Xray-macos-64.zip -d ~/Xray

 # mac m1
wget https://github.com/XTLS/Xray-core/releases/download/v1.7.5/Xray-macos-arm64-v8a.zip
unzip Xray-macos-arm64-v8a.zip -d ~/Xray

cp -r ~/.V2rayU/v2ray-core ~/.V2rayU/v2ray-core-bak
mv -r ~/Xray ~/.V2rayU/v2ray-core
cp ~/.V2rayU/v2ray-core/xray ~/.V2rayU/v2ray-core/v2ray # Don't forget this
sudo chmod 777 -r ~/.V2rayU/v2ray-core
```

**Comment by bylucky** [comment]
如果flow为空，就只是普通的 TLS 模式了， vision 更安全

**Comment by Ryan-Shang** [comment]
> 如果flow为空，就只是普通的 TLS 模式了， vision 更安全

Try replace xray-core by yourself.

**Comment by bylucky** [comment]
Thank you. It has worked normally.

**Comment by zeku2022** [comment]
替换之后我这好像还是有问题..

2023/04/16 14:45:05 [Warning] core: Xray 1.8.0 started
2023/04/16 14:45:12 [Info] [1288995234] proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2023/04/16 14:45:12 [Info] app/dns: Localhost got answer: content-autofill.googleapis.com -> [172.217.163.42 142.251.42.234 142.251.43.10 172.217.160.74 172.217.160.106]
2023/04/16 14:45:12 [Info] [1288995234] app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2023/04/16 14:45:12 [Info] [1288995234] transport/internet/tcp: dialing TCP to tcp:8.x.x.x.4.x3:443
2023/04/16 14:45:12 tcp:127.0.0.1:52753 accepted tcp:content-autofill.googleapis.com:443 [proxy]
2023/04/16 14:45:12 [Info] [1288995234] proxy/vless/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via 8.x.x.x.4.x3:443
2023/04/16 14:45:12 [Warning] [1288995234] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: XTLS only supports TCP, mKCP and DomainSocket for now.
2023/04/16 14:45:12 [Info] [1288995234] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/04/16 14:45:12 [Info] [16279412] proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2023/04/16 14:45:12 [Info] app/dns: Localhost got answer: content-autofill.googleapis.com -> [172.217.163.42 142.251.42.234 142.251.43.10 172.217.160.74 172.217.160.106]
2023/04/16 14:45:12 [Info] [16279412] app/dispatcher: default route for tcp:content-autofill.googleapis.com:443

**Comment by zeku2022** [comment]
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vless",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "8.x.x.x3",
            "users": [
              {
                "encryption": "none",
                "id": "54id..............b9",
                "level": 0,
                "flow": "xtls-rprx-vision"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "IPOnDemand",
      "rules": [
        {
          "type": "field",
          "outboundTag": "proxy",
          "domain": [
            "domain:api.binance.com"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "localhost",
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {}
}

**Comment by pensacola1989** [comment]
自动更新xray-core之后，又出这个问题了，服务端flow关闭还是一样

**Comment by AllenLiui** [comment]
> 自动更新xray-core之后，又出现这个问题了，服务端流关闭还是一样

解决了吗？ 我也用不了，v3.9.0版本，日志显示VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version

**Comment by oilfieldtools** [comment]
目前只有这个提示， FATAL[0000] create service: parse outbound[120]: unsupported flow: xtls-rprx-vision-udp443

我将configSpeedtest文件里的【xtls-rprx-vision-udp443】，改成【xtls-rprx-vision】
保存后，重新运行，无效，它自己还是恢复成【xtls-rprx-vision-udp443】
我目前是通过重新安装解决问题。
