### ISSUE TITLE
能打开，服务器列表配置正常，ping Speed正常，但是无法翻墙

### ISSUE THREAD

**Issue by pJBo** [yanue/V2rayU#1189]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

v.1.5.4版本；Mac版本12.4
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
能打开，服务器列表配置正常，ping Speed正常，但是无法翻墙。前几天都还可以翻墙，今天打开就无法翻墙了。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
2023/03/20 16:37:04 [Info] infra/conf/serial: Reading config: config.json
2023/03/20 16:37:04 [Info] app/dns: DNS: created localhost client
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
2023/03/20 16:37:14 [Info] infra/conf/serial: Reading config: config.json
2023/03/20 16:37:14 [Info] app/dns: DNS: created localhost client
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
2023/03/20 16:37:25 [Info] infra/conf/serial: Reading config: config.json
2023/03/20 16:37:25 [Info] app/dns: DNS: created localhost client
2023/03/20 16:37:25 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.
2023/03/20 16:37:35 [Info] infra/conf/serial: Reading config: config.json
2023/03/20 16:37:35 [Info] app/dns: DNS: created localhost client
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/amd64)
A unified platform for anti-censorship.

**Comment by yoeaki** [comment]
提示你的端口已经被占用，换一下端口试试
