### ISSUE TITLE
 无法打开V2RayU UI 页面 但是活动监视器显示在运行

### ISSUE THREAD

**Issue by UniqueFrank** [yanue/V2rayU#1190]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
  3.3.0            MacBook Pro 2021年 Apple M1 Max

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
  无法打开V2RayU软件UI 页面 但是活动监视器显示在运行 使用了Rosetta打开,也是打不开软件UI操作页面
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by UniqueFrank** [comment]
是否可以使用docker部署




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanue/V2rayU"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 晚上11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanue/V2rayU]  无法打开V2RayU UI 页面 但是活动监视器显示在运行 (Issue #1190)





 
同上，m2 max

**Comment by UniqueFrank** [comment]
> 同上，m2 max

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/93063347/228140143-ac803d4a-b872-486a-becd-fe1f69fc48be.png">
在上面任务栏钉钉使用全页面的时候显示了

**Comment by raintiankunyu** [comment]
我的也是M2，进程里能看到在运行，菜单栏没有图标。最后发现是刘海屏把图标隐藏了。方法是把所有APP先关闭掉（command+Q），菜单栏就会有图标了。然后app商店找到免费的“Hidden Bar”。一切解决，希望能够帮助到大家
