### ISSUE TITLE
试过自己和macbook和朋友的，结果都是没办法使用，软件能正常打开，vpn能挂上，但就是上不了网

### ISSUE THREAD

**Issue by 121546hhx** [yanue/V2rayU#1191]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by bigglory** [comment]
你可以检查一下自己下载的版本是否有问题，要下载自己mac 的芯片对应的软件版本，分为arm和 intel 版本的，新的M1，M2都是arm，之前的都是intel的

**Comment by 121546hhx** [comment]
试过很多版本，甚至系统我都重装过，会不会是现在不支持mac了

**Comment by WillamLi** [comment]
mac M1 遇到同样问题，可以挂上vpn， ping测试也有结果，但仍然不能上网

**Comment by careubaby** [comment]
我也是这样的问题，这个代理服务没有客服，只能提交工单，提交工单回复过来就说自己服务正常要我检查软件。我要是能检查出来我需要这么麻烦发工单？？？按照流程操作还是上不了网，也不出个报错的指导文件。这里要是有他们团队的人看见麻烦解决一下。

**Comment by winglight** [comment]
我也是同样问题，同样的代理在windows下正常翻墙，mac下就完全不行。我也是用的3.3.0，不知道newui能不能解决这个问题？

**Comment by yoeaki** [comment]
我也的是mac m1 pro,  版本是：3.3.0 arm版本，同样遇到这样的问题，能正常上网，但不能科学上网，vpn能挂上，ping也有反应。
请大佬帮看看是什么问题？
日志报错：2023/04/27 09:05:20 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: unknown cipher method: aes-256-cfb
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.

**Comment by winglight** [comment]
我发现有这种情况，隔一段时间，或者mac休眠之后，v2rayu十次有八次需要重连WiFi才能恢复翻墙，剩下一次是完全正常，最后一次是怎么也连不上，然后过一段时间自动恢复，这段时间可长可短，大约在半个小时到一两个小时之间吧。
