### ISSUE TITLE
pac文件可否加上openai？

### ISSUE THREAD

**Issue by XindongG** [yanue/V2rayU#1194]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by dddreee** [comment]
可以加啊，自己加就好了

**Comment by gisealine** [comment]
我看到 proxy.js中已经有了 ||openai.com，也重启了，就是用pac打不开，全局模式可以

**Comment by LittleMcdull** [comment]
我是这个么配置的，配置好了之后是可以使用的，可以参考一下能不能解决，**最后一步浏览就是看看能不能看到自己配置的地址就可以了**

<img width="460" alt="image" src="https://github.com/yanue/V2rayU/assets/42287098/f85d45b6-4231-42ff-b81d-5f9008b1204a">

**Comment by friendmine** [comment]
你这要求太难了，openai 用了cloudflare的服务，所以要加的是整个cloudflare的 ip
