### ISSUE TITLE
有个网站提供的vmess链接无法使用

### ISSUE THREAD

**Issue by zzzqqqhhh** [yanue/V2rayU#12]
https://xn--9iqx9sosjh0d.com/
但是在windows下用v2ray-n却可以用，是不是v2ray core版本太老呢？

**Comment by yanue** [comment]
同 #1, v2ray-core版本信息可以在 Preferences 查看
,你可以切换到4.0版本试一下

**Comment by zzzqqqhhh** [comment]
版本显示4.9。另外这个网站目前开放注册的，随便找个邮箱就行，里面提供一个免费vmess账号
