### ISSUE TITLE
M2 无法启动

### ISSUE THREAD

**Issue by piaoyunsoft** [yanue/V2rayU#1202]
install /Applications/V2rayU.app/Contents/Resources
launchedBefore true false
not install
2023-04-15 12:28:57.893 V2rayU[3464:40630] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSConcreteTask terminationStatus]: task not launched'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001ab58c3e8 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001ab0d6ea8 objc_exception_throw + 60
	2   Foundation                          0x00000001ac488300 -[NSConcreteTask dealloc] + 0
	3   V2rayU                              0x00000001007e2c38 V2rayU + 76856
	4   V2rayU                              0x00000001007d9e94 V2rayU + 40596
	5   V2rayU                              0x00000001007da8ac V2rayU + 43180
	6   CoreFoundation                      0x00000001ab5059ac -[NSSet makeObjectsPerformSelector:] + 176
	7   AppKit                              0x00000001ae777c84 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 828
	8   AppKit                              0x00000001ae76d7f4 loadNib + 340
	9   AppKit                              0x00000001ae76ce24 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 560
	10  AppKit                              0x00000001ae76cb28 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 180
	11  AppKit                              0x00000001ae76c94c +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 300
	12  AppKit                              0x00000001ae7600c8 NSApplicationMain + 488
	13  V2rayU                              0x00000001007d61e4 V2rayU + 25060
	14  dyld                                0x00000001ab107e50 start + 2544
)
libc++abi: terminating with uncaught exception of type NSException
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
[1]    3464 abort      /Applications/V2rayU.app/Contents/MacOS/V2rayU

**Comment by richardwei1297** [comment]
I have the same problem.

**Comment by SweeperDuan** [comment]
我M1也启动不了，有没有其他软件推荐

**Comment by jiluofu** [comment]
M系列可以该用appstore里的shadowrocket

**Comment by okerivy** [comment]
> M系列可以该用appstore里的shadowrocket

谢谢！
