### ISSUE TITLE
程序无法正常启动，没有任何日志输出，仿佛没有工作

### ISSUE THREAD

**Issue by GodayMax** [yanue/V2rayU#1213]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
MacOS 13
V2rayU 3.3.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
程序无法正常启动，没有任何日志输出，仿佛没有工作

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
<img width="733" alt="image" src="https://user-images.githubusercontent.com/8066122/236620555-db341535-4979-4d2c-9327-508af9541124.png">

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by huntersu** [comment]
首先 日志写在了~/Library/Logs/下面的v2ray-core.log

之后有了日志就好办了  会发现 程序还是去老的版本的位置(/Applications/V2rayU.app/Contents/Resources/)读取config.json文件，但是是不存在的，可以在配置好之后把~/.V2rayU/config.json文件拷贝到/Applications/V2rayU.app/Contents/Resources/下面重启应用就可以解决了

总体上这个文件我认为有可能是代码merge出问题把老的代码覆盖了新的，或者其他原因
