### ISSUE TITLE
自定义pac规则没有生效

### ISSUE THREAD

**Issue by gisealine** [yanue/V2rayU#1221]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU为最新版
Mac版本为Ventura

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
pac中添加了||openai.com，还是不能使用pac模式访问 chat.openai.com/chat, 用全局模式可以
我检查了proxy.js，只有一处有openai.com, 如图

![image](https://github.com/yanue/V2rayU/assets/5688675/c95495de-f5c5-4d92-8286-141da53b41cd)

**Comment by futureklaus** [comment]
同样的问题，找到解决方法了吗？
