### ISSUE TITLE
一次subscribe之后，v2rayu的icon就在任务栏消失，但是后台依然在运行ok，重启和重装都无济于事。

### ISSUE THREAD

**Issue by helxsz** [yanue/V2rayU#1223]
我的mac是11.7.6，intel的chip，运行最新的v2rayu版本。本来一直运行的很好，但是前两天subscribe一个链接之后，突然任务栏的icon就消失了，也就打不开UI界面。看到后台的v2ray一直运行的很好，即使是强制关闭，还是会自动重启。后来重启启动的mac，发现icon还是一样消失，默默的在后台运行而已。但是没有UI进行配置非常不方便，我没有卸载，只是重新下载最新版本安装，但依然是老的情况。

是要卸载掉重装，还是可以不卸载，在程序安装的文件夹里做些修改来还原么？

**Comment by benjaminyin01** [comment]
订阅造成无法启动的问题一直有，我遇到好多次。每次都得删除那个plist文件重新配置。

**Comment by helxsz** [comment]
最后的办法还是把v2ray重新删除，除了删除application的app，还要删除  /Users/(computer user name)/.V2rayU 的这个隐藏文件夹。 删除干净后，把v2rayu 的进程强制停止，就不会重新启动；或者简单重启。

然后重新安装之后又可以用了

**Comment by jiuqianyuan** [comment]
碰到了
