### ISSUE TITLE
V2RayU程序无法启动，点了没反应

### ISSUE THREAD

**Issue by jerfee** [yanue/V2rayU#1230]
macOS10.15.7 上V2rayU一直用的好好的，今天系统休眠后黑屏唤醒不了了，就强制重启了，结果重启后显示个提示说“将对你电脑造成伤害”启动不了，删掉重装也不行，后来网上查询提示说安全模式启动后执行“csrutil disable”就可以了，执行之后再启动，没有那个提示了，但是也没有反应，查看system.log 显示有下面的提示：
Jul  2 20:57:10 192 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000004.V2rayU[816]): removing service since it exited with consistent failure - OS_REASON_CODESIGNING | When validating /Applications/V2rayU.app/Contents/MacOS/V2rayU:
	  The code contains a Team ID, but validating its signature failed.
	Please check your system log.
Jul  2 20:57:10 192 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000004.V2rayU[816]): Binary is improperly signed.
Jul  2 20:57:35 192 com.apple.xpc.launchd[1] (com.apple.CloudDocs.MobileDocumentsFileProvider[736]): Service exited due to SIGKILL | sent by launchd[1]
有什么办法能够解决吗？

**Comment by alijafari97** [comment]
i have this problem too

**Comment by SeasonPilot** [comment]
i have this problem too

**Comment by llIIlloremm** [comment]
same problem

**Comment by jerfee** [comment]
问题解决，参考这个[：](https://github.com/yanue/V2rayU/issues/1235)
以及这个[：](https://github.com/yanue/V2rayU/issues/1234)
