### ISSUE TITLE
Mac Monoma 无法打开

### ISSUE THREAD

**Issue by kiradea** [yanue/V2rayU#1232]
<img width="294" alt="image" src="https://github.com/yanue/V2rayU/assets/12182992/e7df7ce2-2ada-469f-ae89-ddf88d9bbb4f">

**Comment by of1102** [comment]
same problem

**Comment by AI2Hub** [comment]
sudo spctl --master-disable
sudo codesign --force --deep --sign - /Applications/V2rayU.app

Try it

**Comment by sryanyuan** [comment]
访达-应用程序 v2rayu 右键-显示简介-覆盖恶意软件保护 打勾

**Comment by Ike-li** [comment]
> 访达-应用程序 v2rayu 右键-显示简介-覆盖恶意软件保护 打勾

<img width="558" alt="截屏2023-07-03 10 04 46" src="https://github.com/yanue/V2rayU/assets/50747621/a2ff6c40-fdbb-4b84-af69-2042337a4da1">

**Comment by kililixi** [comment]
> sudo spctl --master-disable sudo codesign --force --deep --sign - /Applications/V2rayU.app
> 
> Try it

谢谢，我是可以了，虽然会有恶意提示（即使钩上覆盖恶意软件保护），但是程序还是启动了的。

**Comment by sryanyuan** [comment]
> > 访达-应用程序 v2rayu 右键-显示简介-覆盖恶意软件保护 打勾
> 
> <img alt="截屏2023-07-03 10 04 46" width="558" src="https://user-images.githubusercontent.com/50747621/250426035-a2ff6c40-fdbb-4b84-af69-2042337a4da1.png">

看楼上的吧 我这个设置没法解决这个问题

**Comment by edith0126** [comment]
> sudo spctl --master-disable sudo codesign --force --deep --sign - /Applications/V2rayU.app
> 
> Try it

Didn't work

**Comment by edith0126** [comment]
> 访达-应用程序 v2rayu 右键-显示简介-覆盖恶意软件保护 打勾

没用 还是打不开

**Comment by Zheap** [comment]
换成version3.2.0版本就可以了

**Comment by kiradea** [comment]
> sudo spctl --master-disable sudo codesign --force --deep --sign - /Applications/V2rayU.app
> 
> Try it

试过了，不行

**Comment by kiradea** [comment]
> > > 访达-应用程序 v2rayu 右键-显示简介-覆盖恶意软件保护 打勾
> > 
> > 
> > <img alt="截屏2023-07-03 10 04 46" width="558" src="https://user-images.githubusercontent.com/50747621/250426035-a2ff6c40-fdbb-4b84-af69-2042337a4da1.png">
> 
> 看楼上的吧 我这个设置没法解决这个问题

试过了不行

**Comment by Zheap** [comment]
换成3.2.0版本

**Comment by Ike-li** [comment]
> 换成3.2.0版本

换成3.2.0版本，我的代理服务器就用不了了。
https://github.com/yanue/V2rayU/issues/1189

**Comment by Voine** [comment]
按照 https://github.com/yanue/V2rayU/issues/697 把已有版本完全卸载，然后再安装 3.2 即可，否则代理无法生效

**Comment by Voine** [comment]
> > 换成3.2.0版本
> 
> 换成3.2.0版本，我的代理服务器就用不了了。 #1189

把已有的完全卸载再试试，否则卸载会有残留，安装 3.2 也没用

**Comment by kavilee** [comment]
13.4.1系统换了3.2.0也打不开遇到过吗

> > > 换成3.2.0版本
> > 
> > 
> > 换成3.2.0版本，我的代理服务器就用不了了。 #1189
> 
> 把已有的完全卸载再试试，否则卸载会有残留，安装 3.2 也没用
