### ISSUE TITLE
应用程序“V2rayU.app”无法打开

### ISSUE THREAD

**Issue by chubin518** [yanue/V2rayU#1233]
![image](https://github.com/yanue/V2rayU/assets/5813060/eb424a93-e006-478d-9e4d-6e48d384ad07)

系统版本：12.6.5

**Comment by yaoyue** [comment]
+1，M1 13.4.1，苹果不停弹框：`V2rayU.app”将对您的电脑造成伤害。
您应该将它移到废纸篓。`

**Comment by Zheap** [comment]
换成version3.2.0版本就可以了

**Comment by yaoyue** [comment]
> 换成version3.2.0版本就可以了

感谢，我试试 ~

**Comment by Voine** [comment]
按照 https://github.com/yanue/V2rayU/issues/697 把已有版本完全卸载，然后再安装 3.2 即可，否则代理无法生效

**Comment by chubin518** [comment]
> 按照 #697 把已有版本完全卸载，然后再安装 3.2 即可，否则代理无法生效

感谢，我试下

**Comment by jiuqianyuan** [comment]
3.4版本的好像也没用
