### ISSUE TITLE
苹果电脑弹出提示要求删除v2rayu

### ISSUE THREAD

**Issue by lxtx528** [yanue/V2rayU#1236]
疯狂弹出提示，要求删除v2ray核心及v2ayu，说会伤害电脑。系统版本catalina10.15.7。

**Comment by Diluka** [comment]
点取消完全没得用，只有删除了，不然疯狂弹窗没法用电脑了

**Comment by papandadj** [comment]
这程序是个bug吧，才发现一直在后台启动，删除也没用

**Comment by zanjie1999** [comment]
证书过期了app得重新签名

**Comment by Ike-li** [comment]
wait for repair

**Comment by papandadj** [comment]
不太清楚是不是cleanmymac抱的错误， 我感觉是它弹的框，现在只能卸载了

**Comment by yanue** [comment]
@zanjie1999 证书过期发新版后 旧版本还是无法使用了吗?

**Comment by zanjie1999** [comment]
> @zanjie1999 证书过期发新版后 旧版本还是无法使用了吗?

如你所见，现在证书过期了，打不开了，又没有发布新版，所以只能自己签一下用

**Comment by 4ever911** [comment]
> 证书过期了app得重新签名
> 
> 临时解决办法 先打开一次，报错不用管，终端跑以下命令，输入登录密码按回车，密码不会显示
> 
> ```
> sudo codesign --force --deep --sign - /Applications/V2rayU.app
> sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```
> 
> 在应用程序里找到他，右键，显示简介，勾选 覆盖恶意软件保护 然后再打开就可以用了，用不了就重头再来一次

我刚更新的系统，这个解决了问题。

**Comment by marklitle** [comment]
> 证书过期了app得重新签名
> 
> 临时解决办法 先打开一次，报错不用管，终端跑以下命令，输入登录密码按回车，密码不会显示
> 
> ```
> sudo codesign --force --deep --sign - /Applications/V2rayU.app
> sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```
> 
> 在应用程序里找到他，右键，显示简介，勾选 覆盖恶意软件保护 然后再打开就可以用了，用不了就重头再来一次

怒赞
管用

**Comment by godwinjavaee** [comment]
‘xxx‘ “将对您的电脑造成伤害。 您应该将它移到废纸篓。”mac一直弹窗并关不掉的解决方式

10.15.1之后的系统：

在终端输入：csrutil status

如果返回值为：System Integrity Protection status: enabled

说明MAC系统SIP保护开启了，关闭SIP保护即可

重新启动MAC电脑，https://support.apple.com/zh-cn/HT204904

如果使用的是搭载 Apple 芯片的 Mac
1. 按住 Mac 上的电源按钮。如果你继续按住电源按钮，则 Mac 会开机并载入启动选项。当你看到“选项”时，松开电源按钮。
2. 点按“选项”，然后点按在它下方显示的“继续”按钮。
3. 如果系统要求你选择一个你知道相应密码的用户，请选择这样的用户，点按“下一步”，然后输入用户的管理员密码。

如果使用的是基于 Intel 的 Mac
1. 按下 Mac 上的电源按钮以开机，然后松开电源按钮并立即同时按住 Command (⌘) 键和 R 键，直到看到 Apple 标志或旋转的地球。如果你无法通过这种方式从恢复模式启动，请查阅[有关使用启动组合键的准则](https://support.apple.com/zh-cn/HT201255#guidelines)。
2.  如果系统要求你选择一个你知道相应密码的用户，请选择这样的用户，点按“下一步”，然后输入用户的管理员密码。 

进入恢复环境，在恢复环境打开终端

输入csrutil disable

重新启动系统后，再次输入csrutil status，应该显示为disable

**Comment by ZZY1970** [comment]
> ‘xxx‘ “将对您的电脑造成伤害。 您应该将它移到废纸篓。”mac一直弹窗并关不掉的解决方式
> 
> 10.15.1之后的系统：
> 
> 在终端输入：csrutil status
> 
> 如果返回值为：System Integrity Protection status: enabled
> 
> 说明MAC系统SIP保护开启了，关闭SIP保护即可
> 
> 重新启动MAC电脑，https://support.apple.com/zh-cn/HT204904
> 
> 如果使用的是搭载 Apple 芯片的 Mac
> 
> 1. 按住 Mac 上的电源按钮。如果你继续按住电源按钮，则 Mac 会开机并载入启动选项。当你看到“选项”时，松开电源按钮。
> 2. 点按“选项”，然后点按在它下方显示的“继续”按钮。
> 3. 如果系统要求你选择一个你知道相应密码的用户，请选择这样的用户，点按“下一步”，然后输入用户的管理员密码。
> 
> 如果使用的是基于 Intel 的 Mac
> 
> 1. 按下 Mac 上的电源按钮以开机，然后松开电源按钮并立即同时按住 Command (⌘) 键和 R 键，直到看到 Apple 标志或旋转的地球。如果你无法通过这种方式从恢复模式启动，请查阅[有关使用启动组合键的准则](https://support.apple.com/zh-cn/HT201255#guidelines)。
> 2. 如果系统要求你选择一个你知道相应密码的用户，请选择这样的用户，点按“下一步”，然后输入用户的管理员密码。
> 
> 进入恢复环境，在恢复环境打开终端
> 
> 输入csrutil disable
> 
> 重新启动系统后，再次输入csrutil status，应该显示为disable

这个方法试过了，不管用。

**Comment by rust17** [comment]
可以试试清空废纸篓，可能是因为移除到废纸篓并没有真正删除

**Comment by zhoufanscut** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app 执行了这句之后可以正常启动了, 参考: https://blog.csdn.net/weixin_39628380/article/details/113086761

**Comment by vicoqi** [comment]
> 证书过期了app得重新签名
> 
> 临时解决办法 先打开一次，报错不用管，终端跑以下命令，输入登录密码按回车，密码不会显示
> 
> ```
> sudo codesign --force --deep --sign - /Applications/V2rayU.app
> sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```
> 
> 在应用程序里找到他，右键，显示简介，勾选 覆盖恶意软件保护 然后再打开就可以用了，用不了就重头再来一次，多试几次肯定能好
> 
> 另外如果遇到了提示无法验证是否是恶意软件，可以打开系统设置，安全与隐私，通用，下面有个仍然打开的按钮，点一下并且选择打开，退出app再重新打开，这么重复几次之后，就不会再弹了

感谢感谢，怒赞很有用👍，确实证书过期了。昨天明明好的，突然不行了。

**Comment by willemswang** [comment]
> sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app 执行了这句之后可以正常启动了, 参考: https://blog.csdn.net/weixin_39628380/article/details/113086761

其余办法都不生效，就这个命令解决了我的问题，怒赞！
