### ISSUE TITLE
MacOS Ventura Detect it as a Malware!

### ISSUE THREAD

**Issue by dariusdarwish** [yanue/V2rayU#1239]
Hello dear, from last day I can not use v2rayU on macOS Ventura because the OS detects it as untrusted/malware with an unknown source/date. I've tried to reinstall it from your latest version on GitHub but did not work.

**Comment by yanue** [comment]
#1238

**Comment by Dongjie-orange** [comment]
the same question on my mac (version 13.3.1 (22E261))

**Comment by jayden-studio** [comment]
我也有  怎么解决呢

**Comment by RichardLuo** [comment]
same problem with me ventura 13.4.1

**Comment by ZZY1970** [comment]
the same like that, 版本13.3.1 (a) (22E772610a)

**Comment by mattt-s** [comment]
me too

**Comment by ZZY1970** [comment]
证书过期问题导致的：

第一步，执行sudo codesign --force --deep --sign - /Applications/V2rayU.app

第二步，在应用程序中找到V2rayU，右键，显示简介，勾选覆盖恶意软件保护

第三步，打开软件

第四部，执行下面2个命令
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
然后就能正常运行了。
