### ISSUE TITLE
请问如何彻底删除v2rayU呢

### ISSUE THREAD

**Issue by qizhengyang2017** [yanue/V2rayU#1240]
我按照#1238里的建议可以重新安装v2rayU，但是它还是不断的跳出弹框，"v2rayU将对你的电脑造成伤害..."。我又将v2rayU卸载，还是相同的问题。然后我又删了～/.V2rayU，重启之后还是同样的问题。而且现在可能因为删了这个目录，我没有办法再安装V2rayU了。求大家帮助

**Comment by lulu0024** [comment]
我是按文档的方式卸载后直接mac上不了网了，百度也打不开…

**Comment by yangbiny** [comment]
https://github.com/yanue/V2rayU/issues/1234

可以用用这个，尝试过了是OK的

**Comment by 956836421** [comment]
1，访达中卸载软件
2，rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist && rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist

**Comment by godwinjavaee** [comment]
‘xxx‘ “将对您的电脑造成伤害。 您应该将它移到废纸篓。”mac一直弹窗并关不掉的解决方式

10.15.1之后的系统：

在终端输入：csrutil status

如果返回值为：System Integrity Protection status: enabled

说明MAC系统SIP保护开启了，关闭SIP保护即可

重新启动MAC电脑，https://support.apple.com/zh-cn/HT204904

如果使用的是搭载 Apple 芯片的 Mac
1. 按住 Mac 上的电源按钮。如果你继续按住电源按钮，则 Mac 会开机并载入启动选项。当你看到“选项”时，松开电源按钮。
2. 点按“选项”，然后点按在它下方显示的“继续”按钮。
3. 如果系统要求你选择一个你知道相应密码的用户，请选择这样的用户，点按“下一步”，然后输入用户的管理员密码。

如果使用的是基于 Intel 的 Mac
1. 按下 Mac 上的电源按钮以开机，然后松开电源按钮并立即同时按住 Command (⌘) 键和 R 键，直到看到 Apple 标志或旋转的地球。如果你无法通过这种方式从恢复模式启动，请查阅[有关使用启动组合键的准则](https://support.apple.com/zh-cn/HT201255#guidelines)。
2.  如果系统要求你选择一个你知道相应密码的用户，请选择这样的用户，点按“下一步”，然后输入用户的管理员密码。 

进入恢复环境，在恢复环境打开终端

输入csrutil disable

重新启动系统后，再次输入csrutil status，应该显示为disable

**Comment by qizhengyang2017** [comment]
> 1，访达中卸载软件
> 
> 2，rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist && rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist

我试了，还是会有窗口弹出来，点击移到废纸楼没有效果

**Comment by Diluka** [comment]
试一下`brew install v2rayu`呢

**Comment by rust17** [comment]
> > 1，访达中卸载软件
> > 
> > 2，rm -rf ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist && rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist
> 
> 我试了，还是会有窗口弹出来，点击移到废纸楼没有效果

参照一下这个：清空废纸篓
