### ISSUE TITLE
卸载v2rayu后无法上网

### ISSUE THREAD

**Issue by lulu0024** [yanue/V2rayU#1241]
按文档的方式卸载v2rayu后无法上网，只有重新安装打开v2ray的情况下才能上网。关闭了就无法上网

**Comment by Zhouyashi** [comment]
或许把wifi的DNS删除一下？我之前也碰到过无法上网的情况就是这样解决的

**Comment by lulu0024** [comment]
> 或许把wifi的DNS删除一下？我之前也碰到过无法上网的情况就是这样解决的

试过了不是这个问题 应该是软件没删干净之类的，因为我重启电脑那一会是能上网的，但是一会后就上不去了

**Comment by lulu0024** [comment]
删除掉所有网络配置文件后正常了，应该是卸载后网络代理没变
