### ISSUE TITLE
xray-core最新版的配置文件，使用导入json配置模式，启动代理时，配置信息里一些不认识的元素会丢失（比如reality协议相关配置）

### ISSUE THREAD

**Issue by stxpons** [yanue/V2rayU#1246]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU版本：v3.4.0-preview
Mac版本：13.4.1【其实应该无所谓】

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
xray-core官方有新版本时，客户端的config.json配置文件，是可以有一些新元素的。
比如我手工替换了v2ray-core版本为最新的1.8.3版本，使用最新的reality协议，服务器配置使用“导入模式”手工编辑config.json文件【试过手工编辑粘贴json配置和文件导入等当时】，
但最终保存后时，启动该服务时(开启代理)，outbounds的出站配置会被重新覆盖调整，如图所示：
<img width="1400" alt="outbounds元素差异" src="https://github.com/yanue/V2rayU/assets/4133964/96ba9082-eacc-4a31-b71c-b05f1f9f923c">

--> 题外话，目前个人解决方案：
手工修改 ~/.V2rayU/config.json 方式解决。甚至想过修改～/Library/Preferences/net.yanue.V2rayU.plist里的配置。想想还是没干：1是文件内容太多编辑麻烦；2是想了下可能的实现原理，下次编辑说不定还得覆盖我内容，估计是运行时拷贝到~/.V2rayU/config.json文件的。

**Comment by stxpons** [comment]
个人建议的实现方式，可供参考：
每个人的维护精力毕竟有限，但官方产品一直在迭代，导入json配置文件的模式，就没必要非得该软件认识的元素才保存【除非用户从json配置切换到图形界面去编辑保存了】。
直接原生的json配置文件保存应该就可以了。

**Comment by stxpons** [comment]
还是有问题，会把realitySettings里的publicKey和serverName给清没掉。
<img width="1075" alt="image" src="https://github.com/yanue/V2rayU/assets/4133964/d7fa4a59-cd57-4f90-bf61-511ddfb7601f">

**Comment by n0thing2speak** [comment]
> 

还是等作者更新吧，确实3.5有问题，感谢提供的方法，就是感觉自己去改麻烦了，而且话说REALITY不是xray 1.8支持的吗？现在3.5默认更新的xray还是1.7.5，应该也不支持吧

**Comment by xyz3282836** [comment]
> 临时搞定下 手工编辑~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist启动文件，调整了config参数。 重启yanue.v2rayu.v2ray-core: launchctl stop yanue.v2rayu.v2ray-core launchctl unload ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist launchctl load -wF ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist launchctl start yanue.v2rayu.v2ray-core

请问需要怎么调整，plist文件就是个xml

**Comment by stxpons** [comment]
> 

有一些专门的编辑软件的，我用的软件是PlistEdit pro，用软件打开这配置文件，里面有个ProgramArguments参数，我把里面的config.json换成我自己手工编辑好的文件了【要自己提前准备好配置文件。看代码里其实就是用launchctl命令执行这些玩意的。v2ray跟xray是一摸一样的，只是名字改了。xray-core下载最新的1.8.3版本】
<img width="732" alt="image" src="https://github.com/yanue/V2rayU/assets/4133964/db61eb96-1f21-459e-b34f-1b8cb78e7c69">

**Comment by stxpons** [comment]
> > 
> 
> 还是等作者更新吧，确实3.5有问题，感谢提供的方法，就是感觉自己去改麻烦了，而且话说REALITY不是xray 1.8支持的吗？现在3.5默认更新的xray还是1.7.5，应该也不支持吧

我是手工自己到官网下载最新的1.8.3版本【https://github.com/XTLS/Xray-core/releases】，然后全部替换掉 ～/.V2rayU/v2ray-core里的5个文件【v2ray文件直接复制自xray即可】

**Comment by xyz3282836** [comment]
> 手工编辑~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist启动文件，调整了config参数。
> 重启yanue.v2rayu.v2ray-core:
> launchctl stop yanue.v2rayu.v2ray-core
> launchctl unload ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> launchctl load -wF ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> launchctl start yanue.v2rayu.v2ray-core

可以的，按照
手工编辑~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist启动文件，调整了config参数。
重启yanue.v2rayu.v2ray-core:
launchctl stop yanue.v2rayu.v2ray-core
launchctl unload ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
launchctl load -wF ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
launchctl start yanue.v2rayu.v2ray-core
以上的顺序执行下，这样就算覆盖config.json，实际使用的是plist新设置的文件，就不影响使用xray加载了；不过如果退出软件并重新开启，plist也会被覆盖原样

**Comment by xyz3282836** [comment]
https://github.com/yanue/V2rayU/releases/tag/v3.6.0 fix it
