### ISSUE TITLE
怎么又显示恶意软件了

### ISSUE THREAD

**Issue by papandadj** [yanue/V2rayU#1247]
如题

**Comment by cumtsd** [comment]
同问

**Comment by friend43** [comment]
是的，我这里也显示为有害软件，无法打开了。之前使用一直很稳定，昨天开始突然就这样了。

**Comment by cumtsd** [comment]
有其他好用的软件推荐吗，兄弟们

**Comment by papandadj** [comment]
我备选的是shadowrocket，但是真心不好用，感觉没这个好用

**Comment by qilovehua** [comment]
咋整呢，下载很久了一直没问题。早上也显示恶意软件了

**Comment by taoshide** [comment]
是的，昨天还是好好的，今天早上来就不行了。

**Comment by qilovehua** [comment]
另一个issue里有解决方法，说是签名过期了

输入以下三条命令，亲测可以


sudo codesign --force --deep --sign - /Applications/V2rayU.app
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月7日 09:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [yanue/V2rayU] 怎么又显示恶意软件了 (Issue #1247) |

是的，昨天还是好好的，今天早上来就不行了。

**Comment by papandadj** [comment]
主要是作者重新给了个[v3.4.0-preview](https://github.com/yanue/V2rayU/releases/tag/v3.4.0-preview)，为啥又要自己签名了

**Comment by quiet201** [comment]
在电脑 系统设置 -- 安全   那里 多点几次 任然打开 就好了

**Comment by kevinlaunew** [comment]
m1 MacBook air安装老版本解决了此问题
[3.0预览版](https://github.com/yanue/V2rayU/releases/tag/3.0.0.preview)

**Comment by friend43** [comment]
还是看看作者怎么彻底解决这个问题吧。这款软件还是不错的，使用一直很稳定。

**Comment by libyoung** [comment]
你们不要出了问题就找作者，平时多支持作者啊， 给钱了吗

**Comment by islibaodong** [comment]
出问题啦，macos：13.4.1 (22F82)

**Comment by FrankRoc** [comment]
今天我也出现了这样的情况 按照上面大神的三行代码解决了 感谢!

**Comment by canbefree** [comment]
> m1 MacBook air安装3.0老版本解决了此问题
> [3.0预览版](https://github.com/yanue/V2rayU/releases/tag/3.0.0.preview)

🐮B

**Comment by Boliang-Lu** [comment]
> m1 MacBook air安装3.0老版本解决了此问题 [3.0预览版](https://github.com/yanue/V2rayU/releases/tag/3.0.0.preview)

可以用

**Comment by islibaodong** [comment]
使用老版本 [V2rayU-64.dmg](https://github.com/yanue/V2rayU/releases/download/3.3.0/V2rayU-64.dmg)

macOS：13.4.1 (22F82)。2.6 GHz 六核Intel Core i7


sudo codesign --force --deep --sign - /Applications/V2rayU.app
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray

可以解决问题。

**Comment by cumtsd** [comment]
> 使用老版本 [V2rayU-64.dmg](https://github.com/yanue/V2rayU/releases/download/3.3.0/V2rayU-64.dmg)
> 
> macOS：13.4.1 (22F82)。2.6 GHz 六核Intel Core i7
> 
> sudo codesign --force --deep --sign - /Applications/V2rayU.app sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> 
> 可以解决问题。

试了下，并没有解决呀
