### ISSUE TITLE
怎么自己编译？

### ISSUE THREAD

**Issue by bihell** [yanue/V2rayU#1249]
想问下怎么自己编译，最近使用一直报警，用预览版也碰到了

**Comment by stxpons** [comment]
1、
<img width="499" alt="image" src="https://github.com/yanue/V2rayU/assets/4133964/25afed89-ddd6-4048-b09e-ae0abec505a5">
2、如果提示无法运行，检查权限：
/Applications/V2rayU.app/Contents/Resources  和 ~/.V2rayU【实际运行的应该是这个吧】，cmd.sh内容可以看到，里面有些小动作；
3、可能需要重新签名：
sudo codesign --force --deep --sign - /Applications/V2rayU.app
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUHelper
sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/xray
sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray

**Comment by yanue** [comment]
1. fork 然后 git clone 到本地
2. pod install
3. 下载最新版v2ray-core,如: https://github.com/v2ray/v2ray-core/releases/download/v4.8.0/v2ray-macos.zip,解压到Build目录,重命名为v2ray-core
4. 更改签名为自己的,运行xcode即可

**Comment by bihell** [comment]
> 1、 <img alt="image" width="499" src="https://user-images.githubusercontent.com/4133964/251695456-25afed89-ddd6-4048-b09e-ae0abec505a5.png"> 2、如果提示无法运行，检查权限： /Applications/V2rayU.app/Contents/Resources 和 ~/.V2rayU【实际运行的应该是这个吧】，cmd.sh内容可以看到，里面有些小动作； 3、可能需要重新签名： sudo codesign --force --deep --sign - /Applications/V2rayU.app sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUHelper sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/xray sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray

感谢，不报警了，慢点在用楼下的方法试试看自己编译签名试试

**Comment by bihell** [comment]
> 1. fork 然后 git clone 到本地
> 2. pod install
> 3. 下载最新版v2ray-core,如:  https://github.com/v2ray/v2ray-core/releases/download/v4.8.0/v2ray-macos.zip, 解压到Build目录,重命名为v2ray-core
> 4. 更改签名为自己的,运行xcode即可

搞定了，感谢老铁
