### ISSUE TITLE
自行怎样源码编译？

### ISSUE THREAD

**Issue by sonwa** [yanue/V2rayU#1250]
/Users/abc/Downloads/code/V2rayU-3.4.0-preview/Build/v2ray-core /Users/abc/Downloads/code/V2rayU-3.4.0-preview/Build/v2ray-core: No such file or directory

编译时提示这个错误，请问怎样编译？有教程吗？

**Comment by AI2Hub** [comment]
v2ray-core  download   v2ray-core   https://github.com/v2ray/v2ray-core/releases  unzip   put into Build folder v2ray-core

**Comment by sonwa** [comment]
Oh,Yeah
Thanks
