### ISSUE TITLE
请问如何使用局域网代理功能？让局域网内其他设备访问外网

### ISSUE THREAD

**Issue by mulinz** [yanue/V2rayU#1251]
按照之前的帖子把本机Sock监听端口改成0.0.0.0 但是家里的局域网设备还是不能通过代理访问外放 switch和手机试了都不行 求解
谢谢！

**Comment by mulinz** [comment]
重启了几次有好用了

**Comment by yanue** [comment]
要保证同一个网段才行

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: mulinz ***@***.***>
发送时间: Sunday, July 9, 2023 3:59:01 PM
收件人: yanue/V2rayU ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [yanue/V2rayU] 请问如何使用局域网代理功能？让局域网内其他设备访问外网 (Issue #1251)


Closed #1251<https://github.com/yanue/V2rayU/issues/1251> as completed.

―
