### ISSUE TITLE
M1 13.4.1 V2rayU 3.3 3.4 全部叫我移去Bin

### ISSUE THREAD

**Issue by mactrash** [yanue/V2rayU#1253]
只能用回 3.2

**Comment by mactrash** [comment]
I really try all codesign and still same.

**Comment by ewpkw** [comment]
同样问题 
MacOS 14.0 beta 
M1pro

**Comment by damoco** [comment]
为什么更新了反而用不了了啊？

**Comment by damoco** [comment]
3.2也在一直报恶意软件。。。

**Comment by mactrash** [comment]
> 3.2也在一直报恶意软件。。。

我只能 uninstall and clean install

**Comment by jifang** [comment]
Try this
https://github.com/yanue/V2rayU/issues/1238

**Comment by mactrash** [comment]
> Try this #1238

Try already, 

I don't know why a clean install, the program 3.4 don't have right to create .V2rayU

**Comment by goldeye0351** [comment]
是否要重新签名一下?

**Comment by mactrash** [comment]
> 是否要重新签名一下?

已签

**Comment by TianLuen** [comment]
M2 Ventura13.4.1 同样情况

**Comment by yangwudong** [comment]
> Try this #1238

重新签名之后，已经修复好了

**Comment by byalan** [comment]
后悔了，我更新前我看了关于，我的是3.3的，结果更新了全用不了，只能装回3.2……X86

**Comment by yangwudong** [comment]
> 后悔了，我更新前我看了关于，我的是3.3的，结果更新了全用不了，只能装回3.2……X86

sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray

这三条命令执行了就好了啊，一个也别漏了就行

**Comment by mactrash** [comment]
M1
OSX 13.4.1

1. From 3.2
2. Copy V2rayU to Application
3. Run V2rayU

This time I first see [] Override Malware Protect in command i

remove ~/user/.V2rayU

sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray

!important Remember allow it run in Privacy & Security each time

Now work, thx.

**Comment by viczhang** [comment]
Thank you guys for the quick fix.
