### ISSUE TITLE
服务器名称会导致无法使用

### ISSUE THREAD

**Issue by bewater9** [yanue/V2rayU#1259]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

V2RayU3.4、3.3，Mac 13.4.1 (22F82)

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

服务器名称如果带端口会无法使用，比如这样

域名:端口

修改成不带:端口可以使用。

**Comment by yanue** [comment]
不是都有专门填写端口的地方吗

**Comment by yanue** [comment]
发一个示例出来才知道啊
