### ISSUE TITLE
新版还是会弹出让删除

### ISSUE THREAD

**Issue by lxtx528** [yanue/V2rayU#1265]
新版打开和退出还是会弹出让删除，但是点击取消可以继续使用，有办法能彻底解决吗？

**Comment by yayuntian** [comment]
https://discussionschinese.apple.com/thread/254968153

**Comment by yanue** [comment]
彻底卸载重新安装3.6.0试下

**Comment by huxh** [comment]
转自知乎此文回复https://zhuanlan.zhihu.com/p/641261094：
原作者Ohno(https://www.zhihu.com/people/8912fb4368de7f5121a80ff787083975)：
我的经验不一样，没有那个“覆盖恶意软件”，还是打不开，搜了下追加了这个命令有用

sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app

**Comment by kgyhkgyh** [comment]
> 证书过期问题导致的：
> 
> 第一步，执行
> 
> `sudo codesign --force --deep --sign - /Applications/V2rayU.app`
> 
> 第二步，在应用程序中找到V2rayU，右键，显示简介，勾选覆盖恶意软件保护(我的没有此选项)
> 
> 第三步，打开软件
> 
> 第四部，执行
> 
> ```
> sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```
> 
> 然后就能正常运行了。
> 
> 来自：https://discussionschinese.apple.com/thread/254968153

亲测可用，谢谢大佬
