### ISSUE TITLE
V2RayU 3.6.0 缺少geosite.dat

### ISSUE THREAD

**Issue by Mabbs** [yanue/V2rayU#1268]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.6.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
直接安装缺少geosite.dat
3)  请附上出错时软件输出的错误日志。

```
Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 darwin/arm64)
A unified platform for anti-censorship.
2023/07/13 12:30:37 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:cn > infra/conf: failed to load geosite: CN > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /Users/mayx/.V2rayU/v2ray-core/geosite.dat: no such file or directory
```

请预览一下你填的内容再提交。

**Comment by JerryAllison** [comment]
同样的问题
2023/07/13 13:08:11 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:cn > infra/conf: failed to load geosite: CN > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /Users/jack/.V2rayU/v2ray-core/geosite.dat: no such file or directory

**Comment by rhf0576** [comment]
同样的问题，卸掉3.6重装3.5后一切正常

2023/07/13 12:39:26 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:cn > infra/conf: failed to load geosite: CN > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /Users/rhf/.V2rayU/v2ray-core/geosite.dat: no such file or directory
Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 darwin/arm64)
A unified platform for anti-censorship.

**Comment by michaelmyf** [comment]
需要自行下载geosite.dat和geoip.dat，复制到目录~/.V2rayU/v2ray-core文件夹下。推荐这个加强版的规则项目：https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by KEUNGXU** [comment]
1. 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.7.0
2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
设置了节点之后（和之前旧版本一样的操作），开启全局模式，无法打开网页，但是ping speed能有速度延迟，单独也能ping通对应的ip
3. 请附上出错时软件输出的错误日志。
2023/07/14 20:40:41 [Warning] [3817824234] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:41 [Info] [3817824234] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:41 [Warning] [15422248] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:41 [Info] [15422248] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:41 [Warning] [1646231034] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:41 [Info] [1646231034] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:41 [Info] [1182352493] proxy/http: request to Method [CONNECT] Host [otheve.beacon.qq.com:443] with URL [//otheve.beacon.qq.com:443]
2023/07/14 20:40:41 [Info] [1182352493] app/dispatcher: default route for tcp:otheve.beacon.qq.com:443
2023/07/14 20:40:41 [Info] [1182352493] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:41 127.0.0.1:63382 accepted //otheve.beacon.qq.com:443 [proxy]
2023/07/14 20:40:42 [Warning] [2228119638] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:42 [Info] [2228119638] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:42 [Warning] [1302460061] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:42 [Info] [1302460061] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:42 [Warning] [1629641426] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:42 [Info] [1629641426] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:42 [Info] [1880059672] proxy/http: request to Method [CONNECT] Host [p.typekit.net:443] with URL [//p.typekit.net:443]
2023/07/14 20:40:42 [Info] [1880059672] app/dispatcher: default route for tcp:p.typekit.net:443
2023/07/14 20:40:42 [Info] [1880059672] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:42 127.0.0.1:63385 accepted //p.typekit.net:443 [proxy]
2023/07/14 20:40:42 [Warning] [63835580] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:42 [Info] [63835580] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:42 [Warning] [627811144] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:42 [Info] [627811144] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:43 [Warning] [1556780851] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:43 [Info] [1556780851] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:43 [Info] [2498107059] proxy/socks: TCP Connect request to tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:43 [Info] [2498107059] app/dispatcher: default route for tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:43 [Info] [2498107059] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:43 tcp:127.0.0.1:63388 accepted tcp:c.mango.qidian.qq.com:443 [proxy]
2023/07/14 20:40:43 [Info] [2945638229] proxy/http: request to Method [CONNECT] Host [rumt-zh.com:443] with URL [//rumt-zh.com:443]
2023/07/14 20:40:43 [Info] [2945638229] app/dispatcher: default route for tcp:rumt-zh.com:443
2023/07/14 20:40:43 [Info] [2945638229] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:43 127.0.0.1:63390 accepted //rumt-zh.com:443 [proxy]
2023/07/14 20:40:43 [Warning] [784201879] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:43 [Info] [784201879] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:43 [Warning] [2266140923] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:43 [Info] [2266140923] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:44 [Warning] [1182352493] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:44 [Info] [1182352493] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:44 [Info] [1349978615] proxy/socks: TCP Connect request to tcp:otheve.beacon.qq.com:443
2023/07/14 20:40:44 [Info] [1349978615] app/dispatcher: default route for tcp:otheve.beacon.qq.com:443
2023/07/14 20:40:44 [Info] [1349978615] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:44 tcp:127.0.0.1:63393 accepted tcp:otheve.beacon.qq.com:443 [proxy]
2023/07/14 20:40:44 [Warning] [1103025411] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:44 [Info] [1103025411] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:44 [Warning] [3506617236] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:44 [Info] [3506617236] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:45 [Info] [1131945738] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:40:45 [Info] [1131945738] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:40:45 [Info] [1131945738] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:45 tcp:127.0.0.1:63396 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:40:45 [Warning] [1880059672] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:45 [Info] [1880059672] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:45 [Warning] [2945638229] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:45 [Info] [2945638229] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:45 [Info] [4058512242] proxy/http: request to Method [CONNECT] Host [rumt-zh.com:443] with URL [//rumt-zh.com:443]
2023/07/14 20:40:45 [Info] [4058512242] app/dispatcher: default route for tcp:rumt-zh.com:443
2023/07/14 20:40:45 [Info] [4058512242] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:45 127.0.0.1:63399 accepted //rumt-zh.com:443 [proxy]
2023/07/14 20:40:46 [Warning] [2498107059] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:46 [Info] [2498107059] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:46 [Info] [3516014324] proxy/socks: TCP Connect request to tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:46 [Info] [3516014324] app/dispatcher: default route for tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:46 tcp:127.0.0.1:63402 accepted tcp:c.mango.qidian.qq.com:443 [proxy]
2023/07/14 20:40:46 [Info] [3516014324] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:46 [Warning] [1349978615] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:46 [Info] [1349978615] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:46 [Info] [1409812251] proxy/http: request to Method [CONNECT] Host [otheve.beacon.qq.com:443] with URL [//otheve.beacon.qq.com:443]
2023/07/14 20:40:46 [Info] [1409812251] app/dispatcher: default route for tcp:otheve.beacon.qq.com:443
2023/07/14 20:40:46 [Info] [1409812251] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:46 127.0.0.1:63404 accepted //otheve.beacon.qq.com:443 [proxy]
2023/07/14 20:40:47 [Warning] [1131945738] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:47 [Info] [1131945738] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:47 [Info] [212612721] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:40:47 [Info] [212612721] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:40:47 [Info] [212612721] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:47 tcp:127.0.0.1:63407 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:40:48 [Warning] [4058512242] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:48 [Info] [4058512242] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:48 [Warning] [3516014324] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:48 [Info] [3516014324] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:49 [Warning] [1409812251] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:49 [Info] [1409812251] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:49 [Info] [2777916289] proxy/socks: TCP Connect request to tcp:otheve.beacon.qq.com:443
2023/07/14 20:40:49 [Info] [2777916289] app/dispatcher: default route for tcp:otheve.beacon.qq.com:443
2023/07/14 20:40:49 [Info] [2777916289] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:49 tcp:127.0.0.1:63410 accepted tcp:otheve.beacon.qq.com:443 [proxy]
2023/07/14 20:40:49 [Warning] [212612721] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:49 [Info] [212612721] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:50 [Info] [3880593251] proxy/http: request to Method [CONNECT] Host [rumt-zh.com:443] with URL [//rumt-zh.com:443]
2023/07/14 20:40:50 [Info] [3880593251] app/dispatcher: default route for tcp:rumt-zh.com:443
2023/07/14 20:40:50 [Info] [3880593251] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:50 127.0.0.1:63413 accepted //rumt-zh.com:443 [proxy]
2023/07/14 20:40:50 [Info] [1255506059] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:40:50 [Info] [1255506059] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:40:50 [Info] [1255506059] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:50 tcp:127.0.0.1:63416 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:40:51 [Warning] [2777916289] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:51 [Info] [2777916289] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:52 [Warning] [3880593251] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:52 [Info] [3880593251] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:52 [Info] [13243231] proxy/http: request to Method [CONNECT] Host [rumt-zh.com:443] with URL [//rumt-zh.com:443]
2023/07/14 20:40:52 [Info] [13243231] app/dispatcher: default route for tcp:rumt-zh.com:443
2023/07/14 20:40:52 [Info] [13243231] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:52 127.0.0.1:63419 accepted //rumt-zh.com:443 [proxy]
2023/07/14 20:40:52 [Info] [1964893925] proxy/http: request to Method [CONNECT] Host [clients4.google.com:443] with URL [//clients4.google.com:443]
2023/07/14 20:40:52 [Info] [1964893925] app/dispatcher: default route for tcp:clients4.google.com:443
2023/07/14 20:40:52 [Info] [1964893925] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:52 127.0.0.1:63422 accepted //clients4.google.com:443 [proxy]
2023/07/14 20:40:52 [Warning] [1255506059] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:52 [Info] [1255506059] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:52 [Info] [428474887] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:40:52 [Info] [428474887] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:40:52 [Info] [428474887] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:52 tcp:127.0.0.1:63424 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:40:54 [Info] [400043819] proxy/socks: TCP Connect request to tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:54 [Info] [400043819] app/dispatcher: default route for tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:54 tcp:127.0.0.1:63427 accepted tcp:c.mango.qidian.qq.com:443 [proxy]
2023/07/14 20:40:54 [Info] [400043819] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:54 [Warning] [13243231] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:54 [Info] [13243231] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:54 [Warning] [1964893925] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:54 [Info] [1964893925] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:54 [Info] [1058356938] proxy/http: request to Method [CONNECT] Host [clients4.google.com:443] with URL [//clients4.google.com:443]
2023/07/14 20:40:54 [Info] [1058356938] app/dispatcher: default route for tcp:clients4.google.com:443
2023/07/14 20:40:54 [Info] [1058356938] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:54 127.0.0.1:63430 accepted //clients4.google.com:443 [proxy]
2023/07/14 20:40:55 [Warning] [428474887] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:55 [Info] [428474887] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:56 [Warning] [400043819] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:56 [Info] [400043819] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:56 [Info] [508209681] proxy/socks: TCP Connect request to tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:56 [Info] [508209681] app/dispatcher: default route for tcp:c.mango.qidian.qq.com:443
2023/07/14 20:40:56 [Info] [508209681] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:56 tcp:127.0.0.1:63433 accepted tcp:c.mango.qidian.qq.com:443 [proxy]
2023/07/14 20:40:56 [Info] [1991212708] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:40:56 [Info] [1991212708] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:40:56 [Info] [1991212708] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:56 tcp:127.0.0.1:63436 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:40:57 [Warning] [1058356938] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:57 [Info] [1058356938] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:40:58 [Warning] [508209681] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:58 [Info] [508209681] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:59 [Warning] [1991212708] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:40:59 [Info] [1991212708] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:40:59 [Info] [1441168606] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:40:59 [Info] [1441168606] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:40:59 [Info] [1441168606] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:40:59 tcp:127.0.0.1:63440 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:41:00 [Info] [3577238482] proxy/http: request to Method [CONNECT] Host [rumt-zh.com:443] with URL [//rumt-zh.com:443]
2023/07/14 20:41:00 [Info] [3577238482] app/dispatcher: default route for tcp:rumt-zh.com:443
2023/07/14 20:41:00 [Info] [3577238482] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:41:00 127.0.0.1:63443 accepted //rumt-zh.com:443 [proxy]
2023/07/14 20:41:01 [Warning] [1441168606] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:41:01 [Info] [1441168606] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:41:02 [Warning] [3577238482] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:41:02 [Info] [3577238482] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:41:02 [Info] [3877998285] proxy/http: request to Method [CONNECT] Host [rumt-zh.com:443] with URL [//rumt-zh.com:443]
2023/07/14 20:41:02 [Info] [3877998285] app/dispatcher: default route for tcp:rumt-zh.com:443
2023/07/14 20:41:02 [Info] [3877998285] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:41:02 127.0.0.1:63447 accepted //rumt-zh.com:443 [proxy]
2023/07/14 20:41:04 [Info] [2748844776] proxy/socks: TCP Connect request to tcp:c.mango.qidian.qq.com:443
2023/07/14 20:41:04 [Info] [2748844776] app/dispatcher: default route for tcp:c.mango.qidian.qq.com:443
2023/07/14 20:41:04 [Info] [2748844776] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:41:04 tcp:127.0.0.1:63452 accepted tcp:c.mango.qidian.qq.com:443 [proxy]
2023/07/14 20:41:04 [Warning] [3877998285] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:41:04 [Info] [3877998285] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2023/07/14 20:41:04 [Info] [931204856] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:41:04 [Info] [931204856] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:41:04 tcp:127.0.0.1:63455 accepted tcp:alive.github.com:443 [proxy]
2023/07/14 20:41:04 [Info] [931204856] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:41:06 [Warning] [2748844776] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:41:06 [Info] [2748844776] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:41:06 [Info] [4228292718] proxy/socks: TCP Connect request to tcp:c.mango.qidian.qq.com:443
2023/07/14 20:41:06 [Info] [4228292718] app/dispatcher: default route for tcp:c.mango.qidian.qq.com:443
2023/07/14 20:41:06 [Info] [4228292718] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:41:06 tcp:127.0.0.1:63458 accepted tcp:c.mango.qidian.qq.com:443 [proxy]
2023/07/14 20:41:07 [Warning] [931204856] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > unexpected EOF
2023/07/14 20:41:07 [Info] [931204856] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/07/14 20:41:07 [Info] [3883112531] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/07/14 20:41:07 [Info] [3883112531] app/dispatcher: default route for tcp:alive.github.com:443
2023/07/14 20:41:07 [Info] [3883112531] transport/internet/tcp: dialing TCP to tcp:210.1.227.81:41487
2023/07/14 20:41:07 tcp:127.0.0.1:63462 accepted tcp:alive.github.com:443 [proxy]
