### ISSUE TITLE
Suggestions: updating the config file format.

### ISSUE THREAD

**Issue by adamgonglj** [yanue/V2rayU#127]
2019/07/08 00:05:35 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.

**Comment by sonifly** [comment]
log里也出现这条错误

**Comment by devSC** [comment]
+1

**Comment by yanue** [comment]
尚未发版

**Comment by TerickJojo** [comment]
我也出现了这个报错，然后就不能用了

**Comment by noiseorigin** [comment]
求问怎么解决
