### ISSUE TITLE
多次卸载更新3.6.0后开启和关闭还是会提示删除

### ISSUE THREAD

**Issue by lxtx528** [yanue/V2rayU#1273]
提示V2rayU Tool将对你的电脑造成伤害，你应该将它移到废纸篓。

**Comment by yanue** [comment]
删除~/.V2rayU了吗

**Comment by rust17** [comment]
> 删除~/.V2rayU了吗

删除了也卸载了，依旧提示“V2rayU Tool将对你的电脑造成伤害，你应该将它移到废纸篓”

**Comment by rust17** [comment]
终于解决掉弹窗的问题了，清空废纸篓就可以了。。。

**Comment by lxtx528** [comment]
已解决，谢谢大佬。

circle33 ***@***.***> 于 2023年7月15日周六 13:33写道：
