### ISSUE TITLE
更新v3.7.0后，之前正常的代理都不能用了

### ISSUE THREAD

**Issue by vkeeps** [yanue/V2rayU#1274]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

v3.7.0，mac：12.5

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

更新v3.7.0后，之前正常的代理都不能用了，降级回v2.3.1又正常了，说明代理没问题。。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
```
4)  请附上出错时软件输出的错误日志。

```javascript
   operation was canceled dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
发一下2.3.1和3.7.0的配置信息？方便看下什么问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Crane.Peng ***@***.***>
发送时间: Friday, July 14, 2023 11:24:11 AM
收件人: yanue/V2rayU ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yanue/V2rayU] 更新v3.7.0后，之前正常的代理都不能用了 (Issue #1274)


提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

  1.  你正在使用的 V2RayU 和 Mac 版本 ？

v3.7.0，mac：12.5

  1.  你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

更新v3.7.0后，之前正常的代理都不能用了，降级回v2.3.1又正常了，说明代理没问题。。

  1.  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

  1.  请附上出错时软件输出的错误日志。

   operation was canceled dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed


请预览一下你填的内容再提交。

―

**Comment by hymmyh** [comment]
我也降到2.3.1 了.

**Comment by xuchuyuan** [comment]
+1

**Comment by bluaze** [comment]
以我手头的几个节点来看，纯vmess的没问题，vmess+tls+ws和vless+tls+ws的都不行
3.4.0~3.8.0都存在这个问题，之前3.3.0没事

**Comment by yanue** [comment]
> 

需要贴一下之前版本和后面版本的配置,好对比差异在哪

**Comment by vkeeps** [comment]
> 之前

我升级到最新看看，然后做个对比，配置我打个码直接贴出来吗，还是发到作者邮箱。
