### ISSUE TITLE
VLESS+Reality 节点分享链接URL， 没有完全正确导入V2rayU，导致无法正常实现代理

### ISSUE THREAD

**Issue by Maxswang** [yanue/V2rayU#1275]
**使用环境：**

- V2rayU-64：  v3.7.0
- MacOS：13.4.1

**问题：** V2rayU v3.7.0  使用  Windows 下v2rayN v6.23 分享VLESS+Reality节点链接URL 导入节点，切换至对应的节点，但无法正常实现代理。

**解决：** 如下示例 VLESS+Reality节点分享链接中 `sni=www.microsoft.com`   **没有正确解析到 serverName 字段上**， 手动模式下修改将serverName 修改为 `www.microsoft.com` 后 可以正常实现代理。

v2rayN v6.23 分享VLESS+Reality节点链接URL, 示例如下:

```shell
vless://a1b610f6-f87d-4e12-f342-c655e98a8888@xui.example.com:46590?encryption=none&flow=xtls-rprx-vision&security=reality&sni=www.microsoft.com&fp=chrome&pbk=S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4&type=tcp&headerType=none#vless-reality%7CrSjB.love%40xray.com
```

config.json配置：

```json
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vless",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "reality",
        "realitySettings": {
          "spiderX": "",
          "publicKey": "S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4",
          "show": true,
          "serverName": "xui.example.com",
          "shortId": "",
          "fingerprint": "chrome"
        },
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xui.example.com",
            "users": [
              {
                "encryption": "none",
                "id": "a1b610f6-f87d-4e12-f342-c655e98a8888",
                "level": 0,
                "flow": "xtls-rprx-vision"
              }
            ],
            "port": 46590
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```

**另外：** 使用 FranzKafkaYu/x-ui 面板分享VLESS+Reality节点链接URL（与上述v2rayN分享节点示例 属于同一个节点）， 示例如下

```shell
vless://a1b610f6-f87d-4e12-f342-c655e98a8888@xui.example.com:46590?type=tcp&security=reality&sni=www.microsoft.com&pbk=S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4&flow=xtls-rprx-vision&fp=chrome#vless-reality|rSjB.love@xray.com
```

v2rayU 无法导入 分享链接URL，提示: `import server fail: invalid vless url`

**Comment by devilq90** [comment]
同样这个问题，怎么解决呀

**Comment by chouxiang99** [comment]
> **使用环境：**
> 
> * V2rayU-64：  v3.7.0
> * MacOS：13.4.1
> 
> **问题：** V2rayU v3.7.0 使用 Windows 下v2rayN v6.23 分享VLESS+Reality节点链接URL 导入节点，切换至对应的节点，但无法正常实现代理。
> 
> **解决：** 如下示例 VLESS+Reality节点分享链接中 `sni=www.microsoft.com` **没有正确解析到 serverName 字段上**， 手动模式下修改将serverName 修改为 `www.microsoft.com` 后 可以正常实现代理。
> 
> v2rayN v6.23 分享VLESS+Reality节点链接URL, 示例如下:
> 
> ```shell
> vless://a1b610f6-f87d-4e12-f342-c655e98a8888@xui.example.com:46590?encryption=none&flow=xtls-rprx-vision&security=reality&sni=www.microsoft.com&fp=chrome&pbk=S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4&type=tcp&headerType=none#vless-reality%7CrSjB.love%40xray.com
> ```
> 
> config.json配置：
> 
> ```json
> {
>   "log": {
>     "error": "",
>     "loglevel": "info",
>     "access": ""
>   },
>   "inbounds": [
>     {
>       "listen": "127.0.0.1",
>       "protocol": "socks",
>       "settings": {
>         "udp": false,
>         "auth": "noauth"
>       },
>       "port": "1080"
>     },
>     {
>       "listen": "127.0.0.1",
>       "protocol": "http",
>       "settings": {
>         "timeout": 360
>       },
>       "port": "1087"
>     }
>   ],
>   "outbounds": [
>     {
>       "mux": {
>         "enabled": false,
>         "concurrency": 8
>       },
>       "protocol": "vless",
>       "streamSettings": {
>         "tcpSettings": {
>           "header": {
>             "type": "none"
>           }
>         },
>         "security": "reality",
>         "realitySettings": {
>           "spiderX": "",
>           "publicKey": "S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4",
>           "show": true,
>           "serverName": "xui.example.com",
>           "shortId": "",
>           "fingerprint": "chrome"
>         },
>         "network": "tcp"
>       },
>       "tag": "proxy",
>       "settings": {
>         "vnext": [
>           {
>             "address": "xui.example.com",
>             "users": [
>               {
>                 "encryption": "none",
>                 "id": "a1b610f6-f87d-4e12-f342-c655e98a8888",
>                 "level": 0,
>                 "flow": "xtls-rprx-vision"
>               }
>             ],
>             "port": 46590
>           }
>         ]
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {
>         "domainStrategy": "UseIP",
>         "userLevel": 0
>       }
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {
>         "response": {
>           "type": "none"
>         }
>       }
>     }
>   ],
>   "dns": {},
>   "routing": {
>     "settings": {
>       "domainStrategy": "AsIs",
>       "rules": []
>     }
>   },
>   "transport": {}
> }
> ```
> 
> **另外：** 使用 FranzKafkaYu/x-ui 面板分享VLESS+Reality节点链接URL（与上述v2rayN分享节点示例 属于同一个节点）， 示例如下
> 
> ```shell
> vless://a1b610f6-f87d-4e12-f342-c655e98a8888@xui.example.com:46590?type=tcp&security=reality&sni=www.microsoft.com&pbk=S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4&flow=xtls-rprx-vision&fp=chrome#vless-reality|rSjB.love@xray.com
> ```
> 
> v2rayU 无法导入 分享链接URL，提示: `import server fail: invalid vless url`

大佬     使用 FranzKafkaYu/x-ui 面板分享VLESS+Reality节点链接URL，提示import server fail: invalid vless url    这个后来有解决方案嘛？感谢大佬
