### ISSUE TITLE
更新错误！

### ISSUE THREAD

**Issue by nmww** [yanue/V2rayU#1279]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。
<img width="260" alt="image" src="https://github.com/yanue/V2rayU/assets/6917516/301ce67c-f59d-4452-b949-a3d48ae0b13d">
# 获取升级信息时出现错误，请稍后再试。

----

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by zhyi828** [comment]
同样的问题，抓包看了下GitHub API返回是正常的，gitee的DENY了
<img width="1305" alt="image" src="https://github.com/yanue/V2rayU/assets/10600254/990f3d09-4b13-43f9-9e61-0cf413e1c7f7">

**Comment by yanue** [comment]
对 gitee的DENY了  需手动更新

**Comment by zhyi828** [comment]
> 对 gitee的DENY了 需手动更新

那可以通过GitHub在软件内更新嘛？
