### ISSUE TITLE
导入reality节点需要手动填写"server name"

### ISSUE THREAD

**Issue by henryswisvip** [yanue/V2rayU#1281]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.7.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

导入reality 节点时需要手动填写"server name" 无法从url 或者 qr code 中提取. 默认的是ip地址，而不是 server url
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

无
4)  请附上出错时软件输出的错误日志。
无

请预览一下你填的内容再提交。
<img width="415" alt="Screenshot 2023-07-16 at 17 26 40" src="https://github.com/yanue/V2rayU/assets/47855607/7ceef81e-2c3b-43f2-a1b8-008abdd0f0bd">

**Comment by dongshuzhao** [comment]
Duplicate of #1277
