### ISSUE TITLE
support grpc and xray 1.8.3

### ISSUE THREAD

**Issue by aghilpadash** [yanue/V2rayU#1284]
please add grpc and xray 1.8.3 to v2rayu

**Comment by Maxswang** [comment]
The latest version of v2rayU is already using xray 1.8.3, but it just doesn't have grpc support yet.

**Comment by aghilpadash** [comment]
So please add grpc. Because we usually use grpc for better ping and speed.

**Comment by holywen** [comment]
Check that on 3.8.0, it's using Xray 1.5.5

**Comment by holywen** [comment]
oops, my bad. it initially come with 1.5.5, after a while it's been updated to 1.8.3.

**Comment by holywen** [comment]
OK, even `v2ray version` says it's 1.8.3, but in the log console, it's 1.5.5, and it doesn't support "xtls-rprx-vision" 

```
023/07/28 17:03:37 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version
```

**Comment by holywen** [comment]
<img width="1052" alt="image" src="https://github.com/yanue/V2rayU/assets/3616302/63028859-9229-467d-9aca-6d4a186e5933">

**Comment by cytown** [comment]
> 



> OK, even `v2ray version` says it's 1.8.3, but in the log console, it's 1.5.5, and it doesn't support "xtls-rprx-vision"
> 
> ```
> 023/07/28 17:03:37 [Info] infra/conf/serial: Reading config: config.json
> Failed to start: main: failed to load config files: [config.json] > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version
> ```

My v2ray-core.log is 1.8.3.

```
Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 darwin/amd64)
A unified platform for anti-censorship.
2023/07/30 11:04:07 [Info] infra/conf/serial: Reading config: config.json
2023/07/30 11:04:07 [Info] app/dns: DNS: created localhost client
2023/07/30 11:04:07 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8889
2023/07/30 11:04:07 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1087
2023/07/30 11:04:07 [Warning] core: Xray 1.8.3 started
```
