### ISSUE TITLE
3.8 无法启动 v2ray-core 导致失效

### ISSUE THREAD

**Issue by haimingz** [yanue/V2rayU#1287]
V2rayU 3.8.0, macOS 13.4.1

现象：
无法启动 v2ray-core （状态栏显示 On，但实际没启动，v2ray-core.log 是空白），不能正常上网

解决：
把 config.json 文件复制到 v2ray-core 文件夹，双击 v2ray 运行，可以正常上网

**Comment by haimingz** [comment]
update:

执行：
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray

**重启电脑**，正常工作

**Comment by rex5652** [comment]
> V2rayU 3.8.0, macOS 13.4.1
> 
> 现象： 无法启动 v2ray-core （状态栏显示 On，但实际没启动，v2ray-core.log 是空白），不能正常上网
> 
> 解决： 把 config.json 文件复制到 v2ray-core 文件夹，双击 v2ray 运行，可以正常上网

@haimingz 求教config.json和v2ray-core 文件夹的路径。。。

**Comment by haimingz** [comment]
@rex5652 首先点 “查看v2ray日志”，弹出窗口后，点顶部左侧 “显示”，就会在finder中弹出 V2rayU 的文件夹。
