### ISSUE TITLE
v3.8.0 依然无法使用

### ISSUE THREAD

**Issue by rex5652** [yanue/V2rayU#1288]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
MacBook Air M1
v3.8.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法科学上网，PAC模式和全局模式都不行

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
初期我用的是v3.4.0的版本，然后用appcleaner卸载掉旧版之后开始装v3.8.0。
x64和arm64都试过，但我添加好订阅之后，启动v2ray-core，无论是on off多少次，还是重开软件多少次，无论PAC模式和全局模式，就是无法科学上网。日志模式debug，打开日志之后没有任何报错。
我看了一下系统代理，似乎并没有正常设置到127.0.0.1的某个端口上。隐约记得之前好像会自动设置的。

最终换回v3.4.0-x64，一切正常。如果v3.4.0的xray-core能更新，我还不想升级了。。。

这个兄弟似乎有个办法，我不确定是不是这个问题：
https://github.com/yanue/V2rayU/issues/1287

**Comment by 2974146582** [comment]
无法打开“V2rayU”，因为Apple无法检查其是否包含恶意软件。
