### ISSUE TITLE
v3.8.0 终于启动了，附过程和一些潜在bug

### ISSUE THREAD

**Issue by rex5652** [yanue/V2rayU#1289]
首先我的问题是 https://github.com/yanue/V2rayU/issues/1288 ，后来经过 https://github.com/yanue/V2rayU/issues/1287 的指点，找到了能启动的办法，顺便真正更新了Core：

MacBook Air M1 2020，macOS 12.6.7

1. 用appclearer卸载旧版，特别注意用finder到/Users/用户名/ 下看看有没有 .V2rayU 文件夹，有的话直接删掉。
怎么进入这个目录：点 “查看v2ray日志”，弹出窗口后，点顶部左侧 “显示”，就会在finder中弹出 V2rayU 的文件夹。
![image](https://github.com/yanue/V2rayU/assets/1674158/e26579d8-b965-4052-8842-637aa6442cc7)

2.  到 https://github.com/yanue/V2rayU/releases/tag/v3.8.0 下载安装对应的版本（我用arm64），启动之后如果网络自带翻墙的话会提示“成功更新了xray到1.7.5”。 
第一个坑：我在 /Users/用户名/.V2rayU/v2ray-core/ 里看过，两个xray和v2ray文件其实都是xray 1.5.5，也不知道更新1.7.5到哪里去了。
![image](https://github.com/yanue/V2rayU/assets/1674158/258c1d86-164d-4a63-ac0f-8a66056d0cf8)

3. 导入订阅或者添加服务器。
第二个坑：发现如果导入clash格式的订阅，程序会直接卡死。后来导入trojan格式订阅就可以了，但也有小bug，具体见：https://github.com/yanue/V2rayU/issues/1286

4. 按 https://github.com/yanue/V2rayU/issues/1287 所说，执行以下命令：
sudo codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
然后一定要重启电脑！

5. 更新一些文件（可选）：
到 https://github.com/XTLS/Xray-core/releases 这里下载新的xray-core文件，根据版本自行下载。
到 https://github.com/Loyalsoldier/v2ray-rules-dat/releases 这里下载最新的geosite.dat和geoip.dat（虽然我也不知道有没有用）
然后把这些文件都覆盖到 /Users/用户名/.V2rayU/v2ray-core/ 里，注意里面还有个v2ray，其实也是xray，所以复制两次进去。
第三个坑：当我替换成新版本之后，用trojan协议的节点完全没问题，但用ss协议的节点就有问题。我不确定是core本身的问题还是V2RayU的问题，但我没有深究，因为我只用trojan协议的节点。

6. 更新PAC：
我用这个项目：https://raw.githubusercontent.com/Loukky/gfwlist-by-loukky/master/gfwlist.txt

7. 重启软件，记得要重新选择节点和模式。然后就能使用了
![Snipaste_2023-07-21_13-40-05](https://github.com/yanue/V2rayU/assets/1674158/dc5c84e1-40ee-4a4e-9816-c1612b847c74)

v3.4.0没有以上问题，虽然我不知道v3.8.0实质上更新了啥？ reality协议？ 算了就这样吧，不折腾了，希望作者能继续更新

**Comment by yellowbigbird83** [comment]
十分有用
```
注意里面还有个v2ray，其实也是xray，所以复制两次进
```

**Comment by kensinxie** [comment]
好麻烦，所以为啥要更新？

**Comment by amiter** [comment]
`更新PAC：
我用这个项目：https://raw.githubusercontent.com/Loukky/gfwlist-by-loukky/master/gfwlist.txt`

sonoma PAC更换后能启动了

**Comment by dongxr** [comment]
还是等可以正常用的版本吧 3.3.0 codesign还能凑活用

**Comment by CastleDream** [comment]
退回3.4了，更新了3.8没法科学上网了。。。不知道为啥

**Comment by yysw** [comment]
退回到3.1.0才可以用。。。等稳定了再升级吧，最大的诉求就是可用。

**Comment by fzlinjianhui** [comment]
> 十分有用
> 
> ```
> 注意里面还有个v2ray，其实也是xray，所以复制两次进
> ```

为啥我下载下来没有看到v2ray这个文件，只有xray

**Comment by bingli2019** [comment]
mac book air M1 13.4.1 更新3.8.0之后如此操作，还是无法科学上网

**Comment by rex5652** [comment]
> > 十分有用
> > ```
> > 注意里面还有个v2ray，其实也是xray，所以复制两次进
> > ```
> 
> 为啥我下载下来没有看到v2ray这个文件，只有xray

@fzlinjianhui 一样的，同理替换

**Comment by StalkingWolf2023** [comment]
> > 十分有用
> > ```
> > 注意里面还有个v2ray，其实也是xray，所以复制两次进
> > ```
> 
> 为啥我下载下来没有看到v2ray这个文件，只有xray

滑稽，我看了一下日志，下载下来解压出来只有一个xray，只替换xray貌似是没用的，启动的时候日志显示还是1.5.5，版主说的不太明白，我的解决方法是创建一个1.8的xray副本，然后把它改名称v2ray替换掉原装的v2ray，再启动日志里就显示是1.8了。实际到底有没有用我也不知道。。。。。。
另外我这边的SS协议貌似是可以用的，并没有出现不能用的问题。
之前倒是出现过从软件关闭代理失效的问题，每次都要手动关闭设置里的代理开关。。。。。。完全卸载重装之后似乎好了
<img width="644" alt="截屏2023-08-21 下午6 38 18" src="https://github.com/yanue/V2rayU/assets/142795011/ade89f42-ea42-4192-a0dd-e71f7469ba1b">

**Comment by xpader** [comment]
这么麻烦的吗？
之前不是 3.3.0 之后 PAC 功能去掉了吗？后面的版本又加回来了？
