### ISSUE TITLE
v3.3.0 升级到 v3.8.0 可科学上网但Trojan订阅节点的延迟都是-1ms

### ISSUE THREAD

**Issue by chosen1cwp** [yanue/V2rayU#1291]
1) 使用的 V2RayU版本：v3.8.0，Mac 版本：MacBook Pro (Retina, 15-inch, Mid 2015) macOS Monterey 12.3.1 (21E258) 

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

在 版本 v3.3.0时，配置Trojan订阅无法科学上网，删除V2RayU后，重新下载了v3.8.0版本，配置Trojan订阅发现可以科学上网，但是发现一个问题：

延迟测试后（Ping Speed ...）,所有订阅节点的延迟都是-1ms

![V2rayU2023-07-26](https://static.chosen1cwp.com/V2rayU2023-07-26.png)

3)  延迟测试后（Ping Speed ...）查看v2ray日志如下

```javascript
    2023/07/26 10:20:32 [Info] [1308358864] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
```

**Comment by chengfine** [comment]
Ping Speed 多点几次

**Comment by chosen1cwp** [comment]
> 

点击ping speed ,...N次后，依旧-1ms

**Comment by imxintian** [comment]
为啥我的 ss vmess 和 vless 协议的都可以使用，但是Trojan 类型的不能使用

**Comment by hexi618** [comment]
> > 
> 
> 点击ping speed ,...N次后，依旧-1ms

我的使用中，订阅导入的地址都是 -1ms，但是通过复制 vmess 地址导入的节点，它都 ping 出响应时间了，不知道啥原因……
