### ISSUE TITLE
能不能设置成“绕过大陆”模式？

### ISSUE THREAD

**Issue by ahon23** [yanue/V2rayU#1294]
你好，程序员老师。我想问下v2rayu能不能像win端的v2rayn那样有个“绕过大陆”模式？pac模式已经用不习惯啦~~
另外想请教一下，routing里面的路由模式是什么作用呢？我没看懂用懂🤣
感谢！

**Comment by Mabbs** [comment]
路由就可以设置绕过大陆，设置成绕过大陆模式开全局就行了
