### ISSUE TITLE
弱弱的问一下，这个怎么用啊

### ISSUE THREAD

**Issue by Jessicawyml** [yanue/V2rayU#13]
弱弱的问一下，这个怎么用啊，第一次用，不知道怎么使用源代码打包成APP格式。求教

**Comment by yanue** [comment]
有v2ray账号,或是ss账号吗,  有的话,可以直接导入或手动配置, 如果你用过shadowsocksX的话,应该是比较容易的
这个是为macos设计的,app那边已经有对应的软件了,如: Kitsunebi Lite(美区),其他见: https://www.v2ray.com/ui_client/ios.html
