### ISSUE TITLE
Unable to update the core to 1.8.3 on v2rayu 3.8.0

### ISSUE THREAD

**Issue by Heclalava** [yanue/V2rayU#1300]
v2ray 3.8.0 is running core 1.7.5 which doesn't work with xray REALITY. It needs at least xray core 1.8.0 or higher. 
![image](https://github.com/yanue/V2rayU/assets/8341359/d11c0995-c146-42c3-8fd1-b350e27c8385)
When I click update the update fails:
![image](https://github.com/yanue/V2rayU/assets/8341359/10e216b6-e2b4-40a9-9cf8-65e1ff821b73)
How do I get the core updated to 1.8.3?

**Comment by xyz3282836** [comment]
You can update xray to the latest version yourself.
The file directory of xray and the log file are in the same directory.

**Comment by Heclalava** [comment]
I assume it will be the Xray-macos-64.zip? It's an older Mac that doesn't have the M1 chip. 

Besides the core any other files that need to be overwritten?

**Comment by xyz3282836** [comment]
![CleanShot 2023-08-11 at 17 31 43](https://github.com/yanue/V2rayU/assets/8153727/c52ea682-b80f-441a-b3f6-3bb5e0b40213)
you need rename xray to v2ray

**Comment by Heclalava** [comment]
> ![CleanShot 2023-08-11 at 17 31 43](https://user-images.githubusercontent.com/8153727/259971797-c52ea682-b80f-441a-b3f6-3bb5e0b40213.png) you need to rename xray to v2ray

When I go to that hidden folder I am seeing two core files, v2ray AND xray
![image](https://github.com/yanue/V2rayU/assets/8341359/1c8b8653-e2c6-469c-acd0-9581c199d739)
So do I rename the core that I downloaded to v2ray and overwrite the v2ray file?
Or do I not rename and just overwrite the xray file?

**Comment by Heclalava** [comment]
I have tried with both overwriting xray and renaming the xray and overwriting v2ray. Now I am constantly getting this 
![image](https://github.com/yanue/V2rayU/assets/8341359/63c0a12c-b9e5-4011-8cc9-74ee6054d92f)
when I interact with v2rayU.

**Comment by Heclalava** [comment]
I overwrite both files, it has managed to get my xray REALITY servers working, thanks for the help.

**Comment by AI2Hub** [comment]
> I assume it will be the Xray-macos-64.zip? It's an older Mac that doesn't have the M1 chip.
> 
> Besides the core any other files that need to be overwritten?

you download Xray-macos arm version
