### ISSUE TITLE
能不能一键清除无用节点，并能够一键测试实际速度？

### ISSUE THREAD

**Issue by nomco** [yanue/V2rayU#1303]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 3.8和 Mac 版本 14 beta 23a5103g？

2) 节点太多，想一键删除-1的节点。再有最好能一键测试实际连接速度以便选择最好用的节点。（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // i5-7600t 8gddr42400联想AIO 510-23ISH一体机
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 无错误，就是使用体验。
```

请预览一下你填的内容再提交。

**Comment by nomco** [comment]
还不能一键删除节点，节点得一个一个删除。

**Comment by Biohacking6141** [comment]
测速是最重要的，目前在windows下能用的节点，macos （ventura）就不行了。
