### ISSUE TITLE
这个项目是不是对v2ray-core项目包了一层UI？

### ISSUE THREAD

**Issue by dagundejuzi** [yanue/V2rayU#1304]
看到这个项目里，v2ray-core的版本是1.7.5，但是v2ray-core都发布到5.7.0了，能不能把项目里的也换成新的v2ray-core？直接替换文件可以吗？

**Comment by DesireDriver** [comment]
> 

v2rayu中虽然用到了v2ray-core这个名字，但是内核其实是xray-core，ps：感觉v2rayu的issue回答不是很活跃
