### ISSUE TITLE
怎么设置 user-agent

### ISSUE THREAD

**Issue by yolans** [yanue/V2rayU#1305]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.8.0
Mac m2 13.3
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
怎么设置 user-agent，我在 .V2rayU/config.json  和 导入模式设置都不生效，UI上也没有设置的地方，有别的地方设置吗？后面在UI增加可以设置的地方吗？
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```
  "streamSettings": {
        "wsSettings": {
          "path": "***",
          "headers": {
            "host": "",
            "User-Agent":""
          }
        }
```
4)  请附上出错时软件输出的错误日志。

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
手动编辑模式
