### ISSUE TITLE
内核自动更新到1.5.5的bug

### ISSUE THREAD

**Issue by cjjun** [yanue/V2rayU#1309]
作者大大，在这个目录https://github.com/yanue/V2rayU/blob/master/V2rayU/V2rayCore.swift
第17和18行，写死了更新内核到1.5.5的版本的url。

这一现象导致每次xray-core的release更新时，V2rayU一旦检测到更新，会自动调用同页面的更新函数更新到1.5.5的内核版本（实际为降级）；并且由于1.5.5不支持新版协议，会直接导致无法访问github手动替换内核。

希望作者能在百忙之中修复该bug，或者干脆停止自动更新；因为这两天rprx把1.8.4的prelease转为正式版，大规模地导致mac用户今天挂掉，影响还挺大的。

**Comment by sonic3366** [comment]
同遇到类似的问题了。
临时解决办法是，flow这里为空

**Comment by ldw4033** [comment]
> v2ray

下载最新版本 xray-core   替换掉 `~/.V2rayU/v2ray-core`里 的所有文件 , 把xray复制一份并重命名为v2ray，重启V2rayU， ~/.V2rayU 有其他配置文件，删除可能需要重新配置。

**Comment by cjjun** [comment]
> > v2ray
> 
> 下载最新版本 xray-core 替换掉 `~/.V2rayU/v2ray-core`里 的所有文件 , 把xray复制一份并重命名为v2ray，重启V2rayU， ~/.V2rayU 有其他配置文件，删除可能需要重新配置。

这样替换没用的；我指的是替换/Applications/V2rayU.app/Contents/Resources/v2ray-core里的同名文件，真正的源包在那；
~/.V2rayU/v2ray-core只是一个部署的临时文件，就算替换了 过一段时间部署也会被源包重新覆盖掉。

**Comment by choicky** [comment]
我之前手工升级到 xray 1.8.x 了，最近又被自动更新到 1.5.5 了
希望大佬们能修复这个bug

**Comment by AI2Hub** [comment]
> 我之前手工升级到 xray 1.8.x 了，最近又被自动更新到 1.5.5 了 希望大佬们能修复这个bug

将自动更新选项去掉，替换 v2ray-core 目录内容

**Comment by cjjun** [comment]
> > 我之前手工升级到 xray 1.8.x 了，最近又被自动更新到 1.5.5 了 希望大佬们能修复这个bug
> 
> 将自动更新选项去掉，替换 v2ray-core 目录内容

自动更新button管的是app的更新，而core的更新是check()函数管的，这玩意是定时强制执行的。

。。。这是作者自己写着忘了（他注释里都写了要记得替换掉version，但下面download依然是直接把这个url下载了）

你们回复的无关错误的信息越多，作者越看不到我的issue。读一下代码吧哥 我都标记出位置了；要不是swift这语言反人类，还得绑定XCODE开发者，我就自己修了

**Comment by imxintian** [comment]
> 我之前手工升级到 xray 1.8.x 了，最近又被自动更新到 1.5.5 了 希望大佬们能修复这个bug

我也是哎
