### ISSUE TITLE
编译tag v3.8.0按照作者的方式git clone，pod install，放置好v2raycore，打开xcode项目文件，改Team为自己的账号，证书为Sign to Run Locally，build项目提示如下，找不到Shortcut.h?

### ISSUE THREAD

**Issue by DesireDriver** [yanue/V2rayU#1311]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.8.0
Mac 13.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
编译tag v3.8.0按照作者的方式git clone，pod install，放置好v2raycore，打开xcode项目文件，改Team为自己的账号，证书为Sign to Run Locally，build项目提示如下，找不到Shortcut.h

```
/Users/xxx/swift/V2rayU/Common/V2rayU-Bridging-header.h:5:9: error: 'MASShortcut/Shortcut.h' file not found
#import <MASShortcut/Shortcut.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/xxx/Library/Developer/Xcode/DerivedData/V2rayU-fnzsabzidlhyuzdzwukhyxxigkfy/Build/Intermediates.noindex/PrecompiledHeaders/V2rayU-Bridging-header-swift_1X6WG2PLT0N53-clang_120MTAL8OX8X8.pch' for bridging header '/Users/xxx/swift/V2rayU/Common/V2rayU-Bridging-header.h'

```

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by Mabbs** [comment]
看报错信息你也许你应该用Swift Package Manager安装https://github.com/shpakovski/MASShortcut

**Comment by DesireDriver** [comment]
> 看报错信息你也许你应该用Swift Package Manager安装https://github.com/shpakovski/MASShortcut

具体应该怎么做呢？如果我是编译V2RayUtool这个target是可以编译成功的，但是无论是Debug还是Release模式下的到的二进制文件都和GitHub上发布的v3.8.0中包含的V2RayUtool大小不一致，大小差别挺大的，这个应该如何编译才能做到编译出和github上release上一摸一样的二进制文件呢？
