### ISSUE TITLE
v2Ray-Core启动失败没有提示信息

### ISSUE THREAD

**Issue by Life-Of-Coding** [yanue/V2rayU#1325]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

    V2RayU版本为V3.8.0   Mac版本为Mac Monterey 12.6.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

    因误操作更改 ~/Library/LaunchAgents 文件夹的用户组导致 v2RayU 无法使用。详情如下所述——
Turn v2ray-core on 之后，没有任何提示信息，而且查看v2ray-core日志发现日志不更新，于是使用Xcode debug。Debug过 
       程中见到"Start v2ray-core failed."，遂追踪到如下代码
![截屏2023-10-13 14 30 32](https://github.com/yanue/V2rayU/assets/58926959/5d7937d9-fcff-4062-80f0-d2ca869ed18a)

       手动执行 launchctl list 命令，没有找到 "yanue.v2rayu.v2ray-core"，发现代码没有检测.plist文件正常创建，如下图示
![截屏2023-10-13 14 35 18](https://github.com/yanue/V2rayU/assets/58926959/01bbb975-3d07-4881-9039-5795f328c65e)

       整个过程中v2RayU的状态、Icon正常切换，且没有任何提示。
![截屏2023-10-13 14 36 46](https://github.com/yanue/V2rayU/assets/58926959/0ab96aa2-1688-478b-9529-3c1ec2ef7322)
      
请问是否有必要加上相应的提示信息？
       

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/v4.0.0
