### ISSUE TITLE
无论选择哪个server都还是使用的之前的某个serverA

### ISSUE THREAD

**Issue by wangke0809** [yanue/V2rayU#135]
重启软件，重启电脑，删除所有订阅，不添加 serverA，添加 serverB，走的还是 A 的网络。

**Comment by wangke0809** [comment]
已经更新到最新版了。

**Comment by yanue** [comment]
还有这个问题吗 最近没时间看

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: pizi <notifications@github.com>
发送时间: Tuesday, July 16, 2019 11:01:52 PM
收件人: yanue/V2rayU
抄送: Subscribed
主题: Re: [yanue/V2rayU] 无论选择哪个server都还是使用的之前的某个serverA (#135)


Closed #135<https://github.com/yanue/V2rayU/issues/135>.

―

**Comment by wangke0809** [comment]
回复下这个问题：查询日志发现是系统代理端口被占用，查看占用该端口的应用发现是ss开启的代理，导致V2rayU开启代理失败，重启电脑后ss代理竟然还自动开启了，kill掉ss后可正常使用。
