### ISSUE TITLE
4.0预览版Bug

### ISSUE THREAD

**Issue by visense** [yanue/V2rayU#1353]
[4.0预览版]
1、手动设置grpc协议时，分享二维码里的链接出现path
正常情况下，grpc是serviceName和multiMode，
2、用订阅链接更新后，grpc的serviceName和multiMode获取不到值，window版的订阅正常
<img width="439" alt="iShot_2023-11-13_03 22 56" src="https://github.com/yanue/V2rayU/assets/3490833/442e52d2-12ec-4d10-af5b-6fe9b4255f44">

**Comment by yanue** [comment]
更新4.1试下

**Comment by visense** [comment]
> 更新4.1试下

感谢大佬回复，辛苦更新！
grpc协议，更新订阅链接，依旧获取不到serviceName和multiMode的值，同样的订阅链接在windows v2rayN中正常
