### ISSUE TITLE
使用 vaxilu / x-ui 面板分享VLESS+Reality节点链接URL，提示import server fail: invalid vless url

### ISSUE THREAD

**Issue by chouxiang99** [yanue/V2rayU#1354]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU版本：3.8.0
Mac版本：m1+版本14.0 (23A344)
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
使用 vaxilu / x-ui面板分享VLESS+Reality节点链接URL，提示import server fail: invalid vless url

链接的大概格式是：vless://6a0xxxxx-xxxx-4449-xxxx-07d1fd2xxxx@xxx.xxx.top:47111?type=tcp&security=reality&sni=www.inproel.com&pbk=9rxxxxxx-xxxxxEM9TQBO19BOAmmGjJyjN86ll2J7uVc&flow=xtls-rprx-vision&fp=chrome#|xx9J.lxxe@xray.com

这个格式导入windows的v2rayn可正常导入并且使用，所以搭建的节点是没问题的
导入的链接部分内容修改成了xxxx

**Comment by yanue** [comment]
4.1试下

**Comment by chouxiang99** [comment]
4.1版本可以了，感谢感谢


chouxiang99
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanue/V2rayU"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月28日(星期二) 中午1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanue/V2rayU] 使用 vaxilu / x-ui 面板分享VLESS+Reality节点链接URL，提示import server fail: invalid vless url (Issue #1354)





 
4.1试下
