### ISSUE TITLE
订阅来自http有域名的URL无法更新

### ISSUE THREAD

**Issue by oriengy** [yanue/V2rayU#136]
订阅来自如 http://v.naive.com/sub.txt 的地址时无法更新，瞬间报错，抓包没有http包。
订阅来自如 http://38.106.21.xxx/sub.txt 的地址可以更新，可以抓到http包。
https订阅可用。
推测获取http协议的URL时的DNS解析过程有bug。不会写swift，望修复。

**Comment by yanue** [comment]
有显示loading fail : 吗

**Comment by oriengy** [comment]
> 有显示loading fail : 吗

有的，在我的环境中可以稳定复现。
包括localhost也解析不了，127.0.0.1可以用。
我昨天看了代码，你用的是Alamofire包，你的代码完全没有实现请求过程我就不知道怎么办了。

**Comment by yanue** [comment]
我测试都没有问题哦

**Comment by Jevanzhu** [comment]
我也出现这个问题了，不过是在虚拟机的macos下，只能用IP，试用域名的话，瞬间报错fail。明天再在真机上试试。

**Comment by aishlai** [comment]
我的也是，瞬间fail，我用手机端V2rayNG，是可以订阅我生成的url的

使用V2rayU

只要是http + 域名就不行
https+域名可以
http+ip 也可以

iMac10.14.6
