### ISSUE TITLE
1.3.3 安装和权限问题

### ISSUE THREAD

**Issue by xpol** [yanue/V2rayU#137]
在 macOS Mojave 10.14.5 下面：

1.3.3 的 DMG 安装包 Applications 指向的是： `/System/Volumes/Data/Device/Applications` ，拖拽安装会出现：

![image](https://user-images.githubusercontent.com/20248/61260831-52ff6f80-a7b2-11e9-8456-489d481fbeb0.png)

安装不成功，直接拖拽到 /Applications 目录后，每次启动 V2RayU 和会出现下面对话框：

![image](https://user-images.githubusercontent.com/20248/61260903-935eed80-a7b2-11e9-8e4f-c8b9fd7bf103.png)

输入密码后又会出现：

![image](https://user-images.githubusercontent.com/20248/61260909-9e198280-a7b2-11e9-851d-af713f0a6a7d.png)

以后切换服务器也会出现上面这个对话框。

换 1.3.1 dmg 不会出现上述问题。

**Comment by yanue** [comment]
1.3.2有这个问题吗 主要是升级到swift5过后 V2rayUTool编译会导致10.14.3无法切换网络,所以直接用了以前编译好的的V2rayUTool

**Comment by xpol** [comment]
1.3.2 刚才测试了一下，也有这个问题。1.3.2 DMG 里面没有 Applications 快捷方式。

**Comment by yanue** [comment]
dmg打包出问题  没注意 另外那应该是 /Applications/V2rayU.app/Contents/MacOS/V2rayUTool 这个文件权限问题

**Comment by rain0527** [comment]
1.3.3我也遇到同样的问题

**Comment by RealDeanZhao** [comment]
1.4我也遇到这个问题，有什么方法解决吗

**Comment by yanue** [comment]
使用命令行加权限试下
```
cd /Applications/V2rayU.app/Contents/MacOS/
sudo chown root:admin ./V2rayUTool
sudo chmod a+rx ./V2rayUTool
sudo chmod +s ./V2rayUTool
echo done
```
