### ISSUE TITLE
V2ray（v3.8.0） Mac上不能使用

### ISSUE THREAD

**Issue by iris090866** [yanue/V2rayU#1371]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU Version3.8.0   mac版本Apple M1   OS 版本14.1.2 (23B92)
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
 订阅的付费节点 都显示-1ms，打不开谷歌等外国的网站，显示：无法访问此网站 www。Google。com被意外终止了。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "access": "",
    "loglevel": "info",
    "error": ""
  },
  "inbounds": [
    {
      "port": "1080",
      "listen": "127.0.0.1",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "protocol": "socks"
    },
    {
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087",
      "listen": "127.0.0.1"
    }
  ],
  "outbounds": [
    {
      "streamSettings": {
        "wsSettings": {
          "path": "/80080f42e36c6478a808050e.v1.live.m3u8",
          "headers": {
            "host": ""
          }
        },
        "security": "none",
        "network": "ws"
      },
      "protocol": "vmess",
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "users": [
              {
                "id": "0ea8aa58-8068-3f99-b37b-6cf570763659",
                "level": 0,
                "alterId": 0,
                "security": "auto"
              }
            ],
            "address": "hfa1.cdn.node.a.yddns-ounk.com",
            "port": 13455
          }
        ]
      },
      "mux": {
        "enabled": false,
        "concurrency": 8
      }
    },
    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      },
      "tag": "block"
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
4)  请附上出错时软件输出的错误日志。
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:36:23 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:36:23 [Info] app/dns: DNS: created localhost client
2023/12/09 14:36:23 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:37:08 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:37:08 [Info] app/dns: DNS: created localhost client
2023/12/09 14:37:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:37:18 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:37:18 [Info] app/dns: DNS: created localhost client
2023/12/09 14:37:18 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:37:45 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:37:45 [Info] app/dns: DNS: created localhost client
2023/12/09 14:37:45 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:37:56 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:37:56 [Info] app/dns: DNS: created localhost client
2023/12/09 14:37:56 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:40:35 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:40:35 [Info] app/dns: DNS: created localhost client
2023/12/09 14:40:35 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 14:40:45 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 14:40:45 [Info] app/dns: DNS: created localhost client
2023/12/09 14:40:45 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 16:19:57 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 16:19:57 [Info] app/dns: DNS: created localhost client
2023/12/09 16:19:57 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 16:21:15 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 16:21:15 [Info] app/dns: DNS: created localhost client
2023/12/09 16:21:15 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 16:40:41 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 16:40:41 [Info] app/dns: DNS: created localhost client
2023/12/09 16:40:41 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 16:45:37 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 16:45:37 [Info] app/dns: DNS: created localhost client
2023/12/09 16:45:37 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 16:48:08 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 16:48:08 [Info] app/dns: DNS: created localhost client
2023/12/09 16:48:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 17:37:45 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 17:37:45 [Info] app/dns: DNS: created localhost client
2023/12/09 17:37:45 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 17:39:28 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 17:39:28 [Info] app/dns: DNS: created localhost client
2023/12/09 17:39:28 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 18:02:04 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 18:02:04 [Info] app/dns: DNS: created localhost client
2023/12/09 18:02:04 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 18:05:05 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 18:05:05 [Info] app/dns: DNS: created localhost client
2023/12/09 18:05:05 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 18:07:03 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 18:07:03 [Info] app/dns: DNS: created localhost client
2023/12/09 18:07:03 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 18:07:13 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 18:07:13 [Info] app/dns: DNS: created localhost client
2023/12/09 18:07:13 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 18:30:59 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 18:30:59 [Info] app/dns: DNS: created localhost client
2023/12/09 18:30:59 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 22:49:56 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 22:49:56 [Info] app/dns: DNS: created localhost client
2023/12/09 22:49:56 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 22:50:10 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 22:50:10 [Info] app/dns: DNS: created localhost client
2023/12/09 22:50:10 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:00:22 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:00:22 [Info] app/dns: DNS: created localhost client
2023/12/09 23:00:22 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:28:07 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:28:07 [Info] app/dns: DNS: created localhost client
2023/12/09 23:28:07 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:40:13 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:40:13 [Info] app/dns: DNS: created localhost client
2023/12/09 23:40:13 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:41:00 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:41:00 [Info] app/dns: DNS: created localhost client
2023/12/09 23:41:00 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:44:19 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:44:19 [Info] app/dns: DNS: created localhost client
2023/12/09 23:44:19 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:45:49 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:45:49 [Info] app/dns: DNS: created localhost client
2023/12/09 23:45:49 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:46:00 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:46:00 [Info] app/dns: DNS: created localhost client
2023/12/09 23:46:00 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:47:06 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:47:06 [Info] app/dns: DNS: created localhost client
2023/12/09 23:47:06 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:51:50 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:51:50 [Info] app/dns: DNS: created localhost client
2023/12/09 23:51:50 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:52:58 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:52:58 [Info] app/dns: DNS: created localhost client
2023/12/09 23:52:58 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:53:08 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:53:08 [Info] app/dns: DNS: created localhost client
2023/12/09 23:53:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/09 23:53:19 [Info] infra/conf/serial: Reading config: config.json
2023/12/09 23:53:20 [Info] app/dns: DNS: created localhost client
2023/12/09 23:53:20 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/10 00:00:13 [Info] infra/conf/serial: Reading config: config.json
2023/12/10 00:00:13 [Info] app/dns: DNS: created localhost client
2023/12/10 00:00:13 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/10 00:10:50 [Info] infra/conf/serial: Reading config: config.json
2023/12/10 00:10:50 [Info] app/dns: DNS: created localhost client
2023/12/10 00:10:50 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/10 00:11:23 [Info] infra/conf/serial: Reading config: config.json
2023/12/10 00:11:23 [Info] app/dns: DNS: created localhost client
2023/12/10 00:11:23 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/10 00:11:54 [Info] infra/conf/serial: Reading config: config.json
2023/12/10 00:11:54 [Info] app/dns: DNS: created localhost client
2023/12/10 00:11:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/10 01:10:08 [Info] infra/conf/serial: Reading config: config.json
2023/12/10 01:10:08 [Info] app/dns: DNS: created localhost client
2023/12/10 01:10:08 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/arm64)
A unified platform for anti-censorship.
2023/12/10 01:22:31 [Info] infra/conf/serial: Reading config: config.json
2023/12/10 01:22:31 [Info] app/dns: DNS: created localhost client
2023/12/10 01:22:31 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start: app/proxyman/inbound: failed to listen TCP on 1087 > transport/internet: failed to listen on address: 127.0.0.1:1087 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by LhhhL** [comment]
我也遇到了同样的问题

**Comment by iris090866** [comment]
> 我也遇到了同样的问题

我昨天在网上找了个帖子 设置了socks代理，暂时能打开外部网页了；但是我谷歌上看我的ip地址是中国🤦，也不知道用gpt会不会被发现；
https://www.bandianxiang.com/info/Z0LadtX&wd=&eqid=dad304840007c08100000002656206af

设置代理：
在 macOS 系统可以使用系统代理设置来配置 v2ray。
打开“系统偏好设置”，选择“网络”，选择当前使用的网络连接。
在“高级”选项卡里选择“代理”，选择“SOCKS代理”。
在“SOCKS代理服务器”中输入“127.0.0.1”和“1080”（1080 是配置文件的port端口），然后保存设置。

**Comment by cjjun** [comment]
老bug了，检测到xray更新因而自动升级到固定url的1.5.5，反而实质上等同于降级；

给作者提过issue，已经在4.0版本修复了，可以下载最新版 https://github.com/yanue/V2rayU/releases/tag/v4.1.0，覆盖老版就好了

**Comment by alexya** [comment]
@cjjun 我试着升级到4.1.0，还是不行。直接core crash. 
显示 `Start v2ray-core failed`

**Comment by Wallfacer005CN** [comment]
> 老bug了，检测到xray更新因而自动升级到固定url的1.5.5，反而实质上等同于降级；
> 
> 给作者提过issue，已经在4.0版本修复了，可以下载最新版 https://github.com/yanue/V2rayU/releases/tag/v4.1.0 直接覆盖老版3.8.0就好了

怎么配置xray呢？
