### ISSUE TITLE
Mac OS 12 安装V2RayU 3.8.0 全局模式 VM nat模式下的虚拟机无法联网

### ISSUE THREAD

**Issue by sparkjack** [yanue/V2rayU#1372]
Mac 版本：Mac OS Monterey V2RayU版本：V2RayU 3.8.0

1、宿主机使用V2RayU 3.8.0代理功能可正常使用。
2、VM nat模式下的虚拟机无法在V2RayU全局模式下联网，在不使用V2RayU代理模式下，虚拟机可以正常访问国内网站。
3、尝试解决办法：
3.1、V2RayU使用1.5版和1.5.1版本的全局模式，虚拟机都无法联网。
3.2、V2RayU使用1.5版和1.5.1版本的手动模式下，更改V2RayU的本地监听IP为0.0.0.0，设置虚拟机上浏览器的代理为宿主机IP，还是不能正常访问外部网站。
3.3、V2RayU 3.8.0修改本地ip监听为0.0.0.0，全局模式和手动模式虚拟机都无法联网。

**Comment by sparkjack** [comment]
V2RayU 3.8.0修改本地ip监听为0.0.0.0，虚拟机和宿主机在一个网段，才可以正常使用吗？

**Comment by iris090866** [comment]
我也是Mac用V2ray 谷歌和safari都开不开外部网页；节点都显示-1ms；不知咱们是不是一个问题

**Comment by sparkjack** [comment]
> 我也是Mac用V2ray 谷歌和safari都开不开外部网页；节点都显示-1ms；不知咱们是不是一个问题

我的宿主机可以正常使用，nat模式下的虚拟机无法访问外部网页

**Comment by sparkjack** [comment]
问题解决了，之前虚拟机的网关有问题，重新设置一下虚拟的网卡就可以了。

**Comment by sparkjack** [comment]
问题解决了，之前虚拟机的网关有问题，重新设置一下虚拟的网卡就可以了。
