### ISSUE TITLE
4.0、4.1 在pac模式下无法打开google

### ISSUE THREAD

**Issue by chenyuchenluo** [yanue/V2rayU#1376]
两个最新版本在全局模式可以访问google。3.8在两个模式下正常。使用的自建vmess节点，如果大家没遇到这个问题那就是我节点的问题了。

**Comment by linch526** [comment]
我的在pac模式下也是无法访问，我还以为账户有啥问题了，看了你的用全局模式试了下可以访问

**Comment by h3lp404** [comment]
把google.com加入pac列表，现在不能访问的就添加pac列表了

**Comment by IT-NuanxinPro** [comment]
我的也是 pac模式下 不能访问

**Comment by hj149** [comment]
`proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > websocket: close 1000 (normal) > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)`
两台电脑上都没法用，报上面的错误，一直降版本到3.5才好使的，供参考

**Comment by xyz3282836** [comment]
先切到全局，访问下google，再切到pac就可以了

**Comment by chenyuchenluo** [comment]
解决办法总结：
1. 换成了3.8版本（我就是）
2. 先切换全局，访问后切回pac
3. 手动在pac添加google域名
