### ISSUE TITLE
为什么我的telegram一直是connecting

### ISSUE THREAD

**Issue by Smith-Cruise** [yanue/V2rayU#139]
我v2rayu配置正常的，google，YouTube都能正常访问。然后我Telegram设置本地代理，已经能够成功显示ping了，但是连接就是一直connecting。

![image](https://user-images.githubusercontent.com/18729228/61345164-a17e3e00-a886-11e9-902e-995c24454638.png)

**Comment by Smith-Cruise** [comment]
换成了Telegram Desktop版本就行了。醉了。

**Comment by edmund-zhao** [comment]
I faced with the same Question. I will try to use your idea to deal with it.

**Comment by stan8341** [comment]
i have the same problem with windows version

**Comment by hxbo** [comment]
设置好代理，记得一定要重启telegram。不然会一直connecting。

**Comment by shijiezhou1** [comment]
设置 重启也是不行。 8.7.2 版本的telegram 和  v3.2.0 版本的v2

**Comment by shijiezhou1** [comment]
设置 重启也是不行。 8.7.2 版本的telegram 和  v3.2.0 版本的v2
