### ISSUE TITLE
4.1.0 开机启动问题和快捷键打开关闭的提示问题

### ISSUE THREAD

**Issue by zyw5535** [yanue/V2rayU#1398]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
4.1.0，MACOS 10.15.7

2) 你遇到的问题是什么？
1.开机自动启动无效
  启动项中只有yanue.v2rayu.v2ray-core(启动代理)，3.8.0是启动程序
2.快捷键打开关闭代理不提示了，3.8.0可提示。

**Comment by ifr0zen** [comment]
开机启动可以添加这个
<img width="668" alt="QQ20240409-121134@2x" src="https://github.com/yanue/V2rayU/assets/17274321/4d22c875-99c3-4b49-bd13-8fea9203ccaf">
