### ISSUE TITLE
默认“pac模式”下，打不开网站

### ISSUE THREAD

**Issue by bbsccbs** [yanue/V2rayU#1413]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.8和 Mac 14.4.1。
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
默认“pac模式”下，打不开google网站，几乎都打不开。但在“全局模式”下是可以打开的。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by Rabin5214** [comment]
1. 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 4.1和 Mac 14.4.1。
你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
默认“pac模式”下，打不开google网站，几乎都打不开。但在“全局模式”下是可以打开的。
遇到的问题：显示连接超时
请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    // {
  "log": {
    "loglevel": "info",
    "access": "",
    "error": ""
  },
  "inbounds": [
    {
      "settings": {
        "auth": "noauth",
        "udp": false
      },
      "protocol": "socks",
      "listen": "127.0.0.1",
      "port": "1080"
    },
    {
      "settings": {
        "timeout": 360
      },
      "port": "1087",
      "listen": "127.0.0.1",
      "protocol": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "trojan",
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "settings": {
        "servers": [
          {
            "password": "none",
            "email": "",
            "address": "none",
            "port": 4003,
            "flow": "",
            "level": 0
          }
        ]
      },
      "streamSettings": {
        "security": "tls",
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true,
          "fingerprint": "chrome",
          "serverName": ""
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      },
      "tag": "direct"
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "domain": [
            "geosite:cn",
            "localhost"
          ],
          "outboundTag": "direct"
        },
        {
          "outboundTag": "direct",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "type": "field"
        }
      ]
    }
  }
}
请附上出错时软件输出的错误日志。
    // 2024/04/24 15:36:17 [Info] [2468866930] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > EOF
请预览一下你填的内容再提交。

**Comment by zenz** [comment]
同时本地的IP过滤也被忽略了。

**Comment by tianjingdong** [comment]
这个问题我也是找了很久才发现原因，偏好设置--General----取消勾选  “自动检测版本更新”  和 “启动或唤醒时自动从订阅中更新” 两个 选项，就OK了

**Comment by czxdzt** [comment]
> 这个问题我也是找了很久才发现原因，偏好设置--General----取消勾选 “自动检测版本更新” 和 “启动或唤醒时自动从订阅中更新” 两个 选项，就OK了

没用诶，你说的两项，我看了下，本来就没有勾选。我还以为是我这边梯子服务提供商的问题，现在上来一看，原来大家都这样。

**Comment by dmnotdm** [comment]
pac设置 -> 保存设置并从GFW List更新

**Comment by dmnotdm** [comment]
> > 这个问题我也是找了很久才发现原因，偏好设置--General----取消勾选 “自动检测版本更新” 和 “启动或唤醒时自动从订阅中更新” 两个 选项，就OK了
> 
> 没用诶，你说的两项，我看了下，本来就没有勾选。我还以为是我这边梯子服务提供商的问题，现在上来一看，原来大家都这样。


pac设置 -> 保存设置并从GFW List更新

**Comment by bububuhe** [comment]
> > > 这个问题我也是找了很久才发现原因，购买设置--General----取消勾选“自动检测版本更新”和“启动或唤醒时自动从订阅中更新”两个选项，就OK了
> > 
> > 
> > 我觉得这就是我选择的那个问题，你正在选择一个。我看了下面的这个定义，本来它是定义好的选择。
> 
> pac 设置 -> 保存设置 建议GFW 列表更新

这个方法可行，未点击前 ”PAC 设置--浏览 pac 文件“ 无法打开，点击以后 pac 模式可以使用，也能查看 pac 文件了，猜测点保存以后才生成某些文件

**Comment by YOHN89** [comment]
我这里也有同样的问题，PAC下不起作用，只能开全局。

**Comment by qihboy** [comment]
> > > > 这个问题我也是找了很久才发现原因，购买设置--General----取消勾选“自动检测版本更新”和“启动或唤醒时自动从订阅中更新”两个选项，就OK了
> > > 
> > > 
> > > 我觉得这就是我选择的那个问题，你正在选择一个。我看了下面的这个定义，本来它是定义好的选择。
> > 
> > 
> > pac 设置 -> 保存设置 建议GFW 列表更新
> 
> 这个方法可行，未点击前 ”PAC 设置--浏览 pac 文件“ 无法打开，点击以后 pac 模式可以使用，也能查看 pac 文件了，猜测点保存以后才生成某些文件

这个方法真的可以，尤其是第一步“浏览pac文件”,  这个一定要点，我之前就是没点这个，只点了“保存设置并从GFW List更新”就不行。

**Comment by lilu668** [comment]
<img width="730" alt="iShot_2024-07-11_10 56 56" src="https://github.com/yanue/V2rayU/assets/30893776/cd76c167-f490-4e68-835b-91b90f070cc2">
设置里面更新一下这个就可以了

**Comment by zouhuigang** [comment]
使用pac模式太慢了，速度不及全局模式，怎么解决
