### ISSUE TITLE
作者大哥啊，您今天更新版本就更新版本，您把软件老版本又整死了，去年也出现过一次，又提示 “V2rayUTool”将对你的电脑造成伤害。 你应该将它移到废纸篓

### ISSUE THREAD

**Issue by Goog686ii** [yanue/V2rayU#1430]
![image](https://github.com/yanue/V2rayU/assets/38600824/608a4937-4a93-43ee-bd74-aa1efe96bb76)

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.8

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
打开软件出现提示“V2rayUTool”将对你的电脑造成伤害。 你应该把垃圾桶移到废纸篓
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by hiperioncn** [comment]
解决方式如下，选中覆盖恶意软件保护
<img width="494" alt="iShot2024-07-08 11 35 36" src="https://github.com/yanue/V2rayU/assets/6045710/e2cc0d40-61c3-4654-9053-18dcd94a758c">

**Comment by imakj** [comment]
我也有了

**Comment by xc564864894** [comment]
我也有了，按照图上能打开，但是还是一直弹提醒

**Comment by qihboy** [comment]
sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
