### ISSUE TITLE
今天突然提示“V2rayUTool”将对你的电脑造成伤害。 你应该把垃圾桶移到废纸篓

### ISSUE THREAD

**Issue by GitH123i** [yanue/V2rayU#1431]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.8版本

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
![image](https://github.com/yanue/V2rayU/assets/45822319/024ac8c4-0dcf-484f-a5e9-98db0d43dddf)

打开软件就提示“V2rayUTool”将对你的电脑造成伤害。 你应该把垃圾桶移到废纸篓，这样软件就没法正常运行
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by imyellow** [comment]
```
sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
```

**Comment by Chanzhaoyu** [comment]
> ```
> sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
> sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```

问题解决，Thanks

**Comment by pcyfff** [comment]
> ```
> sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
> sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```

灰常感谢 解决！

**Comment by yzw7489757** [comment]
> ```
> sudo /usr/bin/codesign --force --deep --sign - /Applications/V2rayU.app
> sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/V2rayUTool
> sudo /usr/bin/codesign --force --deep --sign - ~/.V2rayU/v2ray-core/v2ray
> ```

3q
