### ISSUE TITLE
MacBook m2 menu bar无法显示图标

### ISSUE THREAD

**Issue by txhxst** [yanue/V2rayU#1433]
MacBook Pro M2 max/ V2RayU 3.9.0, 4.2.2

试了两个版本，更新了系统，网上找了很多方法都没用，菜单栏就是不显示应用图标。其他应用都可以正常显示，clash verge的图标位置很怪但也勉强可以正常使用，V2Ray的就好像压根没这功能一样，怎么弄都没有。（确定没藏在刘海下面） 
新版本可以打开窗口，可以添加订阅，但没有其他按键没法操作。

**Comment by PzzAg6** [comment]
我也是，log也看不到了

**Comment by yanue** [comment]
试下命令行执行
```
sudo cd /Applications/V2rayU.app/Contents/Resources && sh install.sh
```

**Comment by Zeonova** [comment]
sh /Applications/V2rayU.app/Contents/Resources/install.sh

**Comment by PzzAg6** [comment]
> 试下命令行执行
> 
> ```
> sudo cd /Applications/V2rayU.app/Contents/Resources && sh install.sh
> ```

运行后显示
```
sh: install.sh: No such file or directory
```

**Comment by txhxst** [comment]
啊 下了个ibar解决了

**Comment by dsxyy** [comment]
> 试下命令行执行
> 
> ```
> sudo cd /Applications/V2rayU.app/Contents/Resources && sh install.sh
> ```

有用，不过不要带“sudo”，要不然切换不到Resources目录下
