### ISSUE TITLE
看教程搭建的，网速开始的时候下载速度可以达到300M，youtube看8k最高达到15万kb，后来速度就很慢了。请问这是哪里出了问题？或者谁可以提供个速度稳定的订阅链接

### ISSUE THREAD

**Issue by wangxinglove** [yanue/V2rayU#1445]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by qihboy** [comment]
服务器被限流了吧
