### ISSUE TITLE
自编译报错 Swift Compiler Error

### ISSUE THREAD

**Issue by raymao9** [yanue/V2rayU#145]
![QQ20190720-151954](https://user-images.githubusercontent.com/28225813/61575738-0abdb580-ab02-11e9-969f-512eb0e457b1.png)
尝试直接拉1.3.3和1.4.0直接build都不行
版本是xcode 10.1(10B61)，pod version 1.7.5

**Comment by yanue** [comment]
pod install

**Comment by sch1111878** [comment]
> pod install 不行?

需要把Podfile.lock加入到git管理中

**Comment by raymao9** [comment]
> pod install 不行?

此问题在 10.14.6 系统 xcode 11 中已解决

**Comment by sch1111878** [comment]
> > pod install 不行?
> 
> 此问题在 10.14.6 系统 xcode 11 中已解决

因为没有锁定版本号,所以之前会下载最新的依赖,xcode11 下载依赖对应Swift5.0 我还是建议作者上传 Podfile.lock
