### ISSUE TITLE
安装新版 4.2.3 提示最低支持系统为 macOS 11 

### ISSUE THREAD

**Issue by orzuzro** [yanue/V2rayU#1454]
1) 你正在使用的 V2RayU 和 Mac 版本 ？

macOS 10.15, V2RayU 4.2.3

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

安装提示只支持 macOS 11,想问下新版有考虑支持 macOS10.15吗？

总之，非常感谢~辛苦了，如果这个版本支持到macOS 11，可否在更新日志中标明下，再次感谢你.

**Comment by iHover2018** [comment]
注意: 系统需要11.0以上，更新日志里已经表明
