### ISSUE TITLE
Version 4.2.3 Vless ws mode cannot set flow as empty now

### ISSUE THREAD

**Issue by raebralop** [yanue/V2rayU#1457]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
4.2.3 MacOS14.5

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
After update from version 3.9 to Version 4.2.3. I am not able to save "flow" option as empty. Each time I tried to save this option it will revert to "xtls-rprx-vision" by itself.

**Comment by yanue** [comment]
尝试4.2.4

**Comment by raebralop** [comment]
It works now. Thank you.
