### ISSUE TITLE
全局模式事实上不是全局代理

### ISSUE THREAD

**Issue by ivyshow** [yanue/V2rayU#147]
目前的路由模式只有PAC和全局
如果选择全局的话，我看v2ray的服务器配置事实上是绕过大陆IP，用了GEOIP GEOSITE
这个还是会导致误判
建议能增加真正的全局模式，参考Windows端的v2rayN，增加一个设置项目控制v2ray内置的路由配置

**Comment by popofthedead** [comment]
我开启全局模式后就无法正常上网了，不知道是不是你说的这个问题造成的

**Comment by popofthedead** [comment]
开启全局模式无法上网的这个问题，要反馈需要提供哪些环境数据吗

**Comment by danywheeler** [comment]
https://github.com/yanue/V2rayU/issues/122

**Comment by danywheeler** [comment]
#122 
全局模式好像不准守v2ray 配置的路由规则了，全部流量走的是代理，然后你在网络配置中设置的忽略代理规则在切换服务器或者配置的时候，这些设置全部丢失了。

**Comment by yanue** [comment]
#202
