### ISSUE TITLE
Pac模式无法使用

### ISSUE THREAD

**Issue by chinastream** [yanue/V2rayU#1483]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU v4.2.5 Mac 14.5
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
选Pac模式+路由全局，但无法访问googe，只有选了全局模式才可以
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "access": "",
    "loglevel": "error",
    "error": ""
  },
  "inbounds": [
    {
      "port": "1080",
      "protocol": "socks",
      "listen": "0.0.0.0",
      "settings": {
        "udp": false,
        "auth": "noauth"
      }
    },
    {
      "port": "1088",
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 360
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "settings": {
        "vnext": [
          {
            "port": 17739,
            "users": [
              {
                "alterId": 0,
                "level": 0,
                "id": "xxxxx-f2c3-4558-8be3-xxxxx",
                "security": "auto"
              }
            ],
            "address": "xxxx.xxxx.xxxx.xxxx"
          }
        ]
      },
      "streamSettings": {
        "security": "none",
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      },
      "protocol": "vmess"
    },
    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "rules": [
      {
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn",
          "localhost"
        ],
        "outboundTag": "direct"
      }
    ],
    "domainStrategy": "AsIs",
    "balancers": []
  }
}
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
代理未成功，无日志输出，日志等级debug

请预览一下你填的内容再提交。

**Comment by elonleebj** [comment]
pac设置 -> 保存设置并从GFW List更新。猜测点保存以后才生成proxy.js

**Comment by chinastream** [comment]
谢谢您，已经解决！

**Comment by chinastream** [comment]
pac设置 -> 保存设置并从GFW List更新。生成proxy.js后可以使用了。
