### ISSUE TITLE
【bug】二维码信息不全

### ISSUE THREAD

**Issue by xiebruce** [yanue/V2rayU#149]
当使用kcp模式时，kcp有很多参数，但是用二维码导到另一台mac上(也是V2rayU)，kcp参数以及加密方式都使用了默认参数，说明二维码的参数没起作用，希望能解决一下：
![image](https://user-images.githubusercontent.com/13575500/62003019-5d225600-b142-11e9-806c-4b10e3081926.png)

**Comment by yanue** [comment]
#161
