### ISSUE TITLE
missing vmess.user[0].id 这个是什么问题

### ISSUE THREAD

**Issue by idelin** [yanue/V2rayU#15]
![image](https://user-images.githubusercontent.com/23070481/49860441-c4e69380-fe34-11e8-8f89-9fbfe1dcfaed.png)

**Comment by idelin** [comment]
上面那个好像消失了，变成这个了
![image-20181212175435621](https://ws3.sinaimg.cn/large/006tNbRwly1fy4425bf1xj30uu0u0acv.jpg)

**Comment by yanue** [comment]
这个是导入的信息缺失部分参数,请确认是否正确
