### ISSUE TITLE
connection Shadowsocks unknown cipher method: rc4-md5

### ISSUE THREAD

**Issue by xgs0921** [yanue/V2rayU#150]
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to read config file: config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: rc4-md5

**Comment by yanue** [comment]
v2ray本身不支持

**Comment by wajika** [comment]
现在新版已经解决了吗？
