### ISSUE TITLE
用户pac无法更新

### ISSUE THREAD

**Issue by AriaLyy** [yanue/V2rayU#151]
已经在设置从修改了pac，但是查看pac文件时还原来的

![image](https://user-images.githubusercontent.com/10437293/62338037-90316480-b509-11e9-94c4-d47fb4f1f738.png)

**Comment by lxg208** [comment]
pac.js 好像更新了，但是不起作用

**Comment by yuzhidu** [comment]
局域网代理这个功能缺失啊！

**Comment by yanue** [comment]
#195
