### ISSUE TITLE
如何开启局域网共享呢？

### ISSUE THREAD

**Issue by fy8207345** [yanue/V2rayU#152]
目前有没有这个功能？

**Comment by xiebruce** [comment]
目前界面没做，自己在import里把127.0.0.1改成`0.0.0.0`即可。

**Comment by guoyongxin** [comment]
`  
"inbounds": [
    {
      "listen": "0.0.0.0",
      "protocol": "socks",
      "settings": {
        "ip": "",
        "userLevel": 0,
        "timeout": 360,
        "udp": false,
        "auth": "noauth"
      },
      "port": "1111"
    },
    {
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1113"
    }
  ],
`
好像没用，访问局域网ip还是 192.168.3.4 refused to connect.

**Comment by yanue** [comment]
下载1.5
