### ISSUE TITLE
在浏览器可以用 但是在终端不行

### ISSUE THREAD

**Issue by wuyuxx** [yanue/V2rayU#1528]
这个是需要怎么设置吗？？？

**Comment by shrektan** [comment]
默认是不会代理终端的。你点一下图标，上面有个拷贝命令到终端，里面有四个环境变量的设置。要么你每次把这个命令在终端执行下了再跑。要么你把环境变量设置到系统中。

**Comment by wuyuxx** [comment]
> 默认是不会代理终端的。你点一下图标，上面有个拷贝命令到终端，里面有四个环境变量的设置。要么你每次把这个命令在终端执行下了再跑。要么你把环境变量设置到系统中。

昨天试了 现在可以了 谢谢哈
