### ISSUE TITLE
导入 ssr的问题

### ISSUE THREAD

**Issue by M-make** [yanue/V2rayU#153]
我导入了ssr的连接，主机信息都可以正常识别，但是访问网页，代理没有作用。
![image](https://user-images.githubusercontent.com/35563513/62448290-064bfa80-b79a-11e9-996d-2536eaf18a82.png)
然后我使用，小飞机使用同样的节点，小飞机可以访问，v2rayu不可以

**Comment by xiebruce** [comment]
ssr不用想了，v2ray压根不支持ssr，也不会，也不可能支持ssr，因为ssr是抄ss的代码的，大家都不喜欢那个作者，所以ssr作者被人肉，并在2017年放弃了更新ssr服务器端代码，v2ray-core只支持ss，即shadowsocks-libev，而这个v2rayU本质上也是用v2ray-core运行的，界面只是方便填写配置。
