### ISSUE TITLE
osx休眠后要断开wifi重新连接才能使用

### ISSUE THREAD

**Issue by tianhuxu** [yanue/V2rayU#154]
我用的是v1.4.0，每次休眠后唤醒似乎需要断开wifi再重新连接才有可用。看过了#47 issue，禁用+重新启用无法解决。可能是后续版本新引入的一个bug吗？
log如下：
2019/08/06 21:45:11 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/08/06 21:45:11 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/08/06 21:45:11 [Info] [3432897585] v2ray.com/core/app/dispatcher: default route for tcp:1.0.0.0:443
2019/08/06 21:45:11 [Info] [3432897585] v2ray.com/core/transport/internet/websocket: creating connection to tcp:xxx.com:443

2019/08/06 21:45:13 [Info] [1584762176] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/08/06 21:45:13 [Info] [1584762176] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/08/06 21:45:13 [Info] [1670885236] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/08/06 21:45:13 [Info] [1670885236] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by yanue** [comment]
#420
