### ISSUE TITLE
请问如何完全卸载？

### ISSUE THREAD

**Issue by TheLostXianXian** [yanue/V2rayU#157]
PAC模式不能访问谷歌， 但是全局模式就可以。所以我想删除后从新安装。
但我直接在应用中删除后， 重新安装还是会直接出现我的配置信息。
请问如何完全删除？

**Comment by yanue** [comment]
请看readme

**Comment by bytejedi** [comment]
readme not mention how to uninstall completely

**Comment by bytejedi** [comment]
Readme doesn't mention how to completely uninstall
