### ISSUE TITLE
不會設定，能教下嗎 step by step

### ISSUE THREAD

**Issue by franklinchang7** [yanue/V2rayU#16]
Hi
本人下載您的軟件後不會設定能教下嗎？
本人找到免費的SERVER但用QRCODE安裝後重啟還是無法代理上網？
能請你一步一步教下嗎？
感謝

另外
寫信給你請回信好嗎
感謝你百忙中抽空寫教程

**Comment by yanue** [comment]
抱歉,最近在换工作,一直忙
现已支持pac,全局,手动模式,一般情况下,导入qrcode -> Turn v2ray-core On -> 选择pac模式或global模式即可,  如果还是不能上网的话 ,可以通过show logs查看v2ray服务启动情况
