### ISSUE TITLE
通过订阅配置 vmess 时，无法正确设置kcp的header

### ISSUE THREAD

**Issue by Roachard** [yanue/V2rayU#161]
V2rayU: **v1.4.0**
MacOS: **10.14**
目前的情况：
您写的这个工具真的很好用，非常感谢。
我在使用中遇到了一点小问题：同样一段 v2 版本 vmess kcp 配置，通过 **服务器设置-导入模式** 来导入是可以正确设置kcp header的，而通过 **订阅设置-更新** 来更新的话，可以选择到kcp但header始终是none。
期待的结果：
订阅更新能够正确地设置kcp header。

**Comment by chenmin1992** [comment]
同识别不了 header type, quic的header type也不行

**Comment by chenmin1992** [comment]
@yanue 可以来看一下吗? 订阅识别不了kcp header type, quic header type和加密方式和密码

**Comment by Justsoos** [comment]
v1.5.1 依然没修复tcp 的 http header type
```json
{
"add": "1.1.1.1",
 "aid": "233",
 "host": "",
 "id": "31310fef-997a-416a-9a46-3ea21f879f57",
 "net": "tcp",
 "path": "",
 "port": "2922",
 "ps": "Ceshi_http",
 "tls": "",
 "type": "http",
 "v": "2"
}
```
导入后：
```json
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
```

https://github.com/yanue/V2rayU/issues/248

**Comment by yanue** [comment]
已修复,请下载2.0.0
