### ISSUE TITLE
Global Mode doesn't work as expected

### ISSUE THREAD

**Issue by lewisxy** [yanue/V2rayU#162]
Only safari works as expected after turning on the v2ray-core in global mode. Chrome does not work as all (throw `ERR_PROXY_CONNECTION_FAILED` for any webpage), and command line programs such as `youtube-dl` are not working unless specify the sock5-proxy on 1080 (with `--proxy socks5://127.0.0.1:1080/`), which should not be necessary in global mode.

**Comment by rockingdice** [comment]
+1 on this one.

**Comment by yanue** [comment]
you can try:  v2rayu+Proxifier

**Comment by rockingdice** [comment]
Thanks. Will have a try.

**Comment by hasen6** [comment]
Why doesn't global mode work - why not? I found in global mode that other applications like Twitch live stream or an Android emulator the traffic is not going through v2ray...

Proxifier is not free so not much of a solution.

**Comment by lewisxy** [comment]
I know a working implementation at least for TCP connections. [This project](https://github.com/icnetsvs/ShadowsocksX-NG-R) does have a Global Mode that works as expected, so maybe we can borrow some code. Unfortunately I am not a Mac developer and unable to provide pull request for this, hopefully this is a helpful information for anyone willing to improve it.

**Comment by hasen6** [comment]
@lewisxy But that's Shadowsocks, not V2Ray. I think it's a fundamental problem with V2ray itself. Global mode doesn't work on V2rayU or V2rayX on Mac and doesn't work on V2rayN or V2rayW either...
