### ISSUE TITLE
mac下PAC模式如何能代理google drive?

### ISSUE THREAD

**Issue by langziyang** [yanue/V2rayU#163]
使用PAC模式的时候，gogle drive不能连接，请问大家如何解决

**Comment by alex-czp** [comment]
![image](https://user-images.githubusercontent.com/14200813/64234627-5220c980-cf29-11e9-8581-f9aba5579c40.png)
你要设置这里才能用Google drive, 这个跟梯子无关

**Comment by canondin** [comment]
> ![image](https://user-images.githubusercontent.com/14200813/64234755-87c5b280-cf29-11e9-8704-6fda813f3616.png)
> 
> 你要设置这里才能用Google drive, 这个跟梯子无关

不知道你有没有试过，我这样设置还是访问不了，卡在通过浏览器登录，点击没反应
![image](https://user-images.githubusercontent.com/14855855/128347364-3973f860-8424-4311-aa63-e9bda5fd4dc7.png)

![image](https://user-images.githubusercontent.com/14855855/128347447-b65e1ef9-b3f4-4c65-8e02-62255bf5034e.png)
