### ISSUE TITLE
只能支持到V2ray，不支持SSR协议

### ISSUE THREAD

**Issue by cytown** [yanue/V2rayU#164]
订阅正常，并且能识别出ssr服务器，但是选择后无论任何模式，都无法正常访问网络。

**Comment by cytown** [comment]
安装了一个shadowsocksr-ng以后解决了ssr访问的问题，但是用v2rayu是不能访问的。要用ssr，必须关闭v2rayu，然后打开ssr-ng才行。

**Comment by anuxs** [comment]
> 安装了一个shadowsocksr-ng以后解决了ssr访问的问题，但是用v2rayu是不能访问的。要用ssr，必须关闭v2rayu，然后打开ssr-ng才行。

你说法是错误的。你同时开两个不同的代理软件，他们都要修改系统网络连接的pac代理设置，这就冲突了啊兄弟，后开的会在此修改proxy设置的，导致你另外一个代理上不了网。

解决办法，同一时间只开一个代理。SSR是可以用V2的，我证实是没有问题的。

**Comment by cytown** [comment]
> > 安装了一个shadowsocksr-ng以后解决了ssr访问的问题，但是用v2rayu是不能访问的。要用ssr，必须关闭v2rayu，然后打开ssr-ng才行。
> 
> 你说法是错误的。你同时开两个不同的代理软件，他们都要修改系统网络连接的pac代理设置，这就冲突了啊兄弟，后开的会在此修改proxy设置的，导致你另外一个代理上不了网。
> 
> 解决办法，同一时间只开一个代理。SSR是可以用V2的，我证实是没有问题的。

错，我并没有同时打开两个软件，我说了要关闭一个打开另外一个才行。而且，我一开始就光安装了v2rayu，无法使用ssr，只能用v2ray。

**Comment by yanue** [comment]
v2ray本身不支持ssr，ssr模式只是转换成了ss

**Comment by cytown** [comment]
> v2ray本身不支持ssr，ssr模式只是转换成了ss

不支持，但是能识别和订阅，就是选择以后无效，这是什么逻辑？？？
