### ISSUE TITLE
mac全局模式下配置无法成功

### ISSUE THREAD

**Issue by dongbusi** [yanue/V2rayU#165]
![image](https://user-images.githubusercontent.com/39559813/64484756-77734780-d249-11e9-8bcc-d27e6053556a.png)
一直提示这个不知道怎么解决，求助啊

**Comment by yanue** [comment]
这个是正常的提醒,不能使用吗

**Comment by dongbusi** [comment]
会出现间歇性不能用，然后等上20分钟左右就可以重新使用了



------------------ 原始邮件 ------------------
发件人: "yanue"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 上午10:59
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com>; 
抄送: " "<345656572@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yanue/V2rayU] mac全局模式下配置无法成功 (#165)




这个是正常的提醒,不能使用吗
