### ISSUE TITLE
请求是不是还没有兼容10.14.5

### ISSUE THREAD

**Issue by henury** [yanue/V2rayU#168]
请求是不是还没有兼容10.14.5，下载dmg安装的时候，提示要鉴定，但是没有鉴定的按钮

**Comment by ilifelog** [comment]
兼容。我现在是最新版Mac系统。没问题。

**Comment by parcool** [comment]
10.15 Beta 8 ojbk！

**Comment by Zhongjoe** [comment]
我也提示需要 鉴定.

**Comment by yanue** [comment]
请截图看下

**Comment by ChaosLcc** [comment]
![Snip20190923_14](https://user-images.githubusercontent.com/16434139/65410515-2785aa80-de1d-11e9-9674-c4f1df05bd4a.png)
系统 10.14.5

**Comment by boluow** [comment]
直接复制

**Comment by Jeffhop** [comment]
提示需要鉴定，怎么样做呢？

**Comment by parcool** [comment]
@Jeffhop 打开后不要拖到那个文件夹里，先拖到桌面，再从桌面拖到访达里的应用程序目录里。

**Comment by yanue** [comment]
请下载1.5
