### ISSUE TITLE
每天自动更新一次订阅。

### ISSUE THREAD

**Issue by xpol** [yanue/V2rayU#169]
每天更新一次订阅可以让服务器列表中的服务器保存最新。

但是有两个细节要处理：
1. 每天什么时候更新？
    - 首次启动时
    - 首次启动后
    - 每天某个固定时间
    - 用户自定义
2. 更新服务器列表后，如果原来选中的服务器不见了，怎么选择服务器？
    - 不选
    - 选择第一个
    - 选择 ping 最低的
    - 正则表达式过滤

**Comment by yanue** [comment]
暂时增加启动和唤醒时主动更新订阅信息,请下载2.0.0
