### ISSUE TITLE
关于V2ray Rules规则的问题

### ISSUE THREAD

**Issue by lucky0l** [yanue/V2rayU#17]
求问一下，我在用V2rayX的时候使用V2ray rules就可以默认我的V2服务的规则，把代理加到了Http和socks5,但是到咱的V2rayU选择V2ray Rules就不改变作何代理，要自己去设置？这是个Bug么？还是没有加这个功能？只有选全局才会自动设置代理。而且哪怕自己手动设置了也是全局，也不是我的V2的规则。

**Comment by yanue** [comment]
现在已经手动模式,pac模式,全局模式(进入v2ray代理会继续以V2ray rules规则进行), 目前V2ray Rules只能手动改动,如有bug,请反馈
