### ISSUE TITLE
开机自启，无法关闭。。。

### ISSUE THREAD

**Issue by RonaldZhao** [yanue/V2rayU#175]
macOS version : 10.14.6
v2rayU version : 1.4.1
不知道大家有没有这个问题。。。

**Comment by yanue** [comment]
![image](https://user-images.githubusercontent.com/1435250/65375547-728ea900-dcc9-11e9-848b-6d18105da67c.png)
可以设置关闭的，应该没这个问题

**Comment by RonaldZhao** [comment]
设置了，无效，开机依然自启。

**Comment by yelantingfeng** [comment]
是啊，怎么回事
