### ISSUE TITLE
好像不能使用自定义PAC……

### ISSUE THREAD

**Issue by EnjoyColin** [yanue/V2rayU#176]
目前gfw黑名单已经很难确保稳定性了，白名单是更好的方式，但是本软件似乎不支持用户自定义PAC文件，希望增加此功能。

**Comment by yanue** [comment]
![image](https://user-images.githubusercontent.com/1435250/65375401-c5676100-dcc7-11e9-817f-96f7f22776b3.png)
可以自己填写
