### ISSUE TITLE
启动时日志报错 V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom A unified platform for anti-censorship. main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory

### ISSUE THREAD

**Issue by CrazyGriferman** [yanue/V2rayU#177]
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory

请问有人知道是什么问题吗？

**Comment by yanue** [comment]
是放在 /Application 里面了吗

**Comment by CrazyGriferman** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  放在application 后提示需要输入用户名和密码并点击鉴定 但没有鉴定按钮 然后我就先把v2rayu 拖到桌面再拖到application 中                                                                                                                                                                        发送自我的 BlackBerry - 安全智能手机                                                                                                                                                                           发件人： notifications@github.com发送时间： 2019年9月21日 下午11:52收件人： V2rayU@noreply.github.com回复： reply@reply.github.com抄送： 251031557@qq.com; author@noreply.github.com主题： Re: [yanue/V2rayU] 启动时日志报错 V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom A unified platform for anti-censorship. main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory (#177)  是放在 /Application 里面了吗

**Comment by yanue** [comment]
按正常流程安装试下吧 后面考虑优化这块

**Comment by cqamber** [comment]
我也遇到了，什么原因

**Comment by cqamber** [comment]
怎么解决呢

**Comment by esverde** [comment]
> 怎么解决呢

sudo chmod 666 /etc/v2ray/*
