### ISSUE TITLE
有iOS版本的吗？

### ISSUE THREAD

**Issue by ywachao** [yanue/V2rayU#178]
请问这个有iOS版本的吗？

**Comment by yanue** [comment]
没有 有很多ios客户端（美区） https://v2ray.com/awesome/tools.html

**Comment by ywachao** [comment]
美区需要账号啊，现在几乎注册不了美区的账号，国内iOS用户还有其他办法用vmess协议吗？

**Comment by alexcdever** [comment]
去淘宝买美区账号吧

**Comment by lanmeiceo** [comment]
> 美区需要账号啊，现在几乎注册不了美区的账号，国内iOS用户还有其他办法用vmess协议吗？

关注公众号科技产品网，有公用的美区账号
