### ISSUE TITLE
偏好设置页面无法响应

### ISSUE THREAD

**Issue by cogitoxin** [yanue/V2rayU#179]
偏好设置页面只显示General无法显示其他
系统：10.12.6
版本：1.4.1
<img width="572" alt="Screen Shot 2019-09-21 at 14 55 34" src="https://user-images.githubusercontent.com/16520525/65369476-09cf0e80-dc80-11e9-9ace-d5c9ce94a904.png">

**Comment by yanue** [comment]
10.12.6 太老了哈 请升级到10.14吧
