### ISSUE TITLE
现在扫码加入服务器的话，服务器设置里的服务器列表不会更新服务器信息

### ISSUE THREAD

**Issue by liyuhaolol** [yanue/V2rayU#185]
这个问题仅限于扫码，扫码后，直接在服务器列表里，有对应的服务器信息，但是打开服务器设置后，服务器列表就不显示对应的服务器信息，必须删除或者添加一条信息后，服务器信息才会出现，感觉这是BUG

**Comment by hades0932** [comment]
+1
大退软件，再重新打开。

**Comment by yanue** [comment]
已修复,请下载2.0.0
