### ISSUE TITLE
[BUG?] macos10.14.6 Safari浏览器不适用

### ISSUE THREAD

**Issue by Eurus-Holmes** [yanue/V2rayU#186]

**Comment by moonclock** [comment]
<img width="1317" alt="图片" src="https://user-images.githubusercontent.com/12515349/65827864-4c6b9900-e2c7-11e9-8e8a-83390e4328f1.png">
我这里正常, 你看看配置是不是有问题.

**Comment by Eurus-Holmes** [comment]
现在可以了，之前有问题。
