### ISSUE TITLE
PAC模式无法上网

### ISSUE THREAD

**Issue by liangsk53121** [yanue/V2rayU#189]
只能开启全局模式才可以，请问大家有遇到这个问题吗？

**Comment by jangrui** [comment]
> 只能开启全局模式才可以，请问大家有遇到这个问题吗？

貌似昨天晚上出现的问题

**Comment by pannyum** [comment]
现在我用全局也不可以了，提示是网站已永久性地移动到了新网址

**Comment by jangrui** [comment]
> 现在我用全局也不可以了，提示是网站已永久性地移动到了新网址

v2rayx 可以用

**Comment by yanue** [comment]
#195
