### ISSUE TITLE
需要鉴权

### ISSUE THREAD

**Issue by Gleans** [yanue/V2rayU#191]
Mojave 10.14.6 (18G95)

**Comment by Gleans** [comment]
![image](https://user-images.githubusercontent.com/23448967/65668366-2a2e0d00-e074-11e9-9eaf-c20a0ff99390.png)
拖动安装需要鉴权

**Comment by iblogc** [comment]
装好后很多操作都要鉴权，切换个tab都要鉴权😢

**Comment by Gleans** [comment]
> 装好后很多操作都要鉴权，切换个tab都要鉴权😢

解决了
![image](https://user-images.githubusercontent.com/23448967/65669938-fd2f2980-e076-11e9-9e12-24502c0d730d.png)
用命令行把软件拷贝到应用程序之后-》显示简介-》把权限都设置成读与写

**Comment by 1456118242** [comment]
![image](https://user-images.githubusercontent.com/18241022/66093953-c603cf80-e5c4-11e9-8012-02eafd10d38e.png)

**Comment by 1456118242** [comment]
@Gleans 兄弟 有具体步骤吗
