### ISSUE TITLE
代理其他设备

### ISSUE THREAD

**Issue by aeoogo** [yanue/V2rayU#192]
没有设置监听IP的地方，默认是127.0.0.1吧，不能为局域网内其他设备提供代理。

**Comment by haibbo** [comment]
建议增加 局域网HTTP代理的功能

**Comment by aeoogo** [comment]
额，提了这个问题后仔细研究了一番，只要在配置文件的地方将127.0.0.1改为0.0.0.0，就可以监听局域网中其他设备的请求了！

**Comment by YoxY** [comment]
配置修改成  0.0.0.0 也无法开启局域网http 代理，请问如何解决？ 修改后的配置如下
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "protocol": "socks",
      "settings": {
        "ip": "",
        "userLevel": 0,
        "timeout": 360,
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],

**Comment by yuzhidu** [comment]
> 额，提了这个问题后仔细研究了一番，只要在配置文件的地方将127.0.0.1改为0.0.0.0，就可以监听局域网中其他设备的请求了！

怎么设置啊，在哪儿设置

**Comment by YoxY** [comment]
这个设置就是打开服务器列表 选中一个服务器 右边，将会出现改服务器的配置 ，入下图：
[image: image.png]
把该配置里面的监听 端口，改成 0.0.0.0 后保存，重启服务即可。
另外可以用：

lsof -nPi -sTCP:LISTEN | grep 1087

查看1087 监听是否已经开启

saury <notifications@github.com> 于2019年11月10日周日 下午10:04写道：

**Comment by yanue** [comment]
下载1.5
