### ISSUE TITLE
日志没有任何输出

### ISSUE THREAD

**Issue by yangkang55** [yanue/V2rayU#193]
打开之后，日志没有任何输出，也无法翻墙

**Comment by laommmm** [comment]
我也是相同的问题，原来可以的。后来就不行了，重装也无用。
@yangkang55 你解决了吗？求助

**Comment by yangkang55** [comment]
我换成 va2rayx了@laommmm

**Comment by laommmm** [comment]
好吧，我也用X，感觉这个好多坑，我用X能上了。
@yangkang55

**Comment by DearTanker** [comment]
遇到同样问题。

**Comment by ardayan** [comment]
同样。切换一下其他服务器就好了。
