### ISSUE TITLE
PAC和全局问题

### ISSUE THREAD

**Issue by nicksun98** [yanue/V2rayU#195]
今天PAC无法连接Google等外网，可以访问中国网站。
全局极慢，响应经常超时。
已排除服务器问题。
Version 1.4.1
OS版本10.14.6

**Comment by Gaoleiyu** [comment]
我也遇到了这个问题

**Comment by lydcompany** [comment]
嗯，我也发现了这个问题。通过类似几种方法可以解决：1. 先打开ShadowsocksX并开启PAC模式，然后关闭ShadowsocksX，启动v2rayU，此时pac文件可以使用，但如果重启或者从睡眠中唤醒之后PAC会失效的，必须用全局才可以。我注意到ShadowsocksX在系统自动代理中采用的扩展名为.pac，v2rayU采用的是.js，不知道是不是这个问题。

**Comment by boisde** [comment]
> 嗯，我也发现了这个问题。通过类似几种方法可以解决：1. 先打开ShadowsocksX并开启PAC模式，然后关闭ShadowsocksX，启动v2rayU，此时pac文件可以使用，但如果重启或者从睡眠中唤醒之后PAC会失效的，必须用全局才可以。我注意到ShadowsocksX在系统自动代理中采用的扩展名为.pac，v2rayU采用的是.js，不知道是不是这个问题。

我还是不行. 我还把network->advanced->Proxies里面的"Automatic Proxy Configuration"改成了"http://127.0.0.1:1085/proxy.pac" 并且在对应的目录放了对应的文件.

log没有报错, 可是就还是不可用.

**Comment by bbzz7** [comment]
我也遇到了这个问题，v2rayU版本：1.4.1，macOS版本也是：10.14.6
全局模式一切正常，pac模式无法生效访问

**Comment by heiyeliuying** [comment]
同样的问题,10.13.6 
全局模式下没有任何问题. 
PAC模式下,无法连接外网

**Comment by nickeljew** [comment]
前几天升级新版本后 pac 可以用，但今天发现又不行。

**Comment by kanna-makino** [comment]
版本v1.5.1，PAC模式无效。
昨天安装的时候PAC模式还是正常的，但是今天下午开始PAC模式无效，只有在全局模式下才能访问google.com。

**Comment by YoleYu** [comment]
表现同上。
之前有装过ssr。
不知道是什么原因，只有全局模式有效

**Comment by 0x0006e** [comment]
`+ 1`

**Comment by Saafo** [comment]
> 版本v1.5.1，MacOS catalina，PAC模式无效。
> 昨天安装的时候PAC模式还是正常的，但是今天下午开始PAC模式无效，只有在全局模式下才能访问google.com。

Same issue.

**Comment by YoleYu** [comment]
筒子们，是否有替代方案或者软件可以用pac代理呢？

**Comment by 0x0006e** [comment]
> 筒子们，是否有替代方案或者软件可以用pac代理呢？

我卸载了，

**Comment by nickeljew** [comment]
我有个奇葩的解决方案，虽然搞不清楚原因，至少我这里可行。
常见就是重启后 pac 模式无效，但是 dropbox 可以（dropbox 不经过系统代理）。出现这种情况时，我就先关闭 V2RayU 的服务（不需要退出），然后启动原来的 ShadowsocksX-NG-R8（PAC模式），然后再关闭 ShadowsocksX-NG-R8 服务以及退出，打开 V2RayU 服务（PAC 模式），就可以用了。

暂时来说，我觉得 V2RayU 比较其他几个同类 app略好用一些，仅仅是这个 issue。

**Comment by 0x0006e** [comment]
> 我有个奇葩的解决方案，虽然搞不清楚原因，至少我这里可行。
> 常见就是重启后 pac 模式无效，但是 dropbox 可以（dropbox 不经过系统代理）。出现这种情况时，我就先关闭 V2RayU 的服务（不需要退出），然后启动原来的 ShadowsocksX-NG-R8（PAC模式），然后再关闭 ShadowsocksX-NG-R8 服务以及退出，打开 V2RayU 服务（PAC 模式），就可以用了。
> 
> 暂时来说，我觉得 V2RayU 比较其他几个同类 app略好用一些，仅仅是这个 issue。
> 
> --------- 罪恶淫荡的分割线 -------------
> 才发现前面有人提过这个方案，我也是无意之间发现，确实可行。

每次开机休眠都要这样操作一遍

**Comment by nickeljew** [comment]
> > 我有个奇葩的解决方案，虽然搞不清楚原因，至少我这里可行。
> > 常见就是重启后 pac 模式无效，但是 dropbox 可以（dropbox 不经过系统代理）。出现这种情况时，我就先关闭 V2RayU 的服务（不需要退出），然后启动原来的 ShadowsocksX-NG-R8（PAC模式），然后再关闭 ShadowsocksX-NG-R8 服务以及退出，打开 V2RayU 服务（PAC 模式），就可以用了。
> > 暂时来说，我觉得 V2RayU 比较其他几个同类 app略好用一些，仅仅是这个 issue。
> > --------- 罪恶淫荡的分割线 -------------
> > 才发现前面有人提过这个方案，我也是无意之间发现，确实可行。
> 
> 每次开机休眠都要这样操作一遍

休眠恢复不用，可能偶尔会，但通常不用。重新开机貌似会，不过我也很少重启或重新开机。

**Comment by ZR-Huang** [comment]
想请问下，如何更换pac文件。我看到工具设置里pac文件是以txt结尾的：`https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt`

但是系统网络设置里面又是：`http://127.0.0.1:11085/pac/proxy.js`。

我直接更换pac文件的URL好像并没有用，甚至会出现闪退。
所以想请问下有人成功更换了pac文件吗？

**Comment by 0x0006e** [comment]
我今天仔细看了一下 log，居然写的是端口占用，所以在设置🀄️改了端口 PAC 就能用了，重启也没问题。

![image](https://user-images.githubusercontent.com/18499153/75658106-96a3dc80-5ca2-11ea-846b-cf30a2491d05.png)
![image](https://user-images.githubusercontent.com/18499153/75658115-9d325400-5ca2-11ea-9d4c-0ade0f35dcf2.png)
![image](https://user-images.githubusercontent.com/18499153/75658121-a0c5db00-5ca2-11ea-8976-e6a3d3a1856e.png)

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0

**Comment by fingertap** [comment]
仍然有这个问题，自定义的PAC在写入了以后还是不能读取。想问下在哪里看log呀？

**Comment by jiangcanming** [comment]
2.1.0 版本仍然有这个问题

**Comment by LIUZHENGYU2019** [comment]
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ***. ***. ***. ***:2222: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
如果遇到这个报错可以先试着改一下端口号到10000以上，这对我很试用。

**Comment by PygmalionChen** [comment]
> 版本v1.5.1，MacOS catalina，PAC模式无效。
> 昨天安装的时候PAC模式还是正常的，但是今天下午开始PAC模式无效，只有在全局模式下才能访问google.com。

系统与软件版本同楼上。我也曾装过shadowsocks，但是因为怀疑端口占用我直接卸了。试了相关问题的修改端口一直没解决。然后我重启了电脑，授权了v2ray客户端，虽然我记得我曾经授权过。
![image](https://user-images.githubusercontent.com/17659210/87270887-14ef7580-c504-11ea-93cd-76cefac5455c.png)
为了看日志，我把日志等级调成了debug。然后我的pac突然就成功了。自己搞了好久莫名其妙解决了，希望对你们有帮助。
![image](https://user-images.githubusercontent.com/17659210/87270930-40726000-c504-11ea-8833-1f8263364d54.png)

**Comment by LieKeWu** [comment]
> 我今天仔细看了一下 log，居然写的是端口占用，所以在设置🀄️改了端口 PAC 就能用了，重启也没问题。
> 
> ![image](https://user-images.githubusercontent.com/18499153/75658106-96a3dc80-5ca2-11ea-846b-cf30a2491d05.png)
> ![image](https://user-images.githubusercontent.com/18499153/75658115-9d325400-5ca2-11ea-9d4c-0ade0f35dcf2.png)
> ![image](https://user-images.githubusercontent.com/18499153/75658121-a0c5db00-5ca2-11ea-8976-e6a3d3a1856e.png)

这个方法解决啦！

**Comment by konglingwen94** [comment]
同一个pac文件，MacBook设置有效，但是iphone 设置到WiFi下面的自动代理却不能用，有大神知道是什么情况吗

**Comment by nickeljew** [comment]
不能直接用pac模式，拜托，这是ss/v2ray模式，不是pac模式的服务，这个pac指向的是mac本机启动的一个代理服务器

**Comment by FengyunSky** [comment]
重新配置下监听端口可行，已测试【MacBook Pro2019】

**Comment by zhangxiaoyu2046** [comment]
我提供一个解决方法：检查你的Pac 设置里的GFW list是否正确，我改成了：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
即可，PAC也能正常work了。
最新地址应该在此处获取：https://github.com/gfwlist/gfwlist

**Comment by fingertap** [comment]
我弃用了v2rayU直接用v2ray-cli,用内置路由进行控制。

```
"rules": [
            {
              "type": "field",
              "ip": [
                "geoip:private"
              ],
              "outboundTag": "direct"
            },
            {
              "type": "field",
              "domain": [
                "geosite:cn"
              ],
              "outboundTag": "direct"
            },
            {
              "type": "field",
              "ip": [
                "geoip:cn"
              ],
              "outboundTag": "direct"
            },
           ...
]}
```
