### ISSUE TITLE
新增配置后，备注名都是 new server，无法修改

### ISSUE THREAD

**Issue by kgbook** [yanue/V2rayU#197]
### OS
macOS Mojave 10.14.6

### version
v1.4.1

### 现象
- 旧版本 V2RayU 配置，服务器别名 xxx 则仍显示 xxx；新版本新增配置，默认别名 new server，且无法修改，无相关入口。

### operation
Import From Pasteboard---> import success  ---> configure 查看别名 ---> 尝试修改，未找到入口 ---> 尝试修改 tls server name，仍然为 new server。

**Comment by zeusro** [comment]
+1

**Comment by hades0932** [comment]
+1
但有办法处理，整体退出软件，重新打开，新增的配置就出现了，页面改相关的信息。

**Comment by yanue** [comment]
不能双击修改?

**Comment by kgbook** [comment]
> 不能双击修改?

目前升级到 macOS Catalina 10.15 (19A583) ；可以双击修改了。
不确定是不是我操作问题，还是其它因素影响。

**Comment by zeusro** [comment]
> 不能双击修改?

才发现可以双击修改,,,
