### ISSUE TITLE
pac中的gfw list地址如何替换

### ISSUE THREAD

**Issue by shang309073819** [yanue/V2rayU#198]
![image](https://user-images.githubusercontent.com/6511021/65851280-f9f0b200-e384-11e9-8313-75d4882e6107.png)

**Comment by Holokk** [comment]
我也遇到了这个问题，用pac模式经常无法上外网，必须要全局模式才出得来

**Comment by edsion1107** [comment]
有相同的需求。
github的gfwlist经常被屏蔽，所以想改成gitlib的

**Comment by yanue** [comment]
1.5.1已修复
