### ISSUE TITLE
在系统常驻栏的图标里应该像 ShadowsocksX-NG 一样，显示 PAC 模式和全局模式的不同

### ISSUE THREAD

**Issue by bbbear2002** [yanue/V2rayU#200]
在系统常驻栏的图标里应该像 ShadowsocksX-NG 一样，显示 PAC 模式和全局模式的不同。不然每次都要点开图标看看是哪种模式。
在 V2RayU 的图标右下方显示一个 P 或者 G 的字符，就好了

**Comment by yanue** [comment]
请下载1.5
