### ISSUE TITLE
macOS 10.14.3 提示鉴定

### ISSUE THREAD

**Issue by Args** [yanue/V2rayU#203]
不知道去哪鉴定 应该不是个例？换个很多电脑试过而且应该不是同一个os版本，建议作者看下这个问题 而且频繁的跳出要输入密码的权限 一秒10弹没法用

**Comment by xdmlove** [comment]
我也是提示鉴定 直接把程序拷贝到 程序文件夹下面  然后打开后 提示输入密码 之后没问题了!

**Comment by jiangyixiang** [comment]
拖到application后还是没用

**Comment by xiaobinHub** [comment]
同样有这个问题，直接拖到程序文件夹就可以了

**Comment by Lichmaker** [comment]
同样问题，我是直接拖到桌面直接使用

**Comment by Args** [comment]
尝试直接拖出来可以使用了，但是issue先留着了，供参考。谢谢楼上各位

**Comment by yanue** [comment]
请下载1.5
