### ISSUE TITLE
PAC模式无法使用~

### ISSUE THREAD

**Issue by bbzz7** [yanue/V2rayU#206]
v2rayU版本：1.4.1，macOS版本：10.14.6
全局模式一切正常，pac模式下无法连接代理访问

**Comment by littlebox692** [comment]
请问你解决了么？我这边点击浏览文件，弹出来的是127.0.0.1/xxxx的地址。。。在哪里配置。浏览文件都浏览不了

**Comment by littlebox692** [comment]
> v2rayU版本：1.4.1，macOS版本：10.14.6
> 全局模式一切正常，pac模式下无法连接代理访问

请问你解决了么？我这边点击浏览文件，弹出来的是127.0.0.1/xxxx的地址。。。在哪里配置。浏览文件都浏览不了

**Comment by niices** [comment]
我也有这个问题

**Comment by niices** [comment]
好像是chrome本身的问题  我刚试了safari没问题

**Comment by yanue** [comment]
#195
