### ISSUE TITLE
dmg无法安装

### ISSUE THREAD

**Issue by catchandrelease** [yanue/V2rayU#209]
![image](https://user-images.githubusercontent.com/6227330/66382020-fb595480-e9ec-11e9-92a5-c71dfdc0e612.png)

并没有Authenticate按钮，只有ok。
点击ok之后直接中断安装

**Comment by sulizhan** [comment]
+1

**Comment by jack2020** [comment]
+1

**Comment by moshuchao** [comment]
+1

**Comment by sm0king** [comment]
我也遇到这个问题了，直接在fillder里 打开 应用那个文件夹，然后把左边那个图标拖到文件夹里就可以了。

**Comment by hades0932** [comment]
+1
一种zip解压后，复制到应用程序里。

**Comment by liuqian0716** [comment]
> 我也遇到这个问题了，直接在fillder里 打开 应用那个文件夹，然后把左边那个图标拖到文件夹里就可以了。

请问哪个应用的文件夹呢

**Comment by rangershs** [comment]
@liuqian0716 
你不要横着拖，在Finder里面选中文件夹Applications，然后把图标直接拖入到文件夹
@sm0king 方法亲测有效，感谢！

**Comment by Eviews** [comment]
我直接拖入applications的文件夹之后，会报错open config.json: no such file or directory

**Comment by cqamber** [comment]
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory
一直在报错。。。怎么解决

**Comment by yanue** [comment]
请下载1.5
