### ISSUE TITLE
1.1.1版本 手动模式下 切换服务器时会接管系统代理

### ISSUE THREAD

**Issue by burning** [yanue/V2rayU#21]
这应该不是手动模式的意思吧

**Comment by burning** [comment]
是的 就是把别的软件的代理也清除掉了
比如我把他作为Surg*前置代理   切换服务器的时候会把 Surg*设置的系统代理清除掉。

**Comment by yanue** [comment]
额  需要备份之前代理 切换到manual时,需要切换回来,  
最近比较忙,  后续修复

**Comment by burning** [comment]
貌似屏保结束之后，也会重置系统代理。

**Comment by burning** [comment]
最近太忙了吗，什么时候更新一下

**Comment by yanue** [comment]
最近一个月加班严重  年前更新吧

**Comment by yanue** [comment]
已经处理
