### ISSUE TITLE
增加pac网址无效，pac模式有时候整体无效

### ISSUE THREAD

**Issue by Holokk** [yanue/V2rayU#210]
pac模式有时候整体无效，必须要全剧模式才可以使用，再有就是自己增加pac的网址也没有用

**Comment by fzlittlerabbit** [comment]
![image](https://user-images.githubusercontent.com/56330574/66447692-ac113380-ea81-11e9-9fbb-75e8ed4b5685.png)
我也遇到了同样的问题，然后尝试把list地址复制到手动规则里就好了

**Comment by jinglf000** [comment]
> ![image](https://user-images.githubusercontent.com/56330574/66447692-ac113380-ea81-11e9-9fbb-75e8ed4b5685.png)
> 我也遇到了同样的问题，然后尝试把list地址复制到手动规则里就好了

mac 版本是10.15 吗？

**Comment by fzlittlerabbit** [comment]
> > ![image](https://user-images.githubusercontent.com/56330574/66447692-ac113380-ea81-11e9-9fbb-75e8ed4b5685.png)
> > 我也遇到了同样的问题，然后尝试把list地址复制到手动规则里就好了
> 
> mac 版本是10.15 吗？

对的，15寸 mid-2014

**Comment by kjsolo** [comment]
同样问题，PAC无法使用，全局有效，系统版本10.15

**Comment by Shawshank01** [comment]
自己添加规则后要先开全局模式再点击“保存设置并从GFW List更新”，当系统通知中显示更新成功后规则即可生效。

**Comment by yanue** [comment]
#195
