### ISSUE TITLE
macOS10.15正式版，更新最新的V2rayU，连接不稳定，总是一会就连不上，关了重新启动后也连不上，iPhone上对应的梯子连接正常，下面是对应的日志

### ISSUE THREAD

**Issue by zhangdongxiao** [yanue/V2rayU#211]
Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/10/09 17:10:05 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/10/09 17:10:05 [Info] [1372408799] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/10/09 17:10:05 [Info] [1372408799] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:hk3-1.kkworld.xyz:8300
2019/10/09 17:10:05 tcp:127.0.0.1:59980 accepted tcp:www.google.com:443 
2019/10/09 17:10:05 [Info] [1372408799] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:hk3-1.kkworld.xyz:8300
2019/10/09 17:10:20 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/10/09 17:10:20 [Info] [2189935149] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients1.google.com:443
2019/10/09 17:10:20 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/10/09 17:10:20 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/10/09 17:10:20 [Info] [2189935149] v2ray.com/core/app/dispatcher: default route for tcp:clients1.google.com:443
2019/10/09 17:10:20 [Info] [2189935149] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:hk3-1.kkworld.xyz:8300
2019/10/09 17:10:20 tcp:127.0.0.1:59996 accepted tcp:clients1.google.com:443 
2019/10/09 17:10:20 [Info] [2189935149] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients1.google.com:443 via tcp:hk3-1.kkworld.xyz:8300
2019/10/09 17:10:21 [Info] [3306395318] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/10/09 17:10:21 [Info] [3306395318] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/10/09 17:10:21 [Info] [1372408799] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/10/09 17:10:21 [Info] [1372408799] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/10/09 17:10:27 [Info] [2591914304] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > read tcp 172.23.10.180:59958->103.125.232.112:8300: read: operation timed out
2019/10/09 17:10:27 [Info] [2591914304] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by AriaLyy** [comment]
+1 ，同样的问题，总是提示下面警告。
```
You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
```

**Comment by AriaLyy** [comment]
换成classx就正常了～～～

**Comment by zhangdongxiao** [comment]
> 换成clash就正常了～～～

clash老是说托管文件配置不正确 搞伤了

**Comment by TrustTheBoy** [comment]
iPhone用的啥？

**Comment by jinglf000** [comment]
全局模式可以，pac不行？各位知道原因吗？

**Comment by AriaLyy** [comment]
> > 换成clash就正常了～～～
> 
> clash老是说托管文件配置不正确 搞伤了
参考这个配置就行了，将不需要的全部屏蔽
https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml

**Comment by dongbusi** [comment]
10.14我也最近一直碰到这个问题

**Comment by zhangdongxiao** [comment]
> > > 换成clash就正常了～～～
> > 
> > 
> > clash老是说托管文件配置不正确 搞伤了
> > 参考这个配置就行了，将不需要的全部屏蔽
> > https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml

![image](https://user-images.githubusercontent.com/38239911/66532894-9c5a2380-eb43-11e9-9c8b-b2c17f3ec905.png)

按照配置里面配置clash的配置文件，客户端还一直报错。。。。。直接在文档的链接里面把配置文件内容考出来的

**Comment by ganhang** [comment]
同遇到

**Comment by RunawayFzzF** [comment]
+1 十分不稳定，ping主机延迟60 mac打不开

**Comment by wfkbyni** [comment]
请问下手机端有使用v2ray的demo吗？

**Comment by hkstar** [comment]
同样有这样的问题,间歇性

**Comment by Tcooop** [comment]
v2ray，clash在mac电脑上暂时没有这样的问题
可能是因为
1.v2ray服务端配置有问题
2.机房IP已经被封，请使用ping.pe测试端口是否可用
3.客户端参数/配置文件设置有误，如果不会配置的话，建议去官方拉最新的模版。如果你的购买机场的vpn的话，请联系客服
4.v2ray客户端的内核版本和服务器的v2ray版本相差较大，建议保持一致，不要有太大的差别
