### ISSUE TITLE
支持协议: vmess:// 和 ss:// 和 ssr:// 协议,支持socks5协议吗？

### ISSUE THREAD

**Issue by shenzt68** [yanue/V2rayU#213]
如题！
https://github.com/yanue/V2rayU/wiki/V2rayU使用说明里说明支持的，但是发现不支持ssr！

**Comment by knightdf** [comment]
同样的问题，发现不支持ssr, 导入ssr后启动会报错

**Comment by WalterZou** [comment]
同样的问题，SSR 订阅能够更新节点列表，但是选用任何可用节点，都不能翻出去

**Comment by WalterZou** [comment]
同样的问题，SSR 订阅能够更新节点列表，但是选用任何可用节点，都不能翻出去

**Comment by yanue** [comment]
不是全支持ssr的加密方式,v2本身的问题
