### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by antergone** [yanue/V2rayU#215]
Version: 1.4.1
错误日志：
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1080 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1080 > listen tcp 127.0.0.1:1080: bind: address already in use

我可以肯定确认1080端口没有占用。
lsof
telnet
都已经尝试过了

我在配置里面换成了1081，一样也会报错，日志里面端口号换了而已

**Comment by zeptolee** [comment]
the same phonomenon when i turn it on.

**Comment by Weipengzhou** [comment]
me too

**Comment by Weipengzhou** [comment]
偏好设置里要改,服务器配置里也要改
![image](https://user-images.githubusercontent.com/13349980/66798372-613f6200-ef40-11e9-9bf7-215835379337.png)
我的已经可以用了.

**Comment by Qi-HuT** [comment]
老哥你解决这个问题了嘛？？

**Comment by yanue** [comment]
更换重试

**Comment by LYY** [comment]
有人解决了这个问题么？我换成任意端口都提示`bind: address already in use`。用`lsof`也查不到占用的程序，重启也不行，很诡异啊

**Comment by Hhannzch** [comment]
解决啦 在偏好设置里本机http监听端口改一下 +-2范围就行……
