### ISSUE TITLE
ssr订阅不行 导入成功了 但是不管是pac还是全局都不行 建议增加测速功能

### ISSUE THREAD

**Issue by yuzhenghuan** [yanue/V2rayU#216]
测速我可以看看到底有没有连上，你要是能完美支持ssr和v2，那这就可以替代N8了啊哈哈

**Comment by shenzt68** [comment]
![image](https://user-images.githubusercontent.com/17406910/66739107-939a8200-eea2-11e9-91ef-756bd5281f22.png)
根本没有ssr选项啊？

**Comment by WalterZou** [comment]
同样的问题，SSR 订阅后能够拉到 SS 节点，但是选择服务器后无效，不能访问被墙的网站

**Comment by yanue** [comment]
ss并非全支持加密方式,请看对应加密方式是否正确
