### ISSUE TITLE
无法识别pac

### ISSUE THREAD

**Issue by FEI17N** [yanue/V2rayU#218]
导入pac成功 但是使用pac模式 无法翻墙

**Comment by bigwh1te** [comment]
存在同样问题，想问下V2rayU PAC配置格式和SS是否有区别？ 目前只要开Pac模式国内站点基本上打不开。

**Comment by lawger** [comment]
我也是这样。。。

**Comment by littlebox692** [comment]
> 我也是这样。。。

我连浏览pac文件都失败，弹出来的是127.0.0.1/xxxx地址。。。。在哪里可以配？你们解决了？

**Comment by yanue** [comment]
#195
