### ISSUE TITLE
点击Configure...后程序退出

### ISSUE THREAD

**Issue by txdywy** [yanue/V2rayU#22]
从之前版本一路升级过来.其他功能正常使用,但是无法进入server设置了,一点击就退出.logs上没有信息

**Comment by yanue** [comment]
这种信息在系统日志里面的,  command+空格 搜索 console.app 打开, 右边输入v2rayu搜索,然后重启看下具体有什么日志

**Comment by txdywy** [comment]
@yanue 感觉是配置可能有兼容问题,在哪里能找到V2rayU存server config的地方?
