### ISSUE TITLE
10.15最新版系统无法安装

### ISSUE THREAD

**Issue by sdzyff** [yanue/V2rayU#220]
10.15最新版系统无法安装   此软件需要更新。请联系开发者了解更多信息。

**Comment by wjzxz2008** [comment]
不要在安装界面拖动，把图标往访达的“应用程序”里拖

**Comment by xs23933** [comment]
brew cash install v2rayu 也行啊 不过就算你装上了也没用

**Comment by xs23933** [comment]
报错这个问题还没解决
2019/10/21 12:19:55 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.

**Comment by yuyang2009** [comment]
> 报错这个问题还没解决
> 2019/10/21 12:19:55 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.

这个报错我觉得不影响，在终端配置代理后是可以正常使用的。
chrome 上就访问不了，请求不走代理服务器。

**Comment by EndlessTJ** [comment]
![image](https://user-images.githubusercontent.com/23179932/67923508-0157e500-fbe9-11e9-8fec-84d8b07e8fa3.png)
同10.15， 无法打开

**Comment by xs23933** [comment]
> ![image](https://user-images.githubusercontent.com/23179932/67923508-0157e500-fbe9-11e9-8fec-84d8b07e8fa3.png)
> 同10.15， 无法打开

这个非签名软件都会报这个错误所以这个不是这个软件的问题.
具体你可以看这个, 标准MacOS app 未签名程序安装操作说明

```

一、提示“XXX已损坏，打不开，您应该将它移至废纸篓”的解决方法：

1. 依次点击桌面底部程序坞的 “启动台”（小火箭图标）→ “其他” → “终端” 打开终端，粘贴复制输入命令：“sudo spctl --master-disable” 然后回车；

2. 提示 “Password:” ，输入Mac系统密码按回车即可（这里输入密码不会显示），没有提示说明操作成功。

3. 如果还不行，在终端粘贴复制输入命令：“sudo xattr -r -d com.apple.quarantine ”（注意最后有一个空格），打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面会得到类似组合：“sudo xattr -r -d com.apple.quarantine /Applications/Downie\ 3.app”，回到终端窗口按回车，输入系统密码回车即可。


二、打开软件提示“意外退出”、“应该移到废纸篓”等解决方法：

1. 依次点击桌面底部程序坞的 “启动台”（小火箭图标） → “其他” → “终端” 打开终端，粘贴复制命令：“xcode-select --install” 然后回车，弹出提示后点击 “安装” 等待安装完成；

2. 在终端粘贴复制输入命令：“codesign --force --deep --sign - ”（注意最后有一个空格），打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面会得到类似组合：“codesign --force --deep --sign - /Applications/Downie\ 3.app”，回到终端窗口按回车，提示 “replacing existing signature” 即可。

```

**Comment by EndlessTJ** [comment]
> > ![image](https://user-images.githubusercontent.com/23179932/67923508-0157e500-fbe9-11e9-8fec-84d8b07e8fa3.png)
> > 同10.15， 无法打开
> 
> 这个非签名软件都会报这个错误所以这个不是这个软件的问题.
> 具体你可以看这个, 标准MacOS app 未签名程序安装操作说明
> 
> ```
> 
> 一、提示“XXX已损坏，打不开，您应该将它移至废纸篓”的解决方法：
> 
> 1. 依次点击桌面底部程序坞的 “启动台”（小火箭图标）→ “其他” → “终端” 打开终端，粘贴复制输入命令：“sudo spctl --master-disable” 然后回车；
> 
> 2. 提示 “Password:” ，输入Mac系统密码按回车即可（这里输入密码不会显示），没有提示说明操作成功。
> 
> 3. 如果还不行，在终端粘贴复制输入命令：“sudo xattr -r -d com.apple.quarantine ”（注意最后有一个空格），打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面会得到类似组合：“sudo xattr -r -d com.apple.quarantine /Applications/Downie\ 3.app”，回到终端窗口按回车，输入系统密码回车即可。
> 
> 
> 二、打开软件提示“意外退出”、“应该移到废纸篓”等解决方法：
> 
> 1. 依次点击桌面底部程序坞的 “启动台”（小火箭图标） → “其他” → “终端” 打开终端，粘贴复制命令：“xcode-select --install” 然后回车，弹出提示后点击 “安装” 等待安装完成；
> 
> 2. 在终端粘贴复制输入命令：“codesign --force --deep --sign - ”（注意最后有一个空格），打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面会得到类似组合：“codesign --force --deep --sign - /Applications/Downie\ 3.app”，回到终端窗口按回车，提示 “replacing existing signature” 即可。
> ```

非常感谢

**Comment by yanue** [comment]
1.5已修复
