### ISSUE TITLE
开机自启动关闭不了

### ISSUE THREAD

**Issue by wjzxz2008** [yanue/V2rayU#225]
无法关掉开机自启动

**Comment by naore** [comment]
Same issue.

**Comment by Loyea** [comment]
我也是。

只要打开过v2ray，就会生成v2ray-core的启动代理。 这个启动代理与v2ray的偏好设置中的【开机自动启动】独立的。也就是说，即使你没勾选【开机自动启动】，下次开机后台也会出现一个名为 v2ray 的进程，虽然在前台看不到gui，但是已经在使用上一次连接的配置运行了。

**Comment by yanue** [comment]
> 我也是。
> 
> 只要打开过v2ray，就会生成v2ray-core的启动代理。 这个启动代理与v2ray的偏好设置中的【开机自动启动】独立的。也就是说，即使你没勾选【开机自动启动】，下次开机后台也会出现一个名为 v2ray 的进程，虽然在前台看不到gui，但是已经在使用上一次连接的配置运行了。

是这个逻辑

**Comment by yanue** [comment]
#154

**Comment by kentooo** [comment]
> 我也是。
> 
> 只要打开过v2ray，就会生成v2ray-core的启动代理。 这个启动代理与v2ray的偏好设置中的【开机自动启动】独立的。也就是说，即使你没勾选【开机自动启动】，下次开机后台也会出现一个名为 v2ray 的进程，虽然在前台看不到gui，但是已经在使用上一次连接的配置运行了。

一样的问题，而且没办法再monitor中杀掉v2ray进程，需要手动开启一次v2rayU，然后退出v2rayU才可以把这个进程杀掉，很头疼，

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0

**Comment by godfox2012** [comment]
> 已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0

已经更新但是没有起作用，关闭自动启动，依然还是会自动启动

**Comment by DingYou** [comment]
更新至2.2.0了依然存在这个问题

**Comment by V2beach** [comment]
我用的3.0.0版本仍有这个问题。

**Comment by xapool** [comment]
Same issue.

**Comment by followztx** [comment]
流氓软件，总是开机自启，卸载掉吧。
