### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by manmanluo** [yanue/V2rayU#228]

**Comment by manmanluo** [comment]
提示需要管理员名称和密码

**Comment by noroadzh** [comment]
不要在安装界面拖动，把图标往访达的“应用程序”里拖

**Comment by rosefun** [comment]
> 不要在安装界面拖动，把图标往访达的“应用程序”里拖

这样安装后，无法打开V2rayU，请教下是什么问题？

**Comment by noroadzh** [comment]
> > 不要在安装界面拖动，把图标往访达的“应用程序”里拖
> 
> 这样安装后，无法打开V2rayU，请教下是什么问题？

好像是程序内部出问题，这个只有找 作者看了，我也没解决到，感觉应该是mac10.15的权限什么的问题引起的

**Comment by noroadzh** [comment]
#220 你可以看看 这个 不过我还是打不开

**Comment by xiaoxintang** [comment]
![image](https://user-images.githubusercontent.com/24927686/67922600-2a2aab00-fbe6-11e9-845c-685a1dc62aee.png)

**Comment by yanue** [comment]
下载1.5
