### ISSUE TITLE
启动不了 log如下

### ISSUE THREAD

**Issue by gwd0715** [yanue/V2rayU#229]
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by import-yuefeng** [comment]
只是端口被占用，检查一下 127.0.0.1:1087 是否被什么进程占用
参考指令：lsof -i:1087

**Comment by leejnull** [comment]
lsof -i:1087
kill 占用端口
重复多次，知道log提示start

**Comment by yanue** [comment]
端口占用,请更换

**Comment by itnewgay** [comment]
我也有同样的问题。 端口更换后，开始正常。但是第二天又不行了。确定根本不是端口被占用。 用 netstat -ano 查看，这个端口根本没有被占用。
