### ISSUE TITLE
使用manual配置的routing规则应该有问题

### ISSUE THREAD

**Issue by tangtangl** [yanue/V2rayU#23]
"routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "outboundTag": "direct",
          "type": "field",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "domain": [
            "geosite:cn",
            "geosite:speedtest"
          ]
        }
这一段按照官方说明这样写规则的话是同时符合ip规则和域名规则的才会走设置的outbound，实际使用下来我也发现我这边没有实现国内外分流。改为
      "rules": [
        {
          "outboundTag": "direct",
          "type": "field",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ]
        },
        {
          "outboundTag": "direct",
          "type": "field",
          "domain": [
            "geosite:cn",
            "geosite:speedtest"
          ]
        }
这样两个规则后分流正常。
然后我手动编辑config之后如果我再进入configure之后会强制恢复上面的规则。
希望作者帮忙查看一下

**Comment by yanue** [comment]
这个应该是routing区域解析错误,用的是默认数据了
最近比较忙, 后续修复

**Comment by tangtangl** [comment]
> 这个应该是routing区域解析错误,用的是默认数据了
> 最近比较忙, 后续修复

因为我看https://toutyrater.github.io/basic/routing/cndirect.html这里的规则也是这样写，下面说明也有写：在rules 数组中的每个规则由一组大括号{ }扩起来。不知道是不是我的理解有错误，还是跟4.0以前的规则有区别？没有太注意过。
而且我在win系统下面用其他软件也是这样的问题，如果ip和域名写在一组大括号内就无法分流，所以我才觉得可能是规则的问题。

**Comment by hyliang96** [comment]
**“手动模式”生成的config依旧无法国内直连**；但“导入模式”中修改config后能成功解析、保存、国内直连：

详细信息：

版本： V2rayU 1.4.1 ，其自带内核 V2Ray 4.20.0

“手动模式”填写地址、端口、id等参数后，V2rayU生成了一段config，其routing部分如下。使用此config，可连接国外网站，**但依旧无法国内直连**。疑似“手动模式”生成的routing的语法有误，无法被v2ray-core解析。

```json
"routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "outboundTag": "direct",
          "type": "field",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "domain": [
            "geosite:cn",
            "geosite:speedtest"
          ]
        }
      ]
    }
  },
```

在导入模式中，将config的 "routing"部分手动更改为如下后，这段config可以成功解析、保存，不会被V2rayU用其默认config覆盖，使用此config可以国内直连。故建议“手动模式”依照如下格式生成routing。

```json
 "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "outboundTag": "direct",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "geosite:cn",
            "geosite:speedtest"
          ]
        }
      ]
    }
  },
```

**Comment by a2232189** [comment]
Reopen this issue because what @hyliang96 said still exists at v1.5.1, please

**Comment by yanue** [comment]
已增加手动配置路由功能
