### ISSUE TITLE
建议添加自定义GFWList地址功能

### ISSUE THREAD

**Issue by Shawshank01** [yanue/V2rayU#232]
在GFWList项目中发现有公布5个官方镜像地址，同时也是官方推荐使用的，经过测试后发现的确可以解决最近出现的原版GFWList地址更新失败的问题。

但是V2rayU目前并没提供GFWList地址可自定义功能，因此无法通过修改为镜像地址来直接解决无法更新的问题，希望开发者能加入/开放此功能。

**Comment by LiangWeiCheng** [comment]
我也在找这个功能 是不是没界面 ,但可以在配置文件里面处理啊

**Comment by Shawshank01** [comment]
> 
> 
> 我也在找这个功能 是不是没界面 ,但可以在配置文件里面处理啊

谢谢告知。很多功能其实都是没有UI界面的，可以在配置文件里修改。

不过这样的话专门做个UI界面出来的意义不就没有了嘛，本来就是为了方便和降低门槛才做出来UI，如果所有东西都通过配置文件修改的话就没必要做UI出来了。

**Comment by yanue** [comment]
同 #198
