### ISSUE TITLE
连不上网

### ISSUE THREAD

**Issue by winterwd** [yanue/V2rayU#233]
同样的vmess配置，在手机上就可以访问，mac 就不能

**Comment by shingohu** [comment]
一样

**Comment by Shawshank01** [comment]
使用url导入可能会产生一些偏差，因为V2Ray和SS不一样，没有统一的标准url。

建议通过url导入后检查每项配置是否正确，活着直接使用.json文件进行导入

**Comment by rudy2steiner** [comment]
一样呀

**Comment by shingohu** [comment]
全局模式发现可以使用

**Comment by yanue** [comment]
需要查看下具体配置细节
