### ISSUE TITLE
DNS 分流

### ISSUE THREAD

**Issue by JesseWo** [yanue/V2rayU#237]
不支持DNS 分流吗？json配置一保存就自动重置成：
` "dns": {
    "servers": [
      ""
    ]
  },`
或者是因为我操作不当？
https://www.v2ray.com/chapter_02/04_dns.html

**Comment by YUENIIMAA** [comment]
同问，好像自定义的route规则和自定义的dns都不会生效，前者在pac模式下会被gfwlist取代，后者会被Configure中的DNS取代，全局+自定义route我直接就上不了网了ToT。

**Comment by yanue** [comment]
#202
