### ISSUE TITLE
项目打包失败 请问何解啊？

### ISSUE THREAD

**Issue by ilovebamboo** [yanue/V2rayU#24]
![image](https://user-images.githubusercontent.com/6214084/50416222-67057300-085a-11e9-8d8a-0ed410eceaa5.png)

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/50416295-cebbbe00-085a-11e9-92f9-545b297eac28.png)

**Comment by ilovebamboo** [comment]
有没有哪位打好的 给我一份测试谢谢

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases
