### ISSUE TITLE
v2rayu 使用 ss5 和 vmess 均无法联网 且不占用 1080 端口

### ISSUE THREAD

**Issue by Haiming-Yang** [yanue/V2rayU#242]
用 brew 命令安装，使用的 vmess 和 ss5 服务器均可以正常使用，同一台电脑同一个服务器 shadowsocks 客户端可以正常工作。后检查发现 v2rayu 从来不占用 1080 端口，这是为啥啊？安装有问题吗？系统是 macos 10.15，安装方法 brew，问题是 v2rayu 不占用 1080 端口

**Comment by yanue** [comment]
下载1.5重试
