### ISSUE TITLE
我的MAC上用了V2RayX和V2rayU，感觉V2rayU不太稳定，不知道为什么。

### ISSUE THREAD

**Issue by slb116763814** [yanue/V2rayU#244]
我的MAC电脑上同条线路，V2RayX和V2rayU都用了，感觉V2rayU不太稳定，用着用着就掉线了，不知道为什么。

**Comment by LargeJelly** [comment]
是不是购买的流量,优先级问题

**Comment by iSteveyang** [comment]
You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.

在vV2RayU的log里，最多的就是这个了

**Comment by bv5204978** [comment]
我也是哎，感觉u时不时就连不上。。。。

**Comment by iSteveyang** [comment]
> 我也是哎，感觉u时不时就连不上。。。。

我己经改用clashx了，还拥有规则，比pac强些

**Comment by yanue** [comment]
#195
