### ISSUE TITLE
不知道是否有人和我一样问题，osx10.15.1不能正常启动

### ISSUE THREAD

**Issue by noroadzh** [yanue/V2rayU#245]
里面直接报错
Nov  1 21:55:20 dnoroadzhdeMacBook-Pro com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core[26294]): Service exited with abnormal code: 23
Nov  1 21:55:20 dnoroadzhdeMacBook-Pro com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by tobiasde** [comment]
我是启动后没有作用，iOS使用正常

**Comment by zhangyazhong** [comment]
> 我的是报错：
> Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

看下1087端口是不是已经被占用了，如果有占用，kill掉再试试

**Comment by tobiasde** [comment]
> > 我的是报错：
> > Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
> 
> 看下1087端口是不是已经被占用了，如果有占用，kill掉再试试

非常感谢，我将本地客户端端口设置为1088，现在可以用的，就是不知道可否能长期使用。

**Comment by Dream-maerD** [comment]
> > 我的是报错：
> > 无法启动v2ray.com/core/app/proxyman/inbound：无法在1087上侦听TCP> v2ray.com/core/transport/internet：无法在地址127.0.0.1:1087上侦听TCP 127.0.0.1:1087：绑定：地址已在使用中
> 
> 看下1087端口是不是已经被占领了，如果有占用，kill掉再试试
谢谢，的确是pac监听端口被占用的问题；终于可以用放心的用pac模式了，而不是看运气。

**Comment by Zenbow** [comment]
> > > 我的是报错：
> > > Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
> > 
> > 
> > 看下1087端口是不是已经被占用了，如果有占用，kill掉再试试
> 
> 非常感谢，我将本地客户端端口设置为1088，现在可以用的，就是不知道可否能长期使用。

谢谢，我也把本机HTTP监听端口改为了1088，终于可以用了！
