### ISSUE TITLE
PAC模式无法上网, 全局模式可以上网. 

### ISSUE THREAD

**Issue by jaxwang** [yanue/V2rayU#247]
环境:
macOS Catalina 10.15.1
v2rayU 1.4.1

安装方式:
`brew cask install v2rayu`

问题:
切换到pac模式无法上网.
切换到全局模式可以上网.

已经尝试过点击`从GFWlist更新`
`浏览pac`文件也可以正常访问.

但是依然存在问题

<img width="458" alt="WechatIMG5" src="https://user-images.githubusercontent.com/6702636/68178216-10161180-ffc6-11e9-9a06-51bc365e7228.png">

**Comment by CabbSir** [comment]
+1

**Comment by huiyuerandy** [comment]
+1

**Comment by Cong222** [comment]
我和你相反 也是醉了

**Comment by loveallofyou** [comment]
+1 10.15.1

**Comment by niices** [comment]
问题一样  10.15

**Comment by yanue** [comment]
#195
