### ISSUE TITLE
MAC 10.12 运行未响应

### ISSUE THREAD

**Issue by ilovebamboo** [yanue/V2rayU#25]
[“V2rayU”的取样.txt](https://github.com/yanue/V2rayU/files/2709517/V2rayU.txt)

**Comment by ilovebamboo** [comment]
您好 作者
请问 开发这个需要学习object c/cocoa制作OSX 还是学swift(我看到的这个语言多事用来制作IOS应用) 
应该学那个好，我想知道您的这个制作的应用 只需要单一的swift 编程就行了吗？

**Comment by yanue** [comment]
你好 osx10.12没环境测试, 但应该是支持的,最低支持的就是10.12
另外 这个的话  我大致学了下swift,  cocoa这边的话 边摸索边弄的
以上  哈哈
