### ISSUE TITLE
怎么设置本地http监听为0.0.0.0，我要虚拟机也可以用代理，还是没有这个功能啊

### ISSUE THREAD

**Issue by kshq1996** [yanue/V2rayU#250]
怎么设置本地http监听为0.0.0.0，我要虚拟机也可以用代理，还是没有这个功能啊，貌似只有127.0.0.1

**Comment by qylixin** [comment]
> 怎么设置本地http监听为0.0.0.0，我要虚拟机也可以用代理，还是没有这个功能啊，貌似只有127.0.0.1

试试配合Proxifier使用

**Comment by lawrenceching** [comment]
I upvoted this issue.
I hope V2rayU can bind to 0.0.0.0 for its http proxy function.
It should be a trivial change.
I would like to make the change by myself but I just don't know Swift.

**Comment by lawrenceching** [comment]
> > 怎么设置本地http监听为0.0.0.0，我要虚拟机也可以用代理，还是没有这个功能啊，貌似只有127.0.0.1
> 
> 试试配合Proxifier使用

Proxifier is just way too expensive

**Comment by xs23933** [comment]
我建议你暂时自己配置 inbounds
```sh

 "inbounds": [
    {
      "listen": "0.0.0.0",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth",
        "timeout": 360
      },
      "port": "1080"
    },
    {
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
用这里启动 就可以了
/Applications/V2rayU.app/Contents/Resources/v2ray-core/v2ray -config /Applications/V2rayU.app/Contents/Resources/config.json
```

**Comment by xs23933** [comment]
前提是Turn v2rayu off

**Comment by yanue** [comment]
请下载1.5

**Comment by kshq1996** [comment]
> 请下载1.5

棒！谢谢
