### ISSUE TITLE
建议：不要每次重启程序后重建 pac.js

### ISSUE THREAD

**Issue by Justsoos** [yanue/V2rayU#252]
由于 gfwlist 并不科学的对一些网站条目不予处理，所以自建了本地修改版本，但发现 v2rayu 每次重启程序都会从 gfwlist 重建 pac.js 而没有相关不予处理的设置。so

**Comment by LiangWeiCheng** [comment]
弱弱问加楼主 ，mac上生成的pac.js到底在哪 找不到呢

**Comment by Justsoos** [comment]
https://github.com/yanue/V2rayU#%E7%9B%B8%E5%85%B3%E6%96%87%E4%BB%B6
v2rayu 的首页 readme 里有，没有明确说，在
```
/Applications/V2rayU.app/Contents/Resources/pac
```

**Comment by LiangWeiCheng** [comment]
感谢

**Comment by yanue** [comment]
1.5.1已修复
