### ISSUE TITLE
作者大大,帮忙解决一下

### ISSUE THREAD

**Issue by a497134710** [yanue/V2rayU#253]
![image](https://user-images.githubusercontent.com/32241324/68465789-16b6ba00-024e-11ea-8008-803c1c3123af.png)
我手机安卓的都能弄,为啥mac这边日志就是说我  A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory,

**Comment by yanue** [comment]
拖到applications目录

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 蛇皮怪 <notifications@github.com>
发送时间: Friday, November 8, 2019 5:36:40 PM
收件人: yanue/V2rayU <V2rayU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [yanue/V2rayU] 作者大大,帮忙解决一下 (#253)


[image]<https://user-images.githubusercontent.com/32241324/68465789-16b6ba00-024e-11ea-8008-803c1c3123af.png>
我手机安卓的都能弄,为啥mac这边日志就是说我 A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory,

―

**Comment by sch1111878** [comment]
你好, Podfile.lock 也应该加入到git管理中,没有lock的话我下载的依赖都是最新版本,导致无法编译,能不能增加一下?感谢.

**Comment by hasakiSun** [comment]
Windows 系统可以使用吗

**Comment by yanue** [comment]
已加回去

**Comment by yanue** [comment]
请下载1.5
