### ISSUE TITLE
切换节点后总是会监听1087端口

### ISSUE THREAD

**Issue by TheCGDF** [yanue/V2rayU#255]
![TeamViewer_aaadqXmEtQ](https://user-images.githubusercontent.com/17256673/68660424-7aa5ef00-057c-11ea-9fd0-2af0d3c50af2.jpg)

设置了自定义端口之后，如果切换节点，需要重新点一次“保存设置”，否则总是使用1087端口
log会显示unable to bind to address 127.0.0.1:1087

**Comment by yanue** [comment]
没能重现
