### ISSUE TITLE
main: failed to read config file: config.json 

### ISSUE THREAD

**Issue by zzymhz** [yanue/V2rayU#257]
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to read config file: config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: rc4-md5

 > exit status 255

一直报这个错，监听不了端口，求解～～～

**Comment by joyfun** [comment]
同样的bug 之前好像还可以 现在突然不支持rc4-md5了

**Comment by yanue** [comment]
v2本身 不支持
