### ISSUE TITLE
Hope support MAC OS Catalina 10.15

### ISSUE THREAD

**Issue by crossbones1** [yanue/V2rayU#258]
RT

**Comment by YUENIIMAA** [comment]
V2RayU works fine on macOS 10.15, just go to System Preference -> Security & Privacy -> General and allow V2RayU to run when you run it for the first time(IF NOT, you will meet an error message).

**Comment by lawrenceching** [comment]
Yes it works well on my Catalina without any issue.

**Comment by yanue** [comment]
下载1.5试下
