### ISSUE TITLE
使用 PAC 模式在 Mac 下 Chrome 上不去外网

### ISSUE THREAD

**Issue by nickeljew** [yanue/V2rayU#260]
Mac Catalina，使用全局模式使用没问题，可以上 google youtube 等，但 pac 模式就不行。全局模式对我工作有影响。在 ShadowsocksX-ng-r8下用 pac 模式是正常的。不知道是不是 V2RayU 的 pac 文件有问题。

**Comment by ZaaLee** [comment]
同样 mac下面pac模式不管用了。重新安装也不行

**Comment by yanue** [comment]
#195
