### ISSUE TITLE
vmess-header

### ISSUE THREAD

**Issue by z7z** [yanue/V2rayU#264]
已链接模式添加服务器，Windows的N可以用，Mac这个导入模式添加完vmess链接后，不能正常工作，试试了半天，点击手动模式，发现header设置的是none，但是vmess里的header明明是wechat，手动选择wechat，正常工作。

**Comment by chenmin1992** [comment]
+1  还有quic的密码和加密方式读取不到   看代码根本没有处理v2rayN的v2的vmess://订阅格式

**Comment by yanue** [comment]
#161
