### ISSUE TITLE
socks5连接不上

### ISSUE THREAD

**Issue by zqcccc** [yanue/V2rayU#266]
chrome 上用 SwitchyOmega 连接配置挺简单的
![image](https://user-images.githubusercontent.com/19168323/69400421-9784b400-0d2c-11ea-911f-de65bd2b1d4c.png)
这样就可以了，

可是 v2rayU 配置了就是连不上
![image](https://user-images.githubusercontent.com/19168323/69400548-0b26c100-0d2d-11ea-85bc-1448226a0237.png)
请问是我哪里配置错了吗？

原来是 SwitchyOmega > sock5:127.0.0.1:1079
现在我想 SwitchyOmega > v2rayU > sock5:127.0.0.1:1079 请问应该怎么做呢

**Comment by yanue** [comment]
没场景测试, v2本身是支持的
