### ISSUE TITLE
Pac模式完全不能用了。重装还是存在问题。

### ISSUE THREAD

**Issue by ZaaLee** [yanue/V2rayU#269]

**Comment by imsong52** [comment]
同样的问题

**Comment by ZaaLee** [comment]
看了下，好像是Google Chrome Helper这个进程占用了1087端口。

**Comment by ZaaLee** [comment]
解决了，是shadowsocks占用1087端口，导致不能使用http代理。要把shadowsocks删干净，配置文件啥的都删掉。
