### ISSUE TITLE
无论什么模式，都不能上网，一直在报错，而且，每次切换模式，系统都要弹框输密码确认，不能拖动到系统程序里

### ISSUE THREAD

**Issue by cqamber** [yanue/V2rayU#270]
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory

**Comment by zhou-zhou** [comment]
同样的问题

**Comment by yanue** [comment]
下载1.5
