### ISSUE TITLE
关于订阅的问题

### ISSUE THREAD

**Issue by jhonlo** [yanue/V2rayU#276]
v2rayn的格式，粘贴板导入 vmess:// 链接能正常解析出节点，使用订阅的时候死活连不上，看了下log: failed to parse ID，然后看了下解析出来的节点json发现把订阅url中的token解析成uuid了。

**Comment by xs23933** [comment]
哈哈确实是这样的, 订阅的后面参数解析为了uuid 了

**Comment by yanue** [comment]
1.5.1已修复

**Comment by qinkangdeid** [comment]
最新的 我使用还是相同的 users 里的id解析成了我订阅的地址

**Comment by qinkangdeid** [comment]
> 最新的 我使用还是相同的 users 里的id解析成了我订阅的地址

brew 安装的还是1.5.0 看错了  下载release里的1.5.1就可以了
