### ISSUE TITLE
点击Ping Speed程序卡死

### ISSUE THREAD

**Issue by Pr-Chen** [yanue/V2rayU#278]

**Comment by ApocaIypse** [comment]
多等一会就行了

**Comment by jony4** [comment]
建议做到后台线程里边去执行，然后发出消息通知的方式

**Comment by stevechoris** [comment]
碰到同样的问题。

**Comment by cjb2667** [comment]
点击ping 毫无反应

**Comment by riverchu** [comment]
感觉没有必要阻塞程序，ping这种简单的操作后台执行一下就好了吧，我觉得都不需要提示ping完成，可以后台自动每几个小时执行一次，有需要的时候去看就可以。

**Comment by wulei** [comment]
> 感觉没有必要阻塞程序，ping这种简单的操作后台执行一下就好了吧，我觉得都不需要提示ping完成，可以后台自动每几个小时执行一次，有需要的时候去看就可以。

这个感觉比较好，异步的吧，同步点一下整个机器卡半天

**Comment by litangyu** [comment]
我提交了一个pr #330 把ping放到后台线程了

**Comment by litangyu** [comment]
> 多等一会就行了

以现有代码来看，如果server有很多（假设100个或更多），会在所有server都测试结束后才能响应用户时间，也就是造成了假死，这个时间可能会很长。

**Comment by yanue** [comment]
已修复,请下载2.0.0
