### ISSUE TITLE
MacOS10.15 更新之后连不上代理服务器

### ISSUE THREAD

**Issue by ApocaIypse** [yanue/V2rayU#279]
日志反复报错：
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.

**Comment by muermaru** [comment]
10.14.6同样出现这个情况

**Comment by taochangle** [comment]
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0070 'p'

**Comment by xayle** [comment]
this ```id``` wrong
        "vnext": [
          {
            "address": "www.google.com",
            "users": [
              {
                "id": "e.cc/link/94SOSzCdltbITAoL?sub=3",
                "alterId": 2,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 10086
          }
        ]

**Comment by yanue** [comment]
解析错了 会尽快修复

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xayle <notifications@github.com>
发送时间: Monday, December 2, 2019 11:01:39 AM
收件人: yanue/V2rayU <V2rayU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [yanue/V2rayU] MacOS10.15 更新之后连不上代理服务器 (#279)


this id wrong
"vnext": [
{
"address": "www.google.com",
"users": [
{
"id": "e.cc/link/94SOSzCdltbITAoL?sub=3",
"alterId": 2,
"level": 0,
"security": "aes-128-gcm"
}
],
"port": 10086
}
]

―

**Comment by yanue** [comment]
1.5.1已修复
