### ISSUE TITLE
global 模式chrome不能上网，safari可以

### ISSUE THREAD

**Issue by hackershi** [yanue/V2rayU#282]
怎么解决

**Comment by yanue** [comment]
浏览器插件?

**Comment by PoliJun** [comment]
你的chrome浏览器代理设置怎么设置的？

**Comment by hackershi** [comment]
我的chrome 没有设置代理。我的症状和这个一样 [https://github.com/yanue/V2rayU/issues/162]

**Comment by Riverszhou** [comment]
一样的问题  直接chrome的匿名模式也是上不了的，可以排除插件影响了！

**Comment by gaotongsh** [comment]
一样的问题。我可以补充一点，添加到本软件的Shadowsocks服务器+全局模式，可以正常上网。

换句话说，Chrome环境下：

协议类型 | VMess服务器 | Shadowsocks服务器
---|---|---
全局模式 | ❌|✅
PAC模式 | ✅|✅

**Comment by gaotongsh** [comment]
我找到了一个Workaround。
在全局模式下，目前软件同时设置的HTTP代理和SOCKS代理。在采用VMess服务器时，如果把HTTP代理解除（取消勾选代理系统设置的复选框，下图红框内所示的两个），仅保留SOCKS代理，即可在Chrome下正常上网。目前看来，Chrome无法正常解析VMess协议的HTTP代理。
![截图](https://user-images.githubusercontent.com/12027397/72199793-baedf480-347b-11ea-8022-7311f497a877.png)

**Comment by yanue** [comment]
#195

**Comment by CuteApril** [comment]
> 我找到了一个Workaround。
> 在全局模式下，目前软件同时设置的HTTP代理和SOCKS代理。在采用VMess服务器时，如果把HTTP代理解除（取消勾选代理系统设置的复选框，下图红框内所示的两个），仅保留SOCKS代理，即可在Chrome下正常上网。目前看来，Chrome无法正常解析VMess协议的HTTP代理。
> ![截图](https://user-images.githubusercontent.com/12027397/72199793-baedf480-347b-11ea-8022-7311f497a877.png)

我挂了vpn后按也是chrome无法访问Google但safari可以，按照你这样取消掉两个http协议后仍然无法访问怎么办呜呜呜
<img width="316" alt="屏幕快照 2021-12-03 下午5 14 51" src="https://user-images.githubusercontent.com/95471844/144577124-4a4b74d1-ea58-4274-bdb3-3b6e37a4775f.png">

**Comment by gaotongsh** [comment]
> 我挂了vpn后按也是chrome无法访问Google但safari可以，按照你这样取消掉两个http协议后仍然无法访问怎么办呜呜呜

我这个问题在某个版本更新后就解决了，你自己再看看吧，多试试

**Comment by shijiezhou1** [comment]
终于帮到我了 谢谢
