### ISSUE TITLE
1.5.0的版本订阅仍然存在问题

### ISSUE THREAD

**Issue by aishlai** [yanue/V2rayU#286]
虽然可以正确的获取订阅内容了，但是解析出来的是错误的

**Comment by jony4** [comment]
+1

**Comment by aishlai** [comment]
其中会把 V2ray的id直接换成 订阅地址，id应该是一串43d203df-a734-4663-9dd5-5563733dd86a 类似这样的数据

**Comment by riverchu** [comment]
+1 解析的id没有从base64里面取，需要手动再点一次导入才能用

**Comment by yanue** [comment]
1.5.1已修复
