### ISSUE TITLE
更新到1.5.0后无法使用

### ISSUE THREAD

**Issue by cnyy7** [yanue/V2rayU#287]
更新到1.5.0后在终端中会报错：

        `OpenSSL SSL_connect: SSL_ERROR_SYSCAL`

服务器可以ping通

现在重新安装了1.4.1版本使用无问题

**Comment by bigwh1te** [comment]
v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+0026 '&'

无法使用

**Comment by MuMuTian** [comment]
main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+002D '-'

也是报这个错

**Comment by riverchu** [comment]
> main: failed to create server > v2ray.com/core/proxy/vmess/outbound: failed to parse server spec > v2ray.com/core/proxy/vmess: failed to parse ID > encoding/hex: invalid byte: U+002D '-'
> 
> 也是报这个错

这个问题是订阅解析有问题，可以去这个issue里面说 #286

**Comment by yanue** [comment]
1.5.1已修复
