### ISSUE TITLE
type: http不会加载

### ISSUE THREAD

**Issue by bnhxy** [yanue/V2rayU#293]
地址里http类型不会加载，导入后
type显示none，不是HTTP
security被默认aes-128-gcm不是none
类似
{
  "v": "2",
  "ps": "v2test_127.0.0.1",
  "add": "127.0.0.1",
  "port": "2424",
  "id": "588e3335-772c-4da7-bfc1-f91dc6121234",
  "aid": "233",
  "net": "tcp",
  "type": "http",
  "host": "www.baidu.com",
  "path": "",
  "tls": ""
}

测试链接
vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ2MnRlc3RfMTI3LjAuMC4xIiwKICAiYWRkIjogIjEyNy4wLjAuMSIsCiAgInBvcnQiOiAiMjQyNCIsCiAgImlkIjogIjU4OGUzMzM1LTc3MmMtNGRhNy1iZmMxLWY5MWRjNjEyMTIzNCIsCiAgImFpZCI6ICIyMzMiLAogICJuZXQiOiAidGNwIiwKICAidHlwZSI6ICJodHRwIiwKICAiaG9zdCI6ICJ3d3cuYmFpZHUuY29tIiwKICAicGF0aCI6ICIiLAogICJ0bHMiOiAiIgp9

**Comment by aishlai** [comment]
好像还真是~

**Comment by bnhxy** [comment]
有计划在下个版本修复吗？每个更新后，都要手动一个个修正，比较麻烦！

**Comment by yanue** [comment]
已修复 2.0.0
