### ISSUE TITLE
重复提示监听占用

### ISSUE THREAD

**Issue by bigwh1te** [yanue/V2rayU#295]
2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

每次都是提示监听占用，我在配置里面手动更改一次（1087换成类似1099），偶尔会能用一段时间。只要切换节点，又报同样错误，真是让人抓狂... 期待修复这个问题

**Comment by bigwh1te** [comment]
使用别的客户端不存在这个问题，只会在V2出现这个问题。

**Comment by aishlai** [comment]
你把别的app关掉试试？

**Comment by vipadm** [comment]
2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
这个占用，看了只能修改 V2RayU 客户端设置和 系统进程有冲突  
V2RayU--->Pac.. --> Advance  界面中的 
 local  sock port  local http port  修改下才可以

**Comment by HulkZeng** [comment]
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

我也是遇到了这个问题，每次切换不同的服务器配置都会这样，其实没有切换成功，用的还是上一次的服务器，必须要手动改端口。

**Comment by bigwh1te** [comment]
> 2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
> A unified platform for anti-censorship.
> Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
> 这个占用，看了只能修改 V2RayU 客户端设置和 系统进程有冲突
> V2RayU--->Pac.. --> Advance 界面中的
> local sock port local http port 修改下才可以

这种办法只是临时启用，只要一切换节点就失效

**Comment by bigwh1te** [comment]
> Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
> 
> 我也是遇到了这个问题，每次切换不同的服务器配置都会这样，其实没有切换成功，用的还是上一次的服务器，必须要手动改端口。

是的，我的问题跟你一模一样。  关键是使用别的VPN客户端就不会出现监听端口占用问题。

**Comment by HulkZeng** [comment]
这个应该是跟MacOs的系统版本有关，我的是最新的系统版本是10.15.2；
我同事的电脑是10.14，目前就没这个问题。

**Comment by sagezhong** [comment]
我更新到最新的Mac系统也出现了这个问题

**Comment by yanue** [comment]
可能是重复配置导致 fix #328
