### ISSUE TITLE
SSR 不能用

### ISSUE THREAD

**Issue by tankxie** [yanue/V2rayU#297]
2019/12/04 14:31:15 [Info] [2482452406] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:no6575115055.internetworld.cloud:443
2019/12/04 14:31:15 [Info] [2482452406] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:www.google.com:443 via tcp:no6575115055.internetworld.cloud:443
2019/12/04 14:31:15 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/12/04 14:31:15 [Info] [933549669] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/12/04 14:31:15 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/12/04 14:31:15 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/12/04 14:31:15 [Info] [933549669] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/12/04 14:31:15 [Info] [933549669] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:no6575115055.internetworld.cloud:443

**Comment by yanue** [comment]
#322
