### ISSUE TITLE
更新到1.5.1后不能用

### ISSUE THREAD

**Issue by jinghongdaxiong** [yanue/V2rayU#298]
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1 > listen tcp 127.0.0.1:1: bind: permission denied

**Comment by yanue** [comment]
端口不对,一般不能小于1024
