### ISSUE TITLE
mac os 10.14.3 下不起作用

### ISSUE THREAD

**Issue by zomliu** [yanue/V2rayU#30]
另：用户手册链接打不开

**Comment by Insofan** [comment]
同上

**Comment by yanue** [comment]
等我升级测试

**Comment by Insofan** [comment]
@yanue 我是10.14.1 手机上可以上 mac用这个上不了

**Comment by libra10062619** [comment]
Mac 10.13.6 同样不能连接

**Comment by yanue** [comment]
我升级到10.14.3了,pac/global/manual模式都ok,请问你们启用的都是什么模式呢
可以去wifi设置里面看下是否有额外代理信息

**Comment by Insofan** [comment]
@yanue 现在可以用了 是否是 vmess 导入有问题 我把config.json从服务器上考下来然后用文件导入就可以用了但是上午我用的vmess并没有成功

**Comment by yanue** [comment]
@Insofan 通过配置界面设置没成功?那是不是设置没对呢

**Comment by QutGit** [comment]
我这也是升级完以后shadowsocks都不行了

**Comment by Insofan** [comment]
@yanue 应该不是 好几个人出现了 应该是有BUG只不过 我这里表现是vmess不行

**Comment by zomliu** [comment]
我朋友的是升级后shadowsocks不行了，换了这个也不行🙅‍♂️

**Comment by yanue** [comment]
> 我朋友的是升级后shadowsocks不行了，换了这个也不行🙅‍♂️
> 
> PS：哪里还能看用户手册，链接看不了（邮箱：[zombre449@163.com](mailto:zombre449@163.com)）

手册就是readme，[https://github.com/yanue/V2rayU/blob/master/README.md](https://github.com/yanue/V2rayU/blob/master/README.md)

**Comment by Ruixu05** [comment]
全部设置完成也不能使用，端口改成1087也不可以
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1086 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1086 > listen tcp 127.0.0.1:1086: bind: address already in use
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by yanue** [comment]
@Ruixu05 看日志的话 端口都被占用了 你可以换其他端口试下

**Comment by Ruixu05** [comment]
@yanue 换了端口还是不行，mac真心难搞，楼主能远程帮忙看下不

**Comment by yanue** [comment]
@Ruixu05 装个teamviewer 给我截图到: yanue@outlook.com

**Comment by zomliu** [comment]
我这边OK了，原因是google浏览器中启用了代理插件，毙掉插件就可以了

**Comment by Ruixu05** [comment]
@yanue 发过去了
