### ISSUE TITLE
订阅更新日志显示失败，订阅的时候根据最近复制过来的url获取不到订阅信息，为什么？

### ISSUE THREAD

**Issue by zachbai2016** [yanue/V2rayU#301]
loading from : https://portal.caipin.pro/modules/servers/V2raySocks/osubscribe.php?sid=51160&token=9K1sgRGqtbNM

del old from url : https://portal.caipin.pro/modules/servers/V2raySocks/osubscribe.php?sid=51160&token=9K1sgRGqtbNM

fail: no found ss://, ssr://, vmess://
url: <!DOCTYPE HTML>

这里我先不重置UUID 和 token 了， 请问为什么订阅的时候拉不到服务信息？

**Comment by yjy123123** [comment]
请问你解决了吗？

**Comment by RowlingZhang** [comment]
解决了吗

**Comment by yanue** [comment]
几种情况:
1.  订阅地址打不开,需要翻墙情况,请全局代理试下
2. 订阅地址有token检验或过期情况
3. 订阅地址返回的内容无法解析
