### ISSUE TITLE
Ping Speed会卡死一段时间

### ISSUE THREAD

**Issue by zezhishao** [yanue/V2rayU#302]
大概会卡死15s左右。
---- 
macOS版本：10.14.6、10.15.1
V2RayU版本：V2rayU 1.5.1

**Comment by Justsoos** [comment]
不止15s 问题，（我用总共超过20个节点测试 ping）会从bar上直接把v2rayU 的 logo卡没 -- 实际查了下 v2rayU 进程异常退出，但后台 v2ray core 还在运行。

**Comment by Justsoos** [comment]
> 不止15s 问题，（我用总共超过20个节点测试 ping）会从bar上直接把v2rayU 的 logo卡没 -- 实际查了下 v2rayU 进程异常退出，但后台 v2ray core 还在运行。

纠正一下这个问题来历： 是 v2rayU 的socks5 上游解析错误，我改了 config.json 后，虽然可以正确运行 v2ray core，但会造成 v2rayU 在测试 ping 的情况下直接异常退出。
但比较奇怪，系统日志并没有退出记录。

**Comment by Meowzz95** [comment]
我这边只有一个自建server 也会卡死几秒钟，而且怀疑卡死这几秒被计算到ping值里面了
![image](https://user-images.githubusercontent.com/22430379/70844105-39ed0e80-1e77-11ea-9b6c-5c2c70bc1851.png)
实际这个server的ping是80ms左右

**Comment by Justsoos** [comment]
观察这次加的是 tcp port ping，并不是 icmp ping，所以才会导致大规模卡死

**Comment by ycdm** [comment]
一样也有类似的问题

**Comment by litangyu** [comment]
Issues link #278 
PR link #330

**Comment by yanue** [comment]
已修复
