### ISSUE TITLE
pac模式不行，全局没问题，手机正常

### ISSUE THREAD

**Issue by Tungwerl** [yanue/V2rayU#304]
最近老被这个问题困扰

**Comment by junkwei** [comment]
我的也是，macOS 10.15.1 V2Ray1.5.1

**Comment by CrazyMouse** [comment]
pac 貌似用户定义的规则无效

**Comment by vose2008** [comment]
同样问题，自带的pac 规则更新不了，自定义的应用无效。

**Comment by Justsoos** [comment]
请你们自行检查这个文件的头部：
`/Applications/V2rayU.app/Contents/Resources/pac/proxy.js`
是否如下类似：
```
// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;";

var rules = [
```

**Comment by vose2008** [comment]
已解决，谢谢 @Justsoos

**Comment by CrazyMouse** [comment]
@Justsoos 我的貌似多了一个、
var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";
有影响么？

**Comment by luganhuo** [comment]
> @Justsoos 我的貌似多了一个、
> var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";
> 有影响么？

我也是这样，无法使用pac，版本：1.5.1

**Comment by vose2008** [comment]
改了也会失效 pac 又不工作了，修改后一样不工作

**Comment by junkwei** [comment]
查看日志，会提示1087端口已经在使用，这个时候修改端口号就可以了，但是一切换节点又是提示端口已经在使用了，又得重新保存下修改的端口，感觉一切换节点，端口号又重置成默认的了

**Comment by littlebox692** [comment]
> 已解决，谢谢 @Justsoos

请问你这个是怎么解决的？

**Comment by yanue** [comment]
#195
