### ISSUE TITLE
开启客户端情况下无法连接Tor

### ISSUE THREAD

**Issue by MrPoopyLobster** [yanue/V2rayU#308]
在设置后无法连接tor，tor设置了代理端口以后，还是无法连接。但是tor用ss就可以连接。

**Comment by vbonluk** [comment]
+1

**Comment by vbonluk** [comment]
https://github.com/v2ray/discussion/issues/49#issuecomment-534890285

上面有方法，但是是V2rayN的Mac没有这款软件。V2rayU又不支持设置。

**Comment by vbonluk** [comment]
`{
  "inbounds": [
    {
      "port": 1080, // 监听端口
      "protocol": "socks", // 入口协议为 SOCKS 5
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"  //socks的认证设置，noauth 代表不认证，由于 socks 通常在客户端使用，所以这里不认证
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess", // 出口协议
      "settings": {
        "vnext": [
          {
            "address": "serveraddr.com", // 服务器地址，请修改为你自己的服务器 IP 或域名
            "port": 16823,  // 服务器端口
            "users": [
              {
                "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，必须与服务器端配置相同
                "alterId": 64 // 此处的值也应当与服务器相同
              }
            ]
          }
        ]
      }
    }
  ]
}`

配置无法写入sniffing

**Comment by vbonluk** [comment]
12/19/19, 13:03:20.687 [WARN] 17 connections have failed:
12/19/19, 13:03:20.687 [WARN] 12 connections died in state connect()ing with SSL state (No SSL object)
12/19/19, 13:03:20.687 [WARN] 5 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
12/19/19, 13:03:20.692 [NOTICE] Closing no-longer-configured Socks listener on 127.0.0.1:9150
12/19/19, 13:03:20.692 [NOTICE] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
12/19/19, 13:03:20.692 [NOTICE] Delaying directory fetches: DisableNetwork is set.


这是tor的报错内容，链接不上ssl

**Comment by DolorHunter** [comment]
> 
> 
> 在设置后无法连接tor，tor设置了代理端口以后，还是无法连接。但是tor用ss就可以连接。

开启sniffing会导致 Tor 无法使用，要使用 Tor 就得关闭 sniffing
