### ISSUE TITLE
Configuration failed for locales using . as thousand separator and , as decimal separator

### ISSUE THREAD

**Issue by pluush** [yanue/V2rayU#309]
> exit status 255
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to read config file: config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file > v2ray.com/core/infra/conf: invalid port range: "1.0800"

IMO it's better to remove the automatic addition of thousand separator in the advanced preferences altogether.

System proxy on Mac also didn't turn on when V2ray-core was turned on (Global Mode) on this particular configuration, needing manual input on Preferences. On V2ray-core turn off, however, the system proxy turns off.

App version: 1.5.1 and 1.4.1

**Comment by yanue** [comment]
dl 2.0.0
