### ISSUE TITLE
客户端性能不佳？

### ISSUE THREAD

**Issue by aglent** [yanue/V2rayU#31]
在同事mac笔记本上安装后 使用v2ray协议 发现速度很慢 远不如windows下客户端的速度 同一条线路 只能看480P的youtube视频
试着在v2rayU客户端里使用SS协议 和mac下其他SS客户端对比速度 发现速度确实很慢 打开网页都是很卡
不知道客户端有哪里可以优化速度的设置地方？

**Comment by yanue** [comment]
可以尝试手动修改一下dns节点和routing节点:
https://toutyrater.github.io/basic/routing/

**Comment by mll120110** [comment]
我也发现类似情况，请问该如何解决比较好呢
