### ISSUE TITLE
无法启动生效

### ISSUE THREAD

**Issue by xxNB** [yanue/V2rayU#312]
> exit status 255
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: rc4-md5

**Comment by yanue** [comment]
#322
