### ISSUE TITLE
mac 服务器设置直接崩溃

### ISSUE THREAD

**Issue by tonyuncle2019** [yanue/V2rayU#313]
在最初初始化服务器设置时使用了文件config.json 初始化，然后ip配置错误，导致一直连接错误，然后变更服务其设置就直接崩溃，期间尝试修改了/Applications/V2rayU.app/Contents/Resources 下面的config.json 但是启动服务后config.json 马上会被覆盖为之前的错误ip。也尝试了卸载重装，但是重装后依然无法进行服务器设置，并且ip依然是错误的ip。
求help～

**Comment by yanue** [comment]
删除文件 ~/Library/Preferences/net.yanue.V2rayU.plist
