### ISSUE TITLE
每次电脑从待机状态启动无法连接网络，得断掉网络重连才能连上网络v1.5.1, Mac版本：10.15.2

### ISSUE THREAD

**Issue by CannotTell** [yanue/V2rayU#314]

**Comment by zcsunt** [comment]
me too

**Comment by itcodes** [comment]
me too

**Comment by CalanceHao** [comment]
同样的问题，每次重新跑Ping Speed之后就能正常使用了……

之前连不上的日志
> 2019/12/29 16:55:37 [Info] [1905429] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:clients1.google.com:443 via tcp:42.200.112.240:8085
2019/12/29 16:55:37 [Info] [2126988062] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:42.200.112.240:8085
2019/12/29 16:55:37 [Info] [2126988062] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/29 16:55:37 [Info] [2126988062] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:42.200.112.240:8085
2019/12/29 16:55:37 [Info] [2352599904] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:42.200.112.240:8085
2019/12/29 16:55:37 [Info] [3929557573] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:42.200.112.240:8085
2019/12/29 16:55:37 [Info] [2126988062] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:42.200.112.240:8085
2019/12/29 16:55:37 [Warning] [2383806886] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 42.200.112.240:8085: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/29 16:55:37 [Info] [1088358982] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/29 16:55:37 [Info] [1088358982] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: connection ends > context canceled
2019/12/29 16:55:37 [Warning] [2352599904] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 42.200.112.240:8085: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

做完Ping Speed，就正常了……
> 2019/12/29 18:33:54 tcp:127.0.0.1:55641 accepted tcp:www.google.com.hk:443 [agentout] 
2019/12/29 18:33:54 [Info] [4234174029] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com.hk:443
2019/12/29 18:33:54 [Info] [4234174029] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com.hk:443
2019/12/29 18:33:54 [Info] [4234174029] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:10 [Info] [4234174029] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:15 [Info] [4234174029] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:www.google.com.hk:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:16 [Info] [4293925394] v2ray.com/core/proxy/socks: TCP Connect request to tcp:id.google.com.hk:443
2019/12/29 18:34:16 [Info] [4293925394] v2ray.com/core/app/dispatcher: default route for tcp:id.google.com.hk:443
2019/12/29 18:34:16 [Info] [4293925394] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:16 tcp:127.0.0.1:55646 accepted tcp:id.google.com.hk:443 [agentout] 
2019/12/29 18:34:16 [Info] [603808099] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com.hk:443
2019/12/29 18:34:16 [Info] [603808099] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com.hk:443
2019/12/29 18:34:16 [Info] [603808099] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:16 tcp:127.0.0.1:55648 accepted tcp:www.google.com.hk:443 [agentout] 
2019/12/29 18:34:16 [Info] [4293925394] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:id.google.com.hk:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:16 [Info] [603808099] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:www.google.com.hk:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:18 [Info] [1752058513] v2ray.com/core/proxy/socks: TCP Connect request to tcp:id.google.com:443
2019/12/29 18:34:18 [Info] [1752058513] v2ray.com/core/app/dispatcher: default route for tcp:id.google.com:443
2019/12/29 18:34:18 [Info] [1752058513] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:18 tcp:127.0.0.1:55650 accepted tcp:id.google.com:443 [agentout] 
2019/12/29 18:34:18 [Info] [1752058513] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:id.google.com:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:19 [Info] [2352364988] v2ray.com/core/proxy/socks: TCP Connect request to tcp:adservice.google.com.hk:443
2019/12/29 18:34:19 tcp:127.0.0.1:55652 accepted tcp:adservice.google.com.hk:443 [agentout] 
2019/12/29 18:34:19 [Info] [2352364988] v2ray.com/core/app/dispatcher: default route for tcp:adservice.google.com.hk:443
2019/12/29 18:34:19 [Info] [2352364988] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:19 [Info] [2352364988] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:adservice.google.com.hk:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:19 [Info] [2892095563] v2ray.com/core/proxy/socks: TCP Connect request to tcp:adservice.google.com:443
2019/12/29 18:34:19 [Info] [2892095563] v2ray.com/core/app/dispatcher: default route for tcp:adservice.google.com:443
2019/12/29 18:34:19 [Info] [2892095563] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:19 tcp:127.0.0.1:55654 accepted tcp:adservice.google.com:443 [agentout] 
2019/12/29 18:34:20 [Info] [2892095563] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:adservice.google.com:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:21 [Info] [712010038] v2ray.com/core/proxy/socks: TCP Connect request to tcp:ogs.google.com:443
2019/12/29 18:34:21 [Info] [712010038] v2ray.com/core/app/dispatcher: default route for tcp:ogs.google.com:443
2019/12/29 18:34:21 [Info] [712010038] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:21 tcp:127.0.0.1:55656 accepted tcp:ogs.google.com:443 [agentout] 
2019/12/29 18:34:21 [Info] [712010038] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:ogs.google.com:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:31 [Info] [652933475] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2019/12/29 18:34:31 [Info] [652933475] v2ray.com/core/app/dispatcher: default route for tcp:www.gstatic.com:443
2019/12/29 18:34:31 [Info] [652933475] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:31 tcp:127.0.0.1:55658 accepted tcp:www.gstatic.com:443 [agentout] 
2019/12/29 18:34:31 [Info] [2407459117] v2ray.com/core/proxy/socks: TCP Connect request to tcp:apis.google.com:443
2019/12/29 18:34:31 [Info] [2407459117] v2ray.com/core/app/dispatcher: default route for tcp:apis.google.com:443
2019/12/29 18:34:31 [Info] [2407459117] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:31 tcp:127.0.0.1:55660 accepted tcp:apis.google.com:443 [agentout] 
2019/12/29 18:34:31 [Info] [652933475] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:www.gstatic.com:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:31 [Info] [2407459117] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:apis.google.com:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:32 [Info] [669707754] v2ray.com/core/proxy/socks: TCP Connect request to tcp:play.google.com:443
2019/12/29 18:34:32 [Info] [669707754] v2ray.com/core/app/dispatcher: default route for tcp:play.google.com:443
2019/12/29 18:34:32 [Info] [669707754] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:32 tcp:127.0.0.1:55664 accepted tcp:play.google.com:443 [agentout] 
2019/12/29 18:34:32 [Info] [669707754] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:play.google.com:443 via tcp:156.234.236.111:3402
2019/12/29 18:34:33 [Info] [3987854801] v2ray.com/core/proxy/socks: TCP Connect request to tcp:play.google.com:443
2019/12/29 18:34:33 [Info] [3987854801] v2ray.com/core/app/dispatcher: default route for tcp:play.google.com:443
2019/12/29 18:34:33 [Info] [3987854801] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:156.234.236.111:3402
2019/12/29 18:34:33 tcp:127.0.0.1:55666 accepted tcp:play.google.com:443 [agentout] 
2019/12/29 18:34:33 [Info] [3987854801] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:play.google.com:443 via tcp:156.234.236.111:3402

**Comment by q1019736727** [comment]
同样的问题

**Comment by bugushi** [comment]
同样的问题

**Comment by xiaoyuhao0716** [comment]
电脑休眠后必须重启客户端，才可使用。。Mac版本：10.15.3

**Comment by yanue** [comment]
#154
