### ISSUE TITLE
希望可以尽快修复pac模式无法科学上网的问题

### ISSUE THREAD

**Issue by HOMHOG** [yanue/V2rayU#315]
如题，pac模式无法使用

**Comment by lawrenceching** [comment]
发现同样的问题。
初步怀疑是 SOCK 代理出现了问题。

设置 `/Volumes/Macintosh HD/Applications/V2rayU.app/Contents/Resources/pac/pac.js` 返回 HTTP 代理后，恢复正常
`var proxy = "PROXY 127.0.0.1:1087; DIRECT;";`。

**Comment by HOMHOG** [comment]
> 发现同样的问题。
> 初步怀疑是 SOCK 代理出现了问题。
> 
> 设置 `/Volumes/Macintosh HD/Applications/V2rayU.app/Contents/Resources/pac/pac.js` 返回 HTTP 代理后，恢复正常
> `var proxy = "PROXY 127.0.0.1:1087; DIRECT;";`。

按照你的改动确实可以了 谢谢

**Comment by lawrenceching** [comment]
发现原因了。 Sock Proxy 端口被占用，导致无法正常启用。
V2rayU 的 PAC 文件指定的是 Sock Proxy 的地址，所以无法正常上网。

如何验证：

在终端运行 `sudo lsof -PiTCP -sTCP:LISTEN` , 正常情况下应该会看到 V2rayU 占用3个端口
分别是 1085(PAC server)，1080(Sock Proxy) 和 1087(HTTP Proxy)

`V2rayU    15715 <my user name>   13u  IPv4 0xb7bdafbcb2134a99      0t0  TCP localhost:1085 (LISTEN)
V2rayU    15715 <my user name>   20u  IPv6 0xb7bdafbca7403871      0t0  TCP localhost:1085 (LISTEN)
v2ray     35698 <my user name>    6u  IPv4 0xb7bdafbcb319f0d1      0t0  TCP localhost:1080 (LISTEN)
v2ray     35698 <my user name>    8u  IPv4 0xb7bdafbcb7d30461      0t0  TCP localhost:1087 (LISTEN)`

在我出问题的时候，1080 端口被其他程序占用。
输出信息的第二列为进程号（PID）。
通过 `ps -ef  | grep <PID>` 查询是什么程序占用了端口。（我的情况是酸酸乳的客户端不知为何启动了，然后占用了1080 端口）。

另外一个验证方法是在 V2rayU 菜单中选择查看日志，看看到底爆什么错。
可能会看到 `failed to listen TCP on` 的日志。

**Comment by HOMHOG** [comment]
> 发现原因了。 Sock Proxy 端口被占用，导致无法正常启用。
> V2rayU 的 PAC 文件指定的是 Sock Proxy 的地址，所以无法正常上网。
> 
> 如何验证：
> 
> 在终端运行 `sudo lsof -PiTCP -sTCP:LISTEN` , 正常情况下应该会看到 V2rayU 占用3个端口
> 分别是 1085(PAC server)，1080(Sock Proxy) 和 1087(HTTP Proxy)
> 
> `V2rayU 15715 <my user name> 13u IPv4 0xb7bdafbcb2134a99 0t0 TCP localhost:1085 (LISTEN) V2rayU 15715 <my user name> 20u IPv6 0xb7bdafbca7403871 0t0 TCP localhost:1085 (LISTEN) v2ray 35698 <my user name> 6u IPv4 0xb7bdafbcb319f0d1 0t0 TCP localhost:1080 (LISTEN) v2ray 35698 <my user name> 8u IPv4 0xb7bdafbcb7d30461 0t0 TCP localhost:1087 (LISTEN)`
> 
> 在我出问题的时候，1080 端口被其他程序占用。
> 输出信息的第二列为进程号（PID）。
> 通过 `ps -ef | grep <PID>` 查询是什么程序占用了端口。（我的情况是酸酸乳的客户端不知为何启动了，然后占用了1080 端口）。
> 
> 另外一个验证方法是在 V2rayU 菜单中选择查看日志，看看到底爆什么错。
> 可能会看到 `failed to listen TCP on` 的日志。

是的啊 我把pac文件里的socks代理端口换掉就ok了
