### ISSUE TITLE
无法科学上网

### ISSUE THREAD

**Issue by Diiiiiiiiiiiii** [yanue/V2rayU#316]
MAC版本：10.15.2 (19C57) V2rayU版本1.5.1
同样节点IOS PC可以正常使用
Pac模式无效，全局模式网络无法使用
日志：
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by Aaronwang81** [comment]
端口被占用，干掉占端口的进程再启动。

**Comment by lvxianchao** [comment]
换个端口

**Comment by yanue** [comment]
试下2.0,再出现换端口
