### ISSUE TITLE
apple news 怎么pac 走代理？

### ISSUE THREAD

**Issue by freedomandcourage** [yanue/V2rayU#318]
目前的情况是apple news 在pac 模式下无法连接！

请问，怎么参考这篇文章，我想把苹果地图和apple news 走pac 代理，这样地图就不走高德，且apple news 可以载入。
https://chua.pro/unlock-apple-news-regional-restrictions/ 按照这篇文章，我应该吧这个 gspe1-ssl.ls.apple.com 加入 pac proxy ，请问怎么操作，@yanue 可否把pac 编辑改为直接文本修改模式，如v2ray X 的操作逻辑？ 那样就太好了！谢谢

**Comment by yanue** [comment]
可以在设置->pac里面手动编辑文本
