### ISSUE TITLE
V2rayU和Windows的V2RAYN差距很大

### ISSUE THREAD

**Issue by LEO1990CQ** [yanue/V2rayU#319]
在同一网络环境下，我的Windows电脑使用V2RAYN看油管4K视频基本秒开，中间很少出现卡顿，但是我的MACBOOKPro使用V2rayU大部分时间只能看看1080P的视频，而且还很卡，但是有时候又能开4K，但是速度还是与Windows的有差距

**Comment by mqliutie** [comment]
我遇到的问题是总断开连接, 但是手机端小火箭访问没问题

**Comment by yanue** [comment]
下载2.0试下
