### ISSUE TITLE
v2ray config not found

### ISSUE THREAD

**Issue by antergone** [yanue/V2rayU#32]
版本：1.2.0

错误提示：start v2ray fail: v2ray config not found

/Applications/V2rayU.app/Contents/Resources/config.json 这个文件确实不存在，重新安装也不会自动生成。

**Comment by antergone** [comment]
@yanue 权限 777给了。顶部没有图标，但是进程还在。

**Comment by libercata** [comment]
同遇到问题，似乎是因为添加服务器时出了问题

**Comment by phoenixgao** [comment]
同问题，提示 config not found 以后顶部无图标（但是有进程），无法添加配置

**Comment by dominicing** [comment]
同样的问题，有解决的吗？没有图标，有进程。

**Comment by yanue** [comment]
近期更新

**Comment by yanue** [comment]
已经修复:  https://github.com/yanue/V2rayU/releases/tag/1.2.1
