### ISSUE TITLE
查看了V2ray的文档，对ss支持的加密方式只有这几种，但是我看代码里面的加密方式和文档不一样

### ISSUE THREAD

**Issue by chiseller** [yanue/V2rayU#322]
文档地址：
https://www.v2ray.com/chapter_02/protocols/shadowsocks.html

加密方式（其中 AEAD 加密方式在 V2Ray 3.0 中加入）：

1. aes-256-cfb
2. aes-128-cfb
3. chacha20
4. chacha20-ietf
5. aes-256-gcm
6. aes-128-gcm
7. chacha20-poly1305 或称 chacha20-ietf-poly1305

**Comment by yanue** [comment]
#322

**Comment by yanue** [comment]
v2ray本身只支持这些, 我代码实现了ssr的,但是没用

**Comment by ElfSundae** [comment]
@yanue  我刚试用 V2rayU 这个软件，也遇到了 SSR 不能用的问题，想问下是只支持原版 SS 呢还是只支持部分 SSR 混淆？如果不支持 SSR 的话，是不是应该把 ssr 的 scheme 删掉？同时安装 V2rayU 和其他 SSR 客户端时，ssr://  url 的默认打开程序可能就变成 V2rayU 了。
![image](https://user-images.githubusercontent.com/526008/76150910-19d19200-60ea-11ea-830d-3134b36d3263.png)

**Comment by phyzhenli** [comment]
> 文档地址： https://www.v2ray.com/chapter_02/protocols/shadowsocks.html
> 
> 加密方式（其中 AEAD 加密方式在 V2Ray 3.0 中加入）：
> 
> 1. aes-256-cfb
> 2. aes-128-cfb
> 3. chacha20
> 4. chacha20-ietf
> 5. aes-256-gcm
> 6. aes-128-gcm
> 7. chacha20-poly1305 或称 chacha20-ietf-poly1305

aes-256-cfb 已经不能用了。
