### ISSUE TITLE
需要内网分享代理功能

### ISSUE THREAD

**Issue by mengdodo** [yanue/V2rayU#324]
之前在v2rayX上面有一个 Share Over LAN的功能，可以分享代理的端口给虚拟机内的系统使用，用着很方便，希望V2rayU能有，谢谢。

![WX20191220-093412](https://user-images.githubusercontent.com/21698573/71222557-ee6db100-230b-11ea-8027-e72df4a8ef7b.png)

**Comment by cloverkits** [comment]
哈哈 我刚才也提了一个 Issue 没注意看已经有人提出这个问题了

**Comment by yanue** [comment]
see #331
