### ISSUE TITLE
是否有切换模式的快捷键

### ISSUE THREAD

**Issue by litangyu** [yanue/V2rayU#325]
实在是没找到怎么用快捷键切换PAC、全局、手动模式... 求助！

**Comment by litangyu** [comment]
还有就是手动模式具体怎么用呢...

**Comment by bringtree** [comment]
+1

**Comment by brownhuang163** [comment]
I really appreciate your excellent work for this project, I really hope some shortcut would be an add-on for the client. I'm really thankful for your unselfishness.

**Comment by yanue** [comment]
已修复,请下载2.0.0

**Comment by bringtree** [comment]
@yanue  你好，希望快捷键可以自定义。目前的command+T 这个是好多软件的常用快捷键 会出现冲突。比如Chrome的 新建页面  各种代码编辑器的新建页面
