### ISSUE TITLE
1.5.1

### ISSUE THREAD

**Issue by imrbg** [yanue/V2rayU#326]
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: /private/var/folders/4k/ptm7pbn52tj4xbd_606nn54m0000gn/T/AppTranslocation/0F721151-0A89-4D95-A901-2F47BCFABC23/d/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/confloader/external: config file not readable > open /private/var/folders/4k/ptm7pbn52tj4xbd_606nn54m0000gn/T/AppTranslocation/0F721151-0A89-4D95-A901-2F47BCFABC23/d/V2rayU.app/Contents/Resources/config.json: no such file or directory

**Comment by yanue** [comment]
下载2.0
