### ISSUE TITLE
mac book pro 网络设置自动代理疑问 pac模式无法生效

### ISSUE THREAD

**Issue by RichardLiu0926** [yanue/V2rayU#327]
![截图](https://i.loli.net/2019/12/24/mGfE89Kkp7zFqJ1.jpg)

这项配置描述需要.pac结尾文件 但工具提供的是http://127.0.0.1:11085/pac/proxy.js  

最后结果就是pac模式不能正常使用

**Comment by Ray-Y0ung** [comment]
same problem

**Comment by littlebox692** [comment]
> ![截图](https://camo.githubusercontent.com/0c303e46e7e0a3d8286ee9ac1d6cb87182ab7662/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31322f32342f6d47664538394b6b70377a46714a312e6a7067)
> 
> 这项配置描述需要.pac结尾文件 但工具提供的是http://127.0.0.1:11085/pac/proxy.js
> 
> 最后结果就是pac模式不能正常使用

请问你现在解决了么？我也是一样的，pac模式就不行

**Comment by RichardLiu0926** [comment]
> > ![截图](https://camo.githubusercontent.com/0c303e46e7e0a3d8286ee9ac1d6cb87182ab7662/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31322f32342f6d47664538394b6b70377a46714a312e6a7067)
> > 这项配置描述需要.pac结尾文件 但工具提供的是http://127.0.0.1:11085/pac/proxy.js
> > 最后结果就是pac模式不能正常使用
> 
> 请问你现在解决了么？我也是一样的，pac模式就不行

并没有解决

**Comment by charmingYouYou** [comment]
我之前用别的vpn导致了这个问题, 重新装了一下就好了

**Comment by valasco** [comment]
这软件的pac模式就是有问题~只能全局！

> > > ![截图](https://camo.githubusercontent.com/0c303e46e7e0a3d8286ee9ac1d6cb87182ab7662/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31322f32342f6d47664538394b6b70377a46714a312e6a7067)
> > > 这项配置描述需要.pac结尾文件 但工具提供的是http://127.0.0.1:11085/pac/proxy.js
> > > 最后结果就是pac模式不能正常使用
> > 
> > 
> > 请问你现在解决了么？我也是一样的，pac模式就不行
> 
> 并没有解决

**Comment by yanue** [comment]
#195
