### ISSUE TITLE
一直显示端口被占用

### ISSUE THREAD

**Issue by trcat** [yanue/V2rayU#328]
一直显示端口被占用，但是用 `sudo lsof -i` 方式监听显示没有被多个地方占用

**Comment by misa527528** [comment]
遇到同样的问题

**Comment by LYY** [comment]
+1，一样的问题。`lsof`查不到占用的程序，改端口号也没用。

```
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 2080 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:2080 > listen tcp 127.0.0.1:2080: bind: address already in use
```

**Comment by misa527528** [comment]
po一下我的解决过程：
先用`lsof -i`查看端口号被哪个线程占用；然后用`ps -p`查看线程的具体情况——了解到是被小火箭🚀的启动文件占用了，根据提示找到小火箭🚀的一个配置文件，因为小火箭已经卸载了，删除；重启；V2Ray正常了

**Comment by yanue** [comment]
有可能是配置里面出现重复端口

**Comment by aschenmaker** [comment]
也出现了一样的情况privoxy占用了1087端口

**Comment by yanue** [comment]
下载2.0.0试下

**Comment by hcw2175** [comment]
> po一下我的解决过程：
> 先用`lsof -i`查看端口号被哪个线程占用；然后用`ps -p`查看线程的具体情况——了解到是被小火箭🚀的启动文件占用了，根据提示找到小火箭🚀的一个配置文件，因为小火箭已经卸载了，删除；重启；V2Ray正常了

--------------
有用，感谢。

**Comment by Maple13** [comment]
> ps -p

有用，问题一致

**Comment by 827652549** [comment]
> po一下我的解决过程：
> 先用`lsof -i`查看端口号被哪个线程占用；然后用`ps -p`查看线程的具体情况——了解到是被小火箭🚀的启动文件占用了，根据提示找到小火箭🚀的一个配置文件，因为小火箭已经卸载了，删除；重启；V2Ray正常了

有用，我这边MacOS通过Tecent Lomon卸载小火煎并一键清理相关配置文件，然后重启，简单省事～
