### ISSUE TITLE
MacOS10.14.6 yanue.v2rayu.v2ra一直在后台重启

### ISSUE THREAD

**Issue by HanMs** [yanue/V2rayU#329]
Dec 26 15:00:51 NahuhMBP15 com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core[806]): Service exited with abnormal code: 78
Dec 26 15:00:51 NahuhMBP15 com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

![image](https://user-images.githubusercontent.com/23276165/71463302-e1abfa00-27f0-11ea-93f0-af842f296656.png)

**Comment by yanue** [comment]
请确保 V2rayU.app是在applications目录
