### ISSUE TITLE
建议增加局域网(LAN)代理共享功能！

### ISSUE THREAD

**Issue by cloverkits** [yanue/V2rayU#331]
之前使用 `V2RayX` 的时候有这个功能将 `Socks` 代理共享到 LAN 中供其他设备使用
因为很多时候使用虚拟机系统再重新安装一个 `V2Ray` 有点不方便
我一般都是设置 ALL_PROXY 的代理为宿主机的 [IP:Sockst Port]

**Comment by ishare20** [comment]
把服务器配置文件的127.0.0.1改为0.0.0.0，然后重启软件就可以了

**Comment by yanue** [comment]
请到设置中修改local sock listen host为: 0.0.0.0

**Comment by cloverkits** [comment]
@yanue 感谢 问题已解决
