### ISSUE TITLE
怎样添加自定义pac规则

### ISSUE THREAD

**Issue by itcaiyide** [yanue/V2rayU#335]
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
btbtt.me##selector

试了好几种都不行，不知道该怎么写才生效

**Comment by qzi** [comment]
> ! Put user rules line by line in this file.
> ! See https://adblockplus.org/en/filter-cheatsheet
> btbtt.me##selector
> 
> 试了好几种都不行，不知道该怎么写才生效

你找到答案了吗？ 我是试了

> amazonaws.com##selector
interactivebrokers.com##selector
ibllc.com##selector

也不知道有效不

**Comment by J1uT0ng** [comment]
`! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
test.com
||test.com`
试试这样

**Comment by yanue** [comment]
这个请看相关文档
