### ISSUE TITLE
ping.cloud.tencent.com直联很慢

### ISSUE THREAD

**Issue by usufu** [yanue/V2rayU#337]
用v2rayU，配置好规则，国内直联，发现打开http://ping.cloud.tencent.com连接比较慢，要10s，日志显示也是直联，请大佬试一下。不知道卡在哪里了。就这个国内网址访问慢，其他正常，不知道原因。
大佬可以访问试试。

**Comment by yanue** [comment]
试下2.0.0

**Comment by usufu** [comment]
里面的默认路由配置不合适，配置bypass国内和局域网地址不起作用。
你软件生成的如下：
"routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "outboundTag": "direct",
          "type": "field",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ],
          "domain": [
            "geosite:cn"
          ]
        }
      ]
    }
  },

官方给的例子：
"routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }

rules是两个数组，每个元组里面都要设定type和outboundtag，否则好想不起作用。
