### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ilovebamboo** [yanue/V2rayU#339]
![image](https://user-images.githubusercontent.com/6214084/71663243-57830900-2d8f-11ea-9586-dcd7520a5e5f.png)
这个是什么原因 OS 10.15 Beta版(19A582a) XCODE Version 10.1 (10B61)

**Comment by ilovebamboo** [comment]
[https://cdn.jsdelivr.net/gh/ilovebamboo/allimgs@master/uPic/DDHaYt.png](url)

**Comment by ilovebamboo** [comment]
https://cdn.jsdelivr.net/gh/ilovebamboo/allimgs@master/uPic/DDHaYt.png

**Comment by ilovebamboo** [comment]
有没有定制客户端的
有没有定制客户端的，提供API想做个带登录功能的
我TG号：https：//t.me/Superx007

**Comment by yanue** [comment]
https：//t.me/yanue 
yanue at outlook.com
