### ISSUE TITLE
user-rules 文件在哪里保存？

### ISSUE THREAD

**Issue by wangjunwei87** [yanue/V2rayU#34]
`ShadowSocksX-NG` 会把 `gfwlist` 和 `user-rule.txt` 保存到 `~/.ShadowsocksX-NG/`, 我个人把这个目录初始化成一个 git 仓库，便于做备份和版本控制。

V2rayU 没有找到相关文件在哪儿。

**Comment by yanue** [comment]
点击V2rayU图标->Edit User Rules for Pac

**Comment by yanue** [comment]
最终文件地址: /Applications/V2rayU.app/Contents/Resources/pac/user-rule.txt

**Comment by wangjunwei87** [comment]
@yanue 怎么编辑我是知道的，建议像 shadowsocks 那样把配置文件放在 ~/.v2rayu 目录，因为这些配置是和用户相关的，目前的这种设计，V2rayU 一升级版本，用户自定义规则就丢失了。

**Comment by yanue** [comment]
额 是有这个问题

**Comment by yanue** [comment]
@wangjunwei87 文件位置不变,增加存储到UserDefaults保证升级版本不会丢失
