### ISSUE TITLE
建议：加个“端口转发”  

### ISSUE THREAD

**Issue by Justsoos** [yanue/V2rayU#340]
现在各种FQ协议多不胜数，基本上都在本地/局域网开不同端口-- http 或者 socks5，用端口转发terminal后台运行命令行等等方法，不容易控制也不直观，如果能在 v2rayU 的协议里，除了 socks 和 vmess ，ss， 再加个端口转发就方便多了。

**Comment by yanue** [comment]
暂不考虑

**Comment by cc978** [comment]
可以用来转发 trojan，ssr，pingtunel，等等其他程序的代理端口，短期内又不可能v2rayU开发的，又不用修改v2rayU的主工具地位和 pac 一些设置，可以考虑啊
