### ISSUE TITLE
重启电脑后突然用不了了

### ISSUE THREAD

**Issue by iamdeity** [yanue/V2rayU#342]
重启电脑后突然用不了了

**Comment by ONEokDAMON** [comment]
偏好设置里面, 设置端口, 1188或者其他的, 我经常重启无法使用, 每次重新配置一下端口即可

**Comment by iamdeity** [comment]
果然可以，谢谢



---原始邮件---
发件人: "Damon Wade"<notifications@github.com&gt;
发送时间: 2020年1月13日(星期一) 上午10:14
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"iamdeity"<3048155352@qq.com&gt;;
主题: Re: [yanue/V2rayU] 重启电脑后突然用不了了 (#342)



偏好设置里面, 设置端口, 1188或者其他的, 我经常重启无法使用, 每次重新配置一下端口即可

**Comment by hexiaowu** [comment]
> 重启电脑后突然用不了了

试试改成1080，我今天也是重启就不行了，看了下端口，默认是1087，改成1080就可以了

**Comment by yanue** [comment]
下2.0.0试下
