### ISSUE TITLE
订阅之后无法翻墙。

### ISSUE THREAD

**Issue by Maonier666** [yanue/V2rayU#343]
在公司电脑可以正常使用（有线连接）
自己家的电脑没办法翻墙（wifi）

**Comment by Hgexia** [comment]
同样情况，显示连接，也能ping通，就是无法翻墙，ShadowsocksX-NG-R8正常

**Comment by Maonier666** [comment]
> 同样情况，显示连接，也能ping通，就是无法翻墙，ShadowsocksX-NG-R8正常

头疼

**Comment by w-tim** [comment]
一样，看了日志说是加密方法rd4-md5无法识别，认为只是因为iplc提供了低等级的加密方式所致，后来发现中继连接提供的aes-128-gcm同样无法成功，而ShadowsocksX-NG-R8正常。

**Comment by yanue** [comment]
#322
