### ISSUE TITLE
vmess tls 配置，订阅后 serverName 为空，导致不能连接

### ISSUE THREAD

**Issue by chunyu-zhou** [yanue/V2rayU#346]
vmess tls 配置，订阅后 serverName 为空，导致不能连接。
配置如下
`{
  "v": "2",
  "ps": "Test",
  "add": "xxxx.xxx.xxx", // 服务器地址，是域名
  "port": "443",
  "id": "fcb10739-a3bd-39fb-8f4d-86bcdf5eeb0d",
  "aid": "2",
  "net": "ws",
  "type": "none",
  "host": "x'x'x.xxx.xxx", // tls 域名
  "path": "/v2ray",
  "tls": "tls"
}`

**Comment by yanue** [comment]
你手动将serverName填写成add值试下? 这块没试过,不确定要填写啥
