### ISSUE TITLE
提示已经开启但是看不到主程序

### ISSUE THREAD

**Issue by qwazx** [yanue/V2rayU#35]
软件已经打开，但是看不到界面，托盘图标也没有。点击APP也没有反应，尝试通过命令行手动启动也无效……

目前没搞定，不知道什么原因

**Comment by yanue** [comment]
![image](https://user-images.githubusercontent.com/1435250/53137962-b26ca100-35bf-11e9-9fcb-07059b8de8c3.png)
正常启动有两个进程,kill掉重试

**Comment by qwazx** [comment]
我卸载了重装搞定了……感谢帮助
