### ISSUE TITLE
gfwlist的地址在退出v2rayU后会恢复默认

### ISSUE THREAD

**Issue by jiajudu** [yanue/V2rayU#355]
在Preferences>Pac中, 把默认的GFWList URL替换成另一个URL, 然后点击Save and Update Pac from GFWList List后可以正确的更新pac, 但是重启v2rayU后GFWList URL会恢复成默认的https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by yanue** [comment]
已修复,请下载2.0.0
