### ISSUE TITLE
[Glitch] 1.5.1 更新pac导致发生程序退出

### ISSUE THREAD

**Issue by jasonlovescoding** [yanue/V2rayU#356]
OS: Mac OS High Sierra
V2rayU Version: 1.5.1
操作: 在偏好设置-pac中，将gfw list url改为
https://raw.githubusercontent.com/gfwlist/tsilwfg/master/tsilwfg.txt
后点击save and update pac from gfw list
程序会自动退出，没有报错或者崩溃提示

**Comment by yanue** [comment]
没测试出来
