### ISSUE TITLE
如何完全卸载？

### ISSUE THREAD

**Issue by iseesec** [yanue/V2rayU#358]
卸载后，日志一直报错如下：

Jan 30 00:09:49 xiaoz com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core[2997]): Service exited with abnormal code: 78
Jan 30 00:09:49 xiaoz com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 30 00:09:49 xiaoz com.apple.xpc.launchd[1] (yanue.v2rayu.http[2996]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/V2rayU.app/Contents/Resources: 19D76: xpcproxy + 14893 [673][F168B004-7C3C-33AD-8EA9-EF5E7F784A63]: 0x2

**Comment by yanue** [comment]
请参考首页
