### ISSUE TITLE
Mac OS 升级/重启后不能正常访问外网

### ISSUE THREAD

**Issue by l362944795** [yanue/V2rayU#362]
之前用Shadowsocks也有类似的情况 查看日志显示的是：Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 
尝试把本地端口从1087换到1188后就可以正常使用了
![Screen Shot 2020-02-02 at 9 37 56 PM](https://user-images.githubusercontent.com/53050675/73609000-53534100-4604-11ea-9ff5-bf07a81225ef.png)

**Comment by JoeV587** [comment]
同样的问题
Mac 升级10.15.3 后
ailed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by verck** [comment]
1087端口被占用了啊，换一个就正常了。
不知道被哪个程序占用了

**Comment by aschenmaker** [comment]
我也出现了一样的问题

**Comment by yanue** [comment]
请下载2.0试下

**Comment by bobyhands** [comment]
同上改了端口仍旧没用

**Comment by 1030448095** [comment]
> 之前用Shadowsocks也有类似的情况查看日志显示的是：无法启动v2ray.com/core/app/proxyman/inbound：无法在1087上尝试侦听TCP尝试将
> 本地端口从1087转换为1188后就可以正常使用了
> ![截屏2020-02-02,9 37 56 PM](https://user-images.githubusercontent.com/53050675/73609000-53534100-4604-11ea-9ff5-bf07a81225ef.png)

谢谢你的指南，我现在能够正常使用外网
