### ISSUE TITLE
http proxy 不能监听 0.0.0.0

### ISSUE THREAD

**Issue by sunznx** [yanue/V2rayU#365]
填了 0.0.0.0 还是监听的 127.0.0.1

**Comment by playniuniu** [comment]
同样的问题，想恭喜给局域网做连接，实现不了

**Comment by yanue** [comment]
我这边测试没问题,请看v2ray日志的监听状态:
020/02/10 00:35:18 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 0.0.0.0:1080
2020/02/10 00:35:18 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 0.0.0.0:1087
2020/02/10 00:35:18 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:1080
2020/02/10 00:35:18 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 0.0.0.0:1080
2020/02/10 00:35:18 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:1087
