### ISSUE TITLE
希望能修正以避免调用独立显卡增加耗电

### ISSUE THREAD

**Issue by DanistyWuKids** [yanue/V2rayU#368]
用了几天，总体来说觉得不错，但是突然发现拔掉电池后用的时间太短了，经过gfxCardStatus查询后，发现程序可能意外调用了独显 （因为现在Mac已经不允许软件控制独显和集显的调用权），所以希望能排查源代码看看有没有可能设计到调用独显的库？[Apple Developer Ref](https://developer.apple.com/library/archive/qa/qa1734/_index.html)

**Comment by yanue** [comment]
本身代码是没有的,用到的库就不清楚了
