### ISSUE TITLE
因Port的默认设定，导致无法使用

### ISSUE THREAD

**Issue by nn791300** [yanue/V2rayU#37]
节点无法使用，改了很多东西最终发现是port的问题
Locatl http setting port 的默认设定是1086，但是1086无法联网，改成1087就可以了
家里的和公司的电脑都测试了下，默认都是1086，改号码后就都正常了。
另外还有个小问题，在开关打开的过程中，无法更改配置，关掉开关后才可以。
比心~

![35601551674412_ pic](https://user-images.githubusercontent.com/33647845/53710983-e32fbe80-3e7a-11e9-9c7e-49ca5a0d17dd.jpg)

**Comment by HebrewWolf** [comment]
any reason?

**Comment by yanue** [comment]
默认值是1086,如果没有被占用的话 应该是可以用的

**Comment by yanue** [comment]
@nn791300 在开关打开的过程中，无法更改配置，关掉开关后才可以。怎么操作的啊,我这边没测出来问题
