### ISSUE TITLE
每次启动应用都要输入系统的用户密码

### ISSUE THREAD

**Issue by jolay2892** [yanue/V2rayU#370]
每次打开/退出应用，都会弹框要求输入用户密码，猜测应该是调用修改系统网络设置的接口引起的，即使代理设置了手动模式也还是会弹框。可以启动和退出的时候判断下“手动模式”就不去修改系统网络设置吗？

因为我本地有多个代理软件再跑，只能用SwitchyOmega一类的手动控制，如果每次启动都会改系统网络设置的话，会很乱。

有2种弹框 每次都会弹
![image](https://user-images.githubusercontent.com/60792772/74080679-b8ce8400-4a81-11ea-9560-2908490b8957.png)
![image](https://user-images.githubusercontent.com/60792772/74080692-d1d73500-4a81-11ea-87c7-67db66a4b045.png)

**Comment by yanue** [comment]
请下载2.0.0 或 拖动到 applications 目录

**Comment by jolay2892** [comment]
感谢回复， 我试了2.0.0版本，也确认是/Applications目录了，但还是有这个问题
