### ISSUE TITLE
在同一网络下使用同一节点，安卓SSRR可以正常上网但是v2rayU却连不上

### ISSUE THREAD

**Issue by note4** [yanue/V2rayU#374]
设备配置应该是没有问题的，那区别就系统不一样，使用软件不同，网络和节点都是一样的。

**Comment by Hanseltu** [comment]
遇到一样的问题~

**Comment by Bearin** [comment]
同一个节点用其它客户端正常
`A unified platform for anti-censorship.
main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: rc4-md5`

**Comment by yanue** [comment]
v2ray 原始不支持 rc4-md5 等
