### ISSUE TITLE
启动无法上网

### ISSUE THREAD

**Issue by mumudm** [yanue/V2rayU#377]
错误日志为
```
2020/02/10 16:17:15 [Warning] [3056301536] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > malformed HTTP request "\x05\x01\x00"
```
- OS系统：10.15.3
- v2rayU: 2.0.0
手机上节点是可以使用的，不知道原因是啥，无法解决，求指导

**Comment by chenchunyang12345** [comment]
一样的问题

**Comment by gordonCN** [comment]
我的是这个。。。 也是连不上外网
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by mumudm** [comment]
我的问题，发现了公司的 vpn 在一直后台运行，关掉就好了😂
