### ISSUE TITLE
failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

### ISSUE THREAD

**Issue by Hanseltu** [yanue/V2rayU#378]
你好，这两天一直是这个情况，无法上网。以为是旧版问题，更新到了最新的2.0.0，把相应的文件也删除并重新安装了，我看日志报的是以上错误，希望这个日志可以帮到你，谢谢~

系统:Mac OS 10.15.3

详细日志信息如下

`
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
2020/02/10 17:37:23 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/02/10 17:37:23 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
`

**Comment by Hanseltu** [comment]
按照 #362  更改端口后，log信息如下：

`
020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients4.google.com:443
2020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/app/dispatcher: sniffed domain: clients4.google.com
2020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
2020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:13.94.61.66:443
2020/02/10 17:52:34 tcp:127.0.0.1:49575 accepted tcp:clients4.google.com:443 [proxy] 
2020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:13.94.61.66:443
2020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 224 but actually 40
2020/02/10 17:52:34 [Info] [2598314807] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/proxy/socks: TCP Connect request to tcp:accounts.google.com:443
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/app/dispatcher: sniffed domain: accounts.google.com
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/app/dispatcher: default route for tcp:accounts.google.com:443
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:13.94.61.66:443
2020/02/10 17:52:34 tcp:127.0.0.1:49577 accepted tcp:accounts.google.com:443 [proxy] 
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:accounts.google.com:443 via tcp:13.94.61.66:443
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.googleapis.com:443
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/app/dispatcher: sniffed domain: www.googleapis.com
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/app/dispatcher: default route for tcp:www.googleapis.com:443
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:13.94.61.66:443
2020/02/10 17:52:34 tcp:127.0.0.1:49579 accepted tcp:www.googleapis.com:443 [proxy] 
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 246 but actually 176
2020/02/10 17:52:34 [Info] [1009565079] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:13.94.61.66:443
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 237 but actually 64
2020/02/10 17:52:34 [Info] [3356978787] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
`

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0
