### ISSUE TITLE
MacOS 1087 端口占用

### ISSUE THREAD

**Issue by hywu091** [yanue/V2rayU#380]
MAC OS 10.15.3 使用2.0版本V2rayU无法连接的问题

failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

修改端口1087为1188后解决。

**Comment by Hanseltu** [comment]
你好，修改完还是不能连接上诶，见 #378，你改完就连上了吗？

**Comment by hywu091** [comment]
> 你好，修改完还是不能连接上诶，见 #378，你改完就连上了吗？

你好，我是改完就连上了的，google，youtube正常使用...

**Comment by Hanseltu** [comment]
好的，多谢，我再试试~ @hywu091

**Comment by Hanseltu** [comment]
还是不行，log 和 #378 后面的是一样的，难受，，，

**Comment by tpnet** [comment]
继续改端口，socket改成1188,http端口改成1189 @Hanseltu

**Comment by Hanseltu** [comment]
多谢 @tpnet，试过了，还是不行。服务器在手机和iPad上都能用，应该不是服务器的问题。

**Comment by tpnet** [comment]
没有说服务器问题，我说是改高级设置里的端口 @Hanseltu 
![image](https://user-images.githubusercontent.com/17380722/74317261-0ca8d800-4db6-11ea-9fbb-fc4f96a991cb.png)

**Comment by Hanseltu** [comment]
我是按照这个改的高级设置，log报错 `failed to process outbound traffic` @tpnet

**Comment by bobyhands** [comment]
> 没有说服务器问题，我说是改高级设置里的端口 @Hanseltu
> ![image](https://user-images.githubusercontent.com/17380722/74317261-0ca8d800-4db6-11ea-9fbb-fc4f96a991cb.png)

这个解决了，原来vray默认把socket和http监听端口设为了同一个

**Comment by imlinchun** [comment]
同样的问题，解决了

**Comment by YonggenZhang** [comment]
> 我是按照这个改的高级设置，log报错 `failed to process outbound traffic` @Hanseltu 

我也遇到相同的问题， 我按下面的链接在Chrome无痕/隐身模式下可以用， 可能不是端口的问题。但是在chrome 普通模式下还是不能用。如果你找到解决办法，请共享一下。 

链接： https://github.com/v2ray/v2ray-core/issues/1676

调试了一整天，总算定位到了问题的关键所在，应该是一些无良主机商的坑，对某些大小的MTU包莫名其妙的丢弃了。解决方案如下：

用Chrome无痕/隐身模式看看打开网页是否正常？
如果正常，用ifconfig调整服务端MTU值为1280以下，越小越好
Enjoy

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0
