### ISSUE TITLE
关于新增的路由功能如何使用的问题

### ISSUE THREAD

**Issue by iEveQ** [yanue/V2rayU#382]
请问，新增的路由功能，如果我选用域名策略IPifNonMatch，路由模式选用绕过大陆和局域网，是不是可以达到和PAC差不多的功能呢？PAC和全局模式这里我该怎么选？为什么我设置了路由功能却没有效果呢

**Comment by biaogeg** [comment]
域名策略IPifNonMatch，路由模式选用绕过大陆和局域网。选全局模式，再检查其他代理软件有没有关掉

**Comment by iEveQ** [comment]
> 域名策略IPifNonMatch，路由模式选用绕过大陆和局域网。选全局模式，再检查其他代理软件有没有关掉

找到原因了，配置里没有写    
{
      "tag": "direct",
      "protocol": "freedom",
      "settings": null
}
