### ISSUE TITLE
2.0 failed to listen on address: 127.0.0.1:1087，address already in use

### ISSUE THREAD

**Issue by zhouchang2017** [yanue/V2rayU#385]
```
127.0.0.1:1087: bind: address already in use
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
```

**Comment by hjyhj-lzz** [comment]
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
怎么解决这个问题

**Comment by zhouchang2017** [comment]
@hjyhj-lzz 我试着多改了几次端口，已经正常可用了。
![image](https://user-images.githubusercontent.com/28501146/74401526-7e3b6180-4e5c-11ea-9349-340023deaa89.png)

**Comment by zhongjun96** [comment]
同一个情况，mac，检查1087端口占用。我这边是privoxy服务占用了1087端口，检查是ShadowsocksX-NG-R8 该应用组件，卸载该应用，重启即可

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0

**Comment by TomYule** [comment]
2.1.0我还是出现这样的问题
1087改成1089就解决了

**Comment by j1an9w8** [comment]
我 v3.3.0也这样 不过改了上面说的端口就行了 感谢！
