### ISSUE TITLE
路由设置无效

### ISSUE THREAD

**Issue by 1217950746** [yanue/V2rayU#386]
当前设置为全局模式，路由设置直连 icloud.com，但是还是会被代理，对比了 Window 版的 v2rayN 发现生成的配置不太一样，v2rayN 可以正常使用

<img width="650" alt="image" src="https://user-images.githubusercontent.com/7909582/74306651-11fa2880-4d9e-11ea-92e9-ad57b0964d30.png">

**Comment by Daniel-scx** [comment]
+1 并且PAC也变成了全局模式

**Comment by ljh740** [comment]
+1 感觉是bug

**Comment by alphaqiu** [comment]
不支持geoip:cn,geoip:private

**Comment by cnBruceHong** [comment]
@yanue +1

**Comment by nbjwl** [comment]
It's a bug. 
Domain and ip should be seperated in different rule. See :https://toutyrater.github.io/basic/routing/notice.html
"rules": [
        {
          "outboundTag": "direct",
          "type": "field",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ]
	},
	{
	  "outboundTag": "direct",
          "type": "field",
          "domain": [
	    "geosite:microsoft",
            "geosite:apple",
            "geosite:cn"
          ]
        }
      ]

**Comment by yanue** [comment]
![image](https://user-images.githubusercontent.com/1435250/75629048-b0e5a800-5c19-11ea-84af-5cb93abdd2a1.png)
![image](https://user-images.githubusercontent.com/1435250/75629058-cce94980-5c19-11ea-8bb1-cff0444353c3.png)
![image](https://user-images.githubusercontent.com/1435250/75629066-dc689280-5c19-11ea-965d-6b2f25aff518.png)

**Comment by yanue** [comment]
全局模式和路由中的全局是两个东西

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0
