### ISSUE TITLE
context canceled and closed pipe

### ISSUE THREAD

**Issue by liangling627** [yanue/V2rayU#388]
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled

v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by yanue** [comment]
去v2那里问下
