### ISSUE TITLE
更新后的Pac模式还是不能使用，还没有解决吗

### ISSUE THREAD

**Issue by muijk8246** [yanue/V2rayU#391]

**Comment by Jerry007s** [comment]
应该是端口被占用。在设置里，`Advance`中把端口号改一下，建议改成10000多

**Comment by muijk8246** [comment]
> 应该是端口被占用。在设置里，`Advance`中把端口号改一下，建议改成10000多

谢谢！已经搞定！

**Comment by tianbao666** [comment]
> 应该是端口被占用。在设置里，`Advance`中把端口号改一下，建议改成10000多

已搞定，谢谢！

**Comment by dongbingliu** [comment]
> 应该是端口被占用。在设置里，`Advance`中把端口号改一下，建议改成10000多

解决问题

**Comment by 0x0006e** [comment]
> 应该是端口被占用。在设置里，`Advance`中把端口号改一下，建议改成10000多

不行啊。还是只能全局模式上网。

**Comment by yanue** [comment]
#195

**Comment by 0x0006e** [comment]
> 应该是端口被占用。在设置里，`Advance`中把端口号改一下，建议改成10000多

https://github.com/yanue/V2rayU/issues/195#issuecomment-593279951
