### ISSUE TITLE
2.0 切换server时报无法解析config文件的错误

### ISSUE THREAD

**Issue by fantimond** [yanue/V2rayU#392]
查看log文件，具体错误信息如下：
main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: Failed to build TCP config. > v2ray.com/core/infra/conf: invalid TCP header config > v2ray.com/core/infra/conf: unknown config id: vmess

查看 /Applications/V2rayU.app/Contents/Resources/config.json，注意到下面几行:

```json
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "Vmess"
          }
        },
```
将"Vmess"手动改为"none"，可解除异常，正常使用。

**Comment by mumudm** [comment]
按你的设置改完后不报错了，但还是无法科学上网，请问还有其他问题吗，该如何修改
![image](https://user-images.githubusercontent.com/46308185/74805061-0fa74980-531d-11ea-99f5-d150d509363b.png)

**Comment by yanue** [comment]
把有问题的删除再添加试下
