### ISSUE TITLE
相同局域网下，pc手机都可以使用，就macbook不能使用，无法翻墙，我贴了日志在下面

### ISSUE THREAD

**Issue by bobyhands** [yanue/V2rayU#393]
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1088 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1088 > listen tcp 127.0.0.1:1088: bind: address already in use

无法监听，地址已经被使用？我改了端口号也没用，麻烦看看如何解决，多谢

**Comment by bobyhands** [comment]
改了端口也没用

**Comment by bobyhands** [comment]
https://github.com/yanue/V2rayU/issues/380#issuecomment-586101921

问题解决了，通过这个方法，socket和http不能使用同一端口，不知道为什么默认是同一个

**Comment by 0x0006e** [comment]
https://github.com/yanue/V2rayU/issues/195

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0
