### ISSUE TITLE
安卓和win都正常使用,但是mac不行,日志看上去有异常

### ISSUE THREAD

**Issue by maleiqaq** [yanue/V2rayU#395]
v2ray服务正常,安卓和win都可以正常使用.
mac启动v2ray后debug启动日志看上去没有异常
下面是启动日志
`
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
2020/02/14 17:40:29 [Debug] v2ray.com/core/app/log: Logger started
2020/02/14 17:40:29 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/02/14 17:40:29 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1080
2020/02/14 17:40:29 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1188
2020/02/14 17:40:29 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2020/02/14 17:40:29 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1188
2020/02/14 17:40:29 [Warning] v2ray.com/core: V2Ray 4.22.1 started
`
下面是看上去异常的日志
`
2020/02/14 18:20:49 [Info] [3719797495] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/02/14 18:20:59 [Info] [805165781] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/02/14 18:21:00 [Info] [2018578993] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/02/14 18:21:02 [Info] [2306898201] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/02/14 18:21:07 [Info] [3994755535] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/02/14 18:22:24 [Info] [444448994] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > EOF
`
系统版本是catalina 10.15.3

**Comment by jms007ll** [comment]
Mac系统时间与服务器时间看下是否一致.

**Comment by yanue** [comment]
确认下配置 去v2那边看下
