### ISSUE TITLE
最新的2.0，mac 10.15.2，无法读取config文件

### ISSUE THREAD

**Issue by xiaoxin-TOM** [yanue/V2rayU#397]
不知道为啥
 > exit status 255
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: aes-128-ctr

**Comment by xiaoxin-TOM** [comment]
v2ray.com/core/infra/conf: unknown cipher method: aes-128-ctr
似乎没有这个加密方法？？

**Comment by istraw** [comment]
我也是这样问题

**Comment by sassysparrow** [comment]
我更新后报 v2rayU config not found。曾经在1.2.0也出现过

**Comment by sassysparrow** [comment]
> 我更新后报 v2rayU config not found。曾经在1.2.0也出现过

尝试编辑配置文件 /Applications/V2rayU.app/Contents/Resources/config.json
终端反馈该文件不存在，内容为空，保存退出。相当于创建了一个新配置文件，然后v2rayU可以正常启动了，再打开该配置文件的时候，内容已经完全正常了。可以尝试下能否解决

**Comment by sassysparrow** [comment]
> 不知道为啥
> 
> > exit status 255
> > V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
> > A unified platform for anti-censorship.
> > main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unknown cipher method: aes-128-ctr

尝试编辑配置文件 /Applications/V2rayU.app/Contents/Resources/config.json
终端反馈该文件不存在，内容为空，保存退出。相当于创建了一个新配置文件，然后v2rayU可以正常启动了，再打开该配置文件的时候，内容已经完全正常了。可以尝试下能否解决

**Comment by wqj97** [comment]
同样遇到, 还会导致代理http端口错误

**Comment by pizsd** [comment]
同样遇到这个问题

**Comment by grantkuo** [comment]
me too

**Comment by iwascy** [comment]
同，希望作者能解决。

**Comment by chenApostle** [comment]
哪位大佬有没有2.0版本的config文件？

**Comment by yanue** [comment]
试下最新: https://github.com/yanue/V2rayU/releases/tag/2.1.0

**Comment by hye** [comment]
最新版仍是这个问题，怪就怪在 点击查看config.json是看的到的，
我觉得是app权限问题，有些目录是需要读取整盘的的权限的，放/Application 里 多半不行，还是建议放在`NSHomeDirectory()` application support下吧
