### ISSUE TITLE
这是为什么啊

### ISSUE THREAD

**Issue by gqm36524** [yanue/V2rayU#4]
![img_20181202_194051](https://user-images.githubusercontent.com/21172441/49339314-c3fe7680-f66a-11e8-8e56-de618a098106.jpg)

**Comment by yanue** [comment]
这个是生成配置文件失败了，有添加服务吗，也有可能是权限的问题，命令行输入
`
chmod 755 /Applications/V2rayU.app/Contents/Resources
`
然后重新启动v2ray服务
