### ISSUE TITLE
在手机和pad上都可以用的配置在mac上无法使用，刚刚更新，下面是日志。

### ISSUE THREAD

**Issue by RadyChou** [yanue/V2rayU#400]
2020/02/17 11:02:25 [Info] [3146277290] v2ray.com/core/app/dispatcher: sniffed domain: apidata.googleusercontent.com
2020/02/17 11:02:25 tcp:127.0.0.1:63988 accepted tcp:apidata.googleusercontent.com:443 [proxy] 
2020/02/17 11:02:25 [Info] [3146277290] v2ray.com/core/app/dispatcher: default route for tcp:apidata.googleusercontent.com:443
2020/02/17 11:02:25 [Info] [3146277290] v2ray.com/core/transport/internet/websocket: creating connection to tcp:tt42.ttsolate.life:18418
我怀疑是端口的问题 也效仿#380 和 #362 修改了一下 未成功

**Comment by gordonCN** [comment]
我也连不上，日志是这样
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by gordonCN** [comment]
换SS可以上网了

**Comment by liujianyu4303** [comment]
手机上小火箭正常，mac上用不了，日志如下：
``
2020/02/20 12:04:55 [Info] [2958090683] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:hk1.v2server.cf:443
2020/02/20 12:04:55 [Warning] [2958090683] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/02/20 12:04:55 [Info] [2958090683] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/20 12:05:00 [Info] [1153135939] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.googleapis.com:443
2020/02/20 12:05:00 [Info] [1153135939] v2ray.com/core/app/dispatcher: sniffed domain: www.googleapis.com
2020/02/20 12:05:00 tcp:127.0.0.1:53390 accepted tcp:www.googleapis.com:443 [proxy] 
2020/02/20 12:05:00 [Info] [1153135939] v2ray.com/core/app/dispatcher: default route for tcp:www.googleapis.com:443
2020/02/20 12:05:00 [Info] [1153135939] v2ray.com/core/transport/internet/websocket: creating connection to tcp:hk1.v2server.cf:443
2020/02/20 12:05:01 [Info] [1153135939] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:hk1.v2server.cf:443
2020/02/20 12:05:01 [Warning] [1153135939] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/02/20 12:05:01 [Info] [1153135939] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/20 12:05:09 [Info] [375315408] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.googleapis.com:443
2020/02/20 12:05:09 [Info] [375315408] v2ray.com/core/app/dispatcher: sniffed domain: www.googleapis.com
2020/02/20 12:05:09 [Info] [375315408] v2ray.com/core/app/dispatcher: default route for tcp:www.googleapis.com:443
2020/02/20 12:05:09 tcp:127.0.0.1:53392 accepted tcp:www.googleapis.com:443 [proxy] 
2020/02/20 12:05:09 [Info] [375315408] v2ray.com/core/transport/internet/websocket: creating connection to tcp:hk1.v2server.cf:443
2020/02/20 12:05:09 [Info] [375315408] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:hk1.v2server.cf:443
2020/02/20 12:05:10 [Warning] [375315408] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/02/20 12:05:10 [Info] [375315408] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/20 12:05:21 [Info] [2149254435] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients1.google.com:443
2020/02/20 12:05:21 [Info] [2149254435] v2ray.com/core/app/dispatcher: sniffed domain: clients1.google.com

**Comment by SleepyLogan** [comment]
同上，手机小火箭可用，mac用不了

**Comment by caticat** [comment]
一样的问题，mac上用不了
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: connection ends > context canceled

**Comment by yanue** [comment]
请确认配置参数是否正确,可用到v2去看下
