### ISSUE TITLE
在使用过程中会突然多一个“new server”

### ISSUE THREAD

**Issue by ctyytc** [yanue/V2rayU#401]
在使用过程中会突然多一个“new server”，所有测速结果清零，并且正在使用的服务会切到“new server”上……好奇怪

目前已经升级到2.0.0，以上问题均在最新版出现

**Comment by yanue** [comment]
睡眠过后会重新进行订阅更新和ping处理,应该是你的订阅信息获取不到了(更新订阅会删除原有数据)
