### ISSUE TITLE
v2rayU的订阅规则是什么？

### ISSUE THREAD

**Issue by shouziws** [yanue/V2rayU#402]
v2rayU的订阅规则是什么？能发出一个有效的地址或者一段base64做参考吗?

**Comment by colorwin** [comment]
我有一个订阅地址的文件是 https://nscs.357159.xyz/link/jVOheSF40WWoWOem?mu=2

```
vmess://...
vmess://...
```

经过base64的无法解析， 报 `fail:  please add Subscription Url`

在安卓，ios，window上都能解析出来的。

**Comment by shouziws** [comment]
我看了你说的报错，这应该是mac电脑v2rayU的订阅报错，不同平台的订阅规则是不同的，需要你让场主提供v2rayU的订阅专用地址

Color Win <notifications@github.com> 于2020年2月28日周五 下午5:19写道：
