### ISSUE TITLE
能否加入torjan支持

### ISSUE THREAD

**Issue by zach-1996** [yanue/V2rayU#404]
自从武昌起疫以后🧱越来越高，能否像iOS小火箭一样加入torjan支持

**Comment by TianLiAnhui** [comment]
trojan在terminal里安装好本地程序后，V2rayU用socks协议，指向服务器就行

**Comment by yanue** [comment]
#415

**Comment by jameslhc** [comment]
> trojan在terminal里安装好本地程序后，V2rayU用socks协议，指向服务器就行

亲测过么，我是这么配置的，但是trojan窗口一直报协议不识别，v2rayU这边的socks协议没有再细节的设定，不知道是什么情况
我也开了caes #447
