### ISSUE TITLE
pac模式无法访问github.com

### ISSUE THREAD

**Issue by hx2nn** [yanue/V2rayU#405]
我的网络正常无法访问github.com网站，需要开代理。但是用pac模式无法访问，需要开启全局模式才行。可否将github.com,加入pac中

**Comment by xiaohei126** [comment]
pac 设置可以手动添加规则

**Comment by tianbao666** [comment]
github在PAC里面的，我看了下的其他人的ISSUES好像Mac os 是有这个问题，pac模式不生效
你更改pac端口试试

**Comment by xiaohei126** [comment]
> github在PAC里面的，我看了下的其他人的ISSUES好像Mac os 是有这个问题，pac模式不生效
> 你更改pac端口试试

这个pac 模式里面GitHub只有部分域名加入了

**Comment by xiaohei126** [comment]
> 我的网络正常无法访问github.com网站，需要开代理。但是用pac模式无法访问，需要开启全局模式才行。可否将github.com,加入pac中

pac设置中加 github.com  重启浏览器和客户端再试试

**Comment by fuzheng1998** [comment]
PAC模式GitHub图标加载不了

**Comment by fuzheng1998** [comment]
> > github在PAC里面的，我看了下的其他人的ISSUES好像Mac os 是有这个问题，pac模式不生效
> > 你更改pac端口试试
> 
> 这个pac 模式里面GitHub只有部分域名加入了

这个怎么替换pac文件呢

**Comment by fuzheng1998** [comment]
> > github在PAC里面的，我看了下的其他人的ISSUES好像Mac os 是有这个问题，pac模式不生效
> > 你更改pac端口试试
> 
> 这个pac 模式里面GitHub只有部分域名加入了

那我更换gfwlist的url行么，换成acl4ssr这个里面的可以么

**Comment by zzzgit** [comment]
pac文件如何刪除？

**Comment by yanue** [comment]
#195

**Comment by nmsn** [comment]
+1
