### ISSUE TITLE
添加服务器SOCKS5

### ISSUE THREAD

**Issue by vinyo** [yanue/V2rayU#406]
添加服务器SOCKS5保存，然后到回去看里面填的是空的。不能对接本地的trojan。

**Comment by chrisxiao** [comment]
同遇到这个问题，看日志大概是 port 类型的处理有问题，string 转 int之类的。

**Comment by zlwu** [comment]
附议

**Comment by viquu** [comment]
同样遇到这个问题

**Comment by TomYule** [comment]
telegram SOCKS5一直设置不成功 127.0.0.1 1080
