### ISSUE TITLE
配置文件被删除

### ISSUE THREAD

**Issue by Deecyn** [yanue/V2rayU#411]
你好，在 MacOS 10.15.3 中，2.0 版本的 V2rayU 应用，安装完成后，没有了 `/Library/Preferences/net.yanue.V2rayU.plist` 和 `/Applications/V2rayU.app/Contents/Resources/config.json`
 文件，然后应用 Turn On 时报错找不到配置文件。

**Comment by grantkuo** [comment]
i have same issue

**Comment by yanue** [comment]
试下最新版: https://github.com/yanue/V2rayU/releases/tag/2.1.0
