### ISSUE TITLE
能否加上支持trojan协议

### ISSUE THREAD

**Issue by tasselx** [yanue/V2rayU#415]

**Comment by TimeBye** [comment]
这个功能真的很棒

**Comment by youzouzach** [comment]
需求trojan+1

**Comment by hupanqing** [comment]
+1

**Comment by noasquare** [comment]
+10

**Comment by eureka101v** [comment]
+1

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/issues/404#issuecomment-588389091

**Comment by TimeBye** [comment]
曲线救国确实可以，就是不好管理torjan的进程了。如果V2rayU直接支持，那肯定马上可以吸引一大批粉丝哦

**Comment by bennieniu** [comment]
需要trojan + 10086！！！！！！！！

**Comment by naplesblue** [comment]
trojan现在有多线程支持，对于自建vps来说，速度提高了不少。V2rayU秒杀各种trojan的客户端，求原生支持trojan。

**Comment by liliass** [comment]
++1 支持

**Comment by gwsh** [comment]
> trojan现在有多线程支持，对于自建vps来说，速度提高了很多。V2rayU秒杀各种trojan的客户端，求原生支持trojan。

是的 我目前使用的是mellow 体验也不是很好 但是最起码支持协议 而且完美达到了 全局代理想要的效果

**Comment by cyhunter** [comment]
++ 1支持

**Comment by tathyr** [comment]
Trojan+1

**Comment by stevechoris** [comment]
trojan +1

**Comment by itbeihe** [comment]
trojan +1

**Comment by yanue** [comment]
请下载试用: https://github.com/yanue/V2rayU/releases/tag/3.0.0.preview
