### ISSUE TITLE
关于UI一些小建议

### ISSUE THREAD

**Issue by sundayle** [yanue/V2rayU#422]
![image](https://user-images.githubusercontent.com/14009345/75105490-caea1e00-564e-11ea-8b63-8a4107331669.png)  

1.在偏好设置- Advance | Subscribe | Pac | Routing 这几个点击不了，只能在服务器设置一一点击 订阅设置 高级设置 路由设置 才能出现对应窗口。建议每个地方的图标点击了应该去对应位置。  

2.服务器设置-服务器列表 命名服务器名 感觉应该放右边会好点 或在右边服务器设置中。因为手动模式填好(没点确定),去重命名的话,导致该服务器手动填入的数据被清空,如果有添加个复制服务器那就更好了。

3.有点好奇服 务器设置-服务器列表里的 删除服务器的减号- 为什么这么大。

V2rayU version: 2.0.0
mac version: 10.12.6 (16G29)

**Comment by yanue** [comment]
请升级10.13以上

**Comment by sundayle** [comment]
好的。

yanue <notifications@github.com> 于 2020年3月1日周日 11:00写道：
