### ISSUE TITLE
Mac睡眠问题

### ISSUE THREAD

**Issue by lightingtime** [yanue/V2rayU#423]
问题：在Mac上电脑睡眠以后连接节点会重置为节点列表中的第一个。
版本：2.00
OS版本：10.15.3
设备：MacBook Pro 16

**Comment by 0x0006e** [comment]
何止重置，延迟都是 0ms

**Comment by enginemen** [comment]
mac上电脑睡眠后，软件不工作， 需要退出软件，重新启动软件才可以。不知道是否是bug

**Comment by yanue** [comment]
#420
