### ISSUE TITLE
Mac客户端无法科学上网，同样的vmess设置在iOS小火箭上可以使用，日志有明显异常

### ISSUE THREAD

**Issue by SleepyLogan** [yanue/V2rayU#424]
OS:macOS Catalina 10.15.3
V2rayU:v2.0.0
Config.json:

{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "10088"
    },
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "10087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": false
        },
        "security": "tls",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "whatever.com",
            "users": [
              {
                "id": "some id",
                "alterId": 0,
                "level": 0,
                "security": "none"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

V2ray log:

2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/proxy/socks: TCP Connect request to tcp:mtalk.google.com:443
2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/app/dispatcher: sniffed domain: mtalk.google.com
2020/02/25 12:37:26 tcp:127.0.0.1:50452 accepted tcp:mtalk.google.com:443 [proxy] 
2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/app/dispatcher: default route for tcp:mtalk.google.com:443
2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:whatever.com:443
2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:mtalk.google.com:443 via tcp:whatever.com:443
2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 212 but actually 206
2020/02/25 12:37:26 [Info] [2908004282] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/proxy/socks: TCP Connect request to tcp:64.233.189.188:443
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/app/dispatcher: sniffed domain: mtalk.google.com
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/app/dispatcher: default route for tcp:mtalk.google.com:443
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:whatever.com:443
2020/02/25 12:37:26 tcp:127.0.0.1:50454 accepted tcp:64.233.189.188:443 [proxy] 
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:mtalk.google.com:443 via tcp:whatever.com:443
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 153 but actually 115
2020/02/25 12:37:26 [Info] [1706333269] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients4.google.com:443
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/app/dispatcher: sniffed domain: clients4.google.com
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:whatever.com:443
2020/02/25 12:37:44 tcp:127.0.0.1:50457 accepted tcp:clients4.google.com:443 [proxy] 
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:whatever.com:443
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 0 but actually 177
2020/02/25 12:37:44 [Info] [2146617507] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by yanue** [comment]
去掉流量探测试下

**Comment by Rico358097990** [comment]
同样的问题

**Comment by august-xu** [comment]
同样的问题 安卓上就可以

**Comment by emodeqidao** [comment]
我的也是 mac 端不行，手机没问题

**Comment by XinAnzzZ** [comment]
所以这个 issue 解决了么？现在 mac 还是无法使用。

**Comment by lolstudio** [comment]
依然无法使用，求问
