### ISSUE TITLE
routing選項卡裡面的配置

### ISSUE THREAD

**Issue by zzzgit** [yanue/V2rayU#426]
<img width="136" alt="image" src="https://user-images.githubusercontent.com/1060733/75313094-cdd74f80-5896-11ea-8287-1f779bbaf97b.png">

如圖，我們知道，pac這個選項卡中的配置，是在pac模式下起作用。
那麼，routing選項卡裡面的配置，是在何種模式下起作用？

**Comment by Youguang** [comment]
同问 +1

**Comment by yanue** [comment]
请升级10.13以上

**Comment by cdliotop** [comment]
同问+2

**Comment by zhouwenze** [comment]
经过实践发现，Routing在全局模式下起作用(v2.2.0)
