### ISSUE TITLE
最新版系统Mac OS Catalina 10.15.3 升级后提示代理错误，且日志文件始终为0KB

### ISSUE THREAD

**Issue by PeterFuscan** [yanue/V2rayU#427]
英文Chrome版本79.0.3945.117 (Official Build) (64-bit)，使用V2rayU时提示
There is something wrong with the proxy server, or the address is incorrect.
<img width="1261" alt="Screen Shot 2020-02-26 at 2 03 42 PM" src="https://user-images.githubusercontent.com/53958712/75316867-768aac80-58a1-11ea-831a-c8758bce42dc.png">

用Network Utility检测端口未开放
<img width="651" alt="Screen Shot 2020-02-26 at 1 57 12 PM" src="https://user-images.githubusercontent.com/53958712/75316553-9e2d4500-58a0-11ea-9b8c-1a6a9dd6ff22.png">
同时，日志文件大小始终为0KB
<img width="657" alt="Screen Shot 2020-02-26 at 2 02 57 PM" src="https://user-images.githubusercontent.com/53958712/75316594-c1f08b00-58a0-11ea-8962-e0b06e842853.png">

已关闭系统写保护：
System Integrity Protection status: disabled.
<img width="571" alt="Screen Shot 2020-02-26 at 2 03 09 PM" src="https://user-images.githubusercontent.com/53958712/75316607-c9b02f80-58a0-11ea-8189-366b9ee8a9de.png">
<img width="571" alt="Screen Shot 2020-02-26 at 2 03 09 PM" src="https://user-images.githubusercontent.com/53958712/75316639-d5035b00-58a0-11ea-8564-a79f5beba3b3.png">

同时使用命令：
sudo mount -uw /
killall Finder
以读取系统文件

全局模式时Wi-Fi代理配置如下
![Uploading Screen Shot 2020-02-26 at 2.05.20 PM.png…]()
但实际上端口并未开放

网络是中国移动

**Comment by yanue** [comment]
有个自动清理日志的选项 你可以关闭了在看
