### ISSUE TITLE
mac os，v2ray+ws+tls+cdn，安装后无法正常上网

### ISSUE THREAD

**Issue by luojun86** [yanue/V2rayU#428]
mac os最新，v2ray+ws+tls+cfcdn的模式。
刚开始正常，第二天电脑无法正常上网，关闭程序也不行。日志如下：
2020/02/26 18:58:16 [Warning] [1285105773] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://fxxkgfw.ethanluo.ml/abcd321):  > dial tcp 104.31.65.213:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://fxxkgfw.ethanluo.ml/abcd321):  > dial tcp 104.31.64.213:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://fxxkgfw.ethanluo.ml/abcd321):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
麻烦各位帮忙分析下。谢谢！

**Comment by yanue** [comment]
请确认服务是否还可用, 可先到其他平台试下,在对比参数
