### ISSUE TITLE
希望增加订阅

### ISSUE THREAD

**Issue by wee911** [yanue/V2rayU#43]

**Comment by daisholou** [comment]
windows上的v2rayN有订阅，然后这个我找了半天没找到。

**Comment by yanue** [comment]
最近太忙了

**Comment by ColeHou** [comment]
希望添加

**Comment by yanue** [comment]
近期更新

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: test1234455 <notifications@github.com>
发送时间: Monday, May 6, 2019 9:34:54 PM
收件人: yanue/V2rayU
抄送: yanue; Comment
主题: Re: [yanue/V2rayU] 希望增加订阅 (#43)


希望添加

―

**Comment by xpol** [comment]
订阅模式下希望能缓存订阅提供的服务器在本地，这样能应对这样一些场景。

1. 启动的时候如果没网（比如 WiFi 关闭了）， 这时候等连上网络马上就能用缓存的服务器
2. 订阅连接本身也有挂的时候，如果有缓存，还可以用缓存的服务器

（像 V2RayX 那样每次都现从订阅更新服务器很傻）

**Comment by yanue** [comment]
参考了V2rayN,在处理中

**Comment by yanue** [comment]
已增加订阅功能,版本1.3.0
