### ISSUE TITLE
v2rayU 同样的配置，在两台旧mac上能用，在新macbook上就连不上网

### ISSUE THREAD

**Issue by HeLanGouSheng** [yanue/V2rayU#431]
v2rayU 同样的配置，在两台旧mac上能用，在新macbook上就连不上网。

一模一样的配置，手动输入的。

**Comment by HeLanGouSheng** [comment]
![image](https://user-images.githubusercontent.com/61537250/75424544-d05fa500-597b-11ea-86e6-dae72bcdf99f.png)

**Comment by VIXNESS** [comment]
端口被占用了
address is already in use.

**Comment by VIXNESS** [comment]
端口被占用了
address already in use

**Comment by yanue** [comment]
已修复: https://github.com/yanue/V2rayU/releases/tag/2.1.0
