### ISSUE TITLE
有哪位大神有 V2rayU版本的config文件？

### ISSUE THREAD

**Issue by chenApostle** [yanue/V2rayU#432]
xit status 255
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: unable to listen on domain address: 1991518963-xg15-zhui.scbshb.com

**Comment by yanue** [comment]
是2.0.0版本吗?

**Comment by chenApostle** [comment]
> 是2.0.0版本吗？：这个文件看下：
> `/Applications/V2rayU.app/Contents/Resources/config.json`

是2.0版本的

**Comment by chenApostle** [comment]
> 是2.0.0版本吗？：这个文件看下：
> `/Applications/V2rayU.app/Contents/Resources/config.json`

config.json 代码如下？

  "log": {
    "error": "",
    "loglevel": "none",
    "access": ""
  },
  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "1991518963-xg15-zhui.scbshb.com",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/",
          "headers": {
            "host": "aws-us2.nnet.tech"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "aws-us2.mmttpp.icu",
            "users": [
              {
                "id": "609a6a07-2797-3d78-9194-84f9e98092e9",
                "alterId": 2,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 80
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  }
}

**Comment by yanue** [comment]
```      "listen": "1991518963-xg15-zhui.scbshb.com", ``` 你是通过导入的吧?

**Comment by chenApostle** [comment]
> ` "listen": "1991518963-xg15-zhui.scbshb.com",`你是通过引入的吧？
> 还是说“设置->高级设置”界面上设置的就是1991518963-xg15-zhui.scbshb.com
> 
> ![图片](https://user-images.githubusercontent.com/1435250/75628841-bcd06a80-5c17-11ea-8d44-20ed7453af4a.png)
  我够买了机场主的节点，然后通过节点导入后就不能用了？现在的代码如下？

V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
2020/03/02 14:06:24 [Debug] v2ray.com/core/app/log: Logger started
2020/03/02 14:06:24 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/03/02 14:06:24 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 0.0.0.0:1080
2020/03/02 14:06:24 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1087
2020/03/02 14:06:24 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:1080
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
<img width="478" alt="55" src="https://user-images.githubusercontent.com/61539320/75649910-74ed2a00-5c8f-11ea-9650-609a61bb9851.png">
