### ISSUE TITLE
mac 上重启之后就不能用了

### ISSUE THREAD

**Issue by FuckUmei** [yanue/V2rayU#436]
配置好订阅地址，采用Pac模式访问。。每次都是莫名其妙的连接上。只要电脑一重启就连接不上了？

查看log日志：
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

有谁遇到过吗？怎么解决？
环境：
mac10.14.5
Google浏览器80.0.3987.122
V2rayU for version2.0.0

**Comment by FuckUmei** [comment]
ok。。。看了其他人的操作搞定了。。。
https://github.com/yanue/V2rayU/issues/380#issuecomment-585077215

**Comment by 0x0006e** [comment]
搞定你就把 issue 关了
