### ISSUE TITLE
点击服务器设置崩溃

### ISSUE THREAD

**Issue by gloryzgh** [yanue/V2rayU#437]
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [3017]

**Comment by gloryzgh** [comment]
version 2.0.0

**Comment by yanue** [comment]
删除文件后重试:
`~/Library/Preferences/net.yanue.V2rayU.plist`
