### ISSUE TITLE
ipv6设置的节点，测速为-1ms，实际中可以使用

### ISSUE THREAD

**Issue by levinablution** [yanue/V2rayU#439]
<img width="174" alt="Screen Shot 2020-03-03 at 2 30 40 AM" src="https://user-images.githubusercontent.com/10678669/75706352-fc6e8380-5cf7-11ea-971e-fe7674aa8aad.png">

**Comment by yanue** [comment]
可以试下: https://github.com/yanue/V2rayU/releases/tag/2.1.0

**Comment by levinablution** [comment]
使用2.1.0版本后已正常
