### ISSUE TITLE
pac模式下仍然无法访问github，

### ISSUE THREAD

**Issue by NOAME18** [yanue/V2rayU#441]
系统：mojave10.14.3
v2rayu: v2.1.0\v2.0\v1.4

情况：已经尝试多个版本，pac模式下，github不能访问，可以访问油管

### 运行v2.1错误日志
![Snipaste_2020-03-04_01-50-44](https://user-images.githubusercontent.com/53110680/75804556-1f15a080-5dbb-11ea-8b66-481869ed3b08.png)

### 路由设置
![Snipaste_2020-03-04_01-56-12](https://user-images.githubusercontent.com/53110680/75804665-571ce380-5dbb-11ea-9156-48be00f132ea.png)

此外端口已经是改掉了的状态
![Snipaste_2020-03-04_01-51-02](https://user-images.githubusercontent.com/53110680/75804570-2472eb00-5dbb-11ea-8731-045b2e2d5dc5.png)

**Comment by yanue** [comment]
pac 设置可以手动添加规则

**Comment by yanue** [comment]
#405
