### ISSUE TITLE
希望能提供一个新模式，V2RayU 完全使用用户导入的完整 V2Ray JSON 配置文件

### ISSUE THREAD

**Issue by Loyalsoldier** [yanue/V2rayU#442]
首先，感谢作者的劳动。

升级到 v2.1.0 后发现，导入的 V2Ray 配置中的 DNS 不生效了，好像必须从 V2RayU 的图形界面进行设置。

希望提供一个新模式：用户自己导入 V2Ray 配置后，V2RayU 的所有设置项都遵循用户导入的配置文件。

我自己有完整的 V2Ray JSON 配置文件，我对 V2RayU 的期望就是一个能使用图形界面方便查看 V2Ray 日志、自动为系统设置代理的客户端。

不知道有没有这个计划？没有的话，直接关闭此 issue 即可。

**Comment by yanue** [comment]
原本是那样的，后来需求愈来愈多，多个服务合一，所以去掉了
