### ISSUE TITLE
更新完最新版本2.1.0 ping总是显示-1ms

### ISSUE THREAD

**Issue by star4j** [yanue/V2rayU#444]
![image](https://user-images.githubusercontent.com/25194485/75836652-88b69e80-5dfd-11ea-8b35-8ce2cad25d5e.png)

**Comment by ChinaChenp** [comment]
-1应该是超时了

**Comment by star4j** [comment]
就是显示-1ms 服务还是可用的 在iterm ping 我的服务器也可以ping通 在100ms以内

**Comment by jiajudu** [comment]
开机启动后服务器全部显示-1ms, 建议把这个状态和服务器不可用区分开@yanue

**Comment by yanue** [comment]
> 开机启动后服务器全部显示-1ms, 建议把这个状态和服务器不可用区分开@yanue

-1ms是请求不到或服务不可用，5s超时，不能区分
