### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by ChinaChenp** [yanue/V2rayU#445]
1、这个排版能不能稍微改改，看起来太乱了；左右对齐应该都会更直观一些
![image](https://user-images.githubusercontent.com/15309278/75839023-aafeeb00-5e02-11ea-844a-18b944db7665.png)

2、ping延时能有地方设置成自动的么，能直观的看到延时最低的接入服务

整体来说还是非常非常好用的，感谢感谢~！

**Comment by yanue** [comment]
试下2.2
