### ISSUE TITLE
前端用trojan协议出错

### ISSUE THREAD

**Issue by jameslhc** [yanue/V2rayU#447]
Mac10.13.6
使用trojan，单独使用，端口1080配合浏览器插件流量都正常
trojan端口改为1082，使用v2rayU做前端配置127.0.0.1端口1082，协议socks

trojan窗口报错
[2020-03-04 13:42:35] [ERROR] 127.0.0.1:64434 unknown protocol
[2020-03-04 13:42:35] [INFO] 127.0.0.1:64434 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
这是算是BUG还是协议参数有问题

**Comment by jameslhc** [comment]
对了，补充一下，使用的v2rayU版本是最新的2.1.0

**Comment by maidousj** [comment]
更新2.1.0后，trojan窗口同样错误。
用别的节点的话，v2rayU日志如下：

> 2020/03/05 18:07:11 [Info] [3525322634] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2020/03/05 18:07:11 [Info] [3525322634] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2020/03/05 18:07:11 [Info] [3525322634] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/03/05 18:07:11 tcp:127.0.0.1:61199 accepted tcp:www.google.com:443 [proxy] 
2020/03/05 18:07:11 [Warning] [3525322634] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > EOF
2020/03/05 18:07:11 [Info] [3525322634] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/03/05 18:07:11 [Info] [2013812687] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2020/03/05 18:07:11 [Info] [2013812687] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2020/03/05 18:07:11 [Info] [2013812687] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/03/05 18:07:11 tcp:127.0.0.1:61201 accepted tcp:www.google.com:443 [proxy] 
2020/03/05 18:07:11 [Warning] [2013812687] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > EOF
2020/03/05 18:07:11 [Info] [2013812687] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/03/05 18:07:11 [Info] [4009038298] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2020/03/05 18:07:11 [Info] [4009038298] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2020/03/05 18:07:11 [Info] [4009038298] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/03/05 18:07:11 tcp:127.0.0.1:61203 accepted tcp:www.google.com:443 [proxy] 
2020/03/05 18:07:11 [Warning] [4009038298] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > EOF
2020/03/05 18:07:11 [Info] [4009038298] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by yanue** [comment]
#404

**Comment by jameslhc** [comment]
> #404

麻烦看下内容，就是你这404里边报错的情况

**Comment by Koldy-xyz999** [comment]
It's a port binging error, trojan and v2RayU use the same port which is 1080, I have this problem as well, and I have been working on it for several days, today I finally find a way to solve this, see below:
1. do not use the new version v2.1.0, because the new version doesn't support the port 1080 binding while the trojan use the same one, after I change the version to the prior one which is v2.0.0, the problem simply solved;
2. after you change your v2RayU version to the v2.0.0, you can bind the socks port with 1080 same as trojan, and when you wanna browsing, turn on v2rayU first, then turn on trojan after v2rayU turning on
3. happy browsing
finally, this is just on macOS, I don't know if it works on Windows or not 
that's all, thanks

**Comment by maidousj** [comment]
> It's a port binging error, trojan and v2RayU use the same port which is 1080, I have this problem as well, and I have been working on it for several days, today I finally find a way to solve this, see below:
> 
> 1. do not use the new version v2.1.0, because the new version doesn't support the port 1080 binding while the trojan use the same one, after I change the version to the prior one which is v2.0.0, the problem simply solved;
> 2. after you change your v2RayU version to the v2.0.0, you can bind the socks port with 1080 same as trojan, and when you wanna browsing, turn on v2rayU first, then turn on trojan after v2rayU turning on
> 3. happy browsing
>    finally, this is just on macOS, I don't know if it works on Windows or not
>    that's all, thanks

Yes. I do the same way yesterday. Change my version to the v2.0.0. I elaborate it in #455 and want to know if it can be fixed in the new version.

**Comment by Koldy-xyz999** [comment]
> > It's a port binging error, trojan and v2RayU use the same port which is 1080, I have this problem as well, and I have been working on it for several days, today I finally find a way to solve this, see below:
> > 
> > 1. do not use the new version v2.1.0, because the new version doesn't support the port 1080 binding while the trojan use the same one, after I change the version to the prior one which is v2.0.0, the problem simply solved;
> > 2. after you change your v2RayU version to the v2.0.0, you can bind the socks port with 1080 same as trojan, and when you wanna browsing, turn on v2rayU first, then turn on trojan after v2rayU turning on
> > 3. happy browsing
> >    finally, this is just on macOS, I don't know if it works on Windows or not
> >    that's all, thanks
> 
> Yes. I do the same way yesterday. Change my version to the v2.0.0. I elaborate it in #455 and want to know if it can be fixed in the new version.

glad to hear that

**Comment by jameslhc** [comment]
> It's a port binging error, trojan and v2RayU use the same port which is 1080, I have this problem as well, and I have been working on it for several days, today I finally find a way to solve this, see below:
> 
> 1. do not use the new version v2.1.0, because the new version doesn't support the port 1080 binding while the trojan use the same one, after I change the version to the prior one which is v2.0.0, the problem simply solved;
> 2. after you change your v2RayU version to the v2.0.0, you can bind the socks port with 1080 same as trojan, and when you wanna browsing, turn on v2rayU first, then turn on trojan after v2rayU turning on
> 3. happy browsing
>    finally, this is just on macOS, I don't know if it works on Windows or not
>    that's all, thanks

thank you for your solution, but my problem is different.
I didn't use the same port for v2rayU and trojan to avoid the the port conflict.
1080 is used with v2rayU, 1082 is used with trojan.
trojan is used as a socks proxy in v2rayU, and the log shows that trojan didn't work well in v2rayU with socks protocol.
so I believe that there is a bug in  2.1.0, if the older version v2rayU can work well with trojan.
Hope the owner can make it right in the next version, even can make a direct support with trojan protocol better.

**Comment by Justsoos** [comment]
socks 协议改了三版了，依然 bug 早就提过了 https://github.com/yanue/V2rayU/issues/306

**Comment by liang-sss** [comment]
Alse see #455, which probably can be useful.
