### ISSUE TITLE
V2rayUHelper 后台疯狂吃资源

### ISSUE THREAD

**Issue by hezhijie0327** [yanue/V2rayU#449]
版本：2.1.0

**Comment by yanue** [comment]
ping和检查端口时会调用
ping是多协程同时进行，如果服务列表过多，确实有可能 
可以去设置里面关闭自动ping选择最快server（唤醒时会ping）

**Comment by Rainsho** [comment]
我也遇到了，退了客户端，发现进程还在。手动杀了就好了，可能某次调用的时候，资源没回收吧。
