### ISSUE TITLE
客户端日志不会自动清理

### ISSUE THREAD

**Issue by awkj** [yanue/V2rayU#45]
我查看日志位于 library/logs/v2rayU.log 下，能否支持按日清理日志，以及，我在配置中已经省略掉了 日志输出地址，应该是输出到 stdout 才对，为什么会还留存在本地呢？

**Comment by yanue** [comment]
![image](https://user-images.githubusercontent.com/1435250/57531795-dc3a9600-736c-11e9-9b08-db9eadbdc029.png)
增加清除按钮
