### ISSUE TITLE
2020年3月4日更新后，CPU百分百，散热一直响，附图，退出v2rayu后正常了

### ISSUE THREAD

**Issue by apuppy** [yanue/V2rayU#452]
<img width="818" alt="v2ray-issue-1" src="https://user-images.githubusercontent.com/6140347/75888708-c00d6580-5e66-11ea-9cb1-e5a9790309df.png">
<img width="818" alt="v2ray-issue-2" src="https://user-images.githubusercontent.com/6140347/75888770-dd423400-5e66-11ea-83e6-dd86aa80e873.png">
<img width="604" alt="v2rayu-issue-3" src="https://user-images.githubusercontent.com/6140347/75889293-a3bdf880-5e67-11ea-9d4d-bccec839b382.png">

**Comment by LuRenJiasWorld** [comment]
MacOS 10.15，遇到同样问题。V2rayU进程满载。

目前已降级到上一版本，希望开发者能尽快修复，感激不尽。

![image](https://user-images.githubusercontent.com/29622423/75894228-e1724f80-5e6e-11ea-9ba5-78dda803bd6d.png)

![image](https://user-images.githubusercontent.com/29622423/75894247-e931f400-5e6e-11ea-8a51-b868a73d44de.png)

**Comment by lightingtime** [comment]
同遇到，也是Helpler占用过高。以下是日志：
2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients4.google.com:443
2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:38:22 tcp:127.0.0.1:61835 accepted tcp:clients4.google.com:443 [proxy] 
2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:172.86.70.147:80
2020/03/05 14:38:40 [Info] [20802557] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/proxy/socks: TCP Connect request to tcp:live.github.com:443
2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/app/dispatcher: default route for tcp:live.github.com:443
2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:38:42 tcp:127.0.0.1:61837 accepted tcp:live.github.com:443 [proxy] 
2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:live.github.com:443 via tcp:172.86.70.147:80
2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:43:42 tcp:127.0.0.1:61863 accepted tcp:www.google.com:443 [proxy] 
2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:172.86.70.147:80
2020/03/05 14:43:42 [Info] [2705997535] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2020/03/05 14:43:42 [Info] [2705997535] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2020/03/05 14:43:42 [Info] [2705997535] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:43:42 tcp:127.0.0.1:61865 accepted tcp:www.google.com:443 [proxy] 
2020/03/05 14:43:43 [Info] [2705997535] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:172.86.70.147:80
2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/proxy/socks: TCP Connect request to tcp:cse.google.com:443
2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/app/dispatcher: default route for tcp:cse.google.com:443
2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:43:43 tcp:127.0.0.1:61867 accepted tcp:cse.google.com:443 [proxy] 
2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/proxy/socks: TCP Connect request to tcp:fonts.gstatic.com:443
2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/app/dispatcher: default route for tcp:fonts.gstatic.com:443
2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:43:43 tcp:127.0.0.1:61870 accepted tcp:fonts.gstatic.com:443 [proxy] 
2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:cse.google.com:443 via tcp:172.86.70.147:80
2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:fonts.gstatic.com:443 via tcp:172.86.70.147:80
2020/03/05 14:43:44 [Info] [2705997535] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/03/05 14:43:44 [Info] [2705997535] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/03/05 14:44:37 [Info] [2355221464] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/03/05 14:44:37 [Info] [2355221464] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/proxy/socks: TCP Connect request to tcp:mtalk.google.com:5228
2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/app/dispatcher: default route for tcp:mtalk.google.com:5228
2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
2020/03/05 14:44:37 tcp:127.0.0.1:61874 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:mtalk.google.com:5228 via tcp:172.86.70.147:80

**Comment by t-dawei** [comment]
同样, 发热问题

**Comment by jarryyen** [comment]
同样问题....我还另外起了一个帖子...

**Comment by yanue** [comment]
服务列表多吗

**Comment by XXXMrG** [comment]
感觉问题就是后台在一直 ping 导致的，每次看都是在测试中。

**Comment by hsing0527** [comment]
> 服务列表多吗,有没有一直ping?

是的，我看到ping栏一直有个 in testing字样

**Comment by yanue** [comment]
> > 服务列表多吗,有没有一直ping?
> 
> 是的，我看到ping栏一直有个 in testing字样

麻烦上传一下文件:
```
/Applications/V2rayU.app/Contents/Resources/ping.json
```

**Comment by hsing0527** [comment]
> > > 服务列表多吗,有没有一直ping?
> > 
> > 
> > 是的，我看到ping栏一直有个 in testing字样
> 
> 麻烦上传一下文件:
> 
> ```
> /Applications/V2rayU.app/Contents/Resources/ping.json
> ```

我重装了2.0版本 文件应该没有了

**Comment by yanue** [comment]
@hsing0527 现在还一直ping吗 ping会生成ping.json这个文件的

**Comment by hsing0527** [comment]
发现我回滚的2.0版还是会一直出现in [testing，但是没有出现占用CPU。我检查了resources文件，居然没有ping.json 
[<img width="202" alt="Screenshot 2020-03-06 at 10 09 35 AM" src="https://user-images.githubusercontent.com/57891696/76043502-b08b3b00-5f92-11ea-8525-dc876e0b42c0.png">](url)

**Comment by yanue** [comment]
@apuppy @LuRenJiasWorld @lightingtime @t-dawei   麻烦使用2.1上传一下文件:
```
/Applications/V2rayU.app/Contents/Resources/ping.json
```

**Comment by hsing0527** [comment]
> @apuppy @LuRenJiasWorld @lightingtime @t-dawei 麻烦使用2.1上传一下文件:
> 
> ```
> /Applications/V2rayU.app/Contents/Resources/ping.json
> ```

好了 现在又在咆哮不止了😂[
[ping.json.zip](https://github.com/yanue/V2rayU/files/4296164/ping.json.zip)
](url)

**Comment by hsing0527** [comment]
> > @apuppy @LuRenJiasWorld @lightingtime @t-dawei 麻烦使用2.1上传一下文件:
> > ```
> > /Applications/V2rayU.app/Contents/Resources/ping.json
> > ```
> 
> 好了 现在又在咆哮不止了😂[
> [ping.json.zip](https://github.com/yanue/V2rayU/files/4296164/ping.json.zip)
> ](url)

我这边是即使退出v2rayU，helper也依然在运行

**Comment by LuRenJiasWorld** [comment]
> > @apuppy @LuRenJiasWorld @lightingtime @t-dawei 麻烦使用2.1上传一下文件:
> > ```
> > /Applications/V2rayU.app/Contents/Resources/ping.json
> > ```
> 
> 好了 现在又在咆哮不止了😂[
> [ping.json.zip](https://github.com/yanue/V2rayU/files/4296164/ping.json.zip)
> ](url)

你好，文本内容在这里：https://paste.ubuntu.com/p/NdfKXSvFtk/

**Comment by nan-wang** [comment]
同样问题。
mac os 10.15.3
vray2: 2.1.0

**Comment by WalkerJG** [comment]
Same problem. 
macOS version: 10.15.1
v2ray version:2.1.0

**Comment by lightingtime** [comment]
> 同遇到，也是Helpler占用过高。
> macOS版本10.15.3
> 以下是日志：
> 2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients4.google.com:443
> 2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
> 2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:38:22 tcp:127.0.0.1:61835 accepted tcp:clients4.google.com:443 [proxy]
> 2020/03/05 14:38:22 [Info] [102661196] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:172.86.70.147:80
> 2020/03/05 14:38:40 [Info] [20802557] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
> 2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/proxy/socks: TCP Connect request to tcp:live.github.com:443
> 2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/app/dispatcher: default route for tcp:live.github.com:443
> 2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:38:42 tcp:127.0.0.1:61837 accepted tcp:live.github.com:443 [proxy]
> 2020/03/05 14:38:42 [Info] [2376248032] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:live.github.com:443 via tcp:172.86.70.147:80
> 2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
> 2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
> 2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:43:42 tcp:127.0.0.1:61863 accepted tcp:www.google.com:443 [proxy]
> 2020/03/05 14:43:42 [Info] [3853991972] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:172.86.70.147:80
> 2020/03/05 14:43:42 [Info] [2705997535] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
> 2020/03/05 14:43:42 [Info] [2705997535] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
> 2020/03/05 14:43:42 [Info] [2705997535] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:43:42 tcp:127.0.0.1:61865 accepted tcp:www.google.com:443 [proxy]
> 2020/03/05 14:43:43 [Info] [2705997535] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:172.86.70.147:80
> 2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/proxy/socks: TCP Connect request to tcp:cse.google.com:443
> 2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/app/dispatcher: default route for tcp:cse.google.com:443
> 2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:43:43 tcp:127.0.0.1:61867 accepted tcp:cse.google.com:443 [proxy]
> 2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/proxy/socks: TCP Connect request to tcp:fonts.gstatic.com:443
> 2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/app/dispatcher: default route for tcp:fonts.gstatic.com:443
> 2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:43:43 tcp:127.0.0.1:61870 accepted tcp:fonts.gstatic.com:443 [proxy]
> 2020/03/05 14:43:43 [Info] [1122413024] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:cse.google.com:443 via tcp:172.86.70.147:80
> 2020/03/05 14:43:43 [Info] [2571970864] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:fonts.gstatic.com:443 via tcp:172.86.70.147:80
> 2020/03/05 14:43:44 [Info] [2705997535] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
> 2020/03/05 14:43:44 [Info] [2705997535] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
> 2020/03/05 14:44:37 [Info] [2355221464] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
> 2020/03/05 14:44:37 [Info] [2355221464] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
> 2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/proxy/socks: TCP Connect request to tcp:mtalk.google.com:5228
> 2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/app/dispatcher: default route for tcp:mtalk.google.com:5228
> 2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:172.86.70.147:80
> 2020/03/05 14:44:37 tcp:127.0.0.1:61874 accepted tcp:mtalk.google.com:5228 [proxy]
> 2020/03/05 14:44:37 [Info] [185750998] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:mtalk.google.com:5228 via tcp:172.86.70.147:80

ping json(去掉host)：
[
    {
        "name": "config.CA5DCC1D-9D6A-4560-891F-CAED8EF77996",
        "host": "127.0.0.1",
        "ping": "247µs"
    },
    {
        "name": "config.6367D98A-8299-4314-BBDE-C5F182E36CEE",
        "host": "127.0.0.1",
        "ping": "304µs"
    },
    {
        "name": "config.F59ECC84-0A3D-43A5-B1AD-5DF069A597E6",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.B5A978D2-E80E-48F3-B59D-2D253C6D9BFB",
        "host": "",
        "ping": "274.545ms"
    },
    {
        "name": "config.8B98B244-1556-4660-ABFE-62632727A877",
        "host": "",
        "ping": "239.623ms"
    },
    {
        "name": "config.49D4CCB6-2AB0-4FE4-99DC-6893B58C4927",
        "host": "",
        "ping": "24.64ms"
    },
    {
        "name": "config.6FB14EAF-D41C-44B4-B48A-DC5A584A3D55",
        "host": "",
        "ping": "191.059ms"
    },
    {
        "name": "config.0C616F8F-F46B-4F10-A653-5DB8A97A6C83",
        "host": "",
        "ping": "26.794ms"
    },
    {
        "name": "config.4A3104A8-9BCE-4F14-ADBB-9919A45A234D",
        "host": "5",
        "ping": "-1ms"
    },
    {
        "name": "config.53D4C46D-C920-469E-B765-272F5AF2946A",
        "host": "",
        "ping": "25.338ms"
    },
    {
        "name": "config.F4F53DF1-84AF-408E-A629-B7901DA24404",
        "host": "",
        "ping": "99.14ms"
    },
    {
        "name": "config.5B2372FF-C9F7-4FE0-89D0-BD0B7EA3024F",
        "host": "",
        "ping": "26.671ms"
    },
    {
        "name": "config.9486F660-9F1B-4E7F-B2AB-4F5FF9D2FEBA",
        "host": "",
        "ping": "135.623ms"
    },
    {
        "name": "config.61AD6CD2-2CFA-4578-BE3B-3A127C2E89F2",
        "host": "",
        "ping": "99.094ms"
    },
    {
        "name": "config.F2485408-599D-41B5-9CDE-5D56959FEF15",
        "host": "",
        "ping": "17.873ms"
    },
    {
        "name": "config.403FD8BD-2597-4C1B-8624-2C654B83E6F7",
        "host": "",
        "ping": "87.023ms"
    },
    {
        "name": "config.B2FC8B5A-0218-4568-B6F9-5BA6C0984910",
        "host": "",
        "ping": "26.552ms"
    },
    {
        "name": "config.E3960C82-B131-4928-9994-6F4B38F5F068",
        "host": "89.31.125.181",
        "ping": "58.02ms"
    },
    {
        "name": "config.A7C2A43B-E8BB-4F12-B9FE-54F34782CA51",
        "host": "103.56.60.45",
        "ping": "26.627ms"
    },
    {
        "name": "config.0389FF03-C25C-4ADE-87A0-3679F5A8B31E",
        "host": "",
        "ping": "104.103ms"
    },
    {
        "name": "config.910BADF3-48B0-4BA1-8353-1AD4D763F0AF",
        "host": "",
        "ping": "24.822ms"
    },
    {
        "name": "config.BCBB0CAB-83C4-4FF3-AEA0-2DA9BFEA91B8",
        "host": "",
        "ping": "87.567ms"
    },
    {
        "name": "config.63A096B6-0A26-4E48-8059-C48A0D8094B4",
        "host": "",
        "ping": "26.766ms"
    },
    {
        "name": "config.6A9E092F-40E2-4E3C-8E72-831992425E74",
        "host": "",
        "ping": "68.741ms"
    },
    {
        "name": "config.BBB015D5-D550-47D7-9C01-A9F888152065",
        "host": "",
        "ping": "24.578ms"
    },
    {
        "name": "config.1112D3BA-9E6C-4054-A6BC-4F2D8CF3E69F",
        "host": "",
        "ping": "240.642ms"
    },
    {
        "name": "config.C636798F-F7A7-4700-A535-DCA7AC34ED4B",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.1BDD9AA5-25FF-48C9-B3FE-A2DDB675B114",
        "host": ",
        "ping": "159.57ms"
    },
    {
        "name": "config.0E191E51-F3E9-4016-8C88-199A264CBFEB",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.86573C36-EC25-422C-8FAE-F81FA0F09996",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.70AC3508-DA84-45B9-8EA1-FFB4D9E7384C",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.D833881B-A6E9-4362-BF9C-641614C7FFEF",
        "host": "",
        "ping": "26.553ms"
    },
    {
        "name": "config.51AA1FF3-9A1C-40EF-81DF-C59A5456A1C7",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.CF28BC6A-68BB-450C-AF4F-3E6C18373724",
        "host": "",
        "ping": "17.853ms"
    },
    {
        "name": "config.1D2C5142-65FB-4C8C-B670-4117C3B14B52",
        "host": "",
        "ping": "151.928ms"
    },
    {
        "name": "config.24236280-2798-4AFA-99DC-3FD51AC29A67",
        "host": "",
        "ping": "26.601ms"
    },
    {
        "name": "config.8DE759C1-3B10-482A-8971-70CE43009784",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.28990729-0865-4C23-B5A7-5A87F6C26F5D",
        "host": "",
        "ping": "24.954ms"
    },
    {
        "name": "config.B39EA5D3-0825-4100-9F22-7DF70021D09D",
        "host": "",
        "ping": "173.444ms"
    },
    {
        "name": "config.713B49B6-ACBC-4481-A075-170916A59320",
        "host": "",
        "ping": "25.117ms"
    },
    {
        "name": "config.E7438982-CEC8-4649-97A4-E976DC2E5FB5",
        "host": "",
        "ping": "277.178ms"
    },
    {
        "name": "config.06F9500D-BE19-46B0-84DB-A132BCCC4499",
        "host": "",
        "ping": "26.694ms"
    },
    {
        "name": "config.80509908-1AFB-403A-9775-2706484607F8",
        "host": "",
        "ping": "151.243ms"
    },
    {
        "name": "config.39F6B394-0D3B-41BF-955C-99202FF7E321",
        "host": "",
        "ping": "17.767ms"
    },
    {
        "name": "config.A5E3145B-7D1E-4C4D-83F1-BAF2C2143A39",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.92C2EAF8-13F2-4B80-84CE-98615B54F341",
        "host": "",
        "ping": "-1ms"
    },
    {
        "name": "config.0E96BEC9-F463-4FD8-884E-B40F805F8B49",
        "host": "",
        "ping": "206.657ms"
    },
    {
        "name": "config.789F891C-3B4C-4DD9-AEDB-002E12307273",
        "host": "",
        "ping": "26.552ms"
    },
    {
        "name": "config.02D2532D-80F5-4826-BCBF-B62DF68B90DE",
        "host": "",
        "ping": "159.634ms"
    },
    {
        "name": "config.911C0E99-8BDA-421B-BFFA-BA6E25C375DB",
        "host": "",
        "ping": "25.325ms"
    },
    {
        "name": "config.16CD572E-5506-4965-BDC7-D1CA289BF4F1",
        "host": "",
        "ping": "287.408ms"
    },
    {
        "name": "config.4C1F1130-7D63-45F9-9F67-E9B0E2CA7625",
        "host": "",
        "ping": "26.494ms"
    },
    {
        "name": "config.749DD11F-D477-44F5-A5D3-BEE678C896A5",
        "host": ",
        "ping": "69.886ms"
    },
    {
        "name": "config.4ACEA3A5-52D4-4148-A81C-EAED3A726620",
        "host": "",
        "ping": "68.147ms"
    },
    {
        "name": "config.A1E0A2C0-4056-46FF-83AD-5CA9010F0761",
        "host": "",
        "ping": "16.51ms"
    },
    {
        "name": "config.95F51802-DF7C-4E90-9EAB-6EC86A15659B",
        "host": "",
        "ping": "208.825ms"
    },
    {
        "name": "config.99A3CEE0-CBDF-4A8E-9D8F-5DA06DD105AE",
        "host": "",
        "ping": "26.28ms"
    },
    {
        "name": "config.39A634EC-33A3-47C6-9BF2-28807F28DB0D",
        "host": "",
        "ping": "76.872ms"
    },
    {
        "name": "config.92521953-7813-4393-A512-0C66A5313FF1",
        "host": "",
        "ping": "25.019ms"
    },
    {
        "name": "config.95511BA9-5360-48B0-A77C-07CD82FDD0E5",
        "host": "",
        "ping": "97.559ms"
    },
    {
        "name": "config.D765C5BF-6DD5-4263-8179-96755314E349",
        "host": ",
        "ping": "223.478ms"
    },
    {
        "name": "config.43F1C59A-4A3B-4A91-87EF-15C3A1771B73",
        "host": "",
        "ping": "245.355ms"
    },
    {
        "name": "config.10F0CB67-F56F-4881-894B-945FF784E7F2",
        "host": "",
        "ping": "-1ms"
    }
]

**Comment by L-kcirtaP** [comment]
同样的问题，希望能尽快解决。

**Comment by twm17** [comment]
10.15.4，2.1，只要运营程序就持续高功耗，已回滚2.0使用

**Comment by cnyy7** [comment]
同样问题
MacOS: 10.14.5
V2RayU: v2.1.0

**Comment by mfjc-vip** [comment]
同样问题，发烫！！！我直接退出这个进程，解决！

**Comment by hadix-lin** [comment]
> 同样问题，发烫！！！我直接退出这个进程，解决！

我也是这样，我的版本是v2.1

**Comment by Swung0x48** [comment]
我也遇到了这个问题。在V2rayU占满CPU时通过ps查看进程如下：
swung0x48@Swungs-MacBook-Pro ~  ps -ax | grep 16240
16240 ??         0:00.00 /bin/bash -c cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd ping -t 5s -f ./ping.json
16369 ttys000    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 16240

**Comment by sheepstarli** [comment]
macos 10.14.6
v2rayu:v2.1.0
同样问题

**Comment by yanue** [comment]
试下2.2
