### ISSUE TITLE
[reopen] trojan放在前端的错误

### ISSUE THREAD

**Issue by jameslhc** [yanue/V2rayU#455]
大佬好，之前提的case被关了，可能你没看清内容，好像还不能reopen之前的issue，只能新开一个

#447 中描述的就是在v2rayU前面挂trojan，但是协议报错，不知道是设置问题还是软件bug麻烦判断下
具体使用的操作办法就是和 #404 里边一样的

Mac10.13.6， v2rayU 2.1.0
使用trojan，单独使用，配合浏览器插件正常
trojan单独运行作为v2rayU前置代理，协议socks

trojan窗口报错
[2020-03-04 13:42:35] [ERROR] 127.0.0.1:64434 unknown protocol
[2020-03-04 13:42:35] [INFO] 127.0.0.1:64434 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds

**Comment by jameslhc** [comment]
![trojan](https://user-images.githubusercontent.com/48267688/76044969-db778e00-5f96-11ea-8cef-7eb413e61446.png)
![v2rayU-2 1 0-socks](https://user-images.githubusercontent.com/48267688/76044972-ddd9e800-5f96-11ea-8dbb-a99c98b78951.png)

**Comment by maidousj** [comment]
和lz同样配置，补充一点：2.0.0版本可以科学上网。但是用trojan日志：
> V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
main: failed to read config file: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: failed to parse to outbound detour config. > json: cannot unmarshal string into Go struct field SocksRemoteConfig.servers.port of type uint16
> exit status 255

如果用其他的ssr节点，循环打印日志：
> V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1080 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1080 > listen tcp 127.0.0.1:1080: bind: address already in use

如果用的ssr节点加密方式是rc4-md5的话，也会循环打印“不支持rc4-md5”。
但是以上都可以科学上网。

升级成2.1.0以后，会报1080端口被占用（trojan先开启的话）。如果u2ray基础设置那里的socks端口那里修改成其他非1080端口，则无法科学上网。具体日志在昨天的#447 中。

**Comment by johntostring** [comment]
我也被困扰了一阵，我试着删掉了 json 中 outbounds 下 servers `users` 这段后可以了：
Trojan 客户端监听端口我改成了1380，没被其他程序占用就行（比如说 v2ray 端口冲突）
```diff
{
  //...省略
  "outbounds": [
    {
      "protocol": "socks",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": false
        },
        "security": "none",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
-            "users": [
-             {
-                "pass": "",
-                "user": "",
-                "level": 0
-              }
-            ],
            "port": 1380
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
![image](https://user-images.githubusercontent.com/5723484/76593933-a210c680-6532-11ea-9149-93e258233488.png)

**Comment by jameslhc** [comment]
> 我也被`unknown protocol`错误困扰了一阵，我试着删掉了 json 中 outbounds 下 servers `users` 这段，保存重启一下v2ray就行了。
> 
> 我的版本是：
> 
> * macOS 10.14.5
> * v2rayU 2.1.0
> * Trojan 1.14.1
> 
> Trojan 客户端监听端口我改成了1380，没被其他程序占用就行（比如说 v2ray 端口冲突）
> 
> ```diff
> {
>   //...省略
>   "outbounds": [
>     {
>       "protocol": "socks",
>       "streamSettings": {
>         "tcpSettings": {
>           "header": {
>             "type": "none"
>           }
>         },
>         "tlsSettings": {
>           "allowInsecure": false
>         },
>         "security": "none",
>         "network": "tcp"
>       },
>       "tag": "proxy",
>       "settings": {
>         "servers": [
>           {
>             "address": "127.0.0.1",
> -            "users": [
> -             {
> -                "pass": "",
> -                "user": "",
> -                "level": 0
> -              }
> -            ],
>             "port": 1380
>           }
>         ]
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {
>         "domainStrategy": "AsIs",
>         "redirect": "",
>         "userLevel": 0
>       }
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {
>         "response": {
>           "type": "none"
>         }
>       }
>     }
>   ],
>   "dns": {},
>   "routing": {
>     "settings": {
>       "domainStrategy": "AsIs",
>       "rules": []
>     }
>   },
>   "transport": {}
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/5723484/76593933-a210c680-6532-11ea-9149-93e258233488.png)
> 
> 注意：如果以后再点击了界面上的”手动模式“，这段 json 配置又会被加上去。

太棒了，问题解决了，这样看来软件这个issue这样算解决了，希望作者在下个版本可以fix咯

**Comment by cc978** [comment]
不止点击确定，会被保存掉，点击 『手动模式』 ，或者就算看一眼，换到其他节点，也会被自动保存成错误的、无法使用的格式。

最新 2.2.0 依然还是有这个错误。

另外，不删掉 user 全部字段，只删掉 `“user”: [ {} ]` 之中包括大括号的部分就能正常使用，应该就是用户名和密码的简单bug。。。。
https://github.com/yanue/V2rayU/issues/306
