### ISSUE TITLE
2.1.0版本频繁请求密码输入

### ISSUE THREAD

**Issue by YuechenW** [yanue/V2rayU#456]
升级到最新版后，每次开、关v2服务，启动退出应用都会要求输入密码，很困扰。已经确认应用在/applications目录下。而且退到2.0.0版本问题依旧，升级前都没这个问题嘛。。。希望解决一下。

**Comment by zhangyanzt** [comment]
我也是这个问题，后来完全卸载重新安装好了

**Comment by YuechenW** [comment]
请问你是怎么完全卸载的？我把README里面的相关文件都删了再重装还是不行。 @zhangyanzt

**Comment by zhangyanzt** [comment]
> 请问你是怎么完全卸载的？我把README里面的相关文件都删了再重装还是不行。 @zhangyanzt

用CleanMyMac这类第三方软件

**Comment by lengxuegang** [comment]
用brew cask install/uninstall

**Comment by YuechenW** [comment]
上面提到的方法都试了还是不行。。感觉是v2rayutool没有获取到足够的权限。将其改过权限后，虽然不用输密码了，但v2rayu主程序打不开了，哈哈已经要放弃了。
<img width="555" alt="图片" src="https://user-images.githubusercontent.com/44115105/76198676-74bdd300-6229-11ea-9154-24513a8268e8.png">

**Comment by YuechenW** [comment]
好了问题解决啦 跟v2ray没有关系 是不知道什么东西把我的sudoers弄没了 遇到这个问题的朋友检查一下sudo权限

**Comment by ichrispan** [comment]
可以尝试关闭客户端的开机启动，然后重启一遍，之后再重新设置回开机启动

**Comment by jasonhan2003** [comment]
> 好了问题解决啦 跟v2ray没有关系 是不知道什么东西把我的sudoers弄没了 遇到这个问题的朋友检查一下sudo权限

请问新手怎么检查sudo权限？
