### ISSUE TITLE
bug:无法上墙

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#458]
正常打开电脑上网，但是网页一直在刷新状态，可就是刷不出来，调整成全局模式可以刷出网页
Mojave 10.14.6 (18G3020) ；Safari：版本 13.0.5 (14608.5.12) ；V2rayU 2.1.0 
日志
2020/03/06 12:58:56 tcp:127.0.0.1:60231 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/03/06 12:58:56 [Info] [555071872] v2ray.com/core/transport/internet/websocket: creating connection to tcp:43.239.158.177:443
2020/03/06 12:58:56 [Info] [2378233245] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.youtube.com:443
2020/03/06 12:58:56 [Info] [2378233245] v2ray.com/core/app/dispatcher: default route for tcp:www.youtube.com:443
2020/03/06 12:58:56 [Info] [2378233245] v2ray.com/core/transport/internet/websocket: creating connection to tcp:43.239.158.177:443
2020/03/06 12:58:56 tcp:127.0.0.1:60233 accepted tcp:www.youtube.com:443 [proxy] 
2020/03/06 12:58:56 [Info] [555071872] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:yt3.ggpht.com:443 via tcp:43.239.158.177:443
2020/03/06 12:58:57 [Info] [3600087981] v2ray.com/core/proxy/socks: TCP Connect request to tcp:r2---sn-i3b7knlk.googlevideo.com:443
2020/03/06 12:58:57 [Info] [3600087981] v2ray.com/core/app/dispatcher: default route for tcp:r2---sn-i3b7knlk.googlevideo.com:443
2020/03/06 12:58:57 [Info] [3600087981] v2ray.com/core/transport/internet/websocket: creating connection to tcp:43.239.158.177:443
2020/03/06 12:58:57 tcp:127.0.0.1:60237 accepted tcp:r2---sn-i3b7knlk.googlevideo.com:443 [proxy] 
2020/03/06 12:58:58 [Info] [3600087981] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:r2---sn-i3b7knlk.googlevideo.com:443 via tcp:43.239.158.177:443
2020/03/06 12:58:58 [Info] [2378233245] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.youtube.com:443 via tcp:43.239.158.177:443

**Comment by yanue** [comment]
pac? pac模式有问题,重启试下
 手动模式需要外加插件
