### ISSUE TITLE
无法使用点击出现这个

### ISSUE THREAD

**Issue by voestey** [yanue/V2rayU#459]
HTTP error-listen tcp 127.0.0.0.1:1087:bind：address already in use 无法发送图片手动输入

**Comment by Tky9090** [comment]
我和你的一样的问题。

**Comment by biaogeg** [comment]
点一下“订阅设置”然后点顶部第二个按钮“advance”然后出来界面里面的“1087”改成“1088”然后保存

**Comment by biaogeg** [comment]
> HTTP error-listen tcp 127.0.0.0.1:1087:bind：address already in use 无法发送图片手动输入

点一下“订阅设置”然后点顶部第二个按钮“advance”然后出来界面里面的“1087”改成“1088”然后保存

**Comment by voestey** [comment]
> 点一下“订阅设置”然后点顶部第二个按钮“advance”然后出来界面里面的“1087”改成“1088”然后保存
没有出现1087啊 哪里改啊

**Comment by voestey** [comment]
@biaogeg 没看到1087啊 不知道哪里改啊

**Comment by voestey** [comment]
@biaogeg 一大片空白并没有1087啊

**Comment by eliotang** [comment]
为什么我改了之后也不能用啊

**Comment by yanue** [comment]
lsof -i :1087 然后 kill -9
