### ISSUE TITLE
0305更新了新版本v2rayU后发生了问题

### ISSUE THREAD

**Issue by Tky9090** [yanue/V2rayU#460]
打开新版本的v2rayU提示：http error-listen tcp 127.0.0.1:1087 bin:address already in use，
电脑系统：mac 10.15.4.
我已通过终端命令:lsof -i:1087   找到了这个端口，并用命令KILL -9 ***结束了这个占用端口的进程，但是还是不行。
电脑重启，重新安装v2rayU也已经测试过了，还请yanue大佬帮忙，谢谢！

**Comment by yanue** [comment]
换端口试下

**Comment by Tky9090** [comment]
已经解决了，终端删除占用端口是不行的，必须换其他端口，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yanue"<notifications@github.com&gt;; 
发送时间: 2020年3月6日(星期五) 晚上9:55
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;; 
抄送: "kenny"<277938796@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanue/V2rayU] 0305更新了新版本v2rayU后发生了问题 (#460)




换端口试下
