### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by kavin-lee** [yanue/V2rayU#462]
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
2020/03/07 12:30:41 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/03/07 12:30:41 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2020/03/07 12:30:41 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1080
2020/03/07 12:30:41 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2020/03/07 12:30:41 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/03/07 12:30:54 [Info] [2385349169] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.facebook.com:443
2020/03/07 12:30:54 [Info] [2385349169] v2ray.com/core/app/dispatcher: default route for tcp:www.facebook.com:443
2020/03/07 12:30:54 tcp:127.0.0.1:51766 accepted tcp:www.facebook.com:443 [proxy] 
2020/03/07 12:30:54 [Info] [2385349169] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:s207.wewall.xyz:8880
2020/03/07 12:30:54 [Info] [2385349169] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.facebook.com:443 via tcp:s207.wewall.xyz:8880
2020/03/07 12:30:54 [Info] [2385349169] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 35 but actually 142
2020/03/07 12:30:54 [Info] [2385349169] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
以上为配置了v2rayu启动，访问谷歌网站后的日志信息。
谢谢！

**Comment by yanue** [comment]
请查看config.json,并确认配置
