### ISSUE TITLE
tls servername在订阅时，应该通过什么参数传递到客户端？

### ISSUE THREAD

**Issue by NutterChen** [yanue/V2rayU#463]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
tls servername在订阅时，应该通过什么参数传递到客户端？
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by OliverBancroft** [comment]
希望能够指定在ws模式下时直接指定ws里的Host为serverName，不然SNI过不去

**Comment by NutterChen** [comment]
> 希望能够指定在ws模式下时直接指定ws里的Host为serverName，不然SNI过不去

是的，自己添加进去，然后导出url，居然发现没有这一项

**Comment by yanue** [comment]
试下2.2
