### ISSUE TITLE
config.json rewrite，import can't work

### ISSUE THREAD

**Issue by iSk2y** [yanue/V2rayU#464]
1. **版本**
最新 2.1（使用brew cask 安装的2.0也一样）

2. **问题**
在导入模式下，导入我的json配置文件后，点击左边“确定”，已显示save success，但文件内容被改变（貌似还原了）

![Xnip2020-03-08_10-59-35](https://user-images.githubusercontent.com/44657334/76155832-c7fe2b80-612c-11ea-9911-577881201a18.jpg)

再次点击后，还原了
![image](https://user-images.githubusercontent.com/44657334/76155854-10b5e480-612d-11ea-98b9-41437e1fb468.png)

尝试过直接在`/Applications/V2rayU.app/Contents/Resources/config.json`中修改配置文件，也被还原了

**Comment by yanue** [comment]
不能直接更改文件,会被覆盖,正常逻辑
