### ISSUE TITLE
2.1.0版本Pac自定义规则仍然无效

### ISSUE THREAD

**Issue by wonderffee** [yanue/V2rayU#465]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 2.1.0
Mac 10.14.6

2) 你遇到的问题是什么？
最近因为evernote.com网站被封锁，想把 evernote.com 添加到Pac自定义规则中，结果发现没用
① 从2.0.0升级到2.1.0 版本后Pac模式添加自定义规则测试仍然无效，之前的旧版本就是无效的，依然打不开 https://www.evernote.com/ClipperLogin.action?wck=clipper_chr 这个网址
② 重启V2ray后，之前在Pac中增加的自定义规则消息不见了，仿佛是重置了，或者根本没有保存。
③ 直接在 /Applications/V2rayU.app/Contents/Resources/pac/user-rule.txt 中添加自定义规则后，关闭V2ray开关再打开依然无效
④ 直接在 /Applications/V2rayU.app/Contents/Resources/pac/proxy.js中添加自定义规则，关闭V2ray开关再打开后，自定义规则生效

3) 请附上你的配置。
以下是在pac设置中设置的自定义规则
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||evernote.com^

4)  请附上出错时软件输出的错误日志。
无相关日志

**Comment by tpian928** [comment]
我也有这个问题，mark一下，看之后怎么解决。

**Comment by ediron-pr** [comment]
同样是这个问题，在配置文件里写好routing和dns，导入客户端要不就是invalid要不就是重启后这两项修改都没了。而且PAC模式下的速度很慢甚至有的网站直接打不开，但是开全局就能正常使用。。

**Comment by tpian928** [comment]
发现Firefox不好用，Safari是可以的。另外自定义的还需要加上.吧比如
```
.fabric.io
||fabric.io
||github.com
.github.com
appcenter.ms
.appcenter.ms
```

**Comment by yanue** [comment]
试下2.2

**Comment by welkinwalker** [comment]
我是2.2 设置也没有效果

**Comment by honyee** [comment]
版本：2.3.1
```
.demo.com         //二级域名
||part.com        //一级域名
```
以上这种格式也没毛病，但是需要添加进去之后点击 「**保存设置并从GFW List更新**」，然后**断开**连接**重新**连接就生效了。建议在以后的版本把域名添加进文本框时即可, 而不需要额外的动作。

**Comment by RoyCao1995** [comment]
> .fabric.io
> ||fabric.io
> ||github.com
> .github.com
> appcenter.ms
> .appcenter.ms

只能添加全局代理吗？直接连接怎么设置

**Comment by RoyCao1995** [comment]
> * 你正在使用的 V2RayU 和 Mac 版本 ？
>   V2RayU 2.1.0
>   Mac 10.14.6
> * 你遇到的问题是什么？
>   最近因为evernote.com网站被封锁，想把 evernote.com 添加到Pac自定义规则中，结果发现没用
>   ① 从2.0.0升级到2.1.0 版本后Pac模式添加自定义规则测试仍然无效，之前的旧版本就是无效的，依然打不开 https://www.evernote.com/ClipperLogin.action?wck=clipper_chr 这个网址
>   ② 重启V2ray后，之前在Pac中增加的自定义规则消息不见了，仿佛是重置了，或者根本没有保存。
>   ③ 直接在 /Applications/V2rayU.app/Contents/Resources/pac/user-rule.txt 中添加自定义规则后，关闭V2ray开关再打开依然无效
>   ④ 直接在 /Applications/V2rayU.app/Contents/Resources/pac/proxy.js中添加自定义规则，关闭V2ray开关再打开后，自定义规则生效
> * 请附上你的配置。
>   以下是在pac设置中设置的自定义规则
>   ! Put user rules line by line in this file.
>   ! See https://adblockplus.org/en/filter-cheatsheet
>   ||evernote.com^
> * 请附上出错时软件输出的错误日志。
>   无相关日志

只能添加全局代理吗？直接连接怎么设置

**Comment by RoyCao1995** [comment]
> 版本：2.3.1
> 
> ```
> .demo.com         //二级域名
> ||part.com        //一级域名
> ```
> 
> 以上这种格式也没毛病，但是需要添加进去之后点击 「**保存设置并从GFW List更新**」，然后**断开重连**就生效了。建议在以后的版本把域名添加进文本框时即可, 而不需要额外的动作。

只能添加全局代理吗？直接连接怎么设置

**Comment by wonderffee** [comment]
用了最新的3.0.3版本，不知道怎么弄了，最开始能用的改 pac/proxy.js 方法现在已经找不到这个文件了，在pac设置里点保存设置会提示failed to download latest GFW list

**Comment by Tr0py** [comment]
> 用了最新的3.0.3版本，不知道怎么弄了，最开始能用的改 pac/proxy.js 方法现在已经找不到这个文件了，在pac设置里点保存设置会提示failed to download latest GFW list

我解决了，这是因为GFW从raw.github下载但被墙了，解决方法是在User Pac里面加上
```
||githubusercontent.com
.githubusercontent.com
```
让v2rayU下载GFW List的时候走代理。
附上我的Pac list
```
||discord.com
discord.com
.discord.com
.github.com
||github.com
||githubusercontent.com
.githubusercontent.com
```
然后点`Save and Update Pac From GFW List` 之后断开重连一次，再save & update一边。

**Comment by Magikarp96** [comment]
User pac加入github方式可行 老哥牛逼
