### ISSUE TITLE
SSR订阅，可以显示服务器名称，但是无法上墙使用

### ISSUE THREAD

**Issue by afansong** [yanue/V2rayU#467]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by Jacob-pixil** [comment]
同样的问题，V2rayU的SSR似乎不能正常工作， 我用shadowsocks—NG-R8 尝试同样的服务器是正常上网的， 但是v2rayU不行， 望修复

**Comment by TomYule** [comment]
https://lncn.org/ 这个地址上面的服务器 shadowsocks—NG-R8  能用  但是  V2rayU 不行.
希望SSR 能批量导入 逗号分隔
可以参考
https://github.com/wzdnzd/ShadowsocksX-NG-R

**Comment by AboutCXJ** [comment]
遇到相同问题
V2RayU使用Vmess的订阅可正常使用，SSR不行，
相同的SSR订阅在ShadowsocksX-NG-R8可以正常使用。

**Comment by liliass** [comment]
只有SS能用。 SSR不行了。

**Comment by tyboyoole** [comment]
同！我的也是SSR无法使用

**Comment by yanue** [comment]
ssr不考虑了

**Comment by TomYule** [comment]
好吧  没有 稳定的V2Ray
只好改用 https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases
