### ISSUE TITLE
2.1.0版本CPU进程十分高

### ISSUE THREAD

**Issue by EasonWong** [yanue/V2rayU#469]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU版本 2.1.0
Mac：10.15.3

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
自从更新了新的版本的V2RayU之后，当网络环境发生变化（例如WIFI切换后），在进程里面，会发现V2RayHelper的进程占比超过100%，甚至一度达到1000%，此时CPU风扇开足最高功率，温度超过了90度。
关闭V2RayU并没办法改善此问题，一定要手动在活动监视器中强制退出V2RayHelper，才能解决问题。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
不懂，抱歉...
4)  请附上出错时软件输出的错误日志。
不懂，抱歉...

**Comment by Clear-up** [comment]
同样问题，经常要占一整个核心，耗电也很高

**Comment by yosefl20** [comment]
preference中关掉automatically update servers from subscriptions貌似就好了

**Comment by EastLord** [comment]
用2.0

**Comment by jaxwang** [comment]
同样出现这个问题...

**Comment by King-Ran** [comment]
+1 而且程序退出了，在活动监视器中还能看到。CPU 100% + 运行

**Comment by lawrenceching** [comment]
发现同样的问题。
<img width="336" alt="截屏2020-03-13下午12 01 47" src="https://user-images.githubusercontent.com/12114025/76588869-2e1af200-6523-11ea-9b41-a9f92d7616a4.png">

**Comment by echo-layker** [comment]
同样的问题，
![image](https://user-images.githubusercontent.com/10571512/76699511-02496900-66e9-11ea-9449-5bf8fe62da43.png)

[Sample of V2rayUHelper.txt](https://github.com/yanue/V2rayU/files/4334014/Sample.of.V2rayUHelper.txt)

**Comment by Victarry** [comment]
同样的问题+1

**Comment by ligongnan** [comment]
同样的问题+1

**Comment by a1392429292** [comment]
完全卸载旧版，全新安装V2RayU-2.1.0，依然会出现  电脑起飞的 情况，所以不存在从旧版在线升级新版而产生的，是2.1.0 实实在在的存在 高进程的问题。现在回到了2.0版本，暂时没有出现，电脑起飞八九十度的情况。

**Comment by chenzz** [comment]
同样出现了这个问题，啥情况？

**Comment by twm17** [comment]
遇到同样的问题 已回滚2.0 暂时无问题 机器温度一下就降下来了

**Comment by foxgoblin** [comment]
遇到同样问题。

**Comment by imapach** [comment]
+1

**Comment by Justsoos** [comment]
2.1.0 会导致 macos 网络协议栈锁死，已经是让mac被迫重启最多的软件了。只能卸载装旧版本了

**Comment by hhhaiai** [comment]
+1

**Comment by yanue** [comment]
试下2.2

**Comment by DiveInto** [comment]
👏 

![image](https://user-images.githubusercontent.com/698482/83234033-3ac5f280-a1c2-11ea-8c19-6ff6b46e08e3.png)

**Comment by a1392429292** [comment]
没等到作者升级，就买软路由了，现在v2ray架设到路由器上，就不管了。。。舒服且安逸了。。。各位，bye
