### ISSUE TITLE
OSX 休眠后唤醒，似乎要禁用并重新启用一下

### ISSUE THREAD

**Issue by pizzamx** [yanue/V2rayU#47]
OS 版本：10.14.4
刚用几天，观察了一下似乎是这样，唤醒后要禁用再启用才能正常使用，不知道有没有人跟我一样

**Comment by yanue** [comment]
已经唤醒重启服务的 估计测试不到位吧

**Comment by Nojike** [comment]
You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.

v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

v2ray.com/core/transport/internet/kcp: #61480 terminating connection to ************

info级别log提示这个。是客户端问题还是服务端问题？

**Comment by pizzamx** [comment]
1.2.3 应该是修复了
