### ISSUE TITLE
socks error - listen tcp: lookup tcp/1 080: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by Tiisetso** [yanue/V2rayU#471]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU v2.1.0 Mac 10.15.3

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
Was working perfectly then I updated to the v2.1.0. 
Now when I try to turn on the core, 

"socks error - listen tcp: lookup tcp/1 080: nodename nor servname provided, or not known"

Tried changing ports. 

Deleted .plist.

Total uninstallation and clean reinstallation of V2RayU.

Doesn't help.

Additionally. I have re-added the the configuration by QR code and URL. Sometimes I get "invalid inbound.port" sometimes it works. Again, adding automatically, no manual input. 

Even if I rollback to the previous v2RayU release it also doesn't work now. I'm not sure what has changed. 

V2Ray still works on my iPhone using ShadowRocket.

Please help.

P.S. Your software is amazing. Easily the best client, thank you for it.

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
  {
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1 080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1 087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/",
          "headers": {
            "host": "<REMOVED>"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "<REMOVED>",
            "users": [
              {
                "id": "<REMOVED>",
                "alterId": 233,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。

v2ray-core.log is empty.

"socks error - listen tcp: lookup tcp/1 080: nodename nor servname provided, or not known"

**Comment by Tiisetso** [comment]
I think it might be an issue with v2.1.0. After reading some subsequent bug issues I did a port scan and found constant activity on 1086/87 regardless of whether V2ray was on or not. So I uninstalled it again, clearing every single associated file. Ran a port case, 1086/87 now free. Installed v2.0.0 and everything is working as normal. No changes to server.

<img width="756" alt="Screenshot 2020-03-10 at 08 14 13" src="https://user-images.githubusercontent.com/4865991/76280886-5231c580-62ce-11ea-8f4c-a637f41fe123.png">


I recommend waiting

**Comment by yanue** [comment]
试下2.2

**Comment by MPTres** [comment]
This keeps happening in Catalina 10.15.4 (19E287)

The problems seem to be that depending on the system languages, the port text field in preferences use commas. 
<img width="453" alt="preferences-screen" src="https://user-images.githubusercontent.com/22724255/83517071-d6c96400-a50a-11ea-9aa4-630329841591.png">

<img width="707" alt="preferences-file" src="https://user-images.githubusercontent.com/22724255/83517091-e052cc00-a50a-11ea-9413-1cc7c8460d42.png">

And then, the port number is stored in preferences with that commas:
![Uploading preferences-screen.png…]()



when that happens, we get that error. If i manually change the numbers in the preferences file (net.yanue.V2rayU.plist) to remove the comman, the core starts fine.

**Comment by jason-shen** [comment]
> @yanue This keeps happening in Catalina 10.15.4 (19E287)
> 
> The problems seem to be that depending on the system language, the port text field in preferences uses periods instead of commas.
> <img alt="preferences-screen" width="453" src="https://user-images.githubusercontent.com/22724255/83517071-d6c96400-a50a-11ea-9aa4-630329841591.png">
> 
> And then, the port number is stored in preferences with the period:
> <img alt="preferences-file" width="707" src="https://user-images.githubusercontent.com/22724255/83517091-e052cc00-a50a-11ea-9413-1cc7c8460d42.png">
> 
> when that happens, we get that error. If i manually change the numbers in the preferences file (net.yanue.V2rayU.plist) to remove the period, the core starts fine.

what location is net.yanue.V2rayU.plist located, i couldn't find this file at all, just want to change it manually until the next release

cheers

**Comment by Tiisetso** [comment]
> > @yanue This keeps happening in Catalina 10.15.4 (19E287)
> > The problems seem to be that depending on the system language, the port text field in preferences uses periods instead of commas.
> > <img alt="preferences-screen" width="453" src="https://user-images.githubusercontent.com/22724255/83517071-d6c96400-a50a-11ea-9aa4-630329841591.png">
> > And then, the port number is stored in preferences with the period:
> > <img alt="preferences-file" width="707" src="https://user-images.githubusercontent.com/22724255/83517091-e052cc00-a50a-11ea-9413-1cc7c8460d42.png">
> > when that happens, we get that error. If i manually change the numbers in the preferences file (net.yanue.V2rayU.plist) to remove the period, the core starts fine.
> 
> what location is net.yanue.V2rayU.plist located, i couldn't find this file at all, just want to change it manually until the next release
> 
> cheers

~/Library/Preferences/net.yanue.V2rayU.plist
