### ISSUE TITLE
v2ray 进程无法关闭

### ISSUE THREAD

**Issue by thiner** [yanue/V2rayU#474]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
_V2Ray: **2.0.0**_
_Mac: **10.13.6**_

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
_在关闭V2RayU之后，v2ray进程依然在后台运行，占用了1087端口。导致无法启动别的socks代理，比如ShadowSocks。更糟糕的是，即使在监视器里强制退出，或是在terminal里用`kill -9`关闭进程，也会立刻重启新进程。_

**Comment by EasonWong** [comment]
没有设置开机启动V2RayU，但是开机之后发现Telegram能实用，即是Sock监听的1086端口在工作，即使软件没打开，依然在后台工作

**Comment by thiner** [comment]
> 没有设置开机启动V2RayU，但是开机之后发现Telegram能实用，即是Sock监听的1086端口在工作，即使软件没打开，依然在后台工作

是的，我也发现了这样的问题。我把v2rayU删除后，重启系统，依然在系统日志里能看到v2ray不断地在打印log，说找不到v2rayU. 后来找到了它的一个守护程序。通过这个命令卸载后就好了。
`launchctl remove yanue.v2rayu.v2ray-core`

**Comment by yanue** [comment]
正确做法:  设置->去掉自动启动
强制:
launchctl remove yanue.v2rayu.v2ray-core

**Comment by dodoru** [comment]
launchctl remove yanue.v2rayu.v2ray-core
launchctl remove net.yanue.V2rayU.Launcher

**Comment by shuiRong** [comment]
补充个查询（筛选）守护进程列表的语句：
```
# 查看任务列表, 使用 grep '任务部分名字' 过滤
$ launchctl list | grep 'v2ray'
```

**Comment by shijiezhou1** [comment]
> 正确做法: 设置->去掉自动启动 强制: launchctl remove yanue.v2rayu.v2ray-core

You safe my life

**Comment by EthanCCYX** [comment]
> 

hhhhh，you mean "You save my life"？
