### ISSUE TITLE
非管理员用户闪退

### ISSUE THREAD

**Issue by ajeep8** [yanue/V2rayU#477]
非管理员用户闪退，查日志是因为没有Resources目录的写权限，chmod 777 Resources后勉强可用(可能还会有别的问题)。ping.json、config.json、pac等应该放在用户的个人目录下。

**Comment by yaohwu** [comment]
[v2rayCrashed.txt](https://github.com/yanue/V2rayU/files/4367136/v2rayCrashed.txt)
it will crash when ensuring config

**Comment by xpol** [comment]
多用户下也是这样多。
A用户安装了V2rayU，B用户登录mac，然后尝试打开 V2rayU 也会这样。

**Comment by Kiloland** [comment]
同遇到此问题。
看log显示为在resources文件夹下没有权限导致。
进入Finder内，选择Applications文件夹
1.右键V2rayU,点击Get Info,在Sharing & Permissions内添加目标用户并将Privilege改为Read&Write
2.再次右键V2rayU,点击Show Package Contens,右击Contens再次点击Get Info,在Sharing & Permissions内添加目标用户并将Privilege改为Read&Write，同时点击设置的图标选择 Apply to enclosed items..
应该可以解决该问题。

**Comment by yanue** [comment]
多用户暂时不处理
