### ISSUE TITLE
如何更换 menubar 图标

### ISSUE THREAD

**Issue by angao** [yanue/V2rayU#481]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

- V2rayU: 2.1.0
- Mac: 10.15.3 

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

- 希望更换 menubar 图标

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by kptanjunhao** [comment]
下载源码，自己替换再打包。
