### ISSUE TITLE
socket error - listen tcp 127.0.0.1:1080: bind: address already in use

### ISSUE THREAD

**Issue by 36ldq36** [yanue/V2rayU#482]
更新2.1.0后，启动应用，会出现此错误。

重新用旧版本2.0.0替换安装，启动应用，正常使用。

macOS：10.15.3

**Comment by sch1111878** [comment]
一般这个问题重启电脑就可以了

**Comment by xsun2001** [comment]
也有同样的问题
重启mac没有效果

**Comment by Jasonxiaotian** [comment]
换一个端口

**Comment by houkeepmoving** [comment]
> 换一个端口
换一个端口后 翻不了墙了

**Comment by houkeepmoving** [comment]
> 也有同样的问题
> 重启mac没有效果

我也重启了 没效果

**Comment by AlexYuan** [comment]
这个根据我踩过的坑，一般是原来的翻墙软件没有卸载干净，启动占用了1080了。
一般这边处理就可以了：
cd ~/Library/Application\ Support
sudo rm -rf V2RayX
sudo rm -rf ShadowsocksX-NG
sudo rm -rf ShadowsocksX-R

**Comment by Kirito0512** [comment]
> 这个根据我踩过的坑，一般是原来的翻墙软件没有卸载干净，启动占用了1080了。
> 一般这边处理就可以了：
> cd ~/Library/Application\ Support
> sudo rm -rf V2RayX
> sudo rm -rf ShadowsocksX-NG
> sudo rm -rf ShadowsocksX-R

亲测，执行后，重启电脑就行了~
