### ISSUE TITLE
开启easyconnect后V2RayU无法进行代理

### ISSUE THREAD

**Issue by blackbk** [yanue/V2rayU#485]
1) 你正在使用的 V2RayU 和 Mac 版本 ：
    v2rayu: v2.1.0  
    macos: 10.15.3

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    开启easyconnect后，V2RayU无法进行代理，日志可以显示出创建proxy连接，但是没有错误输出，但是用shadowsocks-ng和classX是可以同时进行代理的。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    已排除端口占用冲突

**Comment by litt1e-p** [comment]
same problem

**Comment by fraee** [comment]
> 1. 你正在使用的 V2RayU 和 Mac 版本 ：
>    v2rayu: v2.1.0
>    macos: 10.15.3
> 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    开启easyconnect后，V2RayU无法进行代理，日志可以显示出创建proxy连接，但是没有错误输出，但是用shadowsocks-ng和classX是可以同时进行代理的。
> 3. 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
>    已排除端口占用冲突

我遇到了同样的问题，自己写了个脚本，可以将vmess连接中的域名转换为ip地址，重新组装订阅源，在作者修复issues之前，可以应急使用。

https://github.com/fraee/vmess-domain-coverter

**Comment by yanue** [comment]
#468
