### ISSUE TITLE
什么时候出个iOS端的

### ISSUE THREAD

**Issue by lil-hope** [yanue/V2rayU#488]
1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
请出一个iOS端的代码
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

4)  请附上出错时软件输出的错误日志。

**Comment by kptanjunhao** [comment]
你可以用小火箭，shadowrocket

**Comment by lil-hope** [comment]
> 你可以用小火箭，shadowrocket

怎么用
