### ISSUE TITLE
服务可用，ping 测试显示 -1ms。

### ISSUE THREAD

**Issue by sshallow** [yanue/V2rayU#489]
1) 正在使用的 V2RayU 和 Mac 版本 ？
v2.1.0  MacOS 10.15.3
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
 **服务可用，服务可用，服务可用，** ping 测试显示 -1ms。
<img width="637" alt="image" src="https://user-images.githubusercontent.com/21257340/76814338-7b55d700-6835-11ea-9471-fc90a6dc3836.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/21257340/76814252-3a5dc280-6835-11ea-91b5-f4f63d90628a.png">

**Comment by W-quan** [comment]
+1

**Comment by dsky1990** [comment]
+1

**Comment by yanue** [comment]
试下2.2
