### ISSUE TITLE
耗电巨大，机器起飞

### ISSUE THREAD

**Issue by a1392429292** [yanue/V2rayU#490]
Mac版本：10.15.3
V2rayU版本：2.1.0

查看 活动监视器，V2rayU都排第一位，比耗内存大户的chrome高3倍，啥也没做，Macbook pro 16温度在75度左右，卸载V2rayU后，温度恢复正常的30-40度左右

**Comment by 0es** [comment]
结束v2rayuhelper进程可恢复
目测speed test过程不正常或者未正常结束导致，等待官方修复

**Comment by a1392429292** [comment]
> 结束v2rayuhelper进程可恢复
> 目测ping test过程不正常或者未正常结束导致，等待官方修复

彻底卸载旧版本，重新安装最新版V2rayU，使用几小时未出现无故发烫的情况，后期我再反馈

**Comment by 0es** [comment]
好像是低版本更新到2.1才会出现这种情况
开发者确认下吧

**Comment by lawrenceching** [comment]
我觉得可以关闭这个issue，然后去 #469 点个赞。
