### ISSUE TITLE
是否考虑增加快捷键切换代理模式时，只在特定2种模式间切换的功能（现为3模式循环）

### ISSUE THREAD

**Issue by Dragon-Yu** [yanue/V2rayU#491]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU版本：2.1.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
功能改进建议：
目前使用快捷键切换代理模式时，只能在PAC，全局，手动三种模式中循环切换。对于只惯用其中2种的用户，切换过程很不优雅。
是否考虑优化交互，可以设置将一种模式排除出 快捷键切换代理模式 的切换序列，做到只在2种常用模式间来回切换。（比如在设置页面加一条设置项，选择一个代理模式排除出快捷键切换时的模式序列）

Bug label非我本意，如果可以请移除。

**Comment by mengoreo** [comment]
> 1. 你正在使用的 V2RayU 和 Mac 版本 ？
>    V2RayU版本：2.1.0
> 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    功能改进建议：
>    目前使用快捷键切换代理模式时，只能在PAC，全局，手动三种模式中循环切换。对于只惯用其中2种的用户，切换过程很不优雅。
>    是否考虑优化交互，可以设置将一种模式排除出 快捷键切换代理模式 的切换序列，做到只在2种常用模式间来回切换。（比如在设置页面加一条设置项，选择一个代理模式排除出快捷键切换时的模式序列）
> 
> Bug label非我本意，如果可以请移除。
同求，手动模式切换后会改系统代理，然后就gg辽

**Comment by mengoreo** [comment]
> 1. 你正在使用的 V2RayU 和 Mac 版本 ？
>    V2RayU版本：2.1.0
> 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    功能改进建议：
>    目前使用快捷键切换代理模式时，只能在PAC，全局，手动三种模式中循环切换。对于只惯用其中2种的用户，切换过程很不优雅。
>    是否考虑优化交互，可以设置将一种模式排除出 快捷键切换代理模式 的切换序列，做到只在2种常用模式间来回切换。（比如在设置页面加一条设置项，选择一个代理模式排除出快捷键切换时的模式序列）
> 
> Bug label非我本意，如果可以请移除。

我下了源码，自己改了下😂

**Comment by Dragon-Yu** [comment]
> > 1. 你正在使用的 V2RayU 和 Mac 版本 ？
> >    V2RayU版本：2.1.0
> > 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
> >    功能改进建议：
> >    目前使用快捷键切换代理模式时，只能在PAC，全局，手动三种模式中循环切换。对于只惯用其中2种的用户，切换过程很不优雅。
> >    是否考虑优化交互，可以设置将一种模式排除出 快捷键切换代理模式 的切换序列，做到只在2种常用模式间来回切换。（比如在设置页面加一条设置项，选择一个代理模式排除出快捷键切换时的模式序列）
> > 
> > Bug label非我本意，如果可以请移除。
> 
> 我下了源码，自己改了下😂

厉害。哥们你是把手动模式直接去掉了还是怎样？是否介意源码上传一份，我从你仓库下载编译一个？

**Comment by yanue** [comment]
不考虑

**Comment by fanlb** [comment]
> > 1. 你正在使用的 V2RayU 和 Mac 版本 ？
> >    V2RayU版本：2.1.0
> > 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
> >    功能改进建议：
> >    目前使用快捷键切换代理模式时，只能在PAC，全局，手动三种模式中循环切换。对于只惯用其中2种的用户，切换过程很不优雅。
> >    是否考虑优化交互，可以设置将一种模式排除出 快捷键切换代理模式 的切换序列，做到只在2种常用模式间来回切换。（比如在设置页面加一条设置项，选择一个代理模式排除出快捷键切换时的模式序列）
> > 
> > Bug label非我本意，如果可以请移除。
> 
> 我下了源码，自己改了下😂

大佬, 修改后的版本, 可以发送一份嘛 callback.gz@gmail.com  万分感谢!

**Comment by vencewill** [comment]
> > > 1. 你正在使用的 V2RayU 和 Mac 版本 ？
> > >    V2RayU版本：2.1.0
> > > 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
> > >    功能改进建议：
> > >    目前使用快捷键切换代理模式时，只能在PAC，全局，手动三种模式中循环切换。对于只惯用其中2种的用户，切换过程很不优雅。
> > >    是否考虑优化交互，可以设置将一种模式排除出 快捷键切换代理模式 的切换序列，做到只在2种常用模式间来回切换。（比如在设置页面加一条设置项，选择一个代理模式排除出快捷键切换时的模式序列）
> > > 
> > > Bug label非我本意，如果可以请移除。
> > 
> > 
> > 我下了源码，自己改了下😂
> 
> 大佬, 修改后的版本, 可以发送一份嘛 [callback.gz@gmail.com](mailto:callback.gz@gmail.com) 万分感谢!

没有源码了，当时在本地改的，后面直接用 Clash X 了哈哈
