### ISSUE TITLE
Ping Speed 影响能耗

### ISSUE THREAD

**Issue by InjoyDeng** [yanue/V2rayU#492]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.1.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
如果「Ping Speed」后，能耗非常大，并且将一直持续，CPU温度一直降不下去。
活动监视器显示，影响能耗的进程叫 V2RayUHleper，结束该进程后 CPU 温度就降下来了

**Comment by alfred-zhong** [comment]
我也遇到了这个问题。V2RayUHleper CPU 占用比较大，每次我都手动 kill 掉了。但是过个一段时间又会开始。（当然我不清楚倒是是否是 Ping Speed 导致的）
能否价格开关，可以选择关闭自动 Ping Speed 功能。

**Comment by FlyingMiaow** [comment]
同样的问题，中午电脑还是满电，午觉起来居然只剩1%了，一看统计全被v2rayu给耗完了

**Comment by weinierfei** [comment]
<img width="795" alt="WX20200324-212232@2x" src="https://user-images.githubusercontent.com/11873816/77430152-b0ee5780-6e15-11ea-9fd0-fc8d21f06179.png">
Ping Speed 一直处于测试中,用不了了,cup占用高,macfen风扇呼呼的响

**Comment by 774649283** [comment]
我的也是 ，我退出了，但是进程还在，占用cpu电脑发热严重。每次都是监控台强制退出

**Comment by yanue** [comment]
试下2.2
