### ISSUE TITLE
Inbounds使用dokodemo-door协议提示invalid inbound protocol

### ISSUE THREAD

**Issue by EncourageCong** [yanue/V2rayU#494]
v2ray 配置如下
`{
    "inbounds":[
        {
            "port":"1088",
            "protocol":"dokodemo-door",
            "settings":{
                "address":"xxx.xxx.xxx.xx",
                "port":443,
                "network":"tcp,udp",
                "followRedirect":true
            }
        },
        {
            "listen":"127.0.0.1",
            "protocol":"socks",
            "settings":{
                "udp":true,
                "auth":"noauth"
            },
            "port":"1080"
        }
    ],
    "outbounds":[
        {
            "mux":{
                "enabled":true,
                "concurrency":8
            },
            "protocol":"vmess",
            "streamSettings":{
                "wsSettings":{
                    "path":"/",
                    "headers":{
                        "host":"www.xxxx.com"
                    }
                },
                "tlsSettings":{
                    "allowInsecure":false
                },
                "security":"tls",
                "network":"ws"
            },
            "tag":"proxy",
            "settings":{
                "vnext":[
                    {
                        "address":"127.0.0.1",
                        "users":[
                            {
                                "id":"11111-yyyy-0f512953c497xxx",
                                "alterId":64,
                                "level":0,
                                "security":"auto"
                            }
                        ],
                        "port":1088
                    }
                ]
            }
        },
        {
            "tag":"direct",
            "protocol":"freedom",
            "settings":null
        }
    ]
}`

使用v2ray-core直接运行是没问题的，但是使用v2rayU图形导入时，提示“Invalid inbound protocol”

**Comment by yanue** [comment]
不支持inbounds的dokodemo-door协议
