### ISSUE TITLE
v2rayUHelper进程偶尔会占用百分百的资源导致严重发热

### ISSUE THREAD

**Issue by StevenXu98** [yanue/V2rayU#495]
mac10.15 v2ray-core 2.1.0
v2rayhelper进程偶尔会占用百分百的资源导致严重发热，关闭后无效，只有手动杀死进程

**Comment by StevenXu98** [comment]
![截屏2020-03-2017.55.46.png](https://i.loli.net/2020/03/20/5YDhgeqOaQnbtd6.png)

**Comment by skyWalker1997** [comment]
目前可以通过活动监视器杀死该进程

**Comment by jarnanchen** [comment]
the same as #495

**Comment by twm17** [comment]
不是偶尔 是一直 实在无解 已回滚2.0版本 貌似无这个问题 等下一个版本修复 感谢作者

**Comment by naturezhm** [comment]
2.10这个版本除了这个问题外，其他都挺好的

**Comment by liguidong** [comment]
同样遇到此问题，之前非常疑惑，mbp为何拔掉电源之后居然只能撑一个小时，起初以为chrome耗电，后来改为safari发现续航依然辣鸡，看耗电排行第一个是V2ray，遂退出，没想到问题依旧，最后看cpu占用率才发现还有个helper进程.....

**Comment by wanlinus** [comment]
![image](https://user-images.githubusercontent.com/34122643/77601273-489e9380-6f45-11ea-97ba-18b26a863825.png)
我也遇到了这个问题, 操作系统是10.15.3

**Comment by yankun9527** [comment]
我也遇到这个问题，基本上就吃掉两个CPU

**Comment by wanlinus** [comment]
> 我也遇到这个问题，基本上就吃掉两个CPU

现在我找到的解决办法是使用ClashX

**Comment by daidai21** [comment]
> ![image](https://user-images.githubusercontent.com/34122643/77601273-489e9380-6f45-11ea-97ba-18b26a863825.png)
> 我也遇到了这个问题, 操作系统是10.15.3

+1

**Comment by 2flyfish** [comment]
alias calm="sudo killall V2rayUHelper"
杀掉此进程
然后禁用 General -> Automatically update /select等

**Comment by yanue** [comment]
试下2.2
