### ISSUE TITLE
V2RayU 代理规则在手动模式下时切换代理服务器会去更改系统代理

### ISSUE THREAD

**Issue by fzred** [yanue/V2rayU#498]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
10.14.6  V2rayU **2.1.0**

2) 你遇到的问题是什么？
我同时使用其他代理软件 SpechtLite ，并将其设置为**系统代理**。V2RayU 代理规则是 **手动模式**，但是切换代理服务器时系统代理会被**V2RayU**更改。

3) 期望效果
V2RayU 处于手动模式时，切换代理服务器**不要去修改系统代理的设置**。

Thank  :)

**Comment by phith0n** [comment]
同求，每次我的系统代理都被清空

**Comment by yanue** [comment]
比如之前是pac模式, 切换到手动模式,那是不是需要把之前系统配置的pac去掉呢? 
所以还是要修改系统代理

**Comment by yanue** [comment]
#740
