### ISSUE TITLE
v2.1版本 h2 方式 tls 加密协议无法代理成功

### ISSUE THREAD

**Issue by lpyedge** [yanue/V2rayU#499]
v2.1版本 h2 方式 tls 加密协议无法代理成功
但是用v2rayN可以正常代理生效
仔细对照了v2rayN生成得配置信息和v2rayu里面得配置信息,
除了httpSettings里面得host一个是空值一个是数组,其他基本没有区别.我手动修改v2rayu得对应host得值未空值后直接v2rayu就崩溃了...

**Comment by RRRRRm** [comment]
同样的问题

**Comment by RRRRRm** [comment]
在windows和android下可用的h2协议, 在V2rayU中不可用
报错显示:
```
2020/03/24 03:01:00 [Warning] [3628056049] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status404] > v2ray.com/core/common/retry: all retry attempts failed
```

**Comment by yanue** [comment]
请确认其他参数, host可以设置为空试下, 我本身一直用的就是h2模式

**Comment by MichaelMa666** [comment]
同样的问题。2.2.0也不行。

**Comment by MichaelMa666** [comment]
> 同样的问题。2.2.0也不行。




> 同样的问题。2.2.0也不行。




> 同样的问题。2.2.0也不行。

![image](https://user-images.githubusercontent.com/17587845/86192812-00fb5980-bb7d-11ea-9d09-fb888bf94a1f.png)

**Comment by MichaelMa666** [comment]
> 同样的问题。2.2.0也不行。

同样的配置在手机上v2rayNG是可以用的。

**Comment by yuanyan89** [comment]
跟ls配置一样我也是同样的问题，其他客户端OK，mac上就是不行，求解

**Comment by CloudWzhZzz** [comment]
附议，其他客户端都可以，就是h2不可以

**Comment by CloudWzhZzz** [comment]
附议，其他客户端都可以，就是h2不可以

**Comment by CloudWzhZzz** [comment]
找到解决办法了，原来的host字段是这样的："host": [""],改成："host": ""，去掉中括号即可正常使用h2+tls模式！
