### ISSUE TITLE
把quic支持加上吧

### ISSUE THREAD

**Issue by txdywy** [yanue/V2rayU#5]

**Comment by yanue** [comment]
这个我了解了下 应该属于v2ray-core的范畴把：https://github.com/v2ray/v2ray-core/issues/1137

**Comment by txdywy** [comment]
4.7的core已经支持了,应该主要是ui支持下吧,别的client都还没有

**Comment by yanue** [comment]
好吧 4.7  还没看

**Comment by txdywy** [comment]
😆用上了
