### ISSUE TITLE
v2.1.0 http代理没有启动

### ISSUE THREAD

**Issue by wkj89** [yanue/V2rayU#500]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
  v2.1.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
  http 代理默认没有启动
![image](https://user-images.githubusercontent.com/18138184/77229573-ca02c880-6bc9-11ea-8962-9051d989b595.png)

**Comment by yanue** [comment]
重启服务试下
