### ISSUE TITLE
mac上两个用户，一个用户装了能开，另外一个用户打不开

### ISSUE THREAD

**Issue by ryan7cruise** [yanue/V2rayU#501]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU v2.1
macOS 10.15.3

2) 你遇到的问题是什么？
mac上两个用户，一个用户装了能开，另外一个用户打不开。能开的用户关闭了V2RayU，另一个用户也还是不能打开。

**Comment by Kiloland** [comment]
同遇到此问题。
看log显示为在resources文件夹下没有权限导致。
进入Finder内，选择Applications文件夹
1.右键V2rayU,点击Get Info,在Sharing & Permissions内添加目标用户并将Privilege改为Read&Write
2.再次右键V2rayU,点击Show Package Contens,右击Contens再次点击Get Info,在Sharing & Permissions内添加目标用户并将Privilege改为Read&Write，同时点击设置的图标选择 Apply to enclosed items..
应该可以解决该问题。

**Comment by yanue** [comment]
这个是安装时候,已经确认的一些重要文件及目录, 比如: 
``` /Users/用户/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist ```
暂时不考虑修改
