### ISSUE TITLE
CONNECT 没有走 PAC

### ISSUE THREAD

**Issue by wenxq** [yanue/V2rayU#507]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

v2rayU 2.1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
http connect 请求没有走 PAC 规则

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by Gabirel** [comment]
问题+1

**Comment by Gabirel** [comment]
更新：应该是设置完了之后没有立刻走PAC，需要重启v2rayU才会走。保存过后不重启无法走PAC

**Comment by yanue** [comment]
试下2.2
