### ISSUE TITLE
http error - listen tcp 127.0.0.1:1080: bind: address already in use 

### ISSUE THREAD

**Issue by Jason-YangPeiLin** [yanue/V2rayU#508]
http error - listen tcp 127.0.0.1:1080: bind: address already in use

**Comment by monsterhxw** [comment]
同出现此错误。

```
2020/03/27 13:40:51 [Info] v2ray.com/core/app/dns: DNS: created localhost client
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
```

**Comment by kptanjunhao** [comment]
端口被占用，可以用lsof -i:1080查看端口被什么应用占用，然后kill -9剔除那个进程再开。

**Comment by bigmonster-g** [comment]
同一个问题。bigmonster@promote ~ % lsof -i:1087
COMMAND  PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
privoxy 1193 bigmonster    3u  IPv4 0xf65a85eff99359f7      0t0  TCP localhost:cplscrambler-in (LISTEN)
用上楼方法莫名其妙解决过一次，重启继续这个问题，上楼方法就无用了。很有可能是我不会用，继续求解答。谢谢。

**Comment by AlexYuan** [comment]
这个根据我踩过的坑，一般是原来的翻墙软件没有卸载干净，启动占用了1080了。
一般这边处理就可以了：
cd ~/Library/Application\ Support
sudo rm -rf V2RayX
sudo rm -rf ShadowsocksX-NG
sudo rm -rf ShadowsocksX-R
诸如此类，还有蓝灯什么的，如果你用过。

**Comment by lonelymast** [comment]
同出现这个问题

**Comment by sheldon261** [comment]
同出现此问题

**Comment by todayqq** [comment]
同出现此问题

**Comment by BetterYifan** [comment]
+1，kill pid后还是无效；进到Application目录下rm之前的shadows也没用

**Comment by messi84** [comment]
同出现此问题

**Comment by messi84** [comment]
同出现此问题
执行下面这个也没有用
cd ~/Library/Application\ Support
sudo rm -rf V2RayX
sudo rm -rf ShadowsocksX-NG
sudo rm -rf ShadowsocksX-R

**Comment by yanue** [comment]
> 端口被占用，可以用lsof -i:1080查看端口被什么应用占用，然后kill -9剔除那个进程再开。

使用此方法解决
