### ISSUE TITLE
ping speed 失效

### ISSUE THREAD

**Issue by AlexYuan** [yanue/V2rayU#510]
一直显示测试中，都是-1ms,重启也是这样。

![image](https://user-images.githubusercontent.com/1269376/78004140-4c2e8200-736c-11ea-9fd4-08ffc5b70bfe.png)

**Comment by dsky1990** [comment]
+1

**Comment by assemblyios** [comment]
+1

**Comment by stevieyu** [comment]
+1

**Comment by yanue** [comment]
试下2.2
