### ISSUE TITLE
一段时间后V2RayUhelper的CPU占用率达到100%

### ISSUE THREAD

**Issue by evilhentaro** [yanue/V2rayU#512]
V2RayU 2.1.0
MacOS 10.15.4

正常使用一段时间后CPU使用率到达100%，风扇狂转，打开Activity Monitor看到V2RayUhelper的CPU使用率占满。

**Comment by RyanChill94** [comment]
![image](https://user-images.githubusercontent.com/12482300/78331555-e2ef7e80-75b8-11ea-8a3f-19fc5f3acd1e.png)
相同情况，点了测速

**Comment by yquan** [comment]
我的也是。

![image](https://user-images.githubusercontent.com/1085871/78505703-d715df00-77a7-11ea-9d9b-adb3b1f9076c.png)

**Comment by lichao-eric** [comment]
风扇转的停不下来

**Comment by denvor** [comment]
yes , me too. 在终端用 top 命令看能看到 CPU 大于 100 ， 使用菜单退出也没有用，必须在命令行去 kill 掉进程才行。

**Comment by denvor** [comment]
看起来是网络切换之后造成的。

**Comment by socmap** [comment]
我的也是，还经常卡死。

**Comment by SR2k** [comment]
``` bash
alias calm="sudo killall V2rayUHelper"
```

一键冷静你的 Mac（逃

**Comment by Great-Li-Xin** [comment]
感觉像是有挖矿脚本在跑啊

**Comment by yanue** [comment]
ping的问题 试下2.2
