### ISSUE TITLE
关闭了流量检测 还是连接不上tor

### ISSUE THREAD

**Issue by daveleenew** [yanue/V2rayU#514]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
最新版本你能
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
作为tor的前置代理连接不上
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

![image](https://user-images.githubusercontent.com/34392697/78169179-96565700-7483-11ea-814c-553a9cc97fc6.png)
![image](https://user-images.githubusercontent.com/34392697/78169230-a4a47300-7483-11ea-9ce0-e479df87f9d8.png)

请预览一下你填的内容再提交。

**Comment by MrPoopyLobster** [comment]
我也是相同的问题，换V2rayX就没问题

**Comment by Alantodamoon** [comment]
> 我也是相同的问题，换V2rayX就没问题

V2rayX可以disable sniffing吗？客户端上没有选项，修改config文件也无法生效。求教，你是怎么配置的？感谢🙏
