### ISSUE TITLE
2.0.0版本,开启pac模式,git pull或者push非常慢, ssl超时

### ISSUE THREAD

**Issue by dream-mo** [yanue/V2rayU#517]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

          V2RayU:  2.0.0
          macos版本: 10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

    开启pac模式之后， git pull或者 git push卡死，debug查看 TLS握手一直连接不上。但是开启全局模式或者关闭v2rayU之后恢复正常。 本地查看git没有配置任何代理信息。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by chenxiaolei** [comment]
2.1也是一样, 经常休眠唤醒后,都要手动切换下才能 pull push

**Comment by xvwvx** [comment]
我是 Mac 10.15.4 系统下出现该问题的 Mac 10.14上没问题

**Comment by dream-mo** [comment]
> 我是 Mac 10.15.4 系统下出现该问题的 Mac 10.14上没问题

你说起来这个，我怀疑也是macos升级导致的。 因为以前我用的时候也没问题， 但是最近2周git pull拉代码慢到爆炸。 debug测试 开启pac模式 ssl握手一致卡着不动， 关闭v2rayu或者开启全局就好了。 神奇。。

**Comment by dream-mo** [comment]
解决了，兄弟们。 参考:  https://tlanyan.me/macos-10-15-4-ssh-break-solution/

这个老哥也是发现了一样的问题，brew install openssh  就行了，亲测可行

**Comment by xvwvx** [comment]
`brew install openssh` 之后 使用 命令行 git 没问题 使用`Sourcetree` 还是有问题

**Comment by dream-mo** [comment]
> `brew install openssh` 之后 使用 命令行 git 没问题 使用`Sourcetree` 还是有问题

能用都不错了[捂脸]

**Comment by hcw2175** [comment]
遇到同样问题，也是mac os升级到10.15.4后出现的，关闭v2rayu代理就可以。

**Comment by allenyulun** [comment]
sourcetree的问题有解决吗。。命令行 git是可以了

**Comment by dream-mo** [comment]
更新到V2rayU 2.2.0 , macos:10.15.5  已正常
