### ISSUE TITLE
点击“save and update pac from GFW List”后“GFW list”的内容无法及时更新到“http://127.0.0.1:1086/pac/proxy.js”中

### ISSUE THREAD

**Issue by xiebruce** [yanue/V2rayU#519]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU: `v2.1.0`
macOS: `Mojave 10.14.4 (18E226)`

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
点击“save and update pac from GFW List”后“GFW list”的内容无法及时更新到“http://127.0.0.1:1086/pac/proxy.js” 中，试过turn off再turn on v2ray-core，没用，也试了关掉V2rayU再打开，还是没用。但是，在User Rules中写的规则，却可以正常更新到proxy.js中(点击“save and update pac from GFW List”按钮后马上就更新过去了)。

我是自己把官方gfwlist缓存下来，base64解码后，删除其中一些项，再重新base64 encode，然后把我本地地址提供给V2RayU，如下图所示：
![image](https://user-images.githubusercontent.com/13575500/78419688-c74cac80-767a-11ea-91d7-22008e01b13b.png)

我这么做的原因，是因为官方的规则中有些规则在我这不适用，见：[Please remove ssl.gstatic.com and fonts.gstatic.com from straightforward list](https://github.com/gfwlist/gfwlist/issues/1927)，所以我就自己把它下载下来，remove掉那两个项，然后再base 64 encode回去。gfwlist其实就是一个字符串，每行一条规则，最后base64 encode一下，所以我认为我这么做对它的格式不会有任何影响，也就是说V2rayU不可能因为我这么做了就无法解码了吧？

这是我本地gfwlist地址(太长截不全)
![image](https://user-images.githubusercontent.com/13575500/78419605-e0a12900-7679-11ea-9ad0-9c6f11ee57f0.png)

**What I expected:** 点击“save and update pac from GFW List”后，马上把GFWlist更新到proxy.js中，让它生效。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
该问题跟配置无关！

-----------------

我后来测了一下，算是测出来了，我特地把我`http://localhost/personal/gfwlist/gfwlist.txt`中的内容删的只剩这几行(其实相当于删没了，因为感叹号开头的是注释)：
```
[AutoProxy 0.2.9]
! Checksum: mIShJtvB4UUaZ7ms+0fm4g
! Expires: 6h
! Title: GFWList4LL
! GFWList with EVERYTHING included
! Last Modified: Mon, 04 Nov 2019 11:21:47 -0500
!
! HomePage: https://github.com/gfwlist/gfwlist
! License: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
!
```

然后我再把我的`User Rules`全部删除，再把`/Applications/V2rayU.app/Contents/Resources/pac/proxy.js`删除，再点击`save and update pac from GFW List`，你猜结果怎么样？结果生成的'proxy.js`文件，还是很长，这一看就是没有使用我填的gfwlist地址，而是里面写死了官方的吧？

**Comment by yanue** [comment]
已修复 试下2.2

**Comment by xiebruce** [comment]
@yanue 不知道是不是我系统版本原因，我试了，并没有修复，还是跟原来一样哦，我的系统版本: `macOS 10.14.4`

而且我很确定我用的就是2.2
![image](https://user-images.githubusercontent.com/13575500/83329816-223b0280-a2be-11ea-80b0-1dc0e4e8a297.png)

我点“save and update pac from GFW List”，还是不会使用我填的地址的内容，而是直接使用了官方的。

这是我自己的地址(很明显基本上没什么内容了)
![image](https://user-images.githubusercontent.com/13575500/83329867-5f06f980-a2be-11ea-923a-ef64122d303a.png)

上边内容其实是(也就是我把所有规则都删掉了)：
```
[AutoProxy 0.2.9]
! Checksum: mIShJtvB4UUaZ7ms+0fm4g
! Expires: 6h
! Title: GFWList4LL
! GFWList with EVERYTHING included
! Last Modified: Mon, 04 Nov 2019 11:21:47 -0500
!
! HomePage: https://github.com/gfwlist/gfwlist
! License: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
!
```
我把所有的自定义规则也都删掉了，然而`http://127.0.0.1:1086/pac/proxy.js`还是一样有这么多内容(事实上是超级长的，截图只截了一屏而已)：
![image](https://user-images.githubusercontent.com/13575500/83329938-bad18280-a2be-11ea-8351-74b87aeda583.png)
