### ISSUE TITLE
mac端无法上谷歌，iPhone可以

### ISSUE THREAD

**Issue by lanmeiceo** [yanue/V2rayU#520]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.1.0        10.15.4
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
Mac端无法访问https://www.google.com.hk，但iPhone正常
<img width="1548" alt="截屏2020-04-04 下午4 25 35" src="https://user-images.githubusercontent.com/21143032/78422304-ebb38380-7690-11ea-9fdd-56f5d77e072c.png">

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
v2ray配置文件
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "**********",
            "users": [
              {
                "id": "**********",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 2680
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

2020/04/04 16:34:08 [Info] [3467977794] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com.hk:443
2020/04/04 16:34:08 [Info] [3467977794] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com.hk:443
2020/04/04 16:34:08 [Info] [3467977794] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:184.170.213.191:2680
2020/04/04 16:34:08 tcp:127.0.0.1:52948 accepted tcp:www.google.com.hk:443 [proxy] 
2020/04/04 16:34:09 [Info] [1123710760] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/04/04 16:34:09 [Info] [1123710760] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/04/04 16:34:11 [Info] [3467977794] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com.hk:443 via tcp:184.170.213.191:2680
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by why168** [comment]
我也一样，mac使用不了，上不了网。不知道怎么解决

**Comment by Xiesenjiong** [comment]
同样的网络iPhone能上macos上不了，试过手机开热点也不行

**Comment by JennieCheng** [comment]
同样的问题，iphone可以上网，但macos长不去。

**Comment by studynon** [comment]
同样的问题, iphone能上(用的Kitsunebi), mac上不去(V2RayX和V2RayU都上不去)

**Comment by wungyy** [comment]
v2ray节点的端口是不是443

**Comment by AtaraxiaEta** [comment]
这个感觉像是系统的问题，目前有人有解决方案吗？

**Comment by ZzBrx** [comment]
> 这个感觉像是系统的问题，目前有人有解决方案吗？

你好，请问你解决了吗

**Comment by AtaraxiaEta** [comment]
> > 这个感觉像是系统的问题，目前有人有解决方案吗？
> 
> 
> 
> 你好，请问你解决了吗

试试 Clash
