### ISSUE TITLE
macOS无法使用PAC模式

### ISSUE THREAD

**Issue by yuhan1010** [yanue/V2rayU#522]
你好，目前我的V2RayU只能使用全局模式，pac和手动都无法使用。我是小白，能否在下一个版本提供一个现成的 pac.js 文件以供配置？
同时，也建议增加一个白名单模式。 谢谢

**Comment by chenweican** [comment]
白名单模式，用routing不够？

**Comment by CyrilTaylor** [comment]
版本：v2.1.0
OS: macOS 10.15.4 (19E287)

使用PAC模式，Dropbox使用自动检测代理，可是依旧无法联网，假如浏览器直接用直链，而不使用SwitchyOmega强制代理到127.0.0.1:1080，谷歌之类的也无法访问，也就是PAC并没有在系统层起作用

已确认系统网络里面的APC是自动设置了的

![image](https://user-images.githubusercontent.com/12631466/79222859-e1606900-7e8a-11ea-99ea-4094e46c5b80.png)

**Comment by BeingEasy** [comment]
老哥，解决了吗

**Comment by yinghuijian** [comment]
全局代理网断了？其他的不能用。不知道哪里错了，手机上好好的。

**Comment by yinghuijian** [comment]
全局代理网断了，其他的不能用。不知道哪里错了，手机上好好的。

**Comment by yanue** [comment]
> 版本：v2.1.0
> OS: macOS 10.15.4 (19E287)
> 
> 使用PAC模式，Dropbox使用自动检测代理，可是依旧无法联网，假如浏览器直接用直链，而不使用SwitchyOmega强制代理到127.0.0.1:1080，谷歌之类的也无法访问，也就是PAC并没有在系统层起作用
> 
> 已确认系统网络里面的APC是自动设置了的
> 
> ![image](https://user-images.githubusercontent.com/12631466/79222859-e1606900-7e8a-11ea-99ea-4094e46c5b80.png)

打开那个地址,确认一下文件内的代理地址信息

**Comment by CyrilTaylor** [comment]
是对的
```
// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

var proxy = "SOCKS5 127.0.0.1:1080 SOCKS 127.0.0.1:1080; DIRECT;";
```

**Comment by yanue** [comment]
已修复 试下2.2

**Comment by CyrilTaylor** [comment]
试了2.2，依旧无效

**Comment by rayliu** [comment]
pac模式不能用, 升级到4.2.5, 问题依旧, 根据上面的图查找, 发现是网络里代理的URL地址不对, 旧的是http://127.0.0.1:11085/proxy.js, 手工改成http://127.0.0.1:11085/pac/proxy.js, 然后pac模式就可以正常工作了
![image](https://github.com/user-attachments/assets/82164157-c09e-4e64-bf4f-d10092c24a97)

**Comment by didiiko** [comment]
> pac模式不能用, 升级到4.2.5, 问题依旧, 根据上面的图查找, 发现是网络里代理的URL地址不对, 旧的是http://127.0.0.1:11085/proxy.js, 手工改成http://127.0.0.1:11085/pac/proxy.js, 然后pac模式就可以正常工作了 ![image](https://private-user-images.githubusercontent.com/515574/391206587-82164157-c09e-4e64-bf4f-d10092c24a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjMyNTEsIm5iZiI6MTczMzA2Mjk1MSwicGF0aCI6Ii81MTU1NzQvMzkxMjA2NTg3LTgyMTY0MTU3LWMwOWUtNGU2NC1iZjRmLWQxMDA5MmMyNGE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNDIyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmFmMjlhMGRhOTRlZWVlNzBiZWU2M2FmN2E5YzdkODNlZDE0MTk1YTI1YjU1OWEzNzlmYTM4OWI1MTA2ZWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yht7nrJ4ggkPn8NhzYkZbol-OBX7U1HxdO83u2yyd0Q)

按照您的方法更改了系统网络代理设置，依旧无法解决，不能使用pac模式
