### ISSUE TITLE
更新pac文件时闪退

### ISSUE THREAD

**Issue by Mofimg** [yanue/V2rayU#524]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU:2.1.0
MacOS:10.14.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
pac文件一点更新就闪退，完全卸载重装过几次，也都确认权限了，还是闪退，也尝试主动创建yanue.v2rayu.http.plist文件，然而一打开软件那个文件就被自动删了。
Could not read path: path = /Users/user/Library/LaunchAgents/yanue.v2rayu.http.plist, error = 2: No such file or directory

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
后面几次都是默认配置，只添加了连接。

4)  请附上出错时软件输出的错误日志。

```javascript
Apr  6 19:28:45 bogon com.apple.xpc.launchd[1] (net.yanue.V2rayU.73700[5314]): Service exited due to SIGILL | sent by exc handler[5314]
Apr  6 19:28:47 bogon com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100009.Aqua): Could not read path: path = /Users/user/Library/LaunchAgents/yanue.v2rayu.http.plist, error = 2: No such file or directory
Apr  6 19:28:47 bogon com.apple.xpc.launchd[1] (yanue.v2rayu.v2ray-core): This service is defined to be constantly running and is inherently inefficient.
```

**Comment by yanue** [comment]
试下2.2
