### ISSUE TITLE
无法打开“V2rayU”，因为Apple无法检查其是否包含恶意软件。

### ISSUE THREAD

**Issue by icecreammmm** [yanue/V2rayU#528]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2rayu：2.1.0
mac: 10.15.4 

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法安装

请预览一下你填的内容再提交。

**Comment by minfengyk** [comment]
这不是bug，不是appstore下载的第三方软件一般会有这个提示，在系统便好设置-安全性与隐私-通用里选择仍要打开。

**Comment by leohxj** [comment]
可查看此文章说明：
https://www.jianshu.com/p/a1a672b49d78
