### ISSUE TITLE
MAC 10.15.4 (19E287) V2rayU 2.1.0 failed to process outbound traffic

### ISSUE THREAD

**Issue by SenTomoHiro** [yanue/V2rayU#529]
自建VPS，脚本制作的V2RAY。
同一个节点在安卓和WIN上测试过没有问题，到了MAC上，一开始正常，今天突然就没法用了。

LOG如下：
`2020/04/10 16:28:20 [Warning] v2ray.com/core: V2Ray 4.22.1 started
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
2020/04/10 16:28:21 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/04/10 16:28:22 127.0.0.1:51016 accepted //mainnet-infura.brave.com:443 [proxy] 
2020/04/10 16:28:35 127.0.0.1:51018 accepted http://google.com/ [proxy] 
2020/04/10 16:28:52 [Warning] [2467638488] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/04/10 16:28:54 127.0.0.1:51020 accepted //mainnet-infura.brave.com:443 [proxy] 
2020/04/10 16:29:05 [Warning] [1410663016] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/04/10 16:29:05 [Warning] [1410663016] v2ray.com/core/proxy/http: failed to read response from google.com > io: read/write on closed pipe`

求开发者解决。

**Comment by floatval** [comment]
这个错误，应该是 alterID 不一致的导致的。
可以简单通过将原配置删除，再次导入配置文件解决

**Comment by Lin-von** [comment]
遇到了同样的问题，第一次使用

**Comment by KrisWongz** [comment]
我的mac也是同样的问题，连不上网

**Comment by Detoxify** [comment]
同样的问题

**Comment by islishude** [comment]
rm /Applications/V2rayU.app/Contents/Resources/config.json

然后重启

**Comment by chnxan** [comment]
> 自建VPS，脚本制作的V2RAY。
> 同一个节点在安卓和WIN上测试过没有问题，到了MAC上，一开始正常，今天突然就没法用了。
> 
> LOG如下：
> `2020/04/10 16:28:20 [Warning] v2ray.com/core: V2Ray 4.22.1 started V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64) A unified platform for anti-censorship. 2020/04/10 16:28:21 [Warning] v2ray.com/core: V2Ray 4.22.1 started 2020/04/10 16:28:22 127.0.0.1:51016 accepted //mainnet-infura.brave.com:443 [proxy] 2020/04/10 16:28:35 127.0.0.1:51018 accepted http://google.com/ [proxy] 2020/04/10 16:28:52 [Warning] [2467638488] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF 2020/04/10 16:28:54 127.0.0.1:51020 accepted //mainnet-infura.brave.com:443 [proxy] 2020/04/10 16:29:05 [Warning] [1410663016] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF 2020/04/10 16:29:05 [Warning] [1410663016] v2ray.com/core/proxy/http: failed to read response from google.com > io: read/write on closed pipe`
> 
> 求开发者解决。

请问您是否出现了开启代理后，无法通过终端ssh到自建vps的问题？关闭代理后正常呢

**Comment by yanue** [comment]
请自查

**Comment by Asher1217** [comment]
mac遇到问题，win上可以使用，mac连不上，配置都是一样的
