### ISSUE TITLE
V2rayUHelper进程突然会占用100%的CPU

### ISSUE THREAD

**Issue by hunkchang** [yanue/V2rayU#530]
1) 正在使用的 V2RayU 和 Mac 版本 ？
V2.1.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
V2rayuHelper进程突然会占用100%的CPU，原因未知
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
MacBook Pro (15-inch, 2018)
2.9 GHz 六核Intel Core i9
32 GB 2400 MHz DDR4
osx 10.15.4 
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by hadix-lin** [comment]
遇到相同的问题

**Comment by rfzheng** [comment]
同样的问题，甚至半夜盖着盖也在运行风扇声给我吵醒

**Comment by GreatAuk** [comment]
先回退使用2.0吧😅

**Comment by zzhh9857** [comment]
其中原因之一：ping服务器延迟的时候就会出现这个问题，并且长时间占用CPU，楼上说的那样需要强制杀死进程，但是过一段时间又开始重复占用CPU了。

**Comment by Gabirel** [comment]
同样的问题，CPU占用100%。实在无法忍受。

另外，每次程序启动会全部ping一次，建议取消。

**Comment by cc978** [comment]
怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ :astonished::astonished::astonished:

**Comment by dallion** [comment]
我也遇到相同的问题当使用无效的服务器后ping所有服务器的延迟就会导致ping的命令卡住然后cpu使用率维持100%

**Comment by xcosy** [comment]
Please disable this setting:
[偏好设置] -> [General] -> [自动通过ping选择最快的server]

I think this setting may cause this problem when the server node has network problems.

**Comment by Gabirel** [comment]
> Please disable this setting:
> [偏好设置] -> [General] -> [自动通过ping选择最快的server]
> 
> I think this setting may cause this problem when the server node has network problems.

我默认就是关闭状态。但是仍然会出现这个问题

**Comment by CyrilTaylor** [comment]
> 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲

请文明催更！夸人比诅咒更容易让作者产生动力。快乐是开源的源动力。

**Comment by blessing-gao** [comment]
问题+1

**Comment by KinoamyFx** [comment]
问题+10086, MAC 占用100%CPU，导致发热严重

**Comment by cloud21sky** [comment]
问题+1

**Comment by netstu** [comment]
> 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲

这么说话我真是服了

**Comment by Hoexhe** [comment]
问题+1 风扇狂转, 机身烫得不行

**Comment by GreatAuk** [comment]
建议回退到 2.0 版本

**Comment by zhangciiiii** [comment]
> 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲

你是不是觉得你很幽默？脑瘫孤儿

**Comment by fraee** [comment]
> Please disable this setting:
> [偏好设置] -> [General] -> [自动通过ping选择最快的server]
> 
> I think this setting may cause this problem when the server node has network problems.

This does not work.

**Comment by Annihilater** [comment]
> Please disable this setting:
> [偏好设置] -> [General] -> [自动通过ping选择最快的server]
> 
> I think this setting may cause this problem when the server node has network problems.

我都没开 V2raU，我开的 ClashXR
而且 V2rayU 里面自动 ping 选项也是关闭的

**Comment by peerlessXu** [comment]
版本2.1.0。遇到一样的问题。客户端已经关了，但是cpu列表里v2rayuhelper占用非常高，导致cpu风扇狂转。

**Comment by cc978** [comment]
> > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> 
> 你是不是觉得你很幽默？脑瘫孤儿

上海交通大学电子工程学院自动化系获得学士学位

中文互联网上充斥了一群，根本不关心作者是死是活，只关心作标准道德礼貌卫道士的脑残犯喷子
北大，情花，交大，复旦，排序下来的。
谁愿意搭理你一样

**Comment by yanue** [comment]
> 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ :astonished::astonished::astonished:

真他妈恶毒，恶心🤢，你全家都被新冠带走了

**Comment by zhangciiiii** [comment]
> > > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> > 
> > 
> > 你是不是觉得你很幽默？脑瘫孤儿
> 
> 上海交通大学电子工程学院自动化系获得学士学位
> 
> 中文互联网上充斥了一群，根本不关心作者是死是活，只关心作标准道德礼貌卫道士的脑残犯喷子
> 北大，情花，交大，复旦，排序下来的。
> 谁愿意搭理你一样

宁说得对，我错了，我不该搭理你的。我只是替作者感到不公平，开源的东西被你这种恶毒的人用了，开病毒的玩笑，开作者的玩笑。

什么什么？噢，原来你是在关心作者身体健康啊，那对不起，我误会宁了呢，看来不少人也误会宁了，宁在第五层，我在第一层。对不起对不起。

就此打止，github上大家都是来交流技术的，没必要吵吵闹闹污染环境，打扰到各位真是抱歉，我不会再逼逼赖赖了。

**Comment by yanue** [comment]
试下2.2

**Comment by cc978** [comment]
> > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> 
> 真他妈恶毒，恶心🤢，你全家都被新冠带走了

贵中国大陆人还真是个顶个的内战引战内行，对抗专制外行
一个个恨不得都是道德洁癖，满脑子政治斗争，活该中共对你们进行专制，高等级文明，你们不配

**Comment by yanue** [comment]
> > > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> > 
> > 
> > 真他妈恶毒，恶心🤢，你全家都被新冠带走了
> 
> 贵中国大陆人还真是个顶个的内战引战内行，对抗专制外行
> 一个个恨不得都是道德洁癖，满脑子政治斗争，活该中共对你们进行专制，高等级文明，你们不配

不知道是谁引战的,说话不够脑子, 你那么高级了咋还是要fq呢

**Comment by cc978** [comment]
> > > > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> > > 
> > > 
> > > 真他妈恶毒，恶心🤢，你全家都被新冠带走了
> > 
> > 
> > 贵中国大陆人还真是个顶个的内战引战内行，对抗专制外行
> > 一个个恨不得都是道德洁癖，满脑子政治斗争，活该中共对你们进行专制，高等级文明，你们不配
> 
> 不知道是谁引战的,说话不够脑子, 你那么高级了咋还是要fq呢

对不起，告诉你一个不幸消息，疫情结束，俺的移民纸走人了，不过是疫情拦住了

见识越多你们大陆人，就越觉得恶心，有10%美国黑人闹地位的劲头，你们还用翻墙么？？？
你们那点脑子 + 言语洁癖，自我自尊心强的都飞跃美利坚，一点什么得病的预测都不能说的脆弱小心灵
……
只要用那么10%到对抗专制上，你们也不会有今天，窝在墙里，搞什么说话够脑子，要尊重的窝里斗了
看你这引战，内战的劲头，你配吗？？？

**Comment by CyrilTaylor** [comment]
> > > > > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> > > > 
> > > > 
> > > > 真他妈恶毒，恶心🤢，你全家都被新冠带走了
> > > 
> > > 
> > > 贵中国大陆人还真是个顶个的内战引战内行，对抗专制外行
> > > 一个个恨不得都是道德洁癖，满脑子政治斗争，活该中共对你们进行专制，高等级文明，你们不配
> > 
> > 
> > 不知道是谁引战的,说话不够脑子, 你那么高级了咋还是要fq呢
> 
> 对不起，告诉你一个不幸消息，疫情结束，俺的移民纸走人了，不过是疫情拦住了
> 
> 见识越多你们大陆人，就越觉得恶心，有10%美国黑人闹地位的劲头，你们还用翻墙么？？？
> 你们那点脑子 + 言语洁癖，自我自尊心强的都飞跃美利坚，一点什么得病的预测都不能说的脆弱小心灵
> ……
> 只要用那么10%到对抗专制上，你们也不会有今天，窝在墙里，搞什么说话够脑子，要尊重的窝里斗了
> 看你这引战，内战的劲头，你配吗？？？

看到一个活生生的美奴！自以为移民了就高级了？搞得别人没去过美国一样，说真的，我真心瞧不上，还是我大中华更有趣。

**Comment by yanue** [comment]
> > > > > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> > > > 
> > > > 
> > > > 真他妈恶毒，恶心🤢，你全家都被新冠带走了
> > > 
> > > 
> > > 贵中国大陆人还真是个顶个的内战引战内行，对抗专制外行
> > > 一个个恨不得都是道德洁癖，满脑子政治斗争，活该中共对你们进行专制，高等级文明，你们不配
> > 
> > 
> > 不知道是谁引战的,说话不够脑子, 你那么高级了咋还是要fq呢
> 
> 对不起，告诉你一个不幸消息，疫情结束，俺的移民纸走人了，不过是疫情拦住了
> 
> 见识越多你们大陆人，就越觉得恶心，有10%美国黑人闹地位的劲头，你们还用翻墙么？？？
> 你们那点脑子 + 言语洁癖，自我自尊心强的都飞跃美利坚，一点什么得病的预测都不能说的脆弱小心灵
> ……
> 只要用那么10%到对抗专制上，你们也不会有今天，窝在墙里，搞什么说话够脑子，要尊重的窝里斗了
> 看你这引战，内战的劲头，你配吗？？？

呵呵 高级哦 未来美国人 你那脑子是好啊  什么是玩笑都不知道

**Comment by cc978** [comment]
> > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> 
> 你是不是觉得你很幽默？脑瘫孤儿

告诉你一个更幸福的消息，北大，清华，复旦，后面还要几名排交大，是真正的中国专制上层权贵精英们的老鼠会，别在这显摆你多高级，你的师兄师姐们，都是 GFW 的建设者和支持者，装下水道里逃出来的卫生球，你不配

楼上那种在大中华更有趣的货色，无疑是这个专制 + GFW 的既得利益者，你活该在墙里，你幸福去吧，当然，你还大比例进不去上面北大清华复旦老鼠会，只是个给权贵舔盘子的货色

美奴不奴，移民纸拿到，已经超越你们这些大陆还在伺候专制极权的小流氓50年，你们在墙内继续接受专制虐待吧，sb

**Comment by cc978** [comment]
连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧

你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？

有病

**Comment by zhangciiiii** [comment]
> > > > > > 怪异的是，作者一个月都没修这个明显的bug，这个bug一发作，我的mac网络协议栈就被烧死，只能重启 。。。。 难道作者是被新冠肺炎抓走了？ 😲😲😲
> > > > > 
> > > > > 
> > > > > 真他妈恶毒，恶心🤢，你全家都被新冠带走了
> > > > 
> > > > 
> > > > 贵中国大陆人还真是个顶个的内战引战内行，对抗专制外行
> > > > 一个个恨不得都是道德洁癖，满脑子政治斗争，活该中共对你们进行专制，高等级文明，你们不配
> > > 
> > > 
> > > 不知道是谁引战的,说话不够脑子, 你那么高级了咋还是要fq呢
> > 
> > 
> > 对不起，告诉你一个不幸消息，疫情结束，俺的移民纸走人了，不过是疫情拦住了
> > 见识越多你们大陆人，就越觉得恶心，有10%美国黑人闹地位的劲头，你们还用翻墙么？？？
> > 你们那点脑子 + 言语洁癖，自我自尊心强的都飞跃美利坚，一点什么得病的预测都不能说的脆弱小心灵
> > ……
> > 只要用那么10%到对抗专制上，你们也不会有今天，窝在墙里，搞什么说话够脑子，要尊重的窝里斗了
> > 看你这引战，内战的劲头，你配吗？？？
> 
> 呵呵 高级哦 未来美国人 你那脑子是好啊 什么是玩笑都不知道

别理他了，脑瘫一个，晦气

**Comment by zhangciiiii** [comment]
> 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> 
> 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> 
> 有病

大孝子，舔你美爹的脚趾头和屁眼去吧。

**Comment by cc978** [comment]
> > 
> > 呵呵 高级哦 未来美国人 你那脑子是好啊 什么是玩笑都不知道
> 
> 别理他了，脑瘫一个，晦气

你交大的师兄师姐从没有你这么脑残，参与什么翻墙，早就参与到极权体系，用所谓后发优势，从美国偷盗抢知识产权，捞世界去了

你在这搞引战，毫无利润，与你的师兄师姐完全相反走向的差距，才是真正的脑瘫一个，根本不符合交大校训：
**饮水思源  爱党荣祖**

**Comment by yanue** [comment]
> 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> 
> 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> 
> 有病

数典忘祖 

> 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> 
> 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> 
> 有病

等你过去看看 你的地位有黑人高吗 傻乎乎的一个  高傲自大 还以为自己真了不起  顺便问一句 过去是找凤姐吗?

**Comment by CyrilTaylor** [comment]
前面扯一堆学历，然后又拉一票移民，看得出现实里是个非常自卑又虚荣的人，不过幸好已经滚蛋了，只是夷奴，祸害不到咱们，大家洗洗睡吧，狗咬了咱，咱可不能咬回去，有机会直接打死就可以了。

**Comment by cc978** [comment]
我是今天有空，给你们看看大陆国人引战内行，对抗专制还不如黑人10%，搞起个人利益，随时和党国合作的卑鄙嘴脸，以及你们的高水平老鼠会诞生出来的卫生球有多扯淡，你们继续显摆你们的
“爱国爱党，翻墙为党搞建设，争取把美国偷光”  的新时代精神病气息吧，你们大陆人活该被墙，你们乐于享受其中，在其中找到自我价值

**Comment by cc978** [comment]
> > 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> > 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> > 有病
> 
> 等你过去看看 你的地位有黑人高吗 傻乎乎的一个 高傲自大 还以为自己真了不起 顺便问一句 过去是找凤姐吗?

说实话，我以前真不知道 v2rayU 的作者竟然是这样秀自己脑残水平的，自由，是用你的黑人地位和金钱衡量的啊，自由就是去找凤姐的啊？？？
哈哈哈，怪不得你还在墙内，怪不得凤姐那种垃圾用政治庇护伪造自己被迫害拿身份，你们这些大陆人，一个赛一个的用卑鄙无耻当作有趣吗？？？

**Comment by cc978** [comment]
> 前面扯一堆学历，然后又拉一票移民，看得出现实里是个非常自卑又虚荣的人，不过幸好已经滚蛋了，只是夷奴，祸害不到咱们，大家洗洗睡吧，狗咬了咱，咱可不能咬回去，有机会直接打死就可以了。

这种给党国舔盘子的狗都不如的货色，还把自由当作虚荣，哈哈哈哈，什么中国大陆的卑鄙烂货，你也配上来汪汪叫？

**Comment by cc978** [comment]
> > 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> > 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> > 有病
> 
> 等你过去看看 你的地位有黑人高吗 傻乎乎的一个 高傲自大 还以为自己真了不起 顺便问一句 过去是找凤姐吗?

v2rayU 作者竟然是一个以美国黑人地位，凤姐式恶性投机国人为中国移民在美国生活标靶的，把美国的自由定位为人种地位高低，与中国墙内被专制虐待的地位比，是不是后者更开心，更美好啊？？？
真是让我大跌眼镜。
开源真的只是开了技术，背后真不知道是什么思维定位的货色。太低级，太可怕了！

**Comment by cc978** [comment]
> > 
> > 别理他了，脑瘫一个，晦气
> 
> 你交大的师兄师姐从没有你这么脑残，参与什么翻墙，早就参与到极权体系，用所谓后发优势，从美国偷盗抢知识产权，捞世界去了
> 
> 你在这搞引战，毫无利润，与你的师兄师姐完全相反走向的差距，才是真正的脑瘫一个，根本不符合交大校训：
> **饮水思源 爱党荣祖**

一个1995年就把自己校训改的功利到接近卑鄙，几乎就是【黑虎白虎，作交大的党的好猫】的上海交大，还有毕业生顶着名头出来招摇。
你有能力最好让你们那个垃圾学校把校训改回60年前，别在这装bigger了，丢祖宗的人。
不过，也没啥，整个大陆不都是这种鸟人么

**Comment by netstu** [comment]
> > > 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> > > 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> > > 有病
> > 
> > 
> > 等你过去看看 你的地位有黑人高吗 傻乎乎的一个 高傲自大 还以为自己真了不起 顺便问一句 过去是找凤姐吗?
> 
> v2rayU 作者竟然是一个以美国黑人地位，凤姐式恶性投机国人为中国移民在美国生活标靶的，把美国的自由定位为人种地位高低，与中国墙内被专制虐待的地位比，是不是后者更开心，更美好啊？？？
> 真是让我大跌眼镜。
> 开源真的只是开了技术，背后真不知道是什么思维定位的货色。太低级，太可怕了！

我觉得作者并不是因为中美的问题来怼你的，可能你上面骂人了，他生气然后找了这个借口反骂你而已。

搞梯子的人我觉得不会是他自己骂你的那个原因骂你的。

**Comment by michaellee123** [comment]
> > > 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> > > 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> > > 有病
> > 
> > 
> > 等你过去看看 你的地位有黑人高吗 傻乎乎的一个 高傲自大 还以为自己真了不起 顺便问一句 过去是找凤姐吗?
> 
> v2rayU 作者竟然是一个以美国黑人地位，凤姐式恶性投机国人为中国移民在美国生活标靶的，把美国的自由定位为人种地位高低，与中国墙内被专制虐待的地位比，是不是后者更开心，更美好啊？？？
> 真是让我大跌眼镜。
> 开源真的只是开了技术，背后真不知道是什么思维定位的货色。太低级，太可怕了！

您这么高级，还FQ干嘛？口口声声的说什么不反抗，您可真牛，您的反抗方式就是移民。嘿，还真是厉害呢。真是盖了帽了，我的老baby。

**Comment by michaellee123** [comment]
> > 连黑人都不如，还在这玩高尚呢，你们真是一群，什么物种？自己想想去吧
> > 你们在这里辛勤的翻墙，在专制体系里为从美国盗取、抄袭知识，为把极权中国大陆建设的更美好，你说你们到底是什么鸟，什么种？？？
> > 有病
> 
> 等你过去看看 你的地位有黑人高吗 傻乎乎的一个 高傲自大 还以为自己真了不起 顺便问一句 过去是找凤姐吗?

别管它，我上次就是看到它这个言论，我才花了几个小时来改了下这个bug提的pr。毕竟这种狗也不常见，就把它钉在这儿当展览吧。

**Comment by qxdfv1** [comment]
。
