### ISSUE TITLE
订阅列表不更新的问题

### ISSUE THREAD

**Issue by aishlai** [yanue/V2rayU#531]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU 2.1.0
MAC 10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
订阅列表在服务端已经更新的情况下，客户端手动点击更新后，也成功显示了
『loading from 和 del old from url 以及相关的列表』，但是列表终的内容并没有更新

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
请确认订阅地址是否能正常访问
loading from 是否返回有fail
另外订阅返回的东西是不是正常的
