### ISSUE TITLE
建议升级ping测速为逐条线路实测下载速率

### ISSUE THREAD

**Issue by andersontsui** [yanue/V2rayU#537]
由于出现诸多中继机场，ping出的结果均为国内服务器，无实际意义。建议改为例如curl谷歌首页html所需时间为参考值，自动遍历所有服务器，最终选择最快的服务器，较为切合实际。本想快速修改负责ping的main.go，突然意识到无法遍历所有服务器的v2ray连接，唯有请大神出手。

**Comment by yanue** [comment]
试下2.2吧  没按以前方式了
