### ISSUE TITLE
遇到日志打开是空的情况，重启重装好几次，配置文件又是有内容的，mac系统10.15.3

### ISSUE THREAD

**Issue by qqppwskj** [yanue/V2rayU#538]
遇到日志打开是空的情况，重启重装好几次，配置文件又是有内容的，mac系统10.15.3

**Comment by qqppwskj** [comment]
![image](https://user-images.githubusercontent.com/31661873/79681162-8479ff80-824a-11ea-9aed-8fb83022b56e.png)

**Comment by yanue** [comment]
试下2.2
