### ISSUE TITLE
SAFARI可以正常使用，但是CHROME不可以。而且我的CHROME使用插件也不行。(本人朋友都可以使用)是不是我的CHROME出了毛病?是的话该怎么设置呢?

### ISSUE THREAD

**Issue by Oliver2333Chen** [yanue/V2rayU#539]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by LA-Star** [comment]
@Oliver2333Chen 请问你解决了吗？我的也是Safari可以上，但是Chrome不可以。

**Comment by mingdq1** [comment]
你的Chrome是不是装了什么插件，例如unblock youku啥的，如果是装了就disable掉这些插件

**Comment by Oliver2333Chen** [comment]
所有插件都已经关掉了 
还是不行

**Comment by yanue** [comment]
pac模式或全局模式,再确认下插件
