### ISSUE TITLE
服务器不能自定义名称或备注

### ISSUE THREAD

**Issue by FattyboyN** [yanue/V2rayU#54]
新建服务器只能是“new server” 无法修改名称或备注。

建议加入退出v2ray core时自动将系统代理恢复到初始状态

chacha20-ietf-poly1305 issue解决。测试正常。

**Comment by yanue** [comment]
双击可以修改

**Comment by FattyboyN** [comment]
刚发完issue发现双击可以修改 😂

**Comment by yanue** [comment]
退出时有做恢复代理的,可能有bug吧
