### ISSUE TITLE
v2rayN报错

### ISSUE THREAD

**Issue by itnewgay** [yanue/V2rayU#540]
请预览一下你填的内容再提交。

v2ray 4.23.1  v2rayN 3.15~16 
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

端口更换后，也还是有这个问题。明确是端口并没有被占用。更换其它端口也一样会报这个错。

**Comment by Scyllaly** [comment]
各个你走错地方了，这里是U不是N
