### ISSUE TITLE
无法输入密码 客户端为mac 

### ISSUE THREAD

**Issue by imysm** [yanue/V2rayU#541]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
Mac 10.15.4 
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
登录的密码框不能输入
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
v2rayu版本呢

**Comment by imysm** [comment]
我下载了一个新版本 ，可以用了 。不过速度超慢，还没有google的开源vpn 快。。。 以买三个月的套餐的时候不这样啊 ，为啥包年了就慢了呢
