### ISSUE TITLE
无法连接外网，提示：无法访问此网站

### ISSUE THREAD

**Issue by ArsenicX** [yanue/V2rayU#543]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU：v2.1.0
Mac：10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法正常连接外网。
pac模式下大陆网站正常，外网提示**无法访问此网站**。
全局模式下，所有网站都提示**无法访问此网站**。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    {
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "XXXXXXXXXXXX",
            "users": [
              {
                "id": "XXXXXXXXXXXX",
                "alterId": 0,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": 80
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。
下面两块，第一个日志是我在v2ray-core提的[相同的问题](https://github.com/v2ray/discussion/issues/656)，那个时候的错误日志；
第二个是我现在又试了一下产生的日志。

```javascript
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic 
> v2ray.com/core/proxy/vmess/outbound: failed to find an available destination 
> v2ray.com/core/common/retry: [dial tcp: lookup <机场地址> on [fe80::1]:53: write udp [fe40::c7b:34e9:22f5:c221%en0]:50449->[fe80::1]:53: write: no route to host dial tcp: lookup <机场地址> on [fe80::1]:53: write udp [fe40::c7b:34e9:22f5:c221%en0]:50453-
>[fe80::1]:53: write: no route to host dial tcp: lookup <机场地址> on [fe80::1]:53: write udp [fe40::c7b:34e9:22f5:c221%en0]:50465->[fe80::1]:53: write: no route to host dial tcp: lookup <机场地址> on [fe80::1]:53: write udp [fe40::c7b:34e9:22f5:c221%en0]:50473-
>[fe80::1]:53: write: no route to host dial tcp: lookup <机场地址> on [fe80::1]:53: write udp [fe40::c7b:34e9:22f5:c221%en0]:50481->[fe80::1]:53: write: no route to host] 
> v2ray.com/core/common/retry: all retry attempts failed

v2ray.com/core/app/proxyman/inbound: connection ends 
> v2ray.com/core/proxy/socks: connection ends 
> v2ray.com/core/proxy/socks: failed to transport all TCP response 
> io: read/write on closed pipe
```

```javascript
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic 
> v2ray.com/core/proxy/vmess/outbound: connection ends 
> v2ray.com/core/proxy/vmess/outbound: failed to read header 
> v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 245 but actually 250

v2ray.com/core/app/proxyman/inbound: connection ends 
> v2ray.com/core/proxy/socks: connection ends 
> v2ray.com/core/proxy/socks: failed to transport all TCP response 
> io: read/write on closed pipe

```

排错：
- 我用了V2rayU和V2rayC都不能正常使用，但是换用了ClashX能正常使用。应该不是电脑问题
- 同样的vess地址，手机的v2rayNG和win的V2rayN都可以正常使用。应该不是机场的问题
- v2ray-core那边得到的[回复](https://github.com/v2ray/discussion/issues/656#issuecomment-618040230)是`Dns有问题`。软件的dns是默认为空，我也不知道怎么改；改了本机的dns也没有用。

**Comment by BeingEasy** [comment]
mac下网络配置--高级--代理--自动代理配置需要为pac文件才行

**Comment by jackycheung00077** [comment]
> mac下网络配置--高级--代理--自动代理配置需要为pac文件才行

我的显示pac：http://127.0.0.1:11085/pac/proxy.js，正常吗？我也是上不去

**Comment by JiezengDev** [comment]
我这系统10.15.4一直没法用，但是家人旧版系统可以，查看日志显示如下 ：
`v2ray.com/core/common/retry: [dial tcp: lookup [服务器域名]
... 
i/o timeout dial
`
1. 确认 mac下网络配置--高级--代理--自动代理配置 为 http://127.0.0.1:11085/pac/proxy.js
2. 怀疑是DNS配置问题，修改DNS server，增加8.8.8.8无效，尝试着改了下routing，现在可以了，有兴趣可以试试
![image](https://user-images.githubusercontent.com/42398428/81309774-e2656e80-90b5-11ea-9998-e9b0dfb79009.png)

**Comment by jackycheung00077** [comment]
> 我这系统10.15.4一直没法用，但是家人旧版系统可以，查看日志显示如下 ：
> `v2ray.com/core/common/retry: [dial tcp: lookup [服务器域名] ... i/o timeout dial `
> 
> 1. 确认 mac下网络配置--高级--代理--自动代理配置 为 http://127.0.0.1:11085/pac/proxy.js
> 2. 怀疑是DNS配置问题，修改DNS server，增加8.8.8.8无效，尝试着改了下routing，现在可以了，有兴趣可以试试
>    ![image](https://user-images.githubusercontent.com/42398428/81309774-e2656e80-90b5-11ea-9998-e9b0dfb79009.png)

方便给我一个你的配置文件吗？我按照你说的已经修改了routing，如何增加8.8.8.8无效？需要修改DNS配置文件吗？

我的设置是这个样子，和你的一样吗 ？我不知道问题在哪里？请指教
<img width="455" alt="截屏2020-05-10 下午9 12 44" src="https://user-images.githubusercontent.com/64859200/81500614-d96adc00-9305-11ea-86fd-a5554d144e8b.png">

**Comment by 1065283526** [comment]
> > 我这系统10.15.4一直没法用，但是家人旧版系统可以，查看日志显示如下 ：
> > `v2ray.com/core/common/retry: [dial tcp: lookup [服务器域名] ... i/o timeout dial `
> > 
> > 1. 确认 mac下网络配置--高级--代理--自动代理配置 为 http://127.0.0.1:11085/pac/proxy.js
> > 2. 怀疑是DNS配置问题，修改DNS server，增加8.8.8.8无效，尝试着改了下routing，现在可以了，有兴趣可以试试
> >    ![image](https://user-images.githubusercontent.com/42398428/81309774-e2656e80-90b5-11ea-9998-e9b0dfb79009.png)
> 
> 方便给我一个你的配置文件吗？我按照你说的已经修改了routing，如何增加8.8.8.8无效？需要修改DNS配置文件吗？
> 
> 我的设置是这个样子，和你的一样吗 ？我不知道问题在哪里？请指教
> <img alt="截屏2020-05-10 下午9 12 44" width="455" src="https://user-images.githubusercontent.com/64859200/81500614-d96adc00-9305-11ea-86fd-a5554d144e8b.png">

我的也是无法上，但是clashX可以上

**Comment by yanue** [comment]
配置完,通过菜单查看config.json, 主要确认以下参数正确: (可选用pac,全局模式)
vnext: 
  id: "xxx",
  alterId: xx,
  port: xxx,
streamSettings: 
  network: "ws or tcp or ...",
  对应的wsSettings 或 tlsSettings 或 ...

**Comment by CzyerChen** [comment]
> 我这系统10.15.4一直没法用，但是家人旧版系统可以，查看日志显示如下 ：
> `v2ray.com/core/common/retry: [dial tcp: lookup [服务器域名] ... i/o timeout dial `
> 
> 1. 确认 mac下网络配置--高级--代理--自动代理配置 为 http://127.0.0.1:11085/pac/proxy.js
> 2. 怀疑是DNS配置问题，修改DNS server，增加8.8.8.8无效，尝试着改了下routing，现在可以了，有兴趣可以试试
>    ![image](https://user-images.githubusercontent.com/42398428/81309774-e2656e80-90b5-11ea-9998-e9b0dfb79009.png)

有效，感谢

**Comment by AllstarVirgo** [comment]
> 我这系统10.15.4一直没法用，但是家人旧版系统可以，查看日志显示如下 ： `v2ray.com/core/common/retry: [dial tcp: lookup [服务器域名] ... i/o timeout dial `
> 
> 1. 确认 mac下网络配置--高级--代理--自动代理配置 为 http://127.0.0.1:11085/pac/proxy.js
> 2. 怀疑是DNS配置问题，修改DNS server，增加8.8.8.8无效，尝试着改了下routing，现在可以了，有兴趣可以试试
>    ![image](https://user-images.githubusercontent.com/42398428/81309774-e2656e80-90b5-11ea-9998-e9b0dfb79009.png)
有效 ，感谢大佬
