### ISSUE TITLE
在macOS上，如果有多个账户，状态栏无法展示图标

### ISSUE THREAD

**Issue by kittig** [yanue/V2rayU#545]
用a账户安装了V2ray，在Application目录下。
当切换到b账户后，打开V2ray，无法在状态栏展示图标。

**Comment by xpol** [comment]
我也遇到这个问题，错误信息如下：
```
Application Specific Information:
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“ping.json”存储到文件夹“Resources”中的权限。" UserInfo={NSFilePath=/Applications/V2rayU.app/Contents/Resources/ping.json, NSUserStringVariant=Folder, NSUnderlyingError=0x600003e488d0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}: file /Users/yanue/swift/V2rayU/V2rayU/ping.swift, line 121
 ```

**Comment by Kiloland** [comment]
同遇到此问题。
看log显示为在resources文件夹下没有权限导致。
进入Finder内，选择Applications文件夹
1.右键V2rayU,点击Get Info,在Sharing & Permissions内添加目标用户并将Privilege改为Read&Write
2.再次右键V2rayU,点击Show Package Contens,右击Contens再次点击Get Info,在Sharing & Permissions内添加目标用户并将Privilege改为Read&Write，同时点击设置的图标选择 Apply to enclosed items..
应该可以解决该问题。

**Comment by yanue** [comment]
后续再说
