### ISSUE TITLE
你们有没有遇到占CPU超高、风扇加速、耗电极快，睡眠启动后一直在登录界面假死

### ISSUE THREAD

**Issue by note4** [yanue/V2rayU#547]
你们有没有遇到一打开风扇加速耗电极快，睡眠启动后一直在登录界面假死。

之前不知道是什么情况睡眠恢复好假死在登录界面，后来发现用v2rayN的时候风扇会响，后来每次睡眠前都会先退了v2rayN，后来就没假死过了。

版本号

v2rayN：2.1.0
v2ray-core：4.23.1
系统版：10.15.4

**Comment by GISCAFF** [comment]
这两天陆续出现风扇狂转，v2rayhelpers cpu占用100%

**Comment by Laev** [comment]
> 这两天陆续出现风扇狂转，v2rayhelpers cpu占用100%

+1 ，很久就发现了，打开进程看v2ray Helpers 占用率出奇的高，自动检测版本和自动ping也都关闭了，不知道每次拉起这个进程干什么，每次风扇响就知道这货在作妖，结束进程就好了，其他也没发现啥影响。

**Comment by brandonstack** [comment]
疯狂占用, 好点非常快

**Comment by yanue** [comment]
试下2.2
