### ISSUE TITLE
V2ray + ws + tls 阵亡， 申请支持Trojan！

### ISSUE THREAD

**Issue by magnusguo** [yanue/V2rayU#549]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？ V2.1.0

2) 你遇到的问题是什么？ping服务器没问题， 但连接时配置也没问题，用了几天后则开始无法使用，换了ip 更新了配置也没办法

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
![image](https://user-images.githubusercontent.com/2341376/80482253-75036080-8986-11ea-8286-c412f6224e20.png)

4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by mingdq1** [comment]
你alterID配错了吧

**Comment by cheneyxx** [comment]
看样子是你配置的问题

**Comment by magnusguo** [comment]
求教，之前是可以上的 速度超级慢 且不稳定

**Comment by magnusguo** [comment]
> 看样子是你配置的问题

求教求教

**Comment by xinbs** [comment]
想转Trojan了。可是目前Trojan的客户端都不太好

**Comment by yuchuanzhen** [comment]
https://github.com/yanue/V2rayU/commit/ea55881c1da4799638e2e6f316040751d4fa8e45
看起来马上有了。

**Comment by yanue** [comment]
#415 不要重复提
