### ISSUE TITLE
configure 点击多次会出现多个配置窗口

### ISSUE THREAD

**Issue by ElfenSterben** [yanue/V2rayU#55]
configure 点击多次会出现多个配置窗口
且关闭其中一个 所有窗口都会关闭
再次点击 configure 会打开之前已经打开过的所有窗口

![image](https://user-images.githubusercontent.com/19554131/57594121-24c2a100-7571-11e9-8fed-1fcb94b3d8d6.png)

**Comment by yanue** [comment]
主要是保留dock图标导致

**Comment by snailbing** [comment]
已修正

**Comment by yanue** [comment]
已处理,版本1.3.0
