### ISSUE TITLE
V2rayUhelper在后台疯狂占用CPU  请问它在干什么

### ISSUE THREAD

**Issue by Hsintao** [yanue/V2rayU#550]
RT

**Comment by cyea** [comment]
同样问题 占了 `108%` 的cpu

**Comment by wulie88** [comment]
同样问题 占了106%的cpu

**Comment by BetterChenMing** [comment]
大概知道在干啥了.

**Comment by superwyk** [comment]
同样问题。。。
每次睡眠呼起，cpu都会飙升。。。
而且，mac pro15寸-2019型号是cpu每次都会飙升，mac pro13寸-2019型号频率稍微低点(现在频率也变高了)。。。

**Comment by vipadm** [comment]
V2rayUhelper 同样的问题，macbook pro13寸 2019  每次睡眠唤醒，cpu都会飙升

**Comment by lengjian** [comment]
同样问题+1

**Comment by zjclyz** [comment]
![image](https://user-images.githubusercontent.com/22068835/81490943-96cfe200-92ba-11ea-8ba8-96ca6a9bdfc3.png)
同样问题

**Comment by yaohwu** [comment]
看代码是在 ping 服务器选择最快的服务器 👏

**Comment by Hsintao** [comment]
> 看代码是在 ping 服务器选择最快的服务器 👏

是的   我换回低版本的了

**Comment by yaohwu** [comment]
@Hsintao 你换到哪个版本了？现在的2.1.0 确实感觉问题好多，配置保存闪退这个最影响；
代码跑起来的又正常

**Comment by Hsintao** [comment]
> @Hsintao 你换到哪个版本了？现在的2.1.0 确实感觉问题好多，配置保存闪退这个最影响；
> 代码跑起来的又正常

2.0.0 V2rayhelper的问题没出现过

**Comment by hunkchang** [comment]
作者不会去喝茶了吧？三个月没更新了。

**Comment by xiaosheng2014** [comment]
退回2.0版本

**Comment by brandonstack** [comment]
同样问题...

**Comment by shotacon** [comment]
我的都飚到200%多了. 风扇一直转 cpu一直在60° 不知道在干啥

**Comment by yanue** [comment]
试下2.2
