### ISSUE TITLE
V2RayU没日志

### ISSUE THREAD

**Issue by nickzhao0617** [yanue/V2rayU#551]
1. 系统版本：mac os catalina 10.15.4
    软件版本：2.1.0

2. 开启软件连接时，发现访问不了外网，查看报错信息时，没有日志，将ping spreed开启时有
![image](https://user-images.githubusercontent.com/15995512/80669264-878caf80-8ad6-11ea-94f8-491396cd5fd7.png)显示

3. 这个是配置信息
![image](https://user-images.githubusercontent.com/15995512/80669362-d20e2c00-8ad6-11ea-8b0b-515b56dd1fc6.png)

将软件卸载了再安装也是没日志，换2.0也一样

**Comment by mingdq1** [comment]
alterId配错了 试下0/1/2这三个

**Comment by jackycheung00077** [comment]
我的也是这个样子，但是没找到alterld配置界面，服务器订阅都是正常，可以刷新，可以显示网速，家中宽带千兆，目前就是MacBook无法使用，求解
系统版本：mac os catalina 10.15.4
软件版本：2.1.0

**Comment by mingdq1** [comment]
> 我的也是这个样子，但是没找到alterld配置界面，服务器订阅都是正常，可以刷新，可以显示网速，家中宽带千兆，目前就是MacBook无法使用，求解
> 系统版本：mac os catalina 10.15.4
> 软件版本：2.1.0

用2.0的版本吧

**Comment by nickzhao0617** [comment]
更改了alterId还是不行。
之后操作：
卸载2.1，安装2.0也没日志
将2.0升级至2.1还是没日志
但是将配置导入至其它MAC里面却可以连接

**Comment by yanue** [comment]
试下2.2

**Comment by dirklei** [comment]
今天2.2客户端同样发现这个问题，没有任何日志输出，昨天还好好的，今天打开电脑就不行了，2.2.0 mac10. 15. 6

**Comment by Dandan1314** [comment]
> 今天2.2客户端同样发现这个问题，没有任何日志输出，昨天还好好的，今天打开电脑就不行了，2.2.0 mac10. 15. 6

出现相同问题了
