### ISSUE TITLE
你好，我看软件本地走的是sock协议，能否之后支持sock5.谢谢

### ISSUE THREAD

**Issue by MemoriseXuxu** [yanue/V2rayU#555]
我是用Chrome插件SwitchYOmega的，里面支持sock4和sock5。但是软件没有支持，所以就不能用了。

**Comment by joescon** [comment]
sock5支持的。我一直都用switchy omega +v2rayu正常使用

**Comment by yanue** [comment]
"protocol": "socks",
本身就是socks5
