### ISSUE TITLE
可以接收订阅，测速正常，无法打开外网

### ISSUE THREAD

**Issue by jackycheung00077** [yanue/V2rayU#556]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1)  V2RayU：2.1.0 
     Mac 版本 10.15.4 (19E287)

2) 出现故障：可以接收订阅，无法打开外网，测速正常

3) 请附上你的配置（不知道粘贴的对不对，小白一只）。
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1189"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1190"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/imga",
          "headers": {
            "host": "360622400-az1.yidianfenqi.com"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "jpcdn.zzmy.me",
            "users": [
              {
                "id": "8ff243f8-93fd-3ec3-86a2-7a84e58d3e10",
                "alterId": 2,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 80
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
4)  请附上出错时软件输出的错误日志。

2020/05/06 11:22:26 [Warning] [3858967846] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/05/06 11:22:26 [Warning] [3858967846] v2ray.com/core/proxy/http: failed to read response from ocsp.apple.com > io: read/write on closed pipe
2020/05/06 11:22:26 [Warning] [3858967846] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > v2ray.com/core/proxy/http: failed to write response > write tcp 127.0.0.1:1190->127.0.0.1:50840: write: broken pipe

请预览一下你填的内容再提交。

**Comment by SleepJavaer** [comment]
同样的问题，重新订阅，重新配置文件，代理模式切换，重装软件，没有解决问题。

**Comment by SleepJavaer** [comment]
> 提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
> 除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。
> 
> 1. V2RayU：2.1.0
>    Mac 版本 10.15.4 (19E287)
> 2. 出现故障：可以接收订阅，无法打开外网，测速正常
> 3. 请附上你的配置（不知道粘贴的对不对，小白一只）。
>    {
>    "log": {
>    "error": "",
>    "loglevel": "info",
>    "access": ""
>    },
>    "inbounds": [
>    {
>    "listen": "127.0.0.1",
>    "protocol": "socks",
>    "settings": {
>    "udp": false,
>    "auth": "noauth"
>    },
>    "port": "1189"
>    },
>    {
>    "listen": "127.0.0.1",
>    "protocol": "http",
>    "settings": {
>    "timeout": 360
>    },
>    "port": "1190"
>    }
>    ],
>    "outbounds": [
>    {
>    "mux": {
>    "enabled": false,
>    "concurrency": 8
>    },
>    "protocol": "vmess",
>    "streamSettings": {
>    "wsSettings": {
>    "path": "/imga",
>    "headers": {
>    "host": "360622400-az1.yidianfenqi.com"
>    }
>    },
>    "tlsSettings": {
>    "allowInsecure": true
>    },
>    "security": "none",
>    "network": "ws"
>    },
>    "tag": "proxy",
>    "settings": {
>    "vnext": [
>    {
>    "address": "jpcdn.zzmy.me",
>    "users": [
>    {
>    "id": "8ff243f8-93fd-3ec3-86a2-7a84e58d3e10",
>    "alterId": 2,
>    "level": 0,
>    "security": "aes-128-gcm"
>    }
>    ],
>    "port": 80
>    }
>    ]
>    }
>    },
>    {
>    "tag": "direct",
>    "protocol": "freedom",
>    "settings": {
>    "domainStrategy": "AsIs",
>    "redirect": "",
>    "userLevel": 0
>    }
>    },
>    {
>    "tag": "block",
>    "protocol": "blackhole",
>    "settings": {
>    "response": {
>    "type": "none"
>    }
>    }
>    }
>    ],
>    "dns": {},
>    "routing": {
>    "settings": {
>    "domainStrategy": "AsIs",
>    "rules": []
>    }
>    },
>    "transport": {}
>    }
> 4. 请附上出错时软件输出的错误日志。
> 
> 2020/05/06 11:22:26 [Warning] [3858967846] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
> 2020/05/06 11:22:26 [Warning] [3858967846] v2ray.com/core/proxy/http: failed to read response from ocsp.apple.com > io: read/write on closed pipe
> 2020/05/06 11:22:26 [Warning] [3858967846] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > v2ray.com/core/proxy/http: failed to write response > write tcp 127.0.0.1:1190->127.0.0.1:50840: write: broken pipe
> 
> 请预览一下你填的内容再提交。

我的问题解决了，V2ray配置的问题，我使用其他VMESS地址访问网络是可以的。之后再切换回原先的地址也可以访问了。

**Comment by jackycheung00077** [comment]
可我按照你的方法试了试，切换回来，还是无法使用相关的订阅的地址。你的配置文件是什么样的呢，方便截图吗？
@SleepJavaer

**Comment by jackycheung00077** [comment]
<img width="455" alt="截屏2020-05-10 下午9 12 44" src="https://user-images.githubusercontent.com/64859200/81500202-28fbd880-9303-11ea-8cbc-f4e1c49d70bf.png">

**Comment by SleepJavaer** [comment]
> <img alt="截屏2020-05-10 下午9 12 44" width="455" src="https://user-images.githubusercontent.com/64859200/81500202-28fbd880-9303-11ea-8cbc-f4e1c49d70bf.png">
> 
> @SleepJavaer 你看看和我的一样吗

我的图片上传不了，不过这块是没什么问题的。你再去你的服务上查一下，哪些通道还可用。我的国内通道全fail了，试了国外通道可以正常访问。

**Comment by jackycheung00077** [comment]
> > <img alt="截屏2020-05-10 下午9 12 44" width="455" src="https://user-images.githubusercontent.com/64859200/81500202-28fbd880-9303-11ea-8cbc-f4e1c49d70bf.png">
> > @SleepJavaer 你看看和我的一样吗
> 
> 我的图片上传不了，不过这块是没什么问题的。你再去你的服务上查一下，哪些通道还可用。我的国内通道全fail了，试了国外通道可以正常访问。

非常感谢，但是我的还是不行

**Comment by SleepJavaer** [comment]
> > > <img alt="截屏2020-05-10 下午9 12 44" width="455" src="https://user-images.githubusercontent.com/64859200/81500202-28fbd880-9303-11ea-8cbc-f4e1c49d70bf.png">
> > > @SleepJavaer 你看看和我的一样吗
> > 
> > 
> > 我的图片上传不了，不过这块是没什么问题的。你再去你的服务上查一下，哪些通道还可用。我的国内通道全fail了，试了国外通道可以正常访问。
> 
> 非常感谢，但是我的还是不行

你有其他的vmess地址吗？添加一个试试。

**Comment by jackycheung00077** [comment]
> > > > <img alt="截屏2020-05-10 下午9 12 44" width="455" src="https://user-images.githubusercontent.com/64859200/81500202-28fbd880-9303-11ea-8cbc-f4e1c49d70bf.png">
> > > > @SleepJavaer 你看看和我的一样吗
> > > 
> > > 
> > > 我的图片上传不了，不过这块是没什么问题的。你再去你的服务上查一下，哪些通道还可用。我的国内通道全fail了，试了国外通道可以正常访问。
> > 
> > 
> > 非常感谢，但是我的还是不行
> 
> 你有其他的vmess地址吗？添加一个试试。

试过了，还是不行。。。。我改用clashX了

**Comment by hxx094438** [comment]
同样的问题，还没有效的解决方案吗～

**Comment by yanue** [comment]
请确认配置,包含streamSettings
