### ISSUE TITLE
端口冲突及端口号问题

### ISSUE THREAD

**Issue by Scyllaly** [yanue/V2rayU#557]
1.V2RAYU 的默认 http 端口能否改为 10871 反正不要用1087 因为会与 shadowsocksr-ng 冲突
2.所有的端口号input 处能否不显示逗号，因为打开时默认显示 1,087 ，直接在 1,087后面直接加1成为 1,0871 它会提示端口号错误，使用时十分不便。

**Comment by yanue** [comment]
千分位的问题 不知道咋搞
