### ISSUE TITLE
会支持ACL吗

### ISSUE THREAD

**Issue by xieqing0428** [yanue/V2rayU#56]
还有这个手动模式是怎么体现的呢 感觉和全局没什么区别？

**Comment by xieqing0428** [comment]
PAC好像不能用，选择全局和手动能上油管，选择PAC却不可以

**Comment by yanue** [comment]
已优化,请下载1.3.1进行使用

**Comment by yanue** [comment]
> 还有这个手动模式是怎么体现的呢 感觉和全局没什么区别？

手动模式需要配合浏览器SwitchyOmega插件
