### ISSUE TITLE
自定义路由设置只有最后一条有效

### ISSUE THREAD

**Issue by ArsenicX** [yanue/V2rayU#560]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 2.1.0
MAC 10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
自定义路由设置只有最后一条有效<br>
我先把电脑的代理设置为【全局模式】，路由规则也设置为【IPifNonMatch】和【全局】
再在路由规则的**block**里面添加一条`regexp:.*adservice.*`
这时候用浏览器浏览 http://adservice.google.com 会提示站点不可达。<br>
但是如果我再添加一条`regexp:.*adeventtracker.*`，就会发现第一条规则失效了， http://adservice.google.com 又能进入了。<br>
拿下面这个规则举例子，添加到**block**中会发现只有豆瓣不能进，但是前两个还是正常能进；如果把豆瓣那行删了，就变成百度不能进了，但第一个还是可以正常访问
```
regexp:.*adservice.*,
regexp:.*baidu.*,
regexp:.*douban.*
```
同样的问题在**block**旁边的**代理**和**直连**中也存在，只有最后一行有效

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
略

4)  请附上出错时软件输出的错误日志。
略

**Comment by yanue** [comment]
```
regexp:.*adservice.*,
regexp:.*baidu.*,
regexp:.*douban.*
```
不要加,号,  一行一个配置即可,配置完后可以查看config.json进行确认
