### ISSUE TITLE
直连ip或域名怎么配置？

### ISSUE THREAD

**Issue by allenyulun** [yanue/V2rayU#561]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？ v2RAYU 2.1.0 , mac 10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
sourcetree内网拉代码的时候，pac模式代码拉不下来，看选项里能配置直连ip或域名，试了下无效，想知道怎么配置
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
 
```javascript
    可能是系统原因，sourcetree拉代码时，没有日志
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
设置->routing

**Comment by allenyulun** [comment]
试了下没用，sourcetree 连内网是还是不行
