### ISSUE TITLE
:failed to find an available destination不定时无法连接到服务器

### ISSUE THREAD

**Issue by LIUZHENGYU2019** [yanue/V2rayU#564]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 2.1.0
MAC Catalina 10.15.4
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
不定时无法访问外网，无论Pac模式还是全局模式下。服务器端是可以正常访问的，看了log好像是与服务器连接的问题，日志Warning如下所示。尝试在服务器端开放相关端口并保存并没有解决。最后在更换服务器v2ray端口之后就可以正常访问了。但是更换完端口号的第二天又出现了同样的问题。再次更换端口号就又可以正常访问了。有没有人清楚这是哪里的问题呢？
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "************",
            "users": [
              {
                "id": "344545eb-3558-4199-9850-***********",
                "alterId": 233,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 12121
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "8.8.8.8"
          ],
          "outboundTag": "proxy"
        }
      ]
    }
  },
  "transport": {}
}
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
2020/05/22 12:39:41 [Info] [3931012909] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:***:10021
2020/05/22 12:39:42 [Info] [792466330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:***:10021
2020/05/22 12:39:42 [Info] [3931012909] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:***:10021
2020/05/22 12:39:42 [Info] [446460704] v2ray.com/core/proxy/socks: TCP Connect request to tcp:mtalk.google.com:5228
2020/05/22 12:39:42 [Info] [446460704] v2ray.com/core/app/dispatcher: default route for tcp:mtalk.google.com:5228
2020/05/22 12:39:42 [Info] [446460704] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:***:10021
2020/05/22 12:39:42 tcp:127.0.0.1:53609 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/05/22 12:39:42 [Info] [3931012909] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:204.13.155.119:10021
2020/05/22 12:39:42 [Info] [792466330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:204.13.155.119:10021
2020/05/22 12:39:43 [Warning] [3931012909] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ************:10021: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/05/22 12:39:43 [Warning] [792466330] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ************:10021: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。
已经正常使用了3月左右，没有什么问题。昨天突然出现的这个问题，有没有人清楚这是哪里的问题呢？可以指教一下嘛，谢谢！！

**Comment by mclxly** [comment]
我刚刚遇到类似问题，题主解决没？

**Comment by CyrilTaylor** [comment]
是不是机场被ban了？有试过其他客户端连机场么

**Comment by mclxly** [comment]
> 是不是机场被ban了？有试过其他客户端连机场么

自建，能ssh

尝试了一些免费代理，也失败，几个月都是好好的，午饭后突然挂掉

**Comment by phf0313** [comment]
今天升级后突然也是出现这个问题

**Comment by mclxly** [comment]
解决了，换了个端口

**Comment by LIUZHENGYU2019** [comment]
及时的解决办法是换一个端口，但是还会出现类似的问题，不清楚是哪里的问题。
