### ISSUE TITLE
更新到2.1 后macbook 无法正常使用啊

### ISSUE THREAD

**Issue by thiter** [yanue/V2rayU#567]
求助
2020/05/25 10:36:35 [Info] [905048330] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/05/25 10:36:35 [Info] [905048330] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/05/25 10:36:35 [Info] [905048330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/05/25 10:36:35 tcp:127.0.0.1:52942 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/05/25 10:36:35 [Info] [905048330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/05/25 10:36:35 [Info] [905048330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/05/25 10:36:36 [Info] [905048330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/05/25 10:36:36 [Info] [905048330] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:1080
2020/05/25 10:36:36 [Info] [905048330] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 127.0.0.1:1080: connect: connection refused] > v2ray.com/core/common/retry: all retry attempts failed
2020/05/25 10:36:36 [Info] [905048330] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by thiter** [comment]
尴尬了,更换回到上一个版本也无法使用了.求助.

**Comment by static-host** [comment]
你不会换个端口？

**Comment by firstblood93** [comment]
同问，也没有日志生成

**Comment by yanue** [comment]
试下2.2 
另外: lsof -i :1080 看下 然后 kill -9
