### ISSUE TITLE
unknown cipher method: aes-128-ctr > exit status 255

### ISSUE THREAD

**Issue by Chillimeat** [yanue/V2rayU#568]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
macos 10.15.3 V2Ray 4.23.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
错误日志如下：
main: failed to read config files: [/Applications/V2rayU.app/Contents/Resources/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
v2ray.com/core/infra/conf: unknown cipher method: aes-128-ctr > exit status 255
无法上网
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "error": "",
    "loglevel": "debug",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "streamSettings": {
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "tcp"
      },
      "tag": "proxy",
      "settings": {
        "servers": [
          {
            "port": 11024,
            "method": "aes-128-ctr",
            "password": "aRNNXJ",
            "address": "XXXXXXXXX",
            "level": 0,
            "email": "",
            "ota": false
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
main: failed to read config files: [/Applications/V2rayU.app/Contents/Resources/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
v2ray.com/core/infra/conf: unknown cipher method: aes-128-ctr > exit status 255
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
不支持 aes-128-ctr
