### ISSUE TITLE
什么时候加入导出服务器配置的功能？

### ISSUE THREAD

**Issue by vcan** [yanue/V2rayU#573]
一直在用，V2ray mac客户端里最好用的，主要是其他一个能打的都没有。
但是美中不足的就是没有导出配置的功能，换台电脑，只能一个一个的加配置，非常恼火。
每次一个一个的扫码，画面太美。
希望加入导出服务器配置的功能，以后再也不用一个一个的导入了。

**Comment by BillChen2K** [comment]
同样希望有一个一键导出所有配置的功能。

**Comment by hhhaiai** [comment]
+1
