### ISSUE TITLE
无法找到出口，不能找到可用的目的

### ISSUE THREAD

**Issue by wangleibiancheng** [yanue/V2rayU#574]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2.1.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 72.19.12.55:36778: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1090"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/xv2ray",
          "headers": {
            "host": "phka3.123654.in"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "phka3.123654.in",
            "users": [
              {
                "id": "519d5e80-a0a8-11ea-be0b-1730569b0b10",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。

```javascript
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 72.19.12.55:36778: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
请确认参数,地址是可用d

**Comment by wangleibiancheng** [comment]
确认什么参数呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yanue"<notifications@github.com&gt;; 
发送时间: 2020年5月29日(星期五) 上午9:36
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;; 
抄送: "王磊"<2335837493@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanue/V2rayU] 无法找到出口，不能找到可用的目的 (#574)





 
请确认参数,地址是可用d

**Comment by wtry** [comment]
> 确认什么参数呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yanue"<notifications@github.com&gt;; 发送时间: 2020年5月29日(星期五) 上午9:36 收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;; 抄送: "王磊"<2335837493@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [yanue/V2rayU] 无法找到出口，不能找到可用的目的 (#574) 请确认参数,地址是可用d — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不知道是 vmess 的问题，还是  极游 的问题   极游 的vmess 全部 都是找不到 可用

**Comment by yanue** [comment]
请先到其他平台测试ok再反馈

**Comment by wangleibiancheng** [comment]
手机时可用的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yanue"<notifications@github.com&gt;; 
发送时间: 2020年5月29日(星期五) 上午9:48
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;; 
抄送: "王磊"<2335837493@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanue/V2rayU] 无法找到出口，不能找到可用的目的 (#574)





 
请先到其他平台测试ok再反馈
