### ISSUE TITLE
V2rayUHelper 升级至2.2.0后，仍然咆哮

### ISSUE THREAD

**Issue by zhqiyi** [yanue/V2rayU#575]
![image](https://user-images.githubusercontent.com/2107075/83208940-9de76300-a189-11ea-9ff9-bca99690a209.png)

如图，请老板看看

**Comment by yanue** [comment]
这个工具有2个功能那就是检查端口导致的  不是ping

**Comment by zhqiyi** [comment]
杀掉helper进程，恢复正常，wall也正常骑

**Comment by Kimi-Gao** [comment]
经常让CPU 咆哮 这个问题很影响使用
![image](https://user-images.githubusercontent.com/12554487/83215440-8adc8f00-a199-11ea-9dc1-ca43e90c55d1.png)

**Comment by sakuraovq** [comment]
咆哮的心慌慌

**Comment by xiebruce** [comment]
我这里貌似就是睡眠再恢复会咆哮，其它时间没发现会。macOS: `10.14.4`，后面有情况再补！

**Comment by summerKK** [comment]
我的也是.休眠发烫那么厉害

**Comment by sakz** [comment]
2.2.0版本的ping测试有问题，结果差太远了，基本都是美国线路，全是几十ms，正常应该是200ms左右的
![ping.png](https://i.loli.net/2020/06/10/TnARQVo5WM9tO3e.png)

**Comment by xiebruce** [comment]
哎，这个功能我是不太在意，我就是希望那个自定义的gfw list在保存时能起效果，目前2.2还是不起效果🤣

**Comment by axetroy** [comment]
![截屏2020-06-20 17 29 18](https://user-images.githubusercontent.com/9758711/85198495-c0e5dc80-b31b-11ea-9591-30e007a62c87.png)

同样，CPU 疯狂飙升，风扇一直在转

**Comment by cipchk** [comment]
2.2 我刚才也遇到了，结束掉重来就好了，哎……
