### ISSUE TITLE
开机时未启动 V2RayU，1080端口仍然被其相关服务占用。

### ISSUE THREAD

**Issue by clintwan** [yanue/V2rayU#577]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.2.0
10.15.5

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
开机时未启动 V2RayU，1080端口仍然被其相关服务占用。

**Comment by clintwan** [comment]
将 ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist 删除后重启操作系统，问题不再现。

再次启动 V2RayU 后，会自动生成 ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist。
此时退出 V2RayU 后再重启操作系统。
仍然会自动启动 V2rayU.app/Contents/Resources/v2ray-core/v2ray，表现如下：

$ lsof -i tcp:1080
COMMAND PID  USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
v2ray   366 clint    6u  IPv4 0x3aefcc8e9f60f3d      0t0  TCP localhost:socks (LISTEN)

**Comment by clintwan** [comment]
将 ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist 中的 KeepAlive 修改为 <false/> 后重启操作系统，问题不再现。

但启动 V2RayU 后，该配置文件中的 KeepAlive 会被恢复成  <true/>。
因此问题将继续出现。

**Comment by zhaozyzhaozy** [comment]
你是开着软件直接关机的吧。这个软件退出时会设置false，强制退出当然就不会了。然后v2ray core 就开机自动启动了。 我也发现这个问题，希望大佬改一改。能不能换种方式拉起v2ray core

**Comment by clintwan** [comment]
> 你是开着软件直接关机的吧。这个软件退出时会设置false，强制退出当然就不会了。然后v2ray core 就开机自动启动了。 我也发现这个问题，希望大佬改一改。能不能换种方式拉起v2ray core

建议你仔细看看我写的。
我退出 V2rayU （在顶部菜单栏点击 V2rayU 图标，然后在出现的菜单里点击最后一项）时，
~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist 中的 KeepAlive 没有被设置为 false

**Comment by Setsunalxxl** [comment]
我也出现了这个问题，只从我mac更新到最新的系统之后，所以这几天我一直在使用小飞机

**Comment by zhaozyzhaozy** [comment]
上一个版本我记得是手动退出重启不会拉起代理v2ray core。这次很奇怪，我手动退出后，用cleanmymac这款软件看他的plist是被禁用的，重启就变成启用了。

**Comment by yanue** [comment]
#732 478

**Comment by followztx** [comment]
流氓软件，总是开机自启，卸载掉吧。
