### ISSUE TITLE
升级v2.2.0后点ping后程序自动退出，ping出的ms值也不对

### ISSUE THREAD

**Issue by kbkbqiang** [yanue/V2rayU#585]
![image](https://user-images.githubusercontent.com/14084365/83343849-60720980-a332-11ea-97d6-3122fd0ed03b.png)

**Comment by michaellee123** [comment]
我也遇到了，而且计时感觉是有规律的递增的，还有就是有些其实并不能ping通的也显示了时间

**Comment by dallion** [comment]
是的 我也遇到了相似的问题

**Comment by yanue** [comment]
#739
