### ISSUE TITLE
Mac os上面的客户端遇到一些问题

### ISSUE THREAD

**Issue by Eastion** [yanue/V2rayU#587]
哎按了个回车居然自动发送了
简单说就是，我这边有两个网络环境，一个是家里一个是公司
在公司用v2rayX和V2rayU都可以正常使用，但是在家里却两个都死活上不去
系统版本是目前macos最新的
家里的网络环境是联通的
但是家里面用ipad、iphone、android走一样的订阅配置就可以顺利的使用
这个问题不知道应该怎么解决
按照V2rayU默认设置的 本地sock端口1080 host是127.0.0.1 http端口是1087 监听是127.0.0.1 pac监听端口是11085
以下是连接日志文件，一直报443
`2020/05/31 12:50:49 [Info] [3933670353] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/05/31 12:50:49 [Info] [3933670353] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:49 tcp:127.0.0.1:55943 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/05/31 12:50:50 [Info] [1693149275] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/05/31 12:50:50 [Info] [292917361] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/05/31 12:50:50 [Info] [292917361] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/05/31 12:50:50 [Info] [292917361] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:50 tcp:127.0.0.1:55944 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/05/31 12:50:51 [Info] [1693149275] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:51 [Info] [3122992540] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/05/31 12:50:51 [Info] [3122992540] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:51 [Info] [1693149275] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:51 [Info] [3122992540] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:52 [Info] [1693149275] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:52 [Info] [3289087137] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/05/31 12:50:52 [Info] [3289087137] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:52 [Info] [3122992540] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:52 [Info] [3289087137] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:53 [Warning] [1693149275] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://jp01.ipv2.xyz/ray):  > dial tcp: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://jp01.ipv2.xyz/ray):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/05/31 12:50:53 [Warning] [3122992540] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://jp01.ipv2.xyz/ray):  > dial tcp: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://jp01.ipv2.xyz/ray):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/05/31 12:50:53 [Info] [3289087137] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:54 [Warning] [3289087137] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://jp01.ipv2.xyz/ray):  > dial tcp: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://jp01.ipv2.xyz/ray):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/05/31 12:50:54 [Info] [1656288377] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:55 [Info] [2391001280] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:57 [Info] [2822841919] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/05/31 12:50:57 [Info] [2822841919] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
2020/05/31 12:50:58 [Info] [2822841919] v2ray.com/core/transport/internet/websocket: creating connection to tcp:jp01.ipv2.xyz:443
`

**Comment by mengyalei** [comment]
目测你当前连接的这个节点jp01.ipv2.xyz:443使用的是中转，而且这个中转服务器没有配置tls，所以V2rayU会一直报错这个。

**Comment by Eastion** [comment]
谢谢，已经解决了，wifi网卡的dns设置错了长期没发现&nbsp;





--------------------------------------------------------------------------------------------
Eastion Shen
+86 13860640933
Email:yichenshen@foxmail.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mengyalei"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 下午3:43
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;; 
抄送: "沈奕琛"<yichenshen@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanue/V2rayU] Mac os上面的客户端遇到一些问题 (#587)





 
目测你当前连接的这个节点jp01.ipv2.xyz:443使用的是中转，而且这个中转服务器没有配置tls，所以V2rayU会一直报错这个。
