### ISSUE TITLE
mac遇到的问题

### ISSUE THREAD

**Issue by Panacea-creator** [yanue/V2rayU#592]
点击打开v2ray的时候为什么会显示bind: address already in use呢？咋解决这个问题

**Comment by Panacea-creator** [comment]
V2rayU: v2.2.0
Macos: 10.15.5

**Comment by kungege** [comment]
同问

**Comment by glloyd0314** [comment]
你大概也在用/用过ss？如果是的话那大概就是两者的端口冲突了，高级设置里把http和socks的默认端口（大概是1080和1088）改一下就行了。

**Comment by Panacea-creator** [comment]
@glloyd0314 
我之前用过shadowsocks，但是前段时间把它删了没再用了。v2ray里的设置改成啥好啊~
![image](https://user-images.githubusercontent.com/64947402/83480584-67ce1a00-a4ce-11ea-84e5-9f3c46a3da1f.png)

**Comment by glloyd0314** [comment]
> @glloyd0314
> 我之前用过shadowsocks，但是前段时间把它删了没再用了。v2ray里的设置改成啥好啊~
> ![image](https://user-images.githubusercontent.com/64947402/83480584-67ce1a00-a4ce-11ea-84e5-9f3c46a3da1f.png)

改成1080之外的端口就行啦，比如1081、10808之类的，如果还有问题的话http也类似改一下

**Comment by Panacea-creator** [comment]
@glloyd0314 谢谢你！！可以开了哈哈～～

**Comment by AgnellePapa** [comment]
shadowsocks用得很顺啊，为什么这个真的连不上google，换了好多个节点了呜呜呜

**Comment by urara7** [comment]
> > @glloyd0314
> > 我之前用过shadowsocks，但是前段时间把它删了没再用了。v2ray里的设置改成啥好啊~
> > ![image](https://user-images.githubusercontent.com/64947402/83480584-67ce1a00-a4ce-11ea-84e5-9f3c46a3da1f.png)
> 
> 改成1080之外的端口就行啦，比如1081、10808之类的，如果还有问题的话http也类似改一下

大神求一个联系方式，我mac也链接不上，已经写了一个帖子了，但是没人回复，你能帮帮我吗
