### ISSUE TITLE
PING数值异常

### ISSUE THREAD

**Issue by dallion** [yanue/V2rayU#594]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2ray 2.2.0
Mac 10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

更新2.2.0以后，ping的时间计算比较奇怪，体现为ping的结果在服务器列表中从上之下大体上有序递增，偶有几个稍有不同，**而且数值极大**

----------- 更新 ----------

按照 [#588](https://github.com/yanue/V2rayU/issues/588) 更新core 以后数值极大的问题已经消失，估计是墙的问题，但是测试ping值有序的问题仍旧存在

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by bl0** [comment]
你好，你的这个问题解决了吗？我也遇到了同样的问题。 @dallion

**Comment by dallion** [comment]
> 你好，你的这个问题解决了吗？我也遇到了同样的问题。 @dallion

没有 这个有时候出现有时候不出现往往是用的久了就会出现 而且网络越差效果越明显

**Comment by yanue** [comment]
#739

**Comment by kb5706** [comment]
好几个节点ping一直是 -1ms，有人跟我一样的吗？
