### ISSUE TITLE
请更新V2RayU程序的V2rayCore版本到最新版

### ISSUE THREAD

**Issue by r00t4dm** [yanue/V2rayU#596]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
正在使用V2RayU 2.2.0 v2ray-core 4.23.2
mac catalina 10.15.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray-core 发布了 4.23.4 的更新，该版本更新包含了重大安全漏洞修复
https://github.com/v2ray/v2ray-core/releases

**Comment by xmucyp** [comment]
v2ray-core文件: /Applications/V2rayU.app/Contents/Resources/v2ray-core

**Comment by xmucyp** [comment]
可以暂时手动更新，下载4.23.4 对应的mac包，然后手动替换。
v2ray-core文件: /Applications/V2rayU.app/Contents/Resources/v2ray-core

**Comment by liyuhaolol** [comment]
兄弟这个软件启动就会自动更新v2ray内核，并不要你做什么，也不是bug

**Comment by zyings** [comment]
可以自己下载最新的core去目录下面替换一下

**Comment by Shawshank01** [comment]
其实是会自动更新的 但是因为使用的是v2ray项目的源而不是v2fly 所以更新时效会慢一些

**Comment by DanielYWoo** [comment]
有bug,升级2.2.0之后删除了我的v2ray-core. 我手动copy dmg内的v2ray-core目录过来才行

**Comment by 3vilive** [comment]
> 有bug,升级2.2.0之后删除了我的v2ray-core. 我手动copy dmg内的v2ray-core目录过来才行

我也出现了

**Comment by r00t4dm** [comment]
我直接用v2ray-core了。。。搭配配置文件很方便

**Comment by bennieniu** [comment]
> 可以自己下载最新的core去目录下面替换一下

请问在哪里替换呀
