### ISSUE TITLE
无法使用IP白名单PAC,提示failed to update

### ISSUE THREAD

**Issue by asmburning** [yanue/V2rayU#599]
https://raw.githubusercontent.com/breakwa11/gfw_whitelist/master/whiteiplist.pac
gfw黑名单越来越难以维护和使用, en.wikimedia.org 等等网站pac模式下无法打开
建议支持白名单模式,墙内网站直连,其他走代理

**Comment by curryhendry** [comment]
同，建议增加白名单，这样省心一些。小白维护PAC太麻烦。

**Comment by asmburning** [comment]
已经替换客户端为clash
