### ISSUE TITLE
求支持 Shadowrocket-ADBlock-Rules

### ISSUE THREAD

**Issue by leegang** [yanue/V2rayU#6]
Shadowrocket-ADBlock-Rules
https://github.com/h2y/Shadowrocket-ADBlock-Rules

这里有很多现成的配置规则，希望支持

**Comment by yanue** [comment]
好的 规划中

**Comment by yanue** [comment]
应该可以使用手动编辑模式: https://toutyrater.github.io/basic/routing/adblock.html, 你可以试一下
后面有单独计划在弄吧
