### ISSUE TITLE
希望移除「切换代理模式」中的手动模式

### ISSUE THREAD

**Issue by reepic** [yanue/V2rayU#602]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2.2.0  |  10.15.6 Beta

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
个人习惯是默认PAC模式，当临时某些网站打不开时通过快捷键切到全局（高频的才会加到自定规则中），很少用到手动模式（手动模式的配置对于大多数用户来说比较麻烦吧）。切换代理模式存在一个「手动模式」时，就会导致从全局模式切回自动模式时要多按一次快捷键。
~~之前在 ShadowsocksX-NG 也提过类似的 issue (https://github.com/shadowsocks/ShadowsocksX-NG/issues/931)~~

**Comment by Erope** [comment]
个人习惯是使用手动模式，手动模式对于大多数使用SwitchyOmega的用户是刚需吧，很少用到PAC模式。

**Comment by reepic** [comment]
不太清楚其他用户的使用习惯，之前也一直不知道「手动模式」的使用场景。看了下https://github.com/shadowsocks/ShadowsocksX-NG/issues/27 的讨论，这样来说，对于不使用 _SwitchyOmega_ 类软件内部代理方案，而采用全局智能分流 Pac 模式的用户来说，手动模式好像没什么存在的意义。
不知道在 Preference 里加个开关能不能解决两类用户的需求，当然，这样也会让设置项过于复杂……

**Comment by h2so** [comment]
> 不太清楚其他用户的使用习惯，之前也一直不知道「手动模式」的使用场景。看了下[shadowsocks/ShadowsocksX-NG#27](https://github.com/shadowsocks/ShadowsocksX-NG/issues/27) 的讨论，这样来说，对于不使用 _SwitchyOmega_ 类软件内部代理方案，而采用全局智能分流 Pac 模式的用户来说，手动模式好像没什么存在的意义。
> 
> 不知道在 Preference 里加个开关能不能解决两类用户的需求，当然，这样也会让设置项过于复杂……

在macOS 10.15上，因为存在OpenSSH的bug，一旦开启pac，会影响ssh方式使用git，另外一些情况下，不希望改动系统PAC的时候，手动模式是刚需。

**Comment by knownothingsnow** [comment]
你用不到,不代表别人用不到.如果特别影响你的使用,可以修改源码之后自己编译一下.
