### ISSUE TITLE
启动不了软件

### ISSUE THREAD

**Issue by wen424005910** [yanue/V2rayU#607]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
MAC
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
启动不了代理显示http error - listen tcp 127.0.0.1:1087: bind: address already in use
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
按照V2rayU设置设置的本地sock端口1080 host是127.0.0.1 http端口是1087监听是127.0.0.1 pac监听端口是11085
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```
显示
<img width="736" alt="WechatIMG1" src="https://user-images.githubusercontent.com/36161460/84242440-6c7c7900-ab33-11ea-8efb-685b0f5eb6ab.png">
http error - listen tcp 127.0.0.1:1087: bind: address already in use
请预览一下你填的内容再提交。

**Comment by maozimaozi** [comment]
你好，想请问下你这个问题后来解决了吗？是怎么解决的呀

**Comment by wen424005910** [comment]
> 你好，想请问下你这个问题后来解决了吗？是怎么解决的呀

之前的VPN把端口占了，我把之前的VPN的软件完全删除了就可以了

**Comment by maozimaozi** [comment]
好滴 谢谢

**Comment by maozimaozi** [comment]
不好意思，想再问一下，请问是怎么完全删掉之前VPN的软件的呀，我已经把VPN软件删掉好久了，但还是会提示端口占用
