### ISSUE TITLE
shadowsocks订阅不支持混淆?手工修改json可以支持吗还是程序不支持

### ISSUE THREAD

**Issue by supine-win** [yanue/V2rayU#608]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.2.0 10.15
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
shadowsocks订阅不支持混淆?

**Comment by yanue** [comment]
不支持
