### ISSUE TITLE
内网socks身份认证问题

### ISSUE THREAD

**Issue by xdxiaodong** [yanue/V2rayU#609]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
手动模式里服务器设置选择socks协议时，用户名密码不填时不应该往json配置里写入空字符串，而是users字段不应该写入，因为提供空字符串会导致没有身份验证的内网socks无法正常使用。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by LeeCenY** [comment]
Fixed https://github.com/yanue/V2rayU/pull/605
