### ISSUE TITLE
请问怎么解决pac模式下Apple mail无法连接gmail问题

### ISSUE THREAD

**Issue by LaurenceSamael** [yanue/V2rayU#61]
发现Mac Mojave下的mail app在pac模式下无法连接gmail，提示：Connections to the server “imap.gmail.com” on the default ports timed out.
只有global模式下才能正常，请问怎么解决pac模式无法连接gmail的问题？
谢谢

**Comment by yanue** [comment]
pac模式一般配合浏览器插件SwitchyOmega一起使用,便于自己编辑PAC规则,mail app那边应该不支持这种模式吧

**Comment by gqbre** [comment]
mail app 无法单独设置代理，建议使用 Proxifier
