### ISSUE TITLE
backup and sync google在MAC上无法登陆

### ISSUE THREAD

**Issue by mengyalei** [yanue/V2rayU#610]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU版本2.2.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
打开V2rayU可以正常打开油管等国外网站，但是backup and sync google同步软件却一直无法登陆使用，必须要借助Proxifier这款代理软件才能让backup and sync google同步软件正常使用。
应该是V2rayU没有底层网卡这类的代理模式吧（咱也不是很懂，说错了别打！）？希望万能的开发者考虑增加下这个功能，感谢各位的贡献！

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by DanielYWoo** [comment]
global模式可以, switchy omega之类的插件无效. 感觉这是chrome行为问题, 不是v2ray问题
