### ISSUE TITLE
Mac盖上盖子后第二天再打开盖子V2RayU退出了

### ISSUE THREAD

**Issue by dupeng0811** [yanue/V2rayU#611]
1) 你正在使用的 V2RayU 和 Mac 版本 ？ 
v2.2.0 Mac 版本10.15.5

2) 你遇到的问题是什么？
Mac盖上盖子后第二天再打开盖子V2RayU退出了，没看到有什么报错。

**Comment by dupeng0811** [comment]
同事的Mac也是一样的问题，应该不是我电脑配置的问题

**Comment by carlchina** [comment]
应该不是退出，只是时间栏图标不见了，但是程序进程，功能都好的。

**Comment by dupeng0811** [comment]
> 应该不是退出，只是时间栏图标不见了，但是程序进程，功能都好的。

应该是退出了，因为是科学上不了网了才发现V2RayU退出的。

**Comment by urara7** [comment]
可以求大神一个联系方式吗？我连了一个梯子，Mac上安装了v2ray添加了节点，却都是0ms，求解😭

**Comment by dupeng0811** [comment]
回滚到2.0.0没这个问题了.先用老版本吧。
