### ISSUE TITLE
pac模式下访问不了谷歌或github等

### ISSUE THREAD

**Issue by TimbokY** [yanue/V2rayU#612]
1.  v2RayU Version `2.2.0 ` Mac Version `10.15.4`
2. pac模式下访问不了谷歌或github等，pac配置文件在`gfwlist`更新，开全局模式才可成功搭上梯子。

**Comment by Elliot-hao** [comment]
我也是，pac文件的问题

**Comment by mengdodo** [comment]
检查自己网络的代理设置

**Comment by TimbokY** [comment]
> 检查自己网络的代理设置

请问网络代理设置从哪下手，现在我只确定端口没被占用

**Comment by Elliot-hao** [comment]
请问能不能给一份pac文件

**Comment by TimbokY** [comment]
> 请问能不能给一份pac文件

pac是用的线上的 [gfwlist.txt](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt)

**Comment by Plutoscat** [comment]
主站能进，发布留言时需要切换到Global模式

**Comment by TimbokY** [comment]
> 主站能进，发布留言时需要切换到Global模式。
> 自己再PAC里面增加一条规则后，正常了
> ||github.com^

感谢，加上这条规则可以了耶

**Comment by Elliot-hao** [comment]
感谢 已经正常了
thanks so much

**Comment by yanue** [comment]
#740

**Comment by Evans-Li** [comment]
> 主站能进，发布留言时需要切换到Global模式。
> 自己再PAC里面增加一条规则后，正常了
> ||github.com^

请问下规则在那个文件中添加呢？

**Comment by Evans-Li** [comment]
> > 请问能不能给一份pac文件
> 
> pac是用的线上的 [gfwlist.txt](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt)

线上的失效了 ， 从哪里下载最新的文件呢

**Comment by Whyjsee** [comment]
> 主站能进，发布留言时需要切换到Global模式。
> 自己再PAC里面增加一条规则后，正常了
> ||github.com^

管用，谢了兄弟

**Comment by azin-cn** [comment]
> > 主站能进，发布留言时需要切换到Global模式。
> > 自己再PAC里面增加一条规则后，正常了
> > ||github.com^
> 
> 感谢，加上这条规则可以了耶

感谢，管用了

**Comment by jackywq** [comment]
> 主站能进，发布留言时需要切换到Global模式。 自己再PAC里面增加一条规则后，正常了 ||github.com^

感谢，正常了

**Comment by 503580622** [comment]
> 主站能进，发布留言时需要切换到Global模式。 自己再PAC里面增加一条规则后，正常了 ||github.com^

感谢，管用啊

**Comment by feizhaojun** [comment]
gfwlist 里面吧 fonts.googleapis.com 写成例外了，不走代理，怎么给覆盖掉？
