### ISSUE TITLE
无法导入 V2rayN 生成的 vmess 链接

### ISSUE THREAD

**Issue by poly-1** [yanue/V2rayU#613]
如题，v2rayN 应该是目前比较流行的v2ray GUI 客户端，但是v2rayU不能导入其生成的链接，估计是实现上有些问题（对比一下qv2ray是可以正常导入的）。

不能导入的原因估计是v2rayN生成的链接对应的解码后的json格式每一项都是单独的一行，而不是把所有项排成同一行，于是导入的时候出了问题。

**Comment by yanue** [comment]
#613
