### ISSUE TITLE
Catalina OS 10.15.4 编译出现 ./Common/V2rayU-Bridging-header.h 找不到的问题

### ISSUE THREAD

**Issue by ablueday** [yanue/V2rayU#614]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
MAC：Catalina OS 10.15.4
V2rayU：2.2.0
xcode：11.4
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
想尝试自己编译，把签名改成 local 后，编译出错（如题），说工程目录中 ./Common/V2rayU-Bridging-header.h 找不到（错误 log 见 error1），但我发现 xcode 工程目录中有 Common 目录里边也有相应的 .h 文件

![image](https://user-images.githubusercontent.com/18501666/85199866-45892880-b325-11ea-81a7-07df578cc93b.png)

并且，我发现 Finder 目录中确实有个 V2rayU-Bridging-header.h 文件，自己新建了个 Common 目录，把该 .h 文件放进去后，重新编译后提示 MASShortcut/Shortcut.h 找不到（见 error2）

于是，我把 pod install 下载的 MASShortcut 放到工程父目录下，然后另一个类似的某个文件找不到的问题出来了，我用同样的方法挪动那些文件，但是后面发现坑越来越多 ...... 被打击信心了，前面安装 cocoapds 就折腾了很久。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

error1:
`<unknown>:0: error: error opening input file '/Users/xxx/Downloads/V2rayU-2.2.0/Common/V2rayU-Bridging-header.h' (No such file or directory)`

error2:
`/Users/xxx/Downloads/V2rayU-2.2.0/Common/V2rayU-Bridging-header.h:5:9: error: 'MASShortcut/Shortcut.h' file not found
#import <MASShortcut/Shortcut.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/xxx/Library/Developer/Xcode/DerivedData/V2rayU-aqjfkzldnxqsreejgbveirgfxjbc/Build/Intermediates.noindex/PrecompiledHeaders/V2rayU-Bridging-header-swift_K4LI53ZLSN6L-clang_2LRGIJOJLN4F4.pch' for bridging header '/Users/xxx/Downloads/V2rayU-2.2.0/Common/V2rayU-Bridging-header.h'`

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
加上了
