### ISSUE TITLE
V2RayU没日志 2.2版本也是无法解决

### ISSUE THREAD

**Issue by qqppwskj** [yanue/V2rayU#616]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2rayU 10.14.5
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
查看日志没有信息，连不上，换一台mac又可以，同样的系统
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by DanielYWoo** [comment]
我也没有日志, 只能命令行执行 /Applications/V2rayU.app/Contents/MacOS/V2rayU 看日志. 
2.2.0

**Comment by JimAmuro** [comment]
我也是 突然就没日志了 程序也用不了了 端口根本没打开

**Comment by lander1003** [comment]
> 我也是 突然就没日志了 程序也用不了了 端口根本没打开

我也是这个情况，请问你解决了吗

**Comment by ZWLXX** [comment]
我也是这样，昨天突然不行了。换了个客户端就可以了

**Comment by DanielYWoo** [comment]
@ZWLXX  重新安装一遍就行了, 因为2.2.0处理core升级可能有问题, 导致core被误删除了, 但是界面没有正确的提示错误.

**Comment by ZWLXX** [comment]
@DanielYWoo 我重装了也不行。后来看到重新替换v2ray-core才解决问题

**Comment by DanielYWoo** [comment]
@ZWLXX 重装不可能不行啊, dmg拖过去的时候你如果选择replace, 那么会把dmg里resources目录里的core也copy一份过去的. 不过这不重要了, 重要的是原因基本清楚了, 就是core被v2rayU删除了.....
