### ISSUE TITLE
为什么软件会访问 gitee.com ？

### ISSUE THREAD

**Issue by stfenjobs** [yanue/V2rayU#618]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

都最新版

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**软件访问了 gitee.com 和api.github.com , 想问下访问的原因是什么， gitee.com是国内网站**

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
   无
```
4)  请附上出错时软件输出的错误日志。

```javascript
    无
```

**Comment by Whotakesmyname** [comment]
应该是使用了Sparkle开源自动更新框架。在repo项目目录下info.plist中SUFeedURL有托管在gitee的一个xml，跟踪可见是一个更新文档。可能是为了方便国内使用吧。不想访问可以自己改一个地址重新编译打包试试。
