### ISSUE TITLE
我想知道这警告是什么情况，麻烦解释下

### ISSUE THREAD

**Issue by bihell** [yanue/V2rayU#620]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

V2RayU 2.2.0  Mac 10.15.5 

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

为什么会有录屏警告

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

无需配置信息

4)  请附上出错时软件输出的错误日志。

截图如下：

![image](https://user-images.githubusercontent.com/19926035/85531824-af654300-b641-11ea-8a10-f1f9a791ef77.png)

**Comment by dallion** [comment]
这个是扫二维码需要读取你屏幕的信息吧
