### ISSUE TITLE
能否实现自动更新订阅功能？

### ISSUE THREAD

**Issue by li2412360774** [yanue/V2rayU#621]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU：V2.2.0 Mac:10.15.5
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法自动更新订阅

我查了下其他的相关Issue，貌似都被关闭或者解决了？，希望能教一下如何自动更新订阅

**Comment by yanue** [comment]
启动或唤醒
