### ISSUE TITLE
MacOS 10.15.3节点速率都是0ms，在iPhone上可正常使用

### ISSUE THREAD

**Issue by urara7** [yanue/V2rayU#624]
求各位大神帮忙解答一下，在一个没有客服的网站充值了一个梯子，给了节点，iPhone上可以正常使用，但Mac上没有速度，都是0ms，求解答，研究好几天了也没明白，跪谢🙏
补充了图片：全局模式和手动模式都试了，都不行，其中改为全局模式后连百度都打不开。
![WechatIMG1](https://user-images.githubusercontent.com/67512091/85938247-1cc4ec80-b93e-11ea-9060-a680c4d1b6cc.jpeg)

**Comment by xiaoer3301** [comment]
拖进来即可

**Comment by urara7** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/67512091/85938214-c788db00-b93d-11ea-96b4-1872b8ed723d.jpeg)


> 图片拖进来即可

**谢谢，拖进来了，就是这样，全局代理和手动代理都试了，全都是0ms🙏求大神解答**

**Comment by urara7** [comment]
> 图片拖进来即可

好的谢谢，加在一楼了🙏

**Comment by yanue** [comment]
查看v2ray日志

**Comment by urara7** [comment]
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by urara7** [comment]
纯小白，还望各位大神指点

**Comment by mingdq1** [comment]
把1087的端口换别的看看

**Comment by urara7** [comment]
<img width="449" alt="截屏2020-07-02下午2 40 29" src="https://user-images.githubusercontent.com/67512091/86325115-21f1a680-bc72-11ea-9a16-40d30dcdc02f.png">
还是不行……

**Comment by mingdq1** [comment]
> <img alt="截屏2020-07-02下午2 40 29" width="449" src="https://user-images.githubusercontent.com/67512091/86325115-21f1a680-bc72-11ea-9a16-40d30dcdc02f.png">
> 
> 还是不行……

换了端口号 再打开看看日志报什么 发出来看看

**Comment by urara7** [comment]
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2020/07/02 14:37:45 [Warning] v2ray.com/core: V2Ray 4.21.3 started
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2020/07/02 15:37:56 [Warning] v2ray.com/core: V2Ray 4.21.3 started
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2020/07/02 18:56:48 [Warning] v2ray.com/core: V2Ray 4.21.3 started

**Comment by cxy2333355** [comment]
是不是电脑上防火墙吧v2ray给禁了？

**Comment by yanue** [comment]
#739
