### ISSUE TITLE
希望增加大陆白名单模式  

### ISSUE THREAD

**Issue by lifengZero** [yanue/V2rayU#625]
希望增加大陆白名单模式   大陆白名单 不走代理  不知道好不好实现啊  谢谢

**Comment by Plutoscat** [comment]
软件的设置有一个Routing Rule设置里面有一个选项是Bypassing LAN and Mainland，这个看起来就是大陆白名单模式，是不是这个功能还没有实现？或者要怎么用这个功能？
![image](https://user-images.githubusercontent.com/49501931/86192392-17ed7c00-bb7c-11ea-8ac8-555220d97f99.png)

**Comment by curryhendry** [comment]
同问！
