### ISSUE TITLE
v2rayU禁用开机启动功能无效

### ISSUE THREAD

**Issue by wuwentao** [yanue/V2rayU#632]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

```
v2rayU: 2.2.0
MacOS: 10.15.5
```
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

**需要禁用的原因：**
我还需要运行其他proxy，chrome默认使用1080端口，手工运行不同的proxy软件即可，否则还需要来回去切换端口，切换chrome的proxy配置，经常容易忘记，动不动就网页无法显示，才发现v2rayU一直后台占用了1080端口，而其他proxy无法运行

已经在参数设置里面取消打钩了，但是取消开机启动功能无效，依然后台自动运行
通过```ps aux |grep v2```还是可以看到运行中的后台进程：

```
xxx@xxx-mbp:~#ps aux |grep v2
xxx               843   0.0  0.0  4398864   2576   ??  S     4:59PM   0:00.74 ./v2ray-core/v2ray -config /Applications/V2rayU.app/Contents/Resources/config.json
_driverkit         496   0.0  0.0  4815688    644   ??  Ss    4:58PM   0:00.02 /System/Library/DriverExtensions/AppleUserHIDDrivers.dext/AppleUserHIDDrivers com.apple.driverkit.AppleUserHIDEventDriver.dfrv2 0x1000005b9
xxx             62117   0.0  0.0  4277540    740 s000  S+    1:48PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn v2
```

另外通过```netstat -tunl |grep 1080```也能看到1080端口已经在listen了
```
xxx@xxx-mbp:~#netstat -an |grep 1080
tcp4       0      0  127.0.0.1.1080         *.*                    LISTEN
```

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```
和config.json配置无关
```
4)  请附上出错时软件输出的错误日志。

```
前面已经提供了
```

**临时解决办法：**
手工启动v2rayU，然后显示状态是off的，先运行为on，再运行为off，退出v2ray，即可看到1080端口被释放，同时ps aux |grep v2里面也没有运行的服务了。

**Comment by DingYou** [comment]
删除plist也不能阻止开机启动...

**Comment by followztx** [comment]
流氓软件，总是开机自启，卸载掉吧。

**Comment by alfredtofu** [comment]
要停掉mac的开机自启
`launchctl unload /Users/liangzhujin/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist`
