### ISSUE TITLE
V2RayU无法使用

### ISSUE THREAD

**Issue by maozimaozi** [yanue/V2rayU#633]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
是
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
显示address already in use
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
<img width="736" alt="WX20200712-043949@2x" src="https://user-images.githubusercontent.com/68166701/87301768-b990a800-c542-11ea-89e7-5e9a1dd2e3af.png">

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by zhengyongtao** [comment]
你本地的1087已经有进程占用了，偏好配置-Advance里改一下本机http监听端口就好了
