### ISSUE TITLE
pac监听端口怎么设置成127.0.0.1本地模式

### ISSUE THREAD

**Issue by geodidi** [yanue/V2rayU#635]
pac监听的端口怎么设置成127.0.0.1本地模式？目前默认别人也能访问到我的config.json。

**Comment by gqbre** [comment]
自己把 config.json 改一下

**Comment by holymonson** [comment]
![image](https://user-images.githubusercontent.com/902012/88882566-d62c2000-d264-11ea-808f-0f95784e6356.png)
