### ISSUE TITLE
大神，求解决办法  突然别的正常节点不能用了，

### ISSUE THREAD

**Issue by s395580** [yanue/V2rayU#636]
nds > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/07/19 11:13:00 [Info] [3423613463] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:107.167.20.181:443
2020/07/19 11:13:00 [Warning] [3423613463] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/19 11:13:00 [Info] [3423613463] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64)
A unified platform for anti-censorship.
2020/07/19 11:13:15 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
2020/07/19 11:13:15 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/07/19 11:13:15 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2020/07/19 11:13:15 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2020/07/19 11:13:15 [Warning] v2ray.com/core: V2Ray 4.23.1 started
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64)
A unified platform for anti-censorship.
2020/07/19 11:13:15 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
2020/07/19 11:13:15 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/07/19 11:13:15 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2020/07/19 11:13:15 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2020/07/19 11:13:15 [Warning] v2ray.com/core: V2Ray 4.23.1 started

![image](https://user-images.githubusercontent.com/64362264/87866213-66d74600-c9b1-11ea-9760-c8d4b6618434.png)
![image](https://user-images.githubusercontent.com/64362264/87866219-7c4c7000-c9b1-11ea-87bf-c6a21629124e.png)

**Comment by nthack** [comment]
ok了吗？我也遇到这个问题
