### ISSUE TITLE
MacOS v10.15.6 中开启时提示 config.json 找不到

### ISSUE THREAD

**Issue by chaopao** [yanue/V2rayU#638]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU: v2.2.0
Mac: v10.15.6
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
点击「Turn v2Ray-core on」，报错如下：
![image](https://user-images.githubusercontent.com/66006152/87920675-1b559280-caac-11ea-98ef-44017817e6ac.png)

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
是拖到到/Applications/下的吧?

**Comment by chaopao** [comment]
> 是拖到到/Applications/下的吧?

是的，突然丢失了，手动加了一个服务器后就可以了，但是更新订阅不成功

**Comment by yanue** [comment]
一个可以服务都没了吗

**Comment by ydyleo** [comment]
对的我的OS系统也出现了这个问题，本来前几天还是可以的

**Comment by ydyleo** [comment]
> 一个可以服务都没了吗

想问下作者解决了吗

**Comment by ydyleo** [comment]
> 一个可以服务都没了吗

在下午的时候又自动恢复了

**Comment by ydyleo** [comment]
> > 是拖到到/ Applications /下的吧？
> 
> 是的，突然丢失了，手动加了一个服务器后就可以了，但是更新订阅不成功
> 从以下地址进行加载：[https](https://ghelper.me/rss/xxx) : //ghelper.me/rss/xxx[](https://ghelper.me/rss/xxx)
> 
> 网址中的del old：[https](https://ghelper.me/rss/xxx)：[//ghelper.me/rss/xxx](https://ghelper.me/rss/xxx)
> 
> 失败：未找到ss：//，ssr：//，vmess：//
> 网址：<title> 403：禁止</ title> 403：禁止

作者可以重启看看，我MAC重启之后就好了

**Comment by chaopao** [comment]
> > > 是拖到到/ Applications /下的吧？
> > 
> > 
> > 是的，突然丢失了，手动加了一个服务器后就可以了，但是更新订阅不成功
> > 从以下地址进行加载：[https](https://ghelper.me/rss/xxx) : //ghelper.me/rss/xxx
> > 网址中的del old：[https](https://ghelper.me/rss/xxx)：[//ghelper.me/rss/xxx](https://ghelper.me/rss/xxx)
> > 失败：未找到ss：//，ssr：//，vmess：//
> > 网址：<title> 403：禁止</ title> 403：禁止
> 
> 作者可以重启看看，我MAC重启之后就好了

我这边重启后并没有恢复，不过今天试了一下可以用了，订阅可以正常更新啦，也许时订阅源的问题。。。
问题可以关闭了，感谢关注！
