### ISSUE TITLE
资源占用过高

### ISSUE THREAD

**Issue by LucienShui** [yanue/V2rayU#639]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

| Software | Version |
| --- | --- |
| macOS | `10.15.6` |
| V2RayU | `2.2.0` |

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

发现电脑风扇在狂转，看了一下活动监视器是 `V2rayU` 这个进程的资源占用很多，如图。

<img width="671" alt="截屏2020-07-23 上午10 13 43" src="https://user-images.githubusercontent.com/30151093/88247270-b9757280-cccf-11ea-83cc-636448ea9fa1.png">

<img width="948" alt="截屏2020-07-23 上午10 14 00" src="https://user-images.githubusercontent.com/30151093/88251343-23484900-ccdd-11ea-9748-c8d92f95f3b9.png">

<img width="949" alt="截屏2020-07-23 上午10 14 16" src="https://user-images.githubusercontent.com/30151093/88251346-26433980-ccdd-11ea-95db-0ff1d48738d4.png">

<img width="256" alt="截屏2020-07-23 上午10 14 33" src="https://user-images.githubusercontent.com/30151093/88251351-293e2a00-ccdd-11ea-9009-5a0d5cf92710.png">

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```json
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/v2",
          "headers": {
            "host": "xxx.xxx.xxx"
          }
        },
        "tlsSettings": {
          "serverName": "xxx.xxx.xxx",
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxx.xxx",
            "users": [
              {
                "id": "f153aea5-e2bc-3512-8569-b4168f3975da",
                "alterId": 2,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。

如果有需要的话可以将 `log` 文件邮件过去。

**Comment by abowloflrf** [comment]
+1 for this issue

100% CPU load and the Preferences UI was froozen

**Comment by Whotakesmyname** [comment]
Also have this issue. Noticed that a similar issue has been mentioned before and a fix was updated, but it seems not resolved yet.

**Comment by LynanBreeze** [comment]
+1
