### ISSUE TITLE
还是core的问题，显示如图，没找到更新core的地方

### ISSUE THREAD

**Issue by FattyboyN** [yanue/V2rayU#64]
![Snip20190522_1](https://user-images.githubusercontent.com/41871127/58147856-f63e7780-7c8e-11e9-8df9-f70f5c5b6cf7.png)

**Comment by yanue** [comment]
额  你那边是无法下载?  功能能用吗  后续加上收到更新core功能吧,你可以去https://github.com/v2ray/v2ray-core/releases 下载最新版进行替换,目录:
`
/Applications/V2rayU.app/Contents/Resources/v2ray-core
`

**Comment by FattyboyN** [comment]
功能一直都是好的，从1.2开始都是好的，就是一直显示core-1，所以才发issue的

**Comment by yanue** [comment]
这个有可能是bug,因为我在发版时候,会默认将v2ray-core更新到最新版

**Comment by yanue** [comment]
你可以看下日志,应该是这样的:
`
V2Ray 4.19 (Let's Fly) Custom
A unified platform for anti-censorship.
`
另外 你可以用命令行看下:
`
/Applications/V2rayU.app/Contents/Resources/v2ray-core/v2ray -version
`

**Comment by FattyboyN** [comment]
A unified platform for anti-censorship.
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
V2Ray 4.18.0 (Po) 20190228

**Comment by FattyboyN** [comment]
命令行看
V2Ray 4.19 (Let's Fly) Custom
A unified platform for anti-censorship.

**Comment by FattyboyN** [comment]
刷新一下 日志
V2Ray 4.19 (Let's Fly) Custom
A unified platform for anti-censorship.
127.0.0.1 - - [22/May/2019 13:12:08] "GET /pac/pac.js HTTP/1.1" 200 -
2019/05/22 13:12:12 tcp:127.0.0.1:52723 accepted tcp:www.google.com:443

**Comment by yanue** [comment]
那就是显示上的bug了
