### ISSUE TITLE
V2RayU 安全性问题

### ISSUE THREAD

**Issue by singularity0993** [yanue/V2rayU#645]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.2.0; macOS 10.15.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**在配置过程中，V2RayU自动将防火墙设置为允许外部连接，这会导致本机的服务可以被外部设备访问，进而引发安全性问题
例如，ip:port/pac/proxy.js 不仅可以在本机访问，也可以由局域网上的其他设备访问。**
建议将防火墙默认设置为拒绝外部连接，这样只有localhost才能访问本机服务。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

（与issue无关）

4)  请附上出错时软件输出的错误日志。

（与issue无关）

请预览一下你填的内容再提交。

**Comment by holymonson** [comment]
`v2ray`默认只监听本地，`V2rayU`全局监听的只有PAC。就是说外部设备顶多只能访问到`pac/proxy.js`这个配置文件，知道你什么规则用代理、什么不用，但具体的代理服务是连不上的。

```
❯ sudo lsof -i -nP | rg -i V2ray | rg LISTEN
V2rayU     1327         monson   70u  IPv6 0xf3097409f6c7fff      0t0    TCP *:11085 (LISTEN)
v2ray     43982         monson    9u  IPv4 0xf309740a603a3c7      0t0    TCP 127.0.0.1:1080 (LISTEN)
v2ray     43982         monson   10u  IPv4 0xf309740aa26c05f      0t0    TCP 127.0.0.1:1087 (LISTEN)
```
![image](https://user-images.githubusercontent.com/902012/88881908-3c17a800-d263-11ea-94cc-089eefb34fba.png)

**Comment by singularity0993** [comment]
那还好，不过防火墙确实没必要允许外部连接吧？

**Comment by holymonson** [comment]
V2rayU控制不了防火墙，这取决于用户自己的设置，很多人甚至不开防火墙。在第一次启动V2rayU触发全局监听时，防火墙应该会问你 允许 还是 阻止，这个也可以自己改过来。

![image](https://user-images.githubusercontent.com/902012/88882566-d62c2000-d264-11ea-808f-0f95784e6356.png)

**Comment by singularity0993** [comment]
那这样的话，现在唯一需要修改的就是取消PAC的全局监听，然后就可以了

**Comment by yanue** [comment]
#740
