### ISSUE TITLE
大神们救救我！v2ray在mac 上无法启动 ‘failed to load config'.    BUG

### ISSUE THREAD

**Issue by sv-tech** [yanue/V2rayU#649]
日志如下：failed to load config: /Applications/V2rayU.app/Contents/Resources/config.json > v2ray.com/core/main/confloader/external: config file not readable > open /Applications/V2rayU.app/Contents/Resources/config.json: no such file or directory
重新卸载安装还是不行，用SSR 可以但是好多网站进不去，如 google scholar.
已经试了十几个小时了。

**Comment by csloter** [comment]
点击服务器设置，进去随便保存一份，就有啦

**Comment by yanue** [comment]
配置服务了吗

**Comment by shenlanchenwei** [comment]
1.打开目录
   `open ~/Library/Preferences/`
2.删除V2rayN的配置文件
