### ISSUE TITLE
从Mac os11 beta3升级到beta4后无法上网

### ISSUE THREAD

**Issue by kanhangliew** [yanue/V2rayU#654]
1. 我的版本信息
    V2RayU 2.2.0， Mac 11.0 beta4
2. 我遇到的问题
     一直以来都用这个软件，升级到mac 11 beta3还能用，昨晚升级到beta4之后，今天打开软件链接服务器，用全局模式就无法上网（任何网页都是空白）。
3. 我的配置信息
{
```
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/v2ray",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xx.xxx.xx.xxx",
            "users": [
              {
                "id": "7f99667a-7dfe-3ae0-8e0a-f0fd6279ffcd",
                "alterId": 2,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 80
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4. 错误日志
```
2020/08/06 20:13:28 [Info] [675305791] v2ray.com/core/transport/internet/websocket: creating connection to tcp:v2.bingclub.top:80
2020/08/06 20:13:28 [Info] [1954772174] v2ray.com/core/app/dispatcher: default route for tcp:secure.img1-fg.wfcdn.com:443
2020/08/06 20:13:28 [Info] [1954772174] v2ray.com/core/transport/internet/websocket: creating connection to tcp:v2.bingclub.top:80
2020/08/06 20:13:28 127.0.0.1:50290 accepted //prx.wayfair.com:443 [proxy] 
2020/08/06 20:13:28 127.0.0.1:50289 accepted //secure.img1-fg.wfcdn.com:443 [proxy] 
2020/08/06 20:13:28 [Info] [675305791] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:prx.wayfair.com:443 via tcp:v2.bingclub.top:80
2020/08/06 20:13:29 [Info] [56138981] v2ray.com/core/proxy/http: request to Method [GET] Host [ocsp.apple.com] with URL [http://ocsp.apple.com/ocsp03-appleistca2g129/MFYwVKADAgEAME0wSzBJMAkGBSsOAwIaBQAEFCaEh7OMUBUpl9vU0X43%2Fz8u8xVoBBTYepREfJBwkBae3RecAUQDhtYqKQIQEOE6ClCkwLKEsmIc%2BmEDYA%3D%3D]
2020/08/06 20:13:29 [Info] [56138981] v2ray.com/core/app/dispatcher: default route for tcp:ocsp.apple.com:80
2020/08/06 20:13:29 [Info] [56138981] v2ray.com/core/transport/internet/websocket: creating connection to tcp:v2.bingclub.top:80
2020/08/06 20:13:29 127.0.0.1:50293 accepted http://ocsp.apple.com/ocsp03-appleistca2g129/MFYwVKADAgEAME0wSzBJMAkGBSsOAwIaBQAEFCaEh7OMUBUpl9vU0X43%2Fz8u8xVoBBTYepREfJBwkBae3RecAUQDhtYqKQIQEOE6ClCkwLKEsmIc%2BmEDYA%3D%3D [proxy] 
```

**Comment by whueric** [comment]
我也遇到类似问题，升级macos big sur beta4之后，代理服务就不可用了，http/socks代理均不行。

**Comment by lotosbin** [comment]
#658 不是beta4的问题，

**Comment by whueric** [comment]
> #658 不是beta4的问题，手动更新下 v2ray-core就可以了

是的，手动下载v2ray-core覆盖掉v2rayU的内容就可以了。

**Comment by smart-z** [comment]
> #658 不是beta4的问题，手动更新下 v2ray-core就可以了

万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。

**Comment by whueric** [comment]
> > #658 不是beta4的问题，手动更新下 v2ray-core就可以了
> 
> 万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。

下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
unzip v2ray-macos-64.zip
mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/

**Comment by smart-z** [comment]
> > > #658 不是beta4的问题，手动更新下 v2ray-core就可以了
> > 
> > 
> > 万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。
> 
> 下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> unzip v2ray-macos-64.zip
> mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/

我发现我咋下的V2rayU的版本里面没有 core 的文件夹，再次感谢。

**Comment by kanhangliew** [comment]
> > > > #658 不是beta4的问题，手动更新下 v2ray-core就可以了
> > > 
> > > 
> > > 万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。
> > 
> > 
> > 下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> > unzip v2ray-macos-64.zip
> > mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/
> 
> 前面下了core，就是打开，发现我咋下的V2rayU的版本里面没有 core 的文件夹，已经移过去了，感谢您无微不至的帮助。🙏🙏🙏

我还是没看懂，下载完解压后，是把文件夹里的 v2ray 单个文件移到 v2rayU里面的v2ray-core文件夹吗

**Comment by smart-z** [comment]
> > > > > #658 不是beta4的问题，手动更新下 v2ray-core就可以了
> > > > 
> > > > 
> > > > 万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。
> > > 
> > > 
> > > 下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> > > unzip v2ray-macos-64.zip
> > > mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/
> > 
> > 
> > 前面下了core，就是打开，发现我咋下的V2rayU的版本里面没有 core 的文件夹，已经移过去了，感谢您无微不至的帮助。🙏🙏🙏
> 
> 我还是没看懂，下载完解压后，是把文件夹里的 v2ray 单个文件移到 v2rayU里面的v2ray-core文件夹吗

这样吧，你把上面大神那行代码 就 mv 那行在终端运行一下。

**Comment by kanhangliew** [comment]
> > > > #658 不是beta4的问题，手动更新下 v2ray-core就可以了
> > > 
> > > 
> > > 万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。
> > 
> > 
> > 下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> > unzip v2ray-macos-64.zip
> > mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/
> 
> 前面下了core，就是打开，发现我咋下的V2rayU的版本里面没有 core 的文件夹，已经移过去了，感谢您无微不至的帮助。🙏🙏🙏

是把下载来的压缩包解压，里面的core文件夹

> > > > > > #658 不是beta4的问题，手动更新下 v2ray-core就可以了
> > > > > 
> > > > > 
> > > > > 万分抱歉的当一下伸手党。请问v2ray-core的路径在哪里。我在v2rayu.app里面差了，没有找到core相关的内容，还请您指点一下。
> > > > 
> > > > 
> > > > 下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> > > > unzip v2ray-macos-64.zip
> > > > mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/
> > > 
> > > 
> > > 前面下了core，就是打开，发现我咋下的V2rayU的版本里面没有 core 的文件夹，已经移过去了，感谢您无微不至的帮助。🙏🙏🙏
> > 
> > 
> > 我还是没看懂，下载完解压后，是把文件夹里的 v2ray 单个文件移到 v2rayU里面的v2ray-core文件夹吗
> 
> 这样吧，你把上面大神那行代码 就 mv 那行在终端运行一下。

我知道了 是把整个文件夹拉进去并改名成v2ray-core
