### ISSUE TITLE
2.2.0版本用不了出现 failed to load system root certificate 错误 并且希望新版本加上可以自定义dns 的功能就像1.几版本那样。

### ISSUE THREAD

**Issue by GitH123i** [yanue/V2rayU#655]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
使用的版本 2.2.0，mac版本15.5

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
用不了，或者说经常用不了，突然用不了，只要随便用回1.几的版本就可以用了。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```2020/08/06 22:30:11 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:12 [Info] [3499451877] v2ray.com/core/transport/internet/websocket: creating connection to tcp:1.0.0.1:443
2020/08/06 22:30:12 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:14 [Info] [3499451877] v2ray.com/core/transport/internet/websocket: creating connection to tcp:1.0.0.1:443
2020/08/06 22:30:14 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:16 [Info] [3499451877] v2ray.com/core/transport/internet/websocket: creating connection to tcp:1.0.0.1:443
2020/08/06 22:30:16 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:19 [Warning] [3499451877] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://x.x.x.x/wb2ray): > x509: failed to load system roots and no roots provided; signal: killed] > v2ray.com/core/common/retry: all retry attempts failed

请预览一下你填的内容再提交。

**Comment by DanielYWoo** [comment]
OSX 10.15.6, V2rayU 2.20, exactly the same issue, nothing in log, no port listening.
Start it from command line with "/Applications/V2rayU.app/Contents/MacOS/V2rayU", it shows:
```
2020-08-07 00:18:06.053 V2rayU[4493:60094] Start v2ray-core succeeded.
2020-08-07 00:18:06.053 V2rayU[4493:60094] start v2ray-core done.
webServer.start at:11085
chmod: ./v2ray-core: No such file or directory
/Users/daniel/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 00:18:06.083 V2rayU[4493:60094] Start v2ray-core succeeded.
after SCPreferencesCommitChanges: commitRet = true, applyRet = true
```

**Comment by zhang-wenchao** [comment]
I have the same problem with 2.2.0 and macOS 10.15.5

**Comment by zhang-wenchao** [comment]
nothing in log, no port listening.

**Comment by jingshaoqi** [comment]
我也出现2.2.0 版本不能用的问题
我之前用的版本是2.1.0，升级到2.2.0以后就不能用了，我退回到2.1.0两次，2.1.0版本正常工作，但是2.2.0始终不能用，浏览器提示以下问题：
	
chrome浏览器提示如下：
 	No internetThere is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
Checking the proxy address
ERR_PROXY_CONNECTION_FAILED


fireforx浏览器提示如下

The proxy server is refusing connections

Firefox is configured to use a proxy server that is refusing connections.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to make sure the proxy server is working.

**Comment by GitH123i** [comment]
@yanue @LeeCenY

**Comment by DanielYWoo** [comment]
问题已经找到原因: 升级2.2.0之后v2rayU删除了我的v2ray-core目录. 我手动copy dmg内的v2ray-core目录过来才行

**Comment by GitH123i** [comment]
@DanielYWoo 可能不成立啊，老哥，因为奇怪的这里反应的大部分人都是大概在晚上11点左右不行的，太统一了吧，而且不是升级后不行的，是直接就用的是2.2.0版本的。不是通过低版本升级上去的

**Comment by LeeCenY** [comment]
应该是你们服务器的v2ray-core 版本更新了造成问题，请查看说明： https://github.com/v2fly/v2ray-core/releases/tag/v4.27.0

作者已经给给出了方案：https://github.com/yanue/V2rayU/issues/658#issuecomment-670285981

**Comment by DanielYWoo** [comment]
@GitH123i 我是一直用着2.2.0不是升级v2aryU造成的,我只是纯猜测v2rayU升级v2ray-core导致. 我也是昨晚11点左右突然不行了, 命令行启动报错找不到v2ray-core. 重新下载个2.2.0的dmg解压复制好了. 这是过程和现象, 具体原因不明, 也不见得能重现.

**Comment by DanielYWoo** [comment]
我觉得有两个可以改善的地方
1) 升级v2ray-core在下载完成md5验证完成之后, 把老的core rename为v2ary-core-backup, 不要删除老的core.
2) 如果启动找不到core, 界面里不要告诉用户启动成功, 要报错找不到core, 这样大家就很容易定位问题了. 现在core都找不到了,界面还是告诉用户启动成功, 然后日志也没了, 你得命令行启动v2rayU才能看到找不到core的报错.

**Comment by GitH123i** [comment]
@LeeCenY 哦有个疑问 那为什么回退到2.1版本或者更低的版本就可以了哦

**Comment by likebeta** [comment]
> 我觉得有两个可以改善的地方
> 
> 1. 升级v2ray-core在下载完成md5验证完成之后, 把老的core rename为v2ary-core-backup, 不要删除老的core.
> 2. 如果启动找不到core, 界面里不要告诉用户启动成功, 要报错找不到core, 这样大家就很容易定位问题了. 现在core都找不到了,界面还是告诉用户启动成功, 然后日志也没了, 你得命令行启动v2rayU才能看到找不到core的报错.

我也是用了2.2很久，今天突然不行了

**Comment by DanielYWoo** [comment]
@GitH123i  他说的回退到2.1其实是重新安装了一遍V2RayU, 里面带着一份core, 所以可以工作. 其实不用回退, 重新安装一次也可以的, 只要能补上突然缺失的core.

**Comment by GitH123i** [comment]
@DanielYWoo 嗯老哥目前已经覆盖可以啦 只是还有个问题，通过重装或者覆盖安装解决的会不会过一天或者后面又会在出现这个问题吗，算是彻底解决了没有

**Comment by GitH123i** [comment]
@yanue 咳咳 ，，这次应该是全部使用老哥您这个软件的全部人都有问题。不管是低半年还是高版本的只能通过重装解决了。。

**Comment by DanielYWoo** [comment]
@GitH123i  这就要问yanue哥了, 我反正是留着一份core, 随时准备copy进去, 哈哈

**Comment by yanue** [comment]
#663
