### ISSUE TITLE
 failed to load system root certificate

### ISSUE THREAD

**Issue by lbylbtlbylbt** [yanue/V2rayU#656]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.2.0
MacOS 10.15.6 (19G73)

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
访问超时，突然无法连接外网。Win（做的双系统）、ios都可以正常连接，Chrome提示 ERR_PROXY_CONNECTION_FAILED

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true,
        "auth": "noauth"
      },
      "port": "1085"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1088"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/wb2ray",
          "headers": {
            "host": "XXX.com"
          }
        },
        "tlsSettings": {
          "serverName": "XXX.com",
          "allowInsecure": false
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "X.X.X.X",
            "users": [
              {
                "id": "XXX",
                "alterId": 64,
                "level": 1,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": null
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "proxy",
          "domain": [
            "washingtonpost.com",
            "theguardian.com",
            "independent.co.uk",
            "rarbg.to",
            "dyncdn.me",
            "dailymail.co.uk",
            "v2fly.org",
            "time.com",
            "ign.com",
            "apple.news",
            "live.com"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "*.spotify.com",
            "*.scdn.co"
          ]
        }
      ]
    }
  },
  "transport": {}
}
4)  请附上出错时软件输出的错误日志。

2020/08/06 22:30:11 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:12 [Info] [3499451877] v2ray.com/core/transport/internet/websocket: creating connection to tcp:1.0.0.1:443
2020/08/06 22:30:12 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:14 [Info] [3499451877] v2ray.com/core/transport/internet/websocket: creating connection to tcp:1.0.0.1:443
2020/08/06 22:30:14 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:16 [Info] [3499451877] v2ray.com/core/transport/internet/websocket: creating connection to tcp:1.0.0.1:443
2020/08/06 22:30:16 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > signal: killed
2020/08/06 22:30:19 [Warning] [3499451877] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://x.x.x.x/wb2ray):  > x509: failed to load system roots and no roots provided; signal: killed] > v2ray.com/core/common/retry: all retry attempts failed

请预览一下你填的内容再提交。

**Comment by ncepuwanghui** [comment]
我也遇到了这个问题，晚上突然就无法链接外网，查看v2ray日志，显示 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate

**Comment by axetroy** [comment]
同样的问题，也就刚刚发生

**Comment by AugJujube** [comment]
一模一样的问题

**Comment by withlqs** [comment]
同样的问题，刚刚出现不足一小时。

**Comment by zhang-wenchao** [comment]
同样问题，折腾了半晚上，我还以为自己的问题。

**Comment by zhang-wenchao** [comment]
lsof -i:1080
lsof -i:1087

都没有监听，什么鬼啊。

**Comment by zhang-wenchao** [comment]
日志也空了，什么日志都没有。

**Comment by Roachard** [comment]
同样的问题，今晚突然发生的，求尽快解决，谢谢

**Comment by fuchenxu2008** [comment]
刚刚发生，电脑网络设置都恢复了。。。怀疑人生

**Comment by zhongxuanS** [comment]
同样的问题

**Comment by jiaozhipei** [comment]
我也出现了这个问题。。。。。

**Comment by 0v0** [comment]
+1

**Comment by brycezhang** [comment]
+1，用回2.1版本，暂时解决问题

**Comment by LeeCenY** [comment]
应该是你们服务器的v2ray-core 版本更新了造成问题，请查看说明： https://github.com/v2fly/v2ray-core/releases/tag/v4.27.0

作者已经给给出了方案：https://github.com/yanue/V2rayU/issues/658#issuecomment-670285981

**Comment by lbylbtlbylbt** [comment]
> 应该是你们服务器的v2ray-core 版本更新了造成问题，请查看说明： https://github.com/v2fly/v2ray-core/releases/tag/v4.27.0
> 
> 作者已经给给出了方案：[#658 (comment)](https://github.com/yanue/V2rayU/issues/658#issuecomment-670285981)

完美解决 感谢！

**Comment by sinomoe** [comment]
> 应该是你们服务器的v2ray-core 版本更新了造成问题，请查看说明： https://github.com/v2fly/v2ray-core/releases/tag/v4.27.0
> 
> 作者已经给给出了方案：[#658 (comment)](https://github.com/yanue/V2rayU/issues/658#issuecomment-670285981)

感谢🙏

**Comment by wentfar** [comment]
我也遇到一样的问题。。。。

**Comment by jiaozhipei** [comment]
完美解决,thx
