### ISSUE TITLE
update to 2.2.0 version can't work

### ISSUE THREAD

**Issue by jingshaoqi** [yanue/V2rayU#657]
use 2.2.0 version can't work
 	I used well 2.1.0 version,but when I update to 2.2.0 version,can't work.

 	chrome browser hints:

 	No internetThere is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
Checking the proxy address
ERR_PROXY_CONNECTION_FAILED

fireforx browser hits

The proxy server is refusing connections

Firefox is configured to use a proxy server that is refusing connections.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to make sure the proxy server is working.

 I rollback to 2.1.0 twice ,2.1.0 version work well. but b2.2.0 version always dose not work.

**Comment by naplesblue** [comment]
same here. 2.2.0 suddenly shutdown itself, even log stops at the same time. it won't listen to the local port, that's why the browser always reports the proxy server is refusing connections.

**Comment by yanue** [comment]
#663
