### ISSUE TITLE
同一个配置，同一个局域网下，手机客户端能翻墙，但是Mac不能翻墙

### ISSUE THREAD

**Issue by pencilso** [yanue/V2rayU#658]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU:2.2.0   Mac:10.15.6
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
很奇怪，之前都正常使用，但是今天突然就翻不了墙了，于是我把v2rayU卸载了重装，但是重装后也不行，而且查看日志，日志文件竟然是空的！于是我又试了一下手机，但是手机是可以正常翻墙的，手机和mac是在同一个局域网下。
再然后，我查看了系统偏好设置->网络->高级->代理-> 自动代理配置：http://127.0.0.1:11085/pac/proxy.js  这些东西看起来都正常
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    {
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/v2ray",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xxxxx.cn",
            "users": [
              {
                "id": "4b62fe60-6ea6-440a-df53-5d162dff634e",
                "alterId": 64,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 6701
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}
```
4)  请附上出错时软件输出的错误日志。

```javascript
    因为我把v2rayU重装了一下，错误日志文件现在是空的，我也很奇怪它日志为什么会是空的...
    按理说执行日志啥的总会有点。。。。
```

请预览一下你填的内容再提交。

**Comment by Fendy5** [comment]
同样的情况，从昨晚11点开始Mac就不可访问了，但是手机端可以

**Comment by jjyy1008** [comment]
同样的情况，同样的时间点，晚上差不多11点开始，mac端翻不出去了，但手机端可以

**Comment by lc6chang** [comment]
Same issue.

**Comment by wuzhunshao** [comment]
同样的情况，降级2.1.0恢复正常

**Comment by lc6chang** [comment]
相同的ss节点，shadowsocks可以，v2rayU不可以。

**Comment by cnbailian** [comment]
> 同样的情况，降级2.1.0恢复正常

同样的问题，感谢

**Comment by Wizard23333** [comment]
我也是,以为机场又跑路了

**Comment by IWantADog** [comment]
没有日志输出就很奇怪

**Comment by Wizard23333** [comment]
显示22:00左右就没有日志输出了

**Comment by yanue** [comment]
应该是v2ray-core自动更新了

**Comment by jhonor777** [comment]
我的也是，昨天下午还正常，晚上回家就断了，手机可正常访问，如何解决呢，我已经卸了，重新安装还不行

**Comment by Wizard23333** [comment]
> 我的也是，昨天下午还正常，晚上回家就断了，手机可正常访问，如何解决呢，我已经卸了，重新安装还不行

退回1.几版本可以使用

**Comment by jingqingyun** [comment]
我也碰到一样的问题了，幸好我的电脑上v2rayX还没卸载

**Comment by imaxwen** [comment]
+1+1+1

**Comment by xueshukai** [comment]
一样一样   日志一行都不输出，还纳闷儿呢

**Comment by lc6chang** [comment]
@yanue 确实是v2ray-core更新失败了

```bash
$ /Applications/V2rayU.app/Contents/MacOS/V2rayU
...

2020-08-07 10:07:22.852 V2rayU[] start download
2020-08-07 10:07:23.802 V2rayU[] 已下载：0KB
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./v2ray-macos.zip or
        ./v2ray-macos.zip.zip, and cannot find ./v2ray-macos.zip.ZIP, period.
chmod: ./v2ray-core: No such file or directory

...
```

**Comment by heiwang1997** [comment]
貌似是因为14小时前v2ray Core发布了最新版本4.27，对应MacOS包的名称从v2ray-macos.zip变成了v2ray-macos-64.zip，导致无法找到下载地址，希望能紧急更新一下。这里贴一下log：

```
2020-08-07 10:10:43.798 V2rayU[1964:17601] Permission is root admin
2020-08-07 10:10:43.798 V2rayU[1964:17601] Permission is ok
after SCPreferencesCommitChanges: commitRet = true, applyRet = true
2020-08-07 10:10:43.887 V2rayU[1964:17601] setSystemProxy backup succeeded.
2020-08-07 10:10:43.887 V2rayU[1964:17601] start menu
isOldConfigVersion true
2020-08-07 10:10:43.892 V2rayU[1964:17601] start v2ray-core begin
/Users/huangjh/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 10:10:43.901 V2rayU[1964:17601] Stop v2ray-core succeeded.
2020-08-07 10:10:43.912 V2rayU[1964:17601] checkPort: res=(Optional("ok")) cmd=(cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd port -h 127.0.0.1 -p 1080)
2020-08-07 10:10:43.921 V2rayU[1964:17601] checkPort: res=(Optional("ok")) cmd=(cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd port -h 127.0.0.1 -p 1087)
2020-08-07 10:10:43.929 V2rayU[1964:17601] checkPort: res=(Optional("ok")) cmd=(cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd port -h 0.0.0.0 -p 11085)
webServer.start at:11085
chmod: ./v2ray-core: No such file or directory
/Users/huangjh/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 10:10:43.992 V2rayU[1964:17601] Start v2ray-core succeeded.
2020-08-07 10:10:43.992 V2rayU[1964:17601] start v2ray-core done.
webServer.start at:11085
chmod: ./v2ray-core: No such file or directory
/Users/huangjh/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 10:10:44.070 V2rayU[1964:17601] Start v2ray-core succeeded.
after SCPreferencesCommitChanges: commitRet = true, applyRet = true
2020-08-07 10:10:44.134 V2rayU[1964:17601] setSystemProxy manual succeeded.
sync from Subscribe list
loadConfig nil
SubSync fail:  please add Subscription Url
ping start
chmod: Unable to change file mode on ./V2rayUHelper: Operation not permitted
chmod: Unable to change file mode on ./V2rayUTool: Operation not permitted
GeneratePACFile rewrite 1080
PACFilePath /Applications/V2rayU.app/Contents/Resources/pac/proxy.js
webServer.start at:11085
2020-08-07 10:10:44.221 V2rayU[1964:17601] working dir:/Applications/V2rayU.app
ping error ss.yuismy.vip Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
2020-08-07 10:10:45.663 V2rayU[1964:17601] start download
2020-08-07 10:10:46.940 V2rayU[1964:17741] 已下载：0KB
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./v2ray-macos.zip or
        ./v2ray-macos.zip.zip, and cannot find ./v2ray-macos.zip.ZIP, period.
chmod: ./v2ray-core: No such file or directory
```

**Comment by mingtongzaohua** [comment]
同问题+1
PS：我是之前通过brew下载的1.1.1版本，2020年08月07日早上发现不可使用，至少昨天下午还是正常，

A：按照高赞答主的方法将版本调整至2.1.0可以解决此问题

**Comment by mingtongzaohua** [comment]
> 同样的情况，降级2.1.0恢复正常

亲测此法可行

**Comment by null-id** [comment]
怎么降级？

**Comment by tgy100** [comment]
卸载了, 装2.1.0可以使用

**Comment by btw1q84** [comment]
> 怎么降级？

删除2.2重装2.1

**Comment by tranzwalle** [comment]
> 怎么降级？

从 https://github.com/yanue/V2rayU/releases 下载之前的版本啊

**Comment by yanue** [comment]
可以手动下载v2ray-core替换试下
```/Applications/V2rayU.app/Contents/Resources/v2ray-core/```

**Comment by lander1003** [comment]
我也是这个情况，感觉莫名其妙

**Comment by lc6chang** [comment]
> 可以手动下载v2ray-core替换试下
> `/Applications/V2rayU.app/Contents/Resources/v2ray-core/`

works for me! 👍

**Comment by null-id** [comment]
@yanue Works! Thank you!
```
cd ~/Download
unzip v2ray-macos-64.zip
mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/
```

**Comment by lander1003** [comment]
> @yanue Works! Thank you!
> 
> This is the detailed solution:
> 
> First, download v2ray-core from [here](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0).
> 
> Then,
> 
> ```
> cd ~/Downloads
> unzip v2ray-macos-64.zip
> mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/
> ```

it works for me
thank you

**Comment by cjr0707** [comment]
我擦今早突然挂了 还以为我机场问题呢 原来大家都出现了

**Comment by GitH123i** [comment]
@yanue 谢谢，希望老哥可以更新版本一下，我们进行更新版本就好了，

**Comment by implementt** [comment]
从github重新下载安装包，覆盖安装也能解决这个问题。 

Re-download the installation package from github, overwriting installation can also solve this problem.

**Comment by GitH123i** [comment]
老哥 说的原因是,v2ray-core更改了包下载地址规则,原匹配规则:  所以有个疑问 从github重新下载安装包，覆盖安装也能解决这个问题。或者回退到2.1版本或者更低的版本就可以了哦  这个是啥原因哦

**Comment by TENX-S** [comment]
``

> 可以手动下载v2ray-core替换试下:
> `/Applications/V2rayU.app/Contents/Resources/v2ray-core/`
> 
> 下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> 
> 原因,v2ray-core更改了包下载地址规则,原匹配规则:
> ` var releaseUrl: String = "https://github.com/v2ray/v2ray-core/releases/download/${version}/v2ray-macos.zip"`

版本：V2RayU 2.2.0 
没有`/Applications/V2rayU.app/Contents/Resources/v2ray-core` 这个目录。
目录结构如下图所示
<img width="611" alt="Screen Shot 2020-08-07 at 12 05 30 PM" src="https://user-images.githubusercontent.com/40336192/89607941-50345880-d8a6-11ea-9555-e2532642be51.png">

**Comment by GitH123i** [comment]
@TENX-S 老哥看你这个意思是说   v2ray-core更改了包下载地址规则  然后我们本地的V2rayU 软件居然自动消失了v2ray-core 这个目录，电脑下载安装的本地软件都会被控制自动删除了啊。。。

**Comment by Turmiht** [comment]
same problem since 1:40 a.m. today, check the .plist file and found this error:
![image](https://user-images.githubusercontent.com/61539014/89608941-0ac55a80-d8a9-11ea-86a8-e5a1b8f2412f.png)
hope it helpful!

**Comment by TENX-S** [comment]
卸载2.2.0后，安装2.1.0和2.0.0，问题均复现

**Comment by RussellCao824** [comment]
直接下载最新版本2.20，再重新安装一遍，什么都不用改，直接就好了。

**Comment by GitH123i** [comment]
@yanue 问下 老哥 覆盖安装解决后  过一天或者后面还会在出现这个问题吗

**Comment by shuhankuang** [comment]
> @TENX-S 老哥看你这个意思是说 v2ray-core更改了包下载地址规则 然后我们本地的V2rayU 软件居然自动消失了v2ray-core 这个目录，电脑下载安装的本地软件都会被控制自动删除了啊。。。

不知道是否这样，反正我机子的目录不见了，v2ray-core 目录消失了，然后我重新下载了个安装包，重装后发现有这个文件夹了。

**Comment by lbsha** [comment]
> > @TENX-S 老哥看你这个意思是说 v2ray-core更改了包下载地址规则 然后我们本地的V2rayU 软件居然自动消失了v2ray-core 这个目录，电脑下载安装的本地软件都会被控制自动删除了啊。。。
> 
> 不知道是否这样，反正我机子的目录不见了，v2ray-core 目录消失了，然后我重新下载了个安装包，重装后发现有这个文件夹了。

我也是这样。。。

**Comment by GitH123i** [comment]
？？远程删除我们的v2ray-core 目录。。。。这有点。。。

**Comment by yucheng82** [comment]
> > > @TENX-S 老哥看你这个意思是说 v2ray-core更改了包下载地址规则 然后我们本地的V2rayU 软件居然自动消失了v2ray-core 这个目录，电脑下载安装的本地软件都会被控制自动删除了啊。。。
> > 
> > 
> > 不知道是否这样，反正我机子的目录不见了，v2ray-core 目录消失了，然后我重新下载了个安装包，重装后发现有这个文件夹了。
> 
> 我也是这样。。。

我的v2ray-core也没有了，这个需要一个合理的解释吧？

**Comment by TENX-S** [comment]
> ？？远程删除我们的v2ray-core 目录。。。。这有点。。。



> > > > @TENX-S 老哥看你这个意思是说 v2ray-core更改了包下载地址规则 然后我们本地的V2rayU 软件居然自动消失了v2ray-core 这个目录，电脑下载安装的本地软件都会被控制自动删除了啊。。。
> > > 
> > > 
> > > 不知道是否这样，反正我机子的目录不见了，v2ray-core 目录消失了，然后我重新下载了个安装包，重装后发现有这个文件夹了。
> > 
> > 
> > 我也是这样。。。
> 
> 我的v2ray-core也没有了，这个需要一个合理的解释吧？

读一下Resource目录下的unzip.sh的内容就知道了；远程控制是不可能的啊喂，这是开源项目呢，说这话不怕让人寒心吗

**Comment by GitH123i** [comment]
确实是不可能的，可以说一下那是为啥v2ray-core 目录都自动消失了吗  这么智能吗

**Comment by TENX-S** [comment]
> 确实是不可能的，可以说一下那是为啥v2ray-core 目录都自动消失了吗 这么智能吗
```shell
#!/bin/sh

#  unzip.sh
#  V2rayU
#
#  Created by yanue on 2018/10/17.
#  Copyright © 2018 yanue. All rights reserved.

rm -rf ./v2ray-core
unzip -o ./v2ray-macos.zip -d ./v2ray-core

if [[ $? == 0 ]]; then
    chmod +x ./v2ray-core/v2ray
    chmod +x ./v2ray-core/v2ctl
    echo "unzip 成功".$?
else
    echo "unzip 失败".$?
fi
rm -f ./v2ray-macos.zip
```

**Comment by yanue** [comment]
没有任何远程超控的东西, 你们觉得我要远程超控你们,还将项目开源吗

> 确实是不可能的，可以说一下那是为啥v2ray-core 目录都自动消失了吗 这么智能吗

不相信可以不用,开源我还给你来个远程删除,脑子呢

**Comment by GitH123i** [comment]
@yanue 是啊问下 老哥 覆盖安装解决后 过一天或者后面还会在出现这个问题吗

**Comment by GitH123i** [comment]
同版本2.2.0覆盖安装后后过一天或者后面又会在出现这个问题吗，算是彻底解决了吗？

**Comment by sinomoe** [comment]
解决了

**Comment by pencilso** [comment]
> [v2ray-core]：
> `/Applications/V2rayU.app/Contents/Resources/v2ray-core/`
> 
> *： https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip
> 
> *，v2ray-core *，*， *： *
> ` var releaseUrl: String = "https://github.com/v2ray/v2ray-core/releases/download/${version}/v2ray-macos.zip"`

问题已解决

**Comment by GitH123i** [comment]
~~，，这次应该是全部使用老哥作者这个软件的全部都有问题了。不管是低半年还是高版本的只能通过重装解决了。。

**Comment by Ethan-ww** [comment]
关于v2ray-core文件夹消失的问题我也遇到了，原因是v2rayU每次启动的时候都会删除这个文件夹然后重新解压core压缩文件。
但是v2ray-macos.zip这次改名成v2ray-macos-64.zip了所以脚本解压缩创建v2ray-core文件夹失败。
解决办法是把v2ray-macos-64.zip改名成v2ray-macos.zip，或者把unzip.sh 里第十行改成这样 unzip -o ./v2ray-macos-64.zip -d ./v2ray-core

**Comment by GitH123i** [comment]
@Ethan-ww    ，v2ray-macos-64.zip在那个文件夹呢，/Applications/V2rayU.app/Contents/Resources/v2ray-core/里面没有看到呢

**Comment by GitH123i** [comment]
@Ethan-ww 老哥 v2rayU每次启动的时候都会删除这个文件夹，那替换的v2ray-core，不会重启电脑关闭软件在打开又被删除了吧？？

**Comment by GitH123i** [comment]
> 关于v2ray-core文件夹消失的问题我也遇到了，原因是v2rayU一旦启动的时候都会删除这个文件夹然后重新解压core压缩文件。
> 但是v2ray-macos.zip此改名成v2ray-macos-64。压缩了所以脚本解压缩创建v2ray核文件夹失败。
> 解决办法是把v2ray-macos-64.zip改名成v2ray-macos.zip，或者把unzip.sh里第十行改成这样解压-o ./ v2ray-macos-64.zip -d ./v2ray-core

没用啊老哥 是不是我哪里错了，我把v2ray-core文件夹删除了，然后把unzip.sh 里第十行改成这样 unzip -o ./v2ray-macos-64.zip -d ./v2ray-core  没用任何变化呀 消失的v2ray-core文件夹也没有回来呀

**Comment by GitH123i** [comment]
原因是v2rayU每次启动的时候都会删除这个文件夹，它每次启动的时候 删除文件夹在重新解压干什么？？这个机制存在的本身有问题把？？

**Comment by lolstudio** [comment]
问题依旧，替换v2ray-core或者 降版本到2.1.0都无解

**Comment by Zhou-Bill** [comment]
貌似这个解决方案不太行， 我windows 手机都可以上， 但v2rayu 上不了， 试过更改 v2ray-core 仍无解
