### ISSUE TITLE
无法生成日志 v2.2.0

### ISSUE THREAD

**Issue by Birdknothing** [yanue/V2rayU#659]
无法生成日志

**Comment by huhai586** [comment]
我也遇到这个问题,就今天出现的, 卸载重装app 也不行,且代理无法正常工作

**Comment by somes** [comment]
> 我也遇到这个问题，就今天出现的，卸载重装app也不行，且代理无法正常工作

下午一点遇到同样的问题，起初没把问题想到软件上。认为是节点或者系统问题。
重启、改系统代理配置都不行，然后重装了v2rayu也没用，最后发现是v2ray-core没了。
自己下载放里面去就行了。/Applications/V2rayU.app/Contents/Resources/

**Comment by huhai586** [comment]
> > 我也遇到这个问题，就今天出现的，卸载重装app也不行，且代理无法正常工作
> 
> 下午一点遇到同样的问题，起初没把问题想到软件上。认为是节点或者系统问题。
> 重启、改系统代理配置都不行，然后重装了v2rayu也没用，最后发现是v2ray-core没了。
> 自己下载放里面去就行了。/Applications/V2rayU.app/Contents/Resources/

非常感谢,终于能上网了😰

**Comment by iPhonePKAndroid** [comment]
core 在哪里下载啊

**Comment by huhai586** [comment]
> core 在哪里下载啊

https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0
v2ray-macos-64.zip
