### ISSUE TITLE
1.3的ssr不支持混淆是吧

### ISSUE THREAD

**Issue by burning** [yanue/V2rayU#66]
1.ssr不支持混淆
2.对订阅的支持不是太完美，有些名称会出现乱码
![image](https://user-images.githubusercontent.com/23622/58214243-9811a300-7d27-11e9-8d0c-99b63954e19f.png)

**Comment by chavyleung** [comment]
https://github.com/yanue/V2rayU/commit/112a32d138efd003e85b049da1e94153e7785051

**Comment by yanue** [comment]
是的,v2ray本身不支持ssr

**Comment by yanue** [comment]
订阅的后续看下如何优化

**Comment by itgamer** [comment]
不支持混淆，没法用

**Comment by chavyleung** [comment]
@yanue 
哈哈，release log写得容易误会

**Comment by yanue** [comment]
> @yanue
> 哈哈，release log写得容易误会

已改

**Comment by yanue** [comment]
@chavyleung 已改

**Comment by yanue** [comment]
@burning 订阅功能已优化,请下载1.3.1进行使用
