### ISSUE TITLE
V2.2.0 版本失效

### ISSUE THREAD

**Issue by guiqiqi** [yanue/V2rayU#661]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU: v2.2.0; 
macOS Catalina 10.15.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
从8月7日凌晨开始, 软件失效, v2ray自身日志也停止记录.
通过 `netstat` 命令查看后发现指定的 socket 与 http 端口均没有侦听.
而指定的pac端口侦听正常.

3)  请附上出错时软件输出的错误日志。
无错误输出

感谢作者的工作.

**Comment by ShusenTang** [comment]
同，不过我的是在今天下午一点半突然不行了，日志也停留在一点半的时候

**Comment by LAIBOLIN** [comment]
同样的问题，8.6使用正常，8.7就无法使用了

**Comment by rgshare** [comment]
我也是，今天突然就不行了，一顿折腾之后将版本降级到`2.1.0`后就OK了。

**Comment by yaohwu** [comment]
Aug  7 14:12:20
Service exited with abnormal code: 78
(yanue.v2rayu.v2ray-core): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
(yanue.v2rayu.v2ray-core[4873]): Service could not initialize: 19G73: xpcproxy + 14521 [839][7F45481D-FDD9-30DD-89D8-70B3949DD328]: 0x2

**Comment by dirklei** [comment]
贴一个命令行的启动日志：
/Applications/V2rayU.app/Contents/MacOS/V2rayU
2020-08-07 14:14:28.624 V2rayU[7361:127325] Permission is root admin
2020-08-07 14:14:28.624 V2rayU[7361:127325] Permission is ok
after SCPreferencesCommitChanges: commitRet = true, applyRet = true
2020-08-07 14:14:28.842 V2rayU[7361:127325] setSystemProxy backup succeeded.
2020-08-07 14:14:28.842 V2rayU[7361:127325] start menu
isOldConfigVersion true
ping start
chmod: Unable to change file mode on ./V2rayUHelper: Operation not permitted
chmod: Unable to change file mode on ./V2rayUTool: Operation not permitted
GeneratePACFile rewrite 1090
PACFilePath /Applications/V2rayU.app/Contents/Resources/pac/proxy.js
webServer.start at:11085
2020-08-07 14:14:28.903 V2rayU[7361:127325] working dir:/Applications/V2rayU.app
2020-08-07 14:14:31.551 V2rayU[7361:127325] start download
2020-08-07 14:14:31.833 V2rayU[7361:127475] 已下载：0KB
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./v2ray-macos.zip or
        ./v2ray-macos.zip.zip, and cannot find ./v2ray-macos.zip.ZIP, period.
chmod: ./v2ray-core: No such file or directory
2020-08-07 14:14:31.855 V2rayU[7361:127325] res:
ping error www.xxxxxx（地址） Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
ping error www.xxxxxx Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
ping error www.xxxxxx. Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
ping error xxxxxxxxx Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
ping error xxxxxx Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
ping error xxxxxx Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
ping error xxxxxx Optional(Error Domain=NSURLErrorDomain Code=-1015 "(null)")
2020-08-07 14:14:46.207 V2rayU[7361:127325] start v2ray-core begin
/Users/yulei/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 14:14:46.278 V2rayU[7361:127325] Stop v2ray-core succeeded.
2020-08-07 14:14:46.288 V2rayU[7361:127325] checkPort: res=(Optional("ok")) cmd=(cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd port -h 127.0.0.1 -p 1090)
2020-08-07 14:14:46.296 V2rayU[7361:127325] checkPort: res=(Optional("ok")) cmd=(cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd port -h 127.0.0.1 -p 1089)
2020-08-07 14:14:46.304 V2rayU[7361:127325] checkPort: res=(Optional("ok")) cmd=(cd /Applications/V2rayU.app/Contents/Resources && chmod +x ./V2rayUHelper && ./V2rayUHelper -cmd port -h 0.0.0.0 -p 11085)
webServer.start at:11085
chmod: ./v2ray-core: No such file or directory
/Users/yulei/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 14:14:46.384 V2rayU[7361:127325] Start v2ray-core succeeded.
2020-08-07 14:14:46.385 V2rayU[7361:127325] start v2ray-core done.
webServer.start at:11085
chmod: ./v2ray-core: No such file or directory
/Users/yulei/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Could not find specified service
2020-08-07 14:14:46.460 V2rayU[7361:127325] Start v2ray-core succeeded.
after SCPreferencesCommitChanges: commitRet = true, applyRet = true
2020-08-07 14:14:47.031 V2rayU[7361:127325] setSystemProxy pac succeeded.
2020-08-07 14:14:54.391 V2rayU[7361:127325] open logs succeeded.
我的也是相同配置，osx最新，v2ray版本最新，昨晚还正常，今天就不行了

**Comment by leo-je** [comment]
同.代理端口启动失败,拒绝连接

**Comment by Johnny-Wish** [comment]
应该是这个原因：

`chmod: ./v2ray-core: No such file or directory`
v2ray-core不知道为什么被删除了，解决方法是从https://github.com/v2ray/v2ray-core下载最新v2ray-core的release，然后解压到/Applications/V2rayU.app/Contents/Resources命名为v2ray-core.

**Comment by xinsxxx** [comment]
同样的问题，8月7日无法使用，之前都没问题，折腾了一早上都不知道怎么弄！

**Comment by wentmac** [comment]
2.2版本。上午还能用，下午怎么突然不能用了？？

**Comment by skyer-linlin** [comment]
> 应该是这个原因：
> 
> `chmod: ./v2ray-core: No such file or directory`
> v2ray-core不知道为什么被删除了，解决方法是从[v2ray-core](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0) 下载最新的release，然后解压到`/Applications/V2rayU.app/Contents/Resources`，并将目录命名为`v2ray-core/`

非常有用，3x

**Comment by xinsxxx** [comment]
> > 应该是这个原因：
> > `chmod: ./v2ray-core: No such file or directory`
> > v2ray-core不知道为什么被删除了，解决方法是从[v2ray-core](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0) 下载最新的release，然后解压到`/Applications/V2rayU.app/Contents/Resources`，并将目录命名为`v2ray-core/`
> 
> 非常有用，3x

我刚刚重新下载了最新的release安装后，就解决了，v2ray-core文件夹也有了。

**Comment by Goserizz** [comment]
> 应该是这个原因：
> 
> `chmod: ./v2ray-core: No such file or directory`
> v2ray-core不知道为什么被删除了，解决方法是从[v2ray-core](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0) 下载最新的release，然后解压到`/Applications/V2rayU.app/Contents/Resources`，并将目录命名为`v2ray-core/`

解决了 但是为什么会出现这种问题？

**Comment by dirklei** [comment]
我换回了2.1.0版本,网络恢复正常，日志还是不行，然后通过2.1.0 v2rayU内更新APP到2.2.0,日志恢复正常，网络访问正常了

**Comment by yanue** [comment]
#662

**Comment by Johnny-Wish** [comment]
> > 应该是这个原因：
> > `chmod: ./v2ray-core: No such file or directory`
> > v2ray-core不知道为什么被删除了，解决方法是从[v2ray-core](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0) 下载最新的release，然后解压到`/Applications/V2rayU.app/Contents/Resources`，并将目录命名为`v2ray-core/`
> 
> 解决了 但是为什么会出现这种问题？

看这个https://github.com/yanue/V2rayU/issues/662#issuecomment-670363601

**Comment by m1koo** [comment]
天啊，搞了三个小时吐血

**Comment by guiqiqi** [comment]
问题已经解决.
