### ISSUE TITLE
【解决方法】V2.2.0 突然无法访问情况/无法打开端口/无法生成日志

### ISSUE THREAD

**Issue by Johnny-Wish** [yanue/V2rayU#662]
刚刚遇到这个问题，看到很多人都提到。

首先 `ls /Applications/V2rayU.app/Contents/Resources/v2ray-core` 如果没有v2ray-core目录 说明v2ray-core不知道为什么被删除了
解决方法是从[v2ray-core](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0) 下载最新的macos版release，确认hash之后解压到/Applications/V2rayU.app/Contents/Resources 并重命名为v2ray-core.

**Comment by cytown** [comment]
碰到了同样问题，怪了。重新下载v2rayu.dmg然后 安装是否应该也有效？

**Comment by Johnny-Wish** [comment]
我不是开发者所以不太确定，建议手动验证/Applications/V2rayU.app/Contents/Resources/v2ray-core目录是否存在

**Comment by cytown** [comment]
嗯，也是可以的。奇怪为何会自动被删除了，应该是更新错误。估计有个定期更新v2ray-core的方法，然后出错了。

**Comment by yanue** [comment]
主动更新出问题了, 可以手动下载v2ray-core替换试下: 
```/Applications/V2rayU.app/Contents/Resources/v2ray-core/```

下载地址: https://github.com/v2ray/v2ray-core/releases/download/v4.27.0/v2ray-macos-64.zip

原因,v2ray-core更改了包下载地址规则,原匹配规则:
```    var releaseUrl: String = "https://github.com/v2ray/v2ray-core/releases/download/${version}/v2ray-macos.zip"```

**Comment by LynanBreeze** [comment]
start v2ray fail: config not found的小伙伴有吗？

**Comment by LynanBreeze** [comment]
> start v2ray fail: config not found的小伙伴有吗？
按照上面的方法 替换v2ray-core没有效果。
----------------------------------

重新更新了一下订阅，可以了。

**Comment by zhouwenze** [comment]
> > start v2ray fail: config not found的小伙伴有吗？
> 
> 按照上面的方法 替换v2ray-core没有效果。
> 重新更新了一下订阅，可以了。

不要复制v2ray-macos-64.zip里面的.json配置文件，会把你本地的配置给替换掉
