### ISSUE TITLE
突然无法上网了。iOS端正常

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#669]
相同的节点，Mac端突然无法上网了，ios端正常能上网。
还有重启电脑后提示端口被占用。
另外，有的时候Ping Speed测速效果并不好，测出来的速度不是最快的，有时候都是不能用的，还不如我手动切换呢。
另外，如果测速失败，建议显示通知提示下。
版本V2.2.0 Mac OS 10.15.6

**Comment by wubaiqing** [comment]
我也是 Mac 无法使用。

**Comment by Azarealice** [comment]
#663 https://github.com/yanue/V2rayU/issues/663

**Comment by zealzhangz** [comment]
作者是不是删库跑路了🤦‍♀️

**Comment by qiaoqiao888** [comment]
我和你一样....同样的配置windows可以使用，macos不可以使用。很郁闷。

**Comment by yanue** [comment]
对比一下配置文件

**Comment by moranxichen** [comment]
同楼上 .同样的配置windows可以使用，macos不可以使用
