### ISSUE TITLE
无法卸载，大家慎重安装

### ISSUE THREAD

**Issue by kurodaakira-jp** [yanue/V2rayU#671]
无法卸载，之前issues里面说的指令完全没用，重启依旧会恢复，准备重装了

<img width="708" alt="スクリーンショット 2020-08-10 20 48 52" src="https://user-images.githubusercontent.com/38561128/89784326-10da6600-db4b-11ea-9fca-f15d49187ef4.png">

**Comment by NineSwordsMonster** [comment]
+1

**Comment by yanue** [comment]
#697
