### ISSUE TITLE
V2RayU和winV2同样参数无法访问谷歌

### ISSUE THREAD

**Issue by henry2056** [yanue/V2rayU#672]
如题，V2RayU2.2.0版本和winV2ray同样配置参数无法访问谷歌

你正在使用的 V2RayU 和 Mac 版本 ？
是
你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
系统时间正确，端口也修改，可是还是无法访问谷歌
请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
![微信图片_20200811213221](https://user-images.githubusercontent.com/25130960/89904121-1f904e00-dc1b-11ea-983a-59fa78f3ee7a.jpg)

**Comment by yanue** [comment]
对比一下配置文件
