### ISSUE TITLE
Ping Speed bug

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#673]
当我使用Ping Speed 功能时候，经常它Ping出来的节点都不是速度最快的，而我手动切换的节点却是速度最快的。这是什么原因导致的？我想是不是因为Ping只是Ping一次，而有的时候一个速度快的节点可能偶尔会有速度慢的情况，所以我想这样或许能解决上面提出的问题：同一个节点Ping的次数增加到3-5次，然后取平均速度最大的节点。

**Comment by yanue** [comment]
#739
