### ISSUE TITLE
无法更新，macOS 11 big sur

### ISSUE THREAD

**Issue by chocoford** [yanue/V2rayU#674]
下载完解压完重新启动程序时出错，显示无法解压

**Comment by 2788** [comment]
+1 
我卸载重下2.3.0版本, 现在提示损坏了.... 心态崩了

**Comment by wzzlYwzzl** [comment]
+1 下载的2.3.0无法安装，也是提示损坏

**Comment by yanue** [comment]
请在命令行输入后重试:
sudo spctl --master-disable

**Comment by CodePoem** [comment]
sudo xattr -r -d com.apple.quarantine  /Applications/V2rayU.app

**Comment by Mosery** [comment]
> 目前版本自动更新有问题, 请手动下载安装,如提示：V2rayU已损坏, 请在命令行输入后重试:
> `sudo spctl --master-disable`

提示输入密码，这是什么

**Comment by Goog686ii** [comment]
@yanue 作者大大好，安装2.3版本提示：V2rayU已损坏，可以使用命令解决，想问下为什么2.2版本或者低版本安装就不需要使用命令，就2.3新版本出现这样的损坏呢
