### ISSUE TITLE
2.3版本打开时提示：V2rayU已损坏，无法打开，您应该将它移到废纸篓

### ISSUE THREAD

**Issue by 0x4f5da2** [yanue/V2rayU#675]

**Comment by yanue** [comment]
请在命令行输入后重试:
```sudo spctl --master-disable```

**Comment by CodePoem** [comment]
sudo xattr -r -d com.apple.quarantine  /Applications/V2rayU.app

**Comment by oodzchen** [comment]
我这儿用了命令行好像还是不行
