### ISSUE TITLE
总是弹出网页检查器, 提示"JSON Parse error: Unexpected EOF"

### ISSUE THREAD

**Issue by lihaoyun6** [yanue/V2rayU#677]
打开V2rayU的时候, 还有设置服务器的时候, 都会弹出网页检查器窗口, 提示"JSON Parse error: Unexpected EOF"
服务器配置界面也提示无效的JSON. 但可以用...以前的版本没有这种问题
<img width="1112" alt="Xnip2020-08-12_08-56-32" src="https://user-images.githubusercontent.com/16348097/89963707-e8ea2000-dc7a-11ea-9feb-5e529953ab8c.png">

**Comment by lihaoyun6** [comment]
软件版本是最新的2.3.0
系统版本是10.15.4 (19E287)

**Comment by MerenguesGeek** [comment]
![image](https://user-images.githubusercontent.com/6032223/90011771-c4229680-dcd4-11ea-9715-44ce3174eddf.png)
我也是，一直弹框，弹了好几百个
