### ISSUE TITLE
macOS 10.15.6 (19G73) 执行命令sudo spctl --master-disable还是无法运行

### ISSUE THREAD

**Issue by NuanShen** [yanue/V2rayU#682]
macOS 10.15.6 (19G73) 执行命令sudo spctl --master-disable之后还是提示无法运行

**Comment by hyuhui** [comment]
> macOS 10.15.6 (19G73) 执行命令sudo spctl --master-disable之后还是提示无法运行

执行
sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app

**Comment by Mosery** [comment]
执行上述语句时需要输入password，password是什么

**Comment by Mosery** [comment]
> > macOS 10.15.6 (19G73) 执行命令sudo spctl --master-disable之后还是提示无法运行
> 
> 执行
> sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app

执行上述语句时需要输入password，password是什么

**Comment by bbyan** [comment]
> > > macOS 10.15.6 (19G73) 执行命令sudo spctl --master-disable之后还是提示无法运行
> > 
> > 
> > 执行
> > sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app
> 
> 执行上述语句时需要输入password，password是什么

你mac电脑的密码

**Comment by bbyan** [comment]
> > > macOS 10.15.6 (19G73) 执行命令sudo spctl --master-disable之后还是提示无法运行
> > 
> > 
> > 执行
> > sudo xattr -r -d com.apple.quarantine /Applications/V2rayU.app
> 
> 执行上述语句时需要输入password，password是什么

你MAC 电脑的用户密码
