### ISSUE TITLE
更新后提示 “文件已损坏”？ 这是怎么回事？

### ISSUE THREAD

**Issue by williamlonginfo** [yanue/V2rayU#683]
更新后提示 “文件已损坏”？ 这是怎么回事？
是作者喝茶了还是账号被控制了？

**Comment by philip8728** [comment]
更新后出现了同样的问题，mac系统版本10.15.6

**Comment by wentmac** [comment]
更新后出现了同样的问题，mac系统版本10.15.6

**Comment by jiuqianyuan** [comment]
同出现问题

**Comment by yanue** [comment]
都不看相关问题的吗？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jiuqianyuan <notifications@github.com>
发送时间: Wednesday, August 12, 2020 4:51:07 PM
收件人: yanue/V2rayU <V2rayU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [yanue/V2rayU] 更新后提示 “文件已损坏”？ 这是怎么回事？ (#683)


同出现问题

―
