### ISSUE TITLE
更新了2.3.1以后，不能用了，附日志

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#690]
链接: https://pan.baidu.com/s/1kIkgThBqh3XC-rHBxNbQvA 提取码: yf58
[1234.zip](https://github.com/yanue/V2rayU/files/5074443/1234.zip)

**Comment by davidtall** [comment]
遇到同样的问题，日志空白，用不了

**Comment by ioudove** [comment]
尝试了卸载重新安装，也不能用

**Comment by ioudove** [comment]
重新安装后使用下面命令行
也还是不行
 unzip v2ray-macos-64.zip
     mv ~/Downloads/v2ray-macos-64 /Applications/V2rayU.app/Contents/Resources/v2ray-core/

**Comment by ioudove** [comment]
还有，这个软件没有办法彻底删除，在访达中通过应用程序删除后，再重新安装，之前的所有设置，订阅都还在。不能彻底删除，作者可以说明下如何彻底删除软件么？

**Comment by yanue** [comment]
> 还有，这个软件没有办法彻底删除，在访达中通过应用程序删除后，再重新安装，之前的所有设置，订阅都还在。不能彻底删除，作者可以说明下如何彻底删除软件么？

#697
