### ISSUE TITLE
更新2.3.1以后依然不能用，附报错日志

### ISSUE THREAD

**Issue by gongxianhui0** [yanue/V2rayU#691]
2020/08/14 20:29:52 [Info] [3897608017] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:translate.google.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:29:52 [Info] [4081630481] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:29:52 [Info] [3897608017] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 222 but actually 151
2020/08/14 20:29:52 [Info] [3897608017] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:29:52 [Warning] [4081630481] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/08/14 20:29:52 [Info] [4081630481] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:29:54 [Info] [2661688428] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.googleapis.com:443
2020/08/14 20:29:54 [Info] [2661688428] v2ray.com/core/app/dispatcher: default route for tcp:www.googleapis.com:443
2020/08/14 20:29:54 [Info] [2661688428] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:29:54 tcp:127.0.0.1:55477 accepted tcp:www.googleapis.com:443 [proxy] 
2020/08/14 20:29:54 [Info] [2661688428] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:29:54 [Info] [2077382562] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:29:54 [Info] [2077382562] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:29:54 [Info] [2077382562] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:29:54 tcp:127.0.0.1:55479 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:29:54 [Info] [2077382562] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:29:55 [Info] [2661688428] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 29 but actually 94
2020/08/14 20:29:55 [Info] [2661688428] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:29:55 [Info] [2936373181] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.googleapis.com:443
2020/08/14 20:29:55 [Info] [2936373181] v2ray.com/core/app/dispatcher: default route for tcp:www.googleapis.com:443
2020/08/14 20:29:55 [Info] [2936373181] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:29:55 tcp:127.0.0.1:55481 accepted tcp:www.googleapis.com:443 [proxy] 
2020/08/14 20:29:55 [Info] [2936373181] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:29:55 [Warning] [2077382562] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/08/14 20:29:55 [Info] [2077382562] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:29:55 [Info] [1108429269] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:29:55 [Info] [1108429269] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:29:55 [Info] [1108429269] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:29:55 tcp:127.0.0.1:55483 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:29:55 [Info] [2936373181] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 50 but actually 56
2020/08/14 20:29:55 [Info] [2936373181] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:29:55 [Info] [1108429269] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:29:55 [Warning] [1108429269] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/08/14 20:29:55 [Info] [1108429269] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:30:04 [Info] [117543520] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:04 [Info] [117543520] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:04 [Info] [117543520] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:30:04 tcp:127.0.0.1:55490 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:30:04 [Info] [117543520] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:30:04 [Info] [117543520] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 77 but actually 184
2020/08/14 20:30:04 [Info] [117543520] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:30:04 [Info] [2680952789] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:04 [Info] [2680952789] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:04 [Info] [2680952789] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:30:04 tcp:127.0.0.1:55492 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:30:05 [Info] [2680952789] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:30:05 [Warning] [2680952789] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/08/14 20:30:05 [Info] [2680952789] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:30:21 [Info] [3054770751] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:21 [Info] [3054770751] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:21 [Info] [3054770751] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:30:21 tcp:127.0.0.1:55498 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:30:22 [Info] [3054770751] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:30:22 [Warning] [3054770751] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/08/14 20:30:22 [Info] [3054770751] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:30:22 [Info] [44241514] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:22 [Info] [44241514] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:22 [Info] [44241514] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:30:22 tcp:127.0.0.1:55500 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:30:22 [Info] [44241514] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 darwin/amd64)
A unified platform for anti-censorship.
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 darwin/amd64)
A unified platform for anti-censorship.
2020/08/14 20:30:25 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
2020/08/14 20:30:25 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/08/14 20:30:25 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2020/08/14 20:30:25 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2020/08/14 20:30:25 [Warning] v2ray.com/core: V2Ray 4.27.0 started
2020/08/14 20:30:25 [Info] [3760529358] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:25 [Info] [3760529358] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:25 [Info] [3760529358] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:30:25 tcp:127.0.0.1:55531 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:30:26 [Info] [3760529358] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:30:26 [Warning] [3760529358] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/08/14 20:30:26 [Info] [3760529358] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/14 20:30:26 [Info] [3090697954] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:26 [Info] [3090697954] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2020/08/14 20:30:26 tcp:127.0.0.1:55545 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/08/14 20:30:26 [Info] [3090697954] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:v4.cumt.fun:443
2020/08/14 20:30:27 [Info] [3090697954] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:v4.cumt.fun:443
2020/08/14 20:30:27 [Info] [3090697954] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 183 but actually 114
2020/08/14 20:30:27 [Info] [3090697954] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by ioudove** [comment]
同样的问题，我重新安装还是不行，还不如不升级了，哎。2.30就没有问题
