### ISSUE TITLE
Mac使用2.2版本没有问题，相反升级之后有问题，注意不要升级！！！

### ISSUE THREAD

**Issue by kekincai** [yanue/V2rayU#692]
我看到有新版本升级，升级之后反而报错，这跟官方的说法不一致，可能官方说的是windows的问题。

**Comment by kekincai** [comment]
还是等等吧，现在也没有什么不方便的

**Comment by yutianhang** [comment]
也可以用v2rayX，bug少得多。v2rayU实测用起来太费劲。。。

**Comment by kekincai** [comment]
> 也可以用v2rayX，bug少得多。v2rayU实测用起来太费劲。。。

是的，有时候还崩溃
