### ISSUE TITLE
macos 更新2.3.1以后还是不可以使用

### ISSUE THREAD

**Issue by qiaoqiao888** [yanue/V2rayU#694]
macos 更新 2.3.1不可以使用，前一天还可以正常使用
第二天就凉凉了。

**Comment by Laqian** [comment]
同 我这里出现一下图标就消失了

**Comment by KBvsMJ** [comment]
直接打开这里下载[V2rayU] (https://tlanyan.me/v2ray-clients-download/)

**Comment by KBvsMJ** [comment]
@qiaoqiao888   直接打开这里下载老版本V2rayU客户端[V2rayU](https://tlanyan.me/v2ray-clients-download/)覆盖安装！
