### ISSUE TITLE
小白求教

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#698]
cd ~/Library/LaunchAgents/
/bin/launchctl remove yanue.v2rayu.v2ray-core
/bin/launchctl remove yanue.v2rayu.http

rm -f ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -f ~/Library/Preferences/net.yanue.V2rayU.plist
rm -f ~/Library/Logs/V2rayU.log
这些命令行中的～是不是要替换成自己电脑的目录？ 如果是需要替换的话，怎么确定这个目录的路径呢？
求教，求教～

**Comment by ioudove** [comment]
是不是把这些丢进终端里去执行就行了？但是我执行完以后，软件并没有被删除呢。。。。
cd /Users/xiaolang/Library/LaunchAgents/
/bin/launchctl remove yanue.v2rayu.v2ray-core
/bin/launchctl remove yanue.v2rayu.http

rm -f /Users/xiaolang//Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -f /Users/xiaolang//Library/Preferences/net.yanue.V2rayU.plist
rm -f /Users/xiaolang//Library/Logs/V2rayU.log

**Comment by ioudove** [comment]
作者可以给出详细一点的步骤么？ 小白啊，，，，，

**Comment by yanue** [comment]
删除V2rayU.app过后执行
