### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by burning** [yanue/V2rayU#7]
1、Enable Mux 无效，即使取消勾选，下次默认还是勾选的。
2、有时候了一打开多个Configure设置界面。
3、Configure设置界面 填写好配置不是自动保存，必须点一下OK，甚至有时候点OK也保存不上。
4、每个Servers对应可填写一个 Sock Port 和 Http Port 的意思是可以在后台启动多个代理吗？多服务器同是后台启动？

**Comment by yanue** [comment]
好的  收到 问题4,是同时支持本地sock5代理和http代理,可运用在不同场景

**Comment by swjtuhyq** [comment]
无法设置多个服务器，后面设置的会覆盖前面设置的服务器，这样怎么使用呢
