### ISSUE TITLE
setSystemProxy global failed.

### ISSUE THREAD

**Issue by coolrose78** [yanue/V2rayU#70]
无法设置不同的模式，pac或全局，必须在系统手动要改....s
macos HIgh D=Sierra
![Screen Shot 2019-05-24 at 6 47 42 PM](https://user-images.githubusercontent.com/36027339/58364086-5b33e080-7ece-11e9-89ba-4971b6ffeca8.png)

**Comment by yanue** [comment]
命令行,运行一下V2rayUTool看下,应该是权限不够
`
cd /Applications/V2rayU.app/Contents/Resources/
./V2rayUTool
`

**Comment by coolrose78** [comment]
![swift](https://user-images.githubusercontent.com/36027339/58366413-a27f9880-7ef1-11e9-9488-1651782ecc7e.png)

**Comment by yanue** [comment]
我退回swift4.2了,应该没这个问题了

**Comment by yanue** [comment]
已修复,请下载1.3.2版本

**Comment by lvpeng0412** [comment]
你好，我想问下这个v2rayutool是怎么打包的，直接build只有88kb @yanue
