### ISSUE TITLE
小白求救！failed to handler mux client connection报错问题

### ISSUE THREAD

**Issue by HTHTTT** [yanue/V2rayU#701]
今天win10端启动后无法连接，一直显示warning。我的安卓手机端使用没问题，问了一起搭伙的朋友（mac），他们也能正常用没有问题
warning内容见截图
![微信图片_20200819164852](https://user-images.githubusercontent.com/69895794/90613387-e1f37c80-e23b-11ea-88a8-8675c06f0b4a.png)
百度有的说是电脑没自动设置时间的问题，但我的电脑“自动设置时间”一项一直是开着的
有搜到类似的提问，但鄙人电脑小白，评论区大神一句“请确认配置”简单带过我真的不明白什么意思……希望有大神能耐心帮解答一下，感激不尽！

**Comment by yanue** [comment]
启用tls了? 把证书验证去掉试下,或者tls选为空
![image](https://user-images.githubusercontent.com/1435250/94658622-9e5d5980-0335-11eb-9368-b4a3bfcaae23.png)
