### ISSUE TITLE
2.3.1不能使用

### ISSUE THREAD

**Issue by frankyanghao** [yanue/V2rayU#703]
更新后一天 无法上外网 MAC 端使用

问题：昨日下午出现无法打开外网的情况；服务器列表已更新，且各国都试了均无法打开外网； 小白用户  ，若还需要提供请大佬们明示 感激不尽！期待回复

**Comment by crystal4me** [comment]
我也是无法使用呀，已经是最新版本了，还卸载了重新装的。mac版本。

**Comment by MRYOG** [comment]
可以说下 是mac 那个版本的系统不

**Comment by crystal4me** [comment]
> 可以说下 是mac 那个版本的系统不，哪个mac系不能使用

我的mac版本是10.15.6，不过我发现貌似不是软件造成不能访问的，而是我买的VPN服务挂掉了，提供商跑路了。你们有没有好的VPN服务订阅呀，可以推荐一波，先行谢过！

**Comment by ilovebamboo** [comment]
http://dwz.date/cpVe




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "spirit"<notifications@github.com&gt;; 
发送时间: 2020年8月31日(星期一) 下午5:35
收件人: "yanue/V2rayU"<V2rayU@noreply.github.com&gt;; 
抄送: "APPX"<xuezia@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yanue/V2rayU] 2.3.1不能使用 (#703)





  
可以说下 是mac 那个版本的系统不，哪个mac系不能使用
  
我的mac版本是10.15.6，不过我发现貌似不是软件造成不能访问的，而是我买的VPN服务挂掉了，提供商跑路了。你们有没有好的VPN服务订阅呀，可以推荐一波，先行谢过！
 
&mdash;

**Comment by ilovebamboo** [comment]
http://dwz.date/cpVe

**Comment by TonyNong2007** [comment]
MacOS Catalina 10.15.5
不能使用
APPclear卸载后重装也不行
系统显示程序错误
求解决办法，谢谢！

**Comment by Brianliao1986** [comment]
> > 可以说下 是mac 那个版本的系统不，哪个mac系不能使用
> 
> 我的mac版本是10.15.6，不过我发现貌似不是软件造成不能访问的，而是我买的VPN服务挂掉了，提供商跑路了。你们有没有好的VPN服务订阅呀，可以推荐一波，先行谢过！

http://92.pm/klm

**Comment by yutianhang** [comment]
如果这个问题你总是解决不了，可以试试v2rayX，不用折腾就能用。。。
