### ISSUE TITLE
mac 10.15.6 无法使用

### ISSUE THREAD

**Issue by ilovebamboo** [yanue/V2rayU#704]
![391597993912_ pic_hd](https://user-images.githubusercontent.com/6214084/90879807-0b4a0f00-e3da-11ea-90d7-570d6f97cd92.jpg)

2020/08/21 18:14:38 [Info] [3355951541] v2ray.com/core/transport/internet/websocket: creating connection to tcp:appx1.appx.com:80
2020/08/21 18:14:38 [Info] [414210128] v2ray.com/core/transport/internet/websocket: creating connection to tcp:appx1.appx.com:80
2020/08/21 18:14:38 [Info] [1624753552] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:232.150.18.12:443 > v2ray.com/core/common/retry: [dial tcp 232.150.18.12:443: connect: address family not supported by protocol family] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/21 18:14:38 [Info] [1624753552] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/21 18:14:38 [Info] [1123101696] v2ray.com/core/transport/internet/websocket: creating connection to tcp:appx1.appx.com:80
2020/08/21 18:14:38 [Info] [411338738] v2ray.com/core/transport/internet/websocket: creating connection to tcp:appx1.appx.com:80
2020/08/21 18:14:38 [Info] [592231347] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:232.150.18.12:443 > v2ray.com/core/common/retry: [dial tcp 232.150.18.12:443: connect: address family not supported by protocol family] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/21 18:14:38 [Info] [592231347] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/08/21 18:14:38 [Info] [727235002] v2ray.com/core/transport/internet/websocket: creating connection to tcp:appx1.appx.com:80
2020/08/21 18:14:38 [Info] [4128775007] v2ray.com/core/transport/internet/websocket: creating connection to tcp:appx1.appx.com:80
2020/08/21 18:14:38 [Info] [1978092313] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/08/21 18:14:38 [Info] [1407932356] v2ray.com/core/proxy/socks: TCP Connect request to tcp:0.57.137.3:443
2020/08/21 18:14:38 [Info] [604982661] v2ray.com/core/proxy/socks: TCP Connect request to tcp:149.154.175.50:443
2020/08/21 18:14:38 [Info] [1814012380] v2ray.com/core/proxy/socks: TCP Connect request to tcp:149.154.175.50:80
2020/08/21 18:14:38 [Info] [586519061] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/08/21 18:14:38 [Info] [3725179627] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:248.123.119.5:443
2020/08/21 18:14:38 [Info] [3171179887] v2ray.com/core/proxy/socks: TCP Connect request to tcp:0.57.137.3:443
2020/08/21 18:14:38 [Info] [3171179887] v2ray.com/core/app/dispatcher: taking detour

**Comment by TonyNong2007** [comment]
相同问题。
用APPclear卸载，但是仍然没有解决问题。
求救，谢谢！

**Comment by yutianhang** [comment]
> > 同样最新的10.15.6均无法启动v2rayU，TAG界面的两条命令已经运行还是无法正常启动
> 
> 已解决，参考这个issue完全卸载后重新安装最新版[#697](https://github.com/yanue/V2rayU/issues/697)

也可以使用v2rayX，实测v2rayU问题太多。。。

**Comment by note4** [comment]
> > > 同样最新的10.15.6均无法启动v2rayU，TAG界面的两条命令已经运行还是无法正常启动
> > 
> > 
> > 已解决，参考这个issue完全卸载后重新安装最新版[#697](https://github.com/yanue/V2rayU/issues/697)
> 
> 也可以使用v2rayX，实测v2rayU问题太多。。。

确实问题有点多，ShadowsocksX-NG 挺好用的，可惜不支持 V2ray
