### ISSUE TITLE
啥时候支持VLESS协议呢

### ISSUE THREAD

**Issue by loongwind** [yanue/V2rayU#707]
如题

**Comment by tritu** [comment]
Agree, VLESS is the best!

**Comment by luckyporo** [comment]
附议 自己搭的vless只能win和安卓上用 现在在蹭别人的vmess

**Comment by PangciPG** [comment]
right here waiting! 
4 now, Qv2ary is the alternative GUI

**Comment by bunnyblueair** [comment]
+1

**Comment by gabriel9527** [comment]
+10086, qv2ray有bug，期待更新支持

**Comment by yanue** [comment]
请下载预览版试用: https://github.com/yanue/V2rayU/releases/tag/3.0.0.preview

**Comment by drcege** [comment]
@yanue  尝试了3.0正式版，貌似`从粘贴板导入`以及`url导入模式`都还不识别 vless 协议？
