### ISSUE TITLE
PAC设置不能立即生效

### ISSUE THREAD

**Issue by jason275** [yanue/V2rayU#708]
修改PAC规则，点击保存设置后，需要退出程序再打开才会生效；点击保存后不重启程序不会生效。
频繁修改PAC时会比较麻烦，并且初次使用此功能会感到困惑，以为设置的规则有错误或该功能失效。

**Comment by Shawshank01** [comment]
我本人在使用用没有遇到过此问题，请确保自己有按照开头两行说明和文档输入规则，并在输入完成后保存设置并浏览pac文件查询配置是否已写入。

**Comment by yanue** [comment]
#612
