### ISSUE TITLE
2.3.1无法找到config文件

### ISSUE THREAD

**Issue by Evan-Zhangyf** [yanue/V2rayU#711]
启动v2ray core时显示start v2ray fail: config not found

之前一直没有问题，今天突然出现此问题，有遇到一样问题的朋友吗？

**Comment by Evan-Zhangyf** [comment]
已解决

**Comment by wangxw5** [comment]
hi，你是怎么解决的呀？

**Comment by Evan-Zhangyf** [comment]
> hi，你是怎么解决的呀？

我后面发现是机场出问题了，无法更新订阅，和软件无关。换一个订阅连接即可解决。

**Comment by wangxw5** [comment]
谢谢😁
