### ISSUE TITLE
Mac v2.3.1 无论Pac还是Global模式，whatsapp均无法连接

### ISSUE THREAD

**Issue by xianglinkong** [yanue/V2rayU#714]
其他网站访问都正常，只有whatsapp无法连接，而使用clashX则能顺利连接。

**Comment by ioudove** [comment]
你这应该是需要使用mellow吧

**Comment by yrong** [comment]
不存在

**Comment by xianglinkong** [comment]
我这儿还是存在，墙外网站可以上，但是whatsapp提示电脑没联网，使用mellow是什么意思，怎么操作？谢谢！

> 你这应该是需要使用mellow吧

**Comment by yanue** [comment]
whatsapp需要配合proxifier

**Comment by xianglinkong** [comment]
能否说明一下“whatsapp需要配合proxifier” 具体需要怎么做？

**Comment by xianglinkong** [comment]
> whatsapp需要配合proxifier

能否说明一下具体需要怎么做？
