### ISSUE TITLE
求教：如何添加代理网址

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#717]
求教大家
我想把一个网址添加进Pac里面，目前我的规则是这样的：||macbed.com
但是并不管用，并且 ||macbed.com^ 这样也不管用，
求教大神，怎么把网址添加进Pac里面，让这个网址走代理流量呢

**Comment by Qwenjin** [comment]
![image](https://user-images.githubusercontent.com/15087970/92675092-38426f80-f351-11ea-95fb-7120d594222e.png)

这样也可以走代理

**Comment by yutianhang** [comment]
建议使用v2rayX，v2rayU问题太多

**Comment by ioudove** [comment]
> 建议使用v2rayX，v2rayU问题太多

真的，我把网址设置成了代理，有的时候管用，有的时候不管用，需要全局网络才行。哎，希望作者再完善完善吧

**Comment by ioudove** [comment]
> ![image](https://user-images.githubusercontent.com/15087970/92675092-38426f80-f351-11ea-95fb-7120d594222e.png)
> 
> 这样也可以走代理

您截图中的这种方式走代理和“Pac”功能中的代理功能有什么不同。
目前我的Routing页面是
域名策略：Asls
路由模式：全局

这样设置有问题么（这是默认设置，我没有改动）

**Comment by yanue** [comment]
和pac功能重复, 所以建议全局模式下启用路由
