### ISSUE TITLE
针对Big Sur的圆角矩形图标适配参考

### ISSUE THREAD

**Issue by pommeJack** [yanue/V2rayU#719]
参考设计
<img width="616" alt="image" src="https://user-images.githubusercontent.com/30207328/92455733-a45b9100-f1f4-11ea-8969-0c61e3cd8c93.png">

[V2rayU.icns.zip](https://github.com/yanue/V2rayU/files/5187240/V2rayU.icns.zip)

**Comment by ardayan** [comment]
这个字母，理解开发者同时表达V和U的意思，但觉得圆润些更好看。
