### ISSUE TITLE
订阅update问题

### ISSUE THREAD

**Issue by ripp1e** [yanue/V2rayU#72]
添入订阅地址，update后都是fail: error:url，不能解析。是ssr订阅。

**Comment by yanue** [comment]
有优化,请下载1.3.1试下

**Comment by ripp1e** [comment]
还是有问题，能解析出东西了，不过协议解析错误，ssr，但是protocol那里解析成shadowsocks，而且加密方式也错误，把rcmd5解析成aes256

**Comment by yanue** [comment]
v2ray官方只支持几种加密方式,这边补齐了,不一定能用,可以下载1.3.3试下
