### ISSUE TITLE
分组功能需求

### ISSUE THREAD

**Issue by jack89zhao** [yanue/V2rayU#724]
订阅增加自动分组功能，不同的订阅地址放在不同的组中，而不是所有服务器都放在一个列表中

**Comment by Si3ver** [comment]
对于只有一个订阅源的用户，真的很不喜欢分组功能，每次看服务器或者切换服务器要 hover 多一次。希望能服务器能都放在一级列表中。

**Comment by Si3ver** [comment]
另外，更新订阅的功能也希望能放在一级下拉列表中。方便更新服务器
