### ISSUE TITLE
v2rayu-mac-2.3.1 版本, 点击偏好设置后, tab无法切换,导致advance选项进不去, 也无法更换监听端口, 

### ISSUE THREAD

**Issue by Teshling** [yanue/V2rayU#725]
![图片](https://user-images.githubusercontent.com/13238679/93184562-fbbaad80-f76e-11ea-8fb4-dc68c36ef714.png)

**Comment by Teshling** [comment]
![图片](https://user-images.githubusercontent.com/13238679/93184714-260c6b00-f76f-11ea-8b68-9112bb4eaa5b.png)
无论切换哪一个tab, 都显示的是这个界面

**Comment by Teshling** [comment]
我已经尝试退回到2.2的版本, 还是不能解决这个问题,到底是因为什么?

**Comment by Teshling** [comment]
advance选项已经找到入口, 只能点击-->服务器设置-->高级设置,就可以了进入了
有端口占用导致同样问题的朋友可以参考以下设置: 

![图片](https://user-images.githubusercontent.com/13238679/93188675-d8dec800-f773-11ea-99db-a2c96cb45cc7.png)


 另有一个疑问:  难道直接点击偏好设置里的tab, 就是不能切换的吗~~??

**Comment by yanue** [comment]
macos 版本?
