### ISSUE TITLE
Mac 无法使用

### ISSUE THREAD

**Issue by kkangg1** [yanue/V2rayU#727]
浏览器访问网站显示意外终止连接，Safari和Chrome都出现相同问题。但是浏览器功能与信息推送都是正常状态。例如可以使用Chrome自带的Google翻译以及全局模式下能正常接收微信消息
mac恢复网络出厂设置无法修复此问题。
此问题首次出现在把连接在ipad上的usb网卡重连至mac上时出现

**Comment by 1181406961** [comment]
我也遇到了相同的问题，Mac上不能使用了

**Comment by f4cknet** [comment]
这软件凉凉了，目测是被请喝茶了

**Comment by 1181406961** [comment]
> 这软件凉凉了，目测是被请喝茶了

可以用了，看置顶的issues
