### ISSUE TITLE
上不了

### ISSUE THREAD

**Issue by git897** [yanue/V2rayU#732]
2020/09/23 09:36:48 [Info] [3988354423] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2020/09/23 09:36:48 [Info] [2494236083] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.youtube.com:443] with URL [//www.youtube.com:443]
2020/09/23 09:36:48 [Info] [2494236083] v2ray.com/core/app/dispatcher: default route for tcp:www.youtube.com:443
2020/09/23 09:36:48 [Info] [2494236083] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:shonlinesandcu02.proconcn.xyz:553
2020/09/23 09:36:48 127.0.0.1:51134 accepted //www.youtube.com:443 [proxy] 
2020/09/23 09:36:48 [Info] [2494236083] v2ray.com/core/proxy/shadowsocks: tunneling request to tcp:www.youtube.com:443 via tcp:shonlinesandcu02.proconcn.xyz:553
2020/09/23 09:36:48 [Info] [2494236083] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: connection ends > v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF
2020/09/23 09:36:48 [Info] [2494236083] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe

**Comment by activeliang** [comment]
彻底卸载然后重装最新的2.3.1版本，打开后立即进入偏好设置，把『自动检测版本更新』关闭掉。

彻底卸载方法：https://github.com/yanue/V2rayU/issues/663

**Comment by git897** [comment]
> 彻底卸载然后重装最新的2.3.1版本，打开后立即进入偏好设置，把『自动检测版本更新』关闭掉。
> 
> 彻底卸载方法：#663

还是不行，卸载安装了多次，那个替换文件也试过了，还是上不了

**Comment by yanue** [comment]
请确认服务是否可用参数是否正确
