### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by yanue** [yanue/V2rayU#741]
#580 两个小建议-扫描屏幕上二维码增加快捷键
#578 建议在菜单栏Servers一栏显示当前选择的是哪个server
#573 什么时候加入导出服务器配置的功能？ bug
#558 节点会被自动切换会第一个的问题 bug
#576 建议修改 路由匹配顺序 bug
#499 v2.1版本 h2 方式 tls 加密协议无法代理成功 bug
#498 V2RayU 代理规则在手动模式下时切换代理服务器会去更改系统代理 bug
#635 更改运行目录
#629 偏好设置中日志文件路径错误、日志文件占空间太大 bug
#730 只有在同时关掉『通过ping自动选择最快server』和『启动或唤醒时自动更新订阅』，才能固定已选中节点！
#693 切换节点变得特别卡
#642 配置文件保存路径错误
#724 分组功能需求
#695 2.3.1订阅的服务器列表总是被清空
#644 一打开服务器设置程序就崩溃 bug
#609 内网socks身份认证问题  #472
啥时候支持VLESS协议呢 #707
#613 无法导入 V2rayN 生成的 vmess 链接 bug
一打开服务器设置程序就崩溃 #644
闪退 #622
v2.1版本 h2 方式 tls 加密协议无法代理成功 bug #499
#306  [bugs] socks outbounds 格式错误
功能建议：增加路由规则在菜单中的快速切换 #617
2.3.1版本跑满主程序cpu #726
Mac 下多身份账户互相切换使用的时候软件就不能正常工作了 #595
v2rayU禁用开机启动功能无效 #632
关闭了流量检测 还是连接不上tor #514
能否加上支持trojan协议 #415

**Comment by EnjoyMyCode** [comment]
赞👍

**Comment by drcege** [comment]
CPU 疯转的问题一直没解决啊，之前好几个版本到最新的都还有
