### ISSUE TITLE
Mac 休眠后，V2Ray 退出

### ISSUE THREAD

**Issue by wanyx2015** [yanue/V2rayU#742]
Mac OS 10.13.6
V2Ray: 2.3.1

当MacBook Pro屏幕合上后（进入休眠模式），再次打开屏幕，V2RayU 已不再运行，任务栏上找不到V2RayU的图标，需要重新运行V2RayU。

这个问题，自从2.2.0时候就已经存在。

**Comment by MafiaLee** [comment]
同样的问题
