### ISSUE TITLE
vmess服务器，ios应用Quantumult和小飞机， windows的v2rayN都可以用，但是V2rayU无效，怎么解决

### ISSUE THREAD

**Issue by greenking19** [yanue/V2rayU#746]
iphone跟windows速度都很快，同一个wifi。 但是v2rayu就是上不了梯子。 是不是我的配置问题呢？
![WX20201005-024706](https://user-images.githubusercontent.com/43332372/95024388-40be6980-06b5-11eb-9c83-dff23ca2dd2b.png)
服务器是自己搭的
🙁

**Comment by diner-wang** [comment]
同，小火箭能上，clashX也可以，v2rayU不行

**Comment by totoroyyb** [comment]
@greenking19 可能是端口被占用了，v2rayu端口占用没有弹出窗口提示，可以尝试修改一下本机http监听端口。如果需要详细信息，可以去看log里面有无 "cannot bind. address in use" 等类似的字样。

**Comment by yanue** [comment]
猜大家的情况应该是从手机复制链接到电脑然后导进入的。手机上的vmess一般（或者有些）的混淆模式是ws的，但是从手机复制链接导入到电脑端的时候它的混淆模式会变成tcp，所以你要在电脑端改成手动模式然后在 传输配置->选择网络 改成ws，host和path改成跟你手机的配置一样就可以了。https://v2raytech.com/v2rayu-config-tutorial/comment-page-1/#comments

**Comment by yanue** [comment]
对比下配置
