### ISSUE TITLE
分享不了二维码 也扫描不了屏幕

### ISSUE THREAD

**Issue by huangying10000** [yanue/V2rayU#756]
![image](https://user-images.githubusercontent.com/44154448/96448506-15578500-1246-11eb-94c8-9453d1671c9b.png)

**Comment by zhudi998** [comment]
我也是这种情况，手动添加Trojan信息也无法上网

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
