### ISSUE TITLE
MAC OS 升级到10.15.7后就无法正常使用

### ISSUE THREAD

**Issue by kkangg1** [yanue/V2rayU#757]
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 darwin/amd64)
A unified platform for anti-censorship.
2020/10/21 23:05:59 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
2020/10/21 23:05:59 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/10/21 23:05:59 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use

**Comment by tawoli** [comment]
亲测，能用

**Comment by ardayan** [comment]
127.0.0.1:1087: bind: address already in use

**Comment by kkangg1** [comment]
换端口号后问题解决。1087端口重启，杀进程仍显示端口占用

**Comment by sisley-k** [comment]
> 127.0.0.1:1087: bind: address already in use
> 是不是最近装了其他软件，把1087端口给占用了。找出占用端口的app或者在v2rayu的偏好设置换端口。#362

我也是，这几天开始不能正常使用了，端口也改了。还下载重装了3.0版本也不行。
