### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zhengyongtao** [yanue/V2rayU#76]
1. 当使用配置编辑工具编辑时，有几率会导致v2rayU的dock图标无法隐藏。另外使用配置编辑工具删除某个服务器后，配置文件里的这个服务器配置并没有被实际删除，还存在配置文件中。
2. 添加中文支持
3. 在通知栏图标上让人更直观的看出当前的代理模式，这点可以借鉴shadowsocksX，X在pac模式下会标注p，在Global模式下会标注G
4. 可以考虑完善一下配置生成工具，添加一些高级功能的生成支持，比如开启mux之类的特性等等

**Comment by yanue** [comment]
1. 图标问题请试下1.3.3
2. 后续
3. 同:https://github.com/yanue/V2rayU/issues/29
4. mux是支持的. 后面会增加路由规则配置
