### ISSUE TITLE
設置一切正常但是翻不出去

### ISSUE THREAD

**Issue by simplesprite** [yanue/V2rayU#762]
和往常一樣翻（電腦開機是默認打開的），但是突然就翻不出去了，無論用哪個模式都不行。不僅如此一打開v2ray 連國內的網站也會顯示ERR_CONNECTION_TIMED_OUT。speed都蠻正常，端口也是1087，什麼設置都沒有動過。買的線路也沒有過期（手機上還能用）。重新卸載再安裝也沒有用。
隨便複製了幾行日誌的內容，希望有大佬能幫忙看看。學術找資料需要，真的很緊急。
2020/10/26 15:22:33 [Warning] [360979032] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://hk-5.netflixssr.com:543/hls/cctv5phd.m3u8):  > dial tcp 42.3.89.108:543: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2020/10/26 15:22:33 [Warning] [360979032] v2ray.com/core/proxy/http: failed to read response from ocsp.apple.com > io: read/write on closed pipe
2020/10/26 15:22:33 [Warning] [360979032] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > v2ray.com/core/proxy/http: failed to write response > write tcp 127.0.0.1:1088->127.0.0.1:56356: write: broken pipe
2020/10/26 15:22:33 [Info] [2726975769] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [gateway.icloud.com:443] with URL [//gateway.icloud.com:443]
2020/10/26 15:22:33 [Info] [2726975769] v2ray.com/core/app/dispatcher: sniffed domain: gateway.icloud.com
2020/10/26 15:22:33 [Info] [2726975769] v2ray.com/core/app/dispatcher: default route for tcp:gateway.icloud.com:443
2020/10/26 15:22:33 [Info] [2726975769] v2ray.com/core/transport/internet/websocket: creating connection to tcp:hk-5.netflixssr.com:543
2020/10/26 15:22:33 127.0.0.1:56467 accepted //gateway.icloud.com:443 [proxy] 
2020/10/26 15:22:35 [Info] [1402126406] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > context canceled

**Comment by simplesprite** [comment]
補充一下，是mac os

**Comment by moranxichen** [comment]
> 補充一下，是mac os

同样,能Ping通线路,但是无法翻.

**Comment by jiapengwen** [comment]
更新最新的版本，重装就好了

**Comment by simplesprite** [comment]
> 更新最新的版本，重装就好了

試過了也不行！！！！

**Comment by toutoumu** [comment]
同样的订阅地址 IOS 的 kitsunebi 可以, 但是 Mac os 的就是不行

**Comment by jiapengwen** [comment]
> 同样的订阅地址 IOS 的 kitsunebi 可以, 但是 Mac os 的就是不行

你应该用的是v2rayU, 这个更新出错了，你需要更新v2rayU到最新版本

**Comment by jiapengwen** [comment]
> > 更新最新的版本，重装就好了
> 
> 試過了也不行！！！！

我的意思是更新v2rayU 到最新版本

**Comment by simplesprite** [comment]
> > > 更新最新的版本，重装就好了
> > 
> > 
> > 試過了也不行！！！！
> 
> 我的意思是更新v2rayU 到最新版本

对的！！！我是卸掉了，然后在这里找到最新的版本，就是那个预览版的重装的，也不行

**Comment by simplesprite** [comment]
> > 同样的订阅地址 IOS 的 kitsunebi 可以, 但是 Mac os 的就是不行
> 
> 你应该用的是v2rayU, 这个更新出错了，你需要更新v2rayU到最新版本

已经更新到最新版本了 还是重新下载更新的最新版本！

**Comment by simplesprite** [comment]
> > > 更新最新的版本，重装就好了
> > 
> > 
> > 試過了也不行！！！！
> 
> 我的意思是更新v2rayU 到最新版本

「你已有最新版本！V2rayU 3.0.0.preview 已是目前最新的版本。」

**Comment by young40** [comment]
@simplesprite 

别用预览版，用最新的2.3.1就可以了。

https://github.com/yanue/V2rayU/releases/tag/2.3.1

**Comment by lolstudio** [comment]
> @simplesprite
> 
> 别用预览版，用最新的2.3.1就可以了。
> 
> https://github.com/yanue/V2rayU/releases/tag/2.3.1

也不行，so sad
