### ISSUE TITLE
pac 是生效的，电脑休眠后，再换新，pac失效，需turn off再turn on

### ISSUE THREAD

**Issue by markvlenvision** [yanue/V2rayU#767]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1)  V2RayU  V2rayU 3.0.0.preview 和 Mac 10.15.7

2) bug描述：pac 是生效的，电脑休眠后，再换新，pac失效，需turn off再turn on

3) 跟配置没关系，pac都生效了

**Comment by AriaLyy** [comment]
+ 1 我也有这个问题
