### ISSUE TITLE
我是第一次用，请问是否有快捷键？

### ISSUE THREAD

**Issue by smart-z** [yanue/V2rayU#77]
有些时候一些情况会用到。

比如要**开关代理；**
要**切换代理的模式**；

这两个对我是刚需，很抱歉我没有找到相关快捷键的设置地方。如果没有的话，感觉可以加个功能。

![QQ20190916-210930](https://user-images.githubusercontent.com/1166675/64964684-1f35e880-d8ce-11e9-9171-75c744d51941.png)

**Comment by yanue** [comment]
近期更新

**Comment by smart-z** [comment]
> 近期更新

😘 亲，催单快捷键，排上队了么～

**Comment by tobemaster56** [comment]
想要有的功能：
1、全局快捷键的功能
2、在切换代理模式的时候，menu bar 的图标有些变化，可以有颜色上的变化，或者，图标旁边加个字母，M（代表手动模式），G（全局模式），P（pac模式）

**Comment by tobemaster56** [comment]
今天，收到更新了，1.5.1中已经实现了这个功能：
在切换代理模式的时候，menu bar 的图标有些变化，可以有颜色上的变化，或者，图标旁边加个字母，M（代表手动模式），G（全局模式），P（pac模式）

非常感谢

快捷键的功能也是刚需，希望能尽快见到，再次感谢开发者

1、全局快捷键的功能（代理开关，切换代理模式）

**Comment by smart-z** [comment]
> 今天，收到更新了，1.5.1中已经实现了这个功能：
> 在切换代理模式的时候，menu bar 的图标有些变化，可以有颜色上的变化，或者，图标旁边加个字母，M（代表手动模式），G（全局模式），P（pac模式）
> 
> 非常感谢
> 
> 快捷键的功能也是刚需，希望能尽快见到，再次感谢开发者
> 
> 1、全局快捷键的功能（代理开关，切换代理模式）

就加了图标指示器，并没有更新快捷键

**Comment by uqix** [comment]
@yanue  It would be nice to have a shortcut  to switch to the next node of the current node in the server list

**Comment by yanue** [comment]
功能已加,请下载2.0.0

**Comment by smart-z** [comment]
> 功能已加,请下载2.0.0

感谢老板
