### ISSUE TITLE
更新至MacOS Big Sur后，开启app无法连接

### ISSUE THREAD

**Issue by lge6** [yanue/V2rayU#771]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
Mac版本：MacOS  Big Sur PB 11.0.1
V2rayU版本：2.3.1和3.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
更新至big sur后无法连接，PAC和全局模式都不行。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1087 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1087 > v2ray.com/core/transport/internet/tcp: failed to listen TCP on127.0.0.1:1087 > listen tcp 127.0.0.1:1087: bind: address already in use
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by wjling** [comment]
I'm not the only one!

**Comment by lge6** [comment]
解决方案是，换个htttp的端口，然后在换回去就好了。之前连不上的时候lsof也看不到，估计是个BUG？

**Comment by terry39** [comment]
我在新的 big sur上，无法打开，菜单栏没有图标，docker没有显示已运行，没有任何反应

**Comment by TokisakiYuu** [comment]
我有相同的问题，开启代理之后http代理端口没有监听，lsof看不到，macos big sur 11.4

**Comment by babyofsnake** [comment]
通过下面方式查看端口被谁占用：
lsof -i :1087
我的是被 v2ray占用
https://stackoverflow.com/questions/61071189/why-does-privoxy-constantly-listen-1087-port-after-updating-macos

**Comment by wuyunyian** [comment]
无论是更换软件版本还是换http端口，我的v2rayU都无法连接网络。查看日志
2021/07/09 07:36:52 127.0.0.1:63271 accepted //beacons5.gvt2.com:443 [proxy]
2021/07/09 07:36:52 [Info] [1766974837] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:149.248.39.194:443
2021/07/09 07:36:52 [Info] [1766974837] v2ray.com/core/proxy/vless/outbound: tunneling request to tcp:beacons5.gvt2.com:443 via tcp:XXX.XXX.XX.XXX:443
2021/07/09 07:36:52 [Info] [1766974837] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > read tcp XX.XXX.XXX.XXX:63272->XXX.XXX.XX.XXX:443: read: connection reset by peer
2021/07/09 07:36:52 [Info] [1766974837] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
