### ISSUE TITLE
【安全性问题】pac监听端口设置

### ISSUE THREAD

**Issue by b14ckK** [yanue/V2rayU#775]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU 2.3.1  Mac10.15.3 
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
pac监听端口配置，默认如下
tcp46      0      0  *.11085                *.*                    LISTEN

监听的路径如下：
ls /Applications/V2rayU.app/Contents/Resources/
AppIcon.icns  Assets.car    Base.lproj    V2rayUHelper  V2rayUTool    cmd.sh        config.json   en.lproj      pac           unzip.sh      v2ray-core    zh-HK.lproj   zh-Hans.lproj

主要是在这个目录下有config.json，会导致同一局域网可以直接获取到config.json信息，拿到对应的配置。

希望可以增加pac对应的host配置，默认127.0.0.1。或者修改文件位置

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

无
4)  请附上出错时软件输出的错误日志。

无
请预览一下你填的内容再提交。

**Comment by jiangzhuolin** [comment]
我试了一下，确实同一局域网直接能访问到指定 IP 的 pac 配置信息。

我觉得你可以使用 gfwlist.txt 基本上已经覆盖了绝大部分网站了，如果你确实有自己隐私的网址，临时的方案是你可以先对 11085 设置一个防火墙规则。

另外，我觉得你可以提交一个 PR 的～
