### ISSUE TITLE
请问 软件会支持最新的ARM版MacBook么？

### ISSUE THREAD

**Issue by twm17** [yanue/V2rayU#777]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by neciszhang** [comment]
你先买了，看看支不支持

**Comment by chfanghr** [comment]
好像要等明年二月golang工具链发布 [ref](https://github.com/golang/go/issues/38485)

**Comment by Sousukes** [comment]
> 你先买了，看看支不支持

我买了，不支持，打开后翻不出来，旧mac可以

**Comment by twm17** [comment]
> > 你先买了，看看支不支持
> 
> 我买了，不支持，打开后翻不出来，旧mac可以

其他软件都不重要，有梯子可用，是更换新设备的唯一诉求。听说M1 可以直接跑iOS app，那能直接用小火箭翻么？

**Comment by dr1llc4t** [comment]
> > > 你先买了，看看支不支持
> > 
> > 
> > 我买了，不支持，打开后翻不出来，旧mac可以
> 
> 其他软件都不重要，有梯子可用，是更换新设备的唯一诉求。听说M1 可以直接跑iOS app，那能直接用小火箭翻么？

买个surge不就得了，商业软件，肯定会支持m1

**Comment by twm17** [comment]
> > > > 你先买了，看看支不支持
> > > 
> > > 
> > > 我买了，不支持，打开后翻不出来，旧mac可以
> > 
> > 
> > 其他软件都不重要，有梯子可用，是更换新设备的唯一诉求。听说M1 可以直接跑iOS app，那能直接用小火箭翻么？
> 
> 买个surge不就得了，商业软件，肯定会支持m1

surge作者已经回复 是可以用的

**Comment by dr1llc4t** [comment]
> > > > > 你先买了，看看支不支持
> > > > 
> > > > 
> > > > 我买了，不支持，打开后翻不出来，旧mac可以
> > > 
> > > 
> > > 其他软件都不重要，有梯子可用，是更换新设备的唯一诉求。听说M1 可以直接跑iOS app，那能直接用小火箭翻么？
> > 
> > 
> > 买个surge不就得了，商业软件，肯定会支持m1
> 
> surge作者已经回复 是可以用的

rosetta转义的吧，原生应该还没支持

**Comment by arthasgxy** [comment]
> > 你先买了，看看支不支持
> 
> 我买了，不支持，打开后翻不出来，旧mac可以

https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ffa3c338a-a6b9-43b4-9d1f-886c4325255f%2FWX20201205-1452582x.png?table=block&id=26bfd0fe-e464-43e0-87e8-af5880cedfbe&width=2880&userId=&cache=v2

不需要做任何特殊设置，跟其他mac一样直接安装上把v2ray配置拿过来就能用。
请问骗我对你有什么好处？

**Comment by Sousukes** [comment]
> > > 你先买了，看看支不支持
> > 
> > 
> > 我买了，不支持，打开后翻不出来，旧mac可以
> 
> https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ffa3c338a-a6b9-43b4-9d1f-886c4325255f%2FWX20201205-1452582x.png?table=block&id=26bfd0fe-e464-43e0-87e8-af5880cedfbe&width=2880&userId=&cache=v2
> 
> 不需要做任何特殊设置，跟其他mac一样直接安装上把v2ray配置拿过来就能用。
> 请问骗我对你有什么好处？

？？？可我的新Mac确实出不去

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
