### ISSUE TITLE
删库了？

### ISSUE THREAD

**Issue by dakezuo** [yanue/V2rayU#778]

**Comment by young40** [comment]
哈哈，你需要一双发现美的👀

**Comment by dakezuo** [comment]
> 哈哈，你需要一双发现美的👀
@young40 带我飞

**Comment by iSteveyang** [comment]
请不要随便加BUG标签

**Comment by dakezuo** [comment]
> 请不要随便加BUG标签
@iSteveyang 
是自己加上去的，不是我手动加的

**Comment by iSteveyang** [comment]
> 请不要随便加BUG标签
> @iSteveyang
> 是自己加上去的，不是我手动加的

@dakezuo dakezuo added the bug  label 2 days ago
请自行学习如何使用GitHub

**Comment by dakezuo** [comment]
> > 请不要随便加BUG标签
> > @iSteveyang
> > 是自己加上去的，不是我手动加的
> 
> @dakezuo dakezuo added the bug label 2 days ago
> 请自行学习如何使用GitHub

杠精？

**Comment by iSteveyang** [comment]
> > > 请不要随便加BUG标签
> > > @iSteveyang
> > > 是自己加上去的，不是我手动加的
> > 
> > 
> > @dakezuo dakezuo added the bug label 2 days ago
> > 请自行学习如何使用GitHub
> 
> 杠精？

不诚实还抵赖？真当GitHub是贴吧，微博？

**Comment by dakezuo** [comment]
> > > > 请不要随便加BUG标签
> > > > @iSteveyang
> > > > 是自己加上去的，不是我手动加的
> > > 
> > > 
> > > @dakezuo dakezuo added the bug label 2 days ago
> > > 请自行学习如何使用GitHub
> > 
> > 
> > 杠精？
> 
> 不诚实还抵赖？真当GitHub是贴吧，微博？

您可真有意思，我全删了只打一句话就是这样，如果我操作不对，我认了，但是我也没权限改啊，我都说了是他后来自己加上去的，你不信，不信就算了你有能耐你去帮我改掉啊，我谢谢您，啥都不干就跟我在这对线，我要是能改能删了重来我会不弄？再说了我只是问下是不是删库了想让作者回复下而已，您跳的这么欢我可真是谢谢您咧，可真有意思

**Comment by yxjff** [comment]
请问怎么下载不到了

**Comment by com-wushuang** [comment]
注意看下分支啊！

**Comment by shaohui-wang** [comment]
改下分支就看见了
