### ISSUE TITLE
v2rayu需要键入密码才能切换模式

### ISSUE THREAD

**Issue by fallinsky** [yanue/V2rayU#779]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
v2rayu 2.3.1版本
mac 10.15.7版本

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
每次切换服务器，切换模式，都会弹框提示“v2rayu正在尝试修改网络配置”，需要键入密码才能继续进行。
太频繁了，有点恼人，请问怎么解决。

```

请预览一下你填的内容再提交。

**Comment by Catchen-coder** [comment]
我也遇到这个问题了，每次操作都需要使用密码。

**Comment by frankdqsc** [comment]
我现在还有这个问题。。。
