### ISSUE TITLE
1.3.1 无法自动设置代理

### ISSUE THREAD

**Issue by pzxiaoyi** [yanue/V2rayU#78]
没有自动在系统偏好设置-网络-代理，没有设置代理，无法使用。

**Comment by yanue** [comment]
手动执行一下命令,然后截图看下:
`
cd /Applications/V2rayU.app/Contents/Resources/
./V2rayUTool
`

**Comment by yanue** [comment]
有反馈是这样的 看看是不是同样的问题 
![image](https://user-images.githubusercontent.com/1435250/58761026-e6b60d00-8571-11e9-9fb9-6ee33f464cf0.png)

**Comment by pzxiaoyi** [comment]
是的，和截图所示一模一样。

**Comment by WardLiu** [comment]
我也有这个问题!

**Comment by yanue** [comment]
下载这个: https://support.apple.com/kb/DL1998?locale=en_US ,然后试下

**Comment by gaoliang** [comment]
一样的问题

**Comment by yanue** [comment]
已修复，请下载1.3.2使用
