### ISSUE TITLE
似乎direct/freedom和block/blackhole这两个OutboundConfiguration在设置Routing时不会自动添加

### ISSUE THREAD

**Issue by Dr-Bluemond** [yanue/V2rayU#780]
1) 你正在使用的 V2RayU 和 Mac 版本 ？

3.0.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

之前写入配置时是直接写的json，没带direct/freedom和block/blackhole这两个OutboundConfiguration。
使用GUI设置了Routing之后routing项自动填好了，但是希望如果能自动补上direct/freedom和block/blackhole这两项会更好一点。

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
