### ISSUE TITLE
mac os 状态栏不显示图标

### ISSUE THREAD

**Issue by mirifem** [yanue/V2rayU#787]
单用户，近几个月都不显示图标。致使无法进行任何设置。
系统升级到10.15.7，v2rayU 3.0版，故障依旧。
好在还能用，就是不能更新服务器，不能更新订阅了。

**Comment by mirifem** [comment]
关机重启休眠都不影响使用，任何情况下运行程序，图标会在状态栏一闪，瞬间消失。

**Comment by Jv0id** [comment]
我也遇到了，3.0，我准备换旧版本暂时用了。

**Comment by wm2zfei** [comment]
同样的问题……

**Comment by lysoul147** [comment]
我也是，11.0.1系统，还是用的2.3.1版本

**Comment by dee1024** [comment]
遇到一样的问题，目前无解~

**Comment by GE2Graf19186** [comment]
+1
况且我打算删除重装后,断网了(内外网都断),互联网显示链接正常,就是无法上网
显示:无法连接到服务器(wlan正常,链接正常)
关机多次无效
重装多次之后图标依旧不能显示
后来删除了所以有关文件夹才可以正常上网(内)
外网用了clash才好
