### ISSUE TITLE
3.0预览版更新以后会图标消失，并且再次打开后图标一闪又不见了……

### ISSUE THREAD

**Issue by wm2zfei** [yanue/V2rayU#792]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
Mac版 Big sur
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
一更新就崩溃，图标消失，就算强制关闭进程再打开也依然无法再看见图标。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
 iMac 19，2 
4)  请附上出错时软件输出的错误日志。
 没有日志输出，图标直接消失了

请预览一下你填的内容再提交。

**Comment by wm2zfei** [comment]
没有任何回应吗？？？？

**Comment by FuncTime** [comment]
遇到了,添加了一个订阅之后 就打不开了
