### ISSUE TITLE
无法打开“V2rayU”，因为Apple无法检查其是否包含恶意软件。

### ISSUE THREAD

**Issue by lovewmf** [yanue/V2rayU#795]
无法打开“V2rayU”，因为Apple无法检查其是否包含恶意软件。系统版本Big sur

**Comment by Eminlin** [comment]
系统偏好设置 -> 安全性隐私 -> 通用-> 允许打开即可。

**Comment by Eminlin** [comment]
> 系统偏好设置 -> 安全性隐私 -> 通用-> 允许打开即可。

这真不算 bug...
