### ISSUE TITLE
MacOS Big Sur 11.0.1 版本使用的V2rayU 2.3.1  cpu占用过高 ,一直占用50%左右 

### ISSUE THREAD

**Issue by zhangjiadong** [yanue/V2rayU#796]
![image](https://user-images.githubusercontent.com/8967343/101895869-10c6a180-3be3-11eb-956f-8509c09052e3.png)

**Comment by Loyea** [comment]
我也有这个问题，在能耗一栏里面，v2rayU对能耗的影响会维持在100左右。偶尔会出现这个问题，风扇起飞

**Comment by zhangjiadong** [comment]
> 我也有这个问题，在能耗一栏里面，v2rayU对能耗的影响会维持在100左右。偶尔会出现这个问题，风扇起飞

 咱俩差不多 我也是偶尔出现

**Comment by henryswisvip** [comment]
更新最新版本？作者之前好像解决了这个问题建议升级到2.3.1

**Comment by henryswisvip** [comment]
v2ray重启就行了

**Comment by zhangjiadong** [comment]
> v2ray重启就行了

这个问题出现太频繁了，老是重启也很麻烦

**Comment by summerKK** [comment]
我的也有这个问题

**Comment by Achrou** [comment]
复议

**Comment by guojiang43** [comment]
出现了相同问题，还希望大佬能解决一下呀

**Comment by fengfumin** [comment]
同感，大概一星期出现一次，进程暂用100，cpu风扇就起飞

**Comment by wanqi87** [comment]
复议，不过我的系统版本是11.2.3了
