### ISSUE TITLE
源码编译失败，提示/V2rayU-master/Build/v2ray-core: No such file or directory 两个文件丢失

### ISSUE THREAD

**Issue by lil-hope** [yanue/V2rayU#799]
<img width="155" alt="WX20201218-171439@2x" src="https://user-images.githubusercontent.com/15794187/102596724-8dfa9500-4154-11eb-91d0-69a5eb3b4dd5.png">

**Comment by banwang811** [comment]
怎么解决的呢

**Comment by newfuture33** [comment]
How to fix this problem?

**Comment by yanue** [comment]
看master的readme

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by banwang811** [comment]
> 

在readme里面说了要下载最新版v2ray-core，解压到Build目录,重命名为v2ray-core
