### ISSUE TITLE
ssr用不了啊

### ISSUE THREAD

**Issue by ApocaIypse** [yanue/V2rayU#80]
用v2ray地址添加的服务器可以正常使用，但是用ssr地址添加的服务器就用不了了

<img width="1440" alt="屏幕快照 2019-06-02 22 57 46" src="https://user-images.githubusercontent.com/51293434/58763174-1b35c300-858a-11e9-8eb5-255e0db12fe2.png">

**Comment by yanue** [comment]
是手动添加还是导入的,可以通过导入试下

**Comment by ApocaIypse** [comment]
> 是手动添加还是导入的,可以通过导入试下

用订阅添加的

**Comment by xiaomozhang** [comment]
> > 是手动添加还是导入的,可以通过导入试下
> 
> 用订阅添加的

我也遇到了同样的问题,求解~~

**Comment by yanue** [comment]
有可能是cipher method的问题 ,官方只支持那么多,这边补齐了,不一定有用.请下载1.3.3试下
