### ISSUE TITLE
V2ray config not found

### ISSUE THREAD

**Issue by zhugewala** [yanue/V2rayU#804]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
  2.3.1 / 10.14.6 

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
Turn on 时总是提示V2ray config not found，可是我已经按照帖子里的方法下载替换了最新的code上去，也更新了订阅设置，但还是不行，服务器列表也是空的，不知道哪里出问题了。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
https://ghelper.me/rss/2508aff0894da576604fdb1e9b9dfe57

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。
完了我只是一个普通的ghelper用户，完全不懂代码，应该找谁。

**Comment by ryuuixx** [comment]
Mac OS11.1，2.3.1版本，一直显示v2ray config not found，更新了订阅地址，卸载重装都不行
