### ISSUE TITLE
自定义配置的端口会被默认的443覆盖

### ISSUE THREAD

**Issue by cpfwmsx** [yanue/V2rayU#810]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
目前v2rayu最新版3.0.0 ，osx使用的10.14.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
配置服务器后，点击保存提示成功，也可以正常使用，下次再来到服务器编辑页面，端口会被修改成443，实际上我的端口是23823，非默认443

**Comment by xiec1** [comment]
碰到同样的问题

**Comment by jonise92** [comment]
+1

**Comment by xiec1** [comment]
回退老版本2.3.1没这个问题

**Comment by Coreat** [comment]
我也遇到一样的问题，MacOS 11.1, M1 Macbook Air，彻底卸载3.0回退到2.3.1后问题消失

**Comment by doutuo** [comment]
> 我也遇到一样的问题，MacOS 11.1, M1 Macbook Air，彻底卸载3.0回退到2.3.1后问题消失

现在安装2.3.1 可以直接装还是会提示损坏，要输入两段命令修复 ？

**Comment by Coreat** [comment]
> > 我也遇到一样的问题，MacOS 11.1, M1 Macbook Air，彻底卸载3.0回退到2.3.1后问题消失
> 
> 现在安装2.3.1 可以直接装还是会提示损坏，要输入两段命令修复 ？

我没有遇到过损坏的问题，直接安装的

**Comment by henrywithu** [comment]
3.0版本，同樣問題+1

**Comment by soul-yun** [comment]
这两天也碰到同样问题

**Comment by vpps2020** [comment]
同样的问题，求解决方案！

**Comment by V2beach** [comment]
同样的问题，我选择放弃v2rayU。
