### ISSUE TITLE
程序内存和cpu占用超高，风扇狂转温度极高

### ISSUE THREAD

**Issue by guojiang43** [yanue/V2rayU#813]
1) MAC版本：bigsurr11.2 Beta版(20D5042d)，16寸pro 2.6 GHz 六核Intel Core i7
V2RAY：V2rayU 2.3.1 

2) 程序内存和cpu占用超高，风扇狂转温度极高

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "none",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {手动删除部分
              }
            ],
            "port": 5480
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}4)  请附上出错时软件输出的错误日志。
2021/01/21 21:27:26 [Warning] [1686099197] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 8.8.8.8:8888: i/o timeout dial tcp 8.8.8.8:8888: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/21 21:27:40 [Info] [1485149091] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:27:56 [Info] [1485149091] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:28:12 [Info] [1485149091] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:28:25 [Info] [1485149091] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2021/01/21 21:28:25 [Info] [1485149091] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:28:26 [Warning] [1485149091] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 8.8.8.8:8888: i/o timeout dial tcp 8.8.8.8:8888: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/21 21:28:32 [Info] [2808456020] v2ray.com/core/proxy/socks: TCP Connect request to tcp:apidata.googleusercontent.com:443
2021/01/21 21:28:32 [Info] [2808456020] v2ray.com/core/app/dispatcher: default route for tcp:apidata.googleusercontent.com:443
2021/01/21 21:28:32 [Info] [2808456020] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:28:32 tcp:127.0.0.1:64185 accepted tcp:apidata.googleusercontent.com:443 [proxy] 
2021/01/21 21:28:48 [Info] [2808456020] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:29:05 [Info] [2808456020] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:29:21 [Info] [2808456020] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:29:38 [Info] [2808456020] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:8.8.8.8:8888
2021/01/21 21:29:55 [Warning] [2808456020] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 8.8.8.8:8888: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/21 21:29:55 [Info] [2808456020] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 darwin/amd64)
A unified platform for anti-censorship.

请预览一下你填的内容再提交。

**Comment by ioudove** [comment]
MacBook pro catalina 10.15.7 同样的问题。cpu 100%，风扇狂转，退出程序，重新启动就好了。
