### ISSUE TITLE
就是没法开。。。

### ISSUE THREAD

**Issue by DarthMikuH** [yanue/V2rayU#817]
<img width="1280" alt="截屏2021-02-01 下午9 28 04" src="https://user-images.githubusercontent.com/62818311/106465008-5feacd80-64d4-11eb-83f8-a27755347fd5.png">
<img width="1280" alt="截屏2021-02-01 下午9 28 13" src="https://user-images.githubusercontent.com/62818311/106465028-64af8180-64d4-11eb-9870-b9f5705d0ac1.png">
<img width="1280" alt="截屏2021-02-01 下午9 29 22" src="https://user-images.githubusercontent.com/62818311/106465166-8f99d580-64d4-11eb-83dd-e4fc8a656a6e.png">

**Comment by JunJieYa** [comment]
我也遇到了这个问题
