### ISSUE TITLE
总是过一段时间就连接不了了，不知道为啥

### ISSUE THREAD

**Issue by zhangdongxiao** [yanue/V2rayU#82]
对应的debug级别的日志

your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [2108328210] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [368420264] v2ray.com/core/proxy/socks: TCP Connect request to tcp:lh3.googleusercontent.com:443
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [3718853788] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [3718853788] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/06/03 16:31:58 [Info] [3718853788] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [2108328210] v2ray.com/core/app/dispatcher: default route for tcp:www.gstatic.com:443
2019/06/03 16:31:58 [Info] [2108328210] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [368420264] v2ray.com/core/app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
2019/06/03 16:31:58 [Info] [368420264] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [3171499261] v2ray.com/core/proxy/socks: TCP Connect request to tcp:apis.google.com:443
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [3171499261] v2ray.com/core/app/dispatcher: default route for tcp:apis.google.com:443
2019/06/03 16:31:58 [Info] [3171499261] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 tcp:127.0.0.1:50775 accepted tcp:www.gstatic.com:443 
2019/06/03 16:31:58 tcp:127.0.0.1:50774 accepted tcp:lh3.googleusercontent.com:443 
2019/06/03 16:31:58 tcp:127.0.0.1:50773 accepted tcp:www.google.com:443 
2019/06/03 16:31:58 tcp:127.0.0.1:50776 accepted tcp:apis.google.com:443 
2019/06/03 16:31:58 [Info] [2108328210] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [3718853788] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [368420264] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:lh3.googleusercontent.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [3171499261] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:apis.google.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:58 [Info] [3718853788] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:31:58 [Info] [2108328210] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:31:58 [Info] [2108328210] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/06/03 16:31:58 [Info] [368420264] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:31:58 [Info] [368420264] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/06/03 16:31:58 [Info] [3718853788] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/06/03 16:31:58 [Info] [3171499261] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:31:58 [Info] [3171499261] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [2415950632] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:31:58 [Info] [2415950632] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/06/03 16:31:58 tcp:127.0.0.1:50781 accepted tcp:www.google.com:443 
2019/06/03 16:31:58 [Info] [2415950632] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:59 [Info] [2415950632] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:31:59 [Info] [2415950632] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:31:59 [Info] [2415950632] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/06/03 16:32:03 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:32:03 [Info] [2357415811] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients2.google.com:443
2019/06/03 16:32:03 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:32:03 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:32:03 [Info] [2357415811] v2ray.com/core/app/dispatcher: default route for tcp:clients2.google.com:443
2019/06/03 16:32:03 [Info] [2357415811] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:32:03 tcp:127.0.0.1:50785 accepted tcp:clients2.google.com:443 
2019/06/03 16:32:03 [Info] [2357415811] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients2.google.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:32:04 [Info] [2357415811] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:32:04 [Info] [2357415811] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/06/03 16:32:04 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:32:04 [Info] [4089487001] v2ray.com/core/proxy/socks: TCP Connect request to tcp:clients2.google.com:443
2019/06/03 16:32:04 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:32:04 [Info] v2ray.com/core/features: You are using a deprecated feature: Socks timeout. Please update your config file with latest configuration format, or update your client software.
2019/06/03 16:32:04 [Info] [4089487001] v2ray.com/core/app/dispatcher: default route for tcp:clients2.google.com:443
2019/06/03 16:32:04 [Info] [4089487001] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:32:04 tcp:127.0.0.1:50788 accepted tcp:clients2.google.com:443 
2019/06/03 16:32:04 [Info] [4089487001] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients2.google.com:443 via tcp:tw9-1.kkworld.xyz:8300
2019/06/03 16:32:04 [Info] [4089487001] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/06/03 16:32:04 [Info] [4089487001] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by yanue** [comment]
这个应该是v2ray那边的原因了

**Comment by zhangdongxiao** [comment]
对应的v2ray的日志是不是也是通过这个日志来看的  我把v2ray对应的日志发给他们看看

**Comment by yanue** [comment]
这个都是v2ray的日志 v2rayu的日志在系统里面

**Comment by zhangdongxiao** [comment]
好的 谢谢  那我把这个日志发给他们
