### ISSUE TITLE
V2RayU 3.0.1 无法进行科学上网

### ISSUE THREAD

**Issue by yingjun-skr** [yanue/V2rayU#823]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
正在使用的是V2RayU 3.0.1版本和MacOs Big sur 11.2
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法进行科学上网

**Comment by yingjun-skr** [comment]
麻烦大佬解决下

**Comment by mimikong** [comment]
同样问题，换回2.3.1就可以了，大佬解决下吧~
M1 macbook air
11.2

**Comment by yanue** [comment]
1. 先turn v2ray-core off在turn v2ray-core on试下
2. 看下日志是否类似:
```
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 darwin/amd64)
A unified platform for anti-censorship.
2021/02/06 14:44:38 [Info] v2ray.com/core/main/jsonem: Reading config: config.json
2021/02/06 14:44:38 [Debug] v2ray.com/core/app/log: Logger started
2021/02/06 14:44:38 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2021/02/06 14:44:38 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1080
2021/02/06 14:44:38 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1087
2021/02/06 14:44:38 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/02/06 14:44:38 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1080
2021/02/06 14:44:38 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2021/02/06 14:44:38 [Warning] v2ray.com/core: V2Ray 4.34.0 started
```
3. 命令行,看下文件是否正确 
``` 
ls ~/.V2rayU/
```
4. 命令行,看下是否正常launch
```
launchctl list| grep v2ray
# 尝试手动启动试下
launchctl start yanue.v2rayu.v2ray-core
```

**Comment by Panway** [comment]
同无法使用，而且3.0.1 点击`查看v2ray日志`立马闪退

**Comment by yingjun-skr** [comment]
无法查看日志 点击日志 直接闪退

**Comment by peiqianggao** [comment]
> 同无法使用，而且3.0.1 点击`查看v2ray日志`立马闪退

+1

**Comment by sqzhang-jeremy** [comment]
M1 MacOS Big Sur 11.1
View V2ray 打开日志闪退

**Comment by sqzhang-jeremy** [comment]
> > 同无法使用，而且3.0.1 点击`查看v2ray日志`立马闪退
> 
> +1
> 回退到 3.0.0.preview 版本可以正常使用

确实如此，回退到 3.0.0.preview 版本可以正常使用

**Comment by edward852** [comment]
查看v2ray日志闪退，崩溃日志显示：
`Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“v2ray-core.log”存储到文件夹“.V2rayU”中的权限。"`

**Comment by edward852** [comment]
1. 到日志目录查看v2ray-core.log类似，没看到报错
```
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 darwin/amd64)
A unified platform for anti-censorship.
2021/02/06 15:37:47 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /Applications/V2rayU.app/Contents/Resources/config.json
2021/02/06 15:37:47 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2021/02/06 15:37:47 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/02/06 15:37:47 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1080
2021/02/06 15:37:47 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 192.168.50.20:1081
2021/02/06 15:37:47 [Warning] v2ray.com/core: V2Ray 4.31.0 started
```
2. `~/.V2rayU/` 存在
3.  `launchctl start yanue.v2rayu.v2ray-core` 没效果。 stop了再start也没效果。

**Comment by LSauce** [comment]
M1 MacOS Big Sur 11.1
不能直接覆盖安装，操作后会直接闪退，要先全部卸载，然后在重新安装就好了

**Comment by edward852** [comment]
@yanue 可能和 `.V2rayU` 的访问权限有关，我手动添加权限后正常了。可能程序需要请求用户授权访问 `.V2rayU` 目录。

**Comment by sakuyazh** [comment]
> @yanue 可能和 `.V2rayU` 的访问权限有关，我手动添加权限后正常了。可能程序需要请求用户授权访问 `.V2rayU` 目录。

手动添加权限虽然可以正常启动服务但是切换节点，打开退出的时候都会频繁的提示 V2ray正在尝试修改系统网络配置，每次都得输密码 @yanue

**Comment by LuvTian** [comment]
3.0.1无法使用，点击“查看v2ray日志”就闪退，我的系统环境是mac10.13.6
3.0.1在发布之前没有经过测试吗？

**Comment by jackielg** [comment]
同样无法使用v3.0.1。点查看log就闪退

**Comment by sakuyazh** [comment]
> > @yanue 可能和 `.V2rayU` 的访问权限有关，我手动添加权限后正常了。可能程序需要请求用户授权访问 `.V2rayU` 目录。
> 
> 手动添加权限虽然可以正常启动服务但是切换节点，打开退出的时候都会频繁的提示 V2ray正在尝试修改系统网络配置，每次都得输密码 @yanue

是我加权限的时候少了个s 加上就好了

**Comment by liujk189** [comment]
> > > @yanue 可能和 `.V2rayU` 的访问权限有关，我手动添加权限后正常了。可能程序需要请求用户授权访问 `.V2rayU` 目录。
> > 
> > 
> > 手动添加权限虽然可以正常启动服务但是切换节点，打开退出的时候都会频繁的提示 V2ray正在尝试修改系统网络配置，每次都得输密码 @yanue
> 
> 是我加权限的时候少了个s 加上就好了

请问具体如何操作?能不能具体说一下? 谢谢!

**Comment by sakuyazh** [comment]
> > > > @yanue 可能和 `.V2rayU` 的访问权限有关，我手动添加权限后正常了。可能程序需要请求用户授权访问 `.V2rayU` 目录。
> > > 
> > > 
> > > 手动添加权限虽然可以正常启动服务但是切换节点，打开退出的时候都会频繁的提示 V2ray正在尝试修改系统网络配置，每次都得输密码 @yanue
> > 
> > 
> > 是我加权限的时候少了个s 加上就好了
> 
> 请问具体如何操作?能不能具体说一下? 谢谢!

chmod -R +swxr ~/.V2rayU

**Comment by huangjihua** [comment]
Mac OS big Sur 版本 11.12.1 ,3.0.1无法使用，点击“查看v2ray日志”就闪退

**Comment by sd4324530** [comment]
你们 是怎么升级到3.0.0+版本的？

**Comment by edward852** [comment]
> 你们 是怎么升级到3.0.0+版本的？

之前有发布3.0.1版本，不能使用作者回滚了。3.0.0preview可以安装、正常使用。

**Comment by ZKzhangkun** [comment]
> 2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64) A unified platform for anti-censorship. V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64) A unified platform for anti-censorship. 2023/03/09 16:49:07 [Info] v2ray.com/core/common/platform/ctlcmd: v2ctl> Read config: /Applications/V2rayU.app/Contents/Resources/config.json 2023/03/09 16:49:07 [Info] v2ray.com/core/app/dns: DNS: created localhost client 2023/03/09 16:49:07 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1888 2023/03/09 16:49:07 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1777 2023/03/09 16:49:07 [Warning] v2ray.com/core: V2Ray 4.23.1 started
> 
> 查看日志感觉没问题 ，然后本机网络没有开任何代理 ，访问不了油管，怎么回事呀

mac mini m2  macOS Ventra 13.2.1   V2ray 2.3.0  之前下载最新的V2ray  也不行 ，手机上就能用
