### ISSUE TITLE
一直显示找不到config文件

### ISSUE THREAD

**Issue by WardLiu** [yanue/V2rayU#83]
![image](https://user-images.githubusercontent.com/39974957/58843869-ff740f00-86a6-11e9-9abc-12f69418b541.png)

**Comment by Leonscrt** [comment]
尝试修复磁盘权限

**Comment by evilvlso** [comment]
请问这个问题如何修复磁盘权限呢

**Comment by WardLiu** [comment]
同问 后面版本好像修复不了权限了鸭 (急救栏目里没有的)

**Comment by WardLiu** [comment]
请问这个问题有别的解决措施嘛 谢谢

**Comment by yanue** [comment]
试一下命令行:
```
cd /Applications/V2rayU.app/Contents/Resources/
sudo chmod -R 777 .
```

**Comment by ugvf2009** [comment]
![image](https://user-images.githubusercontent.com/2819436/60567196-cdd08f80-9d9b-11e9-93ac-78f7cc716b7f.png)
安装后的效果，读取不到config.json文件。
另外，每次更换配置服务器的时候，都会要求输入密码。

**Comment by ugvf2009** [comment]
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory
 这是Log

**Comment by WardLiu** [comment]
> V2Ray 4.19.1 (Let's Fly) Custom
> A unified platform for anti-censorship.
> main: failed to load config: config.json > v2ray.com/core/main/confloader/external: config file not readable > open config.json: no such file or directory
> 这是Log

你看下有没有把v2rayU加到访达--"应用程序" (Applications) 里

**Comment by ugvf2009** [comment]
感谢，添加到finder后，问题解决。

**Comment by loverain9999** [comment]
加到Applications 里了，还是不行，log相同。 
另外V2rayX 是不是不维护了？

**Comment by PicaJIN** [comment]
请问这个log文件在什么位置呀
