### ISSUE TITLE
V2RayU的app打不开

### ISSUE THREAD

**Issue by BlessFruit** [yanue/V2rayU#830]
最新版本，添加了个订阅地址，点更新，然后就看见app图标没了，去应用程序想重新打开app，始终打不开
尝试了卸载 重新安装，还是不行

**Comment by kissesu** [comment]
同样的问题。
macbookpro m1

**Comment by samgy66** [comment]
同样的问题，今天更新了订阅结果闪退了，再也打不开了

**Comment by eromoe** [comment]
你们解决了吗，我最新版还是双击打开没反应
