### ISSUE TITLE
如何配置 Trojan

### ISSUE THREAD

**Issue by Asingers** [yanue/V2rayU#836]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.0.0
2) 你遇到的问题是什么？
使用问题

新版中加入了torjan ，如何配置，求教。在手机端的小火箭配置是可以上网的。（只填写了地址、端口、密码，其他插件、混淆都为none）

**Comment by Octobug** [comment]
same

**Comment by gwhcn** [comment]
我也一样，Trojan 3.0.3只设置地址、端口、密码，无法上网
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 darwin/amd64)
A unified platform for anti-censorship.
2021/05/29 00:35:45 [Info] v2ray.com/core/main/jsonem: Reading config: config.json
main: failed to read config files: [config.json] > v2ray.com/core/infra/conf: 0 Trojan server configured.

**Comment by LeneSamils** [comment]
俺也一样

**Comment by JasonBtc** [comment]
俺也一样，设置地址、端口、密码 也无法上网

**Comment by LeneSamils** [comment]
> 俺也一样，设置地址、端口、密码 也无法上网

感觉也没啥可以设置的地方啊，等吧

**Comment by gwhcn** [comment]
暂时可以用clashX或者qr2ray

**Comment by LeneSamils** [comment]
> 暂时可以用clashX或者qr2ray

也只能如此了

**Comment by Octobug** [comment]
trojan 本身还是挺好用的，官方的命令行工具可以作为 server, 也可以作为 client: https://github.com/trojan-gfw/trojan/releases

另外由于这个工具只支持 socks5, 而很多命令行工具只支持 http proxy, 使用 macOS 的同学可以用 privoxy 将 socks5(trojan) 转换为 http 代理，给其他只支持 http 代理的命令行工具使用。

**Comment by zhonggithub** [comment]
same issues

**Comment by a186r** [comment]
same issues

**Comment by YoleYu** [comment]
2023年08月07日14:41:06  同样不行。但是通过本地代理，其他程序可以访问。浏览器无法访问
