### ISSUE TITLE
点击打开就奔溃

### ISSUE THREAD

**Issue by Andrew5** [yanue/V2rayU#837]
Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [91643]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   net.yanue.V2rayU              	0x0000000100c6d091 0x100c5f000 + 57489
1   net.yanue.V2rayU              	0x0000000100c6d0c8 0x100c5f000 + 57544
2   com.apple.CoreFoundation      	0x00007fff34862e45 -[NSSet makeObjectsPerformSelector:] + 231
3   com.apple.AppKit              	0x00007fff31abc8b7 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1485
4   com.apple.AppKit              	0x00007fff31ab06d1 loadNib + 401
5   com.apple.AppKit              	0x00007fff31aafc92 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 693
6   com.apple.AppKit              	0x00007fff31aaf8e8 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
7   com.apple.AppKit              	0x00007fff31aaf6c1 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 446
8   com.apple.AppKit              	0x00007fff31aa1286 NSApplicationMain + 505
9   net.yanue.V2rayU              	0x0000000100c62189 0x100c5f000 + 12681
10  libdyld.dylib                 	0x00007fff6e90ecc9 start + 1

Thread 1:: Dispatch queue: com.apple.root.background-qos
0   libsystem_kernel.dylib        	0x00007fff6ea563be __accept + 10
1   org.cocoapods.Swifter         	0x00000001012d6dc2 closure #1 in HttpServerIO.start(_:forceIPv4:priority:) + 306
2   org.cocoapods.Swifter         	0x00000001012d74d9 thunk for @escaping @callee_guaranteed () -> () + 25
3   libdispatch.dylib             	0x00007fff6e8b46c4 _dispatch_call_block_and_release + 12
4   libdispatch.dylib             	0x00007fff6e8b5658 _dispatch_client_callout + 8
5   libdispatch.dylib             	0x00007fff6e8c3aa8 _dispatch_root_queue_drain + 663
6   libdispatch.dylib             	0x00007fff6e8c4097 _dispatch_worker_thread2 + 92
7   libsystem_pthread.dylib       	0x00007fff6eb0f9f7 _pthread_wqthread + 220
8   libsystem_pthread.dylib       	0x00007fff6eb0eb77 start_wqthread + 15

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6eb0eb68 start_wqthread + 0

Thread 3:: Dispatch queue: com.apple.NSURLSession-work
0   com.apple.AppSSOCore          	0x00007fff479b20e0 DYLD-STUB$$dispatch_once + 0
1   com.apple.CFNetwork           	0x00007fff3322c64c 0x7fff3305a000 + 1910348
2   com.apple.CFNetwork           	0x00007fff3316a767 0x7fff3305a000 + 1116007
3   com.apple.CFNetwork           	0x00007fff330717d3 0x7fff3305a000 + 96211
4   com.apple.CFNetwork           	0x00007fff3312eb03 0x7fff3305a000 + 871171
5   com.apple.CFNetwork           	0x00007fff3312eba8 0x7fff3305a000 + 871336
6   com.apple.CFNetwork           	0x00007fff3307158c 0x7fff3305a000 + 95628
7   com.apple.CFNetwork           	0x00007fff3307060e 0x7fff3305a000 + 91662
8   com.apple.CFNetwork           	0x00007fff330704bf 0x7fff3305a000 + 91327
9   libdispatch.dylib             	0x00007fff6e8b46c4 _dispatch_call_block_and_release + 12
10  libdispatch.dylib             	0x00007fff6e8b5658 _dispatch_client_callout + 8
11  libdispatch.dylib             	0x00007fff6e8bac44 _dispatch_lane_serial_drain + 597
12  libdispatch.dylib             	0x00007fff6e8bb609 _dispatch_lane_invoke + 414
13  libdispatch.dylib             	0x00007fff6e8c4c09 _dispatch_workloop_worker_thread + 596
14  libsystem_pthread.dylib       	0x00007fff6eb0fa3d _pthread_wqthread + 290
15  libsystem_pthread.dylib       	0x00007fff6eb0eb77 start_wqthread + 15

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6eb0eb68 start_wqthread + 0

Thread 5:: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib        	0x00007fff6ea52882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eb13425 _pthread_cond_wait + 698
2   libc++.1.dylib                	0x00007fff6bbe1623 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
3   com.apple.JavaScriptCore      	0x00007fff3906fc35 bmalloc::Scavenger::threadRunLoop() + 741
4   com.apple.JavaScriptCore      	0x00007fff3906f649 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9
5   com.apple.JavaScriptCore      	0x00007fff39071d27 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 39
6   libsystem_pthread.dylib       	0x00007fff6eb13109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eb0eb8b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x00007ffeeefa0270  rcx: 0x0000000000000000  rdx: 0x0000000000000001
  rdi: 0x00007ffeeefa0270  rsi: 0xffffffff00000001  rbp: 0x00007ffeeefa0390  rsp: 0x00007ffeeefa0250
   r8: 0x0000000000000040   r9: 0x00007fff34ad83e0  r10: 0x00007fff8c2128b8  r11: 0x00007fff3480c377
  r12: 0x4000600003008340  r13: 0x00007ffeeefa0310  r14: 0x00007ffeeefa0310  r15: 0xc0000000000000b9
  rip: 0x0000000100c6d091  rfl: 0x0000000000010246  cr2: 0x0000000100ddd290
  
Logical CPU:     4
Error Code:      0x00000000
Trap Number:     6
  这个问题就算是重新安装也不会解决点击打开崩溃问题，我想问问该如何根治，我认为这个软件往系统里写入了一些文件，导致再次打开这个软件的时候会读取配置信息，因为上次的配置信息写入错误，所以就一直崩溃，我想问问这个配置信息写入到哪里了？其实也是想解决软件崩溃问题。

**Comment by Tonny-Gu** [comment]
可以试试删掉这两个文件
~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
~/Library/Preferences/net.yanue.V2rayU.plist

**Comment by rekcah1986** [comment]
> 可以试试删掉这两个文件
> ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> ~/Library/Preferences/net.yanue.V2rayU.plist

好使

**Comment by yann0917** [comment]
> 可以试试删掉这两个文件 ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist ~/Library/Preferences/net.yanue.V2rayU.plist

有效

**Comment by PPPeony** [comment]
> 可以试试删掉这两个文件
> ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> ~/Library/Preferences/net.yanue.V2rayU.plist

**Comment by PPPeony** [comment]
> 可以试试删掉这两个文件
> ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> ~/Library/Preferences/net.yanue.V2rayU.plist

我怎么删了又出来了，还是打不开😭

**Comment by wangqianxu6666** [comment]
> 

请问没有找到这俩文件呢
