### ISSUE TITLE
pac 模式下无法更新 Chrome

### ISSUE THREAD

**Issue by WinLinKer** [yanue/V2rayU#84]
官网查询了下，是说这两个域名，但是在 
tools.google.com
dl.google.com

http://127.0.0.1:1085/pac/pac.js
"@@||dl.google.com",
"@@||tools.google.com",

只有全局模式才能，有点困惑

**Comment by yanue** [comment]
pac模式能访问google吗, 更新chrome是通过浏览器自身下载更新吗

**Comment by WinLinKer** [comment]
> pac模式能访问google吗, 更新chrome是通过浏览器自身下载更新吗

可以访问 google

![image](https://user-images.githubusercontent.com/3109626/58853130-bc786280-86cb-11e9-8809-7b18c6354f7f.jpeg)

https://support.google.com/chrome/answer/111996?visit_id=636952225400259414-1443226338&p=update_error&rd=1
