### ISSUE TITLE
路由模式选择「绕过局域网和大陆地址」在「全局模式」下无法上网

### ISSUE THREAD

**Issue by f2sky** [yanue/V2rayU#841]
路由模式选择「绕过局域网和大陆地址」，代理模式选择「全局模式」无法上网，切换到「Pac模式」则可以上网。

<img width="460" alt="Snipaste210225110556" src="https://user-images.githubusercontent.com/8769077/109097116-b658ce00-7759-11eb-8132-cab2a7f305ef.png">

**Comment by 45gfg9** [comment]
我的版本3.0.2，域名策略`AsIs`，也出现了Global无法上网的问题
执行Release页面的脚本后正常，也许可以试一下？

**Comment by ZihengQin** [comment]
> 我的版本3.0.3，域名策略`AsIs`，也出现了Global无法上网的问题

问题同
