### ISSUE TITLE
正式版没有服务器测速选项

### ISSUE THREAD

**Issue by Anand-lyn** [yanue/V2rayU#842]
软件版本：3.0.2
Mac版本：10.15.7

问题：没有服务器测速选项
![image](https://user-images.githubusercontent.com/58105052/109412439-f7174800-79e2-11eb-9b96-194268bea796.png)

**Comment by bugaio** [comment]
+1

**Comment by demoNo** [comment]
+1

**Comment by popitin593** [comment]
+1

**Comment by ZihengQin** [comment]
+1

**Comment by qianshihua** [comment]
+1

**Comment by qianshihua** [comment]
+1

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
