### ISSUE TITLE
正式版 无法更新 pac文件，提示 无法写入

### ISSUE THREAD

**Issue by joyanhui** [yanue/V2rayU#843]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.0正式版 bigsur 11.2.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法更新 pac文件，提示 无法写入
换 3.0 预览版 没有问题。
另外正式版本 没有服务器测速。。
正式版的 在线更新 也会提示服务器操作

这个版本的正式版 有点不太正式哈

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by f2sky** [comment]
3.0预览版虽然bug一堆，但也还勉强能用，手动更新之后（检查更新都报错）直接不能用了，怎么调整都不行。
PC、安卓、iOS 其它各端正常使用，尤其是安卓端（v2rayNG）非常稳定，而且性能表现非常好。

**Comment by vinsonma** [comment]
同样遇到此问题

**Comment by oyyq99999** [comment]
这个应该是 #844 提到的问题导致的，但我修复以后会出现每次操作的时候都要输密码的情况

**Comment by vinsonma** [comment]
我已经解决了https://github.com/yanue/V2rayU/issues/845
