### ISSUE TITLE
3.0.2 没有~/.V2rayU权限不能正常工作

### ISSUE THREAD

**Issue by edward852** [yanue/V2rayU#844]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.0.2， mac 11.2.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
不能正常工作，跟回退的3.0.1现象一样
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
跟配置无关
4)  请附上出错时软件输出的错误日志。
详见 [issue823](https://github.com/yanue/V2rayU/issues/823#issuecomment-774422105)

**Comment by sunseago** [comment]
我也遇到不能正常运行的问题，不是服务器的原因，配置完全一样，换回预览版就可以正常工作

**Comment by yanue** [comment]
删除 ~/.V2rayU 目录重启u试下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sunseago <notifications@github.com>
发送时间: Monday, March 1, 2021 11:46:28 AM
收件人: yanue/V2rayU <V2rayU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [yanue/V2rayU] 3.0.2 没有~/.V2rayU权限不能正常工作 (#844)


我也遇到不能正常运行的问题，不是服务器的原因，配置完全一样，换回预览版就可以正常工作

―

**Comment by yanue** [comment]
之前安装过3.0.1一定要删除先

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yanue mi <yanue@outlook.com>
发送时间: Monday, March 1, 2021 11:48:06 AM
收件人: yanue/V2rayU <reply@reply.github.com>; yanue/V2rayU <V2rayU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [yanue/V2rayU] 3.0.2 没有~/.V2rayU权限不能正常工作 (#844)

删除 ~/.V2rayU 目录重启u试下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sunseago <notifications@github.com>
发送时间: Monday, March 1, 2021 11:46:28 AM
收件人: yanue/V2rayU <V2rayU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [yanue/V2rayU] 3.0.2 没有~/.V2rayU权限不能正常工作 (#844)


我也遇到不能正常运行的问题，不是服务器的原因，配置完全一样，换回预览版就可以正常工作

―

**Comment by edward852** [comment]
删除`~/.V2rayU`后重启正常了

**Comment by sunseago** [comment]
终端运行作者给的代码还是不能上网。
