### ISSUE TITLE
如何进行局域网共享连接?

### ISSUE THREAD

**Issue by WestKorean** [yanue/V2rayU#847]
设置里面 本机地址绑定里面我把绑定地址改成局域网地址就可以让其他主机连接代理, 但是想同时设置 127.0.0.1 和 局域网地址就不能使用了, 不知道是语法问题,还是没有这个功能

**Comment by edward852** [comment]
填0.0.0.0就可以了

**Comment by Jlif** [comment]
您好，请问这个软件支持跟电脑处于同一局域网的设备连接吗？我在网上搜看到好像ss有这个功能，允许局域网内的连接，这个软件在哪里设置呢

**Comment by romotc** [comment]
> 设置里面 本机地址绑定里面我把绑定地址改成局域网地址就可以让其他主机连接代理, 但是想同时设置 127.0.0.1 和 局域网地址就不能使用了, 不知道是语法问题,还是没有这个功能

貌似设置之后需要重启一下软件，要不然不会生效
