### ISSUE TITLE
建议增加xray-core支持，路由设置中建议增加除了"ip"与"domain"之外的选项。

### ISSUE THREAD

**Issue by lly007** [yanue/V2rayU#850]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU:3.0.3
macOS 11.2  MacBook Pro M1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
主要是提两方面的建议
第一方面，目前v2ray-core没有原生支持Apple Silicon，但是xray-core已经原生支持了Apple Silicon，并且xray-core还提供了一些其他特性，建议V2RayU增加支持。Windows平台的v2rayN与安卓平台的v2rayNG都已经增加了对xray-core的支持。实现应该比较简单，目前我直接把xray改名为v2ray并替换~/V2rayU/v2ray-core/v2ray，V2RayU就可以正常运行，说明xray的运行方法与v2ray-core完全一致。
https://github.com/XTLS/Xray-core
第二方面，建议在路由设置中增加除了"domain"和"ip"之外的其他设置，比如v2ray config里的"port"、"network"、"protocol"等。目前V2RayU只支持"domain"和"ip"，虽然我们可以手动修改config文件，但是V2RayU在启动后会按照自己的配置重新修改config。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
无
4)  请附上出错时软件输出的错误日志。
无

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
