### ISSUE TITLE
3.0.3版本还是无法导入vless链接

### ISSUE THREAD

**Issue by Elderkly** [yanue/V2rayU#851]
mac版本：Big Sur 11.2.1
V2RayU:3.0.3
![image](https://user-images.githubusercontent.com/32736776/110051570-191d1b80-7d91-11eb-917b-2d8659ee41bb.png)

![image](https://user-images.githubusercontent.com/32736776/110051613-263a0a80-7d91-11eb-824d-783cf7b1da9f.png)

**Comment by lawrence1751** [comment]
trojan同樣，沒有支援trojan的url格式

**Comment by Lionelpang** [comment]
估计是多了空格。

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0

**Comment by bug0error** [comment]
> 

3.2版本还是不支持trojan，不更新了吗
