### ISSUE TITLE
V2rayU始终打不开

### ISSUE THREAD

**Issue by jathena233** [yanue/V2rayU#852]
Mac air m1，第一次下载v2rayu后可以打开，url输入地址，添加并且更新后，软件闪退，之后就再也不能打开v2rayu了，点击就是闪烁几下没有反应。卸载重装也是这样，更新最新版本也是打不开...

**Comment by GE2Graf19186** [comment]
+1

**Comment by 90651698** [comment]
一样

**Comment by wxiaohe** [comment]
俺也一样

**Comment by Kun8018** [comment]
我的直接报错，说苹果不能检测是否安全，要开发者更新

**Comment by wxiaohe** [comment]
我目前的做法是完全卸载，然后重装已经不会出现这个问题了。

**Comment by Kun8018** [comment]
> 我目前的做法是完全卸载，然后重装已经不会出现这个问题了。

我在偏好设置了允许之后打开了，可以用

**Comment by tiny-andr** [comment]
我的M1 mac没遇到这问题 2333，不过每次修改配置都要输入电脑账户的密码，挺麻烦的。

**Comment by wxtt522** [comment]
俺也一样、重装后也没用

**Comment by In2013** [comment]
> > 我目前的做法是完全卸载，然后重装已经不会出现这个问题了。
> 
> 我在偏好设置了允许之后打开了，可以用

我允许之后双击没反应
