### ISSUE TITLE
正式版3.0.3，点击订阅设置，pac设置，偏好设置闪退

### ISSUE THREAD

**Issue by Cerrorr** [yanue/V2rayU#853]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
正式版3.0.3 MacBook Pro 13-inch, 2018 macOS11.2.2
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
点击订阅设置，pac设置，偏好设置闪退

**Comment by waitingyou** [comment]
正式版2.3.1添加订阅后重启电脑程序完全打不开
正式版3.0.3添加订阅后重启电脑点击订阅设置，pac设置，偏好设置闪退
MacBook Pro 2011 15-inch，MacOS10.15.6

**Comment by syq6688** [comment]
同样的问题

**Comment by dev4mobile** [comment]
same question

**Comment by dev4mobile** [comment]
remove config, it will done

**Comment by zhuziyi1989** [comment]
同样的问题。

**Comment by zhuziyi1989** [comment]
> remove config, it will done

无效。
This method doesn't work for me

**Comment by vipadm** [comment]
> 1. 你正在使用的 V2RayU 和 Mac 版本 ？
>    正式版3.0.3 MacBook Pro 13-inch, 2018 macOS11.2.2
> 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    点击订阅设置，pac设置，偏好设置闪退

按照  author  的方法完全卸载 

V2rayU彻底删除方法: (推荐使用AppCleaner)

https://github.com/yanue/V2rayU/blob/master/README.md#%E5%BD%BB%E5%BA%95%E5%8D%B8%E8%BD%BD

第一步: 卸载V2rayU.app
停止v2ray-core, 然后卸载V2rayU.app

第二步: 彻底删除相关文件及服务
命令

cd ~/Library/LaunchAgents/
/bin/launchctl remove yanue.v2rayu.v2ray-core
/bin/launchctl remove yanue.v2rayu.http

rm -f ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -f ~/Library/Preferences/net.yanue.V2rayU.plist
rm -f ~/Library/Logs/V2rayU.log
重点
主要是使用launchctl命令停止yanue.v2rayu.v2ray-core服务(会自动启动)

删除 ~/.V2rayU 目录 

重新 安装最新版本 试试

**Comment by Cerrorr** [comment]
> > 1. 你正在使用的 V2RayU 和 Mac 版本 ？
> >    正式版3.0.3 MacBook Pro 13-inch, 2018 macOS11.2.2
> > 2. 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
> >    点击订阅设置，pac设置，偏好设置闪退
> 
> 按照 author 的方法完全卸载
> 
> V2rayU彻底删除方法: (推荐使用AppCleaner)
> 
> https://github.com/yanue/V2rayU/blob/master/README.md#%E5%BD%BB%E5%BA%95%E5%8D%B8%E8%BD%BD
> 
> 第一步: 卸载V2rayU.app
> 停止v2ray-core, 然后卸载V2rayU.app
> 
> 第二步: 彻底删除相关文件及服务
> 命令
> 
> cd ~/Library/LaunchAgents/
> /bin/launchctl remove yanue.v2rayu.v2ray-core
> /bin/launchctl remove yanue.v2rayu.http
> 
> rm -f ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
> rm -f ~/Library/Preferences/net.yanue.V2rayU.plist
> rm -f ~/Library/Logs/V2rayU.log
> 重点
> 主要是使用launchctl命令停止yanue.v2rayu.v2ray-core服务(会自动启动)
> 
> 删除 ~/.V2rayU 目录
> 
> 重新 安装最新版本 试试

有效
