### ISSUE TITLE
3.0.3路由模式选择“绕过……”，v2ray进程就可能不能启动

### ISSUE THREAD

**Issue by Abderrian** [yanue/V2rayU#854]
3.0.3路由模式选择“绕过局域网地址”“绕过大陆地址”“绕过局域网和大陆地址”，v2ray进程就可能不能启动，例如在pac模式下v2ray进程能运行，但是在全局模式下v2ray进程就不能启动，或者反过来，在全局模式下能运行，在pac模式下不能启动。
我试了试，只要routing规则里有geoip（geoip:cn或者geoip:private）就会有这种情况，但是有geosite（geosite:cn）却没有问题。我的~/.V2rayU/v2ray-core里当然是有geoip.dat和geosite.dat的， #848 的命令我也运行过了，这两个文件的权限和拥有者是一样的。真是奇怪了。

**Comment by Abderrian** [comment]
只要在pac模式和全局模式之间切换就有可能不启动v2ray进程，没有geoip也一样。
还有高级设置里的启用UDP并没有效果，无论打开不打开启用UDP，config.json里都是
>   "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },

**Comment by Abderrian** [comment]
正常启动v2ray时log
>V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 darwin/amd64)
 A unified platform for anti-censorship.
2021/03/13 19:17:33 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: config.json
2021/03/13 19:17:33 [Info] github.com/v2fly/v2ray-core/v4/app/dns: DNS: created localhost client
2021/03/13 19:17:33 [Info] github.com/v2fly/v2ray-core/v4/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/03/13 19:17:33 [Info] github.com/v2fly/v2ray-core/v4/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2021/03/13 19:17:33 [Warning] github.com/v2fly/v2ray-core/v4: V2Ray 4.35.1 started

不能启动v2ray时log
> V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 darwin/amd64)
A unified platform for anti-censorship.
2021/03/13 19:18:04 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: config.json

只到Reading config就没有了，但是明明是同一个config.json。

**Comment by godlikejoke** [comment]
我也遇到这个问题，我2台mac，一台可以运行代理成功，另一台代理不了。明明是一样的配置
