### ISSUE TITLE
3.0.3 切换节点之后需要很久时间才能上网

### ISSUE THREAD

**Issue by somes** [yanue/V2rayU#855]
3.0.3 切换节点之后需要很久时间才能上网

**Comment by Abderrian** [comment]
你看看是不是v2ray的进程都没有启动？

**Comment by somes** [comment]
> 你看看是不是v2ray的进程都没有启动？

应该是启动的，就是切换节点的时候需要等很久，我用的socks和http代理。

**Comment by Abderrian** [comment]
> > 你看看是不是v2ray的进程都没有启动？
> 
> 应该是启动的，就是切换节点的时候需要等很久，我用的socks和http代理。

你在活动监视器里搜索v2ray看看是不是只有V2rayU，还是既有V2rayU又有v2ray？

**Comment by somes** [comment]
> > > 你看看是不是v2ray的进程都没有启动？
> > 
> > 
> > 应该是启动的，就是切换例程的时候需要等很久，我用的socks和http代理。
> 
> 你在活动监视器里搜索v2ray看看是不是只有V2rayU，还是既有V2rayU又有v2ray？

两个都是有的

**Comment by zw-wa-wa** [comment]
对 ,   就是这个 原因,  所以  give up,    没有说不好的意思,  现在用 qv2ray,  感觉更适合我

**Comment by somes** [comment]
3.0.0和之前的版本没有这个问题。

**Comment by edward852** [comment]
3.0.0预览版挺快的，新版总感觉要半分钟以上才能正常上网，已经换回预览版了。

**Comment by somes** [comment]
> 3.0.0预览版挺快的，新版总感觉要半分钟以上才能正常上网，已经换回预览版了。

我这边3.0.0不能更改节点端口了，改完之后还是变回443。

**Comment by Chillimeat** [comment]
我也发现这个问题，需要等很久

**Comment by nbxsrj** [comment]
我也遇到了这个问题，我是刚转换到macOS，还以为是系统的原因。qv2ray感觉太过复杂不太适合我使用，而且能耗实在是太高了，v2rayU好就好在轻量化+节能，希望能早日修复这个bug

**Comment by nbxsrj** [comment]
啊，顺便，我用的是m1的机器，big sur 11.2.3

**Comment by tanqci** [comment]
Macbookpro 16 i9
我也遇到启动后/切换节点后 ,要5-10秒才能上网的问题, 之前2.xx的版本都是正常的.
非常感谢!

**Comment by inixue** [comment]
我的也是，已经降回3.0.0预览版了。

**Comment by tanqci** [comment]
> Macbookpro 16 i9
> 我也遇到启动后/切换节点后 ,要5-10秒才能上网的问题, 之前2.xx的版本都是正常的.
> 非常感谢!

启动后, 切换一下PAC模式, 再切回到全局模式, 不行再试一下, 可以解决这个问题

**Comment by godlikejoke** [comment]
我也是，希望尽快修复。

**Comment by jiuqianyuan** [comment]
切换节点的确非常慢

**Comment by craterone** [comment]
+1

**Comment by vipadm** [comment]
+1，已切换成2.3.1

**Comment by fykin** [comment]
+1

**Comment by TeslaCN** [comment]
+1

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
