### ISSUE TITLE
vmess为什么只能用443端口啊 5位数的端口不行？

### ISSUE THREAD

**Issue by bushizhangwudia** [yanue/V2rayU#857]
3.0版本，如题 我中转的5位数端口，填进去自动给我改回443

**Comment by egoistttt** [comment]
> 3.0版本，如题 我中转的5位数端口，填进去自动给我改回443

我这4位数端口也复现了，是在vmss模式就必现，如果是ssr就没问题

**Comment by doutuo** [comment]
我也碰到 导入 vmess 链接，端口自动是443 而不是我自定义的端口。

**Comment by quickhot** [comment]
端口能保存，但是添加多个服务器，其他服务器都会被重置为443.
