### ISSUE TITLE
恢复测速功能

### ISSUE THREAD

**Issue by bugkidz** [yanue/V2rayU#858]
2.3.1 有个ping ，至少还能知道哪些节点的速度，3.0.3以后这个功能也没有了。如果是订阅多节点的情况下，无法知道哪些节点的存活以及连接速度。请恢复测速功能。谢谢

**Comment by FishM4n** [comment]
+1

**Comment by kevinroy-lo** [comment]
+1

**Comment by persiliao** [comment]
缺少这个ping ，总感觉少了点什么

**Comment by zhang-qi-yang** [comment]
+1。最好是真连接速度测试

**Comment by Mozilla88** [comment]
+1 为啥把这个功能取消了啊？这不是必需的吗？真的很不方便，无奈只好改用qv2ray了。

**Comment by Mozilla88** [comment]
+1 属于必需功能了

**Comment by Mozilla88** [comment]
+1 属于必需功能了

**Comment by ioudove** [comment]
+1

**Comment by CzyerChen** [comment]
+1，现在看着那些节点不知道速度，比较懵

**Comment by PumpkinDemo** [comment]
+1，确实没有速度显示很不舒服，因为比较难判断问题出在节点还是本地

**Comment by Darrenzzy** [comment]
+1

**Comment by chao921125** [comment]
+10086

**Comment by maxmadzz** [comment]
+65535

**Comment by maxxxty** [comment]
+1
真的感觉缺少了什么。

**Comment by joeaniu** [comment]
原来是新版去掉了啊， 可惜。 +65535

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
