### ISSUE TITLE
3.0 版本在M1上不能更新pac和代理

### ISSUE THREAD

**Issue by qzi** [yanue/V2rayU#864]
3.0 版本在M1上不能更新pac和代理

**Comment by nbxsrj** [comment]
我的偶尔会出现这种情况，但切换到global模式似乎就没有不能更新的问题了

**Comment by snsnselaoyeye** [comment]
我把pac网址加到自定义规则里，就能更新了

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
