### ISSUE TITLE
MAC启动后，发出嗡嗡响声

### ISSUE THREAD

**Issue by luanweijie** [yanue/V2rayU#865]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
都是最新版
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
MAC启动后，发出嗡嗡的响声，以为是硬件出问题了，后来卸载V2RayU问题消失，后台大量错误日志

**Comment by drcege** [comment]
这个问题好像一直存在，我从好几个版本前就遇到了，但是一直没有解决。经常出现CPU 100%，风扇狂转，必须强行杀死。。。
