### ISSUE TITLE
VLESS协议的配置保存后无法修改

### ISSUE THREAD

**Issue by oyyq99999** [yanue/V2rayU#868]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.0.3
macOS 11.2.2

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
vless配置保存后无法更改

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
![image](https://user-images.githubusercontent.com/3143564/112746585-49e41f80-8fe2-11eb-960f-a0ac0fed0f72.png)
经试验，当协议是vless的时候，红框中的配置一旦保存便再也无法更改，更改保存后重启又恢复之前的配置，只能删掉服务器重新来，绿框中的可以更改，黄框中未试验
已按 #848 中操作过，没有作用

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
