### ISSUE TITLE
同样的配置v2rayx可以用，而v2rayu就不行

### ISSUE THREAD

**Issue by dutry** [yanue/V2rayU#87]
系统是10.13.6。

通过剪贴板分享的链接，v2rayu即便设置为全局，真实效果也是不通过v2ray core而是直接上网，令人费解。 而x就没问题

**Comment by yanue** [comment]
下载这个: https://support.apple.com/kb/DL1998?locale=en_US 试下
后面修复一下

**Comment by dutry** [comment]
@yanue #2 修复过了，还是不行啊。现在只能用v2rayx+ssXng两个客户端一起了，好麻烦

**Comment by yanue** [comment]
你可以对比下和最终v2rayx的参数:
```
/Applications/V2rayU.app/Contents/Resources/config.json
```
