### ISSUE TITLE
不支持Trojan订阅和导入trojan://格式链接

### ISSUE THREAD

**Issue by ZhouKes** [yanue/V2rayU#870]
V2RAYU版本： 3.0.3
MAC OS版本： 11.1
现象，不能订阅Trojan，也不能导入trojan://格式的链接
参考订阅地址：https://proxypoolsstest.herokuapp.com/trojan/sub
参考trojan://链接 ： trojan://7017a129-b828-4d2YWVzLTI1Ni1nY206eDIzWjRMR2tHRGtUaFo5S2F6NERVUlFw@156.146.33.73:443#%F0%9F%87%BA%F0%9F%87%B8US_2991

**Comment by LeneSamils** [comment]
兄弟你好手动怎么配置，能帮忙说一下吗

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
