### ISSUE TITLE
长时间休眠唤醒后无法上网

### ISSUE THREAD

**Issue by realgtk** [yanue/V2rayU#872]
版本3.03，Mojave 10.14.6，全局走geosite内置路由模式。
合盖一晚上，开盖后无法上网，查下来是v2ray-core进程退出，必须得手动“Turn v2ray-core off”，“v2ray-core on”才行。

**Comment by dev4mobile** [comment]
好像我也有这个问题

**Comment by luckymrwang** [comment]
手动添加完，要点击右上角“保存设置并从GFW List更新“

**Comment by luckymrwang** [comment]
+1

**Comment by realgtk** [comment]
更新了v2ray-core后暂时没有出现此问题，有可能和V2rayU没关系，再观察一段时间看看。

**Comment by luckymrwang** [comment]
> 更新了v2ray-core后暂时没有出现此问题，有可能和V2rayU没关系，再观察一段时间看看。

你是怎么更新的，系统安装的更新吗？但我看到V2rayU包里有v2ray-core，它是用的包里自带的

**Comment by realgtk** [comment]
> > 更新了v2ray-core后暂时没有出现此问题，有可能和V2rayU没关系，再观察一段时间看看。
> 
> 你是怎么更新的，系统安装的更新吗？但我看到V2rayU包里有v2ray-core，它是用的包里自带的

自带的v2ray-core是4.34版本，最新的是4.37，手动更新到~/.V2rayU目录里

**Comment by zxdposter** [comment]
我更新了之后解决了

**Comment by luckymrwang** [comment]
> > > 更新了v2ray-core后暂时没有出现此问题，有可能和V2rayU没关系，再观察一段时间看看。
> > 
> > 
> > 你是怎么更新的，系统安装的更新吗？但我看到V2rayU包里有v2ray-core，它是用的包里自带的
> 
> 自带的v2ray-core是4.34版本，最新的是4.37，手动更新到~/.V2rayU目录里

ok，那我也更新试下

**Comment by wangzhiwei61** [comment]
> > > 更新了v2ray-core后暂时没有出现此问题，有可能和V2rayU没关系，再观察一段时间看看。
> > 
> > 
> > 你是怎么更新的，系统安装的更新吗？但我看到V2rayU包里有v2ray-core，它是用的包里自带的
> 
> 自带的v2ray-core是4.34版本，最新的是4.37，手动更新到~/.V2rayU目录里

我看最新版本是4.31.0,是不是我找的有问题，看到麻烦给个链接地址？

**Comment by realgtk** [comment]
> > > > 更新了v2ray-core后暂时没有出现此问题，有可能和V2rayU没关系，再观察一段时间看看。
> > > 
> > > 
> > > 你是怎么更新的，系统安装的更新吗？但我看到V2rayU包里有v2ray-core，它是用的包里自带的
> > 
> > 
> > 自带的v2ray-core是4.34版本，最新的是4.37，手动更新到~/.V2rayU目录里
> 
> 我看最新版本是4.31.0,是不是我找的有问题，看到麻烦给个链接地址？

4.31.0是停止开发的版本，新项目：https://github.com/v2fly/v2ray-core
