### ISSUE TITLE
添加了PAC但是还是不能走代理的问题还没有解决

### ISSUE THREAD

**Issue by ioudove** [yanue/V2rayU#874]
刚刚试了下3.0.3，之前在2.3.1中存在的问题还是没有解决
之前反馈过，不重新贴日志了
https://github.com/yanue/V2rayU/issues/793

**Comment by ioudove** [comment]
添加了PAC后，使用“PAC模式“依然不能走代理，但是全局模式就可以大家网址了，大佬修复下吧。好多人也有这个问题

**Comment by chenby228** [comment]
确认你添加的地址没有被PAC规则屏蔽（/Users/{your name}/.V2rayU/pac/proxy.js）

**Comment by chenby228** [comment]
确认你添加的地址没有被PAC规则屏蔽（/Users/{your name}/.V2rayU/pac/proxy.js）

**Comment by chenby228** [comment]
proxy.js文件中带@@的都是被pac规则屏蔽掉的，一般只针对一些大陆常用的地址，你要手动删除他们才能通过pac代理

**Comment by CzyerChen** [comment]
Mac:10.15.2
v2RayU: 3.0.3

通过彻底删除V2RayU-2.3.1 重新安装3.0.3，并参考 [543](https://github.com/yanue/V2rayU/issues/543)，能够访问外网
不知对你是否有帮助 @ioudove

**Comment by ioudove** [comment]
> Mac:10.15.2
> v2RayU: 3.0.3
> 
> 通过彻底删除V2RayU-2.3.1 重新安装3.0.3，并参考 [543](https://github.com/yanue/V2rayU/issues/543)，能够访问外网
> 不知对你是否有帮助 @ioudove

试过了，还是不行

**Comment by ioudove** [comment]
不知道为啥我昨天贴的网址被屏蔽了，重新贴下吧
就是这个网址添加进了规则里面但是PAC还是不通，全局模式就可以了
https://theyflyblog.com

**Comment by ioudove** [comment]
> > 不知道为啥我昨天贴的网址被屏蔽了，重新贴下吧
> > 就是这个网址添加进了规则里面但是PAC还是不通，大部分模式就可以了
> > https://theyflyblog.com
> 
> .theyflyblog.com
> .shareaholic.net
> .paypalobjects.com
> .youtube.com
> 网站里边有跨域请求，右键 检查-NetWork-刷新，看到红色的请求都加到pac规则（此网站关闭广告拦截插件）

太专业了，我不是学习编程的。您能帮忙给看下我还应该添加哪些网站到PAC才可以么？谢谢您了。

**Comment by chenby228** [comment]
> > > 不知道为啥我昨天贴的网址被屏蔽了，重新贴下吧
> > > 就是这个网址添加进了规则里面但是PAC还是不通，大部分模式就可以了
> > > https://theyflyblog.com
> > 
> > 
> > .theyflyblog.com
> > .shareaholic.net
> > .paypalobjects.com
> > .youtube.com
> > 网站里边有跨域请求，右键 检查-NetWork-刷新，看到红色的请求都加到pac规则（此网站关闭广告拦截插件）
> 
> 太专业了，我不是学习编程的。您能帮忙给看下我还应该添加哪些网站到PAC才可以么？谢谢您了。

![3751617854138_ pic](https://user-images.githubusercontent.com/41767672/113966277-604f6e00-9861-11eb-94f2-e76f244eecaf.jpg)

https://theyflyblog.com这个网站添加这几个我测试可以访问，保存设置，重连

**Comment by ioudove** [comment]
> .theyflyblog.com
> .shareaholic.net
> .paypalobjects.com
> .youtube.com

谢谢，奇怪了，我的还是不行呢

**Comment by Tansan-CC** [comment]
可能是你的PAC文件添加了错误的语句，我之前添加的时候多了一个空格，导致出现了很多问题。请尝试直接修改~/.V2rayU/pac/proxy.js文件。

**Comment by ioudove** [comment]
> 可能是你的PAC文件添加了错误的语句，我之前添加的时候多了一个空格，导致出现了很多问题。请尝试直接修改~/.V2rayU/pac/proxy.js文件。

格式没有问题，就是不管用，哎

**Comment by ooodyn** [comment]
@ioudove

**Comment by zhangxiaoyu2046** [comment]
我提供一个解决方法：检查你的Pac 设置里的GFW list是否正确，我改成了：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
即可，PAC也能正常work了。
最新地址应该在此处获取：https://github.com/gfwlist/gfwlist

**Comment by tongjn** [comment]
> Reference in new issu

个人添加的pac手动规则，我的V2rayU版本是3.8.0，目前在界面的pac设置里面无效，但是可以从/Applications/V2rayU.app/Contents/Resources/pac/user-rule.txt 这路径下找到这文件加进去，就可以生效走代理了

**Comment by tongjn** [comment]
> 添加了PAC后，使用“PAC模式“依然不能走代理，但是全局模式就可以打开网址了，大佬修复下吧。好多人也有这个问题
     个人添加的pac手动规则，我的V2rayU版本是3.8.0，目前在界面的pac设置里面无效，但是可以从/Applications/V2rayU.app/Contents/Resources/pac/user-rule.txt 这路径下找到这文件加进去，就可以生效走代理了

**Comment by l-ning** [comment]
找到了问题，修改完pac以后，手动关闭，在开启一下V2ray就行了，Mac亲测，不然不会生效，希望作者早日修改成自动的哈，辛苦了
