### ISSUE TITLE
V2rayu v3.0.3 error

### ISSUE THREAD

**Issue by kyshop38** [yanue/V2rayU#883]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by kyshop38** [comment]
開了按功能鍵就自動退出 不知道為何
V2rayu v3.0.3

**Comment by mqiezi** [comment]
偏好设置、订阅设置一打开就崩溃
比 2.3.1好像少了测速的功能
V2rayu v3.0.3

**Comment by daiyang94815** [comment]
同前两位，macOS 10.15.7 (19H1030)，偏好设置一打开就崩溃。

**Comment by 3660628** [comment]
同前两位，macOS 11.3.1 (20E241)，订阅和偏好设置这些一打开就崩溃了

**Comment by 3660628** [comment]
报错信息：illegal hardware instruction  /Applications/V2rayU.app/Contents/MacOS/V2rayU

**Comment by hacpai** [comment]
同前两位，macOS 10.12.6

**Comment by kyshop38** [comment]
就不知道問什麼一直閃退。反正就只能裝回舊的版本

**Comment by hacpai** [comment]
@kyshop38 @daiyang94815 @3660628 @mqiezi

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
