### ISSUE TITLE
新版希望支持测试每个服务器的有效性的功能, 以及连接状态的显示

### ISSUE THREAD

**Issue by zszen** [yanue/V2rayU#885]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
mac 3.0.3

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
连上服务器, 并不知道是否真的连上, 还要看控制台的输出状态, 很不直观, 链接一个一个试也挺累人的

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
