### ISSUE TITLE
切换模式打不开网页

### ISSUE THREAD

**Issue by jiangaq** [yanue/V2rayU#887]
每次切换到全局模式，或者换服务器，要等上几秒钟之后才有效，如果马上打开网页会显示无法连接，还要等几分钟才会正常

2.x版本时没这个问题

**Comment by s1ro6** [comment]
开机以后第一次运行时，也有相同的问题

**Comment by duoziEthan** [comment]
同样问题，希望尽快修复唉

**Comment by wangadong** [comment]
新版本开全局模式前必须先 turn off，非常麻烦，望尽快修复

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
