### ISSUE TITLE
如何解决dns污染问题

### ISSUE THREAD

**Issue by xxb5656** [yanue/V2rayU#888]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.0.1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
dns污染导致v2 ws tls方式无法解析，114在内等国内dns均ping不通，本地dns换成google dns &opnedns正常解析。

如何在V2RayU-偏好设置-DNS中，修改成指定某个dns来进行解析。V2Ray相关代码太深奥，且已知V2RayU有这个功能，所以询问。

**Comment by Abderrian** [comment]
应该是这样，不过代理服务器的域名可能一定会用本地DNS解析。
```
{
  "servers": [
    "localhost",
    {
        "address": "8.8.8.8",
        "domains": [
            "domain:你的域名"
        ]
    }
  ]
}
```
`https://www.v2fly.org/config/dns.html`
