### ISSUE TITLE
v2rayU什么时候升级到apple m1芯片原生版本呀？

### ISSUE THREAD

**Issue by code00000001** [yanue/V2rayU#891]
v2rayU什么时候升级到apple m1芯片原生版本呀？
有在开发当中吗？

**Comment by Douglasbeau** [comment]
我m1三四月份都可以用，这个月不能了，不知道啥原因。

**Comment by code00000001** [comment]
> 同样，目前 M1 上运行不了。
用是能用的， 我现在就在用，但还是intel版本的。 而且好久没有更新版本了

**Comment by southwolf** [comment]
现在应该能用的吧, 实在不行自己编译一下也OK

**Comment by hzmjf** [comment]
我是M1芯片的，我可以正常使用，难道我是假的M1么？😀

**Comment by xujintai123** [comment]
> 我是M1芯片的，我可以正常使用，难道我是假的M1么？😀
请问你是用的哪个版本的v2ray

**Comment by hzmjf** [comment]
> > 我是M1芯片的，我可以正常使用，难道我是假的M1么？😀
> > 请问你是用的哪个版本的v2ray

![image](https://user-images.githubusercontent.com/8153861/120348986-48134100-c330-11eb-8cb8-d738ed45f549.png)

**Comment by swyiic** [comment]
同M1 突然就无法使用，intel版的pro装的可以正常使用

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.1.0
