### ISSUE TITLE
OSX 休眠后唤醒，服务器会被选择为空，修改服务器之后延迟生效

### ISSUE THREAD

**Issue by jingzhongwa** [yanue/V2rayU#892]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
    3.0正式版，macos bigsur 11.2.3
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    1、mac电脑唤醒之后服务器会自动被选择为空，需要自己从服务器列表手动重新选择服务器，
    2、每次更换服务器之后需要很长时间才能生效，刚开始还以为是服务器不能用了，来回切换很多次。生效之后倒是可以正常使用。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    默认配置没有修改过。
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
     没有任何报错
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by zhangyongbo** [comment]
v3.0.3 同样有这个问题
