### ISSUE TITLE
~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Path had bad ownership/permissions

### ISSUE THREAD

**Issue by tenadolanter** [yanue/V2rayU#895]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

```
V2RayU  3.0.3
Mac Catalina 10.15.6
```

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

`~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist: Path had bad ownership/permissions`

**Comment by tenadolanter** [comment]
solved by  `sudo chmod 600  ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist`

this save my life

**Comment by vipadm** [comment]
solved by  issues  index page  V2rayU彻底卸载方法 
try reinstall v2rayu
