### ISSUE TITLE
v2RayU 使用 Pac 模式 Telegram 和Discord 无法连接网络问题

### ISSUE THREAD

**Issue by guo5619866** [yanue/V2rayU#896]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU 3.0.3版本，    Mac OS Big Sur 11.4
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2RayU 使用 Pac 模式 Telegram 和Discord 无法连接网络，昨天刚用的时候可以两个软件都可以连接，今天使用 pac 就无法连接了
试了很多次都连接不上

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by nchao** [comment]
同样的问题，彻底卸载后重装恢复
https://github.com/yanue/V2rayU/issues/697

**Comment by guo5619866** [comment]
> 同样的问题，彻底卸载后重装恢复
> #697

重装之后 Telegram 可以用了， 但是 Discord 还是无法使用！
