### ISSUE TITLE
设置生效无明确提示

### ISSUE THREAD

**Issue by cyt7732** [yanue/V2rayU#9]
1、点击保存后无明显提示，也不知道是否保存成功
2、不知道订阅的入口在哪里
3、mkcp伪装设置无法保存
4、能否支持Chinese？

**Comment by yanue** [comment]
1后续加上
2暂不支持订阅，加入计划中
3近期解决
4暂不支持

**Comment by cyt7732** [comment]
另外还有个BUG，在点开配置的时候，列表内偶尔会没有任何服务器配置。但是实际看菜单的服务器列表里面又有。
还有一个问题。就是每次导入新的配置，监听端口都会默认为1080。按照使用环境来说，一般情况是固定在某一个端口，比如1081，然后添加别的服务器，监听端口还是1081。只用在omega里直接设置一个1081即可。（因为我的1080已经被占用，所以必须设置1081等端口，每次添加都要修改不太方便。）
