### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by oahgnod** [yanue/V2rayU#90]
最新的macOS 可以正常打开 点击configure闪退

**Comment by yanue** [comment]
需要发一下日志, command+空格,搜索console.app,打开并搜索V2rayU,如下图
![image](https://user-images.githubusercontent.com/1435250/58931386-1cd1d780-8792-11e9-833c-2a6e0fa367a0.png)

**Comment by oahgnod** [comment]
神奇啊 应该是我之前多次安装的关系 我之前都是用brew来卸载 刚用App Cleaner彻底清理了一下 居然好了 感谢你得及时回复
