### ISSUE TITLE
检查更新提示错误

### ISSUE THREAD

**Issue by maxxxty** [yanue/V2rayU#902]
现在版本为3.0，在得到3.1版本的推送后，选择在软件端检查更细。
结果提示更新错误！获取升级信息时出现错误，请稍后再试。
之后来到GitHub下载安装最新版之后检查更新，还是如此提示。
求解答~

**Comment by ioudove** [comment]
+1
<img width="372" alt="截屏2021-06-16 下午2 04 27" src="https://user-images.githubusercontent.com/14962559/122166225-e31d2680-ceab-11eb-84f7-7490804b6bf0.png">

**Comment by ShawLyon** [comment]
+1

**Comment by yanue** [comment]
重试试下

**Comment by ioudove** [comment]
> 重试试下3.2
3.2中已经修复了，辛苦作者了

**Comment by maxxxty** [comment]
> 重试试下3.2

更新提示方面已经解决，辛苦大佬~
