### ISSUE TITLE
3.1.0 添加订阅地址,服务器乱码 

### ISSUE THREAD

**Issue by songhao8080** [yanue/V2rayU#903]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

系统版本: macOS High Sierra 
V2RayU: 3.1.0

2) 你遇到的问题是什么？
中文乱码
![image](https://user-images.githubusercontent.com/10607039/121978390-ac1b1800-cdba-11eb-9d66-87ee435bb8d3.png)

**Comment by Bean4k** [comment]
遇到同样的问题 
macOS Big Sur 11.2.3 
V2RayU: 3.1.0
谢谢

**Comment by yanue** [comment]
更新3.2

**Comment by yanzhouyoung** [comment]
更新到3.2后，服务器名称都是**new server**，期望名称举例：**🇭🇰 香港专线1**
macOS Monterey 12.0.1
V2RayU: 3.2.0
![image](https://user-images.githubusercontent.com/37031978/143731818-d09c75d4-273b-4117-831a-bf5223409700.png)

**Comment by xiwanglr** [comment]
3.2.0版本，通过二维码导入，ss节点名称都是new server。
vmess、trojan协议的名称正常。
