### ISSUE TITLE
V3.1 点击『Subscribe』闪退

### ISSUE THREAD

**Issue by liuzhongcool** [yanue/V2rayU#904]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
V3.1 & macOS Big Sur 11.4 (20F71)

2) 你遇到的问题是什么？
是新版点击 "subscribe"菜单直接闪退。退回V2.3.1正常。

**Comment by hzxhzc** [comment]
打开prefrence也是闪退

**Comment by vipadm** [comment]
我也是 11.4，是彻底删除所有 重新安装的 都ok

**Comment by hxhlb** [comment]
我也是, 10.15.7 点击偏好设置直接闪退.

**Comment by xyh19981224** [comment]
彻底删除所有 重新安装 ,解决

**Comment by yanue** [comment]
试下: https://github.com/yanue/V2rayU/releases/tag/3.2.0
