### ISSUE TITLE
host为空数组的情况下，会crash

### ISSUE THREAD

**Issue by whlsxl** [yanue/V2rayU#906]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

v3.1.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

h2协议下，"host" 如果是空数组，会crash，不是空数组，不能连接。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
        "httpSettings": {
          "path": "/xxxx",
          "host": [ ]
        },
        "network": "h2"
```

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases/tag/3.2.0
