### ISSUE TITLE
3.10 打开没有任何反应

### ISSUE THREAD

**Issue by eromoe** [yanue/V2rayU#908]
1) 你正在使用的 V2RayU 和 Mac 版本 ？ 

3.10   ，  air m1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

打开应用没有反应

尝试给home 目录下的 .v2rayu 加了权限，还是没有反应

**Comment by sqzhang-jeremy** [comment]
I  have also met the same issue. the icon didn't appear in the up banner, which made me not to further reach to this app. Thanks!

V2ray version: 3.10/3.0.0
Mac: pro m1

**Comment by eromoe** [comment]
@sqzhang-jeremy any alternative suggest?

**Comment by ShawLyon** [comment]
me too

**Comment by yanue** [comment]
试下3.2吧
https://github.com/yanue/V2rayU/releases/tag/3.2.0

**Comment by onlymocha** [comment]
> 试下3.2吧
> https://github.com/yanue/V2rayU/releases/tag/3.2.0

Mac m1   还是不行  没反应

**Comment by sqzhang-jeremy** [comment]
> > 试下3.2吧
> > https://github.com/yanue/V2rayU/releases/tag/3.2.0
> 
> Mac m1 还是不行 没反应

Unfortunately, it certainly does't work at all. :(

**Comment by snsnselaoyeye** [comment]
无法启动的朋友试试运行一个不支持m1原生的app让系统把罗塞塔2装一下就好了。我也是折腾半天才发现的。
今天更新了一下11.5rc，也是无法运行，状态栏没图表显示，但是进程里有app，然后我装了另一个不支持原生m1的app，运行的时候提示要装罗塞塔，就点了是，然后奇迹就出现了，V2rayU的图标终于出来了。
