### ISSUE TITLE
从2.3.1升级至3.2.0时提示“更新错误，解压过程中出现错误，请稍后再试。”

### ISSUE THREAD

**Issue by huaituo** [yanue/V2rayU#915]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
2.3.1 / 11.4 (20F71)
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
从2.3.1升级至3.2.0时提示“更新错误，解压过程中出现错误，请稍后再试。”
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by BinsonZoom** [comment]
@huaituo 
遇到同样的问题! mac版本  10.15.7

![image](https://user-images.githubusercontent.com/17978055/123191786-56d6b900-d4d4-11eb-8419-746a1ded8879.png)

错误提示：解压过程中出现错误，请稍后再试

config.json如下：

{
"log": {
"error": "",
"loglevel": "info",
"access": ""
},
"inbounds": [
{
"listen": "127.0.0.1",
"protocol": "socks",
"settings": {
"udp": false,
"auth": "noauth"
},
"port": "1080"
},
{
"listen": "127.0.0.1",
"protocol": "http",
"settings": {
"timeout": 360
},
"port": "1087"
}
],
"outbounds": [
{
"mux": {
"enabled": false,
"concurrency": 8
},
"protocol": "vmess",
"streamSettings": {
"network": "tcp",
"tcpSettings": {
"header": {
"type": "none"
}
},
"security": "none"
},
"tag": "proxy",
"settings": {
"vnext": [
{
"address": "",
"users": [
{
"id": "",
"alterId": 8,
"level": 0,
"security": ""
}
],
"port": 
}
]
}
},
{
"tag": "direct",
"protocol": "freedom",
"settings": {
"domainStrategy": "UseIP",
"redirect": "",
"userLevel": 0
}
},
{
"tag": "block",
"protocol": "blackhole",
"settings": {
"response": {
"type": "none"
}
}
}
],
"dns": {},
"routing": {
"settings": {
"domainStrategy": "AsIs",
"rules": []
}
},
"transport": {}
}

**Comment by mouhao** [comment]
我也是同样的问题

**Comment by lzq5467** [comment]
。。。重装以后有些网站打不开了。。。怎么办。没以前的版本好用。准备卸载重新下载以前的版本！

**Comment by pygmalion666** [comment]
macOS Big Sur 11.4 出现了同样的问题，后面去 tags 下载了最新 3.2.0 本地安装，成功。但是一打开 “PAC 设置”或者“订阅设置”就奔溃，重启好几次都这样，最后还是回到 2.3.1.

**Comment by liaozhonghui** [comment]
我也是同样的问题，更新不了，然后一打开订阅设置就崩溃

**Comment by hussion** [comment]
同样的问题

**Comment by wuyifan18** [comment]
+1

**Comment by ljmkimqx** [comment]
+1

**Comment by zhangdove** [comment]
+1

**Comment by yhuso** [comment]
+1

**Comment by liyzcj** [comment]
+1

**Comment by guodongfan-pts** [comment]
还没有修复吗？

**Comment by yhuso** [comment]
把旧版本卸载，然后下载新版本重装安装就可以了

**Comment by yhuso** [comment]
> 把旧版本卸载，然后下载新版本重装安装就可以了

也就是说不要直接升级
