### ISSUE TITLE
MacBook Air M1更新3.0以上版本后不能使用

### ISSUE THREAD

**Issue by Riddleofdeath** [yanue/V2rayU#918]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.2.0和3.1.0都测试过，电脑是MacBook Air M1，系统Mac OS Big Sur 11.4。

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法翻出去，什么网站都不行，没有任何报错提示。
但是安装回去2.3.1就没有问题。
服务器是just my socks的v2ray服务器。

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by BoWang816** [comment]
同M1升级以后不能使用，点击订阅设置什么的都会直接退出

**Comment by GreatMartial** [comment]
用AppCleaner卸载，再重装。
亲测可用！

**Comment by dqmzzx** [comment]
> 用AppCleaner卸载，再重装。
> 亲测可用！

我卸载重装还是不行

**Comment by qdpoboy** [comment]
> 同M1升级以后不能使用，点击订阅设置什么的都会直接退出

老哥用的什么版本？我M1电脑新装的3.2版本，装完点击打开无任何反应。。。怎么办？

**Comment by Riddleofdeath** [comment]
要用appcleaner完全卸载后再装就可以了，3.2可用

发自我的iPhone

**Comment by qdpoboy** [comment]
> > 用AppCleaner卸载，再重装。
> > 亲测可用！
> 
> 我卸载重装还是不行

我安装上rosetta就启动起来了，你也可以试试

**Comment by parksben** [comment]
命令行更新一下 rosetta 就行了：

```bash
softwareupdate --install-rosetta
```
