### ISSUE TITLE
无法打开“V2rayU.app”，因为Apple无法检查其是否包含恶意软件

### ISSUE THREAD

**Issue by leechao1981** [yanue/V2rayU#919]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？ 
最新版本3.2  mac big sur 11.4 M1

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法打开应用
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by Martin-Tjj** [comment]
兄弟这是apple的隐私政策，打开软件然后报你这个错，你去
设置 --> 安全与隐私 --->通用 ----> ,下面有个仍要打开就行了

**Comment by xiongxianzhu** [comment]
先安装v2rayx再安装v2rayU, 就可以用v2rayU了， 还有， mac os新系统默认在“安全性与隐私--通用”不显示“任何来源”

在终端执行：

sudo spctl --master-disable

输入密码即可。
