### ISSUE TITLE
点击订阅和偏好会闪退。

### ISSUE THREAD

**Issue by wei-zeyuan** [yanue/V2rayU#920]
V2rayU版本：3.0+（包含3.0）
系统：macOS Big Sur 11.4
处理器：intel i9

**Comment by liaozhonghui** [comment]
我这个问题解决了：装v2.3.1版本的把**订阅设置项全删**了，再装v3.2.0，打开订阅设置重新更新。就好了。

**Comment by wei-zeyuan** [comment]
👌,非常感谢
