### ISSUE TITLE
v2rayu 订阅地址访问不到以至于卡死

### ISSUE THREAD

**Issue by songlongkuan** [yanue/V2rayU#923]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU: 3.2.0   Mac: 11.4
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
启动v2rayu客户端，如果订阅的http地址无法访问后，V2ray会出现卡死很久的现象
即使我取消勾选启动时更新订阅也还是会卡死
期望是  获取不到更新也不会影响到现有的server配置，是否可以在v2rayu启动时通过异步的方式去拉取更新
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

![image](https://user-images.githubusercontent.com/16483654/123916379-2a2f0f80-d9b4-11eb-9fa1-993e9e233b9f.png)

**Comment by dqmzzx** [comment]
我也是这种情况 不知道怎么回事 以前还好好的
