### ISSUE TITLE
点选PAC设置闪退问题

### ISSUE THREAD

**Issue by wanghaolyj** [yanue/V2rayU#927]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2ray 3.2.0 mac 11.4

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
点PAC设置闪退，  PAC里面我在2.3版本添加了几个自定义规则

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
无
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
无
```

请预览一下你填的内容再提交。

**Comment by sudot** [comment]
同题主，除了打开网页，检查更新和切换服务器，其他的功能一点就闪退

**Comment by runskycf** [comment]
同上，升级到3.2版本后闪退

**Comment by iam57-2020** [comment]
同上，请火速更新解决bug

**Comment by hengkx** [comment]
点击偏好设置 也闪退

**Comment by zhangwen9229** [comment]
+1 
V2ray 3.2.0 mac 11.4

**Comment by lsls01** [comment]
+1
点订阅菜单，同样推闪退
V2ray 3.2.0 mac 11.4

**Comment by mufengcoding** [comment]
+1

**Comment by blackstar-baba** [comment]
+1

**Comment by cangwuwuwu** [comment]
点啥都闪退。。 bigsur 11.4

**Comment by tangl163** [comment]
闪退的，试试以下步骤：
1. 退出`V2rayU`
2. `rm ~/Library/Preferences/net.yanue.V2rayU.plist`
3. 重新启动`V2rayU`
