### ISSUE TITLE
关闭开机自启失效，而且标题栏没有图标

### ISSUE THREAD

**Issue by scemsjyd** [yanue/V2rayU#93]
关闭开机自启，重启电脑，mac 命令行窗口下执行 losf -i :1080可以看到v2ray进程监听1080端口。
并且此时状态栏不显示图标。

**Comment by gino2010** [comment]
同样的问题，重现步骤
正常开启v2rayx 软件，关闭系统开启自动加载选项。退出v2rayx后查看 losf 和 ps，确保没有1080监听和v2rayx进程， 然后重启电脑
启动电脑后查看，此时状态栏没有v2rayx图标
lsof -i -P | grep -i "listen"    可以看到 v2rayx进程在监听
ps aux | grep v2ray  可以看到v2rayx进程在运行，尝试kill进程，但进程会自动恢复，pid改变
实际v2ray在运行，可以访问代理，因为服务实际在运行

初步分析和我之前给shadowsocksx-ng的一次修改问题差不多，请参考：
https://github.com/shadowsocks/ShadowsocksX-NG/pull/361

请调整服务加载方式，关闭keeplive，合理使用load unload start stop

**Comment by gino2010** [comment]
同时建议查看PAC监听服务加载方式，也有类似问题
在选择其他模式时应该关闭PAC服务，重启软件后会自己开启

**Comment by yanue** [comment]
估计已修复:1.3.3
