### ISSUE TITLE
3.0.0以后版本都试了，mac端启动无法连接网络，其他系统客户端上网正常

### ISSUE THREAD

**Issue by zhibolink** [yanue/V2rayU#936]
021/07/12 22:50:51 [Warning] [2756704832] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.tk/): 525 Origin SSL Handshake Error > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2021/07/12 22:50:51 [Info] [2756704832] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

这是报错内容

**Comment by th3dm4** [comment]
同样的报错内容，Big Sur 11.4，v2rayU 3.2.0。
同一网络下，android用v2rayNG连接正常，但mac一直报错

**Comment by JoyAbleCN** [comment]
同mac连不上网，windows和android都正常

**Comment by helixcg** [comment]
Big Sur 11.4，v2rayU 3.2.0 
android正常 
mac 可以ping speed 
但
没有日志 浏览器无法连接

**Comment by JoyAbleCN** [comment]
彻底删除v2RayU， 重装3.2.0后， 已经可以使用。

**Comment by th3dm4** [comment]
彻底删除后重启mac，再重装3.2.0，还是报错，但android正常。报错如下：
2021/07/14 16:04:04 [Warning] [1132981069] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by akinlong** [comment]
我也是，删了再装也没有用，有解决方案么

**Comment by Zhou-Bill** [comment]
一样

**Comment by Zhou-Bill** [comment]
2.3版本能用

**Comment by mxm646690173** [comment]
bigSur 11.5.1  一样的报错信息, 能 ping 通, 但是不管是 pac 还是 全局, 都无法跨越长城, clashX 能正常使用

**Comment by zhibolink** [comment]
> 彻底删除后重启mac，再重装3.2.0，还是报错，但android正常。报错如下：
> 2021/07/14 16:04:04 [Warning] [1132981069] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
我也是的，卸载干净重装还是不行

**Comment by zhibolink** [comment]
> 彻底删除v2RayU， 重装3.2.0后， 已经可以使用。

请问你的macOS什么版本

**Comment by bjjdkp** [comment]
> bigSur 11.5.1 一样的报错信息, 能 ping 通, 但是不管是 pac 还是 全局, 都无法跨越长城, clashX 能正常使用

+1 我好像也是更新系统到11.5.1出问题了。。。

**Comment by bjjdkp** [comment]
更新macOS 11.5.2后，依旧用不了。目前在用clashX，但感觉还是V2rayU更好用。

**Comment by zhibolink** [comment]
> > 彻底删除v2RayU， 重装3.2.0后， 已经可以使用。
> 
> 请问你的macOS什么版本

big sur 11.5.1

**Comment by ggz21s** [comment]
Same Question, 
MacOS Monterey  version 12.6.3

2023/03/05 16:09:13 tcp:127.0.0.1:60995 accepted tcp:content-autofill.googleapis.com:443 [proxy]
2023/03/05 16:09:13 [Info] [1777273822] proxy/shadowsocks: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:149.28.77.247:8198
2023/03/05 16:09:14 [Info] [1099725795] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/03/05 16:09:14 [Info] [1099725795] transport/internet/tcp: dialing TCP to tcp:149.28.77.247:8198
2023/03/05 16:09:15 [Info] [1099725795] transport/internet/tcp: dialing TCP to tcp:149.28.77.247:8198
2023/03/05 16:09:15 [Info] [1099725795] transport/internet/tcp: dialing TCP to tcp:149.28.77.247:8198
2023/03/05 16:09:15 [Warning] [1099725795] app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: failed to find an available destination > common/retry: [dial tcp 149.28.77.247:8198: i/o timeout dial tcp 149.28.77.247:8198: operation was canceled] > common/retry: all retry attempts failed

**Comment by zhoujingchao** [comment]
> Same Question: OS: MacOS Monterey Version: 12.6.3 V2rayU 3.2.0
> 
> 2023/03/05 16:09:13 tcp:127.0.0.1:60995 accepted tcp:content-autofill.googleapis.com:443 [proxy] 2023/03/05 16:09:13 [Info] [1777273822] proxy/shadowsocks: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp: 2023/03/05 16:09:14 [Info] [1099725795] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
> 
> 2023/03/05 16:09:15 [Warning] [1099725795] app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: failed to find an available destination > common/retry: [dial tcp xxx.xxx.xxx.xxx:xxxx: i/o timeout dial tcp xxx.xxx.xxx.xxx:xxxx: operation was canceled] > common/retry: all retry attempts failed

Same Question:
OS: MacOS Monterey Version: 12.6.3 V2rayU 3.3.0
