### ISSUE TITLE
Mac端，开关操作，换节点，切换model，都会请求修改系统网络的操作

### ISSUE THREAD

**Issue by lb-louisben** [yanue/V2rayU#937]
**Mac**端，开关操作，换节点，切换model，都会请求修改系统网络的操作

![Screen Shot](https://user-images.githubusercontent.com/65753523/125735949-be0a7871-a148-4ef6-bedc-0b0de99b61b9.png)

**Comment by AnthonyZhai** [comment]
请告知如何解决的
