### ISSUE TITLE
订阅更新的服务器处理方式建议

### ISSUE THREAD

**Issue by xpol** [yanue/V2rayU#94]
目前的订阅更新机制我感觉是这样的：
1. 订阅获得的每个服务器保存到服务器列表。
2. 更新订阅的时候，如果有新服务器就添加到服务器列表。
3. 可能没有处理订阅移除服务器的时候应该从之前的服务器列表中删除。

建议改进：
1. 保存订阅服务器的时候，标注该服务器来着某个订阅。
2. 更新订阅的时候：
    - 如果成功获取了一个服务器列表，则先删除原来服务器列表中标注来着这个订阅的服务器列表，再讲新获得的列表保存到服务器列表。
    -  如果订阅获取失败，则保留原来的列表。

**Comment by yanue** [comment]
已修复:1.3.3
