### ISSUE TITLE
无法增加自定义inbound

### ISSUE THREAD

**Issue by povsister** [yanue/V2rayU#943]
1) 你正在使用的 V2RayU 和 Mac 版本 ？
`V2RayU v3.2.0`
`Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 darwin/amd64)`

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
增加一个自定义inbound之后，点击确定，save success，但实际config文件中并无该字段。
手工修改`config.json`文件后，GUI上启动v2raycore，自定义的inbounds配置立即被删除，然后覆盖为socks和http inbound。

查log很明显看到没有自定义的1088监听，查看live config发现也没有加载自定义的inbound。
希望V2RayU只检查inbounds字段是否包含必要的socks和http配置，不要整个覆盖，避免影响自定义inbound？
```
2021/07/22 16:21:39 [Info] infra/conf/serial: Reading config: config.json
2021/07/22 16:21:39 [Info] app/dns: DNS: created localhost client
2021/07/22 16:21:39 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/07/22 16:21:39 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1087
2021/07/22 16:21:39 [Warning] core: Xray 1.4.2 started
```

![image](https://user-images.githubusercontent.com/11040951/126610592-0795b852-273c-49db-8d87-bc5328312727.png)

**Comment by luoguanping** [comment]
同样的问题。
