### ISSUE TITLE
当前最新版经常断开连接

### ISSUE THREAD

**Issue by asche910** [yanue/V2rayU#944]
目前用的最新版，电脑为Mac M1，电脑锁屏后，经常过段时间设置的代理无法使用，点击手动模式（原先就是手动模式），发现代理又有效了。之前用mac 英特尔芯片未出现这现象。

**Comment by asche910** [comment]
2021/07/22 19:03:38 [Info] [3782173890] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2021/07/22 19:03:38 [Info] [977318563] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2021/07/22 19:03:38 [Info] [2524395537] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2021/07/22 19:03:38 [Info] [977318563] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2021/07/22 19:03:38 [Info] [2524395537] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2021/07/22 19:03:38 [Info] [3782173890] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2021/07/22 19:03:38 [Info] [840873315] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by lileixuan** [comment]
+1
经常是隔一段时间就要重新启动下，否则就连不上了

**Comment by luckymrwang** [comment]
+1
相同的问题，需要重启下才可以

**Comment by thesadboy** [comment]
> +1
> 经常是隔一段时间就要重新启动下，否则就连不上了

+1 重启用不了多久就又挂了，又得重启

**Comment by v2wy** [comment]
+1 锁屏之后有概率出现 每次都是保存设置之后就好了 已经换Qv2ray了 目前还没有这个问题

**Comment by luckymrwang** [comment]
问题越来越频繁，已经换用clashx pro了，目前非常稳定没有这个问题了
