### ISSUE TITLE
start v2ray fail: v2ray config not found

### ISSUE THREAD

**Issue by junditech** [yanue/V2rayU#946]
重新安装也无济于事。<img width="1026" alt="截屏2021-07-30 下午2 15 17" src="https://user-images.githubusercontent.com/73412686/127609636-caba3732-6649-4f6e-9740-ac53f0776493.png">

日志是空的，
config.json 也是空的，
目录下/Applications/V2rayU.app/Contents/Resources/v2ray-core/v2ray/ 也没有 config.json 文件

**Comment by solomsk** [comment]
同样遇到这个问题，请问怎么解决？？

**Comment by jundeeliu** [comment]
> 同样遇到这个问题，请问怎么解决？？

试试这个

https://github.com/yanue/V2rayU/releases/tag/3.0.3

<img width="1020" alt="WX20210926-133457@2x" src="https://user-images.githubusercontent.com/73412686/134795025-4153aeab-55df-4d58-8a8e-2654a3c93f1a.png">
