### ISSUE TITLE
不仅闪退，浏览器还不能访问网络了

### ISSUE THREAD

**Issue by tuyrk** [yanue/V2rayU#947]

**Comment by oldbig** [comment]
我的也是，点击 configuration， pac... 等都闪退

**Comment by iopanda** [comment]
> 3.2.0版本，我的也是，点击 configuration， pac... 等都闪退

保存配置，然后删除~/Library/Preferences/net.yanue.V2rayU.plist并重新配置可以解决闪退。
`rm -rf ~/Library/Preferences/net.yanue.V2rayU.plist`
