### ISSUE TITLE
Ping Speed Return -1ms

### ISSUE THREAD

**Issue by TomLuck1** [yanue/V2rayU#949]
1. Version: 3.2.0;
2. Issue: The return value of a server's Ping is -1ms but this server is connected.

**Comment by bg1rgb** [comment]
+1

1. Version: 3.2.0
2. Issue: Ping speed always display In Testing, and result is  -1ms.

**Comment by Readeon** [comment]
same issue here. Worked well before add a new subscription.

**Comment by everkicker** [comment]
same problem here.

**Comment by Kiteflyingee** [comment]
same issue

**Comment by yanue** [comment]
关闭SIP

**Comment by immustard** [comment]
> 关闭SIP

关闭了还是有这个问题.
