### ISSUE TITLE
Proxy里面添加了rules，无效

### ISSUE THREAD

**Issue by AlbusSong** [yanue/V2rayU#952]
如下图，我添加了一些网站的域名，用英文逗号隔开，但是不生效。
<img width="572" alt="Screen Shot 2021-08-04 at 2 01 54 PM" src="https://user-images.githubusercontent.com/47345588/128134290-0ce5473b-37da-4d01-92da-61661bbcbbe3.png">
是我添加的格式出问题了吗？

**Comment by bjjdkp** [comment]
需要重启core才会生效

**Comment by 1234yws** [comment]
加错地方了
pac设置
<img width="468" alt="WX20210914-160903@2x" src="https://user-images.githubusercontent.com/16277606/133220499-c7d89176-e2b4-40ca-95f8-94a066554328.png">

**Comment by daleyzou** [comment]
> 加错地方了 pac设置 <img alt="WX20210914-160903@2x" width="468" src="https://user-images.githubusercontent.com/16277606/133220499-c7d89176-e2b4-40ca-95f8-94a066554328.png">

感谢，成功添加
