### ISSUE TITLE
从UI界面添加的vless-xtls 默认开启了mux,导致无法上网.

### ISSUE THREAD

**Issue by mrleelp** [yanue/V2rayU#953]
1)   V2RayU 版本 v3.2.0 ， Mac 版本 11.4。
2)  问题：vless-xtls 模式无法上网。
3) 发现 win 版本同样问题已修复。  
https://github.com/2dust/v2rayN/issues/1040
https://github.com/2dust/v2rayN/issues/1034

配置
```javascript
    "mux": {
        "enabled": true,
        "concurrency": 8
        }
```
4)  出错时软件输出的错误日志。
```javascript
   Failed to start: main: failed to load config files: [config.json] > infra/conf: XTLS doesn't support Mux for now.
```

**Comment by chendong0120** [comment]
可以 尝试使用 AppUninstaller 清理现在的 V2ray , 并且清理 rm -rf ~/.V2rayU 这个文件夹, 重新安装一下 就可以了.
