### ISSUE TITLE
feature request: 强制某个应用走代理？

### ISSUE THREAD

**Issue by evenlee** [yanue/V2rayU#955]
非常感谢作者的辛苦付出，我用着一只很稳定。
在使用过程中，发现有些软件不能配置本地代理，所以想请教一下，可不可以开发一个功能，把需要的程序加进去，然后让这些程序的流量强制走配置好的代理，
比如我加safari 或着网易音乐添加到列表：safari;neteasemusic
然后这两个软件的的流量都直接走配置好的 socks5 本地代理。

**Comment by hmddz** [comment]
挺好，这个需求简单明了，我也需要。
不然每次都要查日志，加PAC

**Comment by cn-zhixiang** [comment]
v2ray 是自动配置了个 socks 代理。但 socks 代理是君子协议，可遵守可不遵守，有些应用不遵守这协议的话，你只能去 push 这些应用。
提供一些可行的思路：
https://wangbjun.site/2020/linux/linux-proxy.html

**Comment by flashing** [comment]
proxifier就是干这个的，麻烦了点
