### ISSUE TITLE
M1  

### ISSUE THREAD

**Issue by SayMeAlound** [yanue/V2rayU#961]
M1 上无法安装     有解决的吗

**Comment by xxxx-oooo** [comment]
> M1 上无法安装 有解决的吗

目前需要使用 rosettea 模式才能运行

**Comment by SayMeAlound** [comment]
嗯 可以装小火箭  已经解决了  谢谢回复

**Comment by fushigi823** [comment]
> 嗯 可以装小火箭 已经解决了 谢谢回复
> […](#)
> Sent from my iPhone
> On 20 Aug 2021, at 01:23, oooo-xxxx ***@***.***> wrote: ﻿ M1 上无法安装 有解决的吗 目前需要使用 rosettea 模式才能运行 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问小火箭是哪个软件

**Comment by SayMeAlound** [comment]
shadowrocket     非国区Apple Store 搜索即可

**Comment by mactrash** [comment]
M1 11.5.2 rosettea 也無法上网

**Comment by mactrash** [comment]
M1 11.5.2 (20G95) v3.2.0 可以使用

**Comment by cxMax** [comment]
分享下个人爬坑经历。 因为公司配置m1的电脑，装个Rosetta固件就好了。

https://zhuanlan.zhihu.com/p/344157569

就这哥，现在完美运行了
