### ISSUE TITLE
mac mini 可以ping出速度，但是无法科学上网

### ISSUE THREAD

**Issue by yunxuo** [yanue/V2rayU#962]

**Comment by yunxuo** [comment]
日志：

2021/08/19 21:48:38 [Info] [2142129759] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2021/08/19 21:48:38 [Info] [2142129759] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2021/08/19 21:48:38 [Info] [2142129759] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:c50s4.jamjams.net:19636
2021/08/19 21:48:38 [Info] [1475341481] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2021/08/19 21:48:38 [Info] [1475341481] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:c50s4.jamjams.net:19636
2021/08/19 21:48:38 tcp:127.0.0.1:57969 accepted tcp:content-autofill.googleapis.com:443 [proxy]
2021/08/19 21:48:38 tcp:127.0.0.1:57968 accepted tcp:content-autofill.googleapis.com:443 [proxy]
2021/08/19 21:48:39 [Info] [2142129759] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:c50s4.jamjams.net:19636
2021/08/19 21:48:39 [Info] [1475341481] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:c50s4.jamjams.net:19636
2021/08/19 21:48:39 [Info] [3286107283] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2021/08/19 21:48:39 [Info] [3286107283] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/08/19 21:48:39 [Info] [2077888843] v2ray.com/core/proxy/socks: TCP Connect request to tcp:content-autofill.googleapis.com:443
2021/08/19 21:48:39 [Info] [2077888843] v2ray.com/core/app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2021/08/19 21:48:39 [Info] [2077888843] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:c50s4.jamjams.net:19636
2021/08/19 21:48:39 tcp:127.0.0.1:57972 accepted tcp:content-autofill.googleapis.com:443 [proxy]
2021/08/19 21:48:39 [Info] [2077888843] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:content-autofill.googleapis.com:443 via tcp:c50s4.jamjams.net:19636
2021/08/19 21:48:39 [Info] [1475341481] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2021/08/19 21:48:39 [Info] [1475341481] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/08/19 21:48:39 [Info] [2077888843] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2021/08/19 21:48:39 [Info] [2077888843] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/08/19 21:48:40 [Info] [2142129759] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2021/08/19 21:48:40 [Info] [2142129759] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by DemoorBug** [comment]
同样的问题，麻烦问一下你解决了吗？真的很头痛

**Comment by DemoorBug** [comment]
改用qv2ray了，一切正常bigsur 11.6
