### ISSUE TITLE
Bigsur使用最新版本v2rayu打开软件偏好设置闪退

### ISSUE THREAD

**Issue by Mons0512** [yanue/V2rayU#963]
Bigsur使用最新版本v2rayu打开软件偏好设置闪退

V2RayU3.2.0
Mac Bigsur 11.4

**Comment by yytbob** [comment]
目前 macOS 最新版本 BigSur 11.5.2 (20G95)，暂时没发现问题。

**Comment by ITmao** [comment]
我也遇到了这个问题。但是看日志也没啥特别的提示。
