### ISSUE TITLE
V2ray 为什么是 lntel

### ISSUE THREAD

**Issue by imagine1717** [yanue/V2rayU#964]
![image](https://user-images.githubusercontent.com/42824481/130167811-0a431fcd-cee1-452e-9389-036771614f0f.png)

**Comment by cn-zhixiang** [comment]
就还没适配 M1 呗，应该不影响使用吧

**Comment by liyuhaolol** [comment]
你都M1了，就不用这个软件了，ARM的翻墙软件，不是一地一地的。

**Comment by imagine1717** [comment]
> 就还没适配 M1 呗，应该不影响使用吧

可以正常使用的

**Comment by imagine1717** [comment]
> 你都M1了，就不用这个软件了，ARM的翻墙软件，不是一地一地的。

推荐一下啊，感觉还行就用了

**Comment by liyuhaolol** [comment]
> > 你都M1了，就不用这个软件了，ARM的翻墙软件，不是一地一地的。
> 
> 推荐一下啊，感觉还行就用了

小火箭，用这个就行，作者应该不会适配M1，因为ARM的类似软件太多，作者设配也得不到什么好。

**Comment by ZyjacyaD** [comment]
可以直接下载最新版v2ray-core替换/Users/(你的用户名)/.V2rayU/v2ray-core/v2ray就变成apple了，不过不能使用xray了

**Comment by williambypass** [comment]
> 可以直接下载最新版v2ray-core替换/Users/(你的用户名)/.V2rayU/v2ray-core/v2ray就变成apple了，不过不能使用xray了

骚操作 把arm64-xray改名v2ray放进去就行了

**Comment by LuletterSoul** [comment]
> > 可以直接下载最新版v2ray-core替换/Users/(你的用户名)/.V2rayU/v2ray-core/v2ray就变成apple了，不过不能使用xray了
> 
> 骚操作 把arm64-xray改名v2ray放进去就行了

老哥真稳哈哈，我成功啦！里面有v2ray和xray两个文件，把arm版的xray复制一份改名为v2ray替换进去就好了。
