### ISSUE TITLE
ping speed 一直卡在测试中

### ISSUE THREAD

**Issue by winkerwinker** [yanue/V2rayU#967]
1) 最新版本

2) ping speed 一直卡在测试中，并且节点都连不上

3) 默认配置

![image](https://user-images.githubusercontent.com/50097018/130756255-7871f4e6-998a-45c1-915b-a1b24ac44622.png)

**Comment by ccyyy123** [comment]
同样的情况，不知道怎么解决

**Comment by g1ave** [comment]
> 

SIP是什么？

**Comment by J-Liu** [comment]
> 关闭SIP可解，如果在乎这个目前只能关SIP
> <img alt="Screen Shot 2021-10-16 at 5 16 39 PM" width="501" src="https://user-images.githubusercontent.com/44238918/137582040-90492f0b-8f1b-457d-bd87-a8cd398af0bd.png">

能不能告知一下，怎么关sip？
