### ISSUE TITLE
在PAC模式下git无法往github提交代码

### ISSUE THREAD

**Issue by liyuhaolol** [yanue/V2rayU#968]
不知道是我哪里设置的不对还是怎么样，感觉git push的时候并没有走代理，很久很久之前的版本似乎没有这个问题，好像从3.0.0预览版开始一直有此问题。

**Comment by Invoker-liu** [comment]
https://gist.github.com/chuyik/02d0d37a49edc162546441092efae6a1
按照这个设置一下试试

**Comment by anonymousbone** [comment]
v2rayu的偏好设置内「pac」页面，自己添加上github的网址，带上https的。例如：https://github.com，保存。
这样只要是GitHub这个域名下的页面都会自动代理上，问题就解决了。
