### ISSUE TITLE
Software crashes and won't open again after adding the subscription URL

### ISSUE THREAD

**Issue by Johnny5428** [yanue/V2rayU#971]
Hi, I tried to install V2rayU and the installation was successful. I'm using the version 3.2.0. After the installation opened the software and added the subscription URL. Suddenly the software icon disappear and it never open again. I tried to open several times, But, Nothing happened. Tried to restart my Mac, Still the software doesn't open. How can i fix it?

**Comment by larvido** [comment]
I had the same issue.

版本3.2安装之后，添加完订阅链接，app的icon就不见了，像是自动关闭。重新启动app无效，重启mac无效。
