### ISSUE TITLE
全局模式不起作用

### ISSUE THREAD

**Issue by lck1115** [yanue/V2rayU#973]
用的最新版
全局模式不起作用，感觉还是在PAC下工作，即使切换为全局模式了。

**Comment by lck1115** [comment]
bug太多了，mac休眠再工作的时候，发现上不了网，必须重启下U 才行

看来还是切换回qv2ray了

**Comment by bobwang3** [comment]
> bug太多了，mac休眠再工作的时候，发现上不了网，必须重启下U 才行
> 
> 看来还是切换回qv2ray了

qv2ray已经停止维护了

**Comment by elfive** [comment]
同全局没用，只有pac有用

**Comment by integzz** [comment]
试了一圈，还是 v2rayx 稳定

**Comment by lck1115** [comment]
> 试了一圈，还是 v2rayx 稳定

v2rayx也停止更新很久了吧

**Comment by integzz** [comment]
> > 试了一圈，还是 v2rayx 稳定
> 
> 
> 
> v2rayx也停止更新很久了吧

是啊，但是不耽误用，能用才有价值

**Comment by integzz** [comment]
论更新和稳定，不考虑免费资源，都不如选 clashx

**Comment by FREAHMAN** [comment]
> 同全局没用，只有pac有用

用的是M1 的Mac嘛？我的也是全局没用，只能用pac

**Comment by ivaquero** [comment]
> 试了一圈，还是 v2rayx 稳定

收回之前的话， M1 用户感觉 3.2 的 v2rayu 用着还不错
