### ISSUE TITLE
start v2ray fail: v2ray config not found

### ISSUE THREAD

**Issue by solomsk** [yanue/V2rayU#974]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
V2rayU版本：3.2.0最新版
Mac版本：10.14.6

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
![image](https://user-images.githubusercontent.com/42059016/132436213-080e2a51-6158-46b1-a9e2-c0889816f429.png)
订阅设置，更新订阅，turn on之后，报这个错。
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by lsircode** [comment]
![image](https://user-images.githubusercontent.com/45348354/142579840-b1f17c62-c287-4e8f-a491-fb95c7f7f36e.png)
首次安装  先导入服务器就可以打开了

**Comment by zhengjiawei001** [comment]
同样的问题，现在这个软件彻底不能用了

**Comment by zhongzi** [comment]
我用两个操作解决上述问题：
 1、确保config配置文件位置内容正确，确定后重启下客户端
 2、确保订阅连接正常，刷新订阅列表，拉到服务器后即可解决上述问题

**Comment by ZhongQiyu** [comment]
> ![image](https://user-images.githubusercontent.com/45348354/142579840-b1f17c62-c287-4e8f-a491-fb95c7f7f36e.png) 首次安装 先导入服务器就可以打开了

也可以在不配置服务器的情况下完成操作

**Comment by xiaoxiaoshutong** [comment]
why?
提示  v2rayU error:missing port

**Comment by xiaoxiaoshutong** [comment]
![Uploading 1716217696089.jpg…]()

**Comment by xiaoxiaoshutong** [comment]
![1716217696089](https://github.com/yanue/V2rayU/assets/10345465/0494c899-ede7-473c-9417-3ff857f338a4)
  v2rayU error:missing port

**Comment by vskllee** [comment]
只需要更新下订阅列表就好了
