### ISSUE TITLE
MBP m1安装完成后打开日志空白，pac模式和全局都无法走代理，但是终端手动执行 ~/.v2rayu/v2ray-core/v2ray-core正常走代理

### ISSUE THREAD

**Issue by aiyogg** [yanue/V2rayU#978]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
3.2.0，MacBook Pro m1 macos 11.5.1
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
查看v2ray-core日志空白，v2rayu日志正常。pac模式和全局都无法走代理，但是终端手动执行 ~/.v2rayu/v2ray-core/v2ray-core正常走代理。
看上去是v2rayu没有正常拉起v2ray-core
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
配置从订阅拉的，不会有问题
```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。
查看core日志，打开空白，故无日志信息
```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by aiyogg** [comment]
目前写了个脚本开机后手动拉起v2ray后台运行并写日志来曲线救国😂

**Comment by CometYZ** [comment]
我也是有这样的问题，新买的air m1，还以为是网络不好，然后重启一下v2rayu就没问题了
