### ISSUE TITLE
使用ws协议的时候，Host填了无法保存

### ISSUE THREAD

**Issue by xiebruce** [yanue/V2rayU#98]
V2rayU: `1.3.1`
macOS: `10.14.4 (18E226)`

如图，当network为ws的时候，这个Host死活保存不了，但path就可以保存，而且其他配置都可以保存，就这个Host保存不了，我填的是正常的域名，应该不存在格式不对的问题：
![image](https://user-images.githubusercontent.com/13575500/59036605-39f5cb80-88a2-11e9-8635-47d6067a2e1e.png)

而且我在import那里手动写，cmd+s保存了，但切换一下又没了，相当于Manual那边有的设置会覆盖import那边，但Manual那边没有的，就不会覆盖import那边的值。

**Comment by cvenZ** [comment]
我也发现了类似的问题。。。就是host改了以后好像又是空的了

**Comment by xiebruce** [comment]
@cvenZ 是的，这个没有的话，无法伪装呀，@yanue 大佬什么时候有空修改一下呗，感谢！

**Comment by yanue** [comment]
今晚处理

**Comment by yanue** [comment]
已修复,请下载1.3.2版本

**Comment by xiebruce** [comment]
@yanue 感谢大佬，我都感觉我这速度变快了，哈哈哈……，虽然这跟速度没关系😂
