### ISSUE TITLE
M1芯片正常翻墙，但是无法代理Telegram

### ISSUE THREAD

**Issue by xixuekai1314** [yanue/V2rayU#983]
你正在使用的 V2RayU 和 Mac 版本 ？
V2RayU是3.2.0的最新版   Mac是11.6 M1芯片

你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
正常翻墙，全局模式Telegram一直转菊花圈，Telegram设置socks5代理127.0.0.1:1080也不行

请附上出错时软件输出的错误日志。
没有找到报错的日志，就是创建链接，然后链接失败，这里不是应该是服务的问题，因为win10可以正常访问telegram
config.json部分配置如下，日志在最下边

  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls",
          "http"
        ]
      },
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],

2021/10/02 10:14:34 [Info] [3480863608] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:14:35 [Info] [4211524159] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:14:38 [Info] [4274794941] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:14:44 [Info] [94924210] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2021/10/02 10:14:44 [Info] [94924210] app/dispatcher: sniffed domain: alive.github.com
2021/10/02 10:14:44 [Info] [94924210] app/dispatcher: default route for tcp:alive.github.com:443
2021/10/02 10:14:44 [Info] [94924210] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:14:44 tcp:127.0.0.1:53076 accepted tcp:alive.github.com:443 [proxy]
2021/10/02 10:14:45 [Warning] [1713713146] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.25.86.154/):  > dial tcp 104.25.86.154:443: i/o timeout] > common/retry: all retry attempts failed
2021/10/02 10:14:45 [Info] [1713713146] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/10/02 10:14:51 [Info] [3480863608] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:14:52 [Info] [4211524159] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:14:55 [Info] [4274794941] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:15:00 [Info] [94924210] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:15:07 [Info] [3480863608] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:15:08 [Info] [4211524159] transport/internet/websocket: creating connection to tcp:104.25.86.154:443
2021/10/02 10:15:12 [Info] [4274794941] transport/internet/websocket: creating connection to tcp:104.25.86.154:443

**Comment by duanso** [comment]
Intel也有此问题，外网连接正常，telegram不能走代理。

**Comment by iapplus** [comment]
> Intel也有此问题，外网连接正常，telegram不能走代理。

可能是telegram禁用代理，或者是科学上网服务器就访问不了。VPN可以

**Comment by LiebeXinlin** [comment]
我现在也是这个问题，怎么解决的

**Comment by duanso** [comment]
这是个应用设计问题，开启应用自带本地代理127.0.0.1和代理软件端口

**Comment by shijiezhou1** [comment]
<img width="936" alt="Screen Shot 2022-05-22 at 9 42 16 PM" src="https://user-images.githubusercontent.com/28111591/169698112-0b812dbd-7c8d-4c7f-b8e6-a29161417d86.png">

I added it and it still connected failed. 

我添加了socket5 还是连接不了有人知道为什么吗

**Comment by lemon891105** [comment]
M1芯片添加订阅后无法使用
