### ISSUE TITLE
一切好像都正常，但是连不上外网

### ISSUE THREAD

**Issue by fengyh13** [yanue/V2rayU#984]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

V2ray 3.2.0
mac 10.14.6
<img width="460" alt="mmexport1633168582007" src="https://user-images.githubusercontent.com/15938493/135711999-533572fd-6ab9-43b3-8c4c-459538113b33.png">
<img width="389" alt="mmexport1633168575880" src="https://user-images.githubusercontent.com/15938493/135712000-dd0c9a18-7ac8-49f0-b947-a3fac61d5716.png">

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

我自己买的搬瓦工美国vps，用v2rayu连不上外网，在安卓上用v2rayNG可以连上，能访问外网，相同的配置，在mac上访问不了外网，但是日志似乎也没报错

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
<img width="393" alt="mmexport1633168629017" src="https://user-images.githubusercontent.com/15938493/135712135-fcf3a699-cff1-4048-bef7-8015145c777a.png">
<img width="393" alt="mmexport1633168629017" src="https://user-images.githubusercontent.com/15938493/135712202-0da06b25-cba2-429b-82bc-287d1bddde37.png">
<img width="371" alt="mmexport1633168590345" src="https://user-images.githubusercontent.com/15938493/135712203-6376a835-8892-412c-ab13-c34d5f807d69.png">
<img width="1058" alt="mmexport1633168600059" src="https://user-images.githubusercontent.com/15938493/135712205-f48a4135-8678-49ee-b4be-81d89413af0c.png">

下边是服务器部署的配置
<img width="545" alt="mmexport1633168635384" src="https://user-images.githubusercontent.com/15938493/135712233-68f16b9a-d123-4795-bcff-f438bf96085d.png">

4)  请附上出错时软件输出的错误日志。
<img width="635" alt="mmexport1633168557840" src="https://user-images.githubusercontent.com/15938493/135712216-bff41649-16aa-49fe-a807-d08805f6a78b.png">

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by jbking6666** [comment]
同

**Comment by he-erduo** [comment]
同
