### ISSUE TITLE
合盖/待机后  代理失效  需重新手动配置服务器才行

### ISSUE THREAD

**Issue by zls3434** [yanue/V2rayU#987]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
MacBook Pro 13 M1 2020 (11.6 Big Sur)
V2RayU 3.2.0

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
电脑合盖或者息屏待机后, 代理失效或无指定服务器, 需要重新手动指定代理服务器才能继续使用

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by xiatonglaclary** [comment]
我也是相同问题。

**Comment by Y2zz** [comment]
我也是，而且有时候无缘无故会无法访问
