### ISSUE TITLE
在mac的使用中无法连接

### ISSUE THREAD

**Issue by yodoufuyo** [yanue/V2rayU#993]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？
macos big sur 11.6     v2rayu v3.2.0
2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
可以出速度但是选择节点后mac无法实现代理 节点都是有效的
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。

**Comment by h0lden96** [comment]
> 你直接根据完整卸载的方法进行卸载，重新安装即可。这个是因为升级big sur后有些权限没更新导致的

请问下载的具体步骤是什么？看不懂啊这个命令，是要在哪里输入？
cd ~/Library/LaunchAgents/
/bin/launchctl remove yanue.v2rayu.v2ray-core
/bin/launchctl remove yanue.v2rayu.http

rm -f ~/Library/LaunchAgents/yanue.v2rayu.v2ray-core.plist
rm -f ~/Library/Preferences/net.yanue.V2rayU.plist
rm -f ~/Library/Logs/V2rayU.log

rm -fr ~/.V2rayU/
